import type { GameList } from './types';
import { actorsBoxOfficeHints } from './hints';

export const actorsBoxOffice: GameList = {
  id: 'actors-box-office',
  name: 'Actors by Total Box Office Gross',
  description: 'Actors ranked by cumulative worldwide box office (all films)',
  topics: ['entertainment', 'movies', 'money'],
  hints: actorsBoxOfficeHints,
  valueLabel: 'Total Gross',
  items: [
    "Samuel L. Jackson", "Robert Downey Jr.", "Scarlett Johansson", "Zoe Saldana", "Chris Pratt",
    "Tom Hanks", "Chris Hemsworth", "Vin Diesel", "Bradley Cooper", "Chris Evans",
    "Tom Cruise", "Chadwick Boseman", "Dwayne Johnson", "Karen Gillan", "Benedict Cumberbatch",
    "Don Cheadle", "Josh Brolin", "Elizabeth Olsen", "Cate Blanchett", "Tom Holland",
    "Dave Bautista", "Mark Ruffalo", "Paul Rudd", "Jeremy Renner", "Sebastian Stan",
    "Idris Elba", "Morgan Freeman", "Johnny Depp", "Gary Oldman", "Hugo Weaving",
    "Orlando Bloom", "Margot Robbie", "Will Smith", "Harrison Ford", "Emma Watson",
    "Ben Stiller", "Ian McKellen", "Anthony Daniels", "Liam Neeson", "Andy Serkis",
    "Daniel Craig", "Matt Damon", "Leonardo DiCaprio", "Woody Harrelson", "Jennifer Lawrence",
    "Alan Rickman", "Eddie Murphy", "Adam Sandler", "Ryan Reynolds", "Keanu Reeves",
    "Jeff Goldblum", "Bruce Willis", "Owen Wilson", "Jason Statham", "Cameron Diaz",
    "Jack Black", "Julia Roberts", "Sandra Bullock", "Anne Hathaway", "Judy Greer",
    "Warwick Davis", "Bryce Dallas Howard", "Amanda Seyfried", "Helena Bonham Carter", "Jamie Foxx",
    "Michael Caine", "Charlize Theron", "Ben Affleck", "Amy Adams", "Rachel McAdams",
    "Jude Law", "Brad Pitt", "Timothée Chalamet", "Angelina Jolie", "Kate Winslet",
    "Will Ferrell", "John Goodman", "Gwyneth Paltrow", "Jeff Bridges", "Michael B. Jordan",
    "Josh Gad", "Jason Momoa", "Brie Larson", "Awkwafina", "Tessa Thompson",
    "Jon Favreau", "Anthony Mackie", "Simu Liu", "Oscar Isaac", "Florence Pugh",
    "Letitia Wright", "Danai Gurira", "Winston Duke", "Lupita Nyong'o", "Jacob Batalon",
    "Jon Watts", "Hailee Steinfeld", "Kumail Nanjiani", "Gemma Chan", "Brian Tyree Henry",
  ],
  values: [
    "$27.7B", "$14.4B", "$14.3B", "$14.2B", "$12.6B",
    "$11.6B", "$11.5B", "$11.2B", "$11.2B", "$11.1B",
    "$11.1B", "$10.2B", "$10.5B", "$10.2B", "$10.0B",
    "$9.8B", "$9.7B", "$9.6B", "$9.5B", "$9.4B",
    "$9.3B", "$9.2B", "$8.4B", "$8.3B", "$8.2B",
    "$8.1B", "$8.0B", "$7.9B", "$7.8B", "$7.7B",
    "$7.6B", "$7.5B", "$7.5B", "$7.4B", "$7.2B",
    "$7.0B", "$6.9B", "$6.9B", "$6.8B", "$6.7B",
    "$6.7B", "$6.6B", "$6.5B", "$6.4B", "$6.4B",
    "$6.3B", "$6.3B", "$6.2B", "$6.2B", "$6.0B",
    "$5.9B", "$5.8B", "$5.8B", "$5.7B", "$5.6B",
    "$5.5B", "$5.5B", "$5.4B", "$5.3B", "$5.2B",
    "$5.1B", "$5.0B", "$5.0B", "$4.9B", "$4.9B",
    "$4.8B", "$4.8B", "$4.7B", "$4.7B", "$4.6B",
    "$4.6B", "$4.5B", "$4.5B", "$4.4B", "$4.4B",
    "$4.3B", "$4.3B", "$4.2B", "$4.2B", "$4.1B",
    "$4.0B", "$4.0B", "$3.9B", "$3.9B", "$3.8B",
    "$3.7B", "$3.7B", "$3.6B", "$3.6B", "$3.5B",
    "$3.4B", "$3.4B", "$3.3B", "$3.3B", "$3.2B",
    "$3.1B", "$3.1B", "$3.0B", "$3.0B", "$2.9B",
  ],
};
