import type { GameList } from './types';
import { akcPopularDogBreedsHints } from './hints/akc-popular-dog-breeds';

// Source: https://www.akc.org/expert-advice/news/most-popular-dog-breeds-2024/
// AKC 2024 registration statistics (released 2025)

export const akcPopularDogBreeds: GameList = {
  id: 'akc-popular-dog-breeds',
  name: 'Most Popular Dog Breeds (AKC)',
  description: 'Top 100 dog breeds by AKC registration statistics, 2024 rankings',
  topics: ['misc'],
  hints: akcPopularDogBreedsHints,
  valueLabel: 'AKC Group',
  items: [
    "French Bulldog", "Labrador Retriever", "Golden Retriever", "German Shepherd Dog", "Poodle",
    "Dachshund", "Beagle", "Rottweiler", "Bulldog", "German Shorthaired Pointer",
    "Yorkshire Terrier", "Australian Shepherd", "Cavalier King Charles Spaniel", "Cane Corso", "Pembroke Welsh Corgi",
    "Doberman Pinscher", "Boxer", "Miniature Schnauzer", "Bernese Mountain Dog", "Shih Tzu",
    "Great Dane", "Pomeranian", "Boston Terrier", "Miniature American Shepherd", "Havanese",
    "Siberian Husky", "Chihuahua", "English Springer Spaniel", "Shetland Sheepdog", "Border Collie",
    "Brittany", "Cocker Spaniel", "Belgian Malinois", "Basset Hound", "Vizsla",
    "English Cocker Spaniel", "Maltese", "Pug", "Collie", "Mastiff",
    "West Highland White Terrier", "Shiba Inu", "Rhodesian Ridgeback", "Papillon", "Portuguese Water Dog",
    "Bichon Frise", "Newfoundland", "Dalmatian", "Australian Cattle Dog", "Whippet",
    "Wirehaired Pointing Griffon", "Chesapeake Bay Retriever", "Samoyed", "Scottish Terrier", "Weimaraner",
    "Italian Greyhound", "Giant Schnauzer", "Bloodhound", "Akita", "Cardigan Welsh Corgi",
    "German Wirehaired Pointer", "Saint Bernard", "Staffordshire Bull Terrier", "Airedale Terrier", "Boykin Spaniel",
    "Russell Terrier", "Bullmastiff", "Chinese Crested", "Nova Scotia Duck Tolling Retriever", "Biewer Terrier",
    "Cairn Terrier", "Bull Terrier", "Miniature Pinscher", "Great Pyrenees", "Soft Coated Wheaten Terrier",
    "Irish Wolfhound", "American Staffordshire Terrier", "Lagotto Romagnolo", "Alaskan Malamute", "Basenji",
    "Rat Terrier", "Greater Swiss Mountain Dog", "Chinese Shar-Pei", "Brussels Griffon", "Irish Setter",
    "Anatolian Shepherd Dog", "Pekingese", "Chow Chow", "Old English Sheepdog", "Keeshond",
    "Standard Schnauzer", "Coton de Tulear", "English Setter", "Lhasa Apso", "Dogo Argentino",
    "Dogue de Bordeaux", "Flat-Coated Retriever", "Border Terrier", "Leonberger", "Beauceron",
  ],
  values: [
    "Non-Sporting", "Sporting", "Sporting", "Herding", "Non-Sporting",
    "Hound", "Hound", "Working", "Non-Sporting", "Sporting",
    "Toy", "Herding", "Toy", "Working", "Herding",
    "Working", "Working", "Terrier", "Working", "Toy",
    "Working", "Toy", "Non-Sporting", "Herding", "Toy",
    "Working", "Toy", "Sporting", "Herding", "Herding",
    "Sporting", "Sporting", "Herding", "Hound", "Sporting",
    "Sporting", "Toy", "Toy", "Herding", "Working",
    "Terrier", "Non-Sporting", "Hound", "Toy", "Sporting",
    "Non-Sporting", "Working", "Non-Sporting", "Herding", "Hound",
    "Sporting", "Sporting", "Working", "Terrier", "Sporting",
    "Toy", "Working", "Hound", "Working", "Herding",
    "Sporting", "Working", "Terrier", "Terrier", "Sporting",
    "Terrier", "Working", "Toy", "Sporting", "Toy",
    "Terrier", "Terrier", "Toy", "Working", "Terrier",
    "Hound", "Terrier", "Sporting", "Working", "Hound",
    "Terrier", "Working", "Non-Sporting", "Toy", "Sporting",
    "Working", "Toy", "Non-Sporting", "Herding", "Non-Sporting",
    "Working", "Non-Sporting", "Sporting", "Non-Sporting", "Working",
    "Working", "Sporting", "Terrier", "Working", "Herding",
  ],
  newUntil: '2026-05-14',
};
