// Source: TasteAtlas "100 Best Cuisines in the World" (25/26 Awards)
// https://www.tasteatlas.com/best/cuisines
// Data current as of April 2026
import type { GameList } from './types';
import { bestCuisinesWorldHints } from './hints/best-cuisines-world';

export const bestCuisinesWorld: GameList = {
  id: 'best-cuisines-world',
  name: 'Best Cuisines in the World',
  description: 'Cuisines ranked by TasteAtlas user ratings (25/26 Awards)',
  topics: ['food', 'geography'],
  difficulty: 1,
  hints: bestCuisinesWorldHints,
  valueLabel: 'Region',
  newUntil: '2026-04-14',
  aliases: {
    "Italy": "Italian",
    "Greece": "Greek",
    "Peru": "Peruvian",
    "Portugal": "Portuguese",
    "Spain": "Spanish",
    "Japan": "Japanese",
    "Turkey": "Turkish",
    "China": "Chinese",
    "France": "French",
    "Indonesia": "Indonesian",
    "Mexico": "Mexican",
    "Serbia": "Serbian",
    "India": "Indian",
    "Poland": "Polish",
    "USA": "American",
    "United States": "American",
    "Vietnam": "Vietnamese",
    "Brazil": "Brazilian",
    "Croatia": "Croatian",
    "Korea": "Korean",
    "South Korea": "Korean",
    "Lebanon": "Lebanese",
    "Georgia": "Georgian",
    "Hungary": "Hungarian",
    "Colombia": "Colombian",
    "Thailand": "Thai",
    "Philippines": "Filipino",
    "Argentina": "Argentinian",
    "Germany": "German",
    "Russia": "Russian",
    "Malaysia": "Malaysian",
    "Morocco": "Moroccan",
    "Romania": "Romanian",
    "Chile": "Chilean",
    "Czech Republic": "Czech",
    "Czechia": "Czech",
    "South Africa": "South African",
    "Bulgaria": "Bulgarian",
    "Austria": "Austrian",
    "Palestine": "Palestinian",
    "Egypt": "Egyptian",
    "Ethiopia": "Ethiopian",
    "Canada": "Canadian",
    "Tunisia": "Tunisian",
    "Iran": "Iranian",
    "Ukraine": "Ukrainian",
    "Lithuania": "Lithuanian",
    "Syria": "Syrian",
    "Algeria": "Algerian",
    "Netherlands": "Dutch",
    "Holland": "Dutch",
    "Saudi Arabia": "Saudi",
    "Ecuador": "Ecuadorian",
    "England": "English",
    "UK": "English",
    "Britain": "English",
    "Sweden": "Swedish",
    "Bosnia": "Bosnian and Herzegovinian",
    "Herzegovina": "Bosnian and Herzegovinian",
    "Macedonia": "Macedonian",
    "North Macedonia": "Macedonian",
    "Venezuela": "Venezuelan",
    "Denmark": "Danish",
    "Trinidad": "Trinidadian",
    "Trinidad and Tobago": "Trinidadian",
    "Nicaragua": "Nicaraguan",
    "Puerto Rico": "Puerto Rican",
    "Libya": "Libyan",
    "Bangladesh": "Bengali",
    "Australia": "Australian",
    "Sri Lanka": "Sri Lankan",
    "Finland": "Finnish",
    "Jordan": "Jordanian",
    "Bolivia": "Bolivian",
    "Norway": "Norwegian",
    "Azerbaijan": "Azerbaijani",
    "Belgium": "Belgian",
    "Cuba": "Cuban",
    "Switzerland": "Swiss",
    "Iraq": "Iraqi",
    "Uruguay": "Uruguayan",
    "Pakistan": "Pakistani",
    "Afghanistan": "Afghan",
    "Slovakia": "Slovak",
    "Eritrea": "Eritrean",
    "Albania": "Albanian",
    "Scotland": "Scottish",
    "Belarus": "Belarusian",
    "Ireland": "Irish",
    "Haiti": "Haitian",
    "Dominican Republic": "Dominican",
    "Paraguay": "Paraguayan",
    "Slovenia": "Slovenian",
    "Costa Rica": "Costa Rican",
    "Bahamas": "Bahamian",
    "Armenia": "Armenian",
    "Latvia": "Latvian",
    "Estonia": "Estonian",
    "Singapore": "Singaporean",
    "Montenegro": "Montenegrin",
    "Guatemala": "Guatemalan",
    "Israel": "Israeli",
    "Malta": "Maltese",
    "Nigeria": "Nigerian",
    "Laos": "Lao",
    "Kenya": "Kenyan",
    "Kazakhstan": "Kazakhstani",
    "Qatar": "Qatari",
    "Cyprus": "Cypriot",
  },
  items: [
    "Italian",
    "Greek",
    "Peruvian",
    "Portuguese",
    "Spanish",
    "Japanese",
    "Turkish",
    "Chinese",
    "French",
    "Indonesian",
    "Mexican",
    "Serbian",
    "Indian",
    "Polish",
    "American",
    "Vietnamese",
    "Brazilian",
    "Croatian",
    "Korean",
    "Lebanese",
    "Georgian",
    "Hungarian",
    "Colombian",
    "Thai",
    "Filipino",
    "Argentinian",
    "German",
    "Russian",
    "Malaysian",
    "Moroccan",
    "Romanian",
    "Chilean",
    "Czech",
    "South African",
    "Bulgarian",
    "Austrian",
    "Palestinian",
    "Egyptian",
    "Ethiopian",
    "Canadian",
    "Tunisian",
    "Iranian",
    "Ukrainian",
    "Lithuanian",
    "Syrian",
    "Algerian",
    "Dutch",
    "Saudi",
    "Ecuadorian",
    "English",
    "Swedish",
    "Bosnian and Herzegovinian",
    "Macedonian",
    "Venezuelan",
    "Danish",
    "Trinidadian",
    "Nicaraguan",
    "Puerto Rican",
    "Libyan",
    "Bengali",
    "Australian",
    "Sri Lankan",
    "Finnish",
    "Jordanian",
    "Bolivian",
    "Norwegian",
    "Azerbaijani",
    "Belgian",
    "Cuban",
    "Swiss",
    "Iraqi",
    "Uruguayan",
    "Pakistani",
    "Afghan",
    "Slovak",
    "Eritrean",
    "Albanian",
    "Scottish",
    "Belarusian",
    "Irish",
    "Haitian",
    "Dominican",
    "Paraguayan",
    "Slovenian",
    "Costa Rican",
    "Bahamian",
    "Armenian",
    "Latvian",
    "Estonian",
    "Singaporean",
    "Montenegrin",
    "Guatemalan",
    "Israeli",
    "Maltese",
    "Nigerian",
    "Lao",
    "Kenyan",
    "Kazakhstani",
    "Qatari",
    "Cypriot",
  ],
  values: [
    "Southern Europe", "Southern Europe", "South America", "Southern Europe", "Southern Europe",
    "East Asia", "Western Asia", "East Asia", "Western Europe", "Southeast Asia",
    "North America", "Southern Europe", "South Asia", "Central Europe", "North America",
    "Southeast Asia", "South America", "Southern Europe", "East Asia", "Western Asia",
    "Western Asia", "Central Europe", "South America", "Southeast Asia", "Southeast Asia",
    "South America", "Central Europe", "Eastern Europe", "Southeast Asia", "North Africa",
    "Eastern Europe", "South America", "Central Europe", "Southern Africa", "Eastern Europe",
    "Central Europe", "Western Asia", "North Africa", "East Africa", "North America",
    "North Africa", "Western Asia", "Eastern Europe", "Northern Europe", "Western Asia",
    "North Africa", "Western Europe", "Western Asia", "South America", "Northern Europe",
    "Northern Europe", "Southern Europe", "Southern Europe", "South America", "Northern Europe",
    "Caribbean", "Central America", "Caribbean", "North Africa", "South Asia",
    "Oceania", "South Asia", "Northern Europe", "Western Asia", "South America",
    "Northern Europe", "Western Asia", "Western Europe", "Caribbean", "Western Europe",
    "Western Asia", "South America", "South Asia", "South Asia", "Central Europe",
    "East Africa", "Southern Europe", "Northern Europe", "Eastern Europe", "Northern Europe",
    "Caribbean", "Caribbean", "South America", "Central Europe", "Central America",
    "Caribbean", "Western Asia", "Northern Europe", "Northern Europe", "Southeast Asia",
    "Southern Europe", "Central America", "Western Asia", "Southern Europe", "West Africa",
    "Southeast Asia", "East Africa", "Central Asia", "Western Asia", "Southern Europe",
  ],
};
