import type { GameList } from './types';
import { bestSellingVideoGamesHints } from './hints';

export const bestSellingVideoGames: GameList = {
  id: 'best-selling-video-games',
  name: 'Best Selling Video Games',
  description: 'Video games ranked by all-time units sold (Wikipedia)',
  topics: ['entertainment'],
  hints: bestSellingVideoGamesHints,
  valueLabel: 'Copies Sold',
  items: [
    "Minecraft", "Grand Theft Auto V", "Tetris", "Wii Sports", "PUBG: Battlegrounds",
    "Mario Kart 8", "Red Dead Redemption 2", "Overwatch", "The Witcher 3", "Pokémon Red/Blue",
    "Terraria", "Pac-Man", "Human: Fall Flat", "Super Mario Bros.", "Mario Kart Wii",
    "Super Smash Bros. Ultimate", "The Legend of Zelda: Breath of the Wild", "Call of Duty: Modern Warfare", "Wii Sports Resort", "New Super Mario Bros.",
    "New Super Mario Bros. Wii", "The Elder Scrolls V: Skyrim", "Diablo III", "Call of Duty: Modern Warfare 3", "Pokémon Gold/Silver",
    "Duck Hunt", "The Legend of Zelda: Tears of the Kingdom", "Wii Fit", "Wii Fit Plus", "Call of Duty: Black Ops",
    "Grand Theft Auto: San Andreas", "Call of Duty: Black Ops II", "Animal Crossing: New Horizons", "Call of Duty: Modern Warfare 2", "Super Mario Odyssey",
    "Super Mario World", "Grand Theft Auto IV", "Pokémon Sword/Shield", "FIFA 18", "Kinect Adventures!",
    "Call of Duty: WWII", "Pokémon Diamond/Pearl", "Pokémon Sun/Moon", "Pokémon Ruby/Sapphire", "New Super Mario Bros. 2",
    "Borderlands 2", "The Last of Us", "FIFA 17", "Spider-Man", "Halo: Combat Evolved",
    "Pokémon Scarlet/Violet", "Call of Duty: Ghosts", "Call of Duty: Black Ops III", "Super Mario Bros. 3", "Battlefield 1",
    "Nintendogs", "Star Wars Battlefront", "The Legend of Zelda: Ocarina of Time", "Lego Star Wars: The Complete Saga", "Need for Speed: Most Wanted",
    "Brain Age", "Super Smash Bros. Brawl", "Pokémon X/Y", "Just Dance 2017", "FIFA 16",
    "Uncharted 4", "God of War", "Final Fantasy VII", "Resident Evil 5", "Mario Party 8",
    "Sonic the Hedgehog", "Battlefield 3", "NBA 2K21", "Pokémon Black/White", "Super Mario 64",
    "Halo 3", "Mario Kart DS", "Halo 2", "Gran Turismo 3", "Donkey Kong Country",
    "Splatoon 2", "Fable II", "Guitar Hero III", "Assassin's Creed II", "Crash Bandicoot",
    "Pokémon Let's Go Pikachu/Eevee", "The Sims 3", "Destiny", "Gran Turismo", "Metal Gear Solid",
    "Tomb Raider II", "Mortal Kombat 11", "Super Mario Galaxy", "Gran Turismo 4", "Forza Horizon 5",
    "Tom Clancy's The Division", "Halo Reach", "FIFA 15", "Just Dance 3", "Resident Evil 2",
  ],
  values: [
    "300M", "205M", "202M", "83M", "75M",
    "72M", "65M", "50M", "50M", "47M",
    "44M", "43M", "40M", "40M", "37M",
    "35M", "35M", "34M", "33M", "30M",
    "30M", "30M", "30M", "30M", "29M",
    "28M", "28M", "28M", "28M", "28M",
    "28M", "27M", "27M", "27M", "27M",
    "26M", "26M", "25M", "24M", "24M",
    "24M", "24M", "24M", "23M", "23M",
    "22M", "22M", "22M", "20M", "20M",
    "20M", "19M", "19M", "18M", "18M",
    "17M", "16M", "16M", "16M", "16M",
    "16M", "16M", "15M", "15M", "15M",
    "15M", "14M", "14M", "14M", "14M",
    "14M", "14M", "13M", "13M", "13M",
    "13M", "13M", "13M", "13M", "13M",
    "12M", "12M", "12M", "12M", "12M",
    "12M", "12M", "12M", "12M", "11M",
    "11M", "11M", "11M", "11M", "11M",
    "10M", "10M", "10M", "10M", "10M",
  ],
};
