// Source: TasteAtlas "100 Best Dishes in the World" (25/26 Awards)
// https://www.tasteatlas.com/best/dishes
// Data current as of April 2026
import type { GameList } from './types';
import { bestDishesWorldHints } from './hints/best-dishes-world';

export const bestDishesWorld: GameList = {
  id: 'best-dishes-world',
  name: 'Best Dishes in the World',
  description: 'Dishes ranked by TasteAtlas user ratings (25/26 Awards)',
  topics: ['food'],
  hints: bestDishesWorldHints,
  valueLabel: 'Origin',
  newUntil: '2026-05-14',
  aliases: {
    "Neapolitan Pizza": "Pizza Napoletana",
    "Florentine Steak": "Bistecca alla Fiorentina",
    "Peking Duck": "Beijing kao ya (Peking duck)",
    "Beef Pho": "Phở bò (Beef pho)",
    "Butter Chicken": "Murgh makhani (Butter chicken)",
    "Chicken Karahi": "Murgh karahi (Chicken karahi)",
    "Iskender Kebab": "İskender kebap",
    "Adana Kebab": "Adana kebap",
    "Birria Tacos": "Quesabirria (Birria tacos)",
    "Lobster Roll": "Maine-style Lobster Roll",
    "Salmon Soup": "Lohikeitto (Salmon soup)",
    "Finnish Fish Soup": "Kalakeitto (Finnish fish soup)",
    "Grilled Octopus": "Chtapodi sti schara (Grilled octopus)",
    "Sri Lankan Rice and Curry": "Bath kulu badhu (Sri Lankan rice and curry)",
    "Biang Biang Noodles": "Yóupō miàn (Biáng biáng noodles)",
    "Japanese Curry": "Karē",
    "Katsu Curry": "Katsu karē",
    "Pho": "Phở bò (Beef pho)",
    "Pho Bo": "Phở bò (Beef pho)",
    "Biryani": "Hyderabadi biryani",
    "Ramen": "Tonkotsu ramen",
    "Tonkotsu Ramen": "Tonkotsu ramen",
    "Yokohama Ramen": "Yokohama-Style Ramen",
    "Kebap": "Adana kebap",
    "Kebab": "Adana kebap",
    "BBQ": "Central Texas-Style Barbecue",
    "Barbecue": "Central Texas-Style Barbecue",
    "Texas BBQ": "Central Texas-Style Barbecue",
    "Memphis BBQ": "Memphis-Style Barbecue",
    "Panang Curry": "Phanaeng Curry",
    "Penang Curry": "Phanaeng Curry",
    "Korean BBQ": "Samgyeopsal",
    "Galbi Ribs": "Galbi",
    "Short Ribs": "Galbi",
    "Tuna Sushi": "Maguro nigiri sushi",
    "Salmon Sushi": "Sake nigiri sushi",
    "Scallop Sushi": "Hotate nigiri sushi",
    "Sushi": "Maguro nigiri sushi",
    "Nigiri": "Maguro nigiri sushi",
    "Hot Pot": "Taiwanese Hot Pot",
    "Taiwanese Hot Pot": "Taiwanese Hot Pot",
    "Bolognese": "Tagliatelle al ragù alla Bolognese",
    "Lasagna": "Lasagne alla Bolognese",
    "Lasagne": "Lasagne alla Bolognese",
    "Khao Soi": "Khao soi",
    "Pad Krapow": "Phat kaphrao",
    "Pad Kaprao": "Phat kaphrao",
    "Basil Stir Fry": "Phat kaphrao",
    "Pork Belly": "Samgyeopsal",
    "Moqueca": "Moqueca Baiana",
    "Ceviche": "Ceviche de conchas negras",
  },
  items: [
    "Vori-vori",
    "Pizza Napoletana",
    "Tajarin al tartufo bianco d'Alba",
    "Sate kambing",
    "Oltu cağ kebabı",
    "Kontosouvli",
    "Arroz tapado",
    "Komplet lepinja",
    "Quesabirria (Birria tacos)",
    "Pappardelle al cinghiale",
    "Central Texas-Style Barbecue",
    "Bath kulu badhu (Sri Lankan rice and curry)",
    "Seco de cabrito",
    "Beyran çorbası",
    "Picanha",
    "Siu mei",
    "Amritsari kulcha",
    "Bistecca alla Fiorentina",
    "Pollo a la brasa",
    "Empanadas Tucumanas",
    "Leitão da bairrada",
    "Yokohama-Style Ramen",
    "Cochinita pibil",
    "Maguro nigiri sushi",
    "Païdakia",
    "Beyti kebab",
    "Tibs",
    "Cordero al palo",
    "Soto Betawi",
    "Phanaeng Curry",
    "Khao soi",
    "Châteaubriand",
    "Çökertme kebabı",
    "Costela",
    "Arroz con bogavante",
    "Tagliata di manzo",
    "Tonkotsu ramen",
    "Hünkar beğendi",
    "Bistec a lo pobre",
    "Inasal na manok",
    "Ceviche de conchas negras",
    "Sate Padang",
    "Asado",
    "Tom kha gai",
    "Jalea",
    "Maine-style Lobster Roll",
    "Hotate nigiri sushi",
    "İskender kebap",
    "Parmigiana alla napoletana",
    "Carne de porco à Alentejana",
    "Lohikeitto (Salmon soup)",
    "Sinigang na baboy",
    "Kuzu şiş",
    "Strapatsada",
    "Camarones el mojo de ajo",
    "Tagliatelle al ragù alla Bolognese",
    "Adana kebap",
    "Giouvetsi",
    "Cordero asado",
    "Sinigang",
    "Alinazik kebab",
    "Sirnica",
    "Taiwanese Hot Pot",
    "Murgh karahi (Chicken karahi)",
    "Tanjia",
    "Murgh makhani (Butter chicken)",
    "Karē",
    "Gambas al ajillo",
    "Sake nigiri sushi",
    "Risotto ai funghi porcini",
    "Linguine allo scoglio",
    "Hyderabadi biryani",
    "Galbi",
    "Katsu karē",
    "Pernil",
    "Gunkanmaki",
    "Fritto misto di pesce",
    "Burnt Ends",
    "Kabab torsh",
    "Kalakeitto (Finnish fish soup)",
    "Bún bò nam bộ",
    "Beijing kao ya (Peking duck)",
    "Phở bò (Beef pho)",
    "Lomo saltado",
    "Shahi paneer",
    "Mtsvadi",
    "Paçanga böreği",
    "Memphis-Style Barbecue",
    "Carbonara",
    "Lasagne alla Bolognese",
    "Khachapuri",
    "Phat kaphrao",
    "Polvo à Lagareiro",
    "Chtapodi sti schara (Grilled octopus)",
    "Gambas à la plancha",
    "Samgyeopsal",
    "Yóupō miàn (Biáng biáng noodles)",
    "Moqueca Baiana",
    "Sopa de lima",
    "Sopa da pedra",
  ],
  values: [
    "Soup, Paraguay", "Pizza, Italy", "Pasta, Italy", "Street Food, Indonesia", "Lamb, Turkiye",
    "Pork, Greece", "Rice, Peru", "Breakfast, Serbia", "Street Food, Mexico", "Pasta, Italy",
    "Barbecue, USA", "Rice, Sri Lanka", "Stew, Peru", "Soup, Turkiye", "Beef, Brazil",
    "Meat, China", "Flatbread, India", "Beef, Italy", "Chicken, Peru", "Pastry, Argentina",
    "Pork, Portugal", "Noodle, Japan", "Pork, Mexico", "Rice, Japan", "Lamb, Greece",
    "Meat, Turkiye", "Stir-fry, Ethiopia", "Lamb, Chile", "Soup, Indonesia", "Stew, Thailand",
    "Noodle, Thailand", "Beef, France", "Veal, Turkiye", "Beef, Brazil", "Rice, Spain",
    "Beef, Italy", "Noodle, Japan", "Stew, Turkiye", "Beef, Peru", "Chicken, Philippines",
    "Clam, Peru", "Beef, Indonesia", "Barbecue, Argentina", "Soup, Thailand", "Seafood, Peru",
    "Sandwich, USA", "Rice, Japan", "Lamb, Turkiye", "Casserole, Italy", "Pork, Portugal",
    "Soup, Finland", "Soup, Philippines", "Lamb, Turkiye", "Egg, Greece", "Shrimp, Mexico",
    "Pasta, Italy", "Lamb, Turkiye", "Casserole, Greece", "Lamb, Spain", "Soup, Philippines",
    "Lamb, Turkiye", "Pastry, Bosnia", "Soup, Taiwan", "Chicken, Pakistan", "Lamb, Morocco",
    "Stew, India", "Stew, Japan", "Shrimp, Spain", "Rice, Japan", "Rice, Italy",
    "Pasta, Italy", "Rice, India", "Beef, South Korea", "Meat, Japan", "Pork, Puerto Rico",
    "Rice, Japan", "Seafood, Italy", "Beef, USA", "Beef, Iran", "Soup, Finland",
    "Noodle, Vietnam", "Duck, China", "Soup, Vietnam", "Stir-fry, Peru", "Stew, India",
    "Meat, Georgia", "Pastry, Turkiye", "Barbecue, USA", "Pasta, Italy", "Pasta, Italy",
    "Pie, Georgia", "Stir-fry, Thailand", "Octopus, Portugal", "Octopus, Greece", "Shrimp, Spain",
    "Pork, South Korea", "Noodle, China", "Stew, Brazil", "Soup, Mexico", "Soup, Portugal",
  ],
};
