import type { GameList } from './types';
import { bestSellingAlbumsHints } from './hints';

export const bestSellingAlbums: GameList = {
  id: 'best-selling-albums',
  name: 'Best-Selling Albums',
  description: 'Albums ranked by worldwide sales (Wikipedia / RIAA / IFPI)',
  topics: ['music'],
  difficulty: 2,
  hints: bestSellingAlbumsHints,
  valueLabel: 'Sales',
  items: [
    "Thriller - Michael Jackson", "Back in Black - AC/DC", "The Bodyguard - Whitney Houston", "The Dark Side of the Moon - Pink Floyd", "Their Greatest Hits (1971-1975) - Eagles",
    "Hotel California - Eagles", "Come On Over - Shania Twain", "Rumours - Fleetwood Mac", "Bat Out of Hell - Meat Loaf", "Saturday Night Fever - Bee Gees",
    "Led Zeppelin IV - Led Zeppelin", "Bad - Michael Jackson", "Jagged Little Pill - Alanis Morissette", "Dirty Dancing - Soundtrack", "Falling into You - Celine Dion",
    "Dangerous - Michael Jackson", "21 - Adele", "1 - The Beatles", "The Black Album - Metallica", "Let's Talk About Love - Celine Dion",
    "Legend - Bob Marley and the Wailers", "Nevermind - Nirvana", "Appetite for Destruction - Guns N' Roses", "Born in the U.S.A. - Bruce Springsteen", "Gold: Greatest Hits - ABBA",
    "Brothers in Arms - Dire Straits", "The Immaculate Collection - Madonna", "Supernatural - Santana", "The Wall - Pink Floyd", "Sgt. Pepper's Lonely Hearts Club Band - The Beatles",
    "Abbey Road - The Beatles", "Come Away with Me - Norah Jones", "Grease - Soundtrack", "Music Box - Mariah Carey", "The Eminem Show - Eminem",
    "Titanic - Soundtrack", "Unplugged - Eric Clapton", "Greatest Hits - Queen", "...Baby One More Time - Britney Spears", "Slippery When Wet - Bon Jovi",
    "Greatest Hits - Journey", "Whitney Houston - Whitney Houston", "No Jacket Required - Phil Collins", "The Marshall Mathers LP - Eminem", "Hybrid Theory - Linkin Park",
    "The Joshua Tree - U2", "Purple Rain - Prince", "Tapestry - Carole King", "True Blue - Madonna", "Faith - George Michael",
    "Bridge over Troubled Water - Simon & Garfunkel", "Greatest Hits - Elton John", "Millennium - Backstreet Boys", "25 - Adele", "Spice - Spice Girls",
    "The Sign - Ace of Base", "American Idiot - Green Day", "HIStory - Michael Jackson", "All the Way... A Decade of Song - Celine Dion", "(What's the Story) Morning Glory? - Oasis",
    "The Score - Fugees", "Like a Virgin - Madonna", "Cross Road - Bon Jovi", "Dookie - Green Day", "Cracked Rear View - Hootie & the Blowfish",
    "Elvis' Christmas Album - Elvis Presley", "Boston - Boston", "Daydream - Mariah Carey", "Whitney - Whitney Houston", "The Woman in Me - Shania Twain",
    "Oops!... I Did It Again - Britney Spears", "Hysteria - Def Leppard", "The Miseducation of Lauryn Hill - Lauryn Hill", "Tracy Chapman - Tracy Chapman", "Off the Wall - Michael Jackson",
    "Can't Slow Down - Lionel Richie", "The Colour of My Love - Celine Dion", "Wish You Were Here - Pink Floyd", "Romanza - Andrea Bocelli", "Back to Black - Amy Winehouse",
    "Confessions - Usher", "The Beatles (White Album) - The Beatles", "Achtung Baby - U2", "Use Your Illusion II - Guns N' Roses", "Ten - Pearl Jam",
    "The Lion King - Soundtrack", "Ropin' the Wind - Garth Brooks", "No Fences - Garth Brooks", "The Beatles 1962-1966 - The Beatles", "Bat Out of Hell II - Meat Loaf",
    "Some Gave All - Billy Ray Cyrus", "Yourself or Someone Like You - Matchbox Twenty", "Pieces of You - Jewel", "Vs. - Pearl Jam", "Emotions - Mariah Carey",
    "Goodbye Yellow Brick Road - Elton John", "A Night at the Opera - Queen", "News of the World - Queen", "Please Hammer Don't Hurt 'Em - MC Hammer", "Spiceworld - Spice Girls",
  ],
  values: [
    "70M", "50M", "45M", "45M", "44M",
    "42M", "40M", "40M", "40M", "40M",
    "37M", "35M", "33M", "32M", "32M",
    "32M", "31M", "31M", "31M", "31M",
    "30M", "30M", "30M", "30M", "30M",
    "30M", "30M", "30M", "30M", "30M",
    "30M", "28M", "28M", "28M", "27M",
    "27M", "26M", "25M", "25M", "25M",
    "25M", "25M", "25M", "25M", "25M",
    "25M", "25M", "25M", "25M", "25M",
    "25M", "24M", "24M", "23M", "23M",
    "23M", "23M", "22M", "22M", "22M",
    "22M", "21M", "21M", "20M", "20M",
    "20M", "20M", "20M", "20M", "20M",
    "20M", "20M", "20M", "20M", "20M",
    "20M", "20M", "20M", "20M", "20M",
    "19M", "19M", "18M", "17M", "17M",
    "17M", "17M", "17M", "16M", "16M",
    "15M", "15M", "15M", "15M", "15M",
    "15M", "15M", "15M", "15M", "14M",
  ],
  newUntil: '2026-05-14',
};
