// Source: US sales data (Statista, YouGov), consumer popularity rankings, market research
// Rankings based on US retail sales volume and brand recognition
import type { GameList } from './types';
import { bestSellingCandyHints } from './hints/best-selling-candy';

export const bestSellingCandy: GameList = {
  id: 'best-selling-candy',
  name: 'Best-Selling Candy & Chocolate in the US',
  description: 'Candy and chocolate products ranked by US sales and popularity',
  topics: ['food', 'business'],
  difficulty: 1,
  hints: bestSellingCandyHints,
  valueLabel: 'Manufacturer',
  size: 100,
  newUntil: '2026-05-14',
  items: [
    "Reese's Peanut Butter Cups",
    "M&M's",
    "Snickers",
    "Kit Kat",
    "M&M's Peanut",
    "Hershey's Kisses",
    "Twix",
    "Hershey's Milk Chocolate Bar",
    "Milky Way",
    "Skittles",
    "Starburst",
    "Sour Patch Kids",
    "Jolly Rancher",
    "Nerds",
    "Twizzlers",
    "Butterfinger",
    "York Peppermint Pattie",
    "3 Musketeers",
    "Almond Joy",
    "Mounds",
    "Baby Ruth",
    "Crunch Bar",
    "Haribo Goldbears",
    "Swedish Fish",
    "Tootsie Roll",
    "Tootsie Pop",
    "Whoppers",
    "PayDay",
    "Milk Duds",
    "Rolo",
    "SweeTarts",
    "Airheads",
    "100 Grand",
    "Junior Mints",
    "Dots",
    "Mike and Ike",
    "Hot Tamales",
    "Peeps",
    "Reese's Pieces",
    "Reese's Take 5",
    "Mr. Goodbar",
    "Dove Chocolate",
    "Smarties",
    "Laffy Taffy",
    "Nerds Gummy Clusters",
    "Lemonhead",
    "Good & Plenty",
    "Heath Bar",
    "5th Avenue",
    "Whatchamacallit",
    "Turtles",
    "Raisinets",
    "Goobers",
    "Sno-Caps",
    "Jujyfruits",
    "Chunky",
    "Boston Baked Beans",
    "PEZ",
    "Life Savers",
    "Runts",
    "Pixy Stix",
    "Fun Dip",
    "Pop Rocks",
    "Ring Pop",
    "Push Pop",
    "Baby Bottle Pop",
    "Dum Dums",
    "Charms Blow Pops",
    "Charleston Chew",
    "Andes Mints",
    "Sugar Daddy",
    "Ferrero Rocher",
    "Kinder Bueno",
    "Nutella",
    "Tic Tac",
    "Mentos",
    "Russell Stover",
    "Cadbury Dairy Milk",
    "Cadbury Creme Egg",
    "Toblerone",
    "Godiva",
    "Lindt Lindor Truffles",
    "Ghirardelli Chocolate",
    "Werther's Original",
    "Riesen",
    "Goo Goo Cluster",
    "Pocky",
    "Hi-Chew",
    "Warheads",
    "Toxic Waste",
    "Trolli",
    "Black Forest Gummies",
    "Brach's Candy Corn",
    "Now and Later",
    "Goldenberg's Peanut Chews",
    "Skor",
    "Zero Bar",
    "Mallo Cup",
    "Chuckles",
    "Terry's Chocolate Orange",
  ],
  values: [
    "Hershey", "Mars", "Mars", "Hershey", "Mars",
    "Hershey", "Mars", "Hershey", "Mars", "Mars",
    "Mars", "Mondelēz", "Hershey", "Ferrara", "Hershey",
    "Ferrara", "Hershey", "Mars", "Hershey", "Hershey",
    "Ferrara", "Ferrara", "Haribo", "Mondelēz", "Tootsie Roll",
    "Tootsie Roll", "Hershey", "Hershey", "Hershey", "Hershey",
    "Ferrara", "Perfetti Van Melle", "Ferrara", "Tootsie Roll", "Tootsie Roll",
    "Just Born", "Just Born", "Just Born", "Hershey", "Hershey",
    "Hershey", "Mars", "Ce De Candy", "Ferrara", "Ferrara",
    "Ferrara", "Hershey", "Hershey", "Hershey", "Hershey",
    "DeMet's", "Ferrara", "Ferrara", "Ferrara", "Ferrara",
    "Ferrara", "Ferrara", "PEZ Candy", "Mars Wrigley", "Ferrara",
    "Ferrara", "Ferrara", "Zeta Espacial", "Bazooka Candy", "Bazooka Candy",
    "Bazooka Candy", "Spangler", "Tootsie Roll", "Tootsie Roll", "Tootsie Roll",
    "Tootsie Roll", "Ferrero", "Ferrero", "Ferrero", "Ferrero",
    "Perfetti Van Melle", "Lindt & Sprüngli", "Mondelēz", "Mondelēz", "Mondelēz",
    "Yıldız Holding", "Lindt & Sprüngli", "Lindt & Sprüngli", "Storck", "Storck",
    "Standard Candy", "Ezaki Glico", "Morinaga", "Impact Confections", "Candy Dynamics",
    "Ferrara", "Ferrara", "Ferrara", "Ferrara",
    "Just Born", "Hershey", "Hershey", "Boyer Candy", "Ferrara",
    "Carambar & Co",
  ],
};
