import type { GameList } from './types';
import { bestSellingToysHints } from './hints';

// Sources:
// - https://www.nowblitz.com/blog/15-best-selling-toys-in-history/
// - https://moneyinc.com/best-selling-toys/
// - https://smartbuy.alibaba.com/best-selling/best-selling-toys-of-all-time
// - https://www.accio.com/business/what_is_the_best_selling_toy_ever
// - https://www.accio.com/business/best_selling_board_games_of_all_time
// - https://en.wikipedia.org/wiki/Uno_(card_game)
// - https://en.wikipedia.org/wiki/Play-Doh
// - https://en.wikipedia.org/wiki/Rubik%27s_Cube
// - https://en.wikipedia.org/wiki/Scrabble
// - https://www.museumofplay.org (National Toy Hall of Fame)
// - https://en.wikipedia.org/wiki/List_of_best-selling_game_consoles
// Notes on ranking methodology:
// - Physical toy & board game sales only (no video game software)
// - LEGO piece counts converted to set-equivalent estimates
// - "Chess" and "Checkers" encompass all generic manufacturers
// - Play-Doh counts individual cans sold (3B+), not sets
// - Rankings 1-10 are by verified unit counts; 11-100 are by industry consensus,
//   cultural impact, and corroborated multi-source estimates

export const bestSellingToys: GameList = {
  id: 'best-selling-toys',
  name: 'Best Selling Toys & Board Games',
  description: 'Physical toys, games, and playsets ranked by all-time units sold',
  topics: ['entertainment', 'misc'],
  difficulty: 2,
  hints: bestSellingToysHints,
  valueLabel: 'Units Sold',
  aliases: {
    'Lego': 'LEGO',
    'lego': 'LEGO',
    'Hot wheels': 'Hot Wheels',
    'hot wheels': 'Hot Wheels',
    'Play Doh': 'Play-Doh',
    'play doh': 'Play-Doh',
    'playdoh': 'Play-Doh',
    'Rubiks Cube': "Rubik's Cube",
    'rubiks cube': "Rubik's Cube",
    "rubik's cube": "Rubik's Cube",
    'GI Joe': 'G.I. Joe',
    'gi joe': 'G.I. Joe',
    'Monopoly board game': 'Monopoly',
    'monopoly board game': 'Monopoly',
    'checkers game': 'Checkers',
    'draughts': 'Checkers',
    'Draughts': 'Checkers',
    'uno card game': 'Uno',
    'Uno card game': 'Uno',
    'UNO': 'Uno',
    'uno': 'Uno',
    'frisbee': 'Frisbee',
    'yo yo': 'Yo-Yo',
    'yoyo': 'Yo-Yo',
    'Mr Potato Head': 'Mr. Potato Head',
    'mr potato head': 'Mr. Potato Head',
    'silly putty': 'Silly Putty',
    'etch a sketch': 'Etch A Sketch',
    'Etch-A-Sketch': 'Etch A Sketch',
    'lite brite': 'Lite-Brite',
    'easy bake oven': 'Easy-Bake Oven',
    'easy-bake': 'Easy-Bake Oven',
    'connect 4': 'Connect Four',
    'Connect 4': 'Connect Four',
    'hungry hippos': 'Hungry Hungry Hippos',
    'Hungry Hippos': 'Hungry Hungry Hippos',
    'Cluedo': 'Clue',
    'cluedo': 'Clue',
    'nerf gun': 'Nerf',
    'Nerf gun': 'Nerf',
    'nerf blaster': 'Nerf',
    'super soaker water gun': 'Super Soaker',
    'tmnt': 'Teenage Mutant Ninja Turtles',
    'TMNT': 'Teenage Mutant Ninja Turtles',
    'ninja turtles': 'Teenage Mutant Ninja Turtles',
    'Ninja Turtles': 'Teenage Mutant Ninja Turtles',
    'my little pony toys': 'My Little Pony',
    'pokemon cards': 'Pokémon Trading Cards',
    'Pokemon Trading Cards': 'Pokémon Trading Cards',
    'pokemon trading cards': 'Pokémon Trading Cards',
    'game boy': 'Game Boy',
    'gameboy': 'Game Boy',
    'nintendo ds': 'Nintendo DS',
    'wii console': 'Nintendo Wii',
    'Nintendo Wii': 'Nintendo Wii',
    'american girl': 'American Girl Dolls',
    'bratz': 'Bratz Dolls',
    'cabbage patch': 'Cabbage Patch Kids',
    'tamagotchi virtual pet': 'Tamagotchi',
    'beanie baby': 'Beanie Babies',
    'star wars toys': 'Star Wars action figures',
    'kenner star wars': 'Star Wars action figures',
    'transformers toys': 'Transformers',
    'he man': 'He-Man',
    'masters of the universe': 'He-Man',
    'Masters of the Universe': 'He-Man',
    'tonka truck': 'Tonka Trucks',
    'tonka': 'Tonka Trucks',
    'lincoln log': 'Lincoln Logs',
    'candy land': 'Candy Land',
    'candyland': 'Candy Land',
    'chutes and ladders': 'Chutes and Ladders',
    'snakes and ladders': 'Chutes and Ladders',
    'rock em sock em': "Rock 'Em Sock 'Em Robots",
    'rock em sock em robots': "Rock 'Em Sock 'Em Robots",
    'trivial pursuit game': 'Trivial Pursuit',
    'hacky sack': 'Hacky Sack',
    'hula hoop': 'Hula Hoop',
    'pogo stick': 'Pogo Stick',
    'fisher price little people': 'Fisher-Price Little People',
    'fisher price': 'Fisher-Price Little People',
    'k nex': "K'Nex",
    'k-nex': "K'Nex",
    'erector set': 'Erector Set',
    'tinkertoys': 'Tinkertoy',
    'tinker toys': 'Tinkertoy',
    'thomas trains': 'Thomas the Tank Engine',
    'thomas train': 'Thomas the Tank Engine',
    'brio trains': 'Brio',
    'rainbow loom bands': 'Rainbow Loom',
    'fidget spinner toy': 'Fidget Spinner',
    'dungeons and dragons': 'Dungeons & Dragons',
    'd&d': 'Dungeons & Dragons',
    'DnD': 'Dungeons & Dragons',
    'dnd': 'Dungeons & Dragons',
    'catan': 'Catan',
    'settlers of catan': 'Catan',
    'Settlers of Catan': 'Catan',
    'ticket to ride game': 'Ticket to Ride',
    'pandemic board game': 'Pandemic',
    'jenga blocks': 'Jenga',
    'battleship game': 'Battleship',
    'risk board game': 'Risk',
    'sorry board game': 'Sorry!',
    'operation game': 'Operation',
    'mouse trap game': 'Mousetrap',
    'mousetrap game': 'Mousetrap',
    'twister game': 'Twister',
    'pictionary game': 'Pictionary',
    'boggle game': 'Boggle',
    'yahtzee game': 'Yahtzee',
    'guess who game': 'Guess Who?',
    'Kerplunk': 'Ker-Plunk',
    'kerplunk': 'Ker-Plunk',
    'ker plunk': 'Ker-Plunk',
  },
  items: [
    "LEGO", "Crayola Crayons", "Pokémon Trading Cards", "Checkers", "Magic: The Gathering",
    "Hot Wheels", "Play-Doh", "Playmobil", "Barbie", "Pogs",
    "Beanie Babies", "G.I. Joe", "Rubik's Cube", "Slinky", "Silly Putty",
    "Star Wars action figures", "Monopoly", "Tonka Trucks", "Fisher-Price Little People", "Frisbee",
    "Super Soaker", "Fidget Spinner", "Scrabble", "Nintendo DS", "Uno",
    "Clue", "My Little Pony", "Cabbage Patch Kids", "Bratz Dolls", "Game Boy",
    "Nintendo Wii", "Trivial Pursuit", "Battleship", "Etch A Sketch", "Mr. Potato Head",
    "Risk", "Tamagotchi", "Lincoln Logs", "View-Master", "Beyblades",
    "Bakugan", "Micro Machines", "Jenga", "Connect Four", "Operation",
    "He-Man", "Twister", "Barbie Dreamhouse", "Spirograph", "Simon",
    "Candy Land", "Sorry!", "Lite-Brite", "Hungry Hungry Hippos", "Boggle",
    "Chutes and Ladders", "Tinkertoy", "Yahtzee", "Thomas the Tank Engine", "Hacky Sack",
    "Brio", "Phase 10", "Furby", "Trouble", "Mousetrap",
    "Magna Doodle", "Care Bears", "Pictionary", "Guess Who?", "Catan",
    "Easy-Bake Oven", "Erector Set", "Pound Puppies", "American Girl Dolls", "Stretch Armstrong",
    "Ker-Plunk", "Rainbow Loom", "Slip 'N Slide", "Rock 'Em Sock 'Em Robots", "Perfection",
    "Dungeons & Dragons", "Baby Alive", "Skip-Bo", "Aggravation", "MagnaTiles",
    "Stratego", "Apples to Apples", "Polly Pocket", "Ticket to Ride", "Pandemic",
    "Snap Circuits", "Tickle Me Elmo", "Chess", "Yo-Yo", "Hula Hoop",
    "Transformers", "Nerf", "Teenage Mutant Ninja Turtles", "Pogo Stick", "K'Nex",
  ],
  values: [
    "800B+ pieces", "100B+ crayons", "50.9B+ cards", "50B+ sets est.", "~35B+ cards",
    "9B+ cars", "3B+ cans", "3B+ figures", "~1B+ dolls", "~1B (1994-95 fad)",
    "~500M", "400M+ figures", "350M+", "300M+", "300M+ eggs",
    "300M+ (1978-85)", "275M+", "~250M+", "~250M+", "200M+",
    "200M+", "~200M (2017 fad)", "165M+", "154M", "150M+",
    "150M+", "~150M+", "130M+", "125M+", "118.7M",
    "102M", "100M+", "100M+", "100M+", "100M+",
    "~100M+", "100M+", "100M+ sets", "~100M+", "~100M+",
    "~100M+", "~100M+", "90M+", "~80M+", "~70M+",
    "~70M+ (1981-87)", "~60M+", "~60M+", "~60M+", "~60M+",
    "50M+", "~50M+", "~50M+", "~50M+", "~50M+",
    "~50M+", "~50M+ sets", "~50M+", "~50M+", "~50M+",
    "~50M+", "~50M+", "40M+ (1998-2001)", "~40M+", "~40M+",
    "~40M+", "~40M+", "38M+", "~35M+", "32M+",
    "~30M+", "~30M+", "~30M+", "~30M+", "~30M+",
    "~30M+", "~30M+ kits", "~30M+", "~25M+", "~25M+",
    "~20M+", "~20M+", "~20M+", "~20M+", "~20M+",
    "~20M+", "~15M+", "~10M+", "~10M+", "~10M+",
    "~10M+", "6M+ (1996-98 peak)", "billions", "hundreds of millions", "hundreds of millions",
    "hundreds of millions", "hundreds of millions", "hundreds of millions", "tens of millions", "billions of pieces",
  ],
};
