import type { GameList } from './types';
import { countriesByLiteracyRateHints } from './hints';

export const countriesByLiteracyRate: GameList = {
  id: 'countries-by-literacy-rate',
  name: 'Countries by Literacy Rate (Lowest)',
  description: 'Countries ranked by adult literacy rate, lowest first (UNESCO)',
  topics: ['education', 'world'],
  hints: countriesByLiteracyRateHints,
  valueLabel: 'Literacy Rate',
  items: [
    "Chad", "Mali", "Guinea", "South Sudan", "Niger",
    "Afghanistan", "Central African Republic", "Burkina Faso", "Benin", "Gambia",
    "Sierra Leone", "Guinea-Bissau", "Mozambique", "Ivory Coast", "Liberia",
    "Senegal", "Ethiopia", "Mauritania", "Togo", "Yemen",
    "Pakistan", "Comoros", "Sudan", "Malawi", "Nigeria",
    "Haiti", "DR Congo", "Papua New Guinea", "Nepal", "Burundi",
    "Timor-Leste", "Angola", "Rwanda", "Egypt", "Bangladesh",
    "Morocco", "India", "Madagascar", "Uganda", "Myanmar",
    "Cameroon", "Lesotho", "Tanzania", "Ghana", "Congo",
    "Cambodia", "Guatemala", "Algeria", "Tunisia", "Kenya",
    "Nicaragua", "Gabon", "Iran", "Laos", "Iraq",
    "Zambia", "Honduras", "Libya", "Botswana", "Eswatini",
    "Jamaica", "El Salvador", "Zimbabwe", "Namibia", "Bolivia",
    "Sri Lanka", "Dominican Republic", "Brazil", "Thailand", "Peru",
    "Ecuador", "Paraguay", "South Africa", "Mexico", "Colombia",
    "Malaysia", "Lebanon", "Turkey", "Indonesia", "Oman",
    "Venezuela", "China", "Palestine", "Fiji", "Tonga",
    "Maldives", "Brunei", "Qatar", "Chile", "Vietnam",
    "Philippines", "Saudi Arabia", "Jordan", "Samoa", "Bahrain",
    "Kuwait", "United Arab Emirates", "Costa Rica", "Trinidad & Tobago", "Argentina",
  ],
  values: [
    "22%", "31%", "32%", "35%", "35%",
    "37%", "37%", "41%", "42%", "42%",
    "43%", "46%", "47%", "47%", "48%",
    "52%", "52%", "53%", "53%", "54%",
    "58%", "59%", "61%", "62%", "62%",
    "62%", "63%", "64%", "68%", "68%",
    "68%", "71%", "73%", "73%", "74%",
    "74%", "74%", "75%", "76%", "76%",
    "77%", "77%", "78%", "79%", "80%",
    "81%", "81%", "81%", "81%", "82%",
    "83%", "84%", "84%", "85%", "86%",
    "87%", "87%", "87%", "88%", "88%",
    "88%", "89%", "90%", "91%", "92%",
    "92%", "93%", "93%", "93%", "94%",
    "94%", "94%", "95%", "95%", "95%",
    "95%", "95%", "96%", "96%", "96%",
    "97%", "97%", "97%", "97%", "97%",
    "97%", "97%", "97%", "97%", "98%",
    "98%", "98%", "98%", "98%", "98%",
    "98%", "98%", "98%", "99%", "99%",
  ],
};
