import type { GameList } from './types';
import { countriesByPovertyRateHints } from './hints';

export const countriesByPovertyRate: GameList = {
  id: 'countries-by-poverty-rate',
  name: 'Countries by Poverty Rate (Highest)',
  description: 'Countries ranked by % of population below international poverty line ($2.15/day, World Bank)',
  topics: ['world', 'money'],
  hints: countriesByPovertyRateHints,
  valueLabel: 'Poverty Rate',
  items: [
    "Madagascar", "South Sudan", "Burundi", "DR Congo", "Central African Republic",
    "Mozambique", "Malawi", "Guinea-Bissau", "Sierra Leone", "Rwanda",
    "Lesotho", "Uganda", "Zambia", "Guinea", "Chad",
    "Togo", "Mali", "Burkina Faso", "Niger", "Liberia",
    "Benin", "Ethiopia", "Tanzania", "Congo", "Comoros",
    "Gambia", "Somalia", "Afghanistan", "Nigeria", "Eritrea",
    "Angola", "Cameroon", "Senegal", "Ghana", "Kenya",
    "Haiti", "Ivory Coast", "Zimbabwe", "Pakistan", "Myanmar",
    "Laos", "Timor-Leste", "South Africa", "Papua New Guinea", "Namibia",
    "Solomon Islands", "Eswatini", "Tajikistan", "Honduras", "Botswana",
    "Nepal", "Bangladesh", "Cambodia", "Bolivia", "India",
    "Guatemala", "Nicaragua", "Mauritania", "Sudan", "Yemen",
    "Iraq", "Philippines", "Colombia", "Peru", "Brazil",
    "Morocco", "El Salvador", "Ecuador", "Egypt", "Gabon",
    "Fiji", "Belize", "Paraguay", "Indonesia", "Suriname",
    "Guyana", "Dominican Republic", "Vietnam", "Sri Lanka", "Jamaica",
    "Jordan", "Tunisia", "Mexico", "Mongolia", "Panama",
    "Costa Rica", "Argentina", "Malaysia", "Albania", "Armenia",
    "Thailand", "Georgia", "Ukraine", "China", "Uzbekistan",
    "Kyrgyzstan", "Kazakhstan", "Azerbaijan", "Turkey", "Iran",
  ],
  values: [
    "77%", "76%", "72%", "70%", "67%",
    "65%", "63%", "61%", "58%", "56%",
    "55%", "53%", "52%", "51%", "50%",
    "49%", "47%", "46%", "45%", "44%",
    "38%", "37%", "37%", "36%", "35%",
    "34%", "33%", "33%", "31%", "30%",
    "30%", "28%", "27%", "25%", "24%",
    "24%", "23%", "22%", "22%", "21%",
    "20%", "19%", "19%", "18%", "18%",
    "17%", "17%", "16%", "16%", "16%",
    "15%", "14%", "13%", "13%", "12%",
    "12%", "11%", "11%", "10%", "9%",
    "8%", "6%", "6%", "5%", "5%",
    "4%", "4%", "4%", "3%", "3%",
    "3%", "3%", "3%", "3%", "2%",
    "2%", "2%", "2%", "2%", "2%",
    "2%", "2%", "2%", "1%", "1%",
    "1%", "1%", "1%", "1%", "1%",
    "0.5%", "0.5%", "0.5%", "0.4%", "0.3%",
    "0.3%", "0.1%", "0.1%", "0.1%", "0.1%",
  ],
};
