import type { GameList } from './types';
import { countriesColdestHints } from './hints';

export const countriesColdest: GameList = {
  id: 'countries-coldest',
  name: 'Countries by Average Temperature (Coldest)',
  description: 'Countries ranked by average annual temperature, coldest first (World Bank Climate Portal)',
  topics: ['geography'],
  difficulty: 1,
  hints: countriesColdestHints,
  valueLabel: 'Avg Temp',
  items: [
    "Canada", "Russia", "Mongolia", "Iceland", "Norway",
    "Kyrgyzstan", "Finland", "Tajikistan", "Sweden", "Kazakhstan",
    "Estonia", "Switzerland", "Latvia", "Belarus", "Lithuania",
    "North Korea", "Austria", "Liechtenstein", "China", "Georgia",
    "Armenia", "Ukraine", "Czech Republic", "Andorra", "Denmark",
    "Poland", "Nepal", "Moldova", "Germany", "Slovakia",
    "United Kingdom", "Chile", "Bhutan", "United States", "Luxembourg",
    "Romania", "Slovenia", "Ireland", "Netherlands", "Bosnia",
    "Belgium", "Hungary", "Bulgaria", "Serbia", "Kosovo",
    "New Zealand", "Montenegro", "Croatia", "France", "North Macedonia",
    "Turkey", "Japan", "Albania", "Azerbaijan", "South Korea",
    "Lesotho", "Afghanistan", "Italy", "Uzbekistan", "Spain",
    "Argentina", "Iran", "Portugal", "Lebanon", "Greece",
    "Turkmenistan", "Morocco", "Namibia", "Uruguay", "South Africa",
    "Jordan", "Syria", "Tunisia", "Peru", "Israel",
    "Botswana", "Pakistan", "Mexico", "Libya", "Australia",
    "Iraq", "Egypt", "Algeria", "Ethiopia", "India",
    "Honduras", "Guatemala", "Vietnam", "Colombia", "Brazil",
    "El Salvador", "Cuba", "Oman", "Philippines", "Indonesia",
    "Thailand", "Saudi Arabia", "Nigeria", "Singapore", "Ghana",
  ],
  values: [
    "-5.4°C", "-5.1°C", "-0.7°C", "1.0°C", "1.5°C",
    "1.6°C", "1.7°C", "2.0°C", "2.1°C", "3.5°C",
    "5.1°C", "5.5°C", "5.9°C", "5.9°C", "6.1°C",
    "6.2°C", "6.3°C", "6.4°C", "7.0°C", "7.1°C",
    "7.2°C", "7.4°C", "7.5°C", "7.6°C", "7.7°C",
    "7.8°C", "8.1°C", "8.3°C", "8.5°C", "8.5°C",
    "8.5°C", "8.5°C", "8.6°C", "8.6°C", "8.7°C",
    "8.8°C", "8.9°C", "9.3°C", "9.3°C", "9.6°C",
    "9.7°C", "10.3°C", "10.4°C", "10.4°C", "10.4°C",
    "10.5°C", "10.6°C", "10.7°C", "10.7°C", "11.1°C",
    "11.1°C", "11.2°C", "11.4°C", "11.4°C", "11.5°C",
    "11.7°C", "12.6°C", "12.8°C", "13.0°C", "13.3°C",
    "14.8°C", "15.0°C", "15.2°C", "15.4°C", "15.5°C",
    "15.5°C", "17.1°C", "17.2°C", "17.5°C", "17.7°C",
    "18.3°C", "18.9°C", "19.2°C", "19.5°C", "19.7°C",
    "20.2°C", "20.2°C", "21.0°C", "21.1°C", "21.7°C",
    "21.9°C", "22.1°C", "22.5°C", "22.6°C", "23.7°C",
    "23.9°C", "24.2°C", "24.4°C", "24.5°C", "24.7°C",
    "24.8°C", "25.2°C", "25.6°C", "25.6°C", "25.7°C",
    "26.3°C", "26.4°C", "26.8°C", "27.0°C", "27.2°C",
  ],
};
