import type { GameList } from './types';
import { countriesByLifeExpectancyHints } from './hints';

export const countriesByLifeExpectancy: GameList = {
  id: 'countries-by-life-expectancy',
  name: 'Countries by Life Expectancy',
  description: 'Countries ranked by life expectancy at birth (UN DESA 2023 estimates)',
  topics: ['geography'],
  hints: countriesByLifeExpectancyHints,
  valueLabel: 'Life Expectancy',
  items: [
    "Japan", "South Korea", "Andorra", "Switzerland", "Australia",
    "Singapore", "Italy", "Spain", "France", "Norway",
    "Malta", "Sweden", "United Arab Emirates", "Iceland", "Canada",
    "Israel", "Ireland", "Qatar", "Portugal", "Luxembourg",
    "Netherlands", "Belgium", "New Zealand", "Austria", "Denmark",
    "Finland", "Greece", "Cyprus", "Slovenia", "Germany",
    "United Kingdom", "Bahrain", "Chile", "Maldives", "Costa Rica",
    "Taiwan", "Kuwait", "Oman", "Czech Republic", "Albania",
    "Panama", "United States", "Estonia", "Saudi Arabia", "Poland",
    "Croatia", "Slovakia", "Uruguay", "Cuba", "China",
    "Bosnia and Herzegovina", "Lebanon", "Jordan", "Peru", "Colombia",
    "Iran", "Antigua and Barbuda", "Sri Lanka", "Argentina", "North Macedonia",
    "Ecuador", "Turkey", "Montenegro", "Hungary", "Serbia",
    "Malaysia", "Tunisia", "Thailand", "Algeria", "Latvia",
    "Barbados", "Cape Verde", "Lithuania", "Romania", "Brazil",
    "Armenia", "Bulgaria", "Brunei", "Morocco", "Mexico",
    "Vietnam", "Nicaragua", "Georgia", "Libya", "Bahamas",
    "Seychelles", "Samoa", "Paraguay", "El Salvador", "Honduras",
    "Bangladesh", "Tonga", "Dominican Republic", "Grenada", "Fiji",
    "Uzbekistan", "Suriname", "Venezuela", "Indonesia", "Philippines",
  ],
  values: [
    "84.7 yrs", "84.3 yrs", "84.0 yrs", "84.0 yrs", "83.9 yrs",
    "83.7 yrs", "83.7 yrs", "83.7 yrs", "83.3 yrs", "83.3 yrs",
    "83.3 yrs", "83.3 yrs", "82.9 yrs", "82.7 yrs", "82.6 yrs",
    "82.4 yrs", "82.4 yrs", "82.4 yrs", "82.4 yrs", "82.2 yrs",
    "82.2 yrs", "82.1 yrs", "82.1 yrs", "82.0 yrs", "81.9 yrs",
    "81.9 yrs", "81.9 yrs", "81.7 yrs", "81.6 yrs", "81.4 yrs",
    "81.3 yrs", "81.3 yrs", "81.2 yrs", "81.0 yrs", "80.8 yrs",
    "80.6 yrs", "80.4 yrs", "80.0 yrs", "79.8 yrs", "79.6 yrs",
    "79.6 yrs", "79.3 yrs", "79.2 yrs", "78.7 yrs", "78.6 yrs",
    "78.6 yrs", "78.3 yrs", "78.1 yrs", "78.1 yrs", "78.0 yrs",
    "77.9 yrs", "77.8 yrs", "77.8 yrs", "77.7 yrs", "77.7 yrs",
    "77.7 yrs", "77.6 yrs", "77.5 yrs", "77.4 yrs", "77.4 yrs",
    "77.4 yrs", "77.2 yrs", "77.1 yrs", "77.0 yrs", "76.8 yrs",
    "76.7 yrs", "76.5 yrs", "76.4 yrs", "76.3 yrs", "76.2 yrs",
    "76.2 yrs", "76.1 yrs", "76.0 yrs", "75.9 yrs", "75.9 yrs",
    "75.7 yrs", "75.6 yrs", "75.3 yrs", "75.3 yrs", "75.1 yrs",
    "75.1 yrs", "75.0 yrs", "74.9 yrs", "74.8 yrs", "74.6 yrs",
    "74.5 yrs", "74.4 yrs", "74.2 yrs", "74.0 yrs", "73.8 yrs",
    "73.7 yrs", "73.6 yrs", "73.5 yrs", "73.3 yrs", "73.1 yrs",
    "73.0 yrs", "72.9 yrs", "72.9 yrs", "72.8 yrs", "72.5 yrs",
  ],
  aliases: {
    "UAE": "United Arab Emirates",
    "UK": "United Kingdom",
    "US": "United States",
    "USA": "United States",
    "Korea": "South Korea",
    "Czech": "Czech Republic",
    "Czechia": "Czech Republic",
    "Bosnia": "Bosnia and Herzegovina",
    "Macedonia": "North Macedonia",
  },
  newUntil: '2026-05-14',
};
