import type { GameList } from './types';
import { countriesOlympicMedalsHints } from './hints';

export const countriesOlympicMedals: GameList = {
  id: 'countries-olympic-medals',
  name: 'Countries by All-Time Olympic Medals',
  description: 'Countries ranked by total Olympic medals, Summer + Winter through 2024 (IOC/Wikipedia)',
  topics: ['sports', 'geography'],
  hints: countriesOlympicMedalsHints,
  valueLabel: 'Total Medals',
  items: [
    "United States", "Soviet Union", "Great Britain", "Germany", "France",
    "Italy", "China", "Sweden", "Australia", "Russia",
    "Japan", "Hungary", "Norway", "Netherlands", "Canada",
    "South Korea", "Finland", "Switzerland", "Poland", "Romania",
    "Austria", "Cuba", "Denmark", "Spain", "Belgium",
    "Brazil", "New Zealand", "Greece", "Kenya", "Czech Republic",
    "Turkey", "Belarus", "Bulgaria", "Jamaica", "Argentina",
    "Iran", "Ukraine", "Kazakhstan", "Mexico", "Ethiopia",
    "North Korea", "Croatia", "Indonesia", "India", "Georgia",
    "Ireland", "Thailand", "South Africa", "Colombia", "Egypt",
    "Uzbekistan", "Taiwan", "Slovakia", "Slovenia", "Portugal",
    "Nigeria", "Serbia", "Morocco", "Trinidad & Tobago", "Azerbaijan",
    "Latvia", "Lithuania", "Philippines", "Venezuela", "Bahamas",
    "Estonia", "Tunisia", "Armenia", "Dominican Republic", "Algeria",
    "Uganda", "Pakistan", "Mongolia", "Puerto Rico", "Zimbabwe",
    "Israel", "Cameroon", "Fiji", "Ecuador", "Ivory Coast",
    "Singapore", "Kosovo", "Chile", "Malaysia", "Iceland",
    "Tajikistan", "Kyrgyzstan", "Hong Kong", "Vietnam", "Grenada",
    "Panama", "Peru", "Qatar", "Bahrain", "Moldova",
    "Mozambique", "Suriname", "Afghanistan", "Bermuda", "Turkmenistan",
  ],
  values: [
    "2,959", "1,204", "948", "892", "840",
    "742", "697", "667", "596", "580",
    "560", "529", "517", "394", "385",
    "337", "331", "323", "312", "306",
    "286", "241", "209", "189", "182",
    "171", "135", "125", "117", "104",
    "102", "97", "91", "87", "79",
    "77", "76", "75", "73", "60",
    "56", "44", "44", "42", "40",
    "40", "39", "37", "36", "35",
    "35", "34", "32", "29", "28",
    "27", "26", "26", "22", "18",
    "15", "15", "15", "15", "14",
    "14", "13", "13", "12", "11",
    "10", "10", "9", "9", "8",
    "8", "7", "7", "6", "6",
    "6", "5", "5", "5", "5",
    "4", "4", "4", "4", "3",
    "3", "3", "3", "3", "3",
    "2", "2", "2", "1", "1",
  ],
};
