import type { GameList } from './types';
import { countriesByPovertyRateHints } from './hints';

export const countriesByPovertyRate: GameList = {
  id: 'countries-by-poverty-rate',
  name: 'Countries by Poverty Rate (Highest)',
  description: 'Countries ranked by % of population below international poverty line ($2.15/day, World Bank)',
  topics: ['world', 'money'],
  hints: countriesByPovertyRateHints,
  valueLabel: 'Poverty Rate',
  items: [
    "Madagascar", "South Sudan", "Burundi", "DR Congo", "Central African Republic",
    "Mozambique", "Malawi", "Guinea-Bissau", "Sierra Leone", "Rwanda",
    "Lesotho", "Uganda", "Zambia", "Guinea", "Chad",
    "Togo", "Mali", "Burkina Faso", "Niger", "Ethiopia",
    "Liberia", "Benin", "Tanzania", "Congo", "Comoros",
    "Gambia", "Somalia", "Nigeria", "Eritrea", "Angola",
    "Cameroon", "Senegal", "Ghana", "Kenya", "Ivory Coast",
    "Zimbabwe", "Haiti", "Myanmar", "Laos", "Timor-Leste",
    "Papua New Guinea", "Solomon Islands", "Tajikistan", "Honduras", "Nepal",
    "India", "Bangladesh", "Pakistan", "Cambodia", "Bolivia",
    "Guatemala", "Nicaragua", "Philippines", "South Africa", "Namibia",
    "Botswana", "Eswatini", "Colombia", "Mauritania", "Sudan",
    "Yemen", "Afghanistan", "Iraq", "Morocco", "Egypt",
    "El Salvador", "Gabon", "Fiji", "Belize", "Suriname",
    "Guyana", "Ecuador", "Peru", "Dominican Republic", "Brazil",
    "Paraguay", "Mongolia", "Indonesia", "Vietnam", "Sri Lanka",
    "Jamaica", "Jordan", "Tunisia", "Mexico", "Panama",
    "Costa Rica", "Argentina", "Malaysia", "Thailand", "China",
    "Albania", "Georgia", "Armenia", "Ukraine", "Uzbekistan",
    "Kyrgyzstan", "Kazakhstan", "Azerbaijan", "Turkey", "Iran",
  ],
  values: [
    "77%", "76%", "72%", "70%", "67%",
    "65%", "63%", "61%", "58%", "56%",
    "55%", "53%", "52%", "51%", "50%",
    "49%", "47%", "46%", "45%", "37%",
    "44%", "38%", "37%", "36%", "35%",
    "34%", "33%", "31%", "30%", "30%",
    "28%", "27%", "25%", "24%", "23%",
    "22%", "24%", "21%", "20%", "19%",
    "18%", "17%", "16%", "16%", "15%",
    "12%", "14%", "22%", "13%", "13%",
    "12%", "11%", "6%", "19%", "18%",
    "16%", "17%", "6%", "11%", "10%",
    "9%", "33%", "8%", "4%", "3%",
    "4%", "3%", "3%", "3%", "2%",
    "2%", "4%", "5%", "2%", "5%",
    "3%", "1%", "3%", "2%", "2%",
    "2%", "2%", "2%", "2%", "1%",
    "1%", "1%", "1%", "0.5%", "0.4%",
    "1%", "0.5%", "1%", "0.5%", "0.3%",
    "0.3%", "0.1%", "0.1%", "0.1%", "0.1%",
  ],
};
