// ============================================================
// DAILY SCHEDULE — FROZEN ORDER
// ============================================================
// This array defines the order lists appear as the daily game.
// Day 1 = index 0, Day 2 = index 1, and so on.
//
// RULES:
//   - NEVER reorder, rename, or remove entries. Players who played
//     day N forever played the list at index N-1. Changing this
//     breaks their stored history and the server's daily stats.
//   - When you add a new list to src/lib/lists/index.ts, ALSO
//     append its id to the END of this array. Run:
//         bun run scripts/gen-schedule.ts --append
//     It will detect any list ids missing from the schedule and
//     append them in a deterministic seeded order.
//
// Validation: validate-lists fails if any list id is missing here
// or any id here does not resolve to a real list.
// ============================================================

export const dailySchedule: readonly string[] = [
  'most-visited-wikipedia',
  'most-expensive-paintings',
  'best-selling-candy',
  'most-used-english-words',
  'company-valuation',
  'most-subscribed-youtube',
  'countries-by-poverty-rate',
  'most-popular-medications',
  'most-streamed-spotify-artists',
  'akc-popular-dog-breeds',
  'usnews-college-rankings',
  'best-selling-cars-usa',
  'popular-male-names',
  'sports-teams-by-revenue',
  'largest-greek-organizations',
  'nhl-career-goals',
  'ufc-career-fights',
  'highest-grossing-movies',
  'us-surnames',
  'ufc-career-losses',
  'imdb-top-tv-shows',
  'highest-paid-athletes',
  'nfl-career-rushing-yards',
  'mlb-batters-war',
  'nfl-career-passing-yards',
  'best-selling-albums',
  'longest-rivers',
  'best-selling-toys',
  'best-selling-books',
  'highest-paying-majors',
  'forbes-billionaires',
  'sporting-events-attendance',
  'countries-by-happiness',
  'countries-coldest',
  'ufc-career-wins',
  'countries-by-literacy-rate',
  'f1-career-podiums',
  'most-common-jobs',
  'longest-running-broadway-shows',
  'safest-cities-usa',
  'most-watched-anime',
  'most-visited-countries',
  'most-common-phobias',
  'most-populous-cities-usa',
  'ufc-career-sig-strikes',
  'highest-budget-movies',
  'stadium-capacity',
  'global-cities-cost-of-living',
  'most-downloaded-mobile-apps',
  'march-madness-wins',
  'most-popular-podcasts',
  'most-followed-twitter',
  'cfb-nfl-drafts',
  'tallest-buildings',
  'most-translated-books',
  'most-common-passwords',
  'ufc-career-takedowns',
  'most-visited-national-parks',
  'tennis-career-titles',
  'most-visited-websites',
  'nhl-career-points',
  'pga-tour-wins',
  'imdb-top-movies',
  'nba-career-points',
  'countries-olympic-medals',
  'largest-fast-food-chains',
  'cfb-career-wins',
  'nfl-career-ppr',
  'most-visited-museums',
  'us-cities-cost-of-living',
  'mlb-pitchers-war',
  'actors-box-office',
  'oscar-nominations',
  'largest-cities',
  'most-spoken-languages',
  'countries-by-gdp',
  'nfl-career-touchdowns',
  'qs-world-university-rankings',
  'countries-hottest',
  'countries-by-life-expectancy',
  'nba-career-minutes',
  'fastest-animals',
  'grammy-awards',
  'most-dangerous-jobs',
  'mlb-career-war',
  'best-selling-video-games',
  'nfl-career-receiving-yards',
  'most-streamed-songs',
  'tallest-mountains',
  'most-followed-instagram',
  'most-cited-scientific-papers',
  'directors-box-office',
  'most-populous-countries',
  'longest-running-tv-series',
  'sports-cards-by-sale',
  'ufc-career-finishes',
  'mlb-pitchers-strikeouts',
  'popular-female-names',
  'most-consumed-beverages',
  'best-dishes-world',
  'highest-grossing-tv-shows',
  'elements-earths-crust',
  'best-cuisines-world',
  'longest-charting-hot100',
  'largest-college-populations',
  'highest-grossing-animated-movies',
  'mlb-career-home-runs',
  'highest-grossing-franchises',
  'most-popular-subreddits',
  'countries-by-area',
  'most-viewed-youtube-music-videos',
];
