import type { GameList } from './types';
import { directorsBoxOfficeHints } from './hints';

export const directorsBoxOffice: GameList = {
  id: 'directors-box-office',
  name: 'Directors by Total Box Office Gross',
  description: 'Directors ranked by cumulative worldwide box office (all films)',
  topics: ['film & tv', 'money'],
  hints: directorsBoxOfficeHints,
  valueLabel: 'Total Gross',
  items: [
    "Steven Spielberg", "Anthony Russo & Joe Russo", "Peter Jackson", "Michael Bay", "James Cameron",
    "David Yates", "Christopher Nolan", "Jon Favreau", "James Wan", "Joss Whedon",
    "Ridley Scott", "Tim Burton", "Ron Howard", "Robert Zemeckis", "Gore Verbinski",
    "Bryan Singer", "Zack Snyder", "Sam Raimi", "Taika Waititi", "Ryan Coogler",
    "Denis Villeneuve", "Jon Watts", "Chris Columbus", "Francis Lawrence", "Gary Ross",
    "Chloe Zhao", "Patty Jenkins", "Chad Stahelski", "Martin Scorsese", "Clint Eastwood",
    "George Lucas", "Roland Emmerich", "Brett Ratner", "Todd Phillips", "Matt Reeves",
    "Pete Docter", "Andrew Stanton", "Lee Unkrich", "Brad Bird", "Jennifer Lee",
    "Byron Howard", "Rich Moore", "Pierre Coffin", "Chris Renaud", "Kyle Balda",
    "Dean DeBlois", "Chris Sanders", "Carlos Saldanha", "Eric Darnell", "Tom McGrath",
    "Greta Gerwig", "Jordan Peele", "Quentin Tarantino", "M. Night Shyamalan", "Guy Ritchie",
    "Danny Boyle", "Wes Anderson", "Guillermo del Toro", "David Fincher", "Ang Lee",
    "J.J. Abrams", "Rian Johnson", "Alex Garland", "Paul Greengrass", "Doug Liman",
    "Antoine Fuqua", "Gareth Edwards", "Colin Trevorrow", "F. Gary Gray", "Adam McKay",
    "Tyler Perry", "Woody Allen", "Steven Soderbergh", "Scott Derrickson", "Justin Lin",
    "Alfonso Cuarón", "Alejandro G. Iñárritu", "Barry Sonnenfeld", "Paul W.S. Anderson", "Shawn Levy",
    "Travis Knight", "Charlie Bean", "Mike Mitchell", "Kelly Asbury", "Vicky Jenson",
    "Andrew Adamson", "Conrad Vernon", "Mike Flanagan", "Damien Chazelle", "Bong Joon-ho",
    "Luc Besson", "Wolfgang Petersen", "Tony Scott", "Kathryn Bigelow", "Denis Villeneuve",
    "Spike Lee", "Joel Coen", "Paul Thomas Anderson", "Darren Aronofsky", "Sofia Coppola",
  ],
  values: [
    "$10.6B", "$6.8B", "$6.5B", "$6.5B", "$6.4B",
    "$6.0B", "$5.8B", "$5.5B", "$5.4B", "$3.8B",
    "$5.0B", "$4.9B", "$4.6B", "$4.4B", "$4.2B",
    "$4.0B", "$3.9B", "$3.8B", "$3.7B", "$3.6B",
    "$3.5B", "$3.4B", "$3.3B", "$3.2B", "$3.1B",
    "$3.0B", "$2.9B", "$2.8B", "$2.8B", "$2.7B",
    "$2.7B", "$2.6B", "$2.6B", "$2.5B", "$2.5B",
    "$2.4B", "$2.3B", "$2.3B", "$2.2B", "$2.2B",
    "$2.1B", "$2.1B", "$2.0B", "$2.0B", "$1.9B",
    "$1.9B", "$1.8B", "$1.8B", "$1.7B", "$1.7B",
    "$1.7B", "$1.6B", "$1.6B", "$1.6B", "$1.5B",
    "$1.5B", "$1.4B", "$1.4B", "$1.4B", "$1.3B",
    "$4.7B", "$1.3B", "$1.3B", "$1.2B", "$1.2B",
    "$1.2B", "$1.1B", "$1.1B", "$1.1B", "$1.0B",
    "$1.0B", "$1.0B", "$1.0B", "$990M", "$980M",
    "$970M", "$960M", "$950M", "$940M", "$930M",
    "$920M", "$910M", "$900M", "$890M", "$880M",
    "$870M", "$860M", "$850M", "$840M", "$830M",
    "$820M", "$810M", "$800M", "$790M", "$780M",
    "$770M", "$760M", "$750M", "$740M", "$730M",
  ],
};
