import type { GameList } from './types';
import { forbesBillionairesHints } from './hints';

export const forbesBillionaires: GameList = {
  id: 'forbes-billionaires',
  name: 'Forbes Billionaires Top 100',
  description: "World's wealthiest people ranked by net worth (Forbes 2025)",
  topics: ['business', 'geography'],
  hints: forbesBillionairesHints,
  valueLabel: 'Net Worth',
  items: [
    "Elon Musk", "Mark Zuckerberg", "Jeff Bezos", "Larry Ellison", "Bernard Arnault",
    "Warren Buffett", "Larry Page", "Sergey Brin", "Amancio Ortega", "Steve Ballmer",
    "Jensen Huang", "Michael Dell", "Rob Walton", "Jim Walton", "Bill Gates",
    "Michael Bloomberg", "Alice Walton", "Mukesh Ambani", "Carlos Slim Helu", "Julia Koch",
    "Françoise Bettencourt Meyers", "David Thomson", "Charles Koch", "Changpeng Zhao", "Gautam Adani",
    "Zhong Shanshan", "Thomas Peterffy", "Stephen Schwarzman", "Jeff Yass", "Tadashi Yanai",
    "Ma Huateng", "Ken Griffin", "Zhang Yiming", "Jacqueline Mars", "John Mars",
    "Prajogo Pangestu", "Shiv Nadar", "Giovanni Ferrero", "Alain Wertheimer", "Gérard Wertheimer",
    "Savitri Jindal", "Lukas Walton", "Robin Zeng", "Mark Mateschitz", "Klaus-Michael Kühne",
    "Abigail Johnson", "Li Ka-shing", "Colin Huang", "Miriam Adelson", "Phil Knight",
    "Reinhold Würth", "Eduardo Saverin", "Rafaela Aponte-Diamant", "Gianluigi Aponte", "MacKenzie Scott",
    "William Ding", "Gina Rinehart", "Melinda French Gates", "Masayoshi Son", "Dieter Schwarz",
    "Dilip Shanghvi", "Len Blavatnik", "Low Tuck Kwong", "Elaine Marshall", "Lee Shau Kee",
    "Lyndal Stephens Greth", "He Xiangjian", "Leonid Mikhelson", "German Larrea Mota Velasco", "Vladimir Lisin",
    "Vagit Alekperov", "Andrea Pignataro", "Eyal Ofer", "Eric Schmidt", "Lei Jun",
    "Alexey Mordashov", "Thomas Frist Jr.", "R. Budi Hartono", "John Menard Jr.", "Iris Fontbona",
    "Vladimir Potanin", "Gennady Timchenko", "Andreas von Bechtolsheim", "Jack Ma", "Emmanuel Besnier",
    "Michael Hartono", "Rupert Murdoch", "Daniel Gilbert", "Henry Samueli", "Diane Hendricks",
    "Kumar Birla", "David Tepper", "Cyrus Poonawalla", "Steve Cohen", "Stefan Quandt",
    "Susanne Klatten", "Wang Chuanfu", "François Pinault", "Takemitsu Takizaki", "Donald Bren",
  ],
  values: [
    "$397B", "$261B", "$246B", "$220B", "$207B",
    "$163B", "$156B", "$148B", "$141B", "$134B",
    "$127B", "$120B", "$117B", "$115B", "$107B",
    "$104B", "$102B", "$100B", "$93B", "$90B",
    "$88B", "$86B", "$85B", "$83B", "$82B",
    "$79B", "$77B", "$76B", "$74B", "$72B",
    "$70B", "$68B", "$67B", "$67B", "$67B",
    "$66B", "$65B", "$63B", "$62B", "$62B",
    "$62B", "$61B", "$60B", "$59B", "$57B",
    "$56B", "$55B", "$54B", "$53B", "$53B",
    "$52B", "$51B", "$51B", "$50B", "$49B",
    "$49B", "$48B", "$47B", "$46B", "$46B",
    "$45B", "$45B", "$44B", "$43B", "$43B",
    "$43B", "$42B", "$41B", "$41B", "$41B",
    "$40B", "$40B", "$39B", "$39B", "$38B",
    "$38B", "$37B", "$37B", "$37B", "$36B",
    "$36B", "$36B", "$35B", "$35B", "$35B",
    "$34B", "$34B", "$34B", "$34B", "$33B",
    "$33B", "$33B", "$33B", "$32B", "$32B",
    "$32B", "$32B", "$32B", "$31B", "$31B",
  ],
};
