import type { GameList } from './types';
import { grammyAwardsHints } from './hints';

export const grammyAwards: GameList = {
  id: 'grammy-awards',
  name: 'Most Awarded Artists (Grammys)',
  description: 'Artists ranked by total Grammy Awards won (all time)',
  topics: ['music'],
  hints: grammyAwardsHints,
  valueLabel: 'Grammys Won',
  items: [
    "Beyoncé", "Georg Solti", "Quincy Jones", "Chick Corea", "Stevie Wonder",
    "Alison Krauss", "Pierre Boulez", "Jay-Z", "John Williams", "Vince Gill",
    "Pat Metheny", "U2", "Kanye West", "Bruce Springsteen", "Al Schmitt",
    "Eminem", "Ray Charles", "Henry Mancini", "Aretha Franklin", "Jimmy Sturr",
    "Taylor Swift", "Paul Simon", "Adele", "David Frost (engineer)", "Robert Woods",
    "Kendrick Lamar", "Tina Turner", "Eric Clapton", "Thomas Z. Shepard", "Ella Fitzgerald",
    "Billie Eilish", "John Legend", "Jimmy Carter", "Arturo Sandoval", "CeeLo Green",
    "Babyface", "Herbie Hancock", "Lady Gaga", "Foo Fighters", "Tony Bennett",
    "Michael Tilson Thomas", "Ricky Skaggs", "Metallica", "India.Arie", "Jack White",
    "Bruno Mars", "Dan Auerbach", "Dave Grohl", "Pharrell Williams", "Sting",
    "Robert Plant", "Bonnie Raitt", "Willie Nelson", "Dolly Parton", "Buddy Guy",
    "Kirk Franklin", "Esperanza Spalding", "Plácido Domingo", "Yo-Yo Ma", "James Brown",
    "Mary J. Blige", "Paul McCartney", "Cardi B", "Drake", "H.E.R.",
    "Anderson .Paak", "Chris Stapleton", "Childish Gambino", "Meghan Trainor", "Sam Smith",
    "Lizzo", "Daniel Caesar", "SZA", "Bad Bunny", "Dua Lipa",
    "Olivia Rodrigo", "Harry Styles", "Ed Sheeran", "The Weeknd", "Rihanna",
    "Justin Bieber", "Miley Cyrus", "Ariana Grande", "Post Malone", "Billie Joe Armstrong",
    "Dave Matthews", "Jack Johnson", "John Mayer", "Alicia Keys", "Norah Jones",
    "Amy Winehouse", "Shakira", "Michael Bublé", "Josh Groban", "Christina Aguilera",
    "Kelly Clarkson", "Carrie Underwood", "Tim McGraw", "Keith Urban", "Brad Paisley",
  ],
  values: [
    "32", "31", "28", "27", "25",
    "27", "26", "24", "25", "22",
    "20", "22", "24", "20", "20",
    "15", "17", "20", "18", "18",
    "14", "16", "16", "14", "14",
    "17", "12", "18", "12", "13",
    "9", "12", "3", "10", "6",
    "12", "14", "13", "12", "18",
    "11", "14", "9", "4", "12",
    "15", "10", "16", "13", "17",
    "6", "13", "10", "10", "8",
    "16", "4", "12", "18", "3",
    "9", "18", "1", "5", "5",
    "5", "8", "5", "1", "4",
    "3", "2", "3", "3", "3",
    "3", "1", "1", "0", "9",
    "2", "1", "2", "8", "15",
    "2", "0", "7", "15", "9",
    "5", "3", "4", "0", "6",
    "3", "8", "3", "4", "3",
  ],
};
