import type { GameList } from './types';
import { grammyAwardsHints } from './hints';

export const grammyAwards: GameList = {
  id: 'grammy-awards',
  name: 'Most Awarded Artists (Grammys)',
  description: 'Artists ranked by total Grammy Awards won, all time through 2026 (Grammy.com)',
  topics: ['music'],
  hints: grammyAwardsHints,
  valueLabel: 'Grammys Won',
  items: [
    "Beyoncé", "Kendrick Lamar", "Georg Solti", "Chick Corea", "Quincy Jones",
    "John Williams", "Alison Krauss", "Pierre Boulez", "Jay-Z", "Stevie Wonder",
    "David Frost", "Vladimir Horowitz", "Kanye West", "Şerban Ghenea", "Vince Gill",
    "U2", "Al Schmitt", "Bruce Springsteen", "Pat Metheny", "Yo-Yo Ma",
    "Kirk Franklin", "Henry Mancini", "Paul McCartney", "Eric Clapton", "CeCe Winans",
    "Aretha Franklin", "Jimmy Sturr", "Tony Bennett", "Lady Gaga", "Ray Charles",
    "Tom Elmhirst", "Béla Fleck", "Alicia Keys", "Sting", "Adele",
    "T Bone Burnett", "Ricky Skaggs", "Itzhak Perlman", "David Foster", "Paul Simon",
    "Bruno Mars", "Leonard Bernstein", "Foo Fighters", "B.B. King", "Eminem",
    "Taylor Swift", "Herbie Hancock", "Chet Atkins", "Phil Ramone", "Jack Antonoff",
    "Michael Jackson", "The Chicks", "Pharrell Williams", "Babyface", "Emmylou Harris",
    "Bonnie Raitt", "Ella Fitzgerald", "Willie Nelson", "John Legend", "Shirley Caesar",
    "Jack White", "Linda Ronstadt", "Tina Turner", "Chris Stapleton", "Billie Eilish",
    "Brandi Carlile", "Alan Menken", "Bobby McFerrin", "Joni Mitchell", "Arturo Sandoval",
    "Dolly Parton", "Mark Ronson", "Chaka Khan", "Al Jarreau", "Carlos Santana",
    "Norah Jones", "Justin Timberlake", "Bob Dylan", "Anderson .Paak", "Buddy Guy",
    "Sheryl Crow", "Wynton Marsalis", "Skrillex", "Rihanna", "Eddie Palmieri",
    "Metallica", "Natalie Cole", "Mary J. Blige", "John Mayer", "André 3000",
    "Carrie Underwood", "Usher", "Count Basie", "Robert Plant", "Luther Vandross",
    "Kacey Musgraves", "Phil Collins", "Lauryn Hill", "The Beatles", "Beck",
  ],
  values: [
    "35", "32", "31", "29", "28",
    "27", "27", "26", "25", "25",
    "25", "25", "24", "24", "22",
    "22", "20", "20", "20", "20",
    "20", "20", "19", "18", "18",
    "18", "18", "18", "18", "17",
    "17", "17", "17", "17", "16",
    "16", "16", "16", "16", "16",
    "16", "15", "15", "15", "15",
    "14", "14", "14", "14", "13",
    "13", "13", "13", "13", "13",
    "13", "13", "12", "12", "12",
    "12", "11", "11", "11", "11",
    "11", "11", "11", "11", "10",
    "10", "10", "10", "10", "10",
    "10", "10", "10", "9", "9",
    "9", "9", "9", "9", "9",
    "9", "9", "9", "8", "8",
    "8", "8", "8", "8", "8",
    "8", "8", "8", "8", "8",
  ],
};
