import type { GameList } from './types';
import { grammyAwardsHints } from './hints';

export const grammyAwards: GameList = {
  id: 'grammy-awards',
  name: 'Most Awarded Artists (Grammys)',
  description: 'Artists ranked by total Grammy Awards won, all time through 2026 (Grammy.com)',
  topics: ['music'],
  hints: grammyAwardsHints,
  valueLabel: 'Grammys Won',
  items: [
    "Beyoncé", "Kendrick Lamar", "Georg Solti", "Chick Corea", "Quincy Jones",
    "Alison Krauss", "John Williams", "Pierre Boulez", "David Frost", "Jay-Z",
    "Stevie Wonder", "Vladimir Horowitz", "Kanye West", "Şerban Ghenea", "U2",
    "Vince Gill", "Al Schmitt", "Bruce Springsteen", "Henry Mancini", "Kirk Franklin",
    "Pat Metheny", "Yo-Yo Ma", "Paul McCartney", "Aretha Franklin", "CeCe Winans",
    "Eric Clapton", "Jimmy Sturr", "Lady Gaga", "Tony Bennett", "Alicia Keys",
    "Béla Fleck", "Ray Charles", "Sting", "Tom Elmhirst", "Adele",
    "Bruno Mars", "David Foster", "Itzhak Perlman", "Paul Simon", "Ricky Skaggs",
    "T Bone Burnett", "B.B. King", "Eminem", "Foo Fighters", "Leonard Bernstein",
    "Chet Atkins", "Herbie Hancock", "Phil Ramone", "Taylor Swift", "Babyface",
    "Bonnie Raitt", "Ella Fitzgerald", "Emmylou Harris", "Jack Antonoff", "Michael Jackson",
    "Pharrell Williams", "The Chicks", "Jack White", "John Legend", "Shirley Caesar",
    "Willie Nelson", "Alan Menken", "Billie Eilish", "Bobby McFerrin", "Brandi Carlile",
    "Chris Stapleton", "Joni Mitchell", "Linda Ronstadt", "Tina Turner", "Al Jarreau",
    "Arturo Sandoval", "Bob Dylan", "Carlos Santana", "Chaka Khan", "Dolly Parton",
    "Justin Timberlake", "Mark Ronson", "Norah Jones", "Anderson .Paak", "Buddy Guy",
    "Eddie Palmieri", "Mary J. Blige", "Metallica", "Natalie Cole", "Rihanna",
    "Sheryl Crow", "Skrillex", "Wynton Marsalis", "André 3000", "Beck",
    "Carrie Underwood", "Count Basie", "John Mayer", "Kacey Musgraves", "Lauryn Hill",
    "Luther Vandross", "Phil Collins", "Robert Plant", "The Beatles", "Usher",
  ],
  values: [
    "35", "32", "31", "29", "28",
    "27", "27", "26", "25", "25",
    "25", "25", "24", "24", "22",
    "22", "20", "20", "20", "20",
    "20", "20", "19", "18", "18",
    "18", "18", "18", "18", "17",
    "17", "17", "17", "17", "16",
    "16", "16", "16", "16", "16",
    "16", "15", "15", "15", "15",
    "14", "14", "14", "14", "13",
    "13", "13", "13", "13", "13",
    "13", "13", "12", "12", "12",
    "12", "11", "11", "11", "11",
    "11", "11", "11", "11", "10",
    "10", "10", "10", "10", "10",
    "10", "10", "10", "9", "9",
    "9", "9", "9", "9", "9",
    "9", "9", "9", "8", "8",
    "8", "8", "8", "8", "8",
    "8", "8", "8", "8", "8",
  ],
};
