import type { GameList } from './types';
import { highestBudgetMoviesHints } from './hints';

export const highestBudgetMovies: GameList = {
  id: 'highest-budget-movies',
  name: 'Movies with Highest Budget',
  description: 'Films ranked by production budget (The Numbers/Wikipedia)',
  topics: ['film & tv', 'business'],
  difficulty: 2,
  hints: highestBudgetMoviesHints,
  valueLabel: 'Budget',
  items: [
    "Pirates of the Caribbean: On Stranger Tides", "Avengers: Age of Ultron", "Avengers: Endgame", "Avatar: The Way of Water", "Cleopatra",
    "Avengers: Infinity War", "Star Wars: The Force Awakens", "Pirates of the Caribbean: At World's End", "Justice League", "Star Wars: The Rise of Skywalker",
    "Solo: A Star Wars Story", "John Carter", "Spider-Man: No Way Home", "Tangled", "The Lion King (2019)",
    "Spider-Man 3", "The Amazing Spider-Man 2", "Captain America: Civil War", "Batman v Superman: Dawn of Justice", "The Hobbit: The Battle of the Five Armies",
    "Thor: Love and Thunder", "No Time to Die", "The Fate of the Furious", "Spectre", "Avatar",
    "The Dark Knight Rises", "Robin Hood (2018)", "Men in Black 3", "The Hobbit: The Desolation of Smaug", "Man of Steel",
    "The Chronicles of Narnia: Prince Caspian", "Transformers: The Last Knight", "The Lone Ranger", "Oz the Great and Powerful", "Transformers: Age of Extinction",
    "King Kong (2005)", "Tenet", "Superman Returns", "Star Wars: The Last Jedi", "Toy Story 4",
    "Finding Dory", "Incredibles 2", "Cars 2", "Black Widow", "Doctor Strange in the Multiverse of Madness",
    "Eternals", "Shang-Chi", "Rogue One", "X-Men: Dark Phoenix", "Aquaman",
    "Mulan (2020)", "Green Lantern", "Quantum of Solace", "Titanic", "Transformers: Dark of the Moon",
    "Furious 7", "Jurassic World: Dominion", "The Batman", "Maleficent: Mistress of Evil", "Terminator: Dark Fate",
    "Aladdin (2019)", "Thor: Ragnarok", "Tomorrowland", "X-Men: Apocalypse", "Valerian and the City of a Thousand Planets",
    "Captain Marvel", "Ralph Breaks the Internet", "The Jungle Book (2016)", "King Arthur: Legend of the Sword", "Waterworld",
    "Troy", "Dumbo (2019)", "Terminator 3", "Wild Wild West", "Independence Day: Resurgence",
    "The Polar Express", "Beauty and the Beast (2017)", "Fast & Furious 6", "Warcraft", "Blade Runner 2049",
    "Alexander", "Frozen II", "Pan", "Hugo", "The Matrix Reloaded",
    "The Matrix Revolutions", "Sahara", "The BFG", "Treasure Planet", "Gemini Man",
    "Stealth", "The 13th Warrior", "The Mummy (2017)", "Cutthroat Island", "Ghost in the Shell",
    "A Wrinkle in Time", "Mortal Engines", "Cats", "Ben-Hur (2016)", "The Adventures of Pluto Nash",
  ],
  values: [
    "$410M", "$365M", "$356M", "$350M", "$320M",
    "$316M", "$306M", "$300M", "$300M", "$275M",
    "$275M", "$263M", "$260M", "$260M", "$260M",
    "$258M", "$255M", "$250M", "$250M", "$250M",
    "$250M", "$250M", "$250M", "$245M", "$237M",
    "$230M", "$230M", "$225M", "$225M", "$225M",
    "$225M", "$217M", "$215M", "$215M", "$210M",
    "$207M", "$205M", "$204M", "$200M", "$200M",
    "$200M", "$200M", "$200M", "$200M", "$200M",
    "$200M", "$200M", "$200M", "$200M", "$200M",
    "$200M", "$200M", "$200M", "$200M", "$195M",
    "$190M", "$185M", "$185M", "$185M", "$185M",
    "$183M", "$180M", "$180M", "$178M", "$177M",
    "$175M", "$175M", "$175M", "$175M", "$175M",
    "$175M", "$170M", "$170M", "$170M", "$165M",
    "$165M", "$160M", "$160M", "$160M", "$155M",
    "$155M", "$150M", "$150M", "$150M", "$150M",
    "$150M", "$145M", "$140M", "$140M", "$138M",
    "$135M", "$130M", "$125M", "$115M", "$110M",
    "$103M", "$100M", "$100M", "$100M", "$100M",
  ],
  aliases: {
    "Ghost in the Shell (2017)": "Ghost in the Shell",
    "Dark Phoenix": "X-Men: Dark Phoenix",
  },
};
