import type { GameList } from './types';
import { highestGrossingTvShowsHints } from './hints/highest-grossing-tv-shows';

export const highestGrossingTvShows: GameList = {
  id: 'highest-grossing-tv-shows',
  name: 'Highest-Grossing TV Franchises of All Time',
  description: 'TV franchises ranked by estimated total revenue including syndication, streaming, merchandise & advertising (Wikipedia, Forbes, industry reports)',
  topics: ['film & tv', 'business'],
  difficulty: 2,
  hints: highestGrossingTvShowsHints,
  valueLabel: 'Revenue',
  items: [
    "SpongeBob SquarePants", "The Simpsons", "Star Trek", "Power Rangers", "American Idol",
    "Sesame Street", "Scooby-Doo", "The Big Bang Theory", "Seinfeld", "Friends",
    "Game of Thrones", "Law & Order", "NCIS", "ER", "Yellowstone",
    "CSI", "South Park", "The Walking Dead", "Grey's Anatomy", "Survivor",
    "Family Guy", "Peppa Pig", "Two and a Half Men", "Frasier", "Stranger Things",
    "The Office", "Squid Game", "Breaking Bad", "Everybody Loves Raymond", "House",
    "Cheers", "Baywatch", "The Crown", "Modern Family", "Bridgerton",
    "The Sopranos", "How I Met Your Mother", "Desperate Housewives", "Sex and the City", "The X-Files",
    "Downton Abbey", "M*A*S*H", "24", "Supernatural", "Lost",
    "The Real Housewives", "Criminal Minds", "Dancing with the Stars", "Home Improvement", "Full House",
    "Roseanne", "The Mandalorian", "Married with Children", "Mad Men", "Suits",
    "Beverly Hills, 90210", "Dexter", "Ozark", "Sons of Anarchy", "NCIS: Los Angeles",
    "Blue Bloods", "Chicago Fire", "Hawaii Five-0", "Bones", "Narcos",
    "True Blood", "Shameless", "Money Heist", "Cobra Kai", "The Boys",
    "Westworld", "Homeland", "Ted Lasso", "Succession", "Boardwalk Empire",
    "30 Rock", "Parks and Recreation", "The Wire", "Wednesday", "Peaky Blinders",
    "Arrested Development", "It's Always Sunny in Philadelphia", "The Shield", "Justified", "Castle",
    "Psych", "Monk", "House of the Dragon", "Emily in Paris", "The Last of Us",
    "The Bear", "Severance", "Abbott Elementary", "Only Murders in the Building", "Umbrella Academy",
    "The Witcher", "Outer Banks", "Virgin River", "Invincible", "Euphoria",
  ],
  values: [
    "$16.6B", "$14B", "$11.2B", "$8.7B", "$8B",
    "$7.7B", "$5.4B", "$4.6B", "$4.6B", "$4.5B",
    "$4B", "$4B", "$4B", "$3B", "$2.9B",
    "$2.5B", "$2.5B", "$2B", "$2B", "$2B",
    "$1.8B", "$1.7B", "$1.5B", "$1.5B", "$1.4B",
    "$1.3B", "$1.2B", "$1B", "$1B", "$1B",
    "$800M", "$800M", "$700M", "$700M", "$600M",
    "$600M", "$550M", "$500M", "$500M", "$500M",
    "$500M", "$500M", "$450M", "$450M", "$400M",
    "$400M", "$400M", "$400M", "$350M", "$350M",
    "$350M", "$350M", "$300M", "$300M", "$300M",
    "$300M", "$280M", "$270M", "$260M", "$250M",
    "$250M", "$250M", "$240M", "$230M", "$220M",
    "$220M", "$210M", "$200M", "$200M", "$200M",
    "$190M", "$180M", "$180M", "$170M", "$160M",
    "$150M", "$150M", "$140M", "$140M", "$130M",
    "$120M", "$120M", "$110M", "$110M", "$100M",
    "$100M", "$100M", "$100M", "$95M", "$95M",
    "$90M", "$85M", "$80M", "$75M", "$70M",
    "$70M", "$65M", "$60M", "$55M", "$50M",
  ],
  aliases: {
    "Cheer": "Cheers",
    "Law & Order: SVU": "Law & Order",
    "Law & Order: Criminal Intent": "Law & Order",
    "Law & Order: Special Victims Unit": "Law & Order",
  },
};
