import type { GameList } from './types';
import { highestBudgetMoviesHints } from './hints';

export const highestBudgetMovies: GameList = {
  id: 'highest-budget-movies',
  name: 'Movies with Highest Budget',
  description: 'Films ranked by production budget (inflation-adjusted estimates)',
  topics: ['entertainment', 'movies', 'money'],
  hints: highestBudgetMoviesHints,
  valueLabel: 'Budget',
  items: [
    "Pirates of the Caribbean: On Stranger Tides", "Avengers: Age of Ultron", "Avengers: Endgame", "Avengers: Infinity War", "Pirates of the Caribbean: At World's End",
    "Avatar: The Way of Water", "Justice League", "Star Wars: The Force Awakens", "Spider-Man: No Way Home", "Star Wars: The Last Jedi",
    "Star Wars: The Rise of Skywalker", "Tangled", "Transformers: The Last Knight", "Avatar", "The Lion King (2019)",
    "Spectre", "The Dark Knight Rises", "Toy Story 4", "Captain America: Civil War", "Batman v Superman: Dawn of Justice",
    "The Hobbit: The Battle of the Five Armies", "Frozen II", "Finding Dory", "John Carter", "Incredibles 2",
    "Cars 2", "Men in Black 3", "The Amazing Spider-Man 2", "The Hobbit: The Desolation of Smaug", "Thor: Love and Thunder",
    "Black Widow", "Doctor Strange in the Multiverse of Madness", "Eternals", "Shang-Chi", "Jurassic World: Dominion",
    "No Time to Die", "Solo: A Star Wars Story", "The Batman", "Rogue One", "Man of Steel",
    "X-Men: Dark Phoenix", "The Lone Ranger", "Captain Marvel", "Aquaman", "Thor: Ragnarok",
    "Beauty and the Beast (2017)", "Aladdin (2019)", "Dumbo (2019)", "Ralph Breaks the Internet", "Mulan (2020)",
    "Maleficent: Mistress of Evil", "Tenet", "The Jungle Book (2016)", "Transformers: Dark of the Moon", "Fast & Furious 6",
    "Furious 7", "The Fate of the Furious", "Robin Hood (2018)", "Transformers: Age of Extinction", "Oz the Great and Powerful",
    "Green Lantern", "King Arthur: Legend of the Sword", "A Wrinkle in Time", "Mortal Engines", "The BFG",
    "Terminator: Dark Fate", "Gemini Man", "Cats", "Valerian and the City of a Thousand Planets", "Blade Runner 2049",
    "X-Men: Apocalypse", "Independence Day: Resurgence", "The Mummy (2017)", "Ben-Hur (2016)", "Pan",
    "Tomorrowland", "Warcraft", "Ghost in the Shell", "King Kong (2005)", "Spider-Man 3",
    "Waterworld", "Superman Returns", "Quantum of Solace", "The Chronicles of Narnia: Prince Caspian", "Hugo",
    "Cleopatra", "The Matrix Reloaded", "The Matrix Revolutions", "Troy", "Terminator 3",
    "Wild Wild West", "Titanic", "The Polar Express", "Alexander", "Sahara",
    "Treasure Planet", "The Adventures of Pluto Nash", "Stealth", "The 13th Warrior", "Cutthroat Island",
  ],
  values: [
    "$410M", "$365M", "$356M", "$316M", "$300M",
    "$350M", "$300M", "$306M", "$260M", "$200M",
    "$275M", "$260M", "$217M", "$237M", "$260M",
    "$245M", "$230M", "$200M", "$250M", "$250M",
    "$250M", "$150M", "$200M", "$263M", "$200M",
    "$200M", "$225M", "$255M", "$225M", "$250M",
    "$200M", "$200M", "$200M", "$200M", "$185M",
    "$250M", "$275M", "$185M", "$200M", "$225M",
    "$200M", "$215M", "$175M", "$200M", "$180M",
    "$160M", "$183M", "$170M", "$175M", "$200M",
    "$185M", "$205M", "$175M", "$195M", "$160M",
    "$190M", "$250M", "$230M", "$210M", "$215M",
    "$200M", "$175M", "$103M", "$100M", "$140M",
    "$185M", "$138M", "$100M", "$177M", "$155M",
    "$178M", "$165M", "$125M", "$100M", "$150M",
    "$180M", "$160M", "$110M", "$207M", "$258M",
    "$175M", "$204M", "$200M", "$225M", "$150M",
    "$320M", "$150M", "$150M", "$175M", "$170M",
    "$170M", "$200M", "$165M", "$155M", "$145M",
    "$140M", "$100M", "$135M", "$130M", "$115M",
  ],
};
