import type { GameList } from './types';
import { highestGrossingMoviesHints } from './hints';

export const highestGrossingMovies: GameList = {
  id: 'highest-grossing-movies',
  name: 'Highest Grossing Movies',
  description: 'All-time worldwide box office',
  topics: ['film & tv'],
  hints: highestGrossingMoviesHints,
  valueLabel: 'Box Office',
  items: [
    "Avatar", "Avengers: Endgame", "Avatar: The Way of Water", "Titanic", "Star Wars: The Force Awakens",
    "Avengers: Infinity War", "Spider-Man: No Way Home", "Inside Out 2", "Jurassic World", "The Lion King",
    "The Avengers", "Furious 7", "Frozen II", "Top Gun: Maverick", "Barbie",
    "Avengers: Age of Ultron", "The Super Mario Bros. Movie", "Black Panther", "Harry Potter and the Deathly Hallows Part 2", "Star Wars: The Last Jedi",
    "Jurassic World: Fallen Kingdom", "Frozen", "Beauty and the Beast", "Incredibles 2", "The Fate of the Furious",
    "Iron Man 3", "Minions", "Captain America: Civil War", "Aquaman", "The Lord of the Rings: The Return of the King",
    "Spider-Man: Far From Home", "Captain Marvel", "Transformers: Dark of the Moon", "Skyfall", "Transformers: Age of Extinction",
    "The Dark Knight Rises", "Joker", "Star Wars: The Rise of Skywalker", "Toy Story 4", "Toy Story 3",
    "Pirates of the Caribbean: Dead Man's Chest", "Rogue One", "Aladdin", "Pirates of the Caribbean: On Stranger Tides", "Despicable Me 3",
    "Finding Dory", "Alice in Wonderland", "Zootopia", "The Hobbit: An Unexpected Journey", "The Dark Knight",
    "Harry Potter and the Philosopher's Stone", "Despicable Me 2", "The Jungle Book", "The Hobbit: The Desolation of Smaug", "The Hobbit: The Battle of the Five Armies",
    "Finding Nemo", "Harry Potter and the Deathly Hallows Part 1", "The Lord of the Rings: The Two Towers", "Shrek 2", "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince", "The Lord of the Rings: The Fellowship of the Ring", "Jurassic Park", "Star Wars: Episode I", "Moana",
    "Guardians of the Galaxy Vol. 2", "Spider-Man: Across the Spider-Verse", "Deadpool & Wolverine", "Thor: Ragnarok", "Oppenheimer",
    "Wonder Woman", "Guardians of the Galaxy Vol. 3", "Doctor Strange in the Multiverse of Madness", "Black Panther: Wakanda Forever", "Spider-Man: Homecoming",
    "It", "Venom", "Bohemian Rhapsody", "The Hunger Games: Catching Fire", "Deadpool",
    "The Amazing Spider-Man", "Shrek the Third", "Mission: Impossible - Fallout", "Spider-Man 3", "The Hunger Games",
    "Inception", "Harry Potter and the Prisoner of Azkaban", "Ice Age: Dawn of the Dinosaurs", "Coco", "Kung Fu Panda 2",
    "Batman v Superman: Dawn of Justice", "Puss in Boots: The Last Wish", "Fast & Furious 6", "Madagascar 3", "Shrek Forever After",
    "X-Men: Days of Future Past", "The Chronicles of Narnia: The Lion the Witch and the Wardrobe", "Gravity", "Maleficent", "The Matrix Reloaded"
  ],
  values: [
    "$2.92B", "$2.80B", "$2.32B", "$2.26B", "$2.07B",
    "$2.05B", "$1.92B", "$1.70B", "$1.67B", "$1.66B",
    "$1.52B", "$1.52B", "$1.45B", "$1.49B", "$1.44B",
    "$1.40B", "$1.36B", "$1.35B", "$1.34B", "$1.33B",
    "$1.31B", "$1.28B", "$1.26B", "$1.24B", "$1.24B",
    "$1.21B", "$1.16B", "$1.15B", "$1.15B", "$1.15B",
    "$1.13B", "$1.13B", "$1.12B", "$1.11B", "$1.10B",
    "$1.08B", "$1.07B", "$1.07B", "$1.07B", "$1.07B",
    "$1.07B", "$1.06B", "$1.05B", "$1.05B", "$1.03B",
    "$1.03B", "$1.03B", "$1.02B", "$1.02B", "$1.01B",
    "$1.00B", "$971M", "$967M", "$960M", "$956M",
    "$940M", "$937M", "$934M", "$921M", "$900M",
    "$871M", "$869M", "$868M", "$865M", "$863M",
    "$862M", "$860M", "$859M", "$858M", "$854M",
    "$822M", "$821M", "$819M", "$816M", "$812M",
    "$810M", "$809M", "$803M", "$799M", "$794M",
    "$783M", "$774M", "$773M", "$773M", "$771M",
    "$756M", "$748M", "$746M", "$741M", "$736M",
    "$748M", "$745M", "$723M", "$714M", "$742M",
    "$748M", "$745M", "$723M", "$758M", "$742M",
  ],
};
