import type { GameList } from './types';
import { highestGrossingTvShowsHints } from './hints/highest-grossing-tv-shows';

export const highestGrossingTvShows: GameList = {
  id: 'highest-grossing-tv-shows',
  name: 'Highest-Grossing TV Shows of All Time',
  description: 'TV shows ranked by total franchise revenue and earnings',
  topics: ['entertainment', 'television'],
  hints: highestGrossingTvShowsHints,
  valueLabel: 'Revenue',
  items: [
    'The Simpsons', 'Friends', 'The Big Bang Theory', 'Seinfeld', 'Law & Order',
    'NCIS', "Grey's Anatomy", 'Game of Thrones', 'The Walking Dead', 'Frasier',
    'Everybody Loves Raymond', 'Two and a Half Men', 'The Office', 'Stranger Things', 'Modern Family',
    'House', 'CSI', 'ER', 'Desperate Housewives', 'How I Met Your Mother',
    'Family Guy', 'South Park', 'Cheers', 'M*A*S*H', '24',
    'Lost', 'Breaking Bad', 'The Sopranos', 'Mad Men', 'Succession',
    'Yellowstone', 'Supernatural', 'The Real Housewives', 'Survivor', 'American Idol',
    'Dancing with the Stars', 'The X-Files', 'Married with Children', 'Home Improvement', 'Roseanne',
    'Full House', 'Star Trek', 'Baywatch', 'Beverly Hills, 90210', 'Sex and the City',
    'Downton Abbey', 'The Crown', 'Ozark', 'Squid Game', 'Money Heist',
    'Narcos', 'Dexter', 'True Blood', 'Boardwalk Empire', 'Westworld',
    'Homeland', '30 Rock', 'Parks and Recreation', 'Arrested Development', "It's Always Sunny in Philadelphia",
    'The Wire', 'The Shield', 'Justified', 'Sons of Anarchy', 'Criminal Minds',
    'NCIS: Los Angeles', 'Hawaii Five-0', 'Blue Bloods', 'Chicago Fire', 'Bones',
    'Castle', 'Psych', 'Monk', 'Burn Notice', 'White Collar',
    'Suits', 'Shameless', 'Peaky Blinders', 'Cobra Kai', 'Bridgerton',
    'Emily in Paris', 'Virgin River', 'Outer Banks', 'Wednesday', 'The Witcher',
    'Umbrella Academy', 'Dark', 'Lupin', 'The Last of Us', 'House of the Dragon',
    'The Bear', 'Severance', 'Ted Lasso', 'Abbott Elementary', 'Only Murders in the Building',
    'The Mandalorian', 'Andor', 'The Boys', 'Invincible', 'Euphoria',
  ],
  values: [
    "$750M", "$700M", "$650M", "$600M", "$580M",
    "$560M", "$550M", "$520M", "$500M", "$480M",
    "$460M", "$450M", "$440M", "$430M", "$420M",
    "$400M", "$390M", "$380M", "$370M", "$360M",
    "$350M", "$340M", "$330M", "$320M", "$310M",
    "$300M", "$290M", "$280M", "$270M", "$260M",
    "$250M", "$240M", "$230M", "$220M", "$210M",
    "$200M", "$195M", "$190M", "$185M", "$180M",
    "$175M", "$170M", "$165M", "$160M", "$155M",
    "$150M", "$145M", "$140M", "$135M", "$130M",
    "$125M", "$120M", "$115M", "$110M", "$105M",
    "$100M", "$95M", "$90M", "$85M", "$80M",
    "$78M", "$76M", "$74M", "$72M", "$70M",
    "$68M", "$66M", "$64M", "$62M", "$60M",
    "$58M", "$56M", "$54M", "$52M", "$50M",
    "$48M", "$46M", "$44M", "$42M", "$40M",
    "$38M", "$36M", "$34M", "$32M", "$30M",
    "$28M", "$26M", "$24M", "$22M", "$20M",
    "$18M", "$16M", "$15M", "$14M", "$13M",
    "$12M", "$11M", "$10M", "$9M", "$8M",
  ],
};
