import type { GameList } from './types';
import { highestPaidAthletesHints } from './hints/highest-paid-athletes';

// Source: Forbes Highest-Paid Athletes 2024 list (annual earnings: salary + endorsements)
export const highestPaidAthletes: GameList = {
  id: 'highest-paid-athletes',
  name: 'Highest-Paid Athletes',
  description: 'Athletes ranked by annual earnings (Forbes 2024)',
  topics: ['sports', 'business'],
  hints: highestPaidAthletesHints,
  valueLabel: 'Earnings',
  items: [
    "Cristiano Ronaldo", "Lionel Messi", "LeBron James", "Giannis Antetokounmpo", "Kylian Mbappe",
    "Lamar Jackson", "Luka Doncic", "Stephen Curry", "Canelo Alvarez", "Neymar",
    "Jude Bellingham", "Jaylen Brown", "Joe Burrow", "Dak Prescott", "Patrick Mahomes",
    "Erling Haaland", "Karim Benzema", "Nikola Jokic", "Tyreek Hill", "Joel Embiid",
    "Kevin Durant", "Jalen Hurts", "Jon Rahm", "Mohamed Salah", "Lewis Hamilton",
    "Scottie Scheffler", "Vinicius Junior", "Russell Wilson", "Chris Jones", "Max Verstappen",
    "Jimmy Butler", "Kawhi Leonard", "Anthony Edwards", "Aaron Judge", "Shohei Ohtani",
    "Justin Herbert", "Trae Young", "Anthony Davis", "Kyrie Irving", "Paul George",
    "Kirk Cousins", "Davante Adams", "Deshaun Watson", "Karl-Anthony Towns", "Damian Lillard",
    "Bradley Beal", "Devin Booker", "Rudy Gobert", "Mike Trout", "Naomi Osaka",
    "Josh Allen", "Travis Kelce", "Jamal Adams", "Alexander Ovechkin", "Connor McDavid",
    "Tiger Woods", "Roger Federer", "Novak Djokovic", "Rafael Nadal", "Tyson Fury",
    "Conor McGregor", "Robert Lewandowski", "Kevin De Bruyne", "Harry Kane", "Bukayo Saka",
    "Sadio Mane", "Marcus Rashford", "Phil Foden", "Rodri", "Florian Wirtz",
    "Jadon Sancho", "Trent Alexander-Arnold", "Declan Rice", "Martin Odegaard", "Bruno Fernandes",
    "Casemiro", "Darwin Nunez", "Federico Valverde", "Bernardo Silva", "Lautaro Martinez",
    "Dani Olmo", "Pedri", "Aurelien Tchouameni", "Eduardo Camavinga", "Achraf Hakimi",
    "Ousmane Dembele", "Randal Kolo Muani", "Bradley Barcola", "Jamal Musiala", "Leroy Sane",
    "Joshua Kimmich", "Serge Gnabry", "Thomas Muller", "Manuel Neuer", "Matthijs de Ligt",
    "Frenkie de Jong", "Raphinha", "Jules Kounde", "Ronald Araujo", "Ferran Torres",
  ],
  values: [
    "$260M", "$135M", "$128M", "$111M", "$110M",
    "$101M", "$100M", "$100M", "$97M", "$80M",
    "$76M", "$75M", "$73M", "$72M", "$71M",
    "$70M", "$68M", "$66M", "$64M", "$63M",
    "$62M", "$61M", "$60M", "$59M", "$58M",
    "$57M", "$56M", "$55M", "$54M", "$53M",
    "$52M", "$52M", "$51M", "$50M", "$50M",
    "$49M", "$48M", "$48M", "$47M", "$46M",
    "$45M", "$45M", "$45M", "$44M", "$44M",
    "$43M", "$43M", "$42M", "$42M", "$42M",
    "$41M", "$41M", "$40M", "$40M", "$40M",
    "$39M", "$39M", "$38M", "$38M", "$38M",
    "$37M", "$37M", "$37M", "$36M", "$36M",
    "$36M", "$35M", "$35M", "$35M", "$34M",
    "$34M", "$34M", "$33M", "$33M", "$33M",
    "$32M", "$32M", "$32M", "$31M", "$31M",
    "$31M", "$30M", "$30M", "$30M", "$30M",
    "$29M", "$29M", "$29M", "$29M", "$28M",
    "$28M", "$28M", "$28M", "$28M", "$27M",
    "$27M", "$27M", "$27M", "$27M", "$27M",
  ],
  newUntil: '2026-05-14',
};
