import type { GameList } from './types';
import { highestPaidAthletesHints } from './hints/highest-paid-athletes';

// Source: Sportico "Highest-Paid Athletes in the World: Full List"
// Published: January 14, 2026 | Covers: 2025 calendar year earnings (salary + endorsements)
// URL: https://www.sportico.com/feature/highest-paid-athletes-in-the-world-1234765608/
export const highestPaidAthletes: GameList = {
  id: 'highest-paid-athletes',
  name: 'Highest-Paid Athletes',
  description: 'Athletes ranked by annual earnings — salary, bonuses, and endorsements (Sportico 2025)',
  topics: ['sports', 'business'],
  hints: highestPaidAthletesHints,
  valueLabel: 'Earnings',
  items: [
    "Cristiano Ronaldo", "Canelo Álvarez", "Lionel Messi", "Juan Soto", "LeBron James",
    "Karim Benzema", "Stephen Curry", "Shohei Ohtani", "Kevin Durant", "Jon Rahm",
    "Lewis Hamilton", "Kylian Mbappé", "Giannis Antetokounmpo", "Rory McIlroy", "Max Verstappen",
    "Scottie Scheffler", "Patrick Mahomes", "Erling Haaland", "Josh Allen", "Justin Herbert",
    "Blake Snell", "Terence Crawford", "Bryson DeChambeau", "Anthony Edwards", "Naoya Inoue",
    "Joel Embiid", "Jayson Tatum", "Jimmy Butler", "Nikola Jokic", "Jake Paul",
    "Neymar", "Devin Booker", "Lando Norris", "Vinícius Júnior", "Dak Prescott",
    "Carlos Alcaraz", "Luka Dončić", "Shai Gilgeous-Alexander", "Damian Lillard", "Karl-Anthony Towns",
    "Tiger Woods", "Kawhi Leonard", "Tua Tagovailoa", "Mohamed Salah", "Riyad Mahrez",
    "Tyrese Haliburton", "Paul George", "James Harden", "Jaylen Brown", "Brock Purdy",
    "Jannik Sinner", "Anthony Davis", "Sadio Mané", "Travis Kelce", "Donovan Mitchell",
    "Micah Parsons", "Jalen Hurts", "Matthew Stafford", "Trevor Lawrence", "Trae Young",
    "Zach LaVine", "Zion Williamson", "Joaquin Niemann", "Aaron Judge", "Kyrie Irving",
    "Deshaun Watson", "Lamar Jackson", "T.J. Watt", "Ja Morant", "Bradley Beal",
    "Ja'Marr Chase", "Jamal Murray", "Pascal Siakam", "Lauri Markkanen", "Harry Kane",
    "Franz Wagner", "Zack Wheeler", "Geno Smith", "LaMelo Ball", "Domantas Sabonis",
    "Michael Porter Jr.", "Jacob deGrom", "Joe Burrow", "De'Aaron Fox", "Rudy Gobert",
    "Mike Trout", "Justin Jefferson", "Sam Darnold", "Jude Bellingham", "Baker Mayfield",
    "Darius Garland", "Tyrese Maxey", "Cade Cunningham", "Anthony Rendon", "Rashawn Slater",
    "Gerrit Cole", "Cam Ward", "Oscar Piastri", "Robert Lewandowski", "OG Anunoby",
  ],
  values: [
    "$260M", "$137M", "$130M", "$129.2M", "$128.7M",
    "$115M", "$105.4M", "$102.5M", "$100.8M", "$100.7M",
    "$100M", "$95M", "$94.3M", "$91.2M", "$83M",
    "$82.9M", "$80.3M", "$77.9M", "$73.2M", "$71.1M",
    "$66M", "$66M", "$62.7M", "$62.2M", "$62M",
    "$61M", "$60.4M", "$60.3M", "$60.2M", "$60M",
    "$60M", "$59M", "$59M", "$58M", "$57.8M",
    "$57.8M", "$57.7M", "$56.5M", "$56.4M", "$54.7M",
    "$54.4M", "$54.1M", "$54M", "$54M", "$53.5M",
    "$53.4M", "$53.3M", "$50.9M", "$50.7M", "$50.1M",
    "$50.1M", "$50M", "$50M", "$49.6M", "$49.3M",
    "$49.3M", "$48.9M", "$48.1M", "$48M", "$47.7M",
    "$47.6M", "$47.4M", "$47.2M", "$47.1M", "$46.9M",
    "$46.8M", "$46.4M", "$46.1M", "$44.5M", "$44.5M",
    "$44.4M", "$44.3M", "$44M", "$43.9M", "$43.3M",
    "$42.5M", "$42.3M", "$41.5M", "$41M", "$41M",
    "$40.6M", "$40.3M", "$40.3M", "$39.6M", "$39.6M",
    "$39.5M", "$39.5M", "$39.5M", "$39.5M", "$39.4M",
    "$38.6M", "$38.5M", "$38.2M", "$38.1M", "$38.1M",
    "$38M", "$38M", "$38M", "$38M", "$37.9M",
  ],
  newUntil: '2026-07-14',
};
