import type { GameList } from './types';
import { imdbTopMoviesHints } from './hints/imdb-top-movies';

export const imdbTopMovies: GameList = {
  id: 'imdb-top-movies',
  name: 'Highest-Rated IMDb Movies',
  description: 'Top 100 movies by IMDb user rating (IMDb datasets, April 2026)',
  topics: ['film & tv'],
  hints: imdbTopMoviesHints,
  valueLabel: 'IMDb Rating',
  items: [
    "The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Lord of the Rings: The Return of the King", "12 Angry Men",
    "The Godfather Part II", "Schindler's List", "The Lord of the Rings: The Fellowship of the Ring", "Fight Club", "Pulp Fiction",
    "The Lord of the Rings: The Two Towers", "Inception", "The Good, the Bad and the Ugly", "Forrest Gump", "GoodFellas",
    "Interstellar", "Star Wars: Episode V - The Empire Strikes Back", "The Matrix", "Terminator 2: Judgment Day", "Jai Bhim",
    "Star Wars: Episode IV - A New Hope", "The Silence of the Lambs", "Seven Samurai", "It's a Wonderful Life", "The Green Mile",
    "One Flew Over the Cuckoo's Nest", "Life Is Beautiful", "Seven", "City of God", "Saving Private Ryan",
    "Spirited Away", "Cinema Paradiso", "Parasite", "The Departed", "City Lights",
    "Gladiator", "The Pianist", "Alien", "The Prestige", "Psycho",
    "Whiplash", "Back to the Future", "The Usual Suspects", "The Kashmir Files", "Casablanca",
    "American History X", "Once Upon a Time in the West", "Leon: The Professional", "The Intouchables", "Django Unchained",
    "Rear Window", "The Lion King", "Grave of the Fireflies", "Modern Times", "Spider-Man: Across the Spider-Verse",
    "The Shining", "Spider-Man: Into the Spider-Verse", "Avengers: Endgame", "Avengers: Infinity War", "Dune: Part Two",
    "The Dark Knight Rises", "Aliens", "Good Will Hunting", "Memento", "Raiders of the Lost Ark",
    "The Lives of Others", "The Great Dictator", "Coco", "Amadeus", "Inglourious Basterds",
    "Your Name.", "Sunset Boulevard", "3 Idiots", "WALL-E", "Paths of Glory",
    "Apocalypse Now", "Singin' in the Rain", "North by Northwest", "Star Wars: Episode VI - Return of the Jedi", "Oldboy",
    "Toy Story", "Eternal Sunshine of the Spotless Mind", "A Separation", "Lawrence of Arabia", "Reservoir Dogs",
    "Once Upon a Time in America", "Princess Mononoke", "The Hunt", "2001: A Space Odyssey", "Requiem for a Dream",
    "Joker", "American Beauty", "Braveheart", "Up", "Amelie",
    "Dr. Strangelove", "Scarface", "Das Boot", "Toy Story 3", "Heat",
  ],
  values: [
    "9.3", "9.2", "9.1", "9.0", "9.0",
    "9.0", "9.0", "8.9", "8.8", "8.8",
    "8.8", "8.8", "8.8", "8.8", "8.7",
    "8.7", "8.7", "8.7", "8.6", "8.6",
    "8.6", "8.6", "8.6", "8.6", "8.6",
    "8.6", "8.6", "8.6", "8.6", "8.6",
    "8.6", "8.5", "8.5", "8.5", "8.5",
    "8.5", "8.5", "8.5", "8.5", "8.5",
    "8.5", "8.5", "8.5", "8.5", "8.5",
    "8.5", "8.5", "8.5", "8.5", "8.5",
    "8.5", "8.5", "8.5", "8.5", "8.5",
    "8.4", "8.4", "8.4", "8.4", "8.4",
    "8.4", "8.4", "8.4", "8.4", "8.4",
    "8.4", "8.4", "8.4", "8.4", "8.4",
    "8.4", "8.4", "8.4", "8.4", "8.4",
    "8.4", "8.3", "8.3", "8.3", "8.3",
    "8.3", "8.3", "8.3", "8.3", "8.3",
    "8.3", "8.3", "8.3", "8.3", "8.3",
    "8.3", "8.3", "8.3", "8.3", "8.3",
    "8.3", "8.3", "8.3", "8.3", "8.3",
  ],
  newUntil: '2026-05-14',
};
