import type { GameList } from './types';
import { imdbTopTvShowsHints } from './hints/imdb-top-tv-shows';

export const imdbTopTvShows: GameList = {
  id: 'imdb-top-tv-shows',
  name: 'Highest-Rated IMDb TV Shows',
  description: 'Top 100 TV shows by IMDb user rating (IMDb datasets, April 2026)',
  topics: ['film & tv'],
  hints: imdbTopTvShowsHints,
  valueLabel: 'IMDb Rating',
  items: [
    "Breaking Bad", "Band of Brothers", "Planet Earth", "Planet Earth II", "Chernobyl",
    "Avatar: The Last Airbender", "The Wire", "Blue Planet II", "Cosmos", "Bluey",
    "Game of Thrones", "The Sopranos", "Cosmos: A Spacetime Odyssey", "Our Planet", "The World at War",
    "Attack on Titan", "Fullmetal Alchemist: Brotherhood", "Sherlock", "Better Call Saul", "The Office",
    "Rick and Morty", "Arcane", "One Piece", "Hunter x Hunter", "The Last Dance",
    "Batman: The Animated Series", "The Twilight Zone", "Death Note", "Seinfeld", "Firefly",
    "Gravity Falls", "Cowboy Bebop", "The West Wing", "Frieren: Beyond Journey's End", "Nathan for You",
    "Friends", "True Detective", "Fargo", "Succession", "It's Always Sunny in Philadelphia",
    "BoJack Horseman", "Dragon Ball Z", "Curb Your Enthusiasm", "Freaks and Geeks", "When They See Us",
    "Vinland Saga", "Fawlty Towers", "Last Week Tonight with John Oliver", "Pride and Prejudice", "Steins;Gate",
    "Monty Python's Flying Circus", "Chappelle's Show", "Blackadder Goes Forth", "Peaky Blinders", "Black Mirror",
    "House", "Dark", "Narcos", "South Park", "Ted Lasso",
    "Invincible", "Mad Men", "Downton Abbey", "Twin Peaks", "Fleabag",
    "Naruto: Shippuden", "Rome", "Battlestar Galactica", "Six Feet Under", "Star Trek: The Next Generation",
    "The X-Files", "Stranger Things", "Dexter", "The Boys", "The Mandalorian",
    "House of Cards", "Daredevil", "The Simpsons", "Mindhunter", "Severance",
    "Arrested Development", "Parks and Recreation", "Yellowstone", "The Crown", "Andor",
    "Shogun", "One Punch Man", "Demon Slayer", "Boardwalk Empire", "The Last of Us",
    "The Queen's Gambit", "Vikings", "Mr. Robot", "The Bear", "Hannibal",
    "Community", "Modern Family", "The Penguin", "Brooklyn Nine-Nine", "Suits",
  ],
  values: [
    "9.5", "9.4", "9.4", "9.4", "9.3",
    "9.3", "9.3", "9.3", "9.3", "9.3",
    "9.2", "9.2", "9.2", "9.2", "9.2",
    "9.1", "9.1", "9.0", "9.0", "9.0",
    "9.0", "9.0", "9.0", "9.0", "9.0",
    "9.0", "9.0", "8.9", "8.9", "8.9",
    "8.9", "8.9", "8.9", "8.9", "8.9",
    "8.8", "8.8", "8.8", "8.8", "8.8",
    "8.8", "8.8", "8.8", "8.8", "8.8",
    "8.8", "8.8", "8.8", "8.8", "8.8",
    "8.8", "8.8", "8.8", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
  ],
  newUntil: '2026-05-14',
};
