import type { GameList } from './types';
import { imdbTopMoviesHints } from './hints/imdb-top-movies';

export const imdbTopMovies: GameList = {
  id: 'imdb-top-movies',
  name: 'Highest-Rated IMDb Movies',
  description: 'Top 100 movies by IMDb user rating (IMDb datasets, April 2026)',
  topics: ['film & tv'],
  hints: imdbTopMoviesHints,
  valueLabel: 'IMDb Rating',
  items: [
    "The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Lord of the Rings: The Return of the King", "Schindler's List",
    "The Godfather Part II", "12 Angry Men", "The Lord of the Rings: The Fellowship of the Ring", "Inception", "Fight Club",
    "Forrest Gump", "Pulp Fiction", "The Lord of the Rings: The Two Towers", "The Good, the Bad and the Ugly", "Interstellar",
    "The Matrix", "Star Wars: Episode V - The Empire Strikes Back", "GoodFellas", "Seven", "The Silence of the Lambs",
    "Saving Private Ryan", "Star Wars: Episode IV - A New Hope", "The Green Mile", "Terminator 2: Judgment Day", "One Flew Over the Cuckoo's Nest",
    "Spirited Away", "City of God", "Life Is Beautiful", "It's a Wonderful Life", "Seven Samurai",
    "Jai Bhim", "Django Unchained", "Gladiator", "The Prestige", "The Departed",
    "Back to the Future", "Leon: The Professional", "American History X", "The Lion King", "The Usual Suspects",
    "Parasite", "Whiplash", "Alien", "The Intouchables", "The Pianist",
    "Psycho", "Casablanca", "The Kashmir Files", "Rear Window", "Spider-Man: Across the Spider-Verse",
    "Once Upon a Time in the West", "Grave of the Fireflies", "Cinema Paradiso", "Modern Times", "City Lights",
    "The Dark Knight Rises", "Inglourious Basterds", "Avengers: Endgame", "Memento", "Avengers: Infinity War",
    "WALL-E", "The Shining", "Good Will Hunting", "Raiders of the Lost Ark", "Aliens",
    "Spider-Man: Into the Spider-Verse", "Apocalypse Now", "Dune: Part Two", "Coco", "3 Idiots",
    "Amadeus", "The Lives of Others", "Your Name.", "Sunset Boulevard", "The Great Dictator",
    "Paths of Glory", "Joker", "American Beauty", "Up", "Star Wars: Episode VI - Return of the Jedi",
    "Eternal Sunshine of the Spotless Mind", "Toy Story", "Reservoir Dogs", "Braveheart", "Scarface",
    "Requiem for a Dream", "Toy Story 3", "Amelie", "Heat", "2001: A Space Odyssey",
    "Oldboy", "Dr. Strangelove", "Princess Mononoke", "Once Upon a Time in America", "The Hunt",
    "North by Northwest", "Lawrence of Arabia", "Das Boot", "Singin' in the Rain", "A Separation",
  ],
  values: [
    "9.3", "9.2", "9.1", "9.0", "9.0",
    "9.0", "9.0", "8.9", "8.8", "8.8",
    "8.8", "8.8", "8.8", "8.8", "8.7",
    "8.7", "8.7", "8.7", "8.6", "8.6",
    "8.6", "8.6", "8.6", "8.6", "8.6",
    "8.6", "8.6", "8.6", "8.6", "8.6",
    "8.6", "8.5", "8.5", "8.5", "8.5",
    "8.5", "8.5", "8.5", "8.5", "8.5",
    "8.5", "8.5", "8.5", "8.5", "8.5",
    "8.5", "8.5", "8.5", "8.5", "8.5",
    "8.5", "8.5", "8.5", "8.5", "8.5",
    "8.4", "8.4", "8.4", "8.4", "8.4",
    "8.4", "8.4", "8.4", "8.4", "8.4",
    "8.4", "8.4", "8.4", "8.4", "8.4",
    "8.4", "8.4", "8.4", "8.4", "8.4",
    "8.4", "8.3", "8.3", "8.3", "8.3",
    "8.3", "8.3", "8.3", "8.3", "8.3",
    "8.3", "8.3", "8.3", "8.3", "8.3",
    "8.3", "8.3", "8.3", "8.3", "8.3",
    "8.3", "8.3", "8.3", "8.3", "8.3",
  ],
  newUntil: '2026-05-14',
};
