import type { GameList } from './types';
import { imdbTopTvShowsHints } from './hints/imdb-top-tv-shows';

export const imdbTopTvShows: GameList = {
  id: 'imdb-top-tv-shows',
  name: 'Highest-Rated IMDb TV Shows',
  description: 'Top 100 TV shows by IMDb user rating (IMDb datasets, April 2026)',
  topics: ['film & tv'],
  difficulty: 2,
  hints: imdbTopTvShowsHints,
  valueLabel: 'IMDb Rating',
  items: [
    "Breaking Bad", "Planet Earth II", "Planet Earth", "Band of Brothers", "Chernobyl",
    "Blue Planet II", "Avatar: The Last Airbender", "Bluey", "Cosmos", "The Wire",
    "Cosmos: A Spacetime Odyssey", "Game of Thrones", "The Sopranos", "The World at War", "Our Planet",
    "Attack on Titan", "Fullmetal Alchemist: Brotherhood", "One Piece", "Batman: The Animated Series", "Arcane",
    "Better Call Saul", "Sherlock", "The Office", "The Last Dance", "Rick and Morty",
    "Hunter x Hunter", "The Twilight Zone", "Gravity Falls", "Firefly", "Cowboy Bebop",
    "The West Wing", "Death Note", "Seinfeld", "Nathan for You", "Frieren: Beyond Journey's End",
    "BoJack Horseman", "Fargo", "Dragon Ball Z", "When They See Us", "Fawlty Towers",
    "Steins;Gate", "Freaks and Geeks", "Monty Python's Flying Circus", "Pride and Prejudice", "Friends",
    "Chappelle's Show", "Succession", "Curb Your Enthusiasm", "Blackadder Goes Forth", "Vinland Saga",
    "It's Always Sunny in Philadelphia", "Last Week Tonight with John Oliver", "True Detective", "Black Mirror", "Six Feet Under",
    "Star Trek: The Next Generation", "The Penguin", "Twin Peaks", "Invincible", "Mad Men",
    "One Punch Man", "Community", "Vikings", "House", "The Boys",
    "Modern Family", "Brooklyn Nine-Nine", "The Mandalorian", "Peaky Blinders", "The X-Files",
    "Fleabag", "Boardwalk Empire", "Arrested Development", "Mindhunter", "Dark",
    "Mr. Robot", "Narcos", "The Bear", "The Queen's Gambit", "Rome",
    "House of Cards", "Suits", "Naruto: Shippuden", "Daredevil", "Yellowstone",
    "The Last of Us", "Hannibal", "Battlestar Galactica", "Dexter", "Demon Slayer",
    "Stranger Things", "Severance", "The Simpsons", "The Crown", "Downton Abbey",
    "Andor", "Ted Lasso", "Shogun", "Parks and Recreation", "South Park",
  ],
  values: [
    "9.5", "9.4", "9.4", "9.4", "9.3",
    "9.3", "9.3", "9.3", "9.3", "9.3",
    "9.2", "9.2", "9.2", "9.2", "9.2",
    "9.1", "9.1", "9.0", "9.0", "9.0",
    "9.0", "9.0", "9.0", "9.0", "9.0",
    "9.0", "9.0", "8.9", "8.9", "8.9",
    "8.9", "8.9", "8.9", "8.9", "8.9",
    "8.8", "8.8", "8.8", "8.8", "8.8",
    "8.8", "8.8", "8.8", "8.8", "8.8",
    "8.8", "8.8", "8.8", "8.8", "8.8",
    "8.8", "8.8", "8.8", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
    "8.7", "8.7", "8.7", "8.7", "8.7",
  ],
  newUntil: '2026-05-14',
};
