import type { GameList } from './types';

export const largestGreekOrganizations: GameList = {
  id: 'largest-greek-organizations',
  name: 'Largest Fraternities & Sororities',
  description: 'Largest NIC fraternities and NPC sororities ranked by active collegiate chapters',
  topics: ['education'],
  difficulty: 3,
  size: 50,
  newUntil: '2026-05-15',
  items: [
    "Tau Kappa Epsilon",
    "Chi Omega",
    "Kappa Sigma",
    "Sigma Alpha Epsilon",
    "Sigma Chi",
    "Alpha Omicron Pi",
    "Pi Kappa Alpha",
    "Sigma Phi Epsilon",
    "Zeta Tau Alpha",
    "Delta Zeta",
    "Lambda Chi Alpha",
    "Alpha Phi",
    "Kappa Alpha Theta",
    "Delta Gamma",
    "Sigma Nu",
    "Pi Kappa Phi",
    "Phi Delta Theta",
    "Kappa Delta",
    "Alpha Delta Pi",
    "Gamma Phi Beta",
    "Alpha Tau Omega",
    "Delta Delta Delta",
    "Beta Theta Pi",
    "Alpha Chi Omega",
    "Delta Tau Delta",
    "Phi Gamma Delta",
    "Phi Mu",
    "Pi Beta Phi",
    "Sigma Kappa",
    "Kappa Kappa Gamma",
    "Alpha Xi Delta",
    "Sigma Sigma Sigma",
    "Delta Chi",
    "Alpha Sigma Phi",
    "Kappa Alpha Order",
    "Delta Upsilon",
    "Theta Chi",
    "Alpha Gamma Delta",
    "Delta Sigma Phi",
    "Phi Kappa Psi",
    "Alpha Sigma Alpha",
    "Sigma Tau Gamma",
    "Alpha Epsilon Pi",
    "Phi Sigma Kappa",
    "Alpha Sigma Tau",
    "Phi Kappa Tau",
    "Kappa Delta Rho",
    "Sigma Pi",
    "Theta Phi Alpha",
    "Alpha Gamma Rho",
  ],
  hints: [
    "Tau Kappa Epsilon", "TKE",
    "Chi Omega",
    "Kappa Sigma",
    "Sigma Alpha Epsilon", "SAE",
    "Sigma Chi",
    "Alpha Omicron Pi", "AOPi",
    "Pi Kappa Alpha", "Pike",
    "Sigma Phi Epsilon",
    "Zeta Tau Alpha", "ZTA",
    "Delta Zeta", "DZ",
    "Lambda Chi Alpha",
    "Alpha Phi",
    "Kappa Alpha Theta",
    "Delta Gamma", "DG",
    "Sigma Nu",
    "Pi Kappa Phi",
    "Phi Delta Theta",
    "Kappa Delta", "KD",
    "Alpha Delta Pi", "ADPi",
    "Gamma Phi Beta",
    "Alpha Tau Omega", "ATO",
    "Delta Delta Delta", "Tri Delta",
    "Beta Theta Pi",
    "Alpha Chi Omega",
    "Delta Tau Delta",
    "Phi Gamma Delta", "Fiji",
    "Phi Mu",
    "Pi Beta Phi",
    "Sigma Kappa",
    "Kappa Kappa Gamma", "KKG",
    "Alpha Xi Delta",
    "Sigma Sigma Sigma", "Tri Sigma",
    "Delta Chi",
    "Alpha Sigma Phi",
    "Kappa Alpha Order", "KA",
    "Delta Upsilon", "DU",
    "Theta Chi",
    "Alpha Gamma Delta",
    "Delta Sigma Phi",
    "Phi Kappa Psi",
    "Alpha Sigma Alpha",
    "Sigma Tau Gamma",
    "Alpha Epsilon Pi", "AEPi",
    "Phi Sigma Kappa",
    "Alpha Sigma Tau",
    "Phi Kappa Tau",
    "Kappa Delta Rho", "KDR",
    "Sigma Pi",
    "Theta Phi Alpha",
    "Alpha Gamma Rho",
    // NPHC (Divine Nine) — strike-bait candidates, not in top 50
    "Alpha Kappa Alpha", "AKA",
    "Delta Sigma Theta",
    "Alpha Phi Alpha",
    "Omega Psi Phi", "Ques",
    "Kappa Alpha Psi", "Nupes",
    "Zeta Phi Beta",
    "Sigma Gamma Rho",
    "Phi Beta Sigma",
    "Iota Phi Theta",
    // Other well-known Greek orgs — strike-bait
    "Delta Phi Epsilon",
    "Phi Sigma Sigma",
    "Sigma Delta Tau",
    "Alpha Epsilon Phi",
    "Chi Psi",
    "Delta Kappa Epsilon", "DKE", "Deke",
    "Psi Upsilon",
    "Zeta Beta Tau", "ZBT",
    "Phi Kappa Sigma",
    "Phi Kappa Theta",
    "Acacia",
    "FarmHouse",
    "Triangle",
    "Theta Xi",
    "Sigma Alpha Mu", "Sammy",
    "Chi Phi",
    "Theta Delta Chi",
    "Pi Lambda Phi",
    "Alpha Delta Phi",
    "Delta Phi",
    "Zeta Psi",
    "Tau Epsilon Phi", "TEP",
    "Alpha Delta Gamma",
    "Beta Sigma Psi",
    "Phi Mu Delta",
    "Alpha Kappa Lambda",
    "Delta Lambda Phi",
    "Beta Chi Theta",
    "Beta Upsilon Chi",
    "Alpha Phi Delta",
    "Sigma Phi Delta",
    "Sigma Phi",
    "Phi Lambda Chi",
    "Alpha Chi Rho",
    "Delta Psi",
    "Phi Sigma Phi",
    "Lambda Phi Epsilon",
    "Lambda Theta Alpha",
    "Lambda Theta Phi",
    "Phi Iota Alpha",
    "Sigma Lambda Beta",
    "Sigma Lambda Gamma",
    "Alpha Kappa Delta Phi",
    "Kappa Phi Lambda",
    "Sigma Beta Rho",
    "Omega Delta Phi",
    "Nu Alpha Kappa",
    "Pi Delta Psi",
    "Delta Phi Lambda",
    "Sigma Alpha",
    "Phi Sigma Rho",
    "Alpha Omega Epsilon",
  ],
  aliases: {
    "TKE": "Tau Kappa Epsilon",
    "SAE": "Sigma Alpha Epsilon",
    "AOPi": "Alpha Omicron Pi",
    "Pike": "Pi Kappa Alpha",
    "ZTA": "Zeta Tau Alpha",
    "DZ": "Delta Zeta",
    "DG": "Delta Gamma",
    "KD": "Kappa Delta",
    "ADPi": "Alpha Delta Pi",
    "ATO": "Alpha Tau Omega",
    "Tri Delta": "Delta Delta Delta",
    "Fiji": "Phi Gamma Delta",
    "FIJI": "Phi Gamma Delta",
    "KKG": "Kappa Kappa Gamma",
    "Tri Sigma": "Sigma Sigma Sigma",
    "KA": "Kappa Alpha Order",
    "DU": "Delta Upsilon",
    "AEPi": "Alpha Epsilon Pi",
    "KDR": "Kappa Delta Rho",
  },
};
