import type { GameList } from './types';
import { largestCollegePopulationsHints } from './hints';

export const largestCollegePopulations: GameList = {
  id: 'largest-college-populations',
  name: 'Largest US Colleges by Enrollment',
  description: 'US colleges and universities ranked by total enrollment (NCES/IPEDS)',
  topics: ['education', 'misc'],
  difficulty: 2,
  hints: largestCollegePopulationsHints,
  valueLabel: 'Students',
  items: [
    "University of Central Florida", "Texas A&M", "Ohio State", "Florida International University", "University of Florida",
    "Liberty University", "Arizona State", "University of Texas at Austin", "Michigan State", "Penn State",
    "University of Minnesota", "University of Illinois Urbana-Champaign", "Florida State", "Purdue", "Indiana University",
    "University of South Florida", "University of Michigan", "Rutgers", "University of Houston", "NYU",
    "University of Wisconsin-Madison", "University of Arizona", "University of Georgia", "Georgia State", "University of Washington",
    "University of North Texas", "University of Maryland", "UCLA", "Texas State", "University of Alabama",
    "University of Cincinnati", "Virginia Tech", "University of Kentucky", "Iowa State", "Temple",
    "UC Berkeley", "University of Colorado Boulder", "University of Iowa", "NC State", "University of Oklahoma",
    "University of Tennessee", "University of Oregon", "Brigham Young University", "University of Nebraska", "University of South Carolina",
    "University of Missouri", "California State University Northridge", "University of Kansas", "California State University Fullerton", "University of North Carolina at Charlotte",
    "Auburn", "San Diego State", "Colorado State", "University of Connecticut", "West Virginia University",
    "Oregon State", "University of Utah", "University of Pittsburgh", "Clemson", "Boston University",
    "George Mason University", "University of Nevada Las Vegas", "Baylor", "SUNY Buffalo", "Syracuse",
    "San Jose State", "Louisiana State University", "University of Arkansas", "California State University Long Beach", "University of Mississippi",
    "Wayne State University", "University of New Mexico", "Kent State", "Portland State", "Old Dominion University",
    "University of Memphis", "Towson University", "Northern Arizona University", "California State Polytechnic Pomona", "Florida Atlantic University",
    "East Carolina University", "University of Louisville", "Western Michigan University", "Central Michigan University", "Kansas State",
    "University of Denver", "Kennesaw State", "USC", "Texas Tech", "Mississippi State",
    "Oklahoma State", "UNC Chapel Hill", "Washington State", "University of Delaware", "Ball State",
    "Illinois State", "Stony Brook University", "University of Massachusetts Amherst", "Miami University (Ohio)", "Northeastern",
  ],
  values: [
    "73K", "72K", "68K", "64K", "60K",
    "58K", "57K", "55K", "53K", "52K",
    "52K", "51K", "50K", "49K", "49K",
    "49K", "48K", "48K", "47K", "47K",
    "46K", "46K", "45K", "45K", "44K",
    "44K", "43K", "43K", "42K", "42K",
    "41K", "41K", "40K", "40K", "39K",
    "39K", "38K", "38K", "37K", "37K",
    "36K", "36K", "36K", "35K", "35K",
    "35K", "34K", "34K", "34K", "33K",
    "33K", "33K", "32K", "32K", "32K",
    "31K", "31K", "31K", "30K", "30K",
    "30K", "30K", "29K", "29K", "29K",
    "29K", "28K", "28K", "28K", "28K",
    "27K", "27K", "27K", "27K", "26K",
    "26K", "26K", "26K", "25K", "25K",
    "25K", "25K", "24K", "24K", "24K",
    "24K", "24K", "23K", "23K", "23K",
    "23K", "23K", "22K", "22K", "22K",
    "22K", "21K", "21K", "21K", "21K",
  ],
};
