import type { GameList } from './types';

export const largestGreekOrganizations: GameList = {
  id: 'largest-greek-organizations',
  name: 'Greek Fraternities & Sororities',
  description: 'North American Greek letter organizations',
  topics: ['education'],
  size: 126,
  newUntil: '2026-05-15',
  items: [
    // Ranked roughly by number of active collegiate chapters
    // 1–50: Largest NIC fraternities and NPC sororities
    "Tau Kappa Epsilon",
    "Chi Omega",
    "Kappa Sigma",
    "Sigma Alpha Epsilon",
    "Sigma Chi",
    "Alpha Omicron Pi",
    "Pi Kappa Alpha",
    "Sigma Phi Epsilon",
    "Zeta Tau Alpha",
    "Delta Zeta",
    "Lambda Chi Alpha",
    "Alpha Phi",
    "Kappa Alpha Theta",
    "Delta Gamma",
    "Sigma Nu",
    "Pi Kappa Phi",
    "Phi Delta Theta",
    "Kappa Delta",
    "Alpha Delta Pi",
    "Gamma Phi Beta",
    "Alpha Tau Omega",
    "Delta Delta Delta",
    "Beta Theta Pi",
    "Alpha Chi Omega",
    "Delta Tau Delta",
    "Phi Gamma Delta",
    "Phi Mu",
    "Pi Beta Phi",
    "Sigma Kappa",
    "Kappa Kappa Gamma",
    "Alpha Xi Delta",
    "Sigma Sigma Sigma",
    "Delta Chi",
    "Alpha Sigma Phi",
    "Kappa Alpha Order",
    "Delta Upsilon",
    "Theta Chi",
    "Alpha Gamma Delta",
    "Delta Sigma Phi",
    "Phi Kappa Psi",
    "Alpha Sigma Alpha",
    "Sigma Tau Gamma",
    "Alpha Epsilon Pi",
    "Phi Sigma Kappa",
    "Alpha Sigma Tau",
    "Phi Kappa Tau",
    "Kappa Delta Rho",
    "Sigma Pi",
    "Theta Phi Alpha",
    "Alpha Gamma Rho",
    // 51–59: NPHC (Divine Nine)
    "Alpha Kappa Alpha",
    "Delta Sigma Theta",
    "Alpha Phi Alpha",
    "Omega Psi Phi",
    "Kappa Alpha Psi",
    "Zeta Phi Beta",
    "Sigma Gamma Rho",
    "Phi Beta Sigma",
    "Iota Phi Theta",
    // 60–80: Mid-size NPC sororities and NIC fraternities
    "Delta Phi Epsilon",
    "Phi Sigma Sigma",
    "Sigma Delta Tau",
    "Alpha Epsilon Phi",
    "Chi Psi",
    "Delta Kappa Epsilon",
    "Psi Upsilon",
    "Zeta Beta Tau",
    "Phi Kappa Sigma",
    "Phi Kappa Theta",
    "Acacia",
    "FarmHouse",
    "Triangle",
    "Theta Xi",
    "Sigma Alpha Mu",
    "Chi Phi",
    "Theta Delta Chi",
    "Pi Lambda Phi",
    "Alpha Delta Phi",
    "Delta Phi",
    "Zeta Psi",
    // 81–95: Smaller NIC fraternities
    "Tau Epsilon Phi",
    "Alpha Delta Gamma",
    "Beta Sigma Psi",
    "Phi Mu Delta",
    "Alpha Kappa Lambda",
    "Delta Lambda Phi",
    "Beta Chi Theta",
    "Beta Upsilon Chi",
    "Alpha Phi Delta",
    "Sigma Phi Delta",
    "Sigma Phi",
    "Phi Lambda Chi",
    "Alpha Chi Rho",
    "Delta Psi",
    "Phi Sigma Phi",
    // 96–126: Multicultural and specialty organizations
    "Lambda Phi Epsilon",
    "Lambda Theta Alpha",
    "Lambda Theta Phi",
    "Lambda Upsilon Lambda",
    "Phi Iota Alpha",
    "Sigma Lambda Beta",
    "Sigma Lambda Gamma",
    "Alpha Kappa Delta Phi",
    "Kappa Phi Lambda",
    "Lambda Pi Chi",
    "Sigma Beta Rho",
    "Delta Epsilon Psi",
    "Lambda Sigma Upsilon",
    "Omega Phi Beta",
    "Omega Delta Phi",
    "Nu Alpha Kappa",
    "Chi Sigma Tau",
    "Sigma Iota Alpha",
    "Gamma Phi Omega",
    "Kappa Phi Gamma",
    "Alpha Psi Lambda",
    "Delta Sigma Iota",
    "Sigma Psi Zeta",
    "Delta Xi Phi",
    "Mu Sigma Upsilon",
    "Theta Nu Xi",
    "Pi Delta Psi",
    "Delta Phi Lambda",
    "Sigma Alpha",
    "Phi Sigma Rho",
    "Alpha Omega Epsilon",
  ],
  hints: [
    // All 126 items with well-known abbreviations
    "Tau Kappa Epsilon", "TKE",
    "Chi Omega",
    "Kappa Sigma",
    "Sigma Alpha Epsilon", "SAE",
    "Sigma Chi",
    "Alpha Omicron Pi", "AOPi",
    "Pi Kappa Alpha", "Pike",
    "Sigma Phi Epsilon",
    "Zeta Tau Alpha", "ZTA",
    "Delta Zeta", "DZ",
    "Lambda Chi Alpha",
    "Alpha Phi",
    "Kappa Alpha Theta",
    "Delta Gamma", "DG",
    "Sigma Nu",
    "Pi Kappa Phi",
    "Phi Delta Theta",
    "Kappa Delta", "KD",
    "Alpha Delta Pi", "ADPi",
    "Gamma Phi Beta",
    "Alpha Tau Omega", "ATO",
    "Delta Delta Delta", "Tri Delta",
    "Beta Theta Pi",
    "Alpha Chi Omega",
    "Delta Tau Delta",
    "Phi Gamma Delta", "Fiji",
    "Phi Mu",
    "Pi Beta Phi",
    "Sigma Kappa",
    "Kappa Kappa Gamma", "KKG",
    "Alpha Xi Delta",
    "Sigma Sigma Sigma", "Tri Sigma",
    "Delta Chi",
    "Alpha Sigma Phi",
    "Kappa Alpha Order", "KA",
    "Delta Upsilon", "DU",
    "Theta Chi",
    "Alpha Gamma Delta",
    "Delta Sigma Phi",
    "Phi Kappa Psi",
    "Alpha Sigma Alpha",
    "Sigma Tau Gamma",
    "Alpha Epsilon Pi", "AEPi",
    "Phi Sigma Kappa",
    "Alpha Sigma Tau",
    "Phi Kappa Tau",
    "Kappa Delta Rho", "KDR",
    "Sigma Pi",
    "Theta Phi Alpha",
    "Alpha Gamma Rho",
    // NPHC
    "Alpha Kappa Alpha", "AKA",
    "Delta Sigma Theta",
    "Alpha Phi Alpha",
    "Omega Psi Phi", "Ques",
    "Kappa Alpha Psi", "Nupes",
    "Zeta Phi Beta",
    "Sigma Gamma Rho",
    "Phi Beta Sigma",
    "Iota Phi Theta",
    // Mid-size NPC/NIC
    "Delta Phi Epsilon", "DPhiE",
    "Phi Sigma Sigma",
    "Sigma Delta Tau",
    "Alpha Epsilon Phi",
    "Chi Psi",
    "Delta Kappa Epsilon", "DKE", "Deke",
    "Psi Upsilon",
    "Zeta Beta Tau", "ZBT",
    "Phi Kappa Sigma",
    "Phi Kappa Theta",
    "Acacia",
    "FarmHouse",
    "Triangle",
    "Theta Xi",
    "Sigma Alpha Mu", "Sammy",
    "Chi Phi",
    "Theta Delta Chi",
    "Pi Lambda Phi",
    "Alpha Delta Phi",
    "Delta Phi",
    "Zeta Psi",
    // Smaller NIC
    "Tau Epsilon Phi", "TEP",
    "Alpha Delta Gamma",
    "Beta Sigma Psi",
    "Phi Mu Delta",
    "Alpha Kappa Lambda",
    "Delta Lambda Phi",
    "Beta Chi Theta",
    "Beta Upsilon Chi",
    "Alpha Phi Delta",
    "Sigma Phi Delta",
    "Sigma Phi",
    "Phi Lambda Chi",
    "Alpha Chi Rho",
    "Delta Psi",
    "Phi Sigma Phi",
    // Multicultural and specialty
    "Lambda Phi Epsilon", "LPhiE",
    "Lambda Theta Alpha",
    "Lambda Theta Phi",
    "Lambda Upsilon Lambda",
    "Phi Iota Alpha",
    "Sigma Lambda Beta",
    "Sigma Lambda Gamma",
    "Alpha Kappa Delta Phi",
    "Kappa Phi Lambda",
    "Lambda Pi Chi",
    "Sigma Beta Rho",
    "Delta Epsilon Psi",
    "Lambda Sigma Upsilon",
    "Omega Phi Beta",
    "Omega Delta Phi",
    "Nu Alpha Kappa",
    "Chi Sigma Tau",
    "Sigma Iota Alpha",
    "Gamma Phi Omega",
    "Kappa Phi Gamma",
    "Alpha Psi Lambda",
    "Delta Sigma Iota",
    "Sigma Psi Zeta",
    "Delta Xi Phi",
    "Mu Sigma Upsilon",
    "Theta Nu Xi",
    "Pi Delta Psi",
    "Delta Phi Lambda",
    "Sigma Alpha",
    "Phi Sigma Rho",
    "Alpha Omega Epsilon",
  ],
  aliases: {
    // Well-known abbreviations and nicknames only
    "TKE": "Tau Kappa Epsilon",
    "SAE": "Sigma Alpha Epsilon",
    "AOPi": "Alpha Omicron Pi",
    "Pike": "Pi Kappa Alpha",
    "ZTA": "Zeta Tau Alpha",
    "DZ": "Delta Zeta",
    "DG": "Delta Gamma",
    "KD": "Kappa Delta",
    "ADPi": "Alpha Delta Pi",
    "ATO": "Alpha Tau Omega",
    "Tri Delta": "Delta Delta Delta",
    "Fiji": "Phi Gamma Delta",
    "FIJI": "Phi Gamma Delta",
    "KKG": "Kappa Kappa Gamma",
    "Tri Sigma": "Sigma Sigma Sigma",
    "KA": "Kappa Alpha Order",
    "DU": "Delta Upsilon",
    "AEPi": "Alpha Epsilon Pi",
    "KDR": "Kappa Delta Rho",
    "AKA": "Alpha Kappa Alpha",
    "Ques": "Omega Psi Phi",
    "Nupes": "Kappa Alpha Psi",
    "DPhiE": "Delta Phi Epsilon",
    "DKE": "Delta Kappa Epsilon",
    "Deke": "Delta Kappa Epsilon",
    "ZBT": "Zeta Beta Tau",
    "Sammy": "Sigma Alpha Mu",
    "TEP": "Tau Epsilon Phi",
    "LPhiE": "Lambda Phi Epsilon",
  },
};
