import type { GameList } from './types';
import { longestRiversHints } from './hints/longest-rivers';

export const longestRivers: GameList = {
  id: 'longest-rivers',
  name: 'Longest Rivers in the World',
  description: 'Top 100 rivers ranked by total length',
  topics: ['geography'],
  difficulty: 2,
  hints: longestRiversHints,
  valueLabel: 'Length',
  items: [
    "Nile", "Amazon", "Yangtze", "Mississippi", "Yenisey",
    "Yellow River", "Ob", "Río de la Plata", "Congo", "Amur",
    "Lena", "Mekong", "Mackenzie", "Niger", "Brahmaputra",
    "Murray", "Tocantins", "Volga", "Euphrates", "Madeira",
    "Purús", "Yukon", "Indus", "São Francisco", "Syr Darya",
    "Salween", "Saint Lawrence", "Rio Grande", "Lower Tunguska", "Colorado",
    "Danube", "Irrawaddy", "Zambezi", "Vilyuy", "Ganges",
    "Amu Darya", "Japurá", "Nelson", "Paraguay", "Kolyma",
    "Pilcomayo", "Upper Ob", "Ishim", "Orange", "Ural",
    "Juruá", "Arkansas", "Songhua", "Olenyok", "Dnieper",
    "Aldan", "Ubangi", "Negro", "Columbia", "Tapajós",
    "Pearl", "Red River", "Kasai", "Ohio", "Orinoco",
    "Tarim", "Xingu", "Jubba", "Brazos", "Northern Salado",
    "Içá", "Vitim", "Chenab", "Tigris", "Don",
    "Stony Tunguska", "Pechora", "Kama", "Limpopo", "Chulym",
    "Guaviare", "Marañón", "Indigirka", "Platte", "Senegal",
    "Khatanga", "Upper Jubba", "Uruguay", "Churchill", "Blue Nile",
    "Okavango", "Volta", "Beni", "Shilka", "Tobol",
    "Alazeya", "Kafue", "Yalong", "Magdalena", "Han",
    "Kura", "Oka", "Upper Murray", "Yana", "Pecos",
  ],
  values: [
    "6,650 km", "6,400 km", "6,300 km", "6,275 km", "5,539 km",
    "5,464 km", "5,410 km", "4,880 km", "4,700 km", "4,444 km",
    "4,400 km", "4,350 km", "4,241 km", "4,200 km", "3,969 km",
    "3,672 km", "3,650 km", "3,645 km", "3,596 km", "3,380 km",
    "3,211 km", "3,185 km", "3,180 km", "3,180 km", "3,078 km",
    "3,060 km", "3,058 km", "3,057 km", "2,989 km", "2,945 km",
    "2,888 km", "2,809 km", "2,740 km", "2,720 km", "2,704 km",
    "2,620 km", "2,615 km", "2,570 km", "2,549 km", "2,513 km",
    "2,500 km", "2,490 km", "2,450 km", "2,432 km", "2,428 km",
    "2,410 km", "2,348 km", "2,309 km", "2,292 km", "2,287 km",
    "2,273 km", "2,270 km", "2,250 km", "2,250 km", "2,210 km",
    "2,200 km", "2,188 km", "2,153 km", "2,102 km", "2,101 km",
    "2,100 km", "2,100 km", "2,064 km", "2,060 km", "2,010 km",
    "2,005 km", "1,978 km", "1,974 km", "1,950 km", "1,870 km",
    "1,865 km", "1,809 km", "1,805 km", "1,800 km", "1,799 km",
    "1,760 km", "1,737 km", "1,726 km", "1,690 km", "1,641 km",
    "1,636 km", "1,634 km", "1,610 km", "1,609 km", "1,600 km",
    "1,600 km", "1,600 km", "1,599 km", "1,592 km", "1,591 km",
    "1,590 km", "1,576 km", "1,571 km", "1,550 km", "1,532 km",
    "1,515 km", "1,500 km", "1,500 km", "1,492 km", "1,490 km",
  ],
  aliases: {
    "Huang He": "Yellow River",
    "Huang Ho": "Yellow River",
    "Yellow": "Yellow River",
    "Yangtze River": "Yangtze",
    "Chang Jiang": "Yangtze",
    "Nile River": "Nile",
    "Amazon River": "Amazon",
    "Mississippi River": "Mississippi",
    "Missouri River": "Mississippi",
    "Ganges": "Ganges",
    "Ganga": "Ganges",
    "Caquetá": "Japurá",
    "Putumayo": "Içá",
    "Nu Jiang": "Salween",
    "Lancang": "Mekong",
    "Heilong Jiang": "Amur",
    "Colorado River": "Colorado",
    "Congo River": "Congo",
    "Danube River": "Danube",
    "Niger River": "Niger",
    "Volga River": "Volga",
    "Indus River": "Indus",
    "Zambezi River": "Zambezi",
    "Lena River": "Lena",
    "Mackenzie River": "Mackenzie",
    "Mekong River": "Mekong",
    "Orinoco River": "Orinoco",
    "Columbia River": "Columbia",
    "Tigris River": "Tigris",
    "Euphrates River": "Euphrates",
    "Senegal River": "Senegal",
    "Magdalena River": "Magdalena",
    "Dnieper River": "Dnieper",
    "Don River": "Don",
    "Danube": "Danube",
    "Brahmaputra River": "Brahmaputra",
    "Cubango": "Okavango",
    "Volta River": "Volta",
    "Limpopo River": "Limpopo",
    "Orange River": "Orange",
    "Ural River": "Ural",
    "Irrawaddy River": "Irrawaddy",
    "Kasai River": "Kasai",
    "Kafue River": "Kafue",
    "Kura River": "Kura",
    "Mt'k'vari": "Kura",
  },
};
