import type { GameList } from './types';
import { longestChartingHot100Hints } from './hints';

export const longestChartingHot100: GameList = {
  id: 'longest-charting-hot100',
  name: 'Longest-Charting Songs on Billboard Hot 100',
  description: 'Songs ranked by total weeks on the Billboard Hot 100, all time (Wikipedia/Billboard)',
  topics: ['music'],
  hints: longestChartingHot100Hints,
  valueLabel: 'Weeks on Chart',
  items: [
    "Lose Control - Teddy Swims", "Heat Waves - Glass Animals", "Blinding Lights - The Weeknd", "Beautiful Things - Benson Boone", "Radioactive - Imagine Dragons",
    "All I Want for Christmas Is You - Mariah Carey", "Sail - AWOLNATION", "Levitating - Dua Lipa", "A Bar Song (Tipsy) - Shaboozey", "I'm Yours - Jason Mraz",
    "Wildflower - Billie Eilish", "Rockin' Around the Christmas Tree - Brenda Lee", "Jingle Bell Rock - Bobby Helms", "Stay - The Kid Laroi & Justin Bieber", "Believer - Imagine Dragons",
    "Old Town Road - Lil Nas X ft. Billy Ray Cyrus", "Shape of You - Ed Sheeran", "Last Night - Morgan Wallen", "Someone You Loved - Lewis Capaldi", "The Christmas Song - Nat King Cole",
    "Sunflower - Post Malone & Swae Lee", "Circles - Post Malone", "Rockstar - Post Malone ft. 21 Savage", "Last Christmas - Wham!", "Dance Monkey - Tones and I",
    "It's the Most Wonderful Time of the Year - Andy Williams", "God's Plan - Drake", "A Holly Jolly Christmas - Burl Ives", "Drivers License - Olivia Rodrigo", "Shallow - Lady Gaga & Bradley Cooper",
    "Bad Guy - Billie Eilish", "Closer - The Chainsmokers ft. Halsey", "Uptown Funk - Mark Ronson ft. Bruno Mars", "Anti-Hero - Taylor Swift", "Cruel Summer - Taylor Swift",
    "Rolling in the Deep - Adele", "White Christmas - Bing Crosby", "Feliz Navidad - José Feliciano", "Happy - Pharrell Williams", "Let It Snow! Let It Snow! Let It Snow! - Dean Martin",
    "Despacito - Luis Fonsi ft. Daddy Yankee", "Counting Stars - OneRepublic", "Good 4 U - Olivia Rodrigo", "Stay With Me - Sam Smith", "Roar - Katy Perry",
    "Shake It Off - Taylor Swift", "Starboy - The Weeknd ft. Daft Punk", "Save Your Tears - The Weeknd", "Girls Like You - Maroon 5 ft. Cardi B", "Sicko Mode - Travis Scott",
    "Watermelon Sugar - Harry Styles", "Can't Feel My Face - The Weeknd", "Mood - 24kGoldn ft. iann dior", "Easy on Me - Adele", "One Dance - Drake",
    "Señorita - Shawn Mendes & Camila Cabello", "Flowers - Miley Cyrus", "7 Rings - Ariana Grande", "Perfect - Ed Sheeran", "Thinking Out Loud - Ed Sheeran",
    "Thunder - Imagine Dragons", "Hotline Bling - Drake", "Lean On - Major Lazer & DJ Snake ft. MO", "As It Was - Harry Styles", "Peaches - Justin Bieber ft. Daniel Caesar & Giveon",
    "Don't Start Now - Dua Lipa", "That's What I Like - Bruno Mars", "Cheap Thrills - Sia", "All of Me - John Legend", "Blank Space - Taylor Swift",
    "Thank U, Next - Ariana Grande", "In My Feelings - Drake", "Havana - Camila Cabello ft. Young Thug", "Die For You - The Weeknd", "WAP - Cardi B ft. Megan Thee Stallion",
    "Bodak Yellow - Cardi B", "Vampire - Olivia Rodrigo", "Espresso - Sabrina Carpenter", "New Rules - Dua Lipa", "HUMBLE. - Kendrick Lamar",
    "Sorry - Justin Bieber", "Treat You Better - Shawn Mendes", "Die with a Smile - Lady Gaga & Bruno Mars", "24K Magic - Bruno Mars", "What Do You Mean? - Justin Bieber",
    "Butter - BTS", "Running Up That Hill - Kate Bush", "Stay - Rihanna ft. Mikky Ekko", "Photograph - Ed Sheeran", "Say You Won't Let Go - James Arthur",
    "Dynamite - BTS", "Locked Out of Heaven - Bruno Mars", "Diamonds - Rihanna", "Don't Let Me Down - The Chainsmokers ft. Daya", "Work - Rihanna ft. Drake",
    "We Found Love - Rihanna ft. Calvin Harris", "Umbrella - Rihanna", "Please Please Please - Sabrina Carpenter", "Love Yourself - Justin Bieber", "Not Like Us - Kendrick Lamar",
  ],
  values: [
    "112 weeks", "91 weeks",  "90 weeks",  "89 weeks",  "87 weeks",
    "79 weeks",  "79 weeks",  "77 weeks",  "77 weeks",  "76 weeks",
    "72 weeks",  "71 weeks",  "68 weeks",  "63 weeks",  "62 weeks",
    "61 weeks",  "59 weeks",  "58 weeks",  "57 weeks",  "56 weeks",
    "55 weeks",  "54 weeks",  "54 weeks",  "53 weeks",  "52 weeks",
    "52 weeks",  "51 weeks",  "51 weeks",  "50 weeks",  "50 weeks",
    "49 weeks",  "48 weeks",  "47 weeks",  "47 weeks",  "46 weeks",
    "46 weeks",  "44 weeks",  "43 weeks",  "43 weeks",  "42 weeks",
    "41 weeks",  "41 weeks",  "40 weeks",  "40 weeks",  "39 weeks",
    "39 weeks",  "38 weeks",  "38 weeks",  "38 weeks",  "37 weeks",
    "37 weeks",  "37 weeks",  "37 weeks",  "37 weeks",  "36 weeks",
    "36 weeks",  "36 weeks",  "36 weeks",  "35 weeks",  "35 weeks",
    "35 weeks",  "35 weeks",  "34 weeks",  "34 weeks",  "34 weeks",
    "34 weeks",  "33 weeks",  "33 weeks",  "33 weeks",  "33 weeks",
    "32 weeks",  "32 weeks",  "32 weeks",  "32 weeks",  "31 weeks",
    "31 weeks",  "31 weeks",  "31 weeks",  "31 weeks",  "30 weeks",
    "30 weeks",  "30 weeks",  "30 weeks",  "30 weeks",  "30 weeks",
    "30 weeks",  "29 weeks",  "29 weeks",  "29 weeks",  "29 weeks",
    "29 weeks",  "29 weeks",  "28 weeks",  "28 weeks",  "28 weeks",
    "28 weeks",  "27 weeks",  "27 weeks",  "27 weeks",  "27 weeks",
  ],
};
