import type { GameList } from './types';

export const mostWatchedAnime: GameList = {
  id: 'most-watched-anime',
  name: 'Most Watched Anime',
  description: 'Top 50 anime by global cultural popularity (curated from MAL, AniList & viewership data)',
  topics: ['entertainment'],
  difficulty: 1,
  size: 50,
  newUntil: '2026-04-15',
  items: [
    "Dragon Ball Z",
    "One Piece",
    "Naruto",
    "Attack on Titan",
    "Death Note",
    "Pokémon",
    "Demon Slayer",
    "Fullmetal Alchemist: Brotherhood",
    "Sword Art Online",
    "My Hero Academia",
    "One-Punch Man",
    "Naruto Shippuden",
    "Hunter x Hunter",
    "Tokyo Ghoul",
    "Bleach",
    "Dragon Ball",
    "Sailor Moon",
    "Neon Genesis Evangelion",
    "Cowboy Bebop",
    "Jujutsu Kaisen",
    "Fairy Tail",
    "Code Geass",
    "Steins;Gate",
    "Mob Psycho 100",
    "Spy x Family",
    "JoJo's Bizarre Adventure",
    "Chainsaw Man",
    "Yu Yu Hakusho",
    "Inuyasha",
    "Erased",
    "Vinland Saga",
    "The Seven Deadly Sins",
    "Re:Zero",
    "Haikyuu!!",
    "Black Clover",
    "Parasyte",
    "Your Lie in April",
    "Gurren Lagann",
    "Yu-Gi-Oh!",
    "Trigun",
    "Fruits Basket",
    "Dr. Stone",
    "Fire Force",
    "Overlord",
    "Violet Evergarden",
    "That Time I Got Reincarnated as a Slime",
    "The Promised Neverland",
    "Soul Eater",
    "Psycho-Pass",
    "Dandadan",
  ],
  hints: [
    // Top 50 — one canonical hint per item, plus genuinely different names/abbreviations
    "Dragon Ball Z", "DBZ", "One Piece", "Naruto", "Attack on Titan",
    "Death Note", "Pokemon", "Demon Slayer", "Kimetsu no Yaiba",
    "Fullmetal Alchemist Brotherhood", "FMA", "Sword Art Online", "SAO",
    "My Hero Academia", "Boku no Hero Academia", "MHA",
    "One Punch Man", "OPM", "Naruto Shippuden", "Hunter x Hunter", "HxH",
    "Tokyo Ghoul", "Bleach", "Dragon Ball",
    "Sailor Moon", "Neon Genesis Evangelion", "NGE", "Evangelion",
    "Cowboy Bebop", "Jujutsu Kaisen", "JJK", "Fairy Tail",
    "Code Geass", "Steins Gate", "Mob Psycho 100",
    "Spy x Family", "JoJo's Bizarre Adventure", "JoJo",
    "Chainsaw Man", "CSM", "Yu Yu Hakusho", "Inuyasha",
    "Erased", "Boku dake ga Inai Machi", "Vinland Saga",
    "The Seven Deadly Sins", "Nanatsu no Taizai", "Re Zero",
    "Haikyuu", "Black Clover", "Parasyte", "Kiseijuu",
    "Your Lie in April", "Shigatsu wa Kimi no Uso",
    "Gurren Lagann", "Tengen Toppa Gurren Lagann", "Yugioh",
    "Trigun", "Fruits Basket", "Furuba", "Dr Stone",
    "Fire Force", "Enen no Shouboutai", "Overlord", "Violet Evergarden",
    "That Time I Got Reincarnated as a Slime", "Tensura", "Slime Isekai",
    "The Promised Neverland", "Yakusoku no Neverland", "Soul Eater",
    "Psycho Pass", "Dandadan",
    // Beyond top 50 — popular anime people might guess
    "Akira", "Ghost in the Shell", "Spirited Away", "Princess Mononoke",
    "My Neighbor Totoro", "Howl's Moving Castle", "Grave of the Fireflies",
    "Samurai Champloo", "Rurouni Kenshin", "Berserk", "Claymore",
    "Kill la Kill", "Toradora", "Clannad", "Angel Beats",
    "Elfen Lied", "Hellsing", "Trigun Stampede", "Blue Lock",
    "Bocchi the Rock", "Oshi no Ko", "Frieren", "Solo Leveling",
    "Kaiju No 8", "Mushoku Tensei", "Konosuba", "Shield Hero",
    "Classroom of the Elite", "Assassination Classroom",
    "Ansatsu Kyoushitsu", "Durarara", "Noragami", "Blue Exorcist",
    "Ao no Exorcist", "Magi", "Food Wars", "Shokugeki no Soma",
    "Made in Abyss", "Dororo",
    "Bungo Stray Dogs", "Cells at Work", "Hataraku Saibou",
    "Devilman Crybaby", "Wonder Egg Priority", "Eighty-Six",
    "Ranking of Kings", "Ousama Ranking", "Odd Taxi", "Link Click",
    "Cyberpunk Edgerunners", "Slam Dunk", "Initial D",
    "Case Closed", "Detective Conan", "Lupin the Third",
    "Fist of the North Star", "Hokuto no Ken", "Gundam",
    "Macross", "Astro Boy", "Speed Racer",
    "Doraemon", "Crayon Shin-chan",
  ],
  aliases: {
    // Genuinely different names and abbreviations (normalizeGuess handles punctuation)
    "DBZ": "Dragon Ball Z",
    "Dragonball Z": "Dragon Ball Z",
    "Dragonball": "Dragon Ball",
    "Pokemon": "Pokémon",
    "Kimetsu no Yaiba": "Demon Slayer",
    "FMA Brotherhood": "Fullmetal Alchemist: Brotherhood",
    "FMA": "Fullmetal Alchemist: Brotherhood",
    "SAO": "Sword Art Online",
    "Boku no Hero Academia": "My Hero Academia",
    "MHA": "My Hero Academia",
    "OPM": "One-Punch Man",
    "HxH": "Hunter x Hunter",
    "NGE": "Neon Genesis Evangelion",
    "Evangelion": "Neon Genesis Evangelion",
    "JJK": "Jujutsu Kaisen",
    "Mob Psycho": "Mob Psycho 100",
    "JoJo": "JoJo's Bizarre Adventure",
    "CSM": "Chainsaw Man",
    "Boku dake ga Inai Machi": "Erased",
    "Nanatsu no Taizai": "The Seven Deadly Sins",
    "Kiseijuu": "Parasyte",
    "Shigatsu wa Kimi no Uso": "Your Lie in April",
    "Tengen Toppa Gurren Lagann": "Gurren Lagann",
    "Yugioh": "Yu-Gi-Oh!",
    "Furuba": "Fruits Basket",
    "Enen no Shouboutai": "Fire Force",
    "Tensura": "That Time I Got Reincarnated as a Slime",
    "Slime Isekai": "That Time I Got Reincarnated as a Slime",
    "Yakusoku no Neverland": "The Promised Neverland",
  },
};
