import type { GameList } from './types';
import { mostVisitedWikipediaHints } from './hints/most-visited-wikipedia';

export const mostVisitedWikipedia: GameList = {
  id: 'most-visited-wikipedia',
  name: 'Most-Visited Wikipedia Articles',
  description: 'Wikipedia articles ranked by annual page views (Wikimedia API, 2024)',
  topics: ['entertainment'],
  difficulty: 3,
  hints: mostVisitedWikipediaHints,
  valueLabel: 'Views (2024)',
  items: [
    "Cleopatra", "XXXTentacion", "2024 United States presidential election", "Kamala Harris", "Donald Trump",
    "Indian Premier League", "Deadpool & Wolverine", "Project 2025", "ChatGPT", "Elon Musk",
    "Taylor Swift", "2020 United States presidential election", "United States", "2024 Summer Olympics", "Joe Biden",
    "UEFA Euro 2024", "Lyle and Erik Menendez", "Cristiano Ronaldo", "Kalki 2898 AD", "J. D. Vance",
    "Sean Combs", "Robert F. Kennedy Jr.", "Dune: Part Two", "Sabrina Carpenter", "Liam Payne",
    "Griselda Blanco", "Jimmy Carter", "Pushpa 2: The Rule", "World War II", "Tim Walz",
    "Sex", "India", "Sydney Sweeney", "Mike Tyson", "House of the Dragon",
    "J. Robert Oppenheimer", "Alia Bhatt", "Chappell Roan", "Poor Things", "Oppenheimer",
    "Lionel Messi", "Saltburn", "Dune", "Premier League", "Barry Keoghan",
    "Inside Out 2", "Israel-Hamas war", "UEFA Champions League", "Imane Khelif", "Gladiator II",
    "Simone Biles", "Ariana Grande", "O. J. Simpson", "Bob Marley", "2016 United States presidential election",
    "Wicked", "Eminem", "Barack Obama", "Adolf Hitler", "Napoleon",
    "Elizabeth II", "Ryan Reynolds", "Blake Lively", "Civil War", "Russian invasion of Ukraine",
    "United Kingdom", "Timothee Chalamet", "LeBron James", "Michael Jackson", "Dua Lipa",
    "Charles III", "Zendaya", "Billie Eilish", "Jake Paul vs. Mike Tyson", "Alien: Romulus",
    "John F. Kennedy", "2024 ICC Men's T20 World Cup", "Elvis Presley", "Keir Starmer", "Kingdom of the Planet of the Apes",
    "Lady Gaga", "Travis Kelce", "Fallout", "The Bear", "Israel",
    "September 11 attacks", "Tulsi Gabbard", "Joker: Folie a Deux", "Lamine Yamal", "Richard Gadd",
    "Jeffrey Epstein", "Scarlett Johansson", "WrestleMania XL", "Twisters", "Yellowstone",
    "Wicked the musical", "Nikki Haley", "Glen Powell", "Madame Web", "Jake Paul",
  ],
  values: [
    "50M", "37M", "31M", "29M", "27M",
    "24M", "22M", "20M", "19M", "18M",
    "18M", "17M", "17M", "16M", "15M",
    "15M", "15M", "15M", "14M", "14M",
    "13M", "13M", "13M", "12M", "12M",
    "12M", "12M", "12M", "12M", "12M",
    "11M", "11M", "11M", "11M", "11M",
    "11M", "11M", "10M", "10M", "10M",
    "10M", "10M", "10M", "10M", "9M",
    "9M", "9M", "9M", "9M", "9M",
    "9M", "9M", "9M", "9M", "9M",
    "9M", "9M", "9M", "9M", "9M",
    "9M", "9M", "9M", "9M", "9M",
    "8M", "8M", "8M", "8M", "8M",
    "8M", "8M", "8M", "8M", "8M",
    "8M", "8M", "8M", "8M", "8M",
    "8M", "8M", "8M", "8M", "8M",
    "7M", "7M", "7M", "7M", "7M",
    "7M", "7M", "7M", "7M", "7M",
    "7M", "7M", "7M", "7M", "7M",
  ],
  newUntil: '2026-05-14',
};
