// Source: Edison Research "Top 50 Podcasts in the U.S. for Q4 2025"
// https://podnews.net/press-release/edison-top-50-podcasts-us-q425
// Ranks 51-100 from iHeartRadio, Podtail, Podtrac, Apple & Spotify charts
import type { GameList } from './types';
import { mostPopularPodcastsHints } from './hints/most-popular-podcasts';

export const mostPopularPodcasts: GameList = {
  id: 'most-popular-podcasts',
  name: 'Most Popular Podcasts in the US',
  description: 'Podcasts ranked by US listenership (Edison Research Q4 2025)',
  topics: ['entertainment', 'internet'],
  difficulty: 2,
  hints: mostPopularPodcastsHints,
  valueLabel: 'Genre',
  size: 100,
  newUntil: '2026-04-14',
  items: [
    "The Joe Rogan Experience",
    "Crime Junkie",
    "The Daily",
    "Call Her Daddy",
    "SmartLess",
    "Stuff You Should Know",
    "This American Life",
    "This Past Weekend w/ Theo Von",
    "Dateline NBC",
    "New Heights with Jason & Travis Kelce",
    "Morbid",
    "Bad Friends",
    "The Megyn Kelly Show",
    "Rotten Mango",
    "The Breakfast Club",
    "Radiolab",
    "MrBallen Podcast: Strange, Dark & Mysterious Stories",
    "The MeidasTouch Podcast",
    "The Mel Robbins Podcast",
    "The Tucker Carlson Show",
    "Million Dollaz Worth of Game",
    "TED Talks Daily",
    "My Favorite Murder",
    "Pod Save America",
    "Club Shay Shay",
    "Conan O'Brien Needs a Friend",
    "Dumb Blonde",
    "Planet Money",
    "Not Gonna Lie with Kylie Kelce",
    "Impaulsive with Logan Paul",
    "Murder, Mystery & Makeup",
    "The Basement Yard",
    "The Moth",
    "The Diary Of A CEO with Steven Bartlett",
    "Candace",
    "No Jumper",
    "Up First from NPR",
    "Good Hang with Amy Poehler",
    "The Shawn Ryan Show",
    "The Pat McAfee Show",
    "Distractible",
    "Pardon My Take",
    "The Joe Budden Podcast",
    "Huberman Lab",
    "The 85 South Show",
    "How I Built This with Guy Raz",
    "The Charlie Kirk Show",
    "The Ben Shapiro Show",
    "The Bill Simmons Podcast",
    "Armchair Expert with Dax Shepard",
    "Dan Bongino Show",
    "The Ramsey Show",
    "Fresh Air",
    "NPR News Now",
    "On Purpose with Jay Shetty",
    "48 Hours",
    "Serial",
    "Morning Wire",
    "The Ezra Klein Show",
    "Stuff You Missed in History Class",
    "Wait Wait... Don't Tell Me!",
    "Hidden Brain",
    "Behind the Bastards",
    "The Tim Dillon Show",
    "2 Bears, 1 Cave",
    "Park Predators",
    "The Oprah Podcast",
    "Joel Osteen Podcast",
    "Dark Downeast",
    "The Bible in a Year",
    "Lex Fridman Podcast",
    "The Glenn Beck Program",
    "The Mark Levin Podcast",
    "Cold Case Files",
    "True Crime with Kendall Rae",
    "The Dan Le Batard Show with Stugotz",
    "Las Culturistas",
    "Small Town Murder",
    "American History Tellers",
    "Crime Stories with Nancy Grace",
    "The Way I Heard It with Mike Rowe",
    "Giggly Squad",
    "Pod Save the World",
    "The Bulwark Podcast",
    "Freakonomics Radio",
    "The Why Files",
    "The Matt Walsh Show",
    "The Journal.",
    "Money Rehab with Nicole Lapin",
    "Pivot",
    "The Herd with Colin Cowherd",
    "Sword and Scale",
    "The Dan Patrick Show",
    "Last Podcast on the Left",
    "Anything Goes with Emma Chamberlain",
    "Two Ts in a Pod",
    "The Jordan B. Peterson Podcast",
    "Today, Explained",
    "Flagrant",
    "Kill Tony",
  ],
  aliases: {
    "Joe Rogan": "The Joe Rogan Experience",
    "JRE": "The Joe Rogan Experience",
    "Rogan": "The Joe Rogan Experience",
    "MFM": "My Favorite Murder",
    "PMT": "Pardon My Take",
    "SYSK": "Stuff You Should Know",
    "TAL": "This American Life",
  },
  values: [
    "Comedy / Interview", "True Crime", "News", "Comedy / Lifestyle", "Comedy / Interview",
    "Education", "Society & Culture", "Comedy", "True Crime", "Sports",
    "True Crime", "Comedy", "News / Talk", "True Crime", "Comedy / Talk",
    "Science", "True Crime / Mystery", "News / Politics", "Education / Self-Help", "News / Politics",
    "Music / Talk", "Education", "True Crime / Comedy", "News / Politics", "Sports / Talk",
    "Comedy", "Comedy / Talk", "Business / Economics", "Comedy / Lifestyle", "Comedy / Talk",
    "True Crime / Beauty", "Comedy", "Storytelling", "Business / Interview", "News / Politics",
    "Music / Hip-Hop", "News", "Comedy / Interview", "Society & Culture", "Sports",
    "Comedy / Gaming", "Sports", "Music / Hip-Hop", "Health / Science", "Comedy",
    "Business", "News / Politics", "News / Politics", "Sports / Culture", "Comedy / Interview",
    "News / Politics", "Personal Finance", "Interview / Culture", "News", "Self-Help",
    "True Crime", "True Crime", "News", "Society & Culture", "History / Education",
    "News / Comedy", "Psychology", "History", "Comedy", "Comedy",
    "True Crime", "Society & Culture", "Religion", "True Crime", "Religion",
    "Science / Interview", "News / Politics", "News / Politics", "True Crime", "True Crime",
    "Sports", "Comedy / Culture", "True Crime / Comedy", "History", "True Crime",
    "Storytelling", "Comedy", "News / Politics", "News / Politics", "Economics / Education",
    "Mystery / Paranormal", "News / Politics", "News / Business", "Business / Finance", "Technology / Business",
    "Sports", "True Crime", "Sports", "True Crime / Comedy", "Society & Culture",
    "Entertainment / Reality TV", "Psychology / Education", "News / Culture", "Comedy", "Comedy",
  ],
};
