import type { GameList } from './types';
import { mostCitedScientificPapersHints } from './hints/most-cited-scientific-papers';

// Source: Van Noorden, Maher & Nuzzo, "The top 100 papers," Nature 514, 550-553 (2014).
// Data from Thomson Reuters Web of Science, extracted October 7, 2014.
// Format: "First Author — Short Description (Year)"
export const mostCitedScientificPapers: GameList = {
  id: 'most-cited-scientific-papers',
  name: 'Most Cited Scientific Papers',
  description: 'Papers ranked by citation count (Nature / Web of Science 2014)',
  topics: ['misc'],
  hints: mostCitedScientificPapersHints,
  valueLabel: 'Citations',
  items: [
    "Lowry — Protein measurement with the Folin phenol reagent (1951)",
    "Laemmli — Cleavage of structural proteins during bacteriophage T4 assembly (1970)",
    "Bradford — Rapid method for quantitation of microgram quantities of protein (1976)",
    "Sanger — DNA sequencing with chain-terminating inhibitors (1977)",
    "Chomczynski — Single-step RNA isolation by acid guanidinium thiocyanate (1987)",
    "Towbin — Electrophoretic transfer of proteins to nitrocellulose sheets (1979)",
    "Lee — Colle-Salvetti correlation-energy formula as a DFT functional (1988)",
    "Becke — Density-functional thermochemistry III: role of exact exchange (1993)",
    "Murashige — Revised medium for rapid growth and bioassays with tobacco tissue (1962)",
    "Thompson — CLUSTAL W: improving progressive multiple sequence alignment (1994)",
    "Kaplan — Nonparametric estimation from incomplete observations (1958)",
    "Altschul — Basic Local Alignment Search Tool (1990)",
    "Sheldrick — A short history of SHELX (2008)",
    "Altschul — Gapped BLAST and PSI-BLAST (1997)",
    "Saiki — Primer-directed enzymatic amplification of DNA with Taq polymerase (1988)",
    "Perdew — Generalized gradient approximation made simple (1996)",
    "Kresse — Efficient iterative schemes for ab initio total-energy calculations (1996)",
    "Folstein — Mini-mental state: practical method for grading cognitive state (1975)",
    "Saitou — The neighbor-joining method for reconstructing phylogenetic trees (1987)",
    "Felsenstein — Confidence limits on phylogenies using the bootstrap (1985)",
    "Bland — Statistical methods for assessing agreement between two methods (1986)",
    "Shannon — Revised effective ionic radii in halides and chalcogenides (1976)",
    "Otwinowski — Processing of X-ray diffraction data in oscillation mode (1997)",
    "Cox — Regression models and life-tables (1972)",
    "Kresse — Ab initio molecular dynamics for liquid metals (1993)",
    "Mosmann — Rapid colorimetric assay for cellular growth and survival (1983)",
    "Livak — Analysis of relative gene expression using the 2(-Delta Delta Ct) method (2001)",
    "Thompson — The CLUSTAL X interface for progressive alignment (1997)",
    "Hohenberg — Inhomogeneous electron gas (1964)",
    "Kohn — Self-consistent equations including exchange and correlation effects (1965)",
    "Lipinski — Experimental and computational approaches to estimate solubility (1997)",
    "Becke — Density-functional exchange-energy approximation (1988)",
    "Perdew — Self-interaction correction to density-functional approximations (1981)",
    "Kresse — From ultrasoft pseudopotentials to the projector augmented-wave method (1999)",
    "Iijima — Helical microtubules of graphitic carbon (1991)",
    "Dewar — Development and use of quantum mechanical molecular models: AM1 (1985)",
    "Bligh — A rapid method of total lipid extraction and purification (1959)",
    "Edgar — MUSCLE: multiple sequence alignment with high accuracy (2004)",
    "Felsenstein — PHYLIP: phylogeny inference package (1989)",
    "Berman — The Protein Data Bank (2000)",
    "Pearson — Improved tools for biological sequence comparison: FASTA (1988)",
    "Henikoff — Amino acid substitution matrices from protein blocks: BLOSUM (1992)",
    "Needleman — A general method for search of similarities in amino acid sequences (1970)",
    "Benjamini — Controlling the false discovery rate (1995)",
    "Woese — Towards a natural system of organisms: Archaea, Bacteria, Eucarya (1990)",
    "Watts — Collective dynamics of small-world networks (1998)",
    "Barabasi — Emergence of scaling in random networks (1999)",
    "Akaike — A new look at statistical model identification (1974)",
    "Tamura — MEGA5: molecular evolutionary genetics analysis (2011)",
    "Kumar — MEGA: molecular evolutionary genetics analysis (1994)",
    "Higgins — CLUSTAL: progressive multiple sequence alignment (1988)",
    "Laskowski — PROCHECK: stereochemical quality of protein structures (1993)",
    "Kraulis — MOLSCRIPT: detailed and schematic plots of protein structures (1991)",
    "Jones — Improved methods for building protein models in electron density maps (1991)",
    "Li — Fast and accurate short read alignment with Burrows-Wheeler Aligner (2009)",
    "Vogelstein — A genetic model for colorectal tumorigenesis (1990)",
    "Woese — Bacterial evolution via 16S rRNA phylogenetic analysis (1987)",
    "Benjamini — The control of the false discovery rate under dependency (2001)",
    "Tamura — MEGA4: molecular evolutionary genetics analysis (2007)",
    "Duncan — Multiple range and multiple F-tests (1955)",
    "Li — The sequence alignment/map format and SAMtools (2009)",
    "Langmead — Ultrafast alignment of short DNA sequences: Bowtie (2009)",
    "Greenwald — Measuring individual differences in implicit cognition: IAT (1998)",
    "Bondi — Van der Waals volumes and radii (1964)",
    "Price — Principal components analysis corrects for stratification in GWAS (2006)",
    "Barrett — Haploview: analysis and visualization of LD and haplotype maps (2005)",
    "Purcell — PLINK: whole-genome association and population-based linkage analysis (2007)",
    "Trapnell — Transcript assembly and quantification by RNA-seq: Cufflinks (2010)",
    "Anders — Differential expression analysis for sequence count data: DESeq (2010)",
    "van der Maaten — Visualizing data using t-SNE (2008)",
    "Robinson — edgeR: differential expression analysis of digital gene expression data (2010)",
    "Wright — The interpretation of population structure by F-statistics (1965)",
    "Tajima — Statistical method for testing the neutral mutation hypothesis (1989)",
    "Kim — TopHat: discovering splice junctions with RNA-seq (2009)",
    "DeLano — The PyMOL molecular graphics system (2002)",
    "Subramanian — Gene set enrichment analysis: GSEA (2005)",
    "Ashburner — Gene ontology: tool for the unification of biology (2000)",
    "Collaborative Computational Project No. 4 — The CCP4 suite (1994)",
    "Murshudov — Refinement of macromolecular structures by maximum likelihood: REFMAC (1997)",
    "McKenna — The Genome Analysis Toolkit: GATK (2010)",
    "DePristo — A framework for variation discovery using next-gen sequencing: GATK (2011)",
    "Storey — Statistical significance for genome-wide studies (2003)",
    "Pruitt — NCBI Reference Sequence project: RefSeq (2005)",
    "Benson — GenBank (2000)",
    "Bateman — The Pfam protein families database (2002)",
    "Moher — PRISMA: preferred reporting items for systematic reviews (2009)",
    "Higgins — Measuring inconsistency in meta-analyses: I-squared (2003)",
    "DerSimonian — Meta-analysis in clinical trials: random effects model (1986)",
    "Egger — Bias in meta-analysis detected by a simple graphical test (1997)",
    "Devereux — A comprehensive set of sequence analysis programs for the VAX (1984)",
    "Kumar — MEGA2: molecular evolutionary genetics analysis (2001)",
    "Read — Improved Fourier coefficients for maps using phases from partial structures (1986)",
    "Brunger — X-PLOR: a system for X-ray crystallography and NMR (1992)",
    "Adams — PHENIX: a comprehensive Python-based system for macromolecular structure (2010)",
    "Bayly — A well-behaved electrostatic potential based method: RESP charges (1993)",
    "Spearman — The proof and measurement of association between two things (1904)",
    "Pearson — On the criterion that a given system of deviations: chi-squared test (1900)",
    "Schwarz — Estimating the dimension of a model: Bayesian information criterion (1978)",
    "Hanahan — The hallmarks of cancer (2000)",
    "Hanahan — Hallmarks of cancer: the next generation (2011)",
  ],
  values: [
    "305,148", "213,005", "155,530", "65,335", "60,397",
    "~55,000", "46,702", "46,145", "~44,000", "~43,000",
    "~41,000", "~40,000", "~38,000", "~38,000", "~37,500",
    "~36,500", "~36,000", "~35,000", "~34,500", "~33,500",
    "~33,000", "~32,000", "~31,000", "~31,000", "~30,500",
    "~30,000", "~29,500", "~28,500", "~28,000", "~27,000",
    "~26,500", "~26,000", "~25,500", "~25,000", "~24,500",
    "~24,000", "~23,500", "~23,000", "~22,500", "~22,000",
    "~21,500", "~21,000", "~20,500", "~20,000", "~19,500",
    "~19,000", "~18,500", "~18,000", "~17,500", "~17,000",
    "~16,500", "~16,000", "~15,500", "~15,200", "~14,800",
    "~14,500", "~14,200", "~14,000", "~13,800", "~13,500",
    "~13,200", "~13,000", "~12,800", "~12,700", "~12,500",
    "~12,400", "~12,300", "~12,200", "~12,200", "~12,200",
    "~12,200", "~12,100", "~12,100", "~12,100", "~12,100",
    "~12,100", "~12,100", "~12,100", "~12,100", "~12,100",
    "~12,119", "~12,119", "~12,119", "~12,119", "~12,119",
    "~12,119", "~12,119", "~12,119", "~12,119", "~12,119",
    "~12,119", "~12,119", "~12,119", "~12,119", "~12,119",
    "~12,119", "~12,119", "~12,119", "~12,119", "~12,119",
  ],
  newUntil: '2026-05-14',
};
