import type { GameList } from './types';
import { mostSubscribedYoutubeHints } from './hints';

export const mostSubscribedYoutube: GameList = {
  id: 'most-subscribed-youtube',
  name: 'Most Subscribed YouTube Channels',
  description: 'YouTube channels ranked by subscriber count (2025)',
  topics: ['social media', 'internet', 'entertainment'],
  hints: mostSubscribedYoutubeHints,
  valueLabel: 'Subscribers',
  items: [
    "MrBeast", "T-Series", "Cocomelon - Nursery Rhymes", "SET India", "Vlad and Niki",
    "Kids Diana Show", "Stokes Twins", "Like Nastya", "김프로KIMPRO", "Zee Music Company",
    "WWE", "Alejo Igoa", "PewDiePie", "Goldmines", "Sony SAB",
    "BLACKPINK", "Alan's Universe", "ChuChu TV Nursery Rhymes & Kids Songs", "Zee TV", "A4",
    "Topper Guild", "Baby Shark - Pinkfong Kids' Songs & Stories", "BANGTANTV", "KL BRO Biju Rithvik", "Toys and Colors",
    "ZAMZAM BROTHERS OFFICIAL", "Colors TV", "T-Series Bhakti Sagar", "Tips Official", "5-Minute Crafts",
    "HYBE LABELS", "UR · Cristiano", "Justin Bieber", "Aaj Tak", "Shemaroo Filmi Gaane",
    "Mark Rober", "ISSEI / いっせい", "Fede Vigevani", "Infobells - Hindi", "HAR PAL GEO",
    "YRF", "Bispo Bruno Leonardo", "El Reino Infantil", "Sony Music India", "Wave Music",
    "Anaya Kandhal", "Zhong", "Canal KondZilla", "YOLO AVENTURAS", "ARY Digital HD",
    "Eminem Music", "Movieclips", "Taylor Swift", "PANDA BOI", "LooLoo Kids - Nursery Rhymes and Children's Songs",
    "Dude Perfect", "Shemaroo", "Saregama Music", "Dangal TV Channel", "Acharya Prashant",
    "Masha and the Bear", "ToRung", "SonyMusicIndiaVEVO", "Ed Sheeran", "Marshmello",
    "JioHotstar Kids", "Billion Surprise Toys", "Mikecrack", "Alfredo Larin", "Billie Eilish",
    "Get Movies", "Ariana Grande", "StarPlus", "MrBeast 2", "shfa",
    "Juan de Dios Pantoja", "JuegaGerman", "Celine Dept", "MrBeast Gaming", "Masha and the Bear English",
    "ABS-CBN Entertainment", "Jess No Limit", "HUM TV", "LUCCAS NETO - LUCCAS TOON", "shfa2",
    "Ishtar Music", "Real Fools Shorts Official", "Bad Bunny", "T-Series Bollywood Classics", "BETER BÖCÜK",
    "IShowSpeed", "Sierra & Rhia FAM", "Techno Gamerz", "IndiaTV", "Maria Clara & JP",
    "PowerKids TV", "Fernanfloo", "ABP NEWS", "Shakira", "Karla Bustillos",
  ],
  values: [
    "380M", "284M", "183M", "178M", "131M",
    "130M", "125M", "122M", "120M", "115M",
    "114M", "113M", "111M", "109M", "108M",
    "97M", "96M", "94M", "93M", "91M",
    "89M", "88M", "86M", "86M", "83M",
    "82M", "81M", "80M", "79M", "79M",
    "78M", "78M", "77M", "76M", "75M",
    "74M", "73M", "73M", "72M", "72M",
    "71M", "71M", "70M", "70M", "69M",
    "68M", "68M", "67M", "67M", "66M",
    "66M", "65M", "65M", "64M", "64M",
    "63M", "63M", "62M", "62M", "61M",
    "61M", "60M", "60M", "59M", "59M",
    "58M", "58M", "57M", "57M", "56M",
    "56M", "55M", "55M", "55M", "54M",
    "54M", "53M", "53M", "53M", "52M",
    "52M", "51M", "51M", "51M", "50M",
    "50M", "49M", "49M", "49M", "48M",
    "48M", "47M", "47M", "47M", "46M",
    "46M", "46M", "45M", "45M", "45M",
  ],
};
