// Source: Wikipedia "List of languages by number of native speakers"
// https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers
// Data: Ethnologue 2026 edition (ranks 1-28), extended rankings for 29-50
import type { GameList } from './types';
import { mostSpokenLanguagesHints } from './hints/most-spoken-languages';

export const mostSpokenLanguages: GameList = {
  id: 'most-spoken-languages',
  name: 'Most Spoken Languages by Native Speakers',
  description: 'Languages ranked by number of native speakers (Ethnologue 2026 via Wikipedia)',
  topics: ['misc', 'geography'],
  hints: mostSpokenLanguagesHints,
  valueLabel: 'Native Speakers',
  size: 50,
  newUntil: '2026-05-14',
  items: [
    "Mandarin Chinese",
    "Spanish",
    "English",
    "Hindi",
    "Portuguese",
    "Bengali",
    "Russian",
    "Japanese",
    "Western Punjabi",
    "Turkish",
    "Vietnamese",
    "Yue Chinese",
    "Egyptian Arabic",
    "Wu Chinese",
    "Marathi",
    "Telugu",
    "Korean",
    "Tamil",
    "Urdu",
    "Indonesian",
    "German",
    "French",
    "Javanese",
    "Iranian Persian",
    "Italian",
    "Hausa",
    "Gujarati",
    "Levantine Arabic",
    "Bhojpuri",
    "Min Nan Chinese",
    "Polish",
    "Pashto",
    "Kannada",
    "Xiang Chinese",
    "Malayalam",
    "Sundanese",
    "Odia",
    "Maithili",
    "Burmese",
    "Hakka Chinese",
    "Ukrainian",
    "Moroccan Arabic",
    "Sindhi",
    "Algerian Arabic",
    "Romanian",
    "Dutch",
    "Amharic",
    "Uzbek",
    "Igbo",
    "Tagalog",
  ],
  aliases: {
    "Cantonese": "Yue Chinese",
    "Farsi": "Iranian Persian",
    "Persian": "Iranian Persian",
    "Hokkien": "Min Nan Chinese",
    "Taiwanese": "Min Nan Chinese",
    "Filipino": "Tagalog",
    "Oriya": "Odia",
    "Punjabi": "Western Punjabi",
    "Standard German": "German",
    "Darija": "Moroccan Arabic",
    "Mandarin": "Mandarin Chinese",
  },
  values: [
    "988M", "487M", "372M", "347M", "252M",
    "232M", "133M", "124M", "90M", "86M",
    "86M", "85M", "83M", "83M", "83M",
    "83M", "82M", "79M", "78M", "78M",
    "76M", "76M", "69M", "65M", "60M",
    "58M", "58M", "55M", "53M", "49M",
    "45M", "45M", "44M", "38M", "38M",
    "36M", "36M", "34M", "33M", "32M",
    "32M", "32M", "31M", "30M", "26M",
    "25M", "25M", "24M", "24M", "24M",
  ],
};
