import type { GameList } from './types';
import { mostViewedYoutubeMusicVideosHints } from './hints';

export const mostViewedYoutubeMusicVideos: GameList = {
  id: 'most-viewed-youtube-music-videos',
  name: 'Most Viewed YouTube Music Videos',
  description: 'Music videos ranked by all-time YouTube view count (kworb.net / Wikipedia)',
  topics: ['music'],
  hints: mostViewedYoutubeMusicVideosHints,
  valueLabel: 'Views',
  items: [
    "Despacito - Luis Fonsi",
    "See You Again - Wiz Khalifa",
    "Shape of You - Ed Sheeran",
    "Gangnam Style - PSY",
    "Axel F - Crazy Frog",
    "Uptown Funk - Mark Ronson",
    "Dame Tu Cosita - El Chombo",
    "Shree Hanuman Chalisa - Gulshan Kumar",
    "Waka Waka - Shakira",
    "Counting Stars - OneRepublic",
    "Sugar - Maroon 5",
    "Roar - Katy Perry",
    "Dark Horse - Katy Perry",
    "Perfect - Ed Sheeran",
    "Sorry - Justin Bieber",
    "Let Her Go - Passenger",
    "Girls Like You - Maroon 5",
    "Thinking Out Loud - Ed Sheeran",
    "Faded - Alan Walker",
    "Lean On - Major Lazer & DJ Snake",
    "Bailando - Enrique Iglesias",
    "Blank Space - Taylor Swift",
    "Shake It Off - Taylor Swift",
    "Let It Go - Idina Menzel",
    "Mi Gente - J Balvin",
    "Baby - Justin Bieber",
    "We Don't Talk Anymore - Charlie Puth",
    "Closer - The Chainsmokers",
    "New Rules - Dua Lipa",
    "Hello - Adele",
    "Stressed Out - twenty one pilots",
    "The Lazy Song - Bruno Mars",
    "Rockabye - Clean Bandit",
    "Chantaje - Shakira",
    "Con Calma - Daddy Yankee & Snow",
    "Calma Remix - Pedro Capó & Farruko",
    "Love The Way You Lie - Eminem",
    "Work from Home - Fifth Harmony",
    "Believer - Imagine Dragons",
    "Sunflower - Post Malone & Swae Lee",
    "This Is What You Came For - Calvin Harris & Rihanna",
    "Chandelier - Sia",
    "Rolling in the Deep - Adele",
    "Criminal - Natti Natasha & Ozuna",
    "A Thousand Years - Christina Perri",
    "Taki Taki - DJ Snake",
    "On The Floor - Jennifer Lopez & Pitbull",
    "Starboy - The Weeknd",
    "All About That Bass - Meghan Trainor",
    "Alone - Marshmello",
    "Treat You Better - Shawn Mendes",
    "Numb - Linkin Park",
    "All of Me - John Legend",
    "Rude - MAGIC!",
    "Mayores - Becky G & Bad Bunny",
    "In Da Club - 50 Cent",
    "Somebody That I Used To Know - Gotye",
    "No Me Conoce Remix - Jhay Cortez & J. Balvin & Bad Bunny",
    "Te Bote Remix - Casper & Nio García & Darell",
    "Diamonds - Rihanna",
    "Party Rock Anthem - LMFAO",
    "Wake Me Up - Avicii",
    "That's What I Like - Bruno Mars",
    "Something Just Like This - The Chainsmokers & Coldplay",
    "Échame La Culpa - Luis Fonsi & Demi Lovato",
    "Someone Like You - Adele",
    "APT. - ROSÉ & Bruno Mars",
    "Worth It - Fifth Harmony",
    "November Rain - Guns N' Roses",
    "Side To Side - Ariana Grande",
    "Lovely - Billie Eilish & Khalid",
    "Love Me Like You Do - Ellie Goulding",
    "Nunca Es Suficiente - Los Ángeles Azules",
    "Thunder - Imagine Dragons",
    "Take On Me - a-ha",
    "DDU-DU DDU-DU - BLACKPINK",
    "Dusk Till Dawn - ZAYN",
    "Without Me - Eminem",
    "Propuesta Indecente - Romeo Santos",
    "Heathens - twenty one pilots",
    "X (EQUIS) - Nicky Jam & J. Balvin",
    "China - Anuel AA & Daddy Yankee & Karol G",
    "Sin Pijama - Becky G & Natti Natasha",
    "What Do You Mean? - Justin Bieber",
    "Don't Let Me Down - The Chainsmokers",
    "The Hills - The Weeknd",
    "Dance Monkey - Tones and I",
    "Con Altura - Rosalía & J Balvin",
    "Déjala Que Vuelva - Piso 21",
    "Life Is Good - Future & Drake",
    "Hymn For The Weekend - Coldplay",
    "In The End - Linkin Park",
    "Ay Vamos - J. Balvin",
    "Human - Rag'n'Bone Man",
    "Kill This Love - BLACKPINK",
    "Smells Like Teen Spirit - Nirvana",
    "Just The Way You Are - Bruno Mars",
    "What's Up - 4 Non Blondes",
    "Titanium - David Guetta & Sia",
    "Hotline Bling - Drake",
  ],
  values: [
    "8.99B", "6.97B", "6.70B", "5.91B", "5.85B",
    "5.79B", "5.43B", "5.34B", "4.49B", "4.40B",
    "4.36B", "4.30B", "4.15B", "4.14B", "4.09B",
    "4.04B", "4.00B", "3.99B", "3.95B", "3.90B",
    "3.81B", "3.78B", "3.67B", "3.65B", "3.63B",
    "3.58B", "3.51B", "3.38B", "3.27B", "3.26B",
    "3.20B", "3.19B", "3.17B", "3.16B", "3.15B",
    "3.12B", "3.11B", "3.07B", "2.97B", "2.94B",
    "2.93B", "2.91B", "2.84B", "2.81B", "2.79B",
    "2.79B", "2.79B", "2.74B", "2.70B", "2.70B",
    "2.69B", "2.69B", "2.67B", "2.66B", "2.65B",
    "2.63B", "2.61B", "2.59B", "2.56B", "2.55B",
    "2.51B", "2.51B", "2.50B", "2.50B", "2.48B",
    "2.43B", "2.43B", "2.42B", "2.40B", "2.40B",
    "2.39B", "2.39B", "2.39B", "2.38B", "2.38B",
    "2.38B", "2.38B", "2.37B", "2.36B", "2.34B",
    "2.32B", "2.32B", "2.31B", "2.31B", "2.29B",
    "2.29B", "2.28B", "2.26B", "2.26B", "2.25B",
    "2.23B", "2.22B", "2.22B", "2.20B", "2.16B",
    "2.15B", "2.14B", "2.14B", "2.14B", "2.13B",
  ],
};
