// Source: Reddit subscriber counts, 2025
import type { GameList } from './types';
import { mostPopularSubredditsHints } from './hints/most-popular-subreddits';

export const mostPopularSubreddits: GameList = {
  id: 'most-popular-subreddits',
  name: 'Most Popular Subreddits',
  description: 'The 100 largest subreddits by subscriber count (2025)',
  topics: ['internet'],
  difficulty: 2,
  hints: mostPopularSubredditsHints,
  valueLabel: 'Subscribers',
  newUntil: '2026-06-16',
  items: [
    "r/funny", "r/AskReddit", "r/gaming", "r/worldnews", "r/todayilearned",
    "r/aww", "r/Music", "r/movies", "r/memes", "r/science",
    "r/Showerthoughts", "r/pics", "r/news", "r/Jokes", "r/space",
    "r/videos", "r/books", "r/askscience", "r/mildlyinteresting", "r/EarthPorn",
    "r/food", "r/GetMotivated", "r/LifeProTips", "r/gadgets", "r/sports",
    "r/Art", "r/dataisbeautiful", "r/Futurology", "r/personalfinance", "r/Documentaries",
    "r/UpliftingNews", "r/photoshopbattles", "r/technology", "r/OldSchoolCool", "r/tifu",
    "r/history", "r/nottheonion", "r/DIY", "r/IAmA", "r/listentothis",
    "r/philosophy", "r/nosleep", "r/wholesomememes", "r/television", "r/InternetIsBeautiful",
    "r/nba", "r/gifs", "r/pcmasterrace", "r/creepy", "r/interestingasfuck",
    "r/WallStreetBets", "r/TwoXChromosomes", "r/Fitness", "r/Unexpected", "r/soccer",
    "r/WritingPrompts", "r/nfl", "r/cats", "r/buildapc", "r/CrazyFuckingVideos",
    "r/facepalm", "r/dankmemes", "r/worldpolitics", "r/anime", "r/MadeMeSmile",
    "r/Minecraft", "r/relationship_advice", "r/leagueoflegends", "r/AmItheAsshole", "r/politics",
    "r/dogs", "r/PublicFreakout", "r/pokemon", "r/nextfuckinglevel", "r/StarWars",
    "r/BlackPeopleTwitter", "r/Tinder", "r/NatureIsFuckingLit", "r/CFB", "r/comics",
    "r/baseball", "r/Cooking", "r/MapPorn", "r/hiphopheads", "r/me_irl",
    "r/AskMen", "r/AskWomen", "r/whowouldwin", "r/Marvel", "r/wallpaper",
    "r/Android", "r/apple", "r/MurderedByWords", "r/programming", "r/OutOfTheLoop",
    "r/oddlysatisfying", "r/hockey", "r/IdiotsInCars", "r/HolUp", "r/HistoryMemes",
  ],
  values: [
    "67M", "56M", "47M", "46M", "41M",
    "38M", "38M", "36M", "35M", "34M",
    "34M", "33M", "31M", "30M", "28M",
    "27M", "27M", "26M", "25M", "24M",
    "24M", "24M", "23M", "23M", "22M",
    "22M", "22M", "22M", "21M", "20M",
    "20M", "20M", "20M", "19M", "19M",
    "19M", "19M", "19M", "19M", "18M",
    "18M", "18M", "18M", "18M", "17M",
    "17M", "17M", "16M", "15M", "15M",
    "15M", "14M", "12M", "12M", "12M",
    "11M", "11M", "10M", "10M", "10M",
    "10M", "9.5M", "9.5M", "9M", "9M",
    "8.5M", "8.5M", "8M", "8M", "8M",
    "7.5M", "7.5M", "7M", "7M", "7M",
    "7M", "7M", "6.5M", "6.5M", "6.5M",
    "6M", "6M", "6M", "6M", "6M",
    "6M", "6M", "5.5M", "5.5M", "5.5M",
    "5.5M", "5.5M", "5M", "5M", "5M",
    "5M", "5M", "5M", "5M", "5M",
  ],
  aliases: {
    // Every item without the r/ prefix
    "funny": "r/funny",
    "AskReddit": "r/AskReddit",
    "gaming": "r/gaming",
    "worldnews": "r/worldnews",
    "todayilearned": "r/todayilearned",
    "aww": "r/aww",
    "Music": "r/Music",
    "movies": "r/movies",
    "memes": "r/memes",
    "science": "r/science",
    "Showerthoughts": "r/Showerthoughts",
    "pics": "r/pics",
    "news": "r/news",
    "Jokes": "r/Jokes",
    "space": "r/space",
    "videos": "r/videos",
    "books": "r/books",
    "askscience": "r/askscience",
    "mildlyinteresting": "r/mildlyinteresting",
    "EarthPorn": "r/EarthPorn",
    "food": "r/food",
    "GetMotivated": "r/GetMotivated",
    "LifeProTips": "r/LifeProTips",
    "gadgets": "r/gadgets",
    "sports": "r/sports",
    "Art": "r/Art",
    "dataisbeautiful": "r/dataisbeautiful",
    "Futurology": "r/Futurology",
    "personalfinance": "r/personalfinance",
    "Documentaries": "r/Documentaries",
    "UpliftingNews": "r/UpliftingNews",
    "photoshopbattles": "r/photoshopbattles",
    "technology": "r/technology",
    "OldSchoolCool": "r/OldSchoolCool",
    "tifu": "r/tifu",
    "history": "r/history",
    "nottheonion": "r/nottheonion",
    "DIY": "r/DIY",
    "IAmA": "r/IAmA",
    "listentothis": "r/listentothis",
    "philosophy": "r/philosophy",
    "nosleep": "r/nosleep",
    "wholesomememes": "r/wholesomememes",
    "television": "r/television",
    "InternetIsBeautiful": "r/InternetIsBeautiful",
    "nba": "r/nba",
    "gifs": "r/gifs",
    "pcmasterrace": "r/pcmasterrace",
    "creepy": "r/creepy",
    "interestingasfuck": "r/interestingasfuck",
    "WallStreetBets": "r/WallStreetBets",
    "TwoXChromosomes": "r/TwoXChromosomes",
    "Fitness": "r/Fitness",
    "Unexpected": "r/Unexpected",
    "soccer": "r/soccer",
    "WritingPrompts": "r/WritingPrompts",
    "nfl": "r/nfl",
    "cats": "r/cats",
    "buildapc": "r/buildapc",
    "CrazyFuckingVideos": "r/CrazyFuckingVideos",
    "facepalm": "r/facepalm",
    "dankmemes": "r/dankmemes",
    "worldpolitics": "r/worldpolitics",
    "anime": "r/anime",
    "MadeMeSmile": "r/MadeMeSmile",
    "Minecraft": "r/Minecraft",
    "relationship_advice": "r/relationship_advice",
    "leagueoflegends": "r/leagueoflegends",
    "AmItheAsshole": "r/AmItheAsshole",
    "politics": "r/politics",
    "dogs": "r/dogs",
    "PublicFreakout": "r/PublicFreakout",
    "pokemon": "r/pokemon",
    "nextfuckinglevel": "r/nextfuckinglevel",
    "StarWars": "r/StarWars",
    "BlackPeopleTwitter": "r/BlackPeopleTwitter",
    "Tinder": "r/Tinder",
    "NatureIsFuckingLit": "r/NatureIsFuckingLit",
    "CFB": "r/CFB",
    "comics": "r/comics",
    "baseball": "r/baseball",
    "Cooking": "r/Cooking",
    "MapPorn": "r/MapPorn",
    "hiphopheads": "r/hiphopheads",
    "me_irl": "r/me_irl",
    "AskMen": "r/AskMen",
    "AskWomen": "r/AskWomen",
    "whowouldwin": "r/whowouldwin",
    "Marvel": "r/Marvel",
    "wallpaper": "r/wallpaper",
    "Android": "r/Android",
    "apple": "r/apple",
    "MurderedByWords": "r/MurderedByWords",
    "programming": "r/programming",
    "OutOfTheLoop": "r/OutOfTheLoop",
    "oddlysatisfying": "r/oddlysatisfying",
    "hockey": "r/hockey",
    "IdiotsInCars": "r/IdiotsInCars",
    "HolUp": "r/HolUp",
    "HistoryMemes": "r/HistoryMemes",
    // Common alternate names and abbreviations
    "Wall Street Bets": "r/WallStreetBets",
    "WSB": "r/WallStreetBets",
    "TIFU": "r/tifu",
    "Today I Learned": "r/todayilearned",
    "TIL": "r/todayilearned",
    "LPT": "r/LifeProTips",
    "Life Pro Tips": "r/LifeProTips",
    "AITA": "r/AmItheAsshole",
    "Am I the Asshole": "r/AmItheAsshole",
    "PCMR": "r/pcmasterrace",
    "PC Master Race": "r/pcmasterrace",
    "NBA": "r/nba",
    "NFL": "r/nfl",
    "College Football": "r/CFB",
    "Earth Porn": "r/EarthPorn",
    "Shower Thoughts": "r/Showerthoughts",
    "Ask Science": "r/askscience",
    "Data is Beautiful": "r/dataisbeautiful",
    "Personal Finance": "r/personalfinance",
    "Old School Cool": "r/OldSchoolCool",
    "Mildly Interesting": "r/mildlyinteresting",
    "Photoshop Battles": "r/photoshopbattles",
    "Writing Prompts": "r/WritingPrompts",
    "Build a PC": "r/buildapc",
    "League of Legends": "r/leagueoflegends",
    "LOL": "r/leagueoflegends",
    "Relationship Advice": "r/relationship_advice",
    "Public Freakout": "r/PublicFreakout",
    "Black People Twitter": "r/BlackPeopleTwitter",
    "BPT": "r/BlackPeopleTwitter",
    "Nature is Lit": "r/NatureIsFuckingLit",
    "Hip Hop Heads": "r/hiphopheads",
    "Map Porn": "r/MapPorn",
    "Murdered By Words": "r/MurderedByWords",
    "Out of the Loop": "r/OutOfTheLoop",
    "OOTL": "r/OutOfTheLoop",
    "History Memes": "r/HistoryMemes",
    "Idiots in Cars": "r/IdiotsInCars",
    "Hold Up": "r/HolUp",
    "Star Wars": "r/StarWars",
    "Who Would Win": "r/whowouldwin",
    "Ask Men": "r/AskMen",
    "Ask Women": "r/AskWomen",
    "Ask Reddit": "r/AskReddit",
    "Today I Fucked Up": "r/tifu",
    "Uplifting News": "r/UpliftingNews",
    "Not the Onion": "r/nottheonion",
    "Interesting as Fuck": "r/interestingasfuck",
    "Internet is Beautiful": "r/InternetIsBeautiful",
    "Two X Chromosomes": "r/TwoXChromosomes",
    "Wholesome Memes": "r/wholesomememes",
    "Dank Memes": "r/dankmemes",
    "Made Me Smile": "r/MadeMeSmile",
    "Next Fucking Level": "r/nextfuckinglevel",
    "Nature Is Fucking Lit": "r/NatureIsFuckingLit",
    "Crazy Fucking Videos": "r/CrazyFuckingVideos",
    "Oddly Satisfying": "r/oddlysatisfying",
    "Get Motivated": "r/GetMotivated",
    "Listen to This": "r/listentothis",
    "I Am A": "r/IAmA",
    "World News": "r/worldnews",
    "World Politics": "r/worldpolitics",
    "Face Palm": "r/facepalm",
  },
};
