import type { GameList } from './types';
import { mostStreamedSpotifyArtistsHints } from './hints';

export const mostStreamedSpotifyArtists: GameList = {
  id: 'most-streamed-spotify-artists',
  name: 'Most Streamed Artists on Spotify',
  description: 'All-time most streamed artists on Spotify',
  topics: ['music'],
  difficulty: 2,
  hints: mostStreamedSpotifyArtistsHints,
  valueLabel: 'Total Streams',
  items: [
    "Taylor Swift", "Drake", "Bad Bunny", "The Weeknd", "Ariana Grande",
    "Ed Sheeran", "Billie Eilish", "Eminem", "Kanye West", "Post Malone",
    "BTS", "Justin Bieber", "Bruno Mars", "Rihanna", "Coldplay",
    "Travis Scott", "Kendrick Lamar", "Dua Lipa", "J Balvin", "Imagine Dragons",
    "Juice WRLD", "Lana Del Rey", "Lady Gaga", "David Guetta", "XXXTENTACION",
    "Future", "Ozuna", "Chris Brown", "Nicki Minaj", "Rauw Alejandro",
    "Lil Wayne", "Anuel AA", "21 Savage", "SZA", "KAROL G",
    "Khalid", "Lil Baby", "Arijit Singh", "Maroon 5", "Beyoncé",
    "Maluma", "Feid", "Calvin Harris", "Myke Towers", "Lil Uzi Vert",
    "Linkin Park", "J. Cole", "Peso Pluma", "Sia", "Young Thug",
    "Doja Cat", "Shakira", "Morgan Wallen", "Farruko", "Shawn Mendes",
    "Sam Smith", "Queen", "One Direction", "Harry Styles", "Metro Boomin",
    "Adele", "Gunna", "Arctic Monkeys", "Pritam", "Katy Perry",
    "Tyler, The Creator", "Selena Gomez", "Olivia Rodrigo", "Ty Dolla $ign", "Junior H",
    "The Beatles", "Nicky Jam", "Halsey", "Playboi Carti", "Wiz Khalifa",
    "Fuerza Regida", "Pitbull", "Frank Ocean", "Die drei ???", "JAY-Z",
    "A$AP Rocky", "The Chainsmokers", "Miley Cyrus", "Marshmello", "Sabrina Carpenter",
    "Cardi B", "Twenty One Pilots", "Disney", "Michael Jackson", "Camila Cabello",
    "Arcángel", "Red Hot Chili Peppers", "$uicideboy$", "OneRepublic", "Avicii",
    "Snoop Dogg", "DaBaby", "50 Cent", "Romeo Santos", "Natanael Cano",
  ],
  values: [
    "95B", "85B", "80B", "75B", "65B",
    "60B", "55B", "55B", "52B", "50B",
    "48B", "47B", "45B", "44B", "42B",
    "40B", "39B", "38B", "37B", "37B",
    "36B", "35B", "35B", "34B", "34B",
    "33B", "33B", "32B", "32B", "31B",
    "31B", "30B", "30B", "30B", "29B",
    "29B", "29B", "28B", "28B", "28B",
    "27B", "27B", "27B", "26B", "26B",
    "26B", "26B", "25B", "25B", "25B",
    "24B", "24B", "24B", "24B", "23B",
    "23B", "23B", "23B", "22B", "22B",
    "22B", "22B", "22B", "21B", "21B",
    "21B", "21B", "20B", "20B", "20B",
    "20B", "20B", "19B", "19B", "19B",
    "19B", "18B", "18B", "18B", "18B",
    "18B", "17B", "17B", "17B", "17B",
    "17B", "16B", "16B", "16B", "16B",
    "16B", "15B", "15B", "15B", "15B",
    "15B", "14B", "14B", "14B", "14B",
  ],
};
