// Source: Wikipedia "List of most expensive paintings"
// https://en.wikipedia.org/wiki/List_of_most_expensive_paintings
// Ranked by inflation-adjusted value (2025 USD), nominal prices shown
import type { GameList } from './types';
import { mostExpensivePaintingsHints } from './hints/most-expensive-paintings';

export const mostExpensivePaintings: GameList = {
  id: 'most-expensive-paintings',
  name: 'Most Expensive Paintings Ever Sold',
  description: 'Paintings ranked by sale price — auction & private (Wikipedia)',
  topics: ['misc', 'business'],
  hints: mostExpensivePaintingsHints,
  valueLabel: 'Sale Price',
  size: 50,
  newUntil: '2026-05-14',
  items: [
    "Salvator Mundi",
    "Interchange",
    "The Card Players",
    "Nafea Faa Ipoipo",
    "Number 17A",
    "Wasserschlangen II",
    "No. 6 (Violet, Green and Red)",
    "Pendant portraits of Maerten Soolmans and Oopjen Coppit",
    "Les Femmes d'Alger",
    "Portrait of Elisabeth Lederer",
    "The Standard Bearer",
    "Nu couché",
    "No. 5, 1948",
    "Woman III",
    "Masterpiece",
    "Portrait of Adele Bloch-Bauer I",
    "Shot Sage Blue Marilyn",
    "Le Rêve",
    "Portrait of Dr. Gachet",
    "Nu couché (sur le côté gauche)",
    "Portrait of Adele Bloch-Bauer II",
    "Three Studies of Lucian Freud",
    "Bal du moulin de la Galette",
    "Twelve Landscape Screens",
    "Garçon à la pipe",
    "Les Poseuses, Ensemble",
    "The Scream",
    "Otahi",
    "Reclining Nude with Blue Cushion",
    "La Montagne Sainte-Victoire",
    "Flag",
    "Nude, Green Leaves and Bust",
    "Portrait of Joseph Roulin",
    "Seated Man with a Glass",
    "Irises",
    "Dora Maar au Chat",
    "Eight Elvises",
    "Young Girl with a Flower Basket",
    "Femme à la montre",
    "Anna's Light",
    "Silver Car Crash (Double Disaster)",
    "Untitled (Basquiat)",
    "Portrait de l'artiste sans barbe",
    "Meules",
    "Verger avec cyprès",
    "La Montagne Sainte-Victoire vue du bosquet du Château Noir",
    "Massacre of the Innocents",
    "Nurse",
    "Triptych, 1976",
    "Les Noces de Pierrette",
  ],
  values: [
    "$450.3M", "$300M", "$250M+", "$210M", "$200M",
    "$183.8M", "$186M", "$180M", "$179.4M", "$236.3M",
    "$198M", "$170.4M", "$140M", "$137.5M", "$165M",
    "$135M", "$195M", "$155M", "$82.5M", "$157.2M",
    "$150M", "$142.4M", "$78.1M", "$140.8M", "$104.2M",
    "$149.2M", "$119.9M", "$120M", "$118M", "$137.7M",
    "$110M", "$106.5M", "$58M+", "$107.5M", "$53.9M",
    "$95.2M", "$100M", "$115M", "$139.3M", "$105.7M",
    "$105.4M", "$110.5M", "$71.5M", "$110.7M", "$117.1M",
    "$100M", "$76.7M", "$95.4M", "$86.3M", "$49.3M",
  ],
};
