import type { GameList } from './types';
import { mostFollowedInstagramHints } from './hints';

export const mostFollowedInstagram: GameList = {
  id: 'most-followed-instagram',
  name: 'Most Followed Instagram Accounts',
  description: 'Instagram accounts ranked by follower count (Wikipedia, 2024)',
  topics: ['internet'],
  hints: mostFollowedInstagramHints,
  valueLabel: 'Followers',
  items: [
    "Instagram", "Cristiano Ronaldo", "Lionel Messi", "Selena Gomez", "Kylie Jenner",
    "Dwayne Johnson", "Ariana Grande", "Kim Kardashian", "Beyoncé", "Khloé Kardashian",
    "Nike", "Kendall Jenner", "Justin Bieber", "Taylor Swift", "National Geographic",
    "Virat Kohli", "Jennifer Lopez", "Kourtney Kardashian", "Neymar", "Nicki Minaj",
    "Miley Cyrus", "Katy Perry", "Zendaya", "Kevin Hart", "Cardi B",
    "Real Madrid", "LeBron James", "FC Barcelona", "Rihanna", "Ellen DeGeneres",
    "Drake", "Demi Lovato", "Chris Brown", "UEFA Champions League", "Billie Eilish",
    "NASA", "Lisa", "Jennie", "Shakira", "David Beckham",
    "Gigi Hadid", "Priyanka Chopra", "Shraddha Kapoor", "Bad Bunny", "Premier League",
    "Kylian Mbappé", "Snoop Dogg", "Khaby Lame", "Dua Lipa", "Vin Diesel",
    "Travis Scott", "Narendra Modi", "BLACKPINK", "Lionel Messi Fan Club", "Maluma",
    "Paris Saint-Germain", "BTS", "Ronaldinho", "J Balvin", "Camila Cabello",
    "Manchester United", "Formula 1", "Marshmello", "Will Smith", "Karol G",
    "Lil Nas X", "Post Malone", "Selena Gomez Fan Page", "Jason Derulo", "Gal Gadot",
    "Conor McGregor", "Hailey Bieber", "Zac Efron", "Bella Hadid", "PUBG Mobile",
    "Sergio Ramos", "Hardik Pandya", "Deepika Padukone", "Alia Bhatt", "Neha Kakkar",
    "Anushka Sharma", "The Rock (Fan Page)", "Ryan Reynolds", "Manchester City", "Tom Holland",
    "Juventus", "Marvel", "Salman Khan", "Akshay Kumar", "James Rodriguez",
    "Bayern Munich", "WWE", "Marcelo", "Ozil", "Gerard Piqué",
    "Lewis Hamilton", "Mohamed Salah", "Chelsea FC", "Gareth Bale", "Netflix",
  ],
  values: [
    "676M", "650M", "504M", "425M", "400M",
    "397M", "380M", "364M", "320M", "312M",
    "306M", "294M", "294M", "284M", "284M",
    "275M", "253M", "228M", "228M", "228M",
    "218M", "206M", "185M", "181M", "175M",
    "170M", "157M", "156M", "153M", "151M",
    "149M", "147M", "143M", "134M", "119M",
    "104M", "101M", "96M", "95M", "91M",
    "90M", "89M", "88M", "87M", "86M",
    "86M", "85M", "83M", "82M", "81M",
    "79M", "78M", "72M", "71M", "69M",
    "68M", "66M", "65M", "65M", "64M",
    "63M", "62M", "61M", "60M", "59M",
    "58M", "57M", "56M", "56M", "55M",
    "54M", "54M", "53M", "53M", "52M",
    "52M", "51M", "50M", "50M", "49M",
    "48M", "48M", "47M", "47M", "46M",
    "46M", "45M", "45M", "44M", "44M",
    "43M", "43M", "42M", "42M", "41M",
    "41M", "41M", "40M", "40M", "39M",
  ],
};
