import type { GameList } from './types';

export const mostWatchedAnime: GameList = {
  id: 'most-watched-anime',
  name: 'Most Watched Anime',
  description: 'Anime series by all-time global popularity',
  topics: ['entertainment', 'top 50'],
  size: 50,
  newUntil: '2026-04-15',
  items: [
    "Dragon Ball Z",
    "One Piece",
    "Naruto",
    "Attack on Titan",
    "Death Note",
    "Pokémon",
    "Demon Slayer",
    "Fullmetal Alchemist: Brotherhood",
    "Sword Art Online",
    "My Hero Academia",
    "One-Punch Man",
    "Naruto Shippuden",
    "Hunter x Hunter",
    "Tokyo Ghoul",
    "Bleach",
    "Dragon Ball",
    "Sailor Moon",
    "Neon Genesis Evangelion",
    "Cowboy Bebop",
    "Jujutsu Kaisen",
    "Fairy Tail",
    "Code Geass",
    "Steins;Gate",
    "Mob Psycho 100",
    "Spy x Family",
    "JoJo's Bizarre Adventure",
    "Chainsaw Man",
    "Yu Yu Hakusho",
    "Inuyasha",
    "Erased",
    "Vinland Saga",
    "The Seven Deadly Sins",
    "Re:Zero",
    "Haikyuu!!",
    "Black Clover",
    "Parasyte",
    "Your Lie in April",
    "Gurren Lagann",
    "Yu-Gi-Oh!",
    "Trigun",
    "Fruits Basket",
    "Dr. Stone",
    "Fire Force",
    "Overlord",
    "Violet Evergarden",
    "That Time I Got Reincarnated as a Slime",
    "The Promised Neverland",
    "Soul Eater",
    "Psycho-Pass",
    "Dandadan",
  ],
  hints: [
    // Top 50 (the actual answers)
    "Dragon Ball Z", "One Piece", "Naruto", "Attack on Titan", "Death Note",
    "Pokemon", "Pokémon", "Demon Slayer", "Kimetsu no Yaiba", "Fullmetal Alchemist Brotherhood",
    "Fullmetal Alchemist: Brotherhood", "FMA Brotherhood", "FMA", "Sword Art Online", "SAO",
    "My Hero Academia", "Boku no Hero Academia", "MHA", "One Punch Man", "One-Punch Man",
    "OPM", "Naruto Shippuden", "Naruto Shippūden", "Hunter x Hunter", "HxH",
    "Hunter Hunter", "Tokyo Ghoul", "Bleach", "Dragon Ball", "Dragonball",
    "Dragonball Z", "DBZ", "Sailor Moon", "Neon Genesis Evangelion", "NGE",
    "Evangelion", "Cowboy Bebop", "Jujutsu Kaisen", "JJK", "Fairy Tail",
    "Code Geass", "Steins Gate", "Steins;Gate", "Mob Psycho 100", "Mob Psycho",
    "Spy x Family", "Spy Family", "JoJo's Bizarre Adventure", "JoJo", "Jojos Bizarre Adventure",
    "Chainsaw Man", "CSM", "Yu Yu Hakusho", "YuYu Hakusho", "Inuyasha",
    "Erased", "Boku dake ga Inai Machi", "Vinland Saga", "Seven Deadly Sins",
    "The Seven Deadly Sins", "Nanatsu no Taizai", "Re Zero", "Re:Zero",
    "Haikyuu", "Haikyuu!!", "Haikyu", "Black Clover", "Parasyte",
    "Kiseijuu", "Your Lie in April", "Shigatsu wa Kimi no Uso",
    "Gurren Lagann", "Tengen Toppa Gurren Lagann", "Yu-Gi-Oh", "Yu Gi Oh", "Yugioh",
    "Trigun", "Fruits Basket", "Furuba", "Dr Stone", "Dr. Stone",
    "Fire Force", "Enen no Shouboutai", "Overlord", "Violet Evergarden",
    "That Time I Got Reincarnated as a Slime", "Tensura", "TenSura", "Slime Isekai",
    "The Promised Neverland", "Yakusoku no Neverland", "Soul Eater",
    "Psycho Pass", "Psycho-Pass", "Dandadan", "DanDaDan",
    // Beyond top 50 — popular anime people might guess
    "Akira", "Ghost in the Shell", "Spirited Away", "Princess Mononoke",
    "My Neighbor Totoro", "Howl's Moving Castle", "Grave of the Fireflies",
    "Samurai Champloo", "Rurouni Kenshin", "Berserk", "Claymore",
    "Kill la Kill", "Toradora", "Clannad", "Angel Beats",
    "Elfen Lied", "Hellsing", "Trigun Stampede", "Blue Lock",
    "Bocchi the Rock", "Oshi no Ko", "Frieren", "Solo Leveling",
    "Kaiju No. 8", "Mushoku Tensei", "Konosuba", "Shield Hero",
    "Rising of the Shield Hero", "Classroom of the Elite", "Assassination Classroom",
    "Ansatsu Kyoushitsu", "Durarara", "Noragami", "Blue Exorcist",
    "Ao no Exorcist", "Magi", "Food Wars", "Shokugeki no Soma",
    "Made in Abyss", "The Rising of the Shield Hero", "Dororo",
    "Bungo Stray Dogs", "Mob Psycho", "Cells at Work", "Hataraku Saibou",
    "Devilman Crybaby", "Wonder Egg Priority", "86", "Eighty-Six",
    "Ranking of Kings", "Ousama Ranking", "Odd Taxi", "Link Click",
    "Cyberpunk Edgerunners", "Bocchi", "Slam Dunk", "Initial D",
    "Case Closed", "Detective Conan", "Lupin the Third", "Lupin III",
    "Fist of the North Star", "Hokuto no Ken", "Gundam", "Mobile Suit Gundam",
    "Macross", "Robotech", "Astro Boy", "Speed Racer",
    "Doraemon", "Shin-chan", "Crayon Shin-chan",
  ],
  aliases: {
    "DBZ": "Dragon Ball Z",
    "Dragonball Z": "Dragon Ball Z",
    "Dragonball": "Dragon Ball",
    "Pokemon": "Pokémon",
    "Kimetsu no Yaiba": "Demon Slayer",
    "FMA Brotherhood": "Fullmetal Alchemist: Brotherhood",
    "FMA": "Fullmetal Alchemist: Brotherhood",
    "Fullmetal Alchemist Brotherhood": "Fullmetal Alchemist: Brotherhood",
    "SAO": "Sword Art Online",
    "Boku no Hero Academia": "My Hero Academia",
    "MHA": "My Hero Academia",
    "One Punch Man": "One-Punch Man",
    "OPM": "One-Punch Man",
    "Naruto Shippūden": "Naruto Shippuden",
    "HxH": "Hunter x Hunter",
    "Hunter Hunter": "Hunter x Hunter",
    "NGE": "Neon Genesis Evangelion",
    "Evangelion": "Neon Genesis Evangelion",
    "JJK": "Jujutsu Kaisen",
    "Steins Gate": "Steins;Gate",
    "Mob Psycho": "Mob Psycho 100",
    "Spy Family": "Spy x Family",
    "JoJo": "JoJo's Bizarre Adventure",
    "Jojos Bizarre Adventure": "JoJo's Bizarre Adventure",
    "CSM": "Chainsaw Man",
    "YuYu Hakusho": "Yu Yu Hakusho",
    "Boku dake ga Inai Machi": "Erased",
    "Seven Deadly Sins": "The Seven Deadly Sins",
    "Nanatsu no Taizai": "The Seven Deadly Sins",
    "Re Zero": "Re:Zero",
    "Haikyuu": "Haikyuu!!",
    "Haikyu": "Haikyuu!!",
    "Kiseijuu": "Parasyte",
    "Shigatsu wa Kimi no Uso": "Your Lie in April",
    "Tengen Toppa Gurren Lagann": "Gurren Lagann",
    "Yu Gi Oh": "Yu-Gi-Oh!",
    "Yugioh": "Yu-Gi-Oh!",
    "Yu-Gi-Oh": "Yu-Gi-Oh!",
    "Furuba": "Fruits Basket",
    "Dr Stone": "Dr. Stone",
    "Enen no Shouboutai": "Fire Force",
    "Tensura": "That Time I Got Reincarnated as a Slime",
    "TenSura": "That Time I Got Reincarnated as a Slime",
    "Slime Isekai": "That Time I Got Reincarnated as a Slime",
    "Yakusoku no Neverland": "The Promised Neverland",
    "Psycho Pass": "Psycho-Pass",
    "DanDaDan": "Dandadan",
  },
};
