import type { GameList } from './types';
import { mostVisitedNationalParksHints } from './hints';

export const mostVisitedNationalParks: GameList = {
  id: 'most-visited-national-parks',
  name: 'Most Visited US National Parks',
  description: 'US National Parks ranked by annual recreation visitors (NPS, 2024)',
  topics: ['geography'],
  difficulty: 2,
  hints: mostVisitedNationalParksHints,
  valueLabel: 'Annual Visitors',
  size: 50,
  newUntil: '2025-08-01',
  items: [
    "Great Smoky Mountains", "Zion", "Grand Canyon", "Yellowstone", "Rocky Mountain",
    "Yosemite", "Acadia", "Olympic", "Grand Teton", "Glacier",
    "Joshua Tree", "Cuyahoga Valley", "Indiana Dunes", "Gateway Arch", "Bryce Canyon",
    "Hot Springs", "New River Gorge", "Shenandoah", "Mount Rainier", "Arches",
    "Death Valley", "Hawaii Volcanoes", "Capitol Reef", "Sequoia", "Badlands",
    "Saguaro", "Canyonlands", "Mammoth Cave", "Everglades", "Glacier Bay",
    "Theodore Roosevelt", "Haleakala", "White Sands", "Kings Canyon", "Redwood",
    "Big Bend", "Petrified Forest", "Biscayne", "Crater Lake", "Wind Cave",
    "Mesa Verde", "Denali", "Carlsbad Caverns", "Great Sand Dunes", "Virgin Islands",
    "Kenai Fjords", "Lassen Volcanic", "Pinnacles", "Black Canyon of the Gunnison", "Channel Islands",
  ],
  values: [
    "12.2M visitors", "4.9M visitors", "4.9M visitors", "4.7M visitors", "4.2M visitors",
    "4.1M visitors", "4.0M visitors", "3.7M visitors", "3.6M visitors", "3.2M visitors",
    "3.0M visitors", "2.9M visitors", "2.7M visitors", "2.6M visitors", "2.5M visitors",
    "2.5M visitors", "1.8M visitors", "1.7M visitors", "1.6M visitors", "1.5M visitors",
    "1.4M visitors", "1.4M visitors", "1.4M visitors", "1.3M visitors", "1.1M visitors",
    "946K visitors", "818K visitors", "747K visitors", "742K visitors", "736K visitors",
    "733K visitors", "732K visitors", "702K visitors", "699K visitors", "623K visitors",
    "561K visitors", "560K visitors", "512K visitors", "505K visitors", "489K visitors",
    "480K visitors", "466K visitors", "460K visitors", "438K visitors", "423K visitors",
    "419K visitors", "358K visitors", "354K visitors", "336K visitors", "263K visitors",
  ],
  aliases: {
    "Smokies": "Great Smoky Mountains",
    "Great Smokies": "Great Smoky Mountains",
    "GSMNP": "Great Smoky Mountains",
    "GC": "Grand Canyon",
    "RMNP": "Rocky Mountain",
    "GTNP": "Grand Teton",
    "Tetons": "Grand Teton",
    "Teton": "Grand Teton",
    "Glacier NP": "Glacier",
    "JTree": "Joshua Tree",
    "Bryce": "Bryce Canyon",
    "Volcanoes": "Hawaii Volcanoes",
    "Big Island Volcanoes": "Hawaii Volcanoes",
    "Capitol": "Capitol Reef",
    "Badlands NP": "Badlands",
    "Cuyahoga": "Cuyahoga Valley",
    "Indiana Dunes NP": "Indiana Dunes",
    "Gateway Arch NP": "Gateway Arch",
    "St. Louis Arch": "Gateway Arch",
    "New River": "New River Gorge",
    "Shenandoah NP": "Shenandoah",
    "Rainier": "Mount Rainier",
    "Mt. Rainier": "Mount Rainier",
    "Arches NP": "Arches",
    "Death Valley NP": "Death Valley",
    "Capitol Reef NP": "Capitol Reef",
    "Sequoia NP": "Sequoia",
    "Saguaro NP": "Saguaro",
    "Mammoth Cave NP": "Mammoth Cave",
    "Glacier Bay NP": "Glacier Bay",
    "TR National Park": "Theodore Roosevelt",
    "Haleakala NP": "Haleakala",
    "White Sands NP": "White Sands",
    "Kings": "Kings Canyon",
    "Redwood NP": "Redwood",
    "Big Bend NP": "Big Bend",
    "Petrified Forest NP": "Petrified Forest",
    "Crater Lake NP": "Crater Lake",
    "Wind Cave NP": "Wind Cave",
    "Mesa Verde NP": "Mesa Verde",
    "Denali NP": "Denali",
    "McKinley": "Denali",
    "Mount McKinley": "Denali",
    "Carlsbad Caverns NP": "Carlsbad Caverns",
    "Great Sand Dunes NP": "Great Sand Dunes",
    "Virgin Islands NP": "Virgin Islands",
    "Kenai Fjords NP": "Kenai Fjords",
    "Lassen": "Lassen Volcanic",
    "Lassen Volcanic NP": "Lassen Volcanic",
    "Black Canyon": "Black Canyon of the Gunnison",
    "Channel Islands NP": "Channel Islands",
  },
};
