import type { GameList } from './types';
import { mostFollowedTwitterHints } from './hints';

export const mostFollowedTwitter: GameList = {
  id: 'most-followed-twitter',
  name: 'Most Followed Twitter/X Accounts',
  description: 'Twitter/X accounts ranked by follower count (Wikipedia, 2025)',
  topics: ['internet'],
  hints: mostFollowedTwitterHints,
  valueLabel: 'Followers',
  items: [
    "Elon Musk", "Barack Obama", "Cristiano Ronaldo", "Justin Bieber", "Katy Perry",
    "Rihanna", "Donald Trump", "Narendra Modi", "Taylor Swift", "NASA",
    "Lady Gaga", "YouTube", "Virat Kohli", "Ellen DeGeneres", "Kim Kardashian",
    "Selena Gomez", "Bill Gates", "X (Twitter)", "CNN", "CNN Breaking News",
    "Neymar", "ESPN", "PMO India", "The New York Times", "UEFA Champions League",
    "BBC Breaking News", "Real Madrid CF", "LeBron James", "Justin Timberlake", "BTS",
    "FC Barcelona", "NBA", "Shakira", "Premier League", "Amitabh Bachchan",
    "BTS Official", "Akshay Kumar", "Demi Lovato", "PlayStation", "Jimmy Fallon",
    "Britney Spears", "Salman Khan", "BBC World News", "SportsCenter", "SpaceX",
    "Miley Cyrus", "Shah Rukh Khan", "Sachin Tendulkar", "Manchester United FC", "Joe Biden",
    "Mohamed Salah", "Fabrizio Romano", "Pope Leo XIV", "Fortnite", "ABC News",
    "Gerard Piqué", "Manchester City", "Ed Sheeran", "Al Arabiya", "Felipe Neto",
    "Netflix France", "Ibai Llanos", "The Associated Press", "Donald Trump Jr.", "Binance",
    "Rafael Nadal", "Al-Waleed bin Talal", "Kylian Mbappé", "Beyoncé", "BBC News UK",
    "Diddy", "Sports", "Tim Cook", "The Times of India", "Billboard",
    "Nintendo of America", "EXO", "Microsoft", "Netflix Thailand", "BT21",
    "Tucker Carlson", "ENHYPEN", "CGTN", "World Health Organization", "Jair Bolsonaro",
    "Formula 1", "Indian National Congress", "China Xinhua News", "HuffPost", "The Guardian",
    "Changpeng Zhao", "Programa Pânico", "TED Talks", "Fantástico", "BLACKPINK",
    "Russell Brand", "Emmanuel Macron", "Serena Williams", "Andrés Manuel López Obrador", "Niall Horan",
  ],
  values: [
    "218M", "131M", "113M", "111M", "108M",
    "106M", "101M", "99M", "96M", "90M",
    "84M", "80M", "78M", "77M", "75M",
    "69M", "67M", "67M", "63M", "63M",
    "60M", "58M", "56M", "55M", "55M",
    "52M", "51M", "50M", "49M", "48M",
    "48M", "47M", "47M", "46M", "45M",
    "44M", "43M", "43M", "43M", "42M",
    "42M", "42M", "41M", "41M", "40M",
    "39M", "39M", "38M", "38M", "37M",
    "37M", "36M", "36M", "35M", "35M",
    "34M", "33M", "33M", "33M", "32M",
    "32M", "32M", "31M", "31M", "31M",
    "30M", "30M", "30M", "29M", "29M",
    "28M", "28M", "28M", "28M", "27M",
    "27M", "27M", "26M", "26M", "26M",
    "25M", "25M", "25M", "25M", "24M",
    "24M", "24M", "24M", "23M", "23M",
    "23M", "23M", "22M", "22M", "22M",
    "21M", "21M", "21M", "21M", "21M",
  ],
};
