// Source: ClinCalc Top 300 Drugs — 2023 US prescription data
// Rankings based on total prescription volume
import type { GameList } from './types';
import { mostPopularMedicationsHints } from './hints/most-popular-medications';

export const mostPopularMedications: GameList = {
  id: 'most-popular-medications',
  name: 'Most Popular Medications in the US',
  description: 'The 100 most prescribed medications in the United States (ClinCalc 2023)',
  topics: ['misc'],
  difficulty: 2,
  hints: mostPopularMedicationsHints,
  newUntil: '2026-06-16',
  items: [
    "Atorvastatin",
    "Metformin",
    "Levothyroxine",
    "Lisinopril",
    "Amlodipine",
    "Metoprolol",
    "Albuterol",
    "Losartan",
    "Gabapentin",
    "Omeprazole",
    "Sertraline",
    "Rosuvastatin",
    "Pantoprazole",
    "Escitalopram",
    "Amphetamine/Dextroamphetamine",
    "Hydrochlorothiazide",
    "Bupropion",
    "Fluoxetine",
    "Semaglutide",
    "Montelukast",
    "Trazodone",
    "Simvastatin",
    "Amoxicillin",
    "Tamsulosin",
    "Hydrocodone/Acetaminophen",
    "Fluticasone",
    "Meloxicam",
    "Apixaban",
    "Furosemide",
    "Insulin Glargine",
    "Duloxetine",
    "Ibuprofen",
    "Famotidine",
    "Empagliflozin",
    "Carvedilol",
    "Tramadol",
    "Alprazolam",
    "Prednisone",
    "Hydroxyzine",
    "Buspirone",
    "Clopidogrel",
    "Glipizide",
    "Citalopram",
    "Potassium Chloride",
    "Allopurinol",
    "Aspirin",
    "Cyclobenzaprine",
    "Ergocalciferol",
    "Oxycodone",
    "Methylphenidate",
    "Venlafaxine",
    "Spironolactone",
    "Ondansetron",
    "Zolpidem",
    "Cetirizine",
    "Estradiol",
    "Pravastatin",
    "Lisinopril/Hydrochlorothiazide",
    "Lamotrigine",
    "Quetiapine",
    "Fluticasone/Salmeterol",
    "Clonazepam",
    "Dulaglutide",
    "Azithromycin",
    "Losartan/Hydrochlorothiazide",
    "Amoxicillin/Clavulanate",
    "Latanoprost",
    "Cholecalciferol",
    "Propranolol",
    "Ezetimibe",
    "Topiramate",
    "Paroxetine",
    "Diclofenac",
    "Budesonide/Formoterol",
    "Atenolol",
    "Lisdexamfetamine",
    "Doxycycline",
    "Pregabalin",
    "Ethinyl Estradiol/Norethindrone",
    "Glimepiride",
    "Tizanidine",
    "Clonidine",
    "Fenofibrate",
    "Insulin Lispro",
    "Valsartan",
    "Cephalexin",
    "Baclofen",
    "Rivaroxaban",
    "Ferrous Sulfate",
    "Amitriptyline",
    "Finasteride",
    "Dapagliflozin",
    "Oxycodone/Acetaminophen",
    "Folic Acid",
    "Aripiprazole",
    "Olmesartan",
    "Ethinyl Estradiol/Norgestimate",
    "Valacyclovir",
    "Mirtazapine",
    "Lorazepam",
  ],
  aliases: {
    // Statins
    "Lipitor": "Atorvastatin",
    "Crestor": "Rosuvastatin",
    "Zocor": "Simvastatin",

    // Diabetes
    "Glucophage": "Metformin",
    "Ozempic": "Semaglutide",
    "Wegovy": "Semaglutide",
    "Rybelsus": "Semaglutide",
    "Jardiance": "Empagliflozin",
    "Glucotrol": "Glipizide",
    "Trulicity": "Dulaglutide",
    "Farxiga": "Dapagliflozin",
    "Lantus": "Insulin Glargine",
    "Basaglar": "Insulin Glargine",
    "Humalog": "Insulin Lispro",

    // Blood pressure / Heart
    "Synthroid": "Levothyroxine",
    "Levoxyl": "Levothyroxine",
    "Zestril": "Lisinopril",
    "Prinivil": "Lisinopril",
    "Norvasc": "Amlodipine",
    "Lopressor": "Metoprolol",
    "Toprol": "Metoprolol",
    "Cozaar": "Losartan",
    "Lasix": "Furosemide",
    "Coreg": "Carvedilol",
    "Plavix": "Clopidogrel",
    "Eliquis": "Apixaban",
    "Xarelto": "Rivaroxaban",
    "Inderal": "Propranolol",
    "Tenormin": "Atenolol",
    "Catapres": "Clonidine",
    "Diovan": "Valsartan",
    "Benicar": "Olmesartan",
    "Zetia": "Ezetimibe",
    "Tricor": "Fenofibrate",

    // Respiratory / Allergy
    "ProAir": "Albuterol",
    "Ventolin": "Albuterol",
    "Flonase": "Fluticasone",
    "Advair": "Fluticasone/Salmeterol",
    "Symbicort": "Budesonide/Formoterol",
    "Singulair": "Montelukast",
    "Zyrtec": "Cetirizine",

    // GI
    "Prilosec": "Omeprazole",
    "Protonix": "Pantoprazole",
    "Pepcid": "Famotidine",
    "Zofran": "Ondansetron",

    // Antidepressants / Mood
    "Zoloft": "Sertraline",
    "Lexapro": "Escitalopram",
    "Wellbutrin": "Bupropion",
    "Prozac": "Fluoxetine",
    "Desyrel": "Trazodone",
    "Cymbalta": "Duloxetine",
    "Celexa": "Citalopram",
    "Effexor": "Venlafaxine",
    "Paxil": "Paroxetine",
    "Elavil": "Amitriptyline",
    "Remeron": "Mirtazapine",

    // Antipsychotics
    "Seroquel": "Quetiapine",
    "Abilify": "Aripiprazole",

    // Anticonvulsants
    "Neurontin": "Gabapentin",
    "Lamictal": "Lamotrigine",
    "Topamax": "Topiramate",
    "Lyrica": "Pregabalin",

    // Benzodiazepines / Sleep
    "Xanax": "Alprazolam",
    "Klonopin": "Clonazepam",
    "Ativan": "Lorazepam",
    "Ambien": "Zolpidem",

    // Pain
    "Vicodin": "Hydrocodone/Acetaminophen",
    "Norco": "Hydrocodone/Acetaminophen",
    "Mobic": "Meloxicam",
    "Advil": "Ibuprofen",
    "Motrin": "Ibuprofen",
    "Ultram": "Tramadol",
    "Voltaren": "Diclofenac",
    "OxyContin": "Oxycodone",
    "Roxicodone": "Oxycodone",
    "Percocet": "Oxycodone/Acetaminophen",

    // Muscle Relaxants
    "Flexeril": "Cyclobenzaprine",
    "Zanaflex": "Tizanidine",

    // ADHD
    "Adderall": "Amphetamine/Dextroamphetamine",
    "Ritalin": "Methylphenidate",
    "Concerta": "Methylphenidate",
    "Vyvanse": "Lisdexamfetamine",

    // Antibiotics
    "Zithromax": "Azithromycin",
    "Z-Pack": "Azithromycin",
    "Augmentin": "Amoxicillin/Clavulanate",
    "Keflex": "Cephalexin",

    // Steroids
    "Deltasone": "Prednisone",

    // Misc
    "Aldactone": "Spironolactone",
    "Vistaril": "Hydroxyzine",
    "Atarax": "Hydroxyzine",
    "BuSpar": "Buspirone",
    "Zyloprim": "Allopurinol",
    "Xalatan": "Latanoprost",
    "Flomax": "Tamsulosin",
    "Propecia": "Finasteride",
    "Proscar": "Finasteride",
    "Valtrex": "Valacyclovir",
  },
};
