import type { GameList } from './types';
import { mostStreamedSongsHints } from './hints';

export const mostStreamedSongs: GameList = {
  id: 'most-streamed-songs',
  name: 'Most Streamed Songs on Spotify',
  description: 'All-time most streamed tracks',
  topics: ['entertainment', 'music'],
  hints: mostStreamedSongsHints,
  valueLabel: 'Streams',
  items: [
    "Blinding Lights", "Shape of You", "Someone You Loved", "As It Was", "Sunflower",
    "Dance Monkey", "Starboy", "Closer", "One Dance", "Believer",
    "Rockstar", "Heat Waves", "Stay", "Watermelon Sugar", "Lovely",
    "Don't Start Now", "Señorita", "Perfect", "Lucid Dreams", "Bohemian Rhapsody",
    "Say You Won't Let Go", "Thinking Out Loud", "God's Plan", "Save Your Tears", "Bad Guy",
    "Levitating", "Circles", "Without Me", "Thunder", "I'm Gonna Be (500 Miles)",
    "Shallow", "Love Yourself", "Happier", "Photograph", "Let Her Go",
    "Counting Stars", "Cruel Summer", "Anti-Hero", "Peaches", "Take Me to Church",
    "Riptide", "Sugar", "Jocelyn Flores", "SAD!", "Flowers",
    "Drivers License", "Sweater Weather", "7 Rings", "Sicko Mode", "Despacito",
    "Lean On", "Havana", "Stressed Out", "New Rules", "All of Me",
    "Mood", "Girls Like You", "Old Town Road", "Radioactive", "Uptown Funk",
    "Sorry", "Treat You Better", "There's Nothing Holdin' Me Back", "Something Just Like This", "Thank U Next",
    "High Hopes", "Heather", "XO Tour Llif3", "I Don't Care", "Congratulations",
    "Youngblood", "HUMBLE.", "Feel Good Inc.", "I Ain't Worried", "Dynamite",
    "Attention", "Die For You", "What Makes You Beautiful", "Ride", "Smells Like Teen Spirit",
    "Vampire", "Bad Habits", "Under the Bridge", "Dandelions", "Glimpse of Us",
    "Can't Hold Us", "River Flows in You", "Die with a Smile", "Golden Hour", "Thinkin Bout You",
    "Memories", "Before You Go", "Until I Found You", "Snowman", "Physical",
    "Unstoppable", "Gym Class Heroes: Stereo Hearts", "I Wanna Be Yours", "Put Your Records On", "Tongue Tied"
  ],
  values: [
    "4.8B", "4.2B", "3.7B", "3.6B", "3.5B",
    "3.4B", "3.4B", "3.3B", "3.2B", "3.1B",
    "3.1B", "3.0B", "2.9B", "2.9B", "2.9B",
    "2.8B", "2.8B", "2.8B", "2.8B", "2.7B",
    "2.7B", "2.7B", "2.7B", "2.6B", "2.6B",
    "2.6B", "2.6B", "2.5B", "2.5B", "2.5B",
    "2.5B", "2.4B", "2.4B", "2.4B", "2.4B",
    "2.4B", "2.3B", "2.3B", "2.3B", "2.3B",
    "2.3B", "2.2B", "2.2B", "2.2B", "2.2B",
    "2.2B", "2.2B", "2.1B", "2.1B", "2.1B",
    "2.1B", "2.1B", "2.0B", "2.0B", "2.0B",
    "2.0B", "2.0B", "2.0B", "1.9B", "1.9B",
    "1.9B", "1.9B", "1.9B", "1.9B", "1.9B",
    "1.8B", "1.8B", "1.8B", "1.8B", "1.8B",
    "1.8B", "1.8B", "1.8B", "1.7B", "1.7B",
    "1.7B", "1.7B", "1.7B", "1.7B", "1.7B",
    "1.7B", "1.6B", "1.6B", "1.6B", "1.6B",
    "1.6B", "1.6B", "1.6B", "1.6B", "1.6B",
    "1.5B", "1.5B", "1.5B", "1.5B", "1.5B",
    "1.5B", "1.5B", "1.5B", "1.5B", "1.5B",
  ],
};
