import type { GameList } from './types';
import { mostVisitedCountriesHints } from './hints';

export const mostVisitedCountries: GameList = {
  id: 'most-visited-countries',
  name: 'Most Visited Countries by Tourists',
  description: 'Countries ranked by international tourist arrivals (UNWTO, 2024)',
  topics: ['geography'],
  hints: mostVisitedCountriesHints,
  valueLabel: 'Annual Visitors',
  items: [
    "France", "Spain", "United States", "Italy", "Turkey",
    "Mexico", "United Kingdom", "Germany", "Japan", "Austria",
    "Saudi Arabia", "Portugal", "Malaysia", "Thailand", "China",
    "Hong Kong", "Netherlands", "Canada", "Poland", "Vietnam",
    "Morocco", "South Korea", "Macau", "Egypt", "Indonesia",
    "Romania", "Bulgaria", "Hungary", "Singapore", "Albania",
    "Czechia", "Kazakhstan", "Tunisia", "India", "Belgium",
    "Ireland", "South Africa", "Dominican Republic", "Uzbekistan", "Taiwan",
    "Sweden", "Brazil", "Cambodia", "Bahrain", "Argentina",
    "Norway", "Philippines", "Puerto Rico", "Australia", "Chile",
    "Colombia", "Jordan", "Qatar", "Georgia", "Denmark",
    "Switzerland", "Finland", "New Zealand", "Cuba", "Jamaica",
    "Iceland", "Cyprus", "Greece", "Croatia", "Israel",
    "Oman", "Azerbaijan", "Peru", "Kenya", "Sri Lanka",
    "Maldives", "Nepal", "Armenia", "Tanzania", "Ecuador",
    "Uruguay", "Costa Rica", "Bolivia", "Guatemala", "Panama",
    "El Salvador", "Honduras", "Nicaragua", "Paraguay", "Pakistan",
    "Bangladesh", "Uganda", "Zimbabwe", "Zambia", "Mauritius",
    "Ethiopia", "Myanmar", "Bhutan", "Seychelles", "Fiji",
    "Papua New Guinea", "Belize", "Namibia", "Laos", "Montenegro",
  ],
  values: [
    "100M", "85M", "77M", "65M", "56M",
    "51M", "38M", "37M", "35M", "34M",
    "30M", "30M", "28M", "28M", "27M",
    "27M", "26M", "25M", "24M", "23M",
    "22M", "21M", "21M", "20M", "18M",
    "17M", "17M", "16M", "16M", "15M",
    "15M", "15M", "14M", "13M", "13M",
    "12M", "12M", "12M", "11M", "11M",
    "10M", "10M", "10M", "10M", "9M",
    "8M", "8M", "8M", "8M", "7M",
    "7M", "7M", "7M", "6M", "6M",
    "6M", "5M", "5M", "5M", "5M",
    "4M", "4M", "4M", "4M", "4M",
    "3M", "3M", "3M", "3M", "3M",
    "2M", "2M", "2M", "2M", "2M",
    "2M", "2M", "2M", "2M", "2M",
    "1.5M", "1.5M", "1.5M", "1.5M", "1.5M",
    "1M", "1M", "1M", "1M", "1M",
    "1M", "900K", "800K", "700K", "600K",
    "500K", "500K", "500K", "500K", "500K",
  ],
};
