import type { GameList } from './types';
import { nflPlayersHints } from './hints/nfl-players';

export const nflCareerTouchdowns: GameList = {
  id: 'nfl-career-touchdowns',
  name: 'NFL All-Time Total Touchdowns Leaders',
  description: 'NFL players ranked by all-time career total touchdowns (Pro Football Reference)',
  topics: ['sports'],
  difficulty: 2,
  hints: nflPlayersHints,
  valueLabel: 'Total TDs',
  items: [
    "Jerry Rice", "Emmitt Smith", "LaDainian Tomlinson", "Randy Moss", "Terrell Owens",
    "Marcus Allen", "Marshall Faulk", "Cris Carter", "Marvin Harrison", "Jim Brown",
    "Walter Payton", "Larry Fitzgerald", "Adrian Peterson", "Antonio Gates", "John Riggins",
    "Lenny Moore", "Shaun Alexander", "Tony Gonzalez", "Barry Sanders", "Don Hutson",
    "Tim Brown", "Steve Largent", "Curtis Martin", "Frank Gore", "Franco Harris",
    "Derrick Henry", "Eric Dickerson", "Tony Dorsett", "Davante Adams", "Jerome Bettis",
    "Rob Gronkowski", "LeSean McCoy", "Ricky Watters", "Bobby Mitchell", "Christian McCaffrey",
    "Leroy Kelly", "Jimmy Graham", "Thurman Thomas", "Mike Evans", "Don Maynard",
    "Lance Alworth", "Hines Ward", "Priest Holmes", "Andre Reed", "Antonio Brown",
    "Marshawn Lynch", "Paul Warfield", "Calvin Johnson", "Brandon Marshall", "Corey Dillon",
    "Reggie Wayne", "Clinton Portis", "Edgerrin James", "Tyreek Hill", "Todd Gurley",
    "Harold Carmichael", "Charley Taylor", "Ahman Green", "Travis Kelce", "Chuck Foreman",
    "Steve Smith Sr.", "Fred Taylor", "Jason Witten", "Jamaal Charles", "Dez Bryant",
    "Ezekiel Elliott", "Andre Johnson", "Art Monk", "Rod Smith", "Tiki Barber",
    "Chad Johnson", "Alvin Kamara", "Anquan Boldin", "Jimmy Smith", "Warrick Dunn",
    "Michael Irvin", "Sterling Sharpe", "Aaron Jones", "Charlie Joiner", "Henry Ellard",
    "Darren Sproles", "DeMarco Murray", "Thomas Jones", "Derrick Mason", "Shannon Sharpe",
    "Donald Driver", "Julio Jones", "Isaac Bruce", "Torry Holt", "Chris Johnson",
    "Greg Olsen", "Joe Mixon", "Dalvin Cook", "Saquon Barkley", "Nick Chubb",
    "Wes Welker", "Tony Hill", "Josh Jacobs", "Jonathan Taylor", "Le'Veon Bell",
  ],
  values: [
    "208", "175", "162", "157", "156",
    "145", "136", "131", "128", "126",
    "125", "121", "120", "116", "116",
    "113", "112", "111", "109", "105",
    "105", "101", "100", "100", "100",
    "99", "96", "96", "96", "94",
    "92", "91", "91", "91", "90",
    "90", "89", "88", "88", "88",
    "87", "86", "86", "86", "85",
    "85", "85", "83", "83", "82",
    "82", "80", "80", "79", "79",
    "79", "79", "77", "76", "75",
    "75", "74", "74", "73", "73",
    "72", "70", "68", "68", "67",
    "67", "67", "67", "67", "66",
    "65", "65", "65", "65", "65",
    "64", "63", "63", "63", "62",
    "61", "61", "60", "60", "60",
    "60", "55", "54", "53", "52",
    "50", "49", "47", "43", "42",
  ],
};
