import type { GameList } from './types';
import { oscarNominationsHints } from './hints';

export const oscarNominations: GameList = {
  id: 'oscar-nominations',
  name: 'Movies with Most Oscar Nominations',
  description: 'Films ranked by total Academy Award nominations, all time (Oscars.org)',
  topics: ['film & tv'],
  size: 99,
  hints: oscarNominationsHints,
  valueLabel: 'Nominations',
  items: [
    "All About Eve", "Titanic", "La La Land", "Gone with the Wind", "The Shape of Water",
    "From Here to Eternity", "Mary Poppins", "Who's Afraid of Virginia Woolf?", "Forrest Gump", "Shakespeare in Love",
    "The Lord of the Rings: The Return of the King", "Ben-Hur", "Chicago", "Saving Private Ryan", "Mrs. Miniver",
    "On the Waterfront", "The King's Speech", "Lincoln", "Oppenheimer", "The Curious Case of Benjamin Button",
    "Schindler's List", "The English Patient", "Avatar", "Gangs of New York", "The Godfather",
    "Cabaret", "A Star Is Born (2018)", "The Irishman", "Dances with Wolves", "West Side Story (1961)",
    "Gandhi", "Hugo", "The Aviator", "Braveheart", "The Revenant",
    "American Hustle", "Gravity", "Bohemian Rhapsody", "Mad Max: Fury Road", "Million Dollar Baby",
    "Gladiator", "Rocky", "The Apartment", "Reds", "Terms of Endearment",
    "Rain Man", "A Beautiful Mind", "The Hurt Locker", "12 Years a Slave", "Birdman",
    "Spotlight", "Moonlight", "The Sound of Music", "Doctor Zhivago", "My Fair Lady",
    "Tootsie", "The Color Purple", "JFK", "Amadeus", "Out of Africa",
    "Kramer vs. Kramer", "One Flew Over the Cuckoo's Nest", "Annie Hall", "The Deer Hunter", "Platoon",
    "Silence of the Lambs", "Unforgiven", "No Country for Old Men", "The Departed", "American Beauty",
    "Slumdog Millionaire", "The Artist", "Argo", "Parasite",
    "Nomadland", "CODA", "Everything Everywhere All at Once", "The Godfather Part II", "Chinatown",
    "Network", "Jaws", "Star Wars", "E.T. the Extra-Terrestrial", "Raiders of the Lost Ark",
    "Goodfellas", "Pulp Fiction", "Fargo", "The Shawshank Redemption", "The Pianist",
    "Black Panther", "Joker", "1917", "Little Women (2019)", "Ford v Ferrari",
    "Mank", "Judas and the Black Messiah", "The Power of the Dog", "Dune", "Killers of the Flower Moon",
  ],
  values: [
    "14", "14", "14", "13", "13",
    "13", "13", "13", "13", "13",
    "12", "12", "13", "11", "12",
    "12", "12", "12", "13", "13",
    "12", "12", "9", "10", "11",
    "10", "8", "10", "12", "11",
    "11", "11", "11", "10", "12",
    "10", "10", "5", "10", "7",
    "12", "10", "10", "12", "11",
    "8", "8", "9", "9", "9",
    "6", "8", "10", "10", "12",
    "10", "11", "8", "11", "11",
    "9", "9", "5", "9", "8",
    "7", "9", "8", "5", "8",
    "6", "10", "10", "7", "6",
    "6", "3", "11", "11", "11",
    "10", "4", "11", "9", "9",
    "6", "7", "7", "7", "5",
    "7", "7", "4", "6", "4",
    "10", "6", "12", "10",
  ],
};
