import type { GameList } from './types';
import { oscarNominationsHints } from './hints';

export const oscarNominations: GameList = {
  id: 'oscar-nominations',
  name: 'Movies with Most Oscar Nominations',
  description: 'Films ranked by total Academy Award nominations, all time (Oscars.org)',
  topics: ['film & tv'],
  difficulty: 2,
  hints: oscarNominationsHints,
  valueLabel: 'Nominations',
  items: [
    "Titanic", "All About Eve", "La La Land", "Mary Poppins", "Who's Afraid of Virginia Woolf?",
    "From Here to Eternity", "Gone with the Wind", "Forrest Gump", "The Shape of Water", "Shakespeare in Love",
    "Chicago", "Oppenheimer", "The Curious Case of Benjamin Button", "The Lord of the Rings: The Return of the King", "Ben-Hur",
    "The King's Speech", "On the Waterfront", "Lincoln", "Mrs. Miniver", "Schindler's List",
    "The English Patient", "Dances with Wolves", "The Revenant", "Gladiator", "Reds",
    "My Fair Lady", "Dune", "Saving Private Ryan", "The Godfather", "Gandhi",
    "Hugo", "West Side Story (1961)", "The Aviator", "Terms of Endearment", "The Color Purple",
    "Out of Africa", "Amadeus", "The Godfather Part II", "Chinatown", "Network",
    "E.T. the Extra-Terrestrial", "Gangs of New York", "Cabaret", "The Irishman", "Braveheart",
    "American Hustle", "Gravity", "Mad Max: Fury Road", "The Apartment", "Rocky",
    "Doctor Zhivago", "The Sound of Music", "Tootsie", "Argo", "The Artist",
    "Jaws", "Judas and the Black Messiah", "Killers of the Flower Moon", "Avatar", "Birdman",
    "The Hurt Locker", "12 Years a Slave", "One Flew Over the Cuckoo's Nest", "Kramer vs. Kramer", "The Deer Hunter",
    "Unforgiven", "Goodfellas", "Raiders of the Lost Ark", "The Banshees of Inisherin", "A Star Is Born (2018)",
    "Rain Man", "A Beautiful Mind", "Moonlight", "JFK", "Platoon",
    "No Country for Old Men", "American Beauty", "Million Dollar Baby", "Silence of the Lambs", "Parasite",
    "Fargo", "The Shawshank Redemption", "The Pianist", "Joker", "1917",
    "Spotlight", "Slumdog Millionaire", "Nomadland", "CODA", "Pulp Fiction",
    "Ford v Ferrari", "The Power of the Dog", "Bohemian Rhapsody", "Annie Hall", "The Departed",
    "Black Panther", "Star Wars", "Little Women (2019)", "Mank", "Everything Everywhere All at Once",
  ],
  values: [
    "14", "14", "14", "13", "13",
    "13", "13", "13", "13", "13",
    "13", "13", "13", "12", "12",
    "12", "12", "12", "12", "12",
    "12", "12", "12", "12", "12",
    "12", "12", "11", "11", "11",
    "11", "11", "11", "11", "11",
    "11", "11", "11", "11", "11",
    "11", "10", "10", "10", "10",
    "10", "10", "10", "10", "10",
    "10", "10", "10", "10", "10",
    "10", "10", "10", "9", "9",
    "9", "9", "9", "9", "9",
    "9", "9", "9", "9", "8",
    "8", "8", "8", "8", "8",
    "8", "8", "7", "7", "7",
    "7", "7", "7", "7", "7",
    "6", "6", "6", "6", "6",
    "6", "6", "5", "5", "5",
    "5", "4", "4", "4", "3",
  ],
  aliases: {
    "The Silence of the Lambs": "Silence of the Lambs",
    "Chicago (2002)": "Chicago",
    "Benjamin Button": "The Curious Case of Benjamin Button",
    "West Side Story": "West Side Story (1961)",
    "A Star Is Born": "A Star Is Born (2018)",
  },
};
