import type { GameList } from './types';
import { qsWorldUniversityRankingsHints } from './hints';

// Source: QS World University Rankings 2026 (topuniversities.com / xuanxiao.org)
// Released: 2026. Scores are overall QS scores out of 100.
export const qsWorldUniversityRankings: GameList = {
  id: 'qs-world-university-rankings',
  name: 'QS World University Rankings',
  description: 'Top 100 universities worldwide by QS score (QS World University Rankings 2026)',
  topics: ['education', 'misc'],
  hints: qsWorldUniversityRankingsHints,
  valueLabel: 'QS Score',
  items: [
    "MIT", "Imperial College London", "Stanford", "University of Oxford", "Harvard",
    "University of Cambridge", "ETH Zurich", "NUS", "UCL", "Caltech",
    "University of Hong Kong", "NTU Singapore", "University of Chicago", "Peking University", "UPenn",
    "Cornell", "Tsinghua University", "UC Berkeley", "University of Melbourne", "UNSW Sydney",
    "Yale", "EPFL", "TU Munich", "Johns Hopkins", "Princeton",
    "University of Sydney", "McGill", "Université Paris Sciences et Lettres", "University of Toronto", "Fudan University",
    "King's College London", "Australian National University", "Chinese University of Hong Kong", "University of Edinburgh", "University of Manchester",
    "Monash University", "University of Tokyo", "Columbia", "Seoul National University", "UBC",
    "Institut Polytechnique de Paris", "Northwestern", "University of Queensland", "HKUST", "University of Michigan",
    "UCLA", "Delft University of Technology", "Shanghai Jiao Tong University", "Zhejiang University", "Yonsei University",
    "University of Bristol", "Carnegie Mellon", "University of Amsterdam", "Hong Kong Polytechnic", "NYU",
    "LSE", "Kyoto University", "LMU Munich", "University of Malaya", "KU Leuven",
    "Korea University", "Duke", "City University of Hong Kong", "National Taiwan University", "University of Auckland",
    "UC San Diego", "KFUPM", "UT Austin", "Brown", "UIUC",
    "Université Paris-Saclay", "Lund University", "Sorbonne Université", "University of Warwick", "Trinity College Dublin",
    "University of Birmingham", "University of Western Australia", "KTH Royal Institute of Technology", "University of Glasgow", "Universität Heidelberg",
    "University of Washington", "Adelaide University", "Penn State", "Universidad de Buenos Aires", "Tokyo Institute of Technology",
    "University of Leeds", "University of Southampton", "Boston University", "Freie Universität Berlin", "Purdue",
    "Osaka University", "University of Sheffield", "Uppsala University", "Durham University", "University of Alberta",
    "University of Technology Sydney", "University of Nottingham", "KIT Karlsruhe", "Politecnico di Milano", "University of Zurich",
  ],
  values: [
    "100.0", "99.4", "98.9", "97.9", "97.7",
    "97.2", "96.7", "95.9", "95.8", "94.3",
    "94.2", "93.7", "93.0", "92.6", "92.5",
    "91.6", "91.2", "91.2", "90.8", "90.7",
    "90.4", "90.2", "90.2", "89.7", "89.4",
    "89.4", "88.9", "88.6", "88.5", "88.4",
    "88.3", "87.4", "87.4", "87.2", "86.4",
    "85.8", "85.8", "85.6", "85.6", "85.5",
    "85.4", "85.1", "85.1", "84.8", "84.7",
    "84.4", "84.3", "84.3", "84.0", "82.9",
    "82.5", "82.3", "81.5", "81.2", "81.1",
    "80.5", "80.2", "80.1", "80.1", "79.7",
    "79.6", "79.0", "78.9", "78.9", "77.5",
    "76.9", "76.5", "76.4", "76.2", "75.9",
    "75.9", "75.7", "75.7", "75.2", "73.9",
    "73.8", "73.7", "73.6", "73.4", "73.0",
    "72.7", "72.6", "72.6", "72.3", "72.1",
    "72.0", "71.2", "71.1", "71.1", "71.1",
    "71.0", "70.9", "70.3", "70.1", "70.1",
    "69.9", "69.4", "69.1", "69.1", "68.5",
  ],
};
