import type { GameList } from './types';
import { sportsTeamsByRevenueHints } from './hints';

export const sportsTeamsByRevenue: GameList = {
  id: 'sports-teams-by-revenue',
  name: 'Most Valuable Sports Franchises',
  description: 'Sports franchises ranked by total value (Sportico 2025)',
  topics: ['sports', 'money'],
  hints: sportsTeamsByRevenueHints,
  valueLabel: 'Valuation',
  items: [
    "Dallas Cowboys", "Los Angeles Rams", "New York Giants", "Golden State Warriors", "New England Patriots",
    "San Francisco 49ers", "Philadelphia Eagles", "New York Yankees", "New York Knicks", "Miami Dolphins",
    "New York Jets", "Los Angeles Lakers", "Las Vegas Raiders", "Los Angeles Dodgers", "Washington Commanders",
    "Chicago Bears", "Houston Texans", "Atlanta Falcons", "Seattle Seahawks", "Denver Broncos",
    "Real Madrid", "Kansas City Chiefs", "Pittsburgh Steelers", "Green Bay Packers", "Tampa Bay Buccaneers",
    "Minnesota Vikings", "Los Angeles Chargers", "Tennessee Titans", "Cleveland Browns", "Manchester United",
    "Boston Red Sox", "Baltimore Ravens", "Detroit Lions", "Buffalo Bills", "Carolina Panthers",
    "Indianapolis Colts", "FC Barcelona", "Brooklyn Nets", "Chicago Cubs", "Los Angeles Clippers",
    "Boston Celtics", "Arizona Cardinals", "New Orleans Saints", "Liverpool", "Jacksonville Jaguars",
    "Chicago Bulls", "Cincinnati Bengals", "Bayern Munich", "Manchester City", "Miami Heat",
    "Ferrari", "Houston Rockets", "Toronto Raptors", "Philadelphia 76ers", "Arsenal",
    "Dallas Mavericks", "Phoenix Suns", "Paris Saint-Germain", "San Francisco Giants", "Sacramento Kings",
    "Atlanta Hawks", "Denver Nuggets", "Washington Wizards", "Cleveland Cavaliers", "Mercedes",
    "Milwaukee Bucks", "San Antonio Spurs", "Indiana Pacers", "Atlanta Braves", "Tottenham Hotspur",
    "Utah Jazz", "Toronto Maple Leafs", "Portland Trail Blazers", "Chelsea", "Oklahoma City Thunder",
    "Red Bull Racing", "Orlando Magic", "Detroit Pistons", "Houston Astros", "Philadelphia Phillies",
    "Charlotte Hornets", "Minnesota Timberwolves", "New York Rangers", "New York Mets", "New Orleans Pelicans",
    "Memphis Grizzlies", "Montreal Canadiens", "St. Louis Cardinals", "Boston Bruins", "McLaren",
    "Los Angeles Angels", "Los Angeles Kings", "Texas Rangers", "Chicago Blackhawks", "Edmonton Oilers",
    "Toronto Blue Jays", "San Diego Padres", "Philadelphia Flyers", "Washington Nationals", "Aston Martin",
  ],
  values: [
    "$12.0B", "$9.0B", "$8.6B", "$8.5B", "$8.3B",
    "$8.2B", "$8.1B", "$7.6B", "$7.5B", "$7.1B",
    "$7.0B", "$7.0B", "$6.7B", "$6.6B", "$6.6B",
    "$6.5B", "$6.5B", "$6.4B", "$6.3B", "$6.3B",
    "$6.3B", "$6.2B", "$6.0B", "$5.9B", "$5.9B",
    "$5.8B", "$5.7B", "$5.6B", "$5.6B", "$5.5B",
    "$5.4B", "$5.4B", "$5.3B", "$5.2B", "$5.1B",
    "$5.1B", "$5.1B", "$5.0B", "$5.0B", "$4.9B",
    "$4.8B", "$4.7B", "$4.7B", "$4.6B", "$4.6B",
    "$4.5B", "$4.5B", "$4.4B", "$4.4B", "$4.3B",
    "$4.3B", "$4.2B", "$4.2B", "$4.1B", "$4.1B",
    "$4.0B", "$4.0B", "$3.9B", "$3.8B", "$3.8B",
    "$3.7B", "$3.7B", "$3.6B", "$3.6B", "$3.5B",
    "$3.5B", "$3.4B", "$3.4B", "$3.3B", "$3.3B",
    "$3.2B", "$3.1B", "$3.1B", "$3.1B", "$3.0B",
    "$3.0B", "$2.9B", "$2.9B", "$2.8B", "$2.8B",
    "$2.7B", "$2.7B", "$2.7B", "$2.6B", "$2.6B",
    "$2.5B", "$2.5B", "$2.5B", "$2.4B", "$2.4B",
    "$2.3B", "$2.3B", "$2.2B", "$2.2B", "$2.1B",
    "$2.1B", "$2.0B", "$2.0B", "$2.0B", "$1.9B",
  ],
};
