import type { GameList } from './types';
import { tallestBuildingsHints } from './hints/tallest-buildings';

export const tallestBuildings: GameList = {
  id: 'tallest-buildings',
  name: 'Tallest Buildings in the World',
  description: 'Buildings ranked by architectural height (Wikipedia / CTBUH)',
  topics: ['geography'],
  difficulty: 2,
  hints: tallestBuildingsHints,
  valueLabel: 'Height',
  newUntil: '2026-05-14',
  items: [
    "Burj Khalifa", "Merdeka 118", "Shanghai Tower", "Mecca Royal Clock Tower", "Ping An Finance Centre",
    "Lotte World Tower", "One World Trade Center", "Guangzhou CTF Finance Centre", "Tianjin CTF Finance Centre", "CITIC Tower",
    "Taipei 101", "Shanghai World Financial Center", "International Commerce Centre", "Wuhan Greenland Center", "Central Park Tower",
    "Lakhta Center", "Landmark 81", "International Land-Sea Center", "The Exchange 106", "Changsha IFS Tower 1",
    "Petronas Tower 1", "Petronas Tower 2", "Zifeng Tower", "Suzhou International Financial Center", "Wuhan Center",
    "Willis Tower", "KK100", "Guangzhou International Finance Center", "111 West 57th Street", "Shandong International Financial Center",
    "One Vanderbilt", "432 Park Avenue", "Marina 101", "Trump International Hotel and Tower", "270 Park Avenue",
    "Minying International Trade Center T2", "Jin Mao Tower", "Nanjing Financial City Phase II Plot C Tower 1", "Princess Tower", "Al Hamra Tower",
    "International Finance Centre", "Haeundae LCT The Sharp Landmark Tower", "Ningbo Central Plaza", "Guangxi China Resources Tower", "Guiyang International Financial Center T1",
    "Iconic Tower", "China Merchants Bank Global Headquarters Main Tower", "China Resources Tower", "23 Marina", "CITIC Plaza",
    "Citymark Centre", "Shum Yip Upperhills Tower 1", "30 Hudson Yards", "Public Investment Fund Tower", "Shun Hing Square",
    "Eton Place Dalian Tower 1", "Autograph Tower", "Logan Century Center 1", "Burj Mohammed bin Rashid", "Empire State Building",
    "Elite Residence", "Riverview Plaza", "Dabaihui Plaza", "Guangdong Business Center", "Central Plaza",
    "Federation Tower", "Hengfeng Guiyang Center Tower 1", "Dalian International Trade Center", "Shanghai International Trade Center Tower 1", "Kempinski The Boulevard Dubai",
    "Haitian Center Tower 2", "Golden Eagle Tiandi Tower A", "Bank of China Tower", "Bank of America Tower", "Ciel Dubai Marina",
    "St. Regis Chicago", "Almas Tower", "Ping An Finance Center Jinan", "Huiyun Center", "Hanking Center",
    "Greenland Group Suzhou Center", "City Tower 1", "Gevora Hotel", "Galaxy World Tower 1", "Galaxy World Tower 2",
    "Il Primo Tower", "JW Marriott Marquis Dubai Tower 1", "JW Marriott Marquis Dubai Tower 2", "Emirates Office Tower", "Raffles City Chongqing T3N",
    "Raffles City Chongqing T4N", "OKO South Tower", "CBRT Tower", "The Marina Torch", "SkyTower at Pinnacle One Yonge",
    "Forum 66 Tower 1", "The Pinnacle", "Xi'an Glory International Financial Center", "Spring City 66", "85 Sky Tower",
  ],
  values: [
    "828m", "678.9m", "632m", "601m", "599.1m",
    "554.5m", "541.3m", "530m", "530m", "527.7m",
    "508m", "492m", "484m", "475.6m", "472.4m",
    "462m", "461.2m", "458m", "453.6m", "452.1m",
    "451.9m", "451.9m", "450m", "450m", "443.1m",
    "442.1m", "441.8m", "438.6m", "435.3m", "428m",
    "427m", "425.7m", "425m", "423.2m", "423m",
    "422.6m", "420.5m", "416.6m", "413.4m", "412.6m",
    "412m", "411.6m", "409m", "402.7m", "401m",
    "393.8m", "393m", "392.5m", "392.4m", "390.2m",
    "388.3m", "388.1m", "387.1m", "385m", "384m",
    "383.2m", "382.9m", "381.3m", "381.2m", "381m",
    "380.5m", "376m", "375.6m", "375.5m", "373.9m",
    "373.7m", "373.5m", "370.2m", "370m", "370m",
    "368.9m", "368.1m", "367.4m", "365.8m", "365.5m",
    "362.9m", "360m", "360m", "359.2m", "358.9m",
    "358m", "358m", "356.3m", "356m", "356m",
    "356m", "355.4m", "355.4m", "354.6m", "354.5m",
    "354.5m", "354.2m", "352m", "352m", "351.4m",
    "350.6m", "350.3m", "350m", "349m", "348m",
  ],
  aliases: {
    "Petronas Towers": "Petronas Tower 1",
    "Petronas Twin Towers": "Petronas Tower 1",
    "Twin Towers KL": "Petronas Tower 1",
    "Sears Tower": "Willis Tower",
    "Abraj Al-Bait": "Mecca Royal Clock Tower",
    "Abraj Al Bait": "Mecca Royal Clock Tower",
    "Abraj Al-Bait Clock Tower": "Mecca Royal Clock Tower",
    "Clock Tower Mecca": "Mecca Royal Clock Tower",
    "Freedom Tower": "One World Trade Center",
    "1 WTC": "One World Trade Center",
    "Zhongguo Zun": "CITIC Tower",
    "China Zun": "CITIC Tower",
    "Steinway Tower": "111 West 57th Street",
    "Federation Tower East Tower": "Federation Tower",
    "Federation Tower East": "Federation Tower",
    "2 International Finance Centre": "International Finance Centre",
    "Two IFC": "International Finance Centre",
    "Two International Finance Centre": "International Finance Centre",
    "ICC Hong Kong": "International Commerce Centre",
    "ICC": "International Commerce Centre",
    "Tuntex Sky Tower": "85 Sky Tower",
    "85 Sky Tower Kaohsiung": "85 Sky Tower",
    "Goldin Finance 117": "Ping An Finance Centre",
    "Lakhta Centre": "Lakhta Center",
    "Lakhta Center II": "Lakhta Center",
    "Trump Tower Chicago": "Trump International Hotel and Tower",
    "OKO Tower": "OKO South Tower",
    "Torch Tower": "The Marina Torch",
    "Torch Dubai": "The Marina Torch",
    "Marina Torch": "The Marina Torch",
    "Pinnacle One Yonge": "SkyTower at Pinnacle One Yonge",
    "Empire State": "Empire State Building",
    "ESB": "Empire State Building",
    "Taipei Financial Center": "Taipei 101",
    "SWFC": "Shanghai World Financial Center",
    "JPMorgan Chase World Headquarters": "270 Park Avenue",
    "JPMorgan Chase HQ": "270 Park Avenue",
    "Raffles City Chongqing": "Raffles City Chongqing T3N",
    "JW Marriott Marquis Dubai": "JW Marriott Marquis Dubai Tower 1",
    "Ciel Tower": "Ciel Dubai Marina",
    "Ciel": "Ciel Dubai Marina",
    "PIF Tower": "Public Investment Fund Tower",
    "Shun Hing Tower": "Shun Hing Square",
    "Di Wang": "Shun Hing Square",
    "Willis Tower Chicago": "Willis Tower",
    "Princess Tower Dubai": "Princess Tower",
    "Almas Tower Dubai": "Almas Tower",
    "Lotte World Tower Seoul": "Lotte World Tower",
    "Central Plaza Hong Kong": "Central Plaza",
    "Al Hamra Tower Kuwait": "Al Hamra Tower",
    "The Torch Dubai": "The Marina Torch",
  },
};
