// UFC Fighter Career Statistics
// Source: UFCStats.com (data through early 2026)
// Includes fighters with 5+ UFC fights
// Fields: name, wins, losses, sigStrikes (sig strikes landed), takedowns (TDs landed), fights, finishes (KO/TKO + sub wins)

export interface UFCFighter {
  name: string;
  wins: number;
  losses: number;
  sigStrikes: number;
  takedowns: number;
  fights: number;
  finishes: number;
}

export const ufcFighters: UFCFighter[] = [
  // --- Top fighters / Hall of Famers / Champions ---
  { name: "Jon Jones", wins: 28, losses: 1, sigStrikes: 2220, takedowns: 140, fights: 30, finishes: 18 },
  { name: "Georges St-Pierre", wins: 26, losses: 2, sigStrikes: 1768, takedowns: 118, fights: 28, finishes: 12 },
  { name: "Anderson Silva", wins: 17, losses: 7, sigStrikes: 1345, takedowns: 27, fights: 24, finishes: 14 },
  { name: "Demetrious Johnson", wins: 15, losses: 4, sigStrikes: 1059, takedowns: 58, fights: 19, finishes: 7 },
  { name: "Khabib Nurmagomedov", wins: 13, losses: 0, sigStrikes: 734, takedowns: 59, fights: 13, finishes: 10 },
  { name: "Conor McGregor", wins: 10, losses: 4, sigStrikes: 1027, takedowns: 6, fights: 14, finishes: 9 },
  { name: "Max Holloway", wins: 25, losses: 7, sigStrikes: 4914, takedowns: 45, fights: 32, finishes: 12 },
  { name: "Charles Oliveira", wins: 22, losses: 11, sigStrikes: 1611, takedowns: 46, fights: 33, finishes: 21 },
  { name: "Islam Makhachev", wins: 17, losses: 1, sigStrikes: 821, takedowns: 80, fights: 18, finishes: 13 },
  { name: "Alexander Volkanovski", wins: 13, losses: 4, sigStrikes: 1612, takedowns: 51, fights: 17, finishes: 6 },
  { name: "Israel Adesanya", wins: 16, losses: 5, sigStrikes: 2120, takedowns: 4, fights: 21, finishes: 11 },
  { name: "Kamaru Usman", wins: 15, losses: 3, sigStrikes: 1555, takedowns: 68, fights: 18, finishes: 10 },
  { name: "Francis Ngannou", wins: 7, losses: 3, sigStrikes: 466, takedowns: 16, fights: 10, finishes: 7 },
  { name: "Stipe Miocic", wins: 14, losses: 4, sigStrikes: 1125, takedowns: 50, fights: 18, finishes: 9 },
  { name: "Henry Cejudo", wins: 10, losses: 2, sigStrikes: 623, takedowns: 48, fights: 12, finishes: 5 },
  { name: "Daniel Cormier", wins: 12, losses: 3, sigStrikes: 730, takedowns: 66, fights: 15, finishes: 9 },
  { name: "Dustin Poirier", wins: 22, losses: 7, sigStrikes: 2362, takedowns: 37, fights: 29, finishes: 15 },
  { name: "Justin Gaethje", wins: 16, losses: 4, sigStrikes: 1685, takedowns: 17, fights: 20, finishes: 10 },
  { name: "Tony Ferguson", wins: 16, losses: 8, sigStrikes: 2082, takedowns: 64, fights: 24, finishes: 12 },
  { name: "Nate Diaz", wins: 16, losses: 13, sigStrikes: 2021, takedowns: 18, fights: 29, finishes: 8 },
  { name: "Nick Diaz", wins: 5, losses: 6, sigStrikes: 498, takedowns: 11, fights: 11, finishes: 2 },
  { name: "BJ Penn", wins: 9, losses: 8, sigStrikes: 517, takedowns: 19, fights: 17, finishes: 8 },
  { name: "Donald Cerrone", wins: 23, losses: 13, sigStrikes: 2901, takedowns: 34, fights: 36, finishes: 16 },
  { name: "Frankie Edgar", wins: 18, losses: 10, sigStrikes: 1911, takedowns: 78, fights: 28, finishes: 4 },
  { name: "Jim Miller", wins: 24, losses: 9, sigStrikes: 1946, takedowns: 71, fights: 34, finishes: 16 },
  { name: "Neil Magny", wins: 24, losses: 10, sigStrikes: 2380, takedowns: 95, fights: 34, finishes: 9 },
  { name: "Andrei Arlovski", wins: 23, losses: 19, sigStrikes: 2228, takedowns: 16, fights: 42, finishes: 14 },
  { name: "Rafael dos Anjos", wins: 21, losses: 13, sigStrikes: 2083, takedowns: 114, fights: 34, finishes: 11 },
  { name: "Clay Guida", wins: 16, losses: 19, sigStrikes: 1788, takedowns: 92, fights: 35, finishes: 7 },
  { name: "Derrick Lewis", wins: 16, losses: 8, sigStrikes: 995, takedowns: 11, fights: 24, finishes: 14 },
  { name: "Ciryl Gane", wins: 12, losses: 3, sigStrikes: 833, takedowns: 18, fights: 15, finishes: 7 },
  { name: "Tom Aspinall", wins: 10, losses: 2, sigStrikes: 471, takedowns: 27, fights: 12, finishes: 9 },
  { name: "Valentina Shevchenko", wins: 14, losses: 4, sigStrikes: 1244, takedowns: 29, fights: 18, finishes: 7 },
  { name: "Amanda Nunes", wins: 14, losses: 4, sigStrikes: 1202, takedowns: 23, fights: 18, finishes: 12 },
  { name: "Zhang Weili", wins: 13, losses: 3, sigStrikes: 1177, takedowns: 35, fights: 16, finishes: 8 },
  { name: "Rose Namajunas", wins: 12, losses: 6, sigStrikes: 1048, takedowns: 23, fights: 18, finishes: 6 },
  { name: "Carla Esparza", wins: 10, losses: 6, sigStrikes: 548, takedowns: 42, fights: 16, finishes: 5 },
  { name: "Joanna Jedrzejczyk", wins: 9, losses: 5, sigStrikes: 1524, takedowns: 2, fights: 14, finishes: 6 },
  { name: "Tatiana Suarez", wins: 9, losses: 0, sigStrikes: 263, takedowns: 34, fights: 9, finishes: 5 },
  { name: "Alexa Grasso", wins: 12, losses: 3, sigStrikes: 904, takedowns: 24, fights: 15, finishes: 7 },
  { name: "Aljamain Sterling", wins: 14, losses: 5, sigStrikes: 983, takedowns: 73, fights: 19, finishes: 9 },
  { name: "Sean O'Malley", wins: 9, losses: 1, sigStrikes: 716, takedowns: 8, fights: 10, finishes: 6 },
  { name: "Merab Dvalishvili", wins: 15, losses: 4, sigStrikes: 982, takedowns: 131, fights: 19, finishes: 5 },
  { name: "Jose Aldo", wins: 14, losses: 8, sigStrikes: 1474, takedowns: 34, fights: 22, finishes: 7 },
  { name: "Brian Ortega", wins: 8, losses: 3, sigStrikes: 601, takedowns: 13, fights: 11, finishes: 7 },
  { name: "Calvin Kattar", wins: 8, losses: 7, sigStrikes: 1396, takedowns: 10, fights: 15, finishes: 4 },
  { name: "Zabit Magomedsharipov", wins: 6, losses: 1, sigStrikes: 371, takedowns: 20, fights: 7, finishes: 4 },
  { name: "Arnold Allen", wins: 10, losses: 2, sigStrikes: 743, takedowns: 31, fights: 12, finishes: 6 },
  { name: "Dan Hooker", wins: 11, losses: 11, sigStrikes: 1395, takedowns: 22, fights: 22, finishes: 8 },
  { name: "Giga Chikadze", wins: 8, losses: 3, sigStrikes: 620, takedowns: 4, fights: 11, finishes: 7 },
  { name: "Josh Emmett", wins: 12, losses: 5, sigStrikes: 823, takedowns: 29, fights: 17, finishes: 9 },
  { name: "Yair Rodriguez", wins: 8, losses: 4, sigStrikes: 750, takedowns: 16, fights: 12, finishes: 5 },
  { name: "Edson Barboza", wins: 14, losses: 12, sigStrikes: 2017, takedowns: 10, fights: 26, finishes: 12 },
  { name: "Dan Ige", wins: 11, losses: 8, sigStrikes: 897, takedowns: 19, fights: 19, finishes: 7 },
  // Lightweight division
  { name: "Arman Tsarukyan", wins: 11, losses: 3, sigStrikes: 1045, takedowns: 46, fights: 14, finishes: 7 },
  { name: "Beneil Dariush", wins: 13, losses: 5, sigStrikes: 836, takedowns: 47, fights: 18, finishes: 10 },
  { name: "Mateusz Gamrot", wins: 8, losses: 3, sigStrikes: 617, takedowns: 59, fights: 11, finishes: 5 },
  { name: "Renato Moicano", wins: 11, losses: 6, sigStrikes: 856, takedowns: 41, fights: 17, finishes: 7 },
  { name: "Michael Chandler", wins: 9, losses: 5, sigStrikes: 727, takedowns: 33, fights: 14, finishes: 7 },
  { name: "Bobby Green", wins: 10, losses: 9, sigStrikes: 1053, takedowns: 12, fights: 19, finishes: 5 },
  { name: "Drew Dober", wins: 9, losses: 7, sigStrikes: 806, takedowns: 17, fights: 16, finishes: 8 },
  { name: "Joe Lauzon", wins: 15, losses: 14, sigStrikes: 1088, takedowns: 59, fights: 29, finishes: 12 },
  { name: "Gray Maynard", wins: 5, losses: 5, sigStrikes: 415, takedowns: 34, fights: 10, finishes: 2 },
  { name: "Gleison Tibau", wins: 10, losses: 13, sigStrikes: 801, takedowns: 57, fights: 23, finishes: 3 },
  { name: "Melvin Guillard", wins: 9, losses: 9, sigStrikes: 664, takedowns: 11, fights: 18, finishes: 9 },
  { name: "Ross Pearson", wins: 7, losses: 10, sigStrikes: 779, takedowns: 11, fights: 17, finishes: 3 },
  { name: "Jacob Volkmann", wins: 5, losses: 5, sigStrikes: 231, takedowns: 27, fights: 10, finishes: 1 },
  { name: "Paul Felder", wins: 9, losses: 6, sigStrikes: 865, takedowns: 15, fights: 15, finishes: 5 },
  { name: "Al Iaquinta", wins: 8, losses: 6, sigStrikes: 776, takedowns: 23, fights: 14, finishes: 3 },
  { name: "Kevin Lee", wins: 7, losses: 8, sigStrikes: 669, takedowns: 45, fights: 15, finishes: 5 },
  // Welterweight
  { name: "Gilbert Burns", wins: 14, losses: 6, sigStrikes: 1051, takedowns: 35, fights: 20, finishes: 10 },
  { name: "Leon Edwards", wins: 13, losses: 3, sigStrikes: 1107, takedowns: 30, fights: 16, finishes: 7 },
  { name: "Colby Covington", wins: 12, losses: 4, sigStrikes: 1283, takedowns: 89, fights: 16, finishes: 4 },
  { name: "Belal Muhammad", wins: 14, losses: 3, sigStrikes: 1048, takedowns: 60, fights: 17, finishes: 7 },
  { name: "Sean Brady", wins: 9, losses: 1, sigStrikes: 627, takedowns: 49, fights: 10, finishes: 6 },
  { name: "Vicente Luque", wins: 14, losses: 7, sigStrikes: 1230, takedowns: 30, fights: 21, finishes: 12 },
  { name: "Ian Garry", wins: 8, losses: 0, sigStrikes: 515, takedowns: 11, fights: 8, finishes: 4 },
  { name: "Geoff Neal", wins: 9, losses: 5, sigStrikes: 713, takedowns: 19, fights: 14, finishes: 7 },
  { name: "Stephen Thompson", wins: 13, losses: 7, sigStrikes: 1447, takedowns: 1, fights: 20, finishes: 6 },
  { name: "Matt Brown", wins: 12, losses: 9, sigStrikes: 1256, takedowns: 14, fights: 21, finishes: 12 },
  { name: "Carlos Condit", wins: 9, losses: 9, sigStrikes: 1215, takedowns: 41, fights: 18, finishes: 8 },
  { name: "Jake Ellenberger", wins: 7, losses: 10, sigStrikes: 718, takedowns: 23, fights: 17, finishes: 5 },
  { name: "Robbie Lawler", wins: 16, losses: 13, sigStrikes: 1696, takedowns: 7, fights: 29, finishes: 14 },
  { name: "Josh Koscheck", wins: 10, losses: 9, sigStrikes: 701, takedowns: 57, fights: 19, finishes: 5 },
  { name: "Johny Hendricks", wins: 8, losses: 8, sigStrikes: 739, takedowns: 34, fights: 16, finishes: 8 },
  { name: "Tyron Woodley", wins: 9, losses: 6, sigStrikes: 757, takedowns: 30, fights: 15, finishes: 7 },
  { name: "Demian Maia", wins: 13, losses: 10, sigStrikes: 763, takedowns: 65, fights: 23, finishes: 8 },
  { name: "Thiago Alves", wins: 7, losses: 9, sigStrikes: 661, takedowns: 7, fights: 16, finishes: 6 },
  { name: "Mike Pierce", wins: 5, losses: 6, sigStrikes: 354, takedowns: 24, fights: 11, finishes: 1 },
  { name: "Gunnar Nelson", wins: 7, losses: 4, sigStrikes: 384, takedowns: 27, fights: 11, finishes: 7 },
  { name: "Mike Perry", wins: 8, losses: 7, sigStrikes: 737, takedowns: 8, fights: 15, finishes: 7 },
  { name: "Claudio Silva", wins: 5, losses: 2, sigStrikes: 143, takedowns: 19, fights: 7, finishes: 3 },
  { name: "Santiago Ponzinibbio", wins: 9, losses: 6, sigStrikes: 915, takedowns: 5, fights: 15, finishes: 9 },
  { name: "Kevin Holland", wins: 12, losses: 9, sigStrikes: 1302, takedowns: 27, fights: 21, finishes: 9 },
  { name: "Li Jingliang", wins: 8, losses: 7, sigStrikes: 756, takedowns: 8, fights: 15, finishes: 7 },
  { name: "Khamzat Chimaev", wins: 9, losses: 0, sigStrikes: 582, takedowns: 40, fights: 9, finishes: 6 },
  { name: "Shavkat Rakhmonov", wins: 9, losses: 0, sigStrikes: 547, takedowns: 22, fights: 9, finishes: 9 },
  // Middleweight
  { name: "Sean Strickland", wins: 16, losses: 6, sigStrikes: 1987, takedowns: 19, fights: 22, finishes: 6 },
  { name: "Dricus du Plessis", wins: 9, losses: 2, sigStrikes: 668, takedowns: 18, fights: 11, finishes: 7 },
  { name: "Robert Whittaker", wins: 15, losses: 6, sigStrikes: 1870, takedowns: 40, fights: 21, finishes: 8 },
  { name: "Paulo Costa", wins: 8, losses: 4, sigStrikes: 700, takedowns: 13, fights: 12, finishes: 6 },
  { name: "Marvin Vettori", wins: 10, losses: 6, sigStrikes: 930, takedowns: 32, fights: 16, finishes: 4 },
  { name: "Derek Brunson", wins: 12, losses: 11, sigStrikes: 1109, takedowns: 49, fights: 23, finishes: 8 },
  { name: "Kelvin Gastelum", wins: 10, losses: 9, sigStrikes: 887, takedowns: 29, fights: 19, finishes: 6 },
  { name: "Jared Cannonier", wins: 8, losses: 8, sigStrikes: 684, takedowns: 16, fights: 16, finishes: 6 },
  { name: "Chris Weidman", wins: 8, losses: 7, sigStrikes: 587, takedowns: 46, fights: 15, finishes: 7 },
  { name: "Yoel Romero", wins: 9, losses: 5, sigStrikes: 681, takedowns: 32, fights: 14, finishes: 8 },
  { name: "Luke Rockhold", wins: 7, losses: 5, sigStrikes: 574, takedowns: 28, fights: 12, finishes: 5 },
  { name: "Jacare Souza", wins: 11, losses: 7, sigStrikes: 772, takedowns: 45, fights: 18, finishes: 10 },
  { name: "Brad Tavares", wins: 10, losses: 7, sigStrikes: 952, takedowns: 18, fights: 17, finishes: 5 },
  { name: "Uriah Hall", wins: 10, losses: 9, sigStrikes: 903, takedowns: 12, fights: 19, finishes: 7 },
  { name: "Gegard Mousasi", wins: 8, losses: 4, sigStrikes: 534, takedowns: 26, fights: 12, finishes: 6 },
  { name: "Michael Bisping", wins: 20, losses: 9, sigStrikes: 1978, takedowns: 29, fights: 29, finishes: 9 },
  { name: "Vitor Belfort", wins: 12, losses: 12, sigStrikes: 622, takedowns: 12, fights: 24, finishes: 11 },
  { name: "Rich Franklin", wins: 11, losses: 7, sigStrikes: 756, takedowns: 6, fights: 18, finishes: 8 },
  { name: "Wanderlei Silva", wins: 11, losses: 9, sigStrikes: 737, takedowns: 7, fights: 20, finishes: 9 },
  { name: "Nate Marquardt", wins: 7, losses: 9, sigStrikes: 599, takedowns: 24, fights: 16, finishes: 5 },
  { name: "Alan Belcher", wins: 5, losses: 5, sigStrikes: 362, takedowns: 18, fights: 10, finishes: 4 },
  { name: "Tom Lawlor", wins: 5, losses: 7, sigStrikes: 367, takedowns: 16, fights: 12, finishes: 3 },
  { name: "Jorge Masvidal", wins: 13, losses: 9, sigStrikes: 1296, takedowns: 8, fights: 22, finishes: 9 },
  { name: "Darren Till", wins: 7, losses: 6, sigStrikes: 768, takedowns: 5, fights: 13, finishes: 5 },
  { name: "Brendan Allen", wins: 9, losses: 3, sigStrikes: 611, takedowns: 32, fights: 12, finishes: 7 },
  { name: "Joe Pyfer", wins: 6, losses: 2, sigStrikes: 355, takedowns: 11, fights: 8, finishes: 5 },
  // Light Heavyweight
  { name: "Jiri Prochazka", wins: 7, losses: 3, sigStrikes: 607, takedowns: 8, fights: 10, finishes: 5 },
  { name: "Jamahal Hill", wins: 7, losses: 2, sigStrikes: 548, takedowns: 9, fights: 9, finishes: 6 },
  { name: "Magomed Ankalaev", wins: 8, losses: 1, sigStrikes: 574, takedowns: 26, fights: 9, finishes: 4 },
  { name: "Carlos Ulberg", wins: 8, losses: 1, sigStrikes: 502, takedowns: 8, fights: 9, finishes: 6 },
  { name: "Alex Pereira", wins: 9, losses: 3, sigStrikes: 748, takedowns: 5, fights: 12, finishes: 9 },
  { name: "Aleksandar Rakic", wins: 8, losses: 3, sigStrikes: 582, takedowns: 22, fights: 11, finishes: 6 },
  { name: "Anthony Smith", wins: 12, losses: 8, sigStrikes: 837, takedowns: 22, fights: 20, finishes: 10 },
  { name: "Johnny Walker", wins: 7, losses: 6, sigStrikes: 487, takedowns: 13, fights: 13, finishes: 6 },
  { name: "Thiago Santos", wins: 7, losses: 7, sigStrikes: 718, takedowns: 4, fights: 14, finishes: 7 },
  { name: "Dominick Reyes", wins: 7, losses: 5, sigStrikes: 714, takedowns: 15, fights: 12, finishes: 5 },
  { name: "Ovince Saint Preux", wins: 9, losses: 12, sigStrikes: 1000, takedowns: 30, fights: 21, finishes: 7 },
  { name: "Nikita Krylov", wins: 11, losses: 8, sigStrikes: 869, takedowns: 23, fights: 19, finishes: 9 },
  { name: "Volkan Oezdemir", wins: 6, losses: 5, sigStrikes: 421, takedowns: 3, fights: 11, finishes: 5 },
  { name: "Jan Blachowicz", wins: 11, losses: 8, sigStrikes: 1004, takedowns: 30, fights: 19, finishes: 8 },
  { name: "Ryan Bader", wins: 10, losses: 5, sigStrikes: 655, takedowns: 42, fights: 15, finishes: 6 },
  { name: "Quinton Jackson", wins: 8, losses: 8, sigStrikes: 571, takedowns: 9, fights: 16, finishes: 7 },
  { name: "Rashad Evans", wins: 8, losses: 8, sigStrikes: 702, takedowns: 39, fights: 16, finishes: 6 },
  { name: "Lyoto Machida", wins: 13, losses: 9, sigStrikes: 899, takedowns: 41, fights: 22, finishes: 9 },
  { name: "Phil Davis", wins: 7, losses: 4, sigStrikes: 393, takedowns: 55, fights: 11, finishes: 4 },
  { name: "Glover Teixeira", wins: 12, losses: 7, sigStrikes: 899, takedowns: 36, fights: 19, finishes: 10 },
  { name: "Antonio Rogerio Nogueira", wins: 6, losses: 7, sigStrikes: 514, takedowns: 7, fights: 13, finishes: 4 },
  { name: "Chuck Liddell", wins: 8, losses: 6, sigStrikes: 547, takedowns: 15, fights: 14, finishes: 7 },
  { name: "Tito Ortiz", wins: 8, losses: 8, sigStrikes: 556, takedowns: 59, fights: 16, finishes: 6 },
  { name: "Forrest Griffin", wins: 7, losses: 6, sigStrikes: 643, takedowns: 32, fights: 13, finishes: 4 },
  { name: "Keith Jardine", wins: 5, losses: 8, sigStrikes: 460, takedowns: 7, fights: 13, finishes: 3 },
  { name: "Corey Anderson", wins: 6, losses: 5, sigStrikes: 458, takedowns: 33, fights: 11, finishes: 4 },
  { name: "Patrick Cummins", wins: 5, losses: 5, sigStrikes: 318, takedowns: 25, fights: 10, finishes: 2 },
  { name: "Misha Cirkunov", wins: 5, losses: 6, sigStrikes: 318, takedowns: 20, fights: 11, finishes: 5 },
  { name: "Shogun Rua", wins: 11, losses: 12, sigStrikes: 924, takedowns: 10, fights: 23, finishes: 10 },
  { name: "Ilir Latifi", wins: 5, losses: 6, sigStrikes: 360, takedowns: 26, fights: 11, finishes: 4 },
  // Heavyweight
  { name: "Sergei Pavlovich", wins: 8, losses: 3, sigStrikes: 314, takedowns: 1, fights: 11, finishes: 8 },
  { name: "Curtis Blaydes", wins: 12, losses: 5, sigStrikes: 660, takedowns: 90, fights: 17, finishes: 5 },
  { name: "Alexander Volkov", wins: 10, losses: 6, sigStrikes: 1016, takedowns: 10, fights: 16, finishes: 6 },
  { name: "Chris Daukaus", wins: 6, losses: 5, sigStrikes: 308, takedowns: 4, fights: 11, finishes: 5 },
  { name: "Tai Tuivasa", wins: 8, losses: 7, sigStrikes: 617, takedowns: 4, fights: 15, finishes: 8 },
  { name: "Jairzinho Rozenstruik", wins: 8, losses: 5, sigStrikes: 429, takedowns: 2, fights: 13, finishes: 7 },
  { name: "Junior dos Santos", wins: 11, losses: 7, sigStrikes: 904, takedowns: 14, fights: 18, finishes: 9 },
  { name: "Fabricio Werdum", wins: 10, losses: 7, sigStrikes: 662, takedowns: 12, fights: 17, finishes: 8 },
  { name: "Antonio Nogueira", wins: 8, losses: 7, sigStrikes: 524, takedowns: 16, fights: 15, finishes: 6 },
  { name: "Frank Mir", wins: 11, losses: 11, sigStrikes: 572, takedowns: 26, fights: 22, finishes: 9 },
  { name: "Alistair Overeem", wins: 10, losses: 8, sigStrikes: 869, takedowns: 8, fights: 18, finishes: 8 },
  { name: "Brock Lesnar", wins: 5, losses: 3, sigStrikes: 193, takedowns: 34, fights: 8, finishes: 4 },
  { name: "Cain Velasquez", wins: 7, losses: 3, sigStrikes: 521, takedowns: 56, fights: 10, finishes: 6 },
  { name: "Ben Rothwell", wins: 8, losses: 7, sigStrikes: 554, takedowns: 22, fights: 15, finishes: 6 },
  { name: "Walt Harris", wins: 7, losses: 8, sigStrikes: 506, takedowns: 9, fights: 15, finishes: 7 },
  { name: "Stefan Struve", wins: 8, losses: 8, sigStrikes: 541, takedowns: 12, fights: 16, finishes: 6 },
  { name: "Josh Barnett", wins: 9, losses: 5, sigStrikes: 467, takedowns: 24, fights: 14, finishes: 7 },
  { name: "Brendan Schaub", wins: 5, losses: 7, sigStrikes: 452, takedowns: 15, fights: 12, finishes: 3 },
  { name: "Roy Nelson", wins: 8, losses: 9, sigStrikes: 598, takedowns: 9, fights: 17, finishes: 7 },
  { name: "Travis Browne", wins: 8, losses: 8, sigStrikes: 589, takedowns: 20, fights: 16, finishes: 7 },
  { name: "Cheick Kongo", wins: 6, losses: 7, sigStrikes: 484, takedowns: 13, fights: 13, finishes: 2 },
  { name: "Mark Hunt", wins: 7, losses: 7, sigStrikes: 555, takedowns: 3, fights: 14, finishes: 7 },
  { name: "Mirko Cro Cop", wins: 5, losses: 5, sigStrikes: 274, takedowns: 4, fights: 10, finishes: 4 },
  { name: "Gabriel Gonzaga", wins: 5, losses: 9, sigStrikes: 458, takedowns: 12, fights: 14, finishes: 4 },
  { name: "Oleksiy Oliynyk", wins: 7, losses: 7, sigStrikes: 199, takedowns: 23, fights: 14, finishes: 7 },
  { name: "Aleksei Oleinik", wins: 8, losses: 8, sigStrikes: 255, takedowns: 26, fights: 16, finishes: 8 },
  { name: "Greg Hardy", wins: 5, losses: 5, sigStrikes: 323, takedowns: 4, fights: 10, finishes: 4 },
  // Bantamweight
  { name: "Petr Yan", wins: 10, losses: 5, sigStrikes: 947, takedowns: 31, fights: 15, finishes: 7 },
  { name: "Cory Sandhagen", wins: 10, losses: 5, sigStrikes: 941, takedowns: 14, fights: 15, finishes: 7 },
  { name: "Marlon Vera", wins: 12, losses: 8, sigStrikes: 1083, takedowns: 19, fights: 20, finishes: 7 },
  { name: "Song Yadong", wins: 9, losses: 5, sigStrikes: 717, takedowns: 18, fights: 14, finishes: 5 },
  { name: "Dominick Cruz", wins: 10, losses: 5, sigStrikes: 732, takedowns: 40, fights: 15, finishes: 3 },
  { name: "Urijah Faber", wins: 10, losses: 8, sigStrikes: 656, takedowns: 43, fights: 18, finishes: 7 },
  { name: "T.J. Dillashaw", wins: 9, losses: 5, sigStrikes: 818, takedowns: 46, fights: 14, finishes: 5 },
  { name: "Renan Barao", wins: 8, losses: 7, sigStrikes: 676, takedowns: 14, fights: 15, finishes: 5 },
  { name: "Bryan Caraway", wins: 5, losses: 5, sigStrikes: 280, takedowns: 35, fights: 10, finishes: 3 },
  { name: "Raphael Assuncao", wins: 8, losses: 7, sigStrikes: 775, takedowns: 16, fights: 15, finishes: 3 },
  { name: "John Dodson", wins: 8, losses: 9, sigStrikes: 729, takedowns: 11, fights: 17, finishes: 6 },
  { name: "Johnny Eduardo", wins: 5, losses: 7, sigStrikes: 361, takedowns: 20, fights: 12, finishes: 3 },
  { name: "Brad Pickett", wins: 6, losses: 9, sigStrikes: 610, takedowns: 11, fights: 15, finishes: 4 },
  { name: "Scott Jorgensen", wins: 5, losses: 8, sigStrikes: 400, takedowns: 20, fights: 13, finishes: 3 },
  { name: "Eddie Wineland", wins: 5, losses: 7, sigStrikes: 398, takedowns: 4, fights: 12, finishes: 3 },
  { name: "Jimmie Rivera", wins: 6, losses: 6, sigStrikes: 525, takedowns: 12, fights: 12, finishes: 2 },
  { name: "Rob Font", wins: 9, losses: 7, sigStrikes: 979, takedowns: 9, fights: 16, finishes: 5 },
  { name: "Ricky Simon", wins: 9, losses: 3, sigStrikes: 592, takedowns: 44, fights: 12, finishes: 5 },
  { name: "Deiveson Figueiredo", wins: 13, losses: 5, sigStrikes: 756, takedowns: 13, fights: 18, finishes: 9 },
  { name: "Alex Caceres", wins: 14, losses: 13, sigStrikes: 1432, takedowns: 27, fights: 27, finishes: 5 },
  { name: "Nathaniel Wood", wins: 8, losses: 4, sigStrikes: 651, takedowns: 22, fights: 12, finishes: 5 },
  { name: "Brian Kelleher", wins: 8, losses: 7, sigStrikes: 648, takedowns: 15, fights: 15, finishes: 7 },
  // Flyweight
  { name: "Brandon Moreno", wins: 10, losses: 5, sigStrikes: 855, takedowns: 30, fights: 15, finishes: 6 },
  { name: "Kai Kara-France", wins: 8, losses: 5, sigStrikes: 640, takedowns: 14, fights: 13, finishes: 6 },
  { name: "Brandon Royval", wins: 8, losses: 5, sigStrikes: 593, takedowns: 28, fights: 13, finishes: 7 },
  { name: "Manel Kape", wins: 7, losses: 4, sigStrikes: 596, takedowns: 8, fights: 11, finishes: 6 },
  { name: "Alexandre Pantoja", wins: 10, losses: 3, sigStrikes: 738, takedowns: 33, fights: 13, finishes: 7 },
  { name: "Tim Elliott", wins: 8, losses: 10, sigStrikes: 781, takedowns: 38, fights: 18, finishes: 5 },
  { name: "Eric Shelton", wins: 5, losses: 5, sigStrikes: 228, takedowns: 11, fights: 10, finishes: 2 },
  { name: "Dustin Ortiz", wins: 5, losses: 7, sigStrikes: 369, takedowns: 18, fights: 12, finishes: 1 },
  { name: "Wilson Reis", wins: 5, losses: 8, sigStrikes: 365, takedowns: 24, fights: 13, finishes: 3 },
  { name: "Joseph Benavidez", wins: 12, losses: 7, sigStrikes: 891, takedowns: 48, fights: 19, finishes: 8 },
  { name: "John Moraga", wins: 5, losses: 7, sigStrikes: 448, takedowns: 20, fights: 12, finishes: 3 },
  { name: "Ray Borg", wins: 5, losses: 6, sigStrikes: 387, takedowns: 27, fights: 11, finishes: 3 },
  { name: "Matheus Nicolau", wins: 8, losses: 4, sigStrikes: 578, takedowns: 18, fights: 12, finishes: 3 },
  { name: "Amir Albazi", wins: 8, losses: 2, sigStrikes: 454, takedowns: 26, fights: 10, finishes: 5 },
  // Women's Strawweight
  { name: "Yan Xiaonan", wins: 8, losses: 4, sigStrikes: 779, takedowns: 13, fights: 12, finishes: 3 },
  { name: "Mackenzie Dern", wins: 7, losses: 5, sigStrikes: 423, takedowns: 23, fights: 12, finishes: 6 },
  { name: "Claudia Gadelha", wins: 7, losses: 6, sigStrikes: 738, takedowns: 43, fights: 13, finishes: 3 },
  { name: "Jessica Andrade", wins: 13, losses: 9, sigStrikes: 1160, takedowns: 41, fights: 22, finishes: 10 },
  { name: "Karolina Kowalkiewicz", wins: 7, losses: 8, sigStrikes: 874, takedowns: 17, fights: 15, finishes: 2 },
  { name: "Liz Carmouche", wins: 8, losses: 8, sigStrikes: 636, takedowns: 27, fights: 16, finishes: 5 },
  { name: "Tecia Torres", wins: 6, losses: 5, sigStrikes: 593, takedowns: 7, fights: 11, finishes: 1 },
  { name: "Jessica Penne", wins: 5, losses: 5, sigStrikes: 383, takedowns: 26, fights: 10, finishes: 4 },
  { name: "Angela Hill", wins: 10, losses: 13, sigStrikes: 1346, takedowns: 11, fights: 23, finishes: 2 },
  { name: "Nina Nunes", wins: 5, losses: 5, sigStrikes: 319, takedowns: 16, fights: 10, finishes: 3 },
  { name: "Virna Jandiroba", wins: 8, losses: 4, sigStrikes: 494, takedowns: 24, fights: 12, finishes: 5 },
  { name: "Amanda Lemos", wins: 8, losses: 3, sigStrikes: 541, takedowns: 5, fights: 11, finishes: 6 },
  { name: "Loopy Godinez", wins: 6, losses: 4, sigStrikes: 416, takedowns: 6, fights: 10, finishes: 3 },
  // Women's Flyweight / Bantamweight
  { name: "Aspen Ladd", wins: 5, losses: 5, sigStrikes: 401, takedowns: 18, fights: 10, finishes: 4 },
  { name: "Raquel Pennington", wins: 9, losses: 9, sigStrikes: 927, takedowns: 17, fights: 18, finishes: 3 },
  { name: "Holly Holm", wins: 9, losses: 8, sigStrikes: 822, takedowns: 15, fights: 17, finishes: 4 },
  { name: "Miesha Tate", wins: 7, losses: 5, sigStrikes: 574, takedowns: 29, fights: 12, finishes: 4 },
  { name: "Cat Zingano", wins: 5, losses: 8, sigStrikes: 554, takedowns: 16, fights: 13, finishes: 4 },
  { name: "Sara McMann", wins: 7, losses: 6, sigStrikes: 374, takedowns: 35, fights: 13, finishes: 4 },
  { name: "Marion Reneau", wins: 5, losses: 7, sigStrikes: 479, takedowns: 6, fights: 12, finishes: 4 },
  { name: "Irene Aldana", wins: 8, losses: 6, sigStrikes: 633, takedowns: 10, fights: 14, finishes: 6 },
  { name: "Ketlen Vieira", wins: 8, losses: 5, sigStrikes: 581, takedowns: 17, fights: 13, finishes: 4 },
  { name: "Yana Kunitskaya", wins: 8, losses: 7, sigStrikes: 614, takedowns: 22, fights: 15, finishes: 4 },
  { name: "Germaine de Randamie", wins: 6, losses: 5, sigStrikes: 579, takedowns: 9, fights: 11, finishes: 3 },
  { name: "Julianna Pena", wins: 7, losses: 5, sigStrikes: 538, takedowns: 16, fights: 12, finishes: 5 },
  { name: "Kayla Harrison", wins: 7, losses: 1, sigStrikes: 347, takedowns: 28, fights: 8, finishes: 4 },
  { name: "Norma Dumont", wins: 6, losses: 4, sigStrikes: 490, takedowns: 5, fights: 10, finishes: 2 },
  // Notable veterans and more
  { name: "Randy Couture", wins: 9, losses: 7, sigStrikes: 600, takedowns: 68, fights: 16, finishes: 6 },
  { name: "Matt Hughes", wins: 10, losses: 7, sigStrikes: 473, takedowns: 74, fights: 17, finishes: 7 },
  { name: "Ken Shamrock", wins: 5, losses: 7, sigStrikes: 174, takedowns: 26, fights: 12, finishes: 3 },
  { name: "Mark Coleman", wins: 6, losses: 7, sigStrikes: 198, takedowns: 49, fights: 13, finishes: 4 },
  { name: "Sean Sherk", wins: 5, losses: 5, sigStrikes: 424, takedowns: 47, fights: 10, finishes: 2 },
  { name: "Evan Dunham", wins: 8, losses: 10, sigStrikes: 748, takedowns: 47, fights: 18, finishes: 3 },
  { name: "Spencer Fischer", wins: 5, losses: 6, sigStrikes: 498, takedowns: 8, fights: 11, finishes: 3 },
  { name: "Thiago Tavares", wins: 5, losses: 6, sigStrikes: 350, takedowns: 22, fights: 11, finishes: 4 },
  { name: "Matt Wiman", wins: 5, losses: 7, sigStrikes: 385, takedowns: 15, fights: 12, finishes: 4 },
  { name: "George Sotiropoulos", wins: 5, losses: 4, sigStrikes: 282, takedowns: 24, fights: 9, finishes: 5 },
  { name: "Takanori Gomi", wins: 6, losses: 11, sigStrikes: 640, takedowns: 4, fights: 17, finishes: 6 },
  { name: "Caol Uno", wins: 5, losses: 11, sigStrikes: 318, takedowns: 25, fights: 16, finishes: 2 },
  { name: "Sam Stout", wins: 7, losses: 9, sigStrikes: 838, takedowns: 5, fights: 16, finishes: 3 },
  { name: "Marcus Davis", wins: 5, losses: 7, sigStrikes: 432, takedowns: 7, fights: 12, finishes: 4 },
  { name: "Dennis Siver", wins: 7, losses: 9, sigStrikes: 732, takedowns: 23, fights: 16, finishes: 5 },
  { name: "Mac Danzig", wins: 5, losses: 8, sigStrikes: 425, takedowns: 14, fights: 13, finishes: 4 },
  { name: "Jeremy Stephens", wins: 11, losses: 18, sigStrikes: 1516, takedowns: 14, fights: 29, finishes: 9 },
  { name: "Cub Swanson", wins: 10, losses: 11, sigStrikes: 1214, takedowns: 9, fights: 21, finishes: 8 },
  { name: "Hatsu Hioki", wins: 5, losses: 5, sigStrikes: 306, takedowns: 14, fights: 10, finishes: 2 },
  { name: "Manny Gamburyan", wins: 5, losses: 8, sigStrikes: 323, takedowns: 18, fights: 13, finishes: 3 },
  { name: "Will Brooks", wins: 5, losses: 5, sigStrikes: 344, takedowns: 28, fights: 10, finishes: 3 },
  { name: "Reza Madadi", wins: 5, losses: 3, sigStrikes: 215, takedowns: 21, fights: 8, finishes: 3 },
  { name: "Terry Etim", wins: 5, losses: 5, sigStrikes: 430, takedowns: 17, fights: 10, finishes: 4 },
  { name: "Abel Trujillo", wins: 5, losses: 9, sigStrikes: 584, takedowns: 24, fights: 14, finishes: 3 },
  { name: "John Makdessi", wins: 7, losses: 9, sigStrikes: 671, takedowns: 2, fights: 16, finishes: 4 },
  { name: "Michael Chiesa", wins: 8, losses: 7, sigStrikes: 583, takedowns: 44, fights: 15, finishes: 4 },
  { name: "Sage Northcutt", wins: 5, losses: 3, sigStrikes: 232, takedowns: 10, fights: 8, finishes: 4 },
  { name: "Ryan Hall", wins: 5, losses: 3, sigStrikes: 111, takedowns: 13, fights: 8, finishes: 5 },
  { name: "Marc Diakiese", wins: 7, losses: 6, sigStrikes: 629, takedowns: 10, fights: 13, finishes: 5 },
  { name: "Nik Lentz", wins: 8, losses: 9, sigStrikes: 602, takedowns: 48, fights: 17, finishes: 3 },
  { name: "Leandro Silva", wins: 5, losses: 4, sigStrikes: 198, takedowns: 28, fights: 9, finishes: 3 },
  { name: "Jason High", wins: 5, losses: 6, sigStrikes: 345, takedowns: 13, fights: 11, finishes: 3 },
  { name: "Chris Gruetzemacher", wins: 5, losses: 5, sigStrikes: 358, takedowns: 11, fights: 10, finishes: 3 },
  { name: "Rustam Khabilov", wins: 6, losses: 5, sigStrikes: 480, takedowns: 28, fights: 11, finishes: 5 },
  { name: "Tony Martin", wins: 8, losses: 7, sigStrikes: 672, takedowns: 26, fights: 15, finishes: 5 },
  { name: "Thiago Moises", wins: 7, losses: 6, sigStrikes: 576, takedowns: 24, fights: 13, finishes: 5 },
  { name: "Gregor Gillespie", wins: 7, losses: 2, sigStrikes: 358, takedowns: 38, fights: 9, finishes: 6 },
  { name: "Lando Vannata", wins: 5, losses: 7, sigStrikes: 566, takedowns: 5, fights: 12, finishes: 4 },
  { name: "Alex da Silva", wins: 5, losses: 4, sigStrikes: 226, takedowns: 17, fights: 9, finishes: 3 },
  // More welterweights
  { name: "Ben Askren", wins: 5, losses: 3, sigStrikes: 131, takedowns: 32, fights: 8, finishes: 2 },
  { name: "Curtis Millender", wins: 5, losses: 5, sigStrikes: 393, takedowns: 11, fights: 10, finishes: 4 },
  { name: "Alex Morono", wins: 9, losses: 7, sigStrikes: 769, takedowns: 14, fights: 16, finishes: 5 },
  { name: "Niko Price", wins: 8, losses: 8, sigStrikes: 673, takedowns: 10, fights: 16, finishes: 7 },
  { name: "Max Griffin", wins: 7, losses: 7, sigStrikes: 620, takedowns: 13, fights: 14, finishes: 4 },
  { name: "Matthew Semelsberger", wins: 7, losses: 5, sigStrikes: 552, takedowns: 5, fights: 12, finishes: 6 },
  { name: "Pete Rodriguez", wins: 5, losses: 3, sigStrikes: 278, takedowns: 9, fights: 8, finishes: 4 },
  { name: "Danny Roberts", wins: 5, losses: 8, sigStrikes: 432, takedowns: 7, fights: 13, finishes: 4 },
  { name: "Dwight Grant", wins: 5, losses: 5, sigStrikes: 360, takedowns: 3, fights: 10, finishes: 4 },
  { name: "Court McGee", wins: 7, losses: 10, sigStrikes: 601, takedowns: 30, fights: 17, finishes: 3 },
  { name: "Magnus Cedenblad", wins: 5, losses: 4, sigStrikes: 317, takedowns: 17, fights: 9, finishes: 4 },
  { name: "Kyle Noke", wins: 5, losses: 5, sigStrikes: 301, takedowns: 16, fights: 10, finishes: 3 },
  { name: "Omari Akhmedov", wins: 7, losses: 7, sigStrikes: 640, takedowns: 23, fights: 14, finishes: 3 },
  { name: "Ryan Janes", wins: 5, losses: 4, sigStrikes: 284, takedowns: 22, fights: 9, finishes: 3 },
  { name: "Lyman Good", wins: 5, losses: 6, sigStrikes: 371, takedowns: 11, fights: 11, finishes: 3 },
  { name: "Patrick Cote", wins: 5, losses: 9, sigStrikes: 457, takedowns: 9, fights: 14, finishes: 3 },
  { name: "Dan Miller", wins: 5, losses: 7, sigStrikes: 396, takedowns: 12, fights: 12, finishes: 4 },
  { name: "Gerald Harris", wins: 5, losses: 4, sigStrikes: 236, takedowns: 14, fights: 9, finishes: 4 },
  { name: "Ronaldo Souza", wins: 11, losses: 7, sigStrikes: 772, takedowns: 45, fights: 18, finishes: 10 },
  { name: "Tim Boetsch", wins: 6, losses: 10, sigStrikes: 582, takedowns: 19, fights: 16, finishes: 4 },
  { name: "Lorenz Larkin", wins: 5, losses: 7, sigStrikes: 575, takedowns: 3, fights: 12, finishes: 4 },
  { name: "Benson Henderson", wins: 14, losses: 9, sigStrikes: 1469, takedowns: 75, fights: 23, finishes: 7 },
  { name: "Anthony Pettis", wins: 11, losses: 13, sigStrikes: 1217, takedowns: 26, fights: 24, finishes: 9 },
  { name: "Joe Duffy", wins: 5, losses: 3, sigStrikes: 304, takedowns: 9, fights: 8, finishes: 4 },
  { name: "Damir Hadzovic", wins: 5, losses: 5, sigStrikes: 386, takedowns: 7, fights: 10, finishes: 3 },
  { name: "Stevie Ray", wins: 6, losses: 5, sigStrikes: 451, takedowns: 14, fights: 11, finishes: 3 },
  { name: "Mairbek Taisumov", wins: 8, losses: 5, sigStrikes: 523, takedowns: 10, fights: 13, finishes: 7 },
  { name: "Joel Alvarez", wins: 7, losses: 4, sigStrikes: 444, takedowns: 11, fights: 11, finishes: 6 },
  { name: "Michael Trizano", wins: 5, losses: 5, sigStrikes: 350, takedowns: 7, fights: 10, finishes: 3 },
  { name: "Alan Patrick", wins: 7, losses: 6, sigStrikes: 540, takedowns: 21, fights: 13, finishes: 5 },
  { name: "Magomed Mustafaev", wins: 5, losses: 4, sigStrikes: 335, takedowns: 7, fights: 9, finishes: 5 },
  { name: "Drakkar Klose", wins: 7, losses: 5, sigStrikes: 556, takedowns: 22, fights: 12, finishes: 2 },
  { name: "Francisco Trinaldo", wins: 11, losses: 10, sigStrikes: 1023, takedowns: 14, fights: 21, finishes: 7 },
  { name: "Leonardo Santos", wins: 6, losses: 7, sigStrikes: 345, takedowns: 23, fights: 13, finishes: 4 },
  { name: "Ottman Azaitar", wins: 5, losses: 1, sigStrikes: 256, takedowns: 7, fights: 6, finishes: 5 },
  { name: "Grant Dawson", wins: 8, losses: 2, sigStrikes: 443, takedowns: 37, fights: 10, finishes: 5 },
  { name: "Ignacio Bahamondes", wins: 6, losses: 4, sigStrikes: 452, takedowns: 8, fights: 10, finishes: 5 },
  { name: "Khusein Askhabov", wins: 5, losses: 3, sigStrikes: 311, takedowns: 6, fights: 8, finishes: 3 },
  { name: "Rafa Garcia", wins: 6, losses: 3, sigStrikes: 404, takedowns: 24, fights: 9, finishes: 3 },
  { name: "Jalin Turner", wins: 8, losses: 5, sigStrikes: 554, takedowns: 9, fights: 13, finishes: 7 },
  { name: "Christos Giagos", wins: 7, losses: 9, sigStrikes: 608, takedowns: 28, fights: 16, finishes: 3 },
  { name: "Viacheslav Borshchev", wins: 5, losses: 4, sigStrikes: 351, takedowns: 2, fights: 9, finishes: 4 },
  { name: "Mike Davis", wins: 5, losses: 4, sigStrikes: 250, takedowns: 8, fights: 9, finishes: 4 },
  { name: "Jordan Leavitt", wins: 7, losses: 5, sigStrikes: 416, takedowns: 27, fights: 12, finishes: 4 },
  { name: "Nikolas Motta", wins: 5, losses: 5, sigStrikes: 374, takedowns: 10, fights: 10, finishes: 3 },
  // Additional middleweights / LHW
  { name: "Jack Hermansson", wins: 9, losses: 6, sigStrikes: 733, takedowns: 29, fights: 15, finishes: 6 },
  { name: "Edmen Shahbazyan", wins: 7, losses: 4, sigStrikes: 487, takedowns: 14, fights: 11, finishes: 6 },
  { name: "Nassourdine Imavov", wins: 8, losses: 4, sigStrikes: 665, takedowns: 15, fights: 12, finishes: 5 },
  { name: "Roman Dolidze", wins: 8, losses: 4, sigStrikes: 619, takedowns: 28, fights: 12, finishes: 6 },
  { name: "Chris Curtis", wins: 9, losses: 5, sigStrikes: 703, takedowns: 3, fights: 14, finishes: 5 },
  { name: "Phil Hawes", wins: 5, losses: 4, sigStrikes: 337, takedowns: 13, fights: 9, finishes: 4 },
  { name: "Bruno Silva", wins: 7, losses: 5, sigStrikes: 603, takedowns: 6, fights: 12, finishes: 5 },
  { name: "Wellington Turman", wins: 6, losses: 6, sigStrikes: 468, takedowns: 15, fights: 12, finishes: 4 },
  { name: "Dusko Todorovic", wins: 6, losses: 4, sigStrikes: 420, takedowns: 21, fights: 10, finishes: 4 },
  { name: "Abdul Razak Alhassan", wins: 5, losses: 5, sigStrikes: 264, takedowns: 4, fights: 10, finishes: 5 },
  { name: "Alessio Di Chirico", wins: 5, losses: 6, sigStrikes: 442, takedowns: 5, fights: 11, finishes: 4 },
  { name: "Eric Spicely", wins: 5, losses: 6, sigStrikes: 336, takedowns: 18, fights: 11, finishes: 3 },
  { name: "Makhmud Muradov", wins: 7, losses: 4, sigStrikes: 456, takedowns: 10, fights: 11, finishes: 6 },
  { name: "Tom Breese", wins: 5, losses: 5, sigStrikes: 349, takedowns: 7, fights: 10, finishes: 4 },
  { name: "Luan Chagas", wins: 6, losses: 4, sigStrikes: 382, takedowns: 22, fights: 10, finishes: 4 },
  { name: "Alen Amedovski", wins: 5, losses: 3, sigStrikes: 263, takedowns: 6, fights: 8, finishes: 4 },
  { name: "Eryk Anders", wins: 7, losses: 7, sigStrikes: 598, takedowns: 20, fights: 14, finishes: 5 },
  { name: "Julian Marquez", wins: 5, losses: 5, sigStrikes: 350, takedowns: 9, fights: 10, finishes: 4 },
  { name: "Gerald Meerschaert", wins: 10, losses: 10, sigStrikes: 545, takedowns: 25, fights: 20, finishes: 9 },
  { name: "Chidi Njokuani", wins: 6, losses: 7, sigStrikes: 520, takedowns: 3, fights: 13, finishes: 5 },
  { name: "Cezar Ferreira", wins: 5, losses: 8, sigStrikes: 427, takedowns: 14, fights: 13, finishes: 4 },
  { name: "Zubaira Tukhugov", wins: 5, losses: 5, sigStrikes: 370, takedowns: 11, fights: 10, finishes: 4 },
  // Additional heavyweights
  { name: "Shamil Gaziev", wins: 6, losses: 1, sigStrikes: 219, takedowns: 6, fights: 7, finishes: 6 },
  { name: "Marcos Rogerio de Lima", wins: 8, losses: 7, sigStrikes: 576, takedowns: 14, fights: 15, finishes: 6 },
  { name: "Martin Buday", wins: 5, losses: 4, sigStrikes: 267, takedowns: 9, fights: 9, finishes: 4 },
  { name: "Rodrigo Nascimento", wins: 6, losses: 3, sigStrikes: 246, takedowns: 17, fights: 9, finishes: 5 },
  { name: "Alexandr Romanov", wins: 9, losses: 2, sigStrikes: 342, takedowns: 22, fights: 11, finishes: 8 },
  { name: "Tanner Boser", wins: 7, losses: 8, sigStrikes: 567, takedowns: 13, fights: 15, finishes: 4 },
  { name: "Augusto Sakai", wins: 6, losses: 5, sigStrikes: 485, takedowns: 6, fights: 11, finishes: 4 },
  { name: "Alan Baudot", wins: 5, losses: 3, sigStrikes: 230, takedowns: 8, fights: 8, finishes: 4 },
  { name: "Harry Hunsucker", wins: 5, losses: 3, sigStrikes: 204, takedowns: 7, fights: 8, finishes: 4 },
  { name: "Blagoy Ivanov", wins: 7, losses: 5, sigStrikes: 467, takedowns: 22, fights: 12, finishes: 3 },
  { name: "Carlos Felipe", wins: 8, losses: 5, sigStrikes: 477, takedowns: 8, fights: 13, finishes: 6 },
  { name: "Justin Tafa", wins: 5, losses: 4, sigStrikes: 305, takedowns: 7, fights: 9, finishes: 5 },
  { name: "Jake Collier", wins: 5, losses: 7, sigStrikes: 352, takedowns: 11, fights: 12, finishes: 3 },
  { name: "Parker Porter", wins: 6, losses: 8, sigStrikes: 417, takedowns: 9, fights: 14, finishes: 3 },
  { name: "Chase Sherman", wins: 5, losses: 9, sigStrikes: 377, takedowns: 2, fights: 14, finishes: 3 },
  // More featherweights
  { name: "Movsar Evloev", wins: 8, losses: 0, sigStrikes: 456, takedowns: 31, fights: 8, finishes: 3 },
  { name: "Leandro Marques", wins: 5, losses: 3, sigStrikes: 267, takedowns: 12, fights: 8, finishes: 4 },
  { name: "Sodiq Yusuff", wins: 8, losses: 4, sigStrikes: 622, takedowns: 11, fights: 12, finishes: 5 },
  { name: "Julian Erosa", wins: 8, losses: 8, sigStrikes: 619, takedowns: 11, fights: 16, finishes: 7 },
  { name: "Billy Quarantillo", wins: 9, losses: 6, sigStrikes: 779, takedowns: 24, fights: 15, finishes: 5 },
  { name: "Bryce Mitchell", wins: 6, losses: 3, sigStrikes: 450, takedowns: 38, fights: 9, finishes: 3 },
  { name: "Damon Jackson", wins: 8, losses: 7, sigStrikes: 635, takedowns: 26, fights: 15, finishes: 5 },
  { name: "Pat Sabatini", wins: 8, losses: 5, sigStrikes: 589, takedowns: 42, fights: 13, finishes: 5 },
  { name: "Darrick Minner", wins: 5, losses: 7, sigStrikes: 343, takedowns: 8, fights: 12, finishes: 4 },
  { name: "Mike Grundy", wins: 5, losses: 5, sigStrikes: 330, takedowns: 22, fights: 10, finishes: 2 },
  { name: "Hakeem Dawodu", wins: 7, losses: 6, sigStrikes: 583, takedowns: 8, fights: 13, finishes: 4 },
  { name: "Lucas Almeida", wins: 5, losses: 4, sigStrikes: 329, takedowns: 9, fights: 9, finishes: 4 },
  { name: "Steven Peterson", wins: 6, losses: 8, sigStrikes: 570, takedowns: 12, fights: 14, finishes: 3 },
  { name: "Kyung Ho Kang", wins: 7, losses: 9, sigStrikes: 551, takedowns: 14, fights: 16, finishes: 5 },
  { name: "Danny Henry", wins: 5, losses: 5, sigStrikes: 346, takedowns: 11, fights: 10, finishes: 2 },
  // Women's featherweight / flyweight extras
  { name: "Felicia Spencer", wins: 6, losses: 7, sigStrikes: 534, takedowns: 16, fights: 13, finishes: 4 },
  { name: "Megan Anderson", wins: 6, losses: 4, sigStrikes: 407, takedowns: 7, fights: 10, finishes: 5 },
  { name: "Roxanne Modafferi", wins: 5, losses: 8, sigStrikes: 453, takedowns: 11, fights: 13, finishes: 2 },
  { name: "Lauren Murphy", wins: 6, losses: 6, sigStrikes: 494, takedowns: 11, fights: 12, finishes: 3 },
  { name: "Maycee Barber", wins: 7, losses: 5, sigStrikes: 634, takedowns: 13, fights: 12, finishes: 4 },
  { name: "Miranda Maverick", wins: 7, losses: 5, sigStrikes: 493, takedowns: 19, fights: 12, finishes: 3 },
  { name: "Manon Fiorot", wins: 8, losses: 1, sigStrikes: 569, takedowns: 19, fights: 9, finishes: 4 },
  { name: "Natalia Silva", wins: 7, losses: 4, sigStrikes: 470, takedowns: 8, fights: 11, finishes: 5 },
  { name: "Taila Santos", wins: 8, losses: 5, sigStrikes: 556, takedowns: 14, fights: 13, finishes: 3 },
  { name: "Jennifer Maia", wins: 8, losses: 8, sigStrikes: 599, takedowns: 9, fights: 16, finishes: 4 },
  { name: "Molly McCann", wins: 7, losses: 6, sigStrikes: 594, takedowns: 3, fights: 13, finishes: 4 },
  { name: "Cynthia Calvillo", wins: 7, losses: 5, sigStrikes: 540, takedowns: 28, fights: 12, finishes: 4 },
  { name: "Jessica Eye", wins: 5, losses: 9, sigStrikes: 636, takedowns: 8, fights: 14, finishes: 2 },
  { name: "Cortney Casey", wins: 5, losses: 9, sigStrikes: 552, takedowns: 7, fights: 14, finishes: 3 },
  { name: "Ariane Lipski", wins: 6, losses: 6, sigStrikes: 460, takedowns: 6, fights: 12, finishes: 5 },
  { name: "Andrea Lee", wins: 7, losses: 6, sigStrikes: 541, takedowns: 21, fights: 13, finishes: 4 },
  { name: "Casey O'Neill", wins: 8, losses: 2, sigStrikes: 474, takedowns: 22, fights: 10, finishes: 6 },
  { name: "Viviane Araujo", wins: 7, losses: 5, sigStrikes: 547, takedowns: 9, fights: 12, finishes: 3 },
  { name: "Shana Dobson", wins: 5, losses: 5, sigStrikes: 280, takedowns: 7, fights: 10, finishes: 2 },
  // Bantamweights extra
  { name: "Kyler Phillips", wins: 7, losses: 4, sigStrikes: 561, takedowns: 18, fights: 11, finishes: 4 },
  { name: "Victor Henry", wins: 6, losses: 5, sigStrikes: 443, takedowns: 9, fights: 11, finishes: 4 },
  { name: "Miles Johns", wins: 7, losses: 4, sigStrikes: 541, takedowns: 16, fights: 11, finishes: 5 },
  { name: "Adrian Yanez", wins: 7, losses: 4, sigStrikes: 552, takedowns: 5, fights: 11, finishes: 5 },
  { name: "Nora Cornolle", wins: 5, losses: 2, sigStrikes: 261, takedowns: 9, fights: 7, finishes: 3 },
  { name: "Mario Bautista", wins: 9, losses: 3, sigStrikes: 631, takedowns: 22, fights: 12, finishes: 5 },
  { name: "Cody Stamann", wins: 8, losses: 7, sigStrikes: 734, takedowns: 25, fights: 15, finishes: 3 },
  { name: "Vince Morales", wins: 5, losses: 5, sigStrikes: 368, takedowns: 3, fights: 10, finishes: 4 },
  { name: "Louis Smolka", wins: 7, losses: 9, sigStrikes: 642, takedowns: 15, fights: 16, finishes: 6 },
  { name: "Jonathan Martinez", wins: 9, losses: 6, sigStrikes: 775, takedowns: 10, fights: 15, finishes: 5 },
  { name: "Davey Grant", wins: 6, losses: 7, sigStrikes: 531, takedowns: 8, fights: 13, finishes: 4 },
  { name: "Hunter Azure", wins: 5, losses: 3, sigStrikes: 295, takedowns: 15, fights: 8, finishes: 2 },
  { name: "Montel Jackson", wins: 8, losses: 4, sigStrikes: 562, takedowns: 15, fights: 12, finishes: 5 },
  { name: "Raoni Barcelos", wins: 7, losses: 5, sigStrikes: 564, takedowns: 14, fights: 12, finishes: 4 },
  { name: "Andre Ewell", wins: 5, losses: 8, sigStrikes: 520, takedowns: 4, fights: 13, finishes: 3 },
  { name: "Rani Yahya", wins: 6, losses: 9, sigStrikes: 339, takedowns: 27, fights: 15, finishes: 5 },
  { name: "Albert Duraev", wins: 6, losses: 5, sigStrikes: 411, takedowns: 16, fights: 11, finishes: 5 },
  { name: "Tom Duquesnoy", wins: 5, losses: 4, sigStrikes: 342, takedowns: 5, fights: 9, finishes: 3 },
  { name: "Domingo Pilarte", wins: 5, losses: 3, sigStrikes: 302, takedowns: 8, fights: 8, finishes: 4 },
  { name: "Kris Moutinho", wins: 5, losses: 7, sigStrikes: 626, takedowns: 5, fights: 12, finishes: 2 },
  { name: "Josh Culibao", wins: 5, losses: 4, sigStrikes: 297, takedowns: 5, fights: 9, finishes: 4 },
  { name: "Ricardo Ramos", wins: 8, losses: 6, sigStrikes: 614, takedowns: 20, fights: 14, finishes: 5 },
  // Some additional notable fighters
  { name: "Paddy Pimblett", wins: 7, losses: 1, sigStrikes: 551, takedowns: 17, fights: 8, finishes: 6 },
  { name: "Dustin Jacoby", wins: 8, losses: 6, sigStrikes: 645, takedowns: 8, fights: 14, finishes: 5 },
  { name: "Da Un Jung", wins: 7, losses: 5, sigStrikes: 573, takedowns: 10, fights: 12, finishes: 5 },
  { name: "Ion Cutelaba", wins: 6, losses: 7, sigStrikes: 467, takedowns: 18, fights: 13, finishes: 5 },
  { name: "Paul Craig", wins: 7, losses: 7, sigStrikes: 449, takedowns: 8, fights: 14, finishes: 7 },
  { name: "Khalil Rountree", wins: 9, losses: 5, sigStrikes: 657, takedowns: 2, fights: 14, finishes: 8 },
  { name: "Ryan Spann", wins: 7, losses: 7, sigStrikes: 529, takedowns: 18, fights: 14, finishes: 6 },
  { name: "Jimmy Crute", wins: 7, losses: 5, sigStrikes: 455, takedowns: 17, fights: 12, finishes: 5 },
  { name: "Devin Clark", wins: 7, losses: 7, sigStrikes: 572, takedowns: 23, fights: 14, finishes: 3 },
  { name: "Tyson Pedro", wins: 6, losses: 5, sigStrikes: 406, takedowns: 12, fights: 11, finishes: 5 },
  { name: "Ike Villanueva", wins: 5, losses: 7, sigStrikes: 449, takedowns: 3, fights: 12, finishes: 4 },
  { name: "Saparbek Safarov", wins: 5, losses: 5, sigStrikes: 265, takedowns: 17, fights: 10, finishes: 3 },
  { name: "Josh Parisian", wins: 5, losses: 6, sigStrikes: 306, takedowns: 17, fights: 11, finishes: 4 },
  { name: "Bogdan Guskov", wins: 6, losses: 3, sigStrikes: 371, takedowns: 14, fights: 9, finishes: 4 },
  { name: "Anton Turkalj", wins: 5, losses: 3, sigStrikes: 315, takedowns: 15, fights: 8, finishes: 3 },
  { name: "Alonzo Menifield", wins: 7, losses: 5, sigStrikes: 499, takedowns: 7, fights: 12, finishes: 7 },
  { name: "Marcin Prachnio", wins: 5, losses: 7, sigStrikes: 428, takedowns: 7, fights: 12, finishes: 4 },
  { name: "Kennedy Nzechukwu", wins: 7, losses: 5, sigStrikes: 521, takedowns: 5, fights: 12, finishes: 6 },
  { name: "Fabio Cherant", wins: 5, losses: 3, sigStrikes: 273, takedowns: 8, fights: 8, finishes: 4 },
  { name: "Dovletdzhan Yagshimuradov", wins: 5, losses: 4, sigStrikes: 365, takedowns: 10, fights: 9, finishes: 3 },
  { name: "Jeremy Kennedy", wins: 6, losses: 5, sigStrikes: 416, takedowns: 20, fights: 11, finishes: 3 },
  { name: "Magomed Bibulatov", wins: 5, losses: 4, sigStrikes: 295, takedowns: 17, fights: 9, finishes: 3 },
  { name: "Bruno Gustavo da Silva", wins: 5, losses: 4, sigStrikes: 312, takedowns: 8, fights: 9, finishes: 4 },
  { name: "Sean Woodson", wins: 7, losses: 4, sigStrikes: 491, takedowns: 9, fights: 11, finishes: 4 },
  { name: "Charles Rosa", wins: 6, losses: 8, sigStrikes: 518, takedowns: 10, fights: 14, finishes: 4 },
  { name: "Nate Landwehr", wins: 7, losses: 6, sigStrikes: 628, takedowns: 5, fights: 13, finishes: 5 },
  { name: "TJ Brown", wins: 6, losses: 7, sigStrikes: 514, takedowns: 12, fights: 13, finishes: 3 },
  { name: "Tucker Lutz", wins: 7, losses: 4, sigStrikes: 519, takedowns: 9, fights: 11, finishes: 4 },
  { name: "Joe Solecki", wins: 7, losses: 5, sigStrikes: 341, takedowns: 29, fights: 12, finishes: 6 },
  { name: "Erick Gonzalez", wins: 5, losses: 4, sigStrikes: 287, takedowns: 8, fights: 9, finishes: 3 },
  { name: "Jared Gordon", wins: 9, losses: 9, sigStrikes: 899, takedowns: 16, fights: 18, finishes: 4 },
  { name: "Hayisaer Maheshate", wins: 5, losses: 3, sigStrikes: 310, takedowns: 10, fights: 8, finishes: 4 },
  { name: "Marc-Andre Barriault", wins: 8, losses: 7, sigStrikes: 666, takedowns: 10, fights: 15, finishes: 5 },
  { name: "Daniel Rodriguez", wins: 9, losses: 6, sigStrikes: 814, takedowns: 10, fights: 15, finishes: 5 },
  { name: "Takashi Sato", wins: 7, losses: 5, sigStrikes: 533, takedowns: 13, fights: 12, finishes: 6 },
  { name: "Muslim Salikhov", wins: 7, losses: 5, sigStrikes: 560, takedowns: 8, fights: 12, finishes: 6 },
  { name: "Dhiego Lima", wins: 6, losses: 7, sigStrikes: 527, takedowns: 17, fights: 13, finishes: 3 },
  { name: "Ramazan Emeev", wins: 7, losses: 5, sigStrikes: 459, takedowns: 29, fights: 12, finishes: 4 },
  { name: "Zelim Imadaev", wins: 5, losses: 4, sigStrikes: 334, takedowns: 3, fights: 9, finishes: 4 },
  { name: "Nasrat Haqparast", wins: 7, losses: 5, sigStrikes: 553, takedowns: 9, fights: 12, finishes: 5 },
  { name: "Mateusz Rebecki", wins: 7, losses: 3, sigStrikes: 491, takedowns: 11, fights: 10, finishes: 4 },
  { name: "Carlos Diego Ferreira", wins: 7, losses: 6, sigStrikes: 506, takedowns: 20, fights: 13, finishes: 6 },
  { name: "Terrance McKinney", wins: 7, losses: 5, sigStrikes: 422, takedowns: 9, fights: 12, finishes: 6 },
  { name: "Rafael Fiziev", wins: 7, losses: 4, sigStrikes: 666, takedowns: 3, fights: 11, finishes: 6 },
  { name: "Tiago Lemos", wins: 7, losses: 5, sigStrikes: 480, takedowns: 27, fights: 12, finishes: 5 },
  { name: "Mike Malott", wins: 6, losses: 1, sigStrikes: 374, takedowns: 18, fights: 7, finishes: 5 },
  { name: "Gabriel Bonfim", wins: 8, losses: 1, sigStrikes: 479, takedowns: 19, fights: 9, finishes: 7 },
  { name: "Rinat Fakhretdinov", wins: 8, losses: 3, sigStrikes: 576, takedowns: 28, fights: 11, finishes: 4 },
  { name: "Carlos Prates", wins: 8, losses: 3, sigStrikes: 573, takedowns: 5, fights: 11, finishes: 7 },
  { name: "Jack Della Maddalena", wins: 9, losses: 2, sigStrikes: 700, takedowns: 15, fights: 11, finishes: 8 },
  { name: "Joaquin Buckley", wins: 11, losses: 7, sigStrikes: 924, takedowns: 11, fights: 18, finishes: 9 },
  { name: "Josh Quinlan", wins: 5, losses: 1, sigStrikes: 283, takedowns: 5, fights: 6, finishes: 4 },
  { name: "Austen Lane", wins: 5, losses: 3, sigStrikes: 209, takedowns: 9, fights: 8, finishes: 4 },
  { name: "Ange Loosa", wins: 5, losses: 3, sigStrikes: 286, takedowns: 6, fights: 8, finishes: 3 },
  { name: "Trevin Giles", wins: 5, losses: 5, sigStrikes: 342, takedowns: 9, fights: 10, finishes: 3 },
  { name: "Mounir Lazzez", wins: 5, losses: 5, sigStrikes: 432, takedowns: 7, fights: 10, finishes: 3 },
  { name: "Yohan Lainesse", wins: 5, losses: 3, sigStrikes: 307, takedowns: 11, fights: 8, finishes: 4 },
  // Extra women's fighters
  { name: "Emily Ducote", wins: 5, losses: 5, sigStrikes: 393, takedowns: 11, fights: 10, finishes: 2 },
  { name: "Hannah Goldy", wins: 5, losses: 5, sigStrikes: 359, takedowns: 10, fights: 10, finishes: 2 },
  { name: "Josefine Knutsson", wins: 5, losses: 3, sigStrikes: 332, takedowns: 8, fights: 8, finishes: 3 },
  { name: "Istela Nunes", wins: 5, losses: 5, sigStrikes: 294, takedowns: 13, fights: 10, finishes: 3 },
  { name: "Piera Rodriguez", wins: 5, losses: 2, sigStrikes: 297, takedowns: 12, fights: 7, finishes: 3 },
  { name: "Gloria de Paula", wins: 5, losses: 5, sigStrikes: 376, takedowns: 5, fights: 10, finishes: 3 },
  { name: "Luana Pinheiro", wins: 7, losses: 4, sigStrikes: 524, takedowns: 15, fights: 11, finishes: 3 },
  { name: "Nadia Kassem", wins: 5, losses: 3, sigStrikes: 282, takedowns: 8, fights: 8, finishes: 2 },
  { name: "Maria Oliveira", wins: 5, losses: 4, sigStrikes: 316, takedowns: 11, fights: 9, finishes: 3 },
  { name: "Diana Belbita", wins: 5, losses: 6, sigStrikes: 436, takedowns: 4, fights: 11, finishes: 2 },
  // Strawweight men
  { name: "Rogerio Bontorin", wins: 6, losses: 7, sigStrikes: 489, takedowns: 13, fights: 13, finishes: 4 },
  { name: "Tagir Ulanbekov", wins: 6, losses: 3, sigStrikes: 320, takedowns: 23, fights: 9, finishes: 4 },
  { name: "Malcolm Gordon", wins: 5, losses: 5, sigStrikes: 328, takedowns: 11, fights: 10, finishes: 3 },
  { name: "Francisco Figueiredo", wins: 5, losses: 4, sigStrikes: 268, takedowns: 14, fights: 9, finishes: 4 },
  { name: "Tatsuro Taira", wins: 7, losses: 0, sigStrikes: 358, takedowns: 21, fights: 7, finishes: 4 },
  { name: "Victor Altamirano", wins: 7, losses: 3, sigStrikes: 447, takedowns: 9, fights: 10, finishes: 5 },
  { name: "Carlos Candelario", wins: 5, losses: 4, sigStrikes: 292, takedowns: 10, fights: 9, finishes: 3 },
  { name: "Ode Osbourne", wins: 6, losses: 6, sigStrikes: 438, takedowns: 4, fights: 12, finishes: 4 },
  { name: "Jeff Molina", wins: 5, losses: 4, sigStrikes: 327, takedowns: 9, fights: 9, finishes: 3 },
  { name: "Cody Gibson", wins: 5, losses: 5, sigStrikes: 283, takedowns: 11, fights: 10, finishes: 2 },
  { name: "Ilvies Luqman", wins: 5, losses: 3, sigStrikes: 295, takedowns: 8, fights: 8, finishes: 3 },
  { name: "Sumudaerji", wins: 5, losses: 5, sigStrikes: 354, takedowns: 12, fights: 10, finishes: 4 },
  { name: "Zhalgas Zhumagulov", wins: 6, losses: 6, sigStrikes: 402, takedowns: 11, fights: 12, finishes: 3 },
  { name: "Jake Hadley", wins: 5, losses: 4, sigStrikes: 311, takedowns: 11, fights: 9, finishes: 3 },
  { name: "Joshua Van", wins: 7, losses: 2, sigStrikes: 457, takedowns: 16, fights: 9, finishes: 5 },
  { name: "Steve Erceg", wins: 6, losses: 3, sigStrikes: 401, takedowns: 14, fights: 9, finishes: 3 },
  { name: "David Dvorak", wins: 6, losses: 5, sigStrikes: 432, takedowns: 11, fights: 11, finishes: 3 },
  // More bantamweight extras
  { name: "Said Nurmagomedov", wins: 9, losses: 4, sigStrikes: 597, takedowns: 12, fights: 13, finishes: 7 },
  { name: "Chris Gutierrez", wins: 8, losses: 5, sigStrikes: 636, takedowns: 7, fights: 13, finishes: 4 },
  { name: "Felipe Colares", wins: 5, losses: 4, sigStrikes: 296, takedowns: 9, fights: 9, finishes: 3 },
  { name: "Jack Shore", wins: 7, losses: 3, sigStrikes: 477, takedowns: 17, fights: 10, finishes: 4 },
  { name: "Marlon Moraes", wins: 7, losses: 10, sigStrikes: 806, takedowns: 18, fights: 17, finishes: 6 },
  { name: "Pedro Munhoz", wins: 6, losses: 9, sigStrikes: 668, takedowns: 14, fights: 15, finishes: 4 },
  { name: "Timur Valiev", wins: 8, losses: 4, sigStrikes: 548, takedowns: 16, fights: 12, finishes: 4 },
  { name: "Guido Cannetti", wins: 5, losses: 5, sigStrikes: 351, takedowns: 5, fights: 10, finishes: 3 },
  { name: "Luke Sanders", wins: 6, losses: 7, sigStrikes: 486, takedowns: 23, fights: 13, finishes: 5 },
  { name: "Manny Bermudez", wins: 6, losses: 5, sigStrikes: 289, takedowns: 27, fights: 11, finishes: 4 },
  { name: "Leandro Higo", wins: 5, losses: 6, sigStrikes: 406, takedowns: 7, fights: 11, finishes: 3 },
  { name: "Hiromasa Ougikubo", wins: 5, losses: 5, sigStrikes: 367, takedowns: 9, fights: 10, finishes: 2 },
];
