import type { GameList } from './types';
import { usCitiesCostOfLivingHints } from './hints';

export const usCitiesCostOfLiving: GameList = {
  id: 'us-cities-cost-of-living',
  name: 'US Cities by Cost of Living Index',
  description: 'US metro areas ranked by cost of living index, 100 = national average (C2ER)',
  topics: ['business', 'misc'],
  hints: usCitiesCostOfLivingHints,
  valueLabel: 'COL Index',
  items: [
    "Manhattan", "San Francisco", "Honolulu", "Brooklyn", "San Jose",
    "Orange County (CA)", "Washington DC", "Los Angeles", "Seattle", "Boston",
    "San Diego", "Stamford (CT)", "Queens (NY)", "Oakland", "Portland (OR)",
    "Denver", "Miami", "Sacramento", "Hartford", "Austin",
    "Chicago", "Minneapolis", "Philadelphia", "Raleigh", "Nashville",
    "Salt Lake City", "Baltimore", "Charlotte", "Tampa", "Dallas",
    "Atlanta", "Houston", "Las Vegas", "Phoenix", "Richmond (VA)",
    "Pittsburgh", "Orlando", "Columbus", "Jacksonville", "San Antonio",
    "Indianapolis", "Kansas City", "Tucson", "Reno", "Cincinnati",
    "St. Louis", "Milwaukee", "Albuquerque", "Des Moines", "Louisville",
    "Omaha", "Cleveland", "Boise", "Colorado Springs", "El Paso",
    "Knoxville", "Tulsa", "Little Rock", "Oklahoma City", "Memphis",
    "Birmingham", "Buffalo", "Wichita", "Fort Wayne", "Lexington",
    "Spokane", "Shreveport", "Lubbock", "Columbia (SC)", "Augusta",
    "McAllen", "Brownsville", "Corpus Christi", "Dayton", "Akron",
    "Toledo", "Youngstown", "Syracuse", "Rochester (NY)", "Provo",
    "Ogden", "Huntsville", "Chattanooga", "Jackson (MS)", "Fayetteville (AR)",
    "Cedar Rapids", "Sioux Falls", "Green Bay", "Peoria", "Springfield (MO)",
    "Topeka", "Amarillo", "Beaumont", "Tyler", "Abilene",
    "Harlingen", "Kalamazoo", "Decatur", "Jonesboro", "Danville",
  ],
  values: [
    "228", "180", "170", "172", "165",
    "160", "152", "150", "148", "147",
    "145", "142", "140", "138", "135",
    "130", "128", "125", "123", "120",
    "118", "115", "114", "112", "110",
    "108", "107", "105", "104", "103",
    "102", "101", "100", "100", "99",
    "98", "97", "96", "95", "94",
    "93", "92", "92", "91", "91",
    "90", "90", "89", "89", "88",
    "88", "87", "87", "86", "86",
    "85", "85", "84", "84", "83",
    "83", "82", "82", "81", "81",
    "80", "80", "79", "79", "78",
    "78", "77", "77", "76", "76",
    "75", "75", "74", "74", "73",
    "73", "72", "72", "71", "71",
    "70", "70", "69", "69", "68",
    "68", "67", "67", "66", "66",
    "65", "65", "64", "64", "63",
  ],
};
