import type { GameList } from './types';
import { usnewsCollegeRankingsHints } from './hints';

export const usnewsCollegeRankings: GameList = {
  id: 'usnews-college-rankings',
  name: 'US News College Rankings',
  description: 'US News & World Report Best National Universities (2025)',
  topics: ['education', 'usa'],
  hints: usnewsCollegeRankingsHints,
  valueLabel: 'Rank',
  items: [
    "MIT", "Stanford", "Harvard", "Caltech", "Duke",
    "Johns Hopkins", "UPenn", "Northwestern", "Yale", "Princeton",
    "Columbia", "University of Chicago", "Cornell", "UCLA", "UC Berkeley",
    "Rice", "Dartmouth", "Vanderbilt", "Notre Dame", "University of Michigan",
    "Georgetown", "Carnegie Mellon", "Emory", "University of Virginia", "Washington University in St. Louis",
    "USC", "University of Florida", "UNC Chapel Hill", "NYU", "Wake Forest",
    "Tufts", "UC Santa Barbara", "University of Rochester", "Boston College", "Georgia Tech",
    "UC Irvine", "UC San Diego", "University of Wisconsin-Madison", "University of Illinois Urbana-Champaign", "William & Mary",
    "Brandeis", "Case Western Reserve", "Boston University", "Northeastern", "Ohio State",
    "Purdue", "Tulane", "University of Georgia", "Villanova", "University of Texas at Austin",
    "University of Maryland", "Lehigh", "Pepperdine", "University of Pittsburgh", "Rutgers",
    "University of Washington", "University of Connecticut", "Rensselaer Polytechnic Institute", "Santa Clara University", "George Washington University",
    "Syracuse", "Texas A&M", "Penn State", "University of Minnesota", "Virginia Tech",
    "University of Miami", "University of Colorado Boulder", "Indiana University", "Michigan State", "Fordham",
    "Stevens Institute of Technology", "Baylor", "University of Iowa", "University of Delaware", "Clemson",
    "University of Massachusetts Amherst", "Colorado School of Mines", "Drexel", "Loyola Marymount", "Gonzaga",
    "University of Denver", "Marquette", "Howard", "SMU", "SUNY Stony Brook",
    "SUNY Binghamton", "University of Vermont", "Auburn", "University of South Carolina", "Temple",
    "University of Alabama", "University of Tennessee", "University of Kansas", "University of Oregon", "University of Nebraska",
    "Iowa State", "University of Oklahoma", "University of Kentucky", "Arizona State", "University of Utah",
  ],
  values: [
    "#1", "#2", "#3", "#4", "#5",
    "#6", "#7", "#8", "#9", "#10",
    "#11", "#12", "#13", "#14", "#15",
    "#16", "#17", "#18", "#19", "#20",
    "#21", "#22", "#23", "#24", "#25",
    "#26", "#27", "#28", "#29", "#30",
    "#31", "#32", "#33", "#34", "#35",
    "#36", "#37", "#38", "#39", "#40",
    "#41", "#42", "#43", "#44", "#45",
    "#46", "#47", "#48", "#49", "#50",
    "#51", "#52", "#53", "#54", "#55",
    "#56", "#57", "#58", "#59", "#60",
    "#61", "#62", "#63", "#64", "#65",
    "#66", "#67", "#68", "#69", "#70",
    "#71", "#72", "#73", "#74", "#75",
    "#76", "#77", "#78", "#79", "#80",
    "#81", "#82", "#83", "#84", "#85",
    "#86", "#87", "#88", "#89", "#90",
    "#91", "#92", "#93", "#94", "#95",
    "#96", "#97", "#98", "#99", "#100",
  ],
};
