import type { GameList } from './types';
import { usnewsCollegeRankingsHints } from './hints';

// Source: US News & World Report 2026 Best National Universities Rankings
// Published September 30, 2025
// Tied schools are placed in random order within their tie group.
export const usnewsCollegeRankings: GameList = {
  id: 'usnews-college-rankings',
  name: 'US News College Rankings',
  description: 'US News & World Report Best National Universities (2026)',
  topics: ['education', 'misc'],
  hints: usnewsCollegeRankingsHints,
  valueLabel: 'Rank',
  items: [
    "Princeton", "MIT", "Harvard", "Yale", "Stanford",
    "University of Chicago", "Johns Hopkins", "Northwestern", "Duke", "UPenn",
    "Caltech", "Cornell", "Brown", "Dartmouth", "UC Berkeley",
    "Columbia", "Vanderbilt", "UCLA", "Rice", "Washington University in St. Louis",
    "Carnegie Mellon", "University of Michigan", "Notre Dame", "Emory", "Georgetown",
    "UNC Chapel Hill", "University of Virginia", "USC", "UC San Diego", "University of Texas at Austin",
    "University of Florida", "NYU", "UC Davis", "Georgia Tech", "UC Irvine",
    "Tufts", "University of Illinois Urbana-Champaign", "University of Wisconsin-Madison", "Boston College", "UC Santa Barbara",
    "Ohio State", "Rutgers", "University of Maryland", "Boston University", "University of Washington",
    "Lehigh", "University of Rochester", "University of Georgia", "Purdue", "Northeastern",
    "Florida State", "Virginia Tech", "Texas A&M", "Wake Forest", "William & Mary",
    "Case Western Reserve", "Villanova", "UC Merced", "Penn State", "University of Minnesota",
    "SUNY Stony Brook", "Santa Clara University", "George Washington University", "Michigan State", "University of Massachusetts Amherst",
    "University of Miami", "NC State", "Rensselaer Polytechnic Institute", "University of Connecticut", "Brandeis",
    "University of Pittsburgh", "Tulane", "SUNY Binghamton", "Indiana University", "UC Riverside",
    "Clemson", "SUNY Buffalo", "Syracuse", "Rutgers Newark", "Colorado School of Mines",
    "New Jersey Institute of Technology", "Stevens Institute of Technology", "Drexel", "University of Illinois Chicago", "Yeshiva University",
    "Worcester Polytechnic Institute", "Pepperdine", "Marquette", "American University", "Baylor",
    "University of South Florida", "Rochester Institute of Technology", "SMU", "University of Delaware", "Howard",
    "UC Santa Cruz", "Fordham", "TCU", "Florida International University", "University of Colorado Boulder",
  ],
  values: [
    "#1", "#2", "#3", "#4", "#5",
    "#6", "#7", "#8", "#9", "#10",
    "#11", "#12", "#13", "#14", "#15",
    "#16", "#17", "#18", "#19", "#20",
    "#21", "#22", "#23", "#24", "#25",
    "#26", "#27", "#28", "#29", "#30",
    "#31", "#32", "#33", "#34", "#35",
    "#36", "#37", "#38", "#39", "#40",
    "#41", "#42", "#43", "#44", "#45",
    "#46", "#47", "#48", "#49", "#50",
    "#51", "#52", "#53", "#54", "#55",
    "#56", "#57", "#58", "#59", "#60",
    "#61", "#62", "#63", "#64", "#65",
    "#66", "#67", "#68", "#69", "#70",
    "#71", "#72", "#73", "#74", "#75",
    "#76", "#77", "#78", "#79", "#80",
    "#81", "#82", "#83", "#84", "#85",
    "#86", "#87", "#88", "#89", "#90",
    "#91", "#92", "#93", "#94", "#95",
    "#96", "#97", "#98", "#99", "#100",
  ],
};
