import type { Category } from './types';
import { countriesColdestHints } from './hints';

export const countriesColdest: Category = {
  id: 'countries-coldest',
  name: 'Countries by Average Temperature (Coldest)',
  description: 'Countries ranked by average annual temperature, coldest first',
  tags: ['geography', 'world'],
  hints: countriesColdestHints,
  valueLabel: 'Avg Temp',
  items: [
    "Canada", "Russia", "Mongolia", "Iceland", "Finland",
    "Norway", "Estonia", "Sweden", "Kyrgyzstan", "Latvia",
    "Denmark", "Lithuania", "Kazakhstan", "Belarus", "Tajikistan",
    "Czech Republic", "Poland", "Ireland", "United Kingdom", "Germany",
    "Belgium", "Luxembourg", "Netherlands", "Slovakia", "Austria",
    "Switzerland", "Ukraine", "North Korea", "New Zealand", "Chile",
    "Liechtenstein", "Andorra", "Slovenia", "Croatia", "Georgia",
    "Armenia", "Azerbaijan", "Moldova", "Romania", "Hungary",
    "France", "Serbia", "Bosnia", "Bulgaria", "South Korea",
    "Albania", "China", "Japan", "Italy", "United States",
    "Uzbekistan", "Turkmenistan", "North Macedonia", "Montenegro", "Kosovo",
    "Afghanistan", "Spain", "Greece", "Portugal", "Turkey",
    "Argentina", "Nepal", "Bhutan", "Lebanon", "Iran",
    "Uruguay", "Israel", "Jordan", "Lesotho", "South Africa",
    "Tunisia", "Australia", "Morocco", "Iraq", "Algeria",
    "Syria", "Libya", "Peru", "Mexico", "Egypt",
    "India", "Pakistan", "Saudi Arabia", "Botswana", "Namibia",
    "Brazil", "Ethiopia", "Oman", "Cuba", "Honduras",
    "Guatemala", "El Salvador", "Philippines", "Thailand", "Vietnam",
    "Nigeria", "Ghana", "Indonesia", "Colombia", "Singapore",
  ],
  values: [
    "-5.4°C", "-5.1°C", "-0.7°C", "1.0°C", "1.7°C",
    "1.5°C", "5.1°C", "2.1°C", "1.6°C", "5.9°C",
    "7.7°C", "6.1°C", "3.5°C", "5.9°C", "2.0°C",
    "7.5°C", "7.8°C", "9.3°C", "8.5°C", "8.5°C",
    "9.7°C", "8.7°C", "9.3°C", "8.5°C", "6.3°C",
    "5.5°C", "7.4°C", "6.2°C", "10.5°C", "8.5°C",
    "6.4°C", "7.6°C", "8.9°C", "10.7°C", "7.1°C",
    "7.2°C", "11.4°C", "8.3°C", "8.8°C", "10.3°C",
    "10.7°C", "10.4°C", "9.6°C", "10.4°C", "11.5°C",
    "11.4°C", "7.0°C", "11.2°C", "12.8°C", "8.6°C",
    "13.0°C", "15.5°C", "11.1°C", "10.6°C", "10.4°C",
    "12.6°C", "13.3°C", "15.5°C", "15.2°C", "11.1°C",
    "14.8°C", "8.1°C", "8.6°C", "15.4°C", "15.0°C",
    "17.5°C", "19.7°C", "18.3°C", "11.7°C", "17.7°C",
    "19.2°C", "21.7°C", "17.1°C", "21.9°C", "22.5°C",
    "18.9°C", "21.1°C", "19.5°C", "21.0°C", "22.1°C",
    "23.7°C", "20.2°C", "26.4°C", "20.2°C", "17.2°C",
    "24.7°C", "22.6°C", "25.6°C", "25.2°C", "23.9°C",
    "24.2°C", "24.8°C", "25.6°C", "26.3°C", "24.4°C",
    "26.8°C", "27.2°C", "25.7°C", "24.5°C", "27.0°C",
  ],
};
