import type { Category } from './types';
import { countriesByLiteracyRateHints } from './hints';

export const countriesByLiteracyRate: Category = {
  id: 'countries-by-literacy-rate',
  name: 'Countries by Literacy Rate (Lowest)',
  description: 'Countries ranked by adult literacy rate, lowest first (UNESCO)',
  tags: ['education', 'world'],
  hints: countriesByLiteracyRateHints,
  valueLabel: 'Literacy Rate',
  items: [
    "Chad", "Guinea", "South Sudan", "Afghanistan", "Mali",
    "Central African Republic", "Burkina Faso", "Niger", "Benin", "Sierra Leone",
    "Gambia", "Liberia", "Senegal", "Ethiopia", "Mozambique",
    "Mauritania", "Ivory Coast", "Guinea-Bissau", "Togo", "Comoros",
    "DR Congo", "Malawi", "Madagascar", "Nigeria", "Pakistan",
    "Haiti", "Nepal", "Papua New Guinea", "Bangladesh", "Morocco",
    "Burundi", "Rwanda", "India", "Cameroon", "Uganda",
    "Tanzania", "Zambia", "Ghana", "Timor-Leste", "Kenya",
    "Myanmar", "Laos", "Cambodia", "Egypt", "Guatemala",
    "Honduras", "Iraq", "Algeria", "Dominican Republic", "El Salvador",
    "Nicaragua", "Sudan", "Yemen", "Angola", "Zimbabwe",
    "Namibia", "South Africa", "Botswana", "Gabon", "Congo",
    "Eswatini", "Lesotho", "Bolivia", "Peru", "Brazil",
    "Mexico", "Colombia", "Ecuador", "Venezuela", "Jamaica",
    "Paraguay", "Turkey", "Tunisia", "Malaysia", "Indonesia",
    "Thailand", "China", "Vietnam", "Philippines", "Iran",
    "Saudi Arabia", "Jordan", "Lebanon", "Libya", "Palestine",
    "Fiji", "Tonga", "Samoa", "Maldives", "Sri Lanka",
    "Brunei", "Bahrain", "Qatar", "Kuwait", "United Arab Emirates",
    "Oman", "Trinidad & Tobago", "Costa Rica", "Chile", "Argentina",
  ],
  values: [
    "22%", "32%", "35%", "37%", "31%",
    "37%", "41%", "35%", "42%", "43%",
    "42%", "48%", "52%", "52%", "47%",
    "53%", "47%", "46%", "53%", "59%",
    "63%", "62%", "75%", "62%", "58%",
    "62%", "68%", "64%", "74%", "74%",
    "68%", "73%", "74%", "77%", "76%",
    "78%", "87%", "79%", "68%", "82%",
    "76%", "85%", "81%", "73%", "81%",
    "87%", "86%", "81%", "93%", "89%",
    "83%", "61%", "54%", "71%", "90%",
    "91%", "95%", "88%", "84%", "80%",
    "88%", "77%", "92%", "94%", "93%",
    "95%", "95%", "94%", "97%", "88%",
    "94%", "96%", "81%", "95%", "96%",
    "93%", "97%", "98%", "98%", "84%",
    "98%", "98%", "95%", "87%", "97%",
    "97%", "97%", "98%", "97%", "92%",
    "97%", "98%", "97%", "98%", "98%",
    "96%", "99%", "98%", "97%", "99%",
  ],
};
