import type { Category } from './types';
import { countriesOlympicMedalsHints } from './hints';

export const countriesOlympicMedals: Category = {
  id: 'countries-olympic-medals',
  name: 'Countries by All-Time Olympic Medals',
  description: 'Countries ranked by total Olympic medals (Summer + Winter, through 2024)',
  tags: ['sports', 'world'],
  hints: countriesOlympicMedalsHints,
  valueLabel: 'Total Medals',
  items: [
    "United States", "Soviet Union", "Great Britain", "Germany", "France",
    "Italy", "Sweden", "China", "Russia", "Australia",
    "Japan", "Hungary", "Norway", "South Korea", "Netherlands",
    "Canada", "Romania", "Cuba", "Finland", "Switzerland",
    "Brazil", "Poland", "Spain", "Denmark", "Kenya",
    "Belgium", "Austria", "New Zealand", "Jamaica", "Czech Republic",
    "Ukraine", "Turkey", "Ethiopia", "Argentina", "Greece",
    "South Africa", "Belarus", "Croatia", "Bulgaria", "Iran",
    "India", "North Korea", "Mexico", "Kazakhstan", "Georgia",
    "Bahamas", "Trinidad & Tobago", "Colombia", "Ireland", "Thailand",
    "Indonesia", "Egypt", "Slovakia", "Azerbaijan", "Uzbekistan",
    "Slovenia", "Portugal", "Serbia", "Taiwan", "Latvia",
    "Estonia", "Lithuania", "Morocco", "Nigeria", "Tunisia",
    "Philippines", "Uganda", "Dominican Republic", "Armenia", "Venezuela",
    "Pakistan", "Mongolia", "Puerto Rico", "Cameroon", "Fiji",
    "Kosovo", "Ecuador", "Grenada", "Bermuda", "Mozambique",
    "Zimbabwe", "Tajikistan", "Chile", "Algeria", "Ivory Coast",
    "Panama", "Kyrgyzstan", "Peru", "Suriname", "Israel",
    "Hong Kong", "Malaysia", "Vietnam", "Qatar", "Bahrain",
    "Singapore", "Moldova", "Turkmenistan", "Afghanistan", "Iceland",
  ],
  values: [
    "2,959", "1,204", "948", "892", "840",
    "742", "667", "697", "580", "596",
    "560", "529", "517", "337", "394",
    "385", "306", "241", "331", "323",
    "171", "312", "189", "209", "117",
    "182", "286", "135", "87", "104",
    "76", "102", "60", "79", "125",
    "37", "97", "44", "91", "77",
    "42", "56", "73", "75", "40",
    "14", "22", "36", "40", "39",
    "44", "35", "32", "18", "35",
    "29", "28", "26", "34", "15",
    "14", "15", "26", "27", "13",
    "15", "10", "12", "13", "15",
    "10", "9", "9", "7", "7",
    "5", "6", "3", "1", "2",
    "8", "4", "5", "11", "6",
    "3", "4", "3", "2", "8",
    "4", "5", "4", "3", "3",
    "6", "3", "1", "2", "5",
  ],
};
