import type { Category } from './types';
import { countriesByGdpHints } from './hints';

export const countriesByGdp: Category = {
  id: 'countries-by-gdp',
  name: 'Countries by GDP',
  description: 'Countries ranked by nominal GDP (IMF 2024 estimates)',
  tags: ['money', 'world'],
  hints: countriesByGdpHints,
  valueLabel: 'GDP',
  items: [
    "United States", "China", "Germany", "Japan", "India",
    "United Kingdom", "France", "Italy", "Brazil", "Canada",
    "Russia", "Mexico", "South Korea", "Australia", "Spain",
    "Indonesia", "Turkey", "Netherlands", "Saudi Arabia", "Switzerland",
    "Poland", "Taiwan", "Argentina", "Belgium", "Sweden",
    "Ireland", "Norway", "Thailand", "Israel", "Austria",
    "United Arab Emirates", "Singapore", "Nigeria", "Philippines", "Vietnam",
    "Bangladesh", "Malaysia", "Denmark", "Egypt", "South Africa",
    "Hong Kong", "Iran", "Colombia", "Romania", "Chile",
    "Czech Republic", "Pakistan", "Finland", "Peru", "Iraq",
    "Portugal", "New Zealand", "Kazakhstan", "Greece", "Algeria",
    "Qatar", "Hungary", "Kuwait", "Ethiopia", "Ukraine",
    "Morocco", "Ecuador", "Dominican Republic", "Cuba", "Kenya",
    "Guatemala", "Oman", "Bulgaria", "Uzbekistan", "Luxembourg",
    "Sri Lanka", "Croatia", "Ghana", "Costa Rica", "Ivory Coast",
    "Tanzania", "Belarus", "Lithuania", "Serbia", "Myanmar",
    "Panama", "DR Congo", "Uruguay", "Jordan", "Slovenia",
    "Azerbaijan", "Tunisia", "Cameroon", "Angola", "Bolivia",
    "Libya", "Bahrain", "Latvia", "Paraguay", "Nepal",
    "Uganda", "Estonia", "Cambodia", "El Salvador", "Honduras",
  ],
  values: [
    "$28.8T", "$18.5T", "$4.6T", "$4.2T", "$3.9T",
    "$3.5T", "$3.1T", "$2.3T", "$2.2T", "$2.1T",
    "$2.0T", "$1.8T", "$1.7T", "$1.7T", "$1.6T",
    "$1.4T", "$1.1T", "$1.1T", "$1.1T", "$905B",
    "$842B", "$790B", "$640B", "$632B", "$600B",
    "$545B", "$530B", "$520B", "$510B", "$508B",
    "$505B", "$497B", "$472B", "$440B", "$430B",
    "$420B", "$415B", "$405B", "$395B", "$380B",
    "$375B", "$367B", "$343B", "$340B", "$335B",
    "$330B", "$338B", "$305B", "$268B", "$265B",
    "$260B", "$255B", "$260B", "$248B", "$240B",
    "$235B", "$220B", "$165B", "$205B", "$178B",
    "$150B", "$118B", "$115B", "$107B", "$115B",
    "$102B", "$104B", "$95B", "$90B", "$85B",
    "$84B", "$82B", "$77B", "$71B", "$70B",
    "$68B", "$68B", "$73B", "$66B", "$63B",
    "$62B", "$60B", "$60B", "$58B", "$58B",
    "$56B", "$55B", "$52B", "$50B", "$48B",
    "$46B", "$44B", "$42B", "$40B", "$38B",
    "$36B", "$35B", "$32B", "$30B", "$28B",
  ],
};
