// All ~195 sovereign states — every country is a plausible guess
export const countriesOlympicMedalsHints: string[] = [
  "United States", "Soviet Union", "Great Britain", "Germany", "France",
  "Italy", "Sweden", "China", "Russia", "Australia",
  "Hungary", "Japan", "Finland", "Romania", "Canada",
  "Netherlands", "South Korea", "Poland", "Cuba", "Norway",
  "Switzerland", "Denmark", "Belgium", "Spain", "Brazil",
  "Czech Republic", "Ukraine", "New Zealand", "Kenya", "Ethiopia",
  "Jamaica", "Turkey", "Austria", "South Africa", "Bulgaria",
  "Argentina", "Greece", "Iran", "Mexico", "North Korea",
  "Croatia", "India", "Belarus", "Kazakhstan", "Georgia",
  "Azerbaijan", "Uzbekistan", "Thailand", "Slovakia", "Ireland",
  "Estonia", "Egypt", "Slovenia", "Serbia", "Lithuania",
  "Latvia", "Indonesia", "Colombia", "Portugal", "Trinidad and Tobago",
  "Tunisia", "Morocco", "Nigeria", "Taiwan", "Bahamas",
  "Dominican Republic", "Armenia", "Pakistan", "Mongolia", "Ecuador",
  "Uganda", "Venezuela", "Peru", "Cameroon", "Chile",
  "Tajikistan", "Algeria", "Philippines", "Mozambique", "Kyrgyzstan",
  "Fiji", "Bahrain", "Vietnam", "Kosovo", "Singapore",
  "Qatar", "Malaysia", "Grenada", "Jordan", "Ivory Coast",
  "Puerto Rico", "Guatemala", "Bermuda", "Suriname", "Panama",
  "Liechtenstein", "Botswana", "Moldova", "Kuwait", "Zambia",
  // Beyond top 100
  "Bangladesh", "DR Congo", "Tanzania", "Myanmar",
  "Sudan", "Afghanistan", "Saudi Arabia", "Angola", "Ghana",
  "Yemen", "Nepal", "Madagascar", "Niger", "Mali",
  "Sri Lanka", "Burkina Faso", "Malawi", "Syria",
  "Senegal", "Chad", "Somalia", "Zimbabwe", "Cambodia",
  "Guinea", "Rwanda", "Benin", "Burundi", "Bolivia",
  "South Sudan", "Haiti", "Honduras",
  "United Arab Emirates", "Papua New Guinea", "Israel",
  "Togo", "Sierra Leone", "Laos", "Paraguay", "Libya",
  "Nicaragua", "Turkmenistan",
  "Costa Rica", "Central African Republic", "Palestine",
  "Liberia", "Oman", "Mauritania",
  "Uruguay", "Bosnia and Herzegovina",
  "Albania", "Namibia", "Gambia",
  "Gabon", "Lesotho", "Guinea-Bissau", "North Macedonia",
  "Equatorial Guinea", "Timor-Leste",
  "Mauritius", "Eswatini", "Djibouti",
  "Cyprus", "Comoros", "Guyana", "Bhutan", "Solomon Islands",
  "Luxembourg", "Montenegro", "Cabo Verde", "Malta",
  "Brunei", "Belize", "Maldives", "Iceland",
  "Vanuatu", "Barbados", "São Tomé and Príncipe", "Samoa", "Saint Lucia",
  "Kiribati", "Tonga", "Micronesia", "Saint Vincent and the Grenadines",
  "Antigua and Barbuda", "Seychelles", "Andorra", "Dominica", "Marshall Islands",
  "Saint Kitts and Nevis", "Monaco", "San Marino", "Palau",
  "Tuvalu", "Nauru", "Vatican City",
];
