// ~400 directors people might guess for highest box office gross
export const directorsBoxOfficeHints: string[] = [
  // Top 100 (the actual answers)
  "Steven Spielberg", "Anthony Russo & Joe Russo", "Peter Jackson", "Michael Bay", "James Cameron",
  "David Yates", "Christopher Nolan", "Jon Favreau", "James Wan", "Joss Whedon",
  "Ridley Scott", "Tim Burton", "Ron Howard", "Robert Zemeckis", "Gore Verbinski",
  "Bryan Singer", "Zack Snyder", "Sam Raimi", "Taika Waititi", "Ryan Coogler",
  "Denis Villeneuve", "Jon Watts", "Chris Columbus", "Francis Lawrence", "Gary Ross",
  "Chloe Zhao", "Patty Jenkins", "Chad Stahelski", "Martin Scorsese", "Clint Eastwood",
  "George Lucas", "Roland Emmerich", "Brett Ratner", "Todd Phillips", "Matt Reeves",
  "Pete Docter", "Andrew Stanton", "Lee Unkrich", "Brad Bird", "Jennifer Lee",
  "Byron Howard", "Rich Moore", "Pierre Coffin", "Chris Renaud", "Kyle Balda",
  "Dean DeBlois", "Chris Sanders", "Carlos Saldanha", "Eric Darnell", "Tom McGrath",
  "Greta Gerwig", "Jordan Peele", "Quentin Tarantino", "M. Night Shyamalan", "Guy Ritchie",
  "Danny Boyle", "Wes Anderson", "Guillermo del Toro", "David Fincher", "Ang Lee",
  "J.J. Abrams", "Rian Johnson", "Alex Garland", "Paul Greengrass", "Doug Liman",
  "Antoine Fuqua", "Gareth Edwards", "Colin Trevorrow", "F. Gary Gray", "Adam McKay",
  "Tyler Perry", "Woody Allen", "Steven Soderbergh", "Scott Derrickson", "Justin Lin",
  "Alfonso Cuaron", "Alejandro G. Inarritu", "Barry Sonnenfeld", "Paul W.S. Anderson", "Shawn Levy",
  "Travis Knight", "Charlie Bean", "Mike Mitchell", "Kelly Asbury", "Vicky Jenson",
  "Andrew Adamson", "Conrad Vernon", "Mike Flanagan", "Damien Chazelle", "Bong Joon-ho",
  "Luc Besson", "Wolfgang Petersen", "Tony Scott", "Kathryn Bigelow", "Denis Villeneuve",
  "Spike Lee", "Joel Coen", "Paul Thomas Anderson", "Darren Aronofsky", "Sofia Coppola",
  // Beyond top 100 — famous auteurs, blockbuster directors, Oscar winners, international
  "Stanley Kubrick", "Alfred Hitchcock", "Francis Ford Coppola", "Akira Kurosawa", "Federico Fellini",
  "Ingmar Bergman", "Billy Wilder", "John Ford", "Howard Hawks", "Orson Welles",
  "David Lean", "John Huston", "William Wyler", "Cecil B. DeMille", "Frank Capra",
  "Victor Fleming", "Michael Curtiz", "Elia Kazan", "Robert Wise", "Fred Zinnemann",
  "Sidney Lumet", "Milos Forman", "Oliver Stone", "Sydney Pollack", "Norman Jewison",
  "Brian De Palma", "William Friedkin", "John Carpenter", "George Miller", "Terry Gilliam",
  "Terry Jones", "Richard Donner", "Joel Schumacher", "Barry Levinson", "Rob Reiner",
  "James L. Brooks", "Cameron Crowe", "Nancy Meyers", "Nora Ephron", "Penny Marshall",
  "Ivan Reitman", "Jason Reitman", "John Hughes", "Harold Ramis", "Judd Apatow",
  "Todd Haynes", "Richard Linklater", "Jim Jarmusch", "Spike Jonze", "Charlie Kaufman",
  "David Lynch", "Terrence Malick", "Lars von Trier", "Werner Herzog", "Michael Haneke",
  "Pedro Almodovar", "Hayao Miyazaki", "Wong Kar-wai", "Park Chan-wook", "Denis Villeneuve",
  "Coen Brothers", "Ethan Coen", "Noah Baumbach", "Mike Leigh", "Ken Loach",
  "Ridley Scott", "Tony Scott", "Wachowski Sisters", "Lana Wachowski", "Lilly Wachowski",
  "Christopher McQuarrie", "Edgar Wright", "Matthew Vaughn", "Kenneth Branagh", "Mel Gibson",
  "Ben Affleck", "Bradley Cooper", "Clint Eastwood", "Kevin Costner", "Warren Beatty",
  "Sean Penn", "Jodie Foster", "Barbra Streisand", "Robert Redford", "George Clooney",
  "Angelina Jolie", "Regina King", "Olivia Wilde", "Elizabeth Banks",
  "John Woo", "Ang Lee", "Zhang Yimou", "Chen Kaige", "Kar-Wai Wong",
  "Baz Luhrmann", "Peter Weir", "Phillip Noyce", "Neill Blomkamp", "Gavin Hood",
  "Alfonso Cuaron", "Guillermo del Toro", "Alejandro Gonzalez Inarritu", "Robert Rodriguez",
  "J.A. Bayona", "Juan Antonio Bayona", "Fede Alvarez", "Andy Muschietti",
  "James Gunn", "Taika Waititi", "Destin Daniel Cretton", "Cate Shortland",
  "Peyton Reed", "Anna Boden", "Ryan Fleck",
  "Ava DuVernay", "Barry Jenkins", "Steve McQueen", "Lee Daniels", "John Singleton",
  "Spike Lee", "F. Gary Gray", "Antoine Fuqua", "Ryan Coogler", "Jordan Peele",
  "Robert Eggers", "Ari Aster", "Ti West", "Mike Flanagan", "James Wan",
  "Leigh Whannell", "Scott Derrickson", "David Gordon Green",
  "Sam Mendes", "Joe Wright", "Tom Hooper", "Stephen Daldry", "Danny Boyle",
  "Mike Newell", "David Heyman", "Alfonso Cuaron", "Chris Columbus",
  "Rupert Wyatt", "Matt Reeves", "Gareth Edwards", "Colin Trevorrow",
  "Patty Jenkins", "Chloe Zhao", "Greta Gerwig",
  "Yorgos Lanthimos", "Celine Sciamma", "Julia Ducournau", "Justine Triet",
  "Sean Baker", "Celine Song", "Jonathan Glazer",
  "Christopher Guest", "Alexander Payne", "Jason Reitman", "Mike White",
  "Martin McDonagh", "Taika Waititi", "Adam McKay", "Todd Phillips",
  "Michael Mann", "Kathryn Bigelow", "Ridley Scott", "Tony Scott",
  "John McTiernan", "Paul Verhoeven", "James Cameron",
  "Renny Harlin", "Jan de Bont", "Simon West", "Tony Gilroy",
  "Phil Lord", "Christopher Miller", "Lord and Miller",
  "Lee Isaac Chung", "Chloe Zhao", "Denis Villeneuve",
  "Joe Johnston", "Gore Verbinski", "Jon Turteltaub",
  "Rob Marshall", "Bill Condon", "David Frankel",
  "Jay Roach", "Paul Feig", "Rawson Marshall Thurber",
  "Raja Gosnell", "Tim Hill", "Tom Shadyac",
  "Peter Farrelly", "Bobby Farrelly", "Adam Shankman",
  "Garry Marshall", "Chris Meledandri", "Illumination",
  "John Lasseter", "Josh Cooley", "Enrico Casarosa", "Domee Shi", "Dan Scanlon",
  "Mark Andrews", "Brenda Chapman", "Bob Peterson",
  "Rich Moore", "Don Hall", "Nathan Greno",
  "Kevin Lima", "Kirk DeMicco", "Chris Buck", "Jared Bush",
  "David Lowery", "Denis Villeneuve", "Christopher Nolan",
  "Steven Spielberg", "Martin Scorsese", "Francis Ford Coppola",
  "Sergio Leone", "Sam Peckinpah", "Walter Hill", "Don Siegel",
  "Robert Aldrich", "Nicholas Ray", "Douglas Sirk",
  "Roman Polanski", "Costa-Gavras", "Jean-Luc Godard", "Francois Truffaut",
  "Louis Malle", "Claude Chabrol", "Eric Rohmer", "Jacques Demy",
  "Vittorio De Sica", "Roberto Rossellini", "Luchino Visconti", "Bernardo Bertolucci",
  "Sergio Leone", "Dario Argento", "Giuseppe Tornatore",
  "Satyajit Ray", "S.S. Rajamouli", "Mani Ratnam",
  "Hirokazu Kore-eda", "Takeshi Kitano", "Mamoru Hosoda", "Makoto Shinkai", "Isao Takahata",
  "Ridley Scott", "Tony Scott", "Guy Ritchie", "Dexter Fletcher",
  "Matthew Vaughn", "Edgar Wright", "Danny Boyle", "Sam Mendes",
  "Steve McQueen", "Andrea Arnold", "Lynne Ramsay",
  "Denis Villeneuve", "Xavier Dolan", "Jean-Marc Vallee",
  "Ron Clements", "John Musker",
];
