export const highestGrossingTvShowsHints: string[] = [
  'The Simpsons', 'Friends', 'The Big Bang Theory', 'Seinfeld', 'Law & Order',
  'NCIS', "Grey's Anatomy", 'Game of Thrones', 'The Walking Dead', 'Frasier',
  'Everybody Loves Raymond', 'Two and a Half Men', 'The Office', 'Stranger Things', 'Modern Family',
  'House', 'CSI', 'ER', 'Desperate Housewives', 'How I Met Your Mother',
  'Family Guy', 'South Park', 'Cheers', 'M*A*S*H', '24',
  'Lost', 'Breaking Bad', 'The Sopranos', 'Mad Men', 'Succession',
  'Yellowstone', 'Supernatural', 'The Real Housewives', 'Survivor', 'American Idol',
  'Dancing with the Stars', 'The X-Files', 'Married with Children', 'Home Improvement', 'Roseanne',
  'Full House', 'Star Trek', 'Baywatch', 'Beverly Hills, 90210', 'Sex and the City',
  'Downton Abbey', 'The Crown', 'Ozark', 'Squid Game', 'Money Heist',
  'Narcos', 'Dexter', 'True Blood', 'Boardwalk Empire', 'Westworld',
  'Homeland', '30 Rock', 'Parks and Recreation', 'Arrested Development', "It's Always Sunny in Philadelphia",
  'The Wire', 'The Shield', 'Justified', 'Sons of Anarchy', 'Criminal Minds',
  'NCIS: Los Angeles', 'Hawaii Five-0', 'Blue Bloods', 'Chicago Fire', 'Bones',
  'Castle', 'Psych', 'Monk', 'Burn Notice', 'White Collar',
  'Suits', 'Shameless', 'Peaky Blinders', 'Cobra Kai', 'Bridgerton',
  'Emily in Paris', 'Virgin River', 'Outer Banks', 'Wednesday', 'The Witcher',
  'Umbrella Academy', 'Dark', 'Lupin', 'The Last of Us', 'House of the Dragon',
  'The Bear', 'Severance', 'Ted Lasso', 'Abbott Elementary', 'Only Murders in the Building',
  'The Mandalorian', 'Andor', 'The Boys', 'Invincible', 'Euphoria',
  // Additional plausible guesses
  'Wheel of Fortune', 'Jeopardy!', 'The Price Is Right', 'The Tonight Show', 'Saturday Night Live',
  'Late Night with David Letterman', 'The Late Show', 'Jimmy Kimmel Live', 'Conan', 'The Daily Show',
  '60 Minutes', 'Dateline NBC', '20/20', 'Primetime Live', 'Good Morning America',
  'Today Show', 'Morning Joe', 'Fox & Friends', 'Meet the Press', 'Face the Nation',
  'The Bachelor', 'The Bachelorette', 'Big Brother', 'Amazing Race', 'The Voice',
  "America's Got Talent", 'So You Think You Can Dance', 'Project Runway', 'Top Chef', 'MasterChef',
  "Hell's Kitchen", 'Kitchen Nightmares', 'Bar Rescue', 'Shark Tank', "Dragon's Den",
  'Undercover Boss', 'The Apprentice', 'Celebrity Apprentice', 'Trading Spaces', 'Flip or Flop',
  'The Young and the Restless', 'General Hospital', 'Days of Our Lives', 'The Bold and the Beautiful', 'All My Children',
  'Empire', 'Power', 'Scandal', 'How to Get Away with Murder', 'Quantico',
  'This Is Us', 'Parenthood', 'Brothers & Sisters', 'Ugly Betty',
  'Prison Break', 'Heroes', 'Alias', 'Fringe', 'Person of Interest',
  'Stargate SG-1', 'Battlestar Galactica', 'Dark Matter', 'Firefly', 'The Expanse',
  'Buffy the Vampire Slayer', 'Angel', 'Charmed', 'Sabrina the Teenage Witch', 'Smallville',
  'Arrow', 'The Flash', 'Supergirl', 'Legends of Tomorrow', 'Black Lightning',
];
