export const mlbCareerWarHints: string[] = [
  "Babe Ruth", "Walter Johnson", "Cy Young", "Barry Bonds", "Willie Mays",
  "Ty Cobb", "Henry Aaron", "Roger Clemens", "Tris Speaker", "Honus Wagner",
  "Stan Musial", "Rogers Hornsby", "Eddie Collins", "Ted Williams", "Grover Alexander",
  "Kid Nichols", "Alex Rodriguez", "Lou Gehrig", "Rickey Henderson", "Mel Ott",
  "Mickey Mantle", "Tom Seaver", "Nap Lajoie", "Christy Mathewson", "Frank Robinson",
  "Mike Schmidt", "Lefty Grove", "Greg Maddux", "Albert Pujols", "Randy Johnson",
  "Joe Morgan", "Warren Spahn", "Carl Yastrzemski", "Eddie Mathews", "Phil Niekro",
  "Cal Ripken Jr.", "Roberto Clemente", "Bert Blyleven", "Cap Anson", "Adrian Beltre",
  "Jimmie Foxx", "Al Kaline", "Eddie Plank", "Wade Boggs", "Steve Carlton",
  "Gaylord Perry", "Bob Gibson", "George Brett", "Mike Trout", "Tim Keefe",
  "Robin Roberts", "Chipper Jones", "Charlie Gehringer", "George Davis", "Roger Connor",
  "Fergie Jenkins", "Pedro Martinez", "Ken Griffey Jr.", "John Clarkson", "Mike Mussina",
  "Justin Verlander", "Nolan Ryan", "Rod Carew", "Clayton Kershaw", "Tom Glavine",
  "Jeff Bagwell", "Pete Rose", "Curt Schilling", "Joe DiMaggio", "Dan Brouthers",
  "Brooks Robinson", "Arky Vaughan", "Zack Greinke", "Robin Yount", "Luke Appling",
  "Ozzie Smith", "Bobby Wallace", "Jim McCormick", "Sam Crawford", "Paul Molitor",
  "Max Scherzer", "Old Hoss Radbourn", "Mookie Betts", "Johnny Bench", "Lou Whitaker",
  "Bill Dahlen", "Paul Waner", "Reggie Jackson", "Frank Thomas", "Pud Galvin",
  "Jim Thome", "Larry Walker", "Harry Heilmann", "Rafael Palmeiro", "Frankie Frisch",
  "Derek Jeter", "Bobby Grich", "Ted Lyons", "Alan Trammell", "Johnny Mize",
  // Additional plausible guesses
  "David Ortiz", "Ichiro Suzuki", "Mariano Rivera", "Craig Biggio", "Jeff Kent",
  "Gary Sheffield", "Andruw Jones", "Jim Edmonds", "Scott Rolen", "Bobby Abreu",
  "Todd Helton", "Lance Berkman", "Roy Halladay", "Johan Santana", "CC Sabathia",
  "Roy Oswalt", "Josh Beckett", "Jake Peavy", "Tim Hudson", "Andy Pettitte",
  "David Price", "Cole Hamels", "Zac Gallen", "Shane Bieber", "Corbin Burnes",
  "Jacob deGrom", "Gerrit Cole", "Aaron Nola", "Kevin Gausman", "Luis Castillo",
  "Mike Clevinger", "Chris Sale", "Madison Bumgarner", "Corey Kluber", "Dallas Keuchel",
  "Mike Piazza", "Ivan Rodriguez", "Carlton Fisk", "Gary Carter", "Yogi Berra",
  "Bill Dickey", "Mickey Cochrane", "Gabby Hartnett", "Ernie Banks", "Billy Williams",
  "Ferguson Jenkins", "Ron Santo", "Sammy Sosa", "Ryne Sandberg", "Mark Grace",
  "Joe Torre", "Eddie Murray", "Brooks Robinson", "Jim Palmer", "Frank Robinson",
  "Roberto Alomar", "Barry Larkin", "Dave Concepcion", "Eric Davis", "Ken Griffey Sr.",
  "Willie McCovey", "Orlando Cepeda", "Juan Marichal", "Gaylord Perry", "Willie Stargell",
  "Roberto Clemente", "Dave Parker", "Bill Mazeroski", "Dick Groat", "Bob Friend",
];
