export const mostVisitedCountriesHints: string[] = [
  "France", "Spain", "United States", "Italy", "Turkey",
  "Mexico", "United Kingdom", "Germany", "Japan", "Austria",
  "Saudi Arabia", "Portugal", "Malaysia", "Thailand", "China",
  "Hong Kong", "Netherlands", "Canada", "Poland", "Vietnam",
  "Morocco", "South Korea", "Macau", "Egypt", "Indonesia",
  "Romania", "Bulgaria", "Hungary", "Singapore", "Albania",
  "Czechia", "Kazakhstan", "Tunisia", "India", "Belgium",
  "Ireland", "South Africa", "Dominican Republic", "Uzbekistan", "Taiwan",
  "Sweden", "Brazil", "Cambodia", "Bahrain", "Argentina",
  "Norway", "Philippines", "Puerto Rico", "Australia", "Chile",
  "Colombia", "Jordan", "Qatar", "Georgia", "Denmark",
  "Switzerland", "Finland", "New Zealand", "Cuba", "Jamaica",
  "Iceland", "Cyprus", "Greece", "Croatia", "Israel",
  "Oman", "Azerbaijan", "Peru", "Kenya", "Sri Lanka",
  "Maldives", "Nepal", "Armenia", "Tanzania", "Ecuador",
  "Uruguay", "Costa Rica", "Bolivia", "Guatemala", "Panama",
  "El Salvador", "Honduras", "Nicaragua", "Paraguay", "Pakistan",
  "Bangladesh", "Uganda", "Zimbabwe", "Zambia", "Mauritius",
  "Ethiopia", "Myanmar", "Bhutan", "Seychelles", "Fiji",
  "Papua New Guinea", "Belize", "Namibia", "Laos", "Montenegro",
  // Beyond top 100
  "Russia", "Ukraine", "Belarus", "Moldova", "Slovakia",
  "Slovenia", "Serbia", "Bosnia and Herzegovina", "North Macedonia", "Kosovo",
  "Lithuania", "Latvia", "Estonia", "Luxembourg", "Malta",
  "Andorra", "Liechtenstein", "Monaco", "San Marino", "Vatican City",
  "Libya", "Algeria", "Sudan", "Somalia",
  "Nigeria", "Ghana", "Senegal", "Ivory Coast", "Cameroon",
  "DR Congo", "Angola", "Mozambique", "Madagascar", "Malawi",
  "Rwanda", "Burundi", "South Sudan", "Central African Republic", "Chad",
  "Mali", "Niger", "Burkina Faso", "Togo", "Benin",
  "Guinea", "Sierra Leone", "Liberia", "Gambia", "Guinea-Bissau",
  "Equatorial Guinea", "Gabon", "Congo", "São Tomé and Príncipe", "Comoros",
  "Djibouti", "Eritrea", "Lesotho", "Eswatini", "Botswana",
  "North Korea", "Mongolia", "Kyrgyzstan", "Tajikistan", "Turkmenistan",
  "Afghanistan", "Iraq", "Iran", "Syria", "Lebanon",
  "Yemen", "Bahamas", "Trinidad and Tobago", "Haiti",
  "Barbados", "Saint Lucia", "Grenada", "Antigua and Barbuda", "Dominica",
  "Saint Kitts and Nevis", "Saint Vincent and the Grenadines", "Tonga", "Samoa", "Vanuatu",
  "Solomon Islands", "Kiribati", "Marshall Islands", "Micronesia", "Palau",
  "Nauru", "Tuvalu", "Brunei", "Timor-Leste", "Cabo Verde",
];
