// ~500 movies people might guess for most Oscar nominations
export const oscarNominationsHints: string[] = [
  // Top 100 (the actual answers)
  "All About Eve", "Titanic", "La La Land", "Gone with the Wind", "The Shape of Water",
  "From Here to Eternity", "Mary Poppins", "Who's Afraid of Virginia Woolf?", "Forrest Gump", "Shakespeare in Love",
  "The Lord of the Rings: The Return of the King", "Ben-Hur", "Chicago", "Saving Private Ryan", "Mrs. Miniver",
  "On the Waterfront", "The King's Speech", "Lincoln", "Oppenheimer", "The Curious Case of Benjamin Button",
  "Schindler's List", "The English Patient", "Avatar", "Gangs of New York", "The Godfather",
  "Cabaret", "A Star Is Born (2018)", "The Irishman", "Dances with Wolves", "West Side Story (1961)",
  "Gandhi", "Hugo", "The Aviator", "Braveheart", "The Revenant",
  "American Hustle", "Gravity", "Bohemian Rhapsody", "Mad Max: Fury Road", "Million Dollar Baby",
  "Gladiator", "Rocky", "The Apartment", "Reds", "Terms of Endearment",
  "Rain Man", "A Beautiful Mind", "The Hurt Locker", "12 Years a Slave", "Birdman",
  "Spotlight", "Moonlight", "The Sound of Music", "Doctor Zhivago", "My Fair Lady",
  "Tootsie", "The Color Purple", "JFK", "Amadeus", "Out of Africa",
  "Kramer vs. Kramer", "One Flew Over the Cuckoo's Nest", "Annie Hall", "The Deer Hunter", "Platoon",
  "Silence of the Lambs", "Unforgiven", "No Country for Old Men", "The Departed", "American Beauty",
  "Chicago (2002)", "Slumdog Millionaire", "The Artist", "Argo", "Parasite",
  "Nomadland", "CODA", "Everything Everywhere All at Once", "The Godfather Part II", "Chinatown",
  "Network", "Jaws", "Star Wars", "E.T. the Extra-Terrestrial", "Raiders of the Lost Ark",
  "Goodfellas", "Pulp Fiction", "Fargo", "The Shawshank Redemption", "The Pianist",
  "Black Panther", "Joker", "1917", "Little Women (2019)", "Ford v Ferrari",
  "Mank", "Judas and the Black Messiah", "The Power of the Dog", "Dune", "Killers of the Flower Moon",
  // Beyond top 100 — Best Picture winners, famous nominees, and well-known films
  "Casablanca", "Lawrence of Arabia", "The Bridge on the River Kwai", "Patton", "The French Connection",
  "The Sting", "The Godfather Part III", "Ordinary People", "Chariots of Fire", "Driving Miss Daisy",
  "The Last Emperor", "Crash", "A Man for All Seasons", "Oliver!", "Midnight Cowboy",
  "The Deer Hunter", "In the Heat of the Night", "Tom Jones", "Around the World in 80 Days", "Gigi",
  "An American in Paris", "Marty", "The Greatest Show on Earth", "Gentleman's Agreement", "The Best Years of Our Lives",
  "How Green Was My Valley", "Rebecca", "You Can't Take It with You", "The Life of Emile Zola", "The Great Ziegfeld",
  "Mutiny on the Bounty", "It Happened One Night", "Cavalcade", "Grand Hotel", "Cimarron",
  "All Quiet on the Western Front", "Broadway Melody", "Wings", "No Country for Old Men", "Million Dollar Baby",
  "The Shape of Water", "Green Book", "Moonlight", "12 Years a Slave", "The Artist",
  "The Hurt Locker", "Slumdog Millionaire", "Chicago", "A Beautiful Mind", "Gladiator",
  "American Beauty", "Shakespeare in Love", "Braveheart", "Forrest Gump", "Schindler's List",
  "Unforgiven", "Dances with Wolves", "Driving Miss Daisy", "Rain Man", "The Last Emperor",
  "Platoon", "Out of Africa", "Amadeus", "Terms of Endearment", "Gandhi",
  "Ordinary People", "Kramer vs. Kramer", "The Deer Hunter", "Annie Hall", "Rocky",
  "One Flew Over the Cuckoo's Nest", "The Godfather Part II", "The Sting", "The French Connection", "Patton",
  "Midnight Cowboy", "Oliver!", "In the Heat of the Night", "A Man for All Seasons", "The Sound of Music",
  "My Fair Lady", "Tom Jones", "Lawrence of Arabia", "West Side Story", "Ben-Hur",
  "Gigi", "The Bridge on the River Kwai", "Around the World in 80 Days", "Marty", "On the Waterfront",
  "From Here to Eternity", "The Greatest Show on Earth", "An American in Paris", "All About Eve",
  "Barbie", "Oppenheimer", "The Fabelmans", "Women Talking", "Triangle of Sadness",
  "The Banshees of Inisherin", "Elvis", "Top Gun: Maverick", "All Quiet on the Western Front (2022)", "Tar",
  "West Side Story (2021)", "Belfast", "King Richard", "Licorice Pizza", "Don't Look Up",
  "Being the Ricardos", "Nightmare Alley", "The Tragedy of Macbeth", "Minari", "Promising Young Woman",
  "The Trial of the Chicago 7", "Sound of Metal", "The Father", "Ma Rainey's Black Bottom", "Mank",
  "Once Upon a Time in Hollywood", "Jojo Rabbit", "Marriage Story", "The Two Popes", "Bombshell",
  "Richard Jewell", "A Star Is Born", "BlacKkKlansman", "Vice", "Roma",
  "The Favourite", "Bohemian Rhapsody", "Can You Ever Forgive Me?", "First Reformed", "If Beale Street Could Talk",
  "Three Billboards Outside Ebbing Missouri", "Lady Bird", "Get Out", "Phantom Thread", "Dunkirk",
  "The Post", "Darkest Hour", "I Tonya", "Call Me by Your Name", "The Disaster Artist",
  "Manchester by the Sea", "Fences", "Hidden Figures", "Lion", "Hacksaw Ridge",
  "Arrival", "Hell or High Water", "Loving", "The Big Short", "Bridge of Spies",
  "Carol", "Room", "Brooklyn", "The Martian", "The Danish Girl",
  "Steve Jobs", "Joy", "Trumbo", "The Theory of Everything", "Boyhood",
  "The Grand Budapest Hotel", "Whiplash", "The Imitation Game", "Selma", "Foxcatcher",
  "Gone Girl", "Unbroken", "Into the Woods", "Interstellar", "Wild",
  "Her", "Gravity", "Captain Phillips", "Dallas Buyers Club", "The Wolf of Wall Street",
  "Nebraska", "Philomena", "Blue Jasmine", "August: Osage County", "Inside Llewyn Davis",
  "Life of Pi", "Les Miserables", "Beasts of the Southern Wild", "Amour", "Django Unchained",
  "Zero Dark Thirty", "Silver Linings Playbook", "Flight", "The Master",
  "The Tree of Life", "Moneyball", "The Help", "Extremely Loud & Incredibly Close",
  "The Descendants", "War Horse", "Midnight in Paris", "Hugo", "The Artist",
  "Inception", "The Social Network", "True Grit", "127 Hours", "Winter's Bone",
  "The Kids Are All Right", "Toy Story 3", "Black Swan", "The Fighter", "Blue Valentine",
  "Inglourious Basterds", "An Education", "Precious", "Up in the Air", "A Serious Man",
  "District 9", "The Blind Side", "Up", "Crazy Heart", "Star Trek",
  "Milk", "Frost/Nixon", "The Wrestler", "Doubt", "The Reader",
  "Revolutionary Road", "Benjamin Button", "Atonement", "Michael Clayton", "Juno",
  "There Will Be Blood", "Sweeney Todd", "The Diving Bell and the Butterfly",
  "Babel", "The Queen", "Blood Diamond", "Dreamgirls", "Letters from Iwo Jima",
  "The Last King of Scotland", "Little Miss Sunshine", "Notes on a Scandal", "Pan's Labyrinth",
  "Walk the Line", "Capote", "Good Night and Good Luck", "Syriana", "Munich",
  "Brokeback Mountain", "Memoirs of a Geisha", "The Constant Gardener", "Transamerica",
  "The Aviator", "Sideways", "Finding Neverland", "Ray", "Hotel Rwanda",
  "Vera Drake", "Kinsey", "Closer", "Eternal Sunshine of the Spotless Mind",
  "Mystic River", "Lost in Translation", "Master and Commander", "Seabiscuit",
  "Cold Mountain", "In America", "City of God", "Monster",
  "Gangs of New York", "The Hours", "The Pianist", "Adaptation", "Far from Heaven",
  "Chicago", "Frida", "The Quiet American", "Road to Perdition",
  "Moulin Rouge!", "A Beautiful Mind", "Gosford Park", "In the Bedroom", "Monster's Ball",
  "Training Day", "Black Hawk Down", "The Man Who Wasn't There",
  "Traffic", "Erin Brockovich", "Gladiator", "Crouching Tiger Hidden Dragon", "Almost Famous",
  "Billy Elliot", "Chocolat", "Requiem for a Dream", "Cast Away",
  "American Beauty", "The Sixth Sense", "The Insider", "The Cider House Rules", "The Green Mile",
  "Magnolia", "The Talented Mr. Ripley", "Boys Don't Cry", "Being John Malkovich",
  "Saving Private Ryan", "Life Is Beautiful", "The Thin Red Line", "Elizabeth",
  "Shakespeare in Love", "Gods and Monsters", "Affliction", "Central Station",
  "Good Will Hunting", "L.A. Confidential", "The Full Monty", "As Good as It Gets",
  "Boogie Nights", "The Wings of the Dove", "Titanic", "Wag the Dog",
  "Shine", "The English Patient", "Fargo", "Secrets & Lies", "Jerry Maguire",
  "Sling Blade", "Breaking the Waves", "The People vs. Larry Flynt",
  "Babe", "Sense and Sensibility", "Dead Man Walking", "Leaving Las Vegas",
  "Apollo 13", "Il Postino", "Nixon", "Mr. Holland's Opus",
  "Forrest Gump", "Pulp Fiction", "The Shawshank Redemption", "Quiz Show", "Four Weddings and a Funeral",
  "Ed Wood", "Hoop Dreams", "Bullets Over Broadway",
  "Schindler's List", "The Piano", "In the Name of the Father", "The Remains of the Day",
  "The Fugitive", "The Age of Innocence", "Philadelphia", "Shadowlands",
  "Unforgiven", "A Few Good Men", "The Crying Game", "Howards End",
  "Scent of a Woman", "Malcolm X", "Lorenzo's Oil", "Aladdin",
  "The Silence of the Lambs", "JFK", "Beauty and the Beast", "Thelma & Louise",
  "Bugsy", "Boyz n the Hood", "Barton Fink", "The Fisher King",
  "Dances with Wolves", "Goodfellas", "The Grifters", "Awakenings",
  "Ghost", "Reversal of Fortune", "Dick Tracy", "Edward Scissorhands",
  "Driving Miss Daisy", "Born on the Fourth of July", "Dead Poets Society", "My Left Foot",
  "Glory", "Do the Right Thing", "Field of Dreams", "When Harry Met Sally",
  "Rain Man", "Mississippi Burning", "Working Girl", "The Accidental Tourist",
  "Dangerous Liaisons", "A Cry in the Dark", "Gorillas in the Mist",
  "The Last Temptation of Christ", "Who Framed Roger Rabbit",
  "Moonstruck", "Broadcast News", "Fatal Attraction", "Hope and Glory",
  "Empire of the Sun", "The Last Emperor", "Wall Street",
  "Aliens", "Hannah and Her Sisters", "The Mission", "Children of a Lesser God",
  "A Room with a View", "Stand by Me", "Blue Velvet", "The Fly",
  "The Color Purple", "Out of Africa", "Witness", "Prizzi's Honor",
  "Kiss of the Spider Woman", "The Trip to Bountiful", "Ran",
  "Amadeus", "A Passage to India", "The Killing Fields", "Places in the Heart",
  "A Soldier's Story", "Splash", "The Natural", "Starman",
  "Terms of Endearment", "The Right Stuff", "The Big Chill", "Tender Mercies",
  "The Dresser", "Yentl", "Silkwood", "WarGames",
  "Tootsie", "Gandhi", "E.T. the Extra-Terrestrial", "Missing", "The Verdict",
  "Sophie's Choice", "Victor/Victoria", "Blade Runner",
  "Chariots of Fire", "On Golden Pond", "Reds", "Atlantic City", "Ragtime",
  "Ordinary People", "Coal Miner's Daughter", "The Elephant Man", "Raging Bull",
  "Tess", "Dressed to Kill", "The Stunt Man",
  "Apocalypse Now", "Breaking Away", "All That Jazz", "Norma Rae",
  "Being There", "The China Syndrome", "Manhattan",
  "Coming Home", "The Deer Hunter", "Midnight Express", "An Unmarried Woman",
  "Heaven Can Wait", "Interiors", "Days of Heaven",
  "Annie Hall", "Star Wars", "The Turning Point", "Julia",
  "Close Encounters of the Third Kind", "The Goodbye Girl", "Saturday Night Fever",
  "Rocky", "Network", "All the President's Men", "Taxi Driver", "Bound for Glory",
  "One Flew Over the Cuckoo's Nest", "Dog Day Afternoon", "Barry Lyndon", "Nashville",
  "Jaws", "Shampoo",
  "The Conversation", "The Godfather Part II", "Chinatown", "The Towering Inferno",
  "Lenny", "A Woman Under the Influence",
  "The Sting", "The Exorcist", "Cries and Whispers", "American Graffiti",
  "A Touch of Class", "The Way We Were",
  "Cabaret", "The Godfather", "Deliverance", "Sounder",
  "The Emigrants", "The Poseidon Adventure",
  "The French Connection", "A Clockwork Orange", "Fiddler on the Roof",
  "The Last Picture Show", "Nicholas and Alexandra", "Sunday Bloody Sunday",
  "Patton", "MASH", "Love Story", "Five Easy Pieces", "Airport",
  "Tora! Tora! Tora!", "Women in Love",
  "Midnight Cowboy", "Butch Cassidy and the Sundance Kid", "Z", "Anne of the Thousand Days",
  "Hello Dolly!", "They Shoot Horses Don't They?",
  "Funny Girl", "The Lion in Winter", "Oliver!", "Rachel Rachel",
  "Romeo and Juliet", "Rosemary's Baby",
  "Bonnie and Clyde", "The Graduate", "In the Heat of the Night", "Guess Who's Coming to Dinner",
  "Doctor Dolittle", "Cool Hand Luke",
  "Poor Things", "Past Lives", "Maestro", "Zone of Interest", "Anatomy of a Fall",
  "American Fiction", "The Holdovers", "Nyad", "May December", "Saltburn",
  "The Whale", "Living", "To Leslie", "Blonde", "She Said",
  "Emancipation", "Babylon", "Causeway", "Till", "Glass Onion",
  "The Batman", "Nope", "Tar", "The Menu", "Decision to Leave",
  "RRR", "The Northman", "After Yang", "Aftersun",
  "The Wizard of Oz", "Citizen Kane", "Sunset Boulevard", "Singin' in the Rain",
  "It's a Wonderful Life", "Some Like It Hot", "Rear Window", "Vertigo",
  "Psycho", "North by Northwest", "2001: A Space Odyssey", "To Kill a Mockingbird",
  "12 Angry Men", "The Manchurian Candidate", "Dr. Strangelove", "Spartacus",
  "The Ten Commandments", "Rebel Without a Cause", "East of Eden", "A Streetcar Named Desire",
  "The African Queen", "Treasure of the Sierra Madre", "The Third Man", "Double Indemnity",
  "Mildred Pierce", "The Philadelphia Story", "Mr. Smith Goes to Washington",
  "Wuthering Heights", "Stagecoach", "Dark Victory", "Gone Girl",
  "The Revenant", "Dunkirk", "Hacksaw Ridge", "Whiplash",
  "Get Out", "Lady Bird", "Call Me by Your Name", "The Shape of Water",
  "Three Billboards Outside Ebbing Missouri", "Phantom Thread",
  "Anora", "Conclave", "The Brutalist", "A Complete Unknown", "Emilia Perez",
  "Wicked", "Dune: Part Two", "I'm Still Here", "Nickel Boys", "September 5",
  "The Substance", "Sing Sing", "A Real Pain", "Flow", "Nosferatu",
];
