export const sportsTeamsByRevenueHints: string[] = [
  "Dallas Cowboys", "Los Angeles Rams", "New York Giants", "Golden State Warriors", "New England Patriots",
  "San Francisco 49ers", "Philadelphia Eagles", "New York Yankees", "New York Knicks", "Miami Dolphins",
  "New York Jets", "Los Angeles Lakers", "Las Vegas Raiders", "Los Angeles Dodgers", "Washington Commanders",
  "Chicago Bears", "Houston Texans", "Atlanta Falcons", "Seattle Seahawks", "Denver Broncos",
  "Real Madrid", "Kansas City Chiefs", "Pittsburgh Steelers", "Green Bay Packers", "Tampa Bay Buccaneers",
  "Minnesota Vikings", "Los Angeles Chargers", "Tennessee Titans", "Cleveland Browns", "Manchester United",
  "Boston Red Sox", "Baltimore Ravens", "Detroit Lions", "Buffalo Bills", "Carolina Panthers",
  "Indianapolis Colts", "FC Barcelona", "Brooklyn Nets", "Chicago Cubs", "Los Angeles Clippers",
  "Boston Celtics", "Arizona Cardinals", "New Orleans Saints", "Liverpool", "Jacksonville Jaguars",
  "Chicago Bulls", "Cincinnati Bengals", "Bayern Munich", "Manchester City", "Miami Heat",
  "Ferrari", "Houston Rockets", "Toronto Raptors", "Philadelphia 76ers", "Arsenal",
  "Dallas Mavericks", "Phoenix Suns", "Paris Saint-Germain", "San Francisco Giants", "Sacramento Kings",
  "Atlanta Hawks", "Denver Nuggets", "Washington Wizards", "Cleveland Cavaliers", "Mercedes",
  "Milwaukee Bucks", "San Antonio Spurs", "Indiana Pacers", "Atlanta Braves", "Tottenham Hotspur",
  "Utah Jazz", "Toronto Maple Leafs", "Portland Trail Blazers", "Chelsea", "Oklahoma City Thunder",
  "Red Bull Racing", "Orlando Magic", "Detroit Pistons", "Houston Astros", "Philadelphia Phillies",
  "Charlotte Hornets", "Minnesota Timberwolves", "New York Rangers", "New York Mets", "New Orleans Pelicans",
  "Memphis Grizzlies", "Montreal Canadiens", "St. Louis Cardinals", "Boston Bruins", "McLaren",
  "Los Angeles Angels", "Los Angeles Kings", "Texas Rangers", "Chicago Blackhawks", "Edmonton Oilers",
  "Toronto Blue Jays", "San Diego Padres", "Philadelphia Flyers", "Washington Nationals", "Aston Martin",
  // Additional plausible teams
  "Miami Marlins", "Oakland Athletics", "Colorado Rockies", "Tampa Bay Rays", "Seattle Mariners",
  "Minnesota Twins", "Kansas City Royals", "Cincinnati Reds", "Pittsburgh Pirates", "Baltimore Orioles",
  "Milwaukee Brewers", "Arizona Diamondbacks", "San Francisco Warriors", "New York Red Bulls", "LA Galaxy",
  "Inter Milan", "AC Milan", "Juventus", "Atletico Madrid", "Sevilla",
  "Borussia Dortmund", "Bayer Leverkusen", "RB Leipzig", "Schalke", "Wolfsburg",
  "Paris FC", "Olympique de Marseille", "Olympique Lyonnais", "Monaco", "Lens",
  "Ajax", "PSV Eindhoven", "Feyenoord", "Celtic", "Rangers",
  "Benfica", "Porto", "Sporting CP", "Galatasaray", "Fenerbahçe",
  "Sacramento Republic", "Nashville SC", "Austin FC", "Charlotte FC", "St. Louis City SC",
  "Vancouver Canucks", "Calgary Flames", "Ottawa Senators", "Winnipeg Jets", "Arizona Coyotes",
  "Vegas Golden Knights", "Seattle Kraken", "San Jose Sharks", "Anaheim Ducks", "Colorado Avalanche",
  "Minnesota Wild", "Nashville Predators", "St. Louis Blues", "Columbus Blue Jackets", "Detroit Red Wings",
  "Carolina Hurricanes", "Tampa Bay Lightning", "Florida Panthers", "Washington Capitals", "Pittsburgh Penguins",
  "New Jersey Devils", "New York Islanders", "Buffalo Sabres", "Ottawa Senators", "Toronto Raptors 905",
];
