// ~500 actors people might guess for highest box office gross
export const actorsBoxOfficeHints: string[] = [
  // Top 100 (the actual answers)
  "Samuel L. Jackson", "Robert Downey Jr.", "Scarlett Johansson", "Zoe Saldana", "Chris Pratt",
  "Tom Hanks", "Chris Hemsworth", "Vin Diesel", "Bradley Cooper", "Chris Evans",
  "Tom Cruise", "Chadwick Boseman", "Dwayne Johnson", "Karen Gillan", "Benedict Cumberbatch",
  "Don Cheadle", "Josh Brolin", "Elizabeth Olsen", "Cate Blanchett", "Tom Holland",
  "Dave Bautista", "Mark Ruffalo", "Paul Rudd", "Jeremy Renner", "Sebastian Stan",
  "Idris Elba", "Morgan Freeman", "Johnny Depp", "Gary Oldman", "Hugo Weaving",
  "Orlando Bloom", "Margot Robbie", "Will Smith", "Harrison Ford", "Emma Watson",
  "Ben Stiller", "Ian McKellen", "Anthony Daniels", "Liam Neeson", "Andy Serkis",
  "Daniel Craig", "Matt Damon", "Leonardo DiCaprio", "Woody Harrelson", "Jennifer Lawrence",
  "Alan Rickman", "Eddie Murphy", "Adam Sandler", "Ryan Reynolds", "Keanu Reeves",
  "Jeff Goldblum", "Bruce Willis", "Owen Wilson", "Jason Statham", "Cameron Diaz",
  "Jack Black", "Julia Roberts", "Sandra Bullock", "Anne Hathaway", "Judy Greer",
  "Warwick Davis", "Bryce Dallas Howard", "Amanda Seyfried", "Helena Bonham Carter", "Jamie Foxx",
  "Michael Caine", "Charlize Theron", "Ben Affleck", "Amy Adams", "Rachel McAdams",
  "Jude Law", "Brad Pitt", "Timothee Chalamet", "Angelina Jolie", "Kate Winslet",
  "Will Ferrell", "John Goodman", "Gwyneth Paltrow", "Jeff Bridges", "Michael B. Jordan",
  "Josh Gad", "Jason Momoa", "Brie Larson", "Awkwafina", "Tessa Thompson",
  "Jon Favreau", "Anthony Mackie", "Simu Liu", "Oscar Isaac", "Florence Pugh",
  "Letitia Wright", "Danai Gurira", "Winston Duke", "Lupita Nyong'o", "Jacob Batalon",
  "Jon Watts", "Hailee Steinfeld", "Kumail Nanjiani", "Gemma Chan", "Brian Tyree Henry",
  // Beyond top 100 — A-listers, action stars, franchise stars, Oscar winners, classic stars
  "Al Pacino", "Robert De Niro", "Meryl Streep", "Denzel Washington", "Tom Hardy",
  "Christian Bale", "Joaquin Phoenix", "Nicole Kidman", "Natalie Portman", "Viola Davis",
  "George Clooney", "Sean Connery", "Michael Douglas", "Dustin Hoffman", "Jack Nicholson",
  "Robert Redford", "Paul Newman", "Clint Eastwood", "Anthony Hopkins", "Gene Hackman",
  "Robin Williams", "Jim Carrey", "Mike Myers", "Steve Carell", "Seth Rogen",
  "Jonah Hill", "James Franco", "Jason Sudeikis", "Vince Vaughn", "Luke Wilson",
  "Melissa McCarthy", "Rebel Wilson", "Tiffany Haddish", "Kevin Hart", "Ice Cube",
  "Chris Rock", "Martin Lawrence", "Tracy Morgan", "Dave Chappelle", "Will Forte",
  "Arnold Schwarzenegger", "Sylvester Stallone", "Jean-Claude Van Damme", "Steven Seagal", "Chuck Norris",
  "Gerard Butler", "Karl Urban", "Liam Hemsworth", "Sam Worthington",
  "Milla Jovovich", "Kate Beckinsale", "Michelle Rodriguez", "Gal Gadot", "Zendaya",
  "Emma Stone", "Jennifer Aniston", "Reese Witherspoon", "Drew Barrymore", "Halle Berry",
  "Megan Fox", "Jessica Alba", "Eva Mendes", "Salma Hayek", "Penelope Cruz",
  "Javier Bardem", "Antonio Banderas", "Benicio Del Toro", "Diego Luna", "Pedro Pascal",
  "John Boyega", "Daisy Ridley", "Adam Driver", "Kelly Marie Tran",
  "Mark Hamill", "Carrie Fisher", "Billy Dee Williams", "Ewan McGregor",
  "Hayden Christensen", "Ian McDiarmid",
  "Robert Pattinson", "Kristen Stewart", "Taylor Lautner", "Anna Kendrick",
  "Chris Pine", "Zachary Quinto", "Simon Pegg", "John Cho",
  "Patrick Stewart", "Hugh Jackman", "James McAvoy", "Michael Fassbender",
  "Ryan Gosling", "Jake Gyllenhaal", "Michelle Williams", "Casey Affleck",
  "Jesse Eisenberg", "Andrew Garfield", "Tobey Maguire", "Kirsten Dunst", "Jamie Dornan",
  "Dakota Johnson", "Michael Keaton", "Tim Robbins", "Kevin Bacon", "Steve Martin",
  "Bill Murray", "Dan Aykroyd", "Chevy Chase", "John Belushi", "Rick Moranis",
  "Danny DeVito", "Joe Pesci", "Ray Liotta", "James Gandolfini", "Steve Buscemi",
  "Willem Dafoe", "John Travolta", "Nicolas Cage", "Alec Baldwin", "Billy Crystal",
  "Meg Ryan", "Tom Selleck", "Richard Gere", "Kevin Costner", "Kurt Russell",
  "Goldie Hawn", "Diane Keaton", "Barbra Streisand", "Sally Field", "Whoopi Goldberg",
  "Glenn Close", "Sigourney Weaver", "Jodie Foster", "Susan Sarandon", "Geena Davis",
  "Winona Ryder", "Uma Thurman", "Sharon Stone", "Demi Moore", "Michelle Pfeiffer",
  "Cillian Murphy", "Emily Blunt", "John Krasinski", "Sienna Miller", "Saoirse Ronan",
  "Anya Taylor-Joy", "Sydney Sweeney", "Jenna Ortega", "Glen Powell",
  "Austin Butler", "Barry Keoghan", "Paul Mescal", "Daisy Edgar-Jones", "Rachel Zegler",
  "Millie Bobby Brown", "Finn Wolfhard", "Noah Schnapp", "Sadie Sink",
  "Henry Cavill", "Daniel Kaluuya", "Lakeith Stanfield",
  "Jonathan Majors", "Keke Palmer", "Janelle Monae", "Regina King", "Taraji P. Henson",
  "Octavia Spencer", "Leslie Odom Jr.", "Cynthia Erivo", "Ariana DeBose",
  "Forest Whitaker", "Terrence Howard", "Laurence Fishburne", "Wesley Snipes",
  "Cuba Gooding Jr.", "Angela Bassett", "Alfre Woodard",
  "Tommy Lee Jones", "Ed Harris", "Sam Elliott", "Jeff Daniels", "William H. Macy",
  "Philip Seymour Hoffman", "John C. Reilly", "Woody Allen", "Diane Lane", "Julianne Moore",
  "Frances McDormand", "Laura Dern", "Allison Janney", "Patricia Arquette", "Toni Collette",
  "Vera Farmiga", "Elizabeth Banks", "Rose Byrne", "Kristen Wiig", "Maya Rudolph",
  "Tina Fey", "Amy Poehler", "Rachel Weisz", "Keira Knightley",
  "Rosamund Pike", "Felicity Jones", "Alicia Vikander", "Emilia Clarke",
  "Sophie Turner", "Maisie Williams", "Kit Harington", "Peter Dinklage",
  "Sean Bean", "Viggo Mortensen", "Elijah Wood", "Liv Tyler", "John Rhys-Davies",
  "Christopher Lee", "Maggie Smith", "Ralph Fiennes", "Emma Thompson",
  "Kenneth Branagh", "Colin Firth", "Judi Dench", "Helen Mirren", "Olivia Colman",
  "Martin Freeman", "Eddie Redmayne", "Tom Hiddleston",
  "Dev Patel", "Riz Ahmed", "Priyanka Chopra", "Irrfan Khan",
  "Jackie Chan", "Jet Li", "Donnie Yen", "Tony Leung", "Michelle Yeoh",
  "Ken Watanabe", "Rinko Kikuchi",
  "Russell Crowe", "Naomi Watts",
  "Sam Neill", "Eric Bana",
  "Mel Gibson", "Heath Ledger", "Guy Pearce", "Joel Edgerton",
  "Channing Tatum", "Miles Teller", "Shailene Woodley", "Ansel Elgort",
  "Zac Efron", "Vanessa Hudgens", "Selena Gomez", "Justin Timberlake",
  "Lady Gaga", "Beyonce", "Rihanna", "Jennifer Lopez", "Queen Latifah",
  "Tyler Perry", "Oprah Winfrey", "Kevin James", "David Spade", "Rob Schneider",
  "Chris Tucker", "Bernie Mac", "Cedric the Entertainer", "Steve Harvey",
  "Danny Glover", "Bruce Lee", "Dolph Lundgren",
  "Randy Couture", "Terry Crews", "Expendables",
  "Patrick Dempsey", "Matthew McConaughey", "Josh Hartnett",
  "Josh Duhamel", "Shia LaBeouf", "Mark Wahlberg", "Donnie Wahlberg",
  "Paul Walker", "Tyrese Gibson", "Ludacris", "Jordana Brewster",
  "John Cena",
  "Mahershala Ali", "Rami Malek", "Brendan Fraser", "Ke Huy Quan",
  "Jamie Lee Curtis", "Stephanie Hsu", "James Hong",
  "Ana de Armas",
  "America Ferrera", "Kate McKinnon", "Issa Rae",
  "Rebecca Ferguson", "Stellan Skarsgard",
  "Christopher Walken", "Dennis Hopper", "Harvey Keitel", "James Caan",
  "Robert Duvall", "Gene Wilder", "Richard Pryor", "Peter Sellers",
  "Audrey Hepburn", "Elizabeth Taylor", "Marilyn Monroe", "Grace Kelly",
  "Humphrey Bogart", "James Stewart", "Cary Grant", "John Wayne",
  "Gregory Peck", "Spencer Tracy", "Marlon Brando", "James Dean",
  "Clark Gable", "Fred Astaire", "Ginger Rogers", "Katharine Hepburn",
  "Bette Davis", "Ingrid Bergman", "Lauren Bacall", "Judy Garland",
  "Kirk Douglas", "Burt Lancaster", "Charlton Heston", "Sidney Poitier",
  "Roger Moore", "Timothy Dalton", "Pierce Brosnan",
];
