// ~500 dog breed names for hints
// Top 100: AKC 2024 most popular breeds (akc.org/expert-advice/news/most-popular-dog-breeds-2024/)
// Plus all other AKC-recognized breeds (ranks 101-201 from same list) + well-known non-AKC/designer breeds
export const akcPopularDogBreedsHints: string[] = [
  // ===== TOP 100 (the actual answers) =====
  "French Bulldog", "Labrador Retriever", "Golden Retriever", "German Shepherd Dog", "Poodle",
  "Dachshund", "Beagle", "Rottweiler", "Bulldog", "German Shorthaired Pointer",
  "Yorkshire Terrier", "Australian Shepherd", "Cavalier King Charles Spaniel", "Cane Corso", "Pembroke Welsh Corgi",
  "Doberman Pinscher", "Boxer", "Miniature Schnauzer", "Bernese Mountain Dog", "Shih Tzu",
  "Great Dane", "Pomeranian", "Boston Terrier", "Miniature American Shepherd", "Havanese",
  "Siberian Husky", "Chihuahua", "English Springer Spaniel", "Shetland Sheepdog", "Border Collie",
  "Brittany", "Cocker Spaniel", "Belgian Malinois", "Basset Hound", "Vizsla",
  "English Cocker Spaniel", "Maltese", "Pug", "Collie", "Mastiff",
  "West Highland White Terrier", "Shiba Inu", "Rhodesian Ridgeback", "Papillon", "Portuguese Water Dog",
  "Bichon Frise", "Newfoundland", "Dalmatian", "Australian Cattle Dog", "Whippet",
  "Wirehaired Pointing Griffon", "Chesapeake Bay Retriever", "Samoyed", "Scottish Terrier", "Weimaraner",
  "Italian Greyhound", "Giant Schnauzer", "Bloodhound", "Akita", "Cardigan Welsh Corgi",
  "German Wirehaired Pointer", "Saint Bernard", "Staffordshire Bull Terrier", "Airedale Terrier", "Boykin Spaniel",
  "Russell Terrier", "Bullmastiff", "Chinese Crested", "Nova Scotia Duck Tolling Retriever", "Biewer Terrier",
  "Cairn Terrier", "Bull Terrier", "Miniature Pinscher", "Great Pyrenees", "Soft Coated Wheaten Terrier",
  "Irish Wolfhound", "American Staffordshire Terrier", "Lagotto Romagnolo", "Alaskan Malamute", "Basenji",
  "Rat Terrier", "Greater Swiss Mountain Dog", "Chinese Shar-Pei", "Brussels Griffon", "Irish Setter",
  "Anatolian Shepherd Dog", "Pekingese", "Chow Chow", "Old English Sheepdog", "Keeshond",
  "Standard Schnauzer", "Coton de Tulear", "English Setter", "Lhasa Apso", "Dogo Argentino",
  "Dogue de Bordeaux", "Flat-Coated Retriever", "Border Terrier", "Leonberger", "Beauceron",

  // ===== AKC RANKS 101-201 =====
  "Bouvier des Flandres", "Borzoi", "Japanese Chin", "Norwich Terrier", "Miniature Bull Terrier",
  "Schipperke", "Belgian Tervuren", "Toy Fox Terrier", "Gordon Setter", "Afghan Hound",
  "Silky Terrier", "Parson Russell Terrier", "Wire Fox Terrier", "Boerboel", "Manchester Terrier",
  "American Eskimo Dog", "Tibetan Terrier", "Greyhound", "Xoloitzcuintli", "Spinone Italiano",
  "Pointer", "Mudi", "Welsh Terrier", "Norwegian Elkhound", "American Hairless Terrier",
  "Tibetan Spaniel", "Black Russian Terrier", "Neapolitan Mastiff", "Finnish Lapphund", "Norfolk Terrier",
  "Belgian Sheepdog", "Bracco Italiano", "German Pinscher", "Bedlington Terrier", "Kerry Blue Terrier",
  "Irish Terrier", "Bluetick Coonhound", "Welsh Springer Spaniel", "Smooth Fox Terrier", "Bearded Collie",
  "Saluki", "Barbet", "Icelandic Sheepdog", "Redbone Coonhound", "Briard",
  "English Toy Spaniel", "Spanish Water Dog", "Tibetan Mastiff", "Clumber Spaniel", "Russian Toy",
  "Black and Tan Coonhound", "Treeing Walker Coonhound", "Swedish Vallhund", "Lowchen", "Petit Basset Griffon Vendeen",
  "Lakeland Terrier", "Portuguese Podengo Pequeno", "Australian Terrier", "Wirehaired Vizsla", "Field Spaniel",
  "Nederlandse Kooikerhondje", "Affenpinscher", "Curly-Coated Retriever", "Kuvasz", "Scottish Deerhound",
  "Berger Picard", "American Water Spaniel", "Sealyham Terrier", "Pumi", "Irish Red and White Setter",
  "American English Coonhound", "Puli", "Plott Hound", "Ibizan Hound", "Sussex Spaniel",
  "Glen of Imaal Terrier", "Irish Water Spaniel", "Entlebucher Mountain Dog", "Skye Terrier", "Dandie Dinmont Terrier",
  "Polish Lowland Sheepdog", "Chinook", "Harrier", "Norwegian Buhund", "Pharaoh Hound",
  "Komondor", "Cesky Terrier", "Pyrenean Shepherd", "Lancashire Heeler", "Belgian Laekenois",
  "Cirneco dell'Etna", "Azawakh", "American Foxhound", "Finnish Spitz", "Canaan Dog",
  "Otterhound", "Sloughi", "Norwegian Lundehund", "Grand Basset Griffon Vendeen", "Bergamasco Sheepdog",
  "English Foxhound",

  // ===== OTHER AKC-RECOGNIZED BREEDS (not in top 201) =====
  "Appenzeller Sennenhund", "Barbado da Terceira", "Bavarian Mountain Scent Hound", "Belgian Shepherd",
  "Bohemian Shepherd", "Bolognese", "Bouvier des Ardennes", "Braque du Bourbonnais",
  "Broholmer", "Calupoh", "Carolina Dog", "Catahoula Leopard Dog", "Caucasian Shepherd Dog",
  "Central Asian Shepherd Dog", "Czechoslovakian Vlciak", "Danish-Swedish Farmdog", "Drentsche Patrijshond",
  "Dutch Shepherd", "Estrela Mountain Dog", "Eurasier", "French Spaniel", "German Longhaired Pointer",
  "German Spitz", "Hamiltonstovare", "Hanoverian Scenthound", "Hokkaido", "Hovawart",
  "Japanese Akitainu", "Japanese Spitz", "Kai Ken", "Karelian Bear Dog", "Korean Jindo Dog",
  "Kromfohrlander", "Lapponian Herder", "Large Munsterlander", "Mountain Cur", "Norrbottenspets",
  "Peruvian Inca Orchid", "Pont-Audemer Spaniel", "Porcelaine", "Portuguese Sheepdog",
  "Pudelpointer", "Romanian Carpathian Shepherd", "Romanian Mioritic Shepherd Dog",
  "Russian Tsvetnaya Bolonka", "Schapendoes", "Segugio Italiano", "Shikoku Ken", "Slovakian Wirehaired Pointer",
  "Slovensky Cuvac", "Small Munsterlander", "Spanish Mastiff", "Stabyhoun",
  "Swedish Lapphund", "Taiwan Dog", "Teddy Roosevelt Terrier", "Thai Bangkaew", "Thai Ridgeback",
  "Tosa", "Transylvanian Hound", "Treeing Tennessee Brindle", "Volpino Italiano",
  "Wetterhoun", "Working Kelpie", "Yakutian Laika", "Basset Fauve de Bretagne",
  "Braque Francais Pyrenean", "Braque Saint-Germain", "Australian Kelpie", "Australian Stumpy Tail Cattle Dog",
  "Poodle (Toy)", "Poodle (Miniature)", "Poodle (Standard)",

  // ===== WELL-KNOWN DESIGNER / NON-AKC BREEDS =====
  "Labradoodle", "Goldendoodle", "Cockapoo", "Maltipoo", "Cavapoo",
  "Bernedoodle", "Aussiedoodle", "Sheepadoodle", "Schnoodle", "Yorkipoo",
  "Pomsky", "Morkie", "Puggle", "Doodle", "Shorkie",
  "Poochon", "Cavachon", "Teddy Bear Dog", "Chipoo", "Chiweenie",
  "Pomchi", "Hug Dog", "Jack Chi", "Beaglier", "Spoodle",
  "Jackapoo", "Sproodle", "Bordoodle", "Groodle", "Cavoodle",
  "Bolonoodle", "Whoodle", "Saint Berdoodle", "Pyredoodle", "Weimardoodle",
  "Springerdoodle", "Eskapoo", "Lhasapoo", "Peekapoo", "Doxiepoo",
  "Irish Doodle", "Double Doodle", "Multigen Doodle",
  "Wolf Dog", "Tamaskan", "Northern Inuit Dog", "Utonagan",
  "Alaskan Klee Kai", "Miniature Husky",
];
