// ~900 dish names for autocomplete hints
export const bestDishesWorldHints: string[] = [
  // Top 100 (the actual answers)
  "Vori-vori", "Pizza Napoletana", "Tajarin al tartufo bianco d'Alba",
  "Sate kambing", "Oltu cağ kebabı", "Kontosouvli", "Arroz tapado",
  "Komplet lepinja", "Quesabirria (Birria tacos)", "Pappardelle al cinghiale",
  "Central Texas-Style Barbecue", "Bath kulu badhu (Sri Lankan rice and curry)",
  "Seco de cabrito", "Beyran çorbası", "Picanha", "Siu mei",
  "Amritsari kulcha", "Bistecca alla Fiorentina", "Pollo a la brasa",
  "Empanadas Tucumanas", "Leitão da bairrada", "Yokohama-Style Ramen",
  "Cochinita pibil", "Maguro nigiri sushi", "Païdakia",
  "Beyti kebab", "Tibs", "Cordero al palo", "Soto Betawi",
  "Phanaeng Curry", "Khao soi", "Châteaubriand", "Çökertme kebabı",
  "Costela", "Arroz con bogavante", "Tagliata di manzo", "Tonkotsu ramen",
  "Hünkar beğendi", "Bistec a lo pobre", "Inasal na manok",
  "Ceviche de conchas negras", "Sate Padang", "Asado", "Tom kha gai",
  "Jalea", "Maine-style Lobster Roll", "Hotate nigiri sushi",
  "İskender kebap", "Parmigiana alla napoletana",
  "Carne de porco à Alentejana", "Lohikeitto (Salmon soup)",
  "Sinigang na baboy", "Kuzu şiş", "Strapatsada",
  "Camarones el mojo de ajo", "Tagliatelle al ragù alla Bolognese",
  "Adana kebap", "Giouvetsi", "Cordero asado", "Sinigang",
  "Alinazik kebab", "Sirnica", "Taiwanese Hot Pot",
  "Murgh karahi (Chicken karahi)", "Tanjia",
  "Murgh makhani (Butter chicken)", "Karē", "Gambas al ajillo",
  "Sake nigiri sushi", "Risotto ai funghi porcini",
  "Linguine allo scoglio", "Hyderabadi biryani", "Galbi",
  "Katsu karē", "Pernil", "Gunkanmaki", "Fritto misto di pesce",
  "Burnt Ends", "Kabab torsh", "Kalakeitto (Finnish fish soup)",
  "Bún bò nam bộ", "Beijing kao ya (Peking duck)", "Phở bò (Beef pho)",
  "Lomo saltado", "Shahi paneer", "Mtsvadi", "Paçanga böreği",
  "Memphis-Style Barbecue", "Carbonara", "Lasagne alla Bolognese",
  "Khachapuri", "Phat kaphrao", "Polvo à Lagareiro",
  "Chtapodi sti schara (Grilled octopus)", "Gambas à la plancha",
  "Samgyeopsal", "Yóupō miàn (Biáng biáng noodles)",
  "Moqueca Baiana", "Sopa de lima", "Sopa da pedra",

  // ==================== ITALIAN ====================
  "Amatriciana", "Cacio e Pepe", "Gricia", "Arrabbiata",
  "Puttanesca", "Bolognese", "Cannelloni", "Manicotti",
  "Gnocchi", "Risotto Milanese", "Ossobuco",
  "Cotoletta alla Milanese", "Saltimbocca", "Chicken Cacciatore",
  "Polpette", "Arancini", "Supplì", "Bruschetta", "Crostini",
  "Caprese Salad", "Panzanella", "Ribollita", "Minestrone",
  "Pasta e Fagioli", "Pasta e Ceci", "Zuppa di Pesce",
  "Caponata", "Melanzane alla Parmigiana", "Involtini",
  "Braciole", "Saltimbocca alla Romana", "Trippa alla Romana",
  "Coda alla Vaccinara", "Bucatini all'Amatriciana",
  "Spaghetti alle Vongole", "Fettuccine Alfredo",
  "Orecchiette con Cime di Rapa", "Pasta alla Norma",
  "Pasta con le Sarde", "Spaghetti al Nero di Seppia",
  "Calzone", "Stromboli", "Focaccia", "Piadina",
  "Vitello Tonnato", "Bagna Càuda", "Fonduta",
  "Calamari Fritti", "Porchetta", "Arista",
  "Carpaccio", "Bresaola", "Prosciutto e Melone",
  "Farinata", "Torta Pasqualina", "Cannoli", "Sfogliatelle",
  "Babà", "Zeppole", "Pastiera Napoletana", "Torta della Nonna",
  "Panna Cotta", "Tiramisu", "Affogato", "Gelato", "Granita",
  "Zuppa Inglese", "Amaretti", "Biscotti", "Panforte",
  "Pizza Margherita", "Pizza Marinara", "Aglio e Olio",

  // ==================== JAPANESE ====================
  "Miso Soup", "Tonkatsu", "Yakiniku", "Yakitori", "Teriyaki",
  "Tempura", "Udon", "Soba", "Yakisoba", "Shabu-Shabu",
  "Sukiyaki", "Oden", "Karaage", "Gyoza", "Takoyaki",
  "Okonomiyaki", "Chawanmushi", "Tamagoyaki", "Oyakodon",
  "Katsudon", "Gyudon", "Tendon", "Unaju", "Chirashi Sushi",
  "Temaki", "Maki Sushi", "Inari Sushi", "Onigiri",
  "Sashimi", "Uni", "Ikura", "Amaebi", "Wagyu Beef",
  "Teppanyaki", "Kaiseki", "Curry Rice", "Chazuke",
  "Tamago Kake Gohan", "Hitsumabushi", "Kaisendon",
  "Taiyaki", "Dorayaki", "Mochi", "Daifuku", "Matcha Ice Cream",
  "Ramen", "Shoyu Ramen", "Miso Ramen", "Shio Ramen",
  "Tsukemen", "Sapporo Ramen", "Hakata Ramen",

  // ==================== CHINESE ====================
  "Kung Pao Chicken", "Mapo Tofu", "Xiaolongbao",
  "Char Siu", "Wonton Soup", "Sichuan Hot Pot",
  "Congee", "Chow Mein", "Lo Mein", "Yangzhou Fried Rice",
  "Dan Dan Noodles", "Zhajiangmian", "Lanzhou Beef Noodle Soup",
  "Scallion Pancakes", "Red Braised Pork", "Dongpo Pork",
  "Lion's Head Meatballs", "Sweet and Sour Pork",
  "General Tso's Chicken", "Sesame Chicken", "Moo Shu Pork",
  "Stinky Tofu", "Mooncakes", "Tang Yuan", "Jiaozi",
  "Shengjian Bao", "Baozi", "Spring Rolls", "Egg Rolls",
  "Clay Pot Rice", "Steamed Fish", "Salt and Pepper Squid",
  "Drunken Chicken", "White Cut Chicken", "Beggar's Chicken",
  "Crispy Duck", "Buddha's Delight", "Dim Sum",
  "Har Gow", "Siu Mai", "Char Siu Bao", "Cheung Fun",
  "Turnip Cake", "Egg Tart", "Pineapple Bun",
  "Guotie", "Nian Gao", "Zongzi", "Mantou",

  // ==================== THAI ====================
  "Tom Yum Goong", "Green Curry", "Red Curry", "Yellow Curry",
  "Massaman Curry", "Som Tum", "Larb", "Nam Tok",
  "Gai Yang", "Moo Ping", "Khao Pad", "Pad See Ew",
  "Pad Woon Sen", "Rad Na", "Gaeng Pa", "Pad Thai",
  "Hoy Tod", "Kai Jeow", "Tod Mun Pla",
  "Satay (Thai)", "Miang Kham", "Khao Tom", "Khao Man Gai",
  "Khao Ka Moo", "Mango Sticky Rice", "Tab Tim Krob",

  // ==================== INDIAN ====================
  "Dal Makhani", "Dal Tadka", "Chana Masala", "Rajma",
  "Palak Paneer", "Paneer Tikka Masala", "Saag Paneer",
  "Malai Kofta", "Aloo Gobi", "Kadai Paneer",
  "Pav Bhaji", "Vada Pav", "Bhel Puri", "Pani Puri",
  "Samosa", "Pakora", "Onion Bhaji", "Idli", "Dosa",
  "Masala Dosa", "Uttapam", "Sambar", "Rasam", "Appam",
  "Kerala Fish Curry", "Chettinad Chicken",
  "Lucknowi Biryani", "Dum Biryani", "Tandoori Chicken",
  "Tikka Masala", "Naan", "Paratha", "Aloo Paratha",
  "Chapati", "Roti", "Kulfi", "Gulab Jamun", "Jalebi",
  "Rasgulla", "Kheer", "Halwa", "Ladoo", "Barfi",
  "Biryani", "Butter Naan", "Chicken Tikka",
  "Vindaloo", "Korma", "Rogan Josh", "Dhansak",
  "Peshwari Naan", "Keema", "Daal",

  // ==================== MEXICAN ====================
  "Tamales", "Enchiladas", "Burritos", "Quesadillas",
  "Nachos", "Chilaquiles", "Huevos Rancheros",
  "Pozole", "Menudo", "Birria", "Barbacoa", "Carnitas",
  "Tacos al Pastor", "Chiles en Nogada", "Chile Relleno",
  "Mole Poblano", "Mole Negro", "Mole Verde",
  "Tlayuda", "Tostadas", "Sopes", "Gorditas",
  "Flautas", "Taquitos", "Torta Ahogada", "Cemita",
  "Elote", "Esquites", "Carne Asada", "Frijoles Charros",
  "Churros", "Tres Leches", "Flan",
  "Tacos", "Guacamole", "Pico de Gallo", "Salsa Verde",

  // ==================== TURKISH ====================
  "Doner Kebap", "Shish Kebab", "Lahmacun", "Pide",
  "Gözleme", "Menemen", "Meze", "Dolma", "Imam Bayildi",
  "Karniyarik", "Köfte", "Tantuni", "Manti",
  "Baklava", "Kunefe", "Turkish Delight", "Urfa Kebap", "Testi Kebab",
  "Borek", "Sigara Boregi", "Su Boregi", "Cilbir",
  "Mercimek Corbasi", "Ezogelin Corbasi",
  "Iskender", "Cig Kofte", "Simit", "Acili Ezme",
  "Dürüm", "Tavuk Göğsü",

  // ==================== GREEK ====================
  "Moussaka", "Souvlaki", "Gyros", "Spanakopita",
  "Tiropita", "Saganaki", "Taramasalata", "Dolmades",
  "Horiatiki", "Tzatziki", "Avgolemono", "Stifado",
  "Pastitsio", "Galaktoboureko", "Loukoumades",
  "Kleftiko", "Fasolada", "Gemista", "Briam",
  "Koulouri", "Bougatsa",
  "Revithada", "Garides Saganaki", "Kolokithokeftedes",

  // ==================== KOREAN ====================
  "Bulgogi", "Galbi Jjim", "Doenjang Jjigae",
  "Kimchi Jjigae", "Sundubu Jjigae", "Budae Jjigae",
  "Dak Galbi", "Haemul Pajeon", "Bindaetteok",
  "Tteokbokki", "Japchae", "Naengmyeon", "Bibim Naengmyeon",
  "Kalguksu", "Jajangmyeon", "Seolleongtang",
  "Bossam", "Jokbal", "Yangnyeom Chicken",
  "Korean Fried Chicken", "Hotteok", "Bungeoppang",
  "Gimbap", "Bibimbap", "Kimchi Bokkeumbap",
  "Gamjatang", "Dakgangjeong", "Sundae",

  // ==================== FRENCH ====================
  "Cassoulet", "Confit de Canard", "Ratatouille",
  "Crêpes Suzette", "Soufflé", "Quiche Lorraine",
  "French Onion Soup", "Pot-au-Feu", "Blanquette de Veau",
  "Steak Frites", "Steak au Poivre", "Duck à l'Orange",
  "Poulet Rôti", "Escargots de Bourgogne", "Foie Gras",
  "Terrine", "Pâté", "Croque Monsieur", "Croque Madame",
  "Salade Niçoise", "Gratin Dauphinois", "Bouillabaisse",
  "Coq au Vin", "Beef Bourguignon", "Sole Meunière",
  "Moules Marinières", "Moules Frites", "Raclette",
  "Fondue", "Tartiflette", "Croissant",
  "Pain au Chocolat", "Brioche", "Éclair",
  "Mille-Feuille", "Macaron", "Profiteroles",
  "Crème Brûlée", "Mousse au Chocolat", "Tarte Tatin",
  "Madeleines", "Clafoutis", "Canelé",

  // ==================== SOUTHEAST ASIAN ====================
  // Filipino
  "Adobo", "Kare-Kare", "Lechon", "Lechon Kawali",
  "Crispy Pata", "Sisig", "Bulalo", "Tinola", "Dinuguan",
  "Pinakbet", "Bicol Express", "Pancit", "Pancit Bihon",
  "Halo-Halo", "Bibingka", "Lumpia",

  // Vietnamese
  "Bún Chả", "Bún Bò Huế", "Cao Lầu", "Bánh Xèo",
  "Bánh Cuốn", "Bò Lúc Lắc", "Cơm Tấm", "Bún Riêu",
  "Mì Quảng", "Gỏi Cuốn", "Chả Giò", "Bánh Mì",
  "Phở Gà", "Hủ Tiếu",

  // Indonesian/Malaysian
  "Nasi Goreng", "Rendang", "Soto Ayam", "Mie Goreng",
  "Bakso", "Gado-Gado", "Nasi Uduk", "Nasi Lemak",
  "Martabak", "Tempe", "Satay", "Laksa", "Char Kway Teow",
  "Roti Canai", "Bak Kut Teh", "Chili Crab",
  "Hainanese Chicken Rice", "Kaya Toast",
  "Curry Puff", "Teh Tarik", "Pempek", "Rawon",

  // ==================== PORTUGUESE ====================
  "Bacalhau à Brás", "Bacalhau com Natas", "Caldo Verde",
  "Cozido à Portuguesa", "Arroz de Marisco", "Cataplana",
  "Sardinhas Assadas", "Bifanas", "Francesinha",
  "Prego no Pão", "Pastéis de Belém", "Piri-Piri Chicken",
  "Ovos Moles", "Arroz Doce",

  // ==================== SPANISH ====================
  "Gazpacho", "Salmorejo", "Cocido Madrileño",
  "Fabada Asturiana", "Tortilla Española", "Patatas Bravas",
  "Pan con Tomate", "Jamón Ibérico", "Chorizo",
  "Croquetas", "Calamares a la Romana",
  "Pulpo a la Gallega", "Pimientos de Padrón",
  "Paella Valenciana", "Churros con Chocolate",
  "Crema Catalana", "Pintxos", "Tapas",
  "Arroz Negro", "Fideuà",

  // ==================== PERUVIAN ====================
  "Ceviche", "Aji de Gallina", "Causa", "Papa Rellena",
  "Anticuchos", "Tiradito", "Rocoto Relleno",
  "Papa a la Huancaína", "Arroz con Pollo",
  "Arroz Chaufa", "Suspiro Limeño", "Picarones",
  "Cau Cau", "Tacu Tacu",

  // ==================== SOUTH AMERICAN ====================
  "Feijoada", "Churrasco", "Pão de Queijo", "Coxinha",
  "Brigadeiro", "Açaí Bowl", "Arepas", "Bandeja Paisa",
  "Sancocho", "Empanada Argentina", "Milanesa", "Provoleta",
  "Locro", "Alfajores", "Dulce de Leche",
  "Pastel de Choclo", "Cazuela", "Sopaipillas",

  // ==================== MIDDLE EASTERN ====================
  "Hummus", "Baba Ganoush", "Tabbouleh", "Fattoush",
  "Kibbeh", "Kafta", "Labneh", "Falafel", "Shawarma",
  "Manakish", "Fatayer", "Knafeh",
  "Mansaf", "Kabsa", "Shakshuka", "Ful Medames",
  "Mujaddara", "Kabab Koobideh", "Chelo Kabab",
  "Joojeh Kabab", "Ghormeh Sabzi", "Fesenjan",
  "Tahdig", "Ash Reshteh", "Zereshk Polo",

  // ==================== AMERICAN ====================
  "Buffalo Wings", "Mac and Cheese", "Lobster Roll",
  "Crab Cake", "Jambalaya", "Gumbo", "Beignets",
  "Shrimp and Grits", "Pulled Pork Sandwich",
  "Philly Cheesesteak", "Chicago-Style Hot Dog",
  "Detroit-Style Pizza", "New York-Style Pizza",
  "Smash Burger", "Corn Dog", "Apple Pie", "Pecan Pie",
  "Key Lime Pie", "New York Cheesecake", "Eggs Benedict",
  "Clam Chowder", "Fried Chicken", "Biscuits and Gravy",
  "Chicken Pot Pie", "Po'boy", "Reuben Sandwich",
  "BLT", "Club Sandwich", "Sloppy Joe",
  "Kansas City-Style Barbecue", "Carolina-Style Barbecue",
  "Nashville Hot Chicken", "Deep-Dish Pizza",

  // ==================== AFRICAN ====================
  "Jollof Rice", "Tagine", "Couscous", "Injera",
  "Doro Wat", "Kitfo", "Suya", "Egusi Soup",
  "Fufu", "Bobotie", "Bunny Chow", "Boerewors",
  "Chakalaka", "Thieboudienne", "Yassa Poulet",
  "Mafe", "Peanut Soup", "Akara",

  // ==================== EASTERN EUROPEAN ====================
  "Borscht", "Pierogi", "Goulash", "Beef Stroganoff",
  "Blini", "Pelmeni", "Chicken Kiev", "Svíčková",
  "Schnitzel", "Sauerbraten",
  "Gołąbki", "Bigos", "Żurek",
  "Ćevapi", "Pljeskavica", "Burek",

  // ==================== GERMAN/AUSTRIAN ====================
  "Bratwurst", "Currywurst", "Weisswurst",
  "Schweinshaxe", "Spätzle", "Käsespätzle",
  "Maultaschen", "Rouladen", "Kartoffelsuppe",
  "Bretzel", "Apfelstrudel", "Sachertorte",
  "Kaiserschmarrn", "Wiener Schnitzel",

  // ==================== SCANDINAVIAN ====================
  "Swedish Meatballs", "Gravlax", "Smörgåsbord",
  "Smørrebrød", "Frikadeller", "Æbleskiver",
  "Kanelbulle", "Semla", "Karjalan Piirakka",

  // ==================== CARIBBEAN/CENTRAL AMERICAN ====================
  "Jerk Chicken", "Ackee and Saltfish", "Rice and Peas",
  "Curry Goat", "Oxtail Stew", "Mofongo",
  "Arroz con Gandules", "Pupusas", "Gallo Pinto",
  "Cuban Sandwich", "Ropa Vieja", "Tostones",
  "Doubles", "Pelau",

  // ==================== GEORGIAN ====================
  "Khinkali", "Adjarian Khachapuri", "Lobio",
  "Pkhali", "Badrijani", "Chakhokhbili",
  "Churchkhela", "Shkmeruli",

  // ==================== PAKISTANI/SOUTH ASIAN ====================
  "Nihari", "Haleem", "Chapli Kebab", "Seekh Kebab",
  "Karahi", "Bihari Kebab", "Paye",
  "Kabuli Pulao", "Mantu", "Bolani",
  "Kottu Roti", "Hoppers", "String Hoppers",
  "Lamprais", "Pol Sambol",
  "Momos", "Dal Bhat", "Sel Roti",

  // ==================== MISCELLANEOUS GLOBAL ====================
  "Fish and Chips", "Full English Breakfast",
  "Shepherd's Pie", "Bangers and Mash", "Cornish Pasty",
  "Sunday Roast", "Toad in the Hole", "Scotch Egg",
  "Rösti", "Swiss Fondue", "Raclette (Swiss)",
  "Poutine", "Tourtière", "Nanaimo Bar",
  "Haggis", "Rendang Padang",
];
