// ~500 well-known albums — the top 100 answers plus 400 additional albums
export const bestSellingAlbumsHints: string[] = [
  // Top 100 (the actual answers)
  "Thriller - Michael Jackson", "Back in Black - AC/DC", "The Bodyguard - Whitney Houston", "The Dark Side of the Moon - Pink Floyd", "Their Greatest Hits (1971-1975) - Eagles",
  "Hotel California - Eagles", "Come On Over - Shania Twain", "Rumours - Fleetwood Mac", "Bat Out of Hell - Meat Loaf", "Saturday Night Fever - Bee Gees",
  "Led Zeppelin IV - Led Zeppelin", "Bad - Michael Jackson", "Jagged Little Pill - Alanis Morissette", "Dirty Dancing - Soundtrack", "Falling into You - Celine Dion",
  "Dangerous - Michael Jackson", "21 - Adele", "1 - The Beatles", "The Black Album - Metallica", "Let's Talk About Love - Celine Dion",
  "Legend - Bob Marley and the Wailers", "Nevermind - Nirvana", "Appetite for Destruction - Guns N' Roses", "Born in the U.S.A. - Bruce Springsteen", "Gold: Greatest Hits - ABBA",
  "Brothers in Arms - Dire Straits", "The Immaculate Collection - Madonna", "Supernatural - Santana", "The Wall - Pink Floyd", "Sgt. Pepper's Lonely Hearts Club Band - The Beatles",
  "Abbey Road - The Beatles", "Come Away with Me - Norah Jones", "Grease - Soundtrack", "Music Box - Mariah Carey", "The Eminem Show - Eminem",
  "Titanic - Soundtrack", "Unplugged - Eric Clapton", "Greatest Hits - Queen", "...Baby One More Time - Britney Spears", "Slippery When Wet - Bon Jovi",
  "Greatest Hits - Journey", "Whitney Houston - Whitney Houston", "No Jacket Required - Phil Collins", "The Marshall Mathers LP - Eminem", "Hybrid Theory - Linkin Park",
  "The Joshua Tree - U2", "Purple Rain - Prince", "Tapestry - Carole King", "True Blue - Madonna", "Faith - George Michael",
  "Bridge over Troubled Water - Simon & Garfunkel", "Greatest Hits - Elton John", "Millennium - Backstreet Boys", "25 - Adele", "Spice - Spice Girls",
  "The Sign - Ace of Base", "American Idiot - Green Day", "HIStory - Michael Jackson", "All the Way... A Decade of Song - Celine Dion", "(What's the Story) Morning Glory? - Oasis",
  "The Score - Fugees", "Like a Virgin - Madonna", "Cross Road - Bon Jovi", "Dookie - Green Day", "Cracked Rear View - Hootie & the Blowfish",
  "Elvis' Christmas Album - Elvis Presley", "Boston - Boston", "Daydream - Mariah Carey", "Whitney - Whitney Houston", "The Woman in Me - Shania Twain",
  "Oops!... I Did It Again - Britney Spears", "Hysteria - Def Leppard", "The Miseducation of Lauryn Hill - Lauryn Hill", "Tracy Chapman - Tracy Chapman", "Off the Wall - Michael Jackson",
  "Can't Slow Down - Lionel Richie", "The Colour of My Love - Celine Dion", "Wish You Were Here - Pink Floyd", "Romanza - Andrea Bocelli", "Back to Black - Amy Winehouse",
  "Confessions - Usher", "The Beatles (White Album) - The Beatles", "Achtung Baby - U2", "Use Your Illusion II - Guns N' Roses", "Ten - Pearl Jam",
  "The Lion King - Soundtrack", "Ropin' the Wind - Garth Brooks", "No Fences - Garth Brooks", "The Beatles 1962-1966 - The Beatles", "Bat Out of Hell II - Meat Loaf",
  "Some Gave All - Billy Ray Cyrus", "Yourself or Someone Like You - Matchbox Twenty", "Pieces of You - Jewel", "Vs. - Pearl Jam", "Emotions - Mariah Carey",
  "Goodbye Yellow Brick Road - Elton John", "A Night at the Opera - Queen", "News of the World - Queen", "Please Hammer Don't Hurt 'Em - MC Hammer", "Spiceworld - Spice Girls",
  // 101-500 additional well-known albums
  "OK Computer - Radiohead", "The Bends - Radiohead", "Kid A - Radiohead", "In Rainbows - Radiohead",
  "Parachutes - Coldplay", "A Rush of Blood to the Head - Coldplay", "X&Y - Coldplay", "Viva la Vida - Coldplay", "Mylo Xyloto - Coldplay",
  "Fearless - Taylor Swift", "1989 - Taylor Swift", "Red - Taylor Swift", "reputation - Taylor Swift", "Lover - Taylor Swift", "folklore - Taylor Swift", "Midnights - Taylor Swift",
  "Lemonade - Beyonce", "Dangerously in Love - Beyonce", "I Am... Sasha Fierce - Beyonce", "Renaissance - Beyonce",
  "The Chronic - Dr. Dre", "2001 - Dr. Dre", "Ready to Die - Notorious B.I.G.", "Life After Death - Notorious B.I.G.",
  "All Eyez on Me - 2Pac", "Me Against the World - 2Pac", "Illmatic - Nas", "Reasonable Doubt - Jay-Z", "The Blueprint - Jay-Z", "4:44 - Jay-Z",
  "College Dropout - Kanye West", "Late Registration - Kanye West", "Graduation - Kanye West", "My Beautiful Dark Twisted Fantasy - Kanye West",
  "Slim Shady LP - Eminem", "Recovery - Eminem", "Relapse - Eminem",
  "Songs in the Key of Life - Stevie Wonder", "Innervisions - Stevie Wonder", "What's Going On - Marvin Gaye",
  "Kind of Blue - Miles Davis", "A Love Supreme - John Coltrane",
  "Led Zeppelin I - Led Zeppelin", "Led Zeppelin II - Led Zeppelin", "Physical Graffiti - Led Zeppelin", "Houses of the Holy - Led Zeppelin",
  "Exile on Main St. - Rolling Stones", "Let It Bleed - Rolling Stones", "Sticky Fingers - Rolling Stones", "Some Girls - Rolling Stones",
  "Who's Next - The Who", "Tommy - The Who", "Quadrophenia - The Who",
  "Blood on the Tracks - Bob Dylan", "Highway 61 Revisited - Bob Dylan", "Blonde on Blonde - Bob Dylan",
  "Electric Ladyland - Jimi Hendrix", "Are You Experienced - Jimi Hendrix",
  "Paranoid - Black Sabbath", "Master of Reality - Black Sabbath",
  "The Number of the Beast - Iron Maiden", "Powerslave - Iron Maiden",
  "Master of Puppets - Metallica", "Ride the Lightning - Metallica", "...And Justice for All - Metallica",
  "Use Your Illusion I - Guns N' Roses", "Chinese Democracy - Guns N' Roses",
  "Pyromania - Def Leppard", "Adrenalize - Def Leppard",
  "New Jersey - Bon Jovi", "Keep the Faith - Bon Jovi",
  "Born to Run - Bruce Springsteen", "The River - Bruce Springsteen", "Nebraska - Bruce Springsteen",
  "Like a Prayer - Madonna", "Ray of Light - Madonna", "Confessions on a Dance Floor - Madonna",
  "In the Zone - Britney Spears", "Blackout - Britney Spears", "Circus - Britney Spears",
  "Songs in A Minor - Alicia Keys", "The Diary of Alicia Keys - Alicia Keys",
  "19 - Adele", "30 - Adele",
  "Thank U, Next - Ariana Grande", "Positions - Ariana Grande", "My Everything - Ariana Grande",
  "Voodoo - D'Angelo", "Aquemini - OutKast", "Speakerboxxx/The Love Below - OutKast", "Stankonia - OutKast",
  "Licensed to Ill - Beastie Boys", "Paul's Boutique - Beastie Boys",
  "Merry Christmas - Mariah Carey", "The Emancipation of Mimi - Mariah Carey", "#1's - Mariah Carey",
  "Catch a Fire - Bob Marley", "Exodus - Bob Marley", "Kaya - Bob Marley",
  "Discovery - Daft Punk", "Random Access Memories - Daft Punk",
  "Automatic for the People - R.E.M.", "Out of Time - R.E.M.",
  "Doolittle - Pixies", "Surfer Rosa - Pixies",
  "Dummy - Portishead", "Mezzanine - Massive Attack",
  "Unknown Pleasures - Joy Division", "Closer - Joy Division",
  "The Queen Is Dead - The Smiths", "Meat Is Murder - The Smiths",
  "Toys in the Attic - Aerosmith", "Get a Grip - Aerosmith", "Pump - Aerosmith",
  "Piano Man - Billy Joel", "The Stranger - Billy Joel", "52nd Street - Billy Joel",
  "Face Value - Phil Collins", "...But Seriously - Phil Collins",
  "Straight Outta Compton - N.W.A",
  "Vol. 2... Hard Knock Life - Jay-Z", "The Black Album - Jay-Z",
  "808s & Heartbreak - Kanye West", "Yeezus - Kanye West", "Donda - Kanye West",
  "To Pimp a Butterfly - Kendrick Lamar", "good kid, m.A.A.d city - Kendrick Lamar", "DAMN. - Kendrick Lamar", "Mr. Morale & The Big Steppers - Kendrick Lamar",
  "Channel Orange - Frank Ocean", "Blonde - Frank Ocean",
  "Take Care - Drake", "Nothing Was the Same - Drake", "Views - Drake", "Scorpion - Drake",
  "Astroworld - Travis Scott", "Rodeo - Travis Scott",
  "My Name Is - Eminem", "Curtain Call - Eminem",
  "After Hours - The Weeknd", "Starboy - The Weeknd", "Beauty Behind the Madness - The Weeknd",
  "Future Nostalgia - Dua Lipa", "Dua Lipa - Dua Lipa",
  "Fine Line - Harry Styles", "Harry's House - Harry Styles", "Harry Styles - Harry Styles",
  "When We All Fall Asleep, Where Do We Go? - Billie Eilish", "Happier Than Ever - Billie Eilish",
  "Divide - Ed Sheeran", "Multiply - Ed Sheeran", "Plus - Ed Sheeran", "Equals - Ed Sheeran",
  "Purpose - Justin Bieber", "Believe - Justin Bieber", "My World 2.0 - Justin Bieber",
  "In My Room - Frank Sinatra", "Songs for Swingin' Lovers! - Frank Sinatra",
  "Harvest - Neil Young", "After the Gold Rush - Neil Young",
  "Wide Open Spaces - Dixie Chicks", "Fly - Dixie Chicks",
  "Breathe - Faith Hill", "It Matters to Me - Faith Hill",
  "Up! - Shania Twain", "Greatest Hits - Shania Twain",
  "The Chase - Garth Brooks", "Double Live - Garth Brooks",
  "Laundry Service - Shakira", "She Wolf - Shakira",
  "Grandes Exitos - Ricky Martin", "Ricky Martin - Ricky Martin",
  "Justified - Justin Timberlake", "FutureSex/LoveSounds - Justin Timberlake", "The 20/20 Experience - Justin Timberlake",
  "Stripped - Christina Aguilera", "Back to Basics - Christina Aguilera",
  "FutureSex/LoveSounds - Justin Timberlake",
  "Speak Now - Taylor Swift", "evermore - Taylor Swift", "The Tortured Poets Department - Taylor Swift",
  "Cowboy Carter - Beyonce", "B'Day - Beyonce", "4 - Beyonce",
  "AM - Arctic Monkeys", "Whatever People Say I Am, That's What I'm Not - Arctic Monkeys",
  "Is This It - The Strokes", "Room on Fire - The Strokes",
  "Hot Fuss - The Killers", "Sam's Town - The Killers",
  "Songs About Jane - Maroon 5", "V - Maroon 5",
  "Lungs - Florence and the Machine", "Ceremonials - Florence and the Machine",
  "Night Visions - Imagine Dragons", "Smoke + Mirrors - Imagine Dragons",
  "Blurryface - Twenty One Pilots", "Trench - Twenty One Pilots",
  "A Fever You Can't Sweat Out - Panic! at the Disco",
  "American Beauty/American Psycho - Fall Out Boy", "From Under the Cork Tree - Fall Out Boy",
  "The Black Parade - My Chemical Romance", "Three Cheers for Sweet Revenge - My Chemical Romance",
  "Enema of the State - Blink-182", "Take Off Your Pants and Jacket - Blink-182",
  "Toxicity - System of a Down", "Mezmerize - System of a Down",
  "Meteora - Linkin Park", "Minutes to Midnight - Linkin Park",
  "Tragic Kingdom - No Doubt", "Rock Steady - No Doubt",
  "Fallen - Evanescence", "The Open Door - Evanescence",
  "By the Way - Red Hot Chili Peppers", "Californication - Red Hot Chili Peppers", "Stadium Arcadium - Red Hot Chili Peppers", "Blood Sugar Sex Magik - Red Hot Chili Peppers",
  "Morning Glory - Oasis", "Definitely Maybe - Oasis", "Be Here Now - Oasis",
  "Parklife - Blur", "The Great Escape - Blur", "13 - Blur",
  "Origin of Symmetry - Muse", "Absolution - Muse", "Black Holes and Revelations - Muse",
  "The Suburbs - Arcade Fire", "Funeral - Arcade Fire", "Neon Bible - Arcade Fire",
  "In the Aeroplane Over the Sea - Neutral Milk Hotel",
  "Transatlanticism - Death Cab for Cutie", "Plans - Death Cab for Cutie",
  "Graceland - Paul Simon", "Still Crazy After All These Years - Paul Simon",
  "Rumour Has It - Adele", "Set Fire to the Rain - Adele",
  "The Slim Shady LP - Eminem", "Music to Be Murdered By - Eminem",
  "Animals - Pink Floyd", "Meddle - Pink Floyd", "Atom Heart Mother - Pink Floyd",
  "Let It Be - The Beatles", "Revolver - The Beatles", "Rubber Soul - The Beatles", "Help! - The Beatles", "A Hard Day's Night - The Beatles",
  "Beggars Banquet - Rolling Stones", "Tattoo You - Rolling Stones", "Aftermath - Rolling Stones",
  "Pet Sounds - The Beach Boys", "Surfin' U.S.A. - The Beach Boys",
  "Nevermind the Bollocks - Sex Pistols", "London Calling - The Clash",
  "Parallel Lines - Blondie", "Eat to the Beat - Blondie",
  "Synchronicity - The Police", "Ghost in the Machine - The Police", "Reggatta de Blanc - The Police",
  "Violator - Depeche Mode", "Music for the Masses - Depeche Mode",
  "Disintegration - The Cure", "Kiss Me, Kiss Me, Kiss Me - The Cure",
  "The Head on the Door - The Cure", "Wish - The Cure",
  "So - Peter Gabriel", "Us - Peter Gabriel",
  "War - U2", "The Unforgettable Fire - U2", "Rattle and Hum - U2", "Zooropa - U2", "Pop - U2", "All That You Can't Leave Behind - U2",
  "Play - Moby", "Oxygene - Jean-Michel Jarre",
  "Buena Vista Social Club - Buena Vista Social Club",
  "Getz/Gilberto - Stan Getz", "Time Out - Dave Brubeck Quartet",
  "Thriller 25 - Michael Jackson", "Invincible - Michael Jackson",
  "In Utero - Nirvana", "MTV Unplugged in New York - Nirvana",
  "Superunknown - Soundgarden", "Badmotorfinger - Soundgarden",
  "Dirt - Alice in Chains", "Jar of Flies - Alice in Chains",
  "Core - Stone Temple Pilots", "Purple - Stone Temple Pilots",
  "Evil Empire - Rage Against the Machine", "Rage Against the Machine - Rage Against the Machine",
  "Siamese Dream - Smashing Pumpkins", "Mellon Collie and the Infinite Sadness - Smashing Pumpkins",
  "August and Everything After - Counting Crows",
  "Weezer (Blue Album) - Weezer", "Pinkerton - Weezer",
  "Sixteen Stone - Bush", "Razorblade Suitcase - Bush",
  "Throwing Copper - Live", "Secret Samadhi - Live",
  "No Need to Argue - The Cranberries", "Everybody Else Is Doing It - The Cranberries",
  "Alanis Unplugged - Alanis Morissette", "Supposed Former Infatuation Junkie - Alanis Morissette",
];
