// ~550 cuisine names for autocomplete hints
// Includes all 100 answers + every other plausible national/regional cuisine
export const bestCuisinesWorldHints: string[] = [
  // Top 100 (the actual answers)
  "Italian", "Greek", "Peruvian", "Portuguese", "Spanish",
  "Japanese", "Turkish", "Chinese", "French", "Indonesian",
  "Mexican", "Serbian", "Indian", "Polish", "American",
  "Vietnamese", "Brazilian", "Croatian", "Korean", "Lebanese",
  "Georgian", "Hungarian", "Colombian", "Thai", "Filipino",
  "Argentinian", "German", "Russian", "Malaysian", "Moroccan",
  "Romanian", "Chilean", "Czech", "South African", "Bulgarian",
  "Austrian", "Palestinian", "Egyptian", "Ethiopian", "Canadian",
  "Tunisian", "Iranian", "Ukrainian", "Lithuanian", "Syrian",
  "Algerian", "Dutch", "Saudi", "Ecuadorian", "English",
  "Swedish", "Bosnian and Herzegovinian", "Macedonian", "Venezuelan",
  "Danish", "Trinidadian", "Nicaraguan", "Puerto Rican", "Libyan",
  "Bengali", "Australian", "Sri Lankan", "Finnish", "Jordanian",
  "Bolivian", "Norwegian", "Azerbaijani", "Belgian", "Cuban",
  "Swiss", "Iraqi", "Uruguayan", "Pakistani", "Afghan",
  "Slovak", "Eritrean", "Albanian", "Scottish", "Belarusian",
  "Irish", "Haitian", "Dominican", "Paraguayan", "Slovenian",
  "Costa Rican", "Bahamian", "Armenian", "Latvian", "Estonian",
  "Singaporean", "Montenegrin", "Guatemalan", "Israeli", "Maltese",
  "Nigerian", "Lao", "Kenyan", "Kazakhstani", "Qatari", "Cypriot",

  // ==================== EUROPE (not in top 100) ====================
  "Welsh", "Icelandic", "Luxembourgish", "Monégasque",
  "Andorran", "Liechtensteiner", "San Marinese",
  "Basque", "Catalan", "Galician", "Andalusian",
  "Sicilian", "Sardinian", "Neapolitan", "Tuscan",
  "Venetian", "Piedmontese", "Lombardian", "Emilian",
  "Provençal", "Alsatian", "Breton", "Norman", "Corsican",
  "Burgundian", "Lyonnaise",
  "Bavarian", "Swabian", "Saxon", "Rhineland",
  "Flemish", "Walloon",
  "Cretan", "Thessalian", "Cycladic",
  "Transylvanian", "Moldovan",
  "Dalmatian", "Istrian", "Slavonian",
  "Kosovar", "Kosovan",

  // ==================== ASIA (not in top 100) ====================
  "Taiwanese", "Tibetan", "Uyghur", "Cantonese",
  "Sichuan", "Hunanese", "Shanghainese", "Fujian",
  "Hakka", "Teochew", "Hokkien", "Dongbei",
  "Mongolian", "North Korean",
  "Okinawan", "Hokkaido",
  "Burmese", "Cambodian", "Bruneian", "Timorese",
  "Nepali", "Bhutanese", "Maldivian",
  "Uzbek", "Turkmen", "Kyrgyz", "Tajik",
  "Emirati", "Kuwaiti", "Bahraini", "Omani", "Yemeni",
  "Kurdish", "Druze", "Assyrian",
  "Goan", "Kashmiri", "Punjabi", "Rajasthani",
  "Gujarati", "Maharashtrian", "Hyderabadi", "Chettinad",
  "Kerala", "Tamil", "Andhra", "Bengali (Indian)",
  "Awadhi", "Mughlai", "Lucknowi", "Bihari",
  "Odia", "Assamese", "Manipuri", "Naga",
  "Sindhi", "Balochi", "Pashtun",

  // ==================== AFRICA (not in top 100) ====================
  "Ghanaian", "Senegalese", "Cameroonian", "Ivorian",
  "Malian", "Burkinabè", "Togolese", "Beninese",
  "Nigerien", "Guinean", "Sierra Leonean", "Liberian",
  "Gambian", "Cape Verdean",
  "Congolese", "Rwandan", "Burundian", "Ugandan",
  "Tanzanian", "Mozambican", "Zimbabwean", "Zambian",
  "Malawian", "Malagasy", "Mauritian", "Seychellois",
  "Somali", "Djiboutian", "Sudanese", "South Sudanese",
  "Angolan", "Namibian", "Botswanan", "Swazi",
  "Lesotho", "Comorian",

  // ==================== AMERICAS (not in top 100) ====================
  "Jamaican", "Barbadian", "Guyanese", "Surinamese",
  "Belizean", "Honduran", "Panamanian", "Salvadoran",
  "Bermudian", "Curaçaoan", "Aruban",
  "Antiguan", "Vincentian", "Grenadian", "Lucian",
  "Cajun", "Creole", "Tex-Mex", "Southern American",
  "New England", "Southwestern American", "Hawaiian",
  "Oaxacan", "Yucatecan", "Jalisciense", "Poblano",
  "Veracruzano", "Norteño",
  "Bahian", "Mineiro", "Gaúcho", "Amazonian",
  "Patagonian",

  // ==================== OCEANIA (not in top 100) ====================
  "New Zealand", "Fijian", "Samoan", "Tongan",
  "Papua New Guinean", "Polynesian", "Melanesian",
  "Micronesian", "Aboriginal Australian",

  // ==================== REGIONAL/STYLE CUISINES ====================
  "Mediterranean", "Nordic", "Scandinavian", "Baltic",
  "Balkan", "Caucasian", "Central Asian", "East Asian",
  "Southeast Asian", "South Asian", "Middle Eastern",
  "North African", "West African", "East African",
  "Southern African", "Caribbean", "Central American",
  "Pacific Islander",
  "Levantine", "Mesopotamian", "Persian",
  "Maghreb", "Berber", "Bedouin",
  "Creole (Louisiana)", "Acadian",
  "Indo-Chinese", "Peranakan", "Nonya",
  "Eurasian", "Fusion", "Pan-Asian",
  "Latin American", "Iberian",
  "Alpine", "Coastal", "Island",

  // ==================== ADDITIONAL NATIONAL (small states) ====================
  "Sammarinese", "Vatican", "Faroese", "Greenlandic",
  "Caymanian", "Turks and Caicos",
  "Guamanian", "Saipanese",

  // ==================== MORE AFRICAN ====================
  "Congolese (DRC)", "Gabonese", "Equatorial Guinean",
  "São Toméan", "Chadian", "Central African",
  "Swazi (Eswatini)", "Basotho", "Réunionese",

  // ==================== MORE ASIAN ====================
  "Macanese", "Hong Kong", "Zhejiang", "Yunnan",
  "Xinjiang", "Guizhou", "Jiangsu", "Anhui",
  "Henan", "Shandong", "Hubei", "Guangxi",
  "Korean (North)", "Ryukyuan",
  "Malay (Peninsular)", "Bornean", "Javanese", "Balinese",
  "Sumatran", "Sulawesi", "Minangkabau", "Sundanese",
  "Betawi", "Manado",
  "Visayan", "Bicolano", "Ilocano", "Kapampangan",
  "Thai (Northern)", "Thai (Southern)", "Thai (Isan)",
  "Lanna", "Isaan",

  // ==================== MORE EUROPEAN ====================
  "Cornish", "Yorkshire", "Norfolk",
  "Aragonese", "Asturian", "Canarian", "Valencian",
  "Extremaduran", "Castilian", "Murcian", "Manchego",
  "Apulian", "Calabrian", "Ligurian", "Umbrian",
  "Abruzzese", "Marchigiano", "Friulian", "Trentino",
  "Dauphine", "Gascon", "Basque (French)", "Savoyard",
  "Périgord", "Languedoc", "Picard", "Auvergne",
  "Westphalian", "Franconian", "Brandenburg", "Thuringian",
  "Hessian", "Baden", "Palatinate", "Holstein",
  "Frisian", "Tyrolean", "Carinthian", "Styrian",
  "Voivodinian", "Transylvanian (Romanian)", "Wallachian",
  "Silesian", "Pomeranian", "Masurian", "Greater Poland",
  "Galician (Eastern European)", "Podlachian",
  "Karelian", "Sámi", "Ålandic",
  "Scanian", "Gotlandic",
  "Jutlandic", "Zealand (Danish)", "Bornholmsk",
  "Trøndelag", "Northern Norwegian",

  // ==================== MORE AMERICAS ====================
  "Peruvian (Amazonian)", "Peruvian (Coastal)", "Peruvian (Andean)",
  "Mexican (Baja)", "Mexican (Chiapas)", "Mexican (Guerrero)",
  "Mexican (Michoacán)", "Mexican (Sinaloa)", "Mexican (Sonora)",
  "Brazilian (Northeastern)", "Brazilian (Southern)", "Brazilian (Amazonian)",
  "Brazilian (Minas Gerais)", "Brazilian (São Paulo)", "Brazilian (Pará)",
  "Nikkei (Japanese-Peruvian)", "Chifa (Chinese-Peruvian)",
  "Novo Latino", "Pan-Latin",
  "Midwestern American", "Pacific Northwest",
  "Californian", "Soul Food", "Appalachian",
  "Pennsylvania Dutch", "Low Country", "Southwestern",
  "Deep South", "Gulf Coast", "Chesapeake Bay",
  "Native American", "First Nations", "Inuit",
  "Québécois", "Maritime Canadian", "Prairie Canadian",
  "British Columbian",
  "Jamaican Chinese", "Indo-Caribbean", "Afro-Caribbean",
  "Virgin Islands", "Martinican", "Guadeloupean",
  "French Guianese", "Saint Lucian",

  // ==================== MORE MIDDLE EAST/CENTRAL ASIA ====================
  "Yazidi", "Chaldean", "Circassian",
  "Kurdish (Iraqi)", "Kurdish (Turkish)", "Kurdish (Iranian)",

  // ==================== DIASPORA/FUSION CUISINES ====================
  "Chindian", "Anglo-Indian", "British-Indian",
  "Chinese-American", "Japanese-American",
  "Korean-American", "Vietnamese-American",
  "Italian-American", "Greek-American",
  "Mexican-American", "Cuban-American",
  "Jewish (Ashkenazi)", "Jewish (Sephardic)", "Jewish (Mizrahi)",
  "Pan-African", "New Nordic", "Modern Australian",
  "Pacific Rim", "Nuevo Latino", "Contemporary European",

  // ==================== ADDITIONAL ====================
  "Corfiot", "Pontian Greek", "Smyrna",
  "Abruzzese (Abruzzo)", "Romagnol",
  "Walloon (Belgian)", "Franche-Comté",
  "Aragonese (Spanish)", "Navarrese",
  "Madeiran", "Azorean",
  "Balearic", "Majorcan",
  "Karelian (Russian)",
];

