export const bestSellingToysHints: string[] = [
  // ===== TOP 100 ANSWERS =====
  "LEGO", "Barbie", "Hot Wheels", "Play-Doh", "Rubik's Cube",
  "Monopoly", "Scrabble", "Chess", "Uno", "Checkers",
  "Yo-Yo", "Slinky", "Frisbee", "Silly Putty", "Mr. Potato Head",
  "Trivial Pursuit", "Battleship", "G.I. Joe", "Star Wars action figures", "Transformers",
  "Cabbage Patch Kids", "Tamagotchi", "Beanie Babies", "He-Man", "Barbie Dreamhouse",
  "Nerf", "Super Soaker", "Fisher-Price Little People", "Tonka Trucks", "Lincoln Logs",
  "Candy Land", "Chutes and Ladders", "Clue", "Risk", "Sorry!",
  "Jenga", "Connect Four", "Operation", "Hungry Hungry Hippos", "Mousetrap",
  "Twister", "Pictionary", "Boggle", "Yahtzee", "Guess Who?",
  "Etch A Sketch", "Lite-Brite", "Easy-Bake Oven", "Spirograph", "View-Master",
  "Furby", "Tickle Me Elmo", "Teenage Mutant Ninja Turtles", "My Little Pony", "Care Bears",
  "Stretch Armstrong", "Simon", "Magna Doodle", "Jumbo Jet", "Rock 'Em Sock 'Em Robots",
  "Pokémon Trading Cards", "Magic: The Gathering", "Game Boy", "Nintendo DS", "Wii",
  "K'Nex", "Erector Set", "Tinkertoy", "Brio", "Thomas the Tank Engine",
  "American Girl Dolls", "Bratz Dolls", "Rainbow Loom", "Fidget Spinner", "Rubik's Snake",
  "Stratego", "Catan", "Ticket to Ride", "Pandemic",
  "Dungeons & Dragons", "Pokemon Red/Blue", "Pogo Stick", "Hacky Sack", "Hula Hoop",
  "Crayola Crayons", "Playmobil", "Puppy Surprise", "Baby Alive", "Pound Puppies",
  "Ker-Plunk", "Trouble", "Perfection", "Topple", "Aggravation",

  // ===== CLASSIC TOYS =====
  "Teddy Bear", "Jacks", "Marbles", "Jump Rope", "Kite",
  "Spinning Top", "Wooden Blocks", "Pull Toy", "Baby Rattle", "Rocking Horse",
  "Dollhouse", "Toy Train", "Tin Soldier", "Balsa Wood Airplane", "Paper Airplane",
  "Boomerang", "Paddle Ball", "Croquet Set", "Badminton Set", "Volleyball",
  "Basketball Hoop", "Soccer Ball", "Football", "Baseball Glove", "Skateboard",
  "Roller Skates", "Bicycle", "Tricycle", "Big Wheel", "Wagon",
  "Sandbox", "Swing Set", "Slide", "See-Saw", "Monkey Bars",
  "Doll", "Stuffed Animal", "Puppet", "Hand Puppet", "Sock Puppet",
  "Marionette", "Jack-in-the-Box", "Music Box", "Kaleidoscope", "Snow Globe",

  // ===== ACTION FIGURES & CHARACTER TOYS =====
  "Spider-Man action figure", "Batman action figure", "Superman action figure", "Iron Man action figure",
  "Captain America action figure", "Thor action figure", "Hulk action figure", "Wonder Woman action figure",
  "Luke Skywalker", "Darth Vader", "Han Solo", "Princess Leia", "Yoda",
  "Optimus Prime", "Bumblebee", "Megatron",
  "Skeletor", "Man-At-Arms", "Teela",
  "Duke", "Snake Eyes", "Storm Shadow", "Cobra Commander",
  "Raphael", "Leonardo", "Michelangelo", "Donatello",
  "Buzz Lightyear", "Woody", "Forky", "Rex the Dinosaur",
  "Pikachu toy", "Charizard toy", "Mewtwo toy",
  "Dragon Ball Z figures", "Naruto figures", "One Piece figures",
  "WWE action figures", "Power Rangers action figures", "Mighty Morphin Power Rangers",
  "Ghostbusters toys", "Back to the Future toys", "Indiana Jones toys",
  "Masters of the Universe figures", "ThunderCats toys", "Voltron",

  // ===== DOLLS =====
  "Skipper", "Ken doll", "Midge doll", "Christie doll",
  "Raggedy Ann", "Raggedy Andy", "Holly Hobbie", "Strawberry Shortcake",
  "Polly Pocket", "Groovy Girls", "Disney Princess dolls", "Frozen Elsa doll",
  "Monster High dolls", "Ever After High", "LOL Surprise dolls",
  "Lalaloopsy", "Jem and the Holograms doll", "Jem doll",
  "My Scene dolls", "Moxie Girlz", "Project MC2",
  "Baby Born", "Baby Annabel", "Bitty Baby",
  "Chatty Cathy", "Tiny Tears", "Betsy Wetsy",

  // ===== BUILDING & CONSTRUCTION =====
  "LEGO Technic", "LEGO Star Wars", "LEGO City", "LEGO Harry Potter", "LEGO Creator",
  "LEGO Ninjago", "LEGO Minecraft", "LEGO Duplo",
  "Mega Bloks", "Mega Construx",
  "Meccano", "Capsela", "Snap Circuits",
  "Marble Run", "Gravitrax",

  // ===== BOARD GAMES =====
  "Backgammon", "Mah-jongg", "Go", "Othello", "Chinese Checkers",
  "Parcheesi", "Ludo", "Snakes and Ladders",
  "Taboo", "Cranium", "Cards Against Humanity", "What Do You Meme?",
  "Codenames", "Carcassonne", "7 Wonders",
  "Pandemic Legacy", "Gloomhaven", "Azul", "Wingspan", "Spirit Island",
  "Scythe", "Root", "Terraforming Mars", "Agricola", "Power Grid",
  "Dominion", "Deck of cards", "Poker", "Solitaire", "Hearts",
  "Rummy", "Gin Rummy", "Canasta", "Bridge", "Cribbage",
  "Phase 10", "Skip-Bo", "Sequence", "Blink", "Spot It!",
  "Exploding Kittens", "Throw Throw Burrito", "Sushi Go", "Taco Cat Goat Cheese Pizza",
  "Coup", "Love Letter", "Bang!", "Resistance", "Werewolf",
  "Balderdash", "Scattergories", "Outburst", "Headbandz", "Telestrations",
  "Wink", "Pit", "Sleeping Queens", "Bohnanza", "No Thanks!",
  "Cluedo", "Game of Life", "Payday", "Hotel", "Mastermind", "Othello/Reversi", "Hex", "Blokus", "Quoridor",
  "Settlers of Catan Jr.", "Hive", "Quarto", "Patchwork",
  "Just One", "Dixit", "Mysterium", "Betrayal at House on the Hill",
  "Pandemic: Reign of Cthulhu", "Arkham Horror",

  // ===== CARD GAMES =====
  "Old Maid", "War", "Go Fish", "Crazy Eights", "Snap",
  "Concentration", "Memory", "Pokemon starter deck", "Yu-Gi-Oh! starter deck",
  "Dragonball Super Card Game", "Flesh and Blood", "KeyForge",
  "Sorcery: Contested Realm",

  // ===== ELECTRONIC TOYS =====
  "Speak & Spell", "Leapfrog LeapPad", "V-Tech toys", "Hatchimals", "Fingerlings",
  "Zhu Zhu Pets", "FurReal Friends", "Neopets", "Webkinz",
  "Tamiya RC cars", "Air Hogs", "Radio Flyer",
  "Game & Watch", "Tiger Electronics", "Game Gear", "Sega Game Gear",
  "Virtual Boy", "Atari Lynx", "Neo Geo Pocket",
  "Leapster", "Nintendo 64 portable",
  "Nintendo Switch", "PlayStation", "Xbox",
  "Atari 2600", "ColecoVision", "Intellivision", "Odyssey",
  "NES", "Super Nintendo", "Sega Genesis", "Sega Saturn", "Dreamcast",
  "Nintendo 64", "GameCube", "PlayStation 2", "PlayStation 3", "Xbox 360",
  "3DS", "PSP", "PS Vita",
  "Alexa Kids", "Echo Dot Kids",
  "Drone", "RC Helicopter", "Hexbug", "Anki Overdrive",
  "Cozmo robot", "Sphero", "Ozobot",

  // ===== OUTDOOR TOYS =====
  "Water Gun", "Slip 'N Slide", "Sprinkler", "Wading Pool", "Sand Castle Mold",
  "Double Dutch", "Stilts", "Lawn Darts", "Croquet", "Bocce Ball",
  "Frisbee Golf disc", "Noodle (pool)", "Squirt Gun", "Stomp Rocket",
  "Backyard Bowling", "Cornhole", "Ring Toss", "Horseshoes",

  // ===== CRAFT & SCIENCE TOYS =====
  "Shrinky Dinks", "Paint by Numbers", "Perler Beads", "Loom Bands",
  "Friendship Bracelets kit", "Bead Loom", "Macrame kit",
  "Science Kit", "Chemistry Set", "Ant Farm", "Sea Monkeys", "Crystal Growing Kit",
  "Telescope", "Microscope", "Planetarium Projector",
  "Pottery Wheel", "Mold-A-Rama", "Pin Art",
  "3D Pen", "Soap Making Kit", "Tie-Dye Kit", "Candle Making Kit",

  // ===== PUZZLES & BRAINTEASERS =====
  "Jigsaw Puzzle", "1000-piece puzzle", "3D Puzzle", "Metal Puzzle", "Wooden Puzzle",
  "Tower of Hanoi", "Soma Cube", "Tangram", "Pentominos",
  "Sudoku", "Word Search", "Crossword Puzzle", "Cryptogram",
  "Rubik's Revenge", "Pyraminx", "Skewb", "Megaminx", "Mirror Cube",

  // ===== PARTY GAMES =====
  "Pin the Tail on the Donkey", "Musical Chairs", "Duck Duck Goose", "Simon Says",
  "Freeze Dance", "Charades", "Telephone", "Truth or Dare",
  "Never Have I Ever", "Two Truths and a Lie",
  "Escape Room in a Box", "Clue: Harry Potter",
  "Wits & Wagers", "Trivial Pursuit: Pop Culture",

  // ===== EDUCATIONAL TOYS =====
  "Flash Cards", "Alphabet Blocks", "Abacus", "Counting Rods", "Number Line",
  "LeapFrog Fridge Phonics", "VTech Baby Walker", "Fisher-Price Laugh & Learn",
  "LeapPad Ultra", "MagnaTiles", "Cuisenaire Rods",
  "Montessori Puzzle", "Stacking Rings", "Shape Sorter", "Nesting Cups",
  "Globe", "World Map Puzzle", "US States Puzzle",
  "Human Body Model", "Solar System Model", "DNA Model",
  "Coding Robot", "Dash Robot", "Cubetto",

  // ===== NOVELTY & FAD TOYS =====
  "Pet Rock", "Mood Ring", "Magic 8-Ball", "Whoopee Cushion", "Joy Buzzer",
  "Slap Bracelet", "Pogs", "Troll Dolls", "Mighty Morphin Power Coin",
  "Micro Machines", "Mighty Max", "Polly Pocket (original)",
  "Sky Dancers", "Dragon Flyz", "Biker Mice from Mars",
  "Crossfire game", "Laser Tag", "Paintball gun",
  "Cap Gun", "Cowboy Hat", "Sheriff's Badge",
  "Kaleidograph",
  "Chia Pet", "Grow Capsules",
  "Creepy Crawlers", "Glow in the Dark Stars",
  "Stretch Monster", "Slime",
  "Pop-Up Pirate", "Buckaroo",
  "Gak", "Floam",
  "Mighty Beanz", "Beyblades", "Bakugan",
  "Digimon", "Tamagotchi Plus", "Giga Pet",
  "Silly Bands", "Livestrong bracelet",
  "Fidget Cube", "Pop It", "Kinetic Sand", "Kinetic Rock",
  "Moon Sand", "Sand Art",
  "Light-Up Sneakers", "Light-Up Yo-Yo",
  "Snap Bracelets", "Shutter Shades",
  "Nintendo Wii",
  "Apples to Apples",
];
