// ~500 notable/best-selling video games of all time
export const bestSellingVideoGamesHints: string[] = [
  // Top 100 (the actual answers)
  "Minecraft", "Grand Theft Auto V", "Tetris", "Wii Sports", "PUBG: Battlegrounds",
  "Mario Kart 8", "Super Smash Bros. Ultimate", "Red Dead Redemption 2", "Overwatch", "The Witcher 3",
  "Pac-Man", "Human: Fall Flat", "Super Mario Bros.", "Pokémon Red/Blue", "Mario Kart Wii",
  "The Legend of Zelda: Breath of the Wild", "Call of Duty: Modern Warfare", "Terraria", "New Super Mario Bros.", "Wii Sports Resort",
  "New Super Mario Bros. Wii", "The Elder Scrolls V: Skyrim", "Diablo III", "Call of Duty: Modern Warfare 3", "Pokémon Gold/Silver",
  "Duck Hunt", "The Legend of Zelda: Tears of the Kingdom", "Wii Fit", "Wii Fit Plus", "Call of Duty: Black Ops",
  "Call of Duty: Black Ops II", "Animal Crossing: New Horizons", "Call of Duty: Modern Warfare 2", "FIFA 18", "Kinect Adventures!",
  "Grand Theft Auto: San Andreas", "Super Mario World", "Call of Duty: WWII", "Pokémon Sword/Shield", "Pokémon Diamond/Pearl",
  "Super Mario Odyssey", "Pokémon Sun/Moon", "Pokémon Ruby/Sapphire", "Super Mario Bros. 3", "Grand Theft Auto IV",
  "New Super Mario Bros. 2", "Borderlands 2", "The Last of Us", "Spider-Man", "FIFA 17",
  "Halo: Combat Evolved", "Call of Duty: Ghosts", "Nintendogs", "Pokémon Scarlet/Violet", "Battlefield 1",
  "Star Wars Battlefront", "Call of Duty: Black Ops III", "The Legend of Zelda: Ocarina of Time", "Lego Star Wars: The Complete Saga", "Need for Speed: Most Wanted",
  "Brain Age", "Super Smash Bros. Brawl", "Pokémon X/Y", "Just Dance 2017", "FIFA 16",
  "God of War", "Uncharted 4", "Final Fantasy VII", "Resident Evil 5", "Mario Party 8",
  "Sonic the Hedgehog", "Battlefield 3", "NBA 2K21", "Pokémon Black/White", "Super Mario 64",
  "Halo 3", "Mario Kart DS", "Halo 2", "Gran Turismo 3", "Splatoon 2",
  "Donkey Kong Country", "Fable II", "Guitar Hero III", "Assassin's Creed II", "Crash Bandicoot",
  "Pokémon Let's Go Pikachu/Eevee", "The Sims 3", "Destiny", "Gran Turismo", "Metal Gear Solid",
  "Tomb Raider II", "Mortal Kombat 11", "Super Mario Galaxy", "Gran Turismo 4", "Forza Horizon 5",
  "Tom Clancy's The Division", "Halo Reach", "FIFA 15", "Just Dance 3", "Resident Evil 2",
  // 101–200
  "Fortnite", "League of Legends", "Valorant", "Apex Legends", "Counter-Strike 2",
  "Roblox", "Genshin Impact", "Among Us", "Fall Guys", "Rocket League",
  "FIFA 19", "FIFA 20", "FIFA 21", "FIFA 22", "FIFA 23",
  "EA Sports FC 24", "Madden NFL 23", "Madden NFL 24", "NBA 2K22", "NBA 2K23",
  "NBA 2K24", "MLB The Show 23", "NHL 24",
  "Call of Duty: Vanguard", "Call of Duty: Cold War", "Call of Duty: Modern Warfare II",
  "Call of Duty: Modern Warfare III", "Call of Duty: Advanced Warfare", "Call of Duty: Infinite Warfare",
  "Call of Duty: Black Ops 4", "Call of Duty 4: Modern Warfare",
  "Battlefield 4", "Battlefield V", "Battlefield 2042", "Battlefield: Bad Company 2",
  "Halo Infinite", "Halo 4", "Halo 5: Guardians", "Halo Wars", "Halo: ODST",
  "Destiny 2", "The Division 2", "Tom Clancy's Rainbow Six Siege", "Tom Clancy's Ghost Recon Wildlands",
  "Assassin's Creed", "Assassin's Creed III", "Assassin's Creed IV: Black Flag",
  "Assassin's Creed Unity", "Assassin's Creed Syndicate", "Assassin's Creed Origins",
  "Assassin's Creed Odyssey", "Assassin's Creed Valhalla", "Assassin's Creed Mirage",
  "Far Cry 3", "Far Cry 4", "Far Cry 5", "Far Cry 6",
  "Watch Dogs", "Watch Dogs 2", "Watch Dogs: Legion",
  "The Crew", "The Crew 2", "Steep",
  "Just Dance 2018", "Just Dance 2019", "Just Dance 2020", "Just Dance 2021", "Just Dance 2022",
  "The Sims", "The Sims 2", "The Sims 4", "SimCity", "SimCity 2000",
  "Civilization V", "Civilization VI", "Civilization IV",
  // 201–300
  "Red Dead Redemption", "Grand Theft Auto III", "Grand Theft Auto: Vice City",
  "Grand Theft Auto: Liberty City Stories", "Grand Theft Auto: Vice City Stories",
  "Bully", "L.A. Noire", "Max Payne 3",
  "The Last of Us Part II", "Uncharted 2", "Uncharted 3", "Uncharted: Drake's Fortune",
  "God of War: Ragnarök", "God of War III", "God of War II",
  "Horizon Zero Dawn", "Horizon Forbidden West", "Days Gone", "Ghost of Tsushima",
  "Spider-Man: Miles Morales", "Marvel's Spider-Man 2", "Ratchet & Clank: Rift Apart",
  "Returnal", "Demon's Souls", "Astro's Playroom",
  "Bloodborne", "Dark Souls", "Dark Souls II", "Dark Souls III",
  "Elden Ring", "Sekiro: Shadows Die Twice", "Armored Core VI",
  "Final Fantasy XV", "Final Fantasy XVI", "Final Fantasy XIV",
  "Final Fantasy X", "Final Fantasy VIII", "Final Fantasy VI",
  "Kingdom Hearts", "Kingdom Hearts II", "Kingdom Hearts III",
  "Dragon Quest XI", "Dragon Quest VIII", "Chrono Trigger",
  "Persona 5", "Persona 5 Royal", "Persona 4 Golden", "Persona 3",
  "Ni no Kuni", "Tales of Arise", "Xenoblade Chronicles",
  "Xenoblade Chronicles 2", "Xenoblade Chronicles 3",
  "Fire Emblem: Three Houses", "Fire Emblem Engage", "Fire Emblem Awakening",
  "Pokémon Legends: Arceus", "Pokémon Brilliant Diamond/Shining Pearl",
  "Pokémon HeartGold/SoulSilver", "Pokémon FireRed/LeafGreen",
  "Pokémon Emerald", "Pokémon Platinum", "Pokémon Black 2/White 2",
  "Pokémon Ultra Sun/Ultra Moon", "Pokémon Mystery Dungeon",
  "Super Mario Maker", "Super Mario Maker 2", "Super Mario 3D World",
  "Super Mario 3D All-Stars", "Super Mario Galaxy 2",
  "Mario Party Superstars", "Mario Party 9", "Mario Party 10",
  "Luigi's Mansion 3", "Luigi's Mansion", "Luigi's Mansion: Dark Moon",
  "Kirby and the Forgotten Land", "Kirby Star Allies", "Kirby's Dream Land",
  "Metroid Dread", "Metroid Prime", "Metroid Prime Remastered",
  "Splatoon 3", "Splatoon", "Arms",
  "Animal Crossing: New Leaf", "Animal Crossing: Wild World", "Animal Crossing",
  // 301–400
  "The Legend of Zelda: Skyward Sword", "The Legend of Zelda: Twilight Princess",
  "The Legend of Zelda: The Wind Waker", "The Legend of Zelda: Majora's Mask",
  "The Legend of Zelda: A Link to the Past", "The Legend of Zelda: Link's Awakening",
  "The Legend of Zelda", "Hyrule Warriors: Age of Calamity",
  "Donkey Kong Country 2", "Donkey Kong Country Returns", "Donkey Kong Country: Tropical Freeze",
  "Yoshi's Island", "Yoshi's Crafted World",
  "Star Fox 64", "F-Zero", "Pikmin", "Pikmin 3", "Pikmin 4",
  "Sonic the Hedgehog 2", "Sonic the Hedgehog 3", "Sonic Adventure",
  "Sonic Adventure 2", "Sonic Mania", "Sonic Frontiers", "Sonic Generations",
  "Crash Bandicoot 2", "Crash Bandicoot 3: Warped", "Crash Bandicoot N. Sane Trilogy",
  "Crash Team Racing", "Crash Bandicoot 4",
  "Spyro the Dragon", "Spyro 2: Ripto's Rage", "Spyro: Year of the Dragon",
  "Spyro Reignited Trilogy",
  "Jak and Daxter", "Jak II", "Jak 3",
  "Ratchet & Clank", "Ratchet & Clank: Going Commando", "Ratchet & Clank: Up Your Arsenal",
  "Sly Cooper", "Sly 2: Band of Thieves", "Sly 3: Honor Among Thieves",
  "LittleBigPlanet", "LittleBigPlanet 2", "LittleBigPlanet 3",
  "Stardew Valley", "Hollow Knight", "Celeste", "Cuphead", "Hades",
  "Hades II", "Dead Cells", "Slay the Spire", "Undertale", "Deltarune",
  "Shovel Knight", "Ori and the Blind Forest", "Ori and the Will of the Wisps",
  "Subnautica", "No Man's Sky", "Valheim", "Satisfactory", "Factorio",
  "Rust", "ARK: Survival Evolved", "DayZ", "7 Days to Die",
  "Left 4 Dead", "Left 4 Dead 2", "Back 4 Blood",
  "Dead by Daylight", "Phasmophobia", "Lethal Company",
  "Palworld", "V Rising", "Enshrouded",
  // 401–500+
  "World of Warcraft", "StarCraft", "StarCraft II", "Warcraft III",
  "Diablo II", "Diablo IV", "Diablo Immortal",
  "Overwatch 2", "Hearthstone",
  "Counter-Strike: Global Offensive", "Counter-Strike: Source", "Counter-Strike",
  "Half-Life", "Half-Life 2", "Half-Life: Alyx", "Portal", "Portal 2",
  "Team Fortress 2", "Garry's Mod", "Dota 2",
  "Age of Empires II", "Age of Empires IV", "Age of Mythology",
  "Total War: Warhammer III", "Total War: Three Kingdoms",
  "XCOM 2", "XCOM: Enemy Unknown",
  "Fallout 4", "Fallout 3", "Fallout: New Vegas", "Fallout 76",
  "The Elder Scrolls IV: Oblivion", "The Elder Scrolls III: Morrowind",
  "Starfield", "Dishonored", "Dishonored 2", "Prey",
  "Doom", "Doom Eternal", "Wolfenstein: The New Order", "Wolfenstein II",
  "BioShock", "BioShock Infinite", "BioShock 2",
  "Mass Effect", "Mass Effect 2", "Mass Effect 3", "Mass Effect: Legendary Edition",
  "Dragon Age: Origins", "Dragon Age: Inquisition", "Dragon Age: The Veilguard",
  "Baldur's Gate 3", "Divinity: Original Sin 2",
  "The Outer Worlds", "Pillars of Eternity",
  "Cyberpunk 2077", "CD Projekt Red",
  "Metal Gear Solid 2", "Metal Gear Solid 3", "Metal Gear Solid 4", "Metal Gear Solid V",
  "Death Stranding", "Silent Hill 2",
  "Resident Evil 4", "Resident Evil Village", "Resident Evil 7",
  "Resident Evil 3", "Resident Evil 6",
  "Devil May Cry 5", "Devil May Cry 3", "Devil May Cry",
  "Monster Hunter: World", "Monster Hunter Rise",
  "Street Fighter 6", "Street Fighter V", "Street Fighter II",
  "Tekken 8", "Tekken 7", "Tekken 3",
  "Mortal Kombat X", "Mortal Kombat 9", "Mortal Kombat 1",
  "Super Smash Bros. Melee", "Super Smash Bros.",
  "Dragon Ball FighterZ", "Dragon Ball Z: Kakarot",
  "Naruto Shippuden: Ultimate Ninja Storm 4",
  "FIFA 14", "FIFA 13", "FIFA 12", "FIFA 11", "FIFA 10",
  "Pro Evolution Soccer 2021", "eFootball",
  "Need for Speed: Heat", "Need for Speed: Payback", "Need for Speed: Underground 2",
  "Forza Horizon 4", "Forza Horizon 3", "Forza Motorsport",
  "Gran Turismo 5", "Gran Turismo 6", "Gran Turismo 7",
  "Mario Kart 7", "Mario Kart: Double Dash", "Mario Kart: Super Circuit",
  "Burnout Paradise", "Burnout 3: Takedown",
  "Wipeout", "F-Zero GX",
  // 500+ additional titles
  "It Takes Two", "A Way Out", "Brothers: A Tale of Two Sons",
  "Outer Wilds", "The Witness", "Braid", "Fez", "Limbo", "Inside",
  "Little Nightmares", "Little Nightmares II", "Spiritfarer",
  "Journey", "Abzû", "Flower", "Shadow of the Colossus",
  "The Last Guardian", "ICO", "Okami",
  "Bayonetta", "Bayonetta 2", "Bayonetta 3",
  "Astral Chain", "Wonderful 101", "NieR: Automata", "NieR Replicant",
  "Control", "Alan Wake", "Alan Wake 2", "Quantum Break", "Max Payne", "Max Payne 2",
  "Psychonauts", "Psychonauts 2", "Brutal Legend",
  "Titanfall", "Titanfall 2", "Anthem",
  "Star Wars Jedi: Fallen Order", "Star Wars Jedi: Survivor",
  "Star Wars: Knights of the Old Republic", "Star Wars Battlefront II",
  "Lego Star Wars: The Skywalker Saga", "Lego Marvel Super Heroes",
  "Lego Batman", "Lego Harry Potter", "Lego City Undercover",
  "Plants vs. Zombies", "Plants vs. Zombies: Garden Warfare",
  "Bejeweled", "Peggle", "Zuma",
  "Angry Birds", "Angry Birds 2", "Cut the Rope", "Fruit Ninja", "Temple Run",
  "Candy Crush Saga", "Clash of Clans", "Clash Royale",
  "Pokémon GO", "Mario Kart Tour", "Fire Emblem Heroes",
  "Animal Crossing: Pocket Camp", "Dr. Mario",
  "Wii Party", "Wii Music", "Wii Play",
  "Ring Fit Adventure", "Nintendo Switch Sports", "1-2-Switch",
  "Xenoblade Chronicles: Definitive Edition",
  "Donkey Kong", "Donkey Kong Jr.", "Donkey Kong 64",
  "Banjo-Kazooie", "Banjo-Tooie", "Conker's Bad Fur Day",
  "GoldenEye 007", "Perfect Dark",
  "The Legend of Zelda: A Link Between Worlds",
  "The Legend of Zelda: Phantom Hourglass", "The Legend of Zelda: Spirit Tracks",
  "The Legend of Zelda: The Minish Cap",
  "Mega Man", "Mega Man 2", "Mega Man X", "Mega Man 11",
  "Castlevania: Symphony of the Night", "Castlevania",
  "Contra", "Contra III", "Metal Slug",
  "Double Dragon", "Streets of Rage 2", "Golden Axe", "Final Fight",
];
