export const collegeTeamsHints: string[] = [
  "Alabama", "Arkansas", "Auburn", "Florida", "Georgia",
  "Kentucky", "LSU", "Mississippi State", "Missouri", "Ole Miss",
  "Oklahoma", "South Carolina", "Tennessee", "Texas", "Texas A&M",
  "Vanderbilt", "Arizona", "Arizona State", "California", "Colorado",
  "Oregon", "Oregon State", "Stanford", "UCLA", "USC",
  "Utah", "Washington", "Washington State", "Boston College", "Clemson",
  "Duke", "Florida State", "Georgia Tech", "Louisville", "Miami",
  "North Carolina", "NC State", "Notre Dame", "Pittsburgh", "Syracuse",
  "Virginia", "Virginia Tech", "Wake Forest", "Illinois", "Indiana",
  "Iowa", "Maryland", "Michigan", "Michigan State", "Minnesota",
  "Nebraska", "Northwestern", "Ohio State", "Penn State", "Purdue",
  "Rutgers", "Wisconsin", "Baylor", "BYU", "Cincinnati",
  "Houston", "Iowa State", "Kansas", "Kansas State", "Oklahoma State",
  "TCU", "Texas Tech", "UCF", "West Virginia", "Air Force",
  "Army", "Boise State", "Colorado State", "Fresno State", "Hawaii",
  "Navy", "Nevada", "New Mexico", "San Diego State", "San Jose State",
  "UNLV", "Utah State", "Wyoming", "Appalachian State", "Coastal Carolina",
  "Georgia Southern", "Georgia State", "James Madison", "Louisiana", "Louisiana Monroe",
  "Marshall", "Old Dominion", "South Alabama", "Southern Miss", "Texas State",
  "Troy", "Akron", "Ball State", "Bowling Green", "Buffalo",
  "Central Michigan", "Eastern Michigan", "Kent State", "Miami (OH)", "Northern Illinois",
  "Ohio", "Toledo", "Western Michigan", "Charlotte", "East Carolina",
  "FAU", "FIU", "Memphis", "Middle Tennessee", "North Texas",
  "Rice", "SMU", "South Florida", "Temple", "Tulane",
  "Tulsa", "UAB", "UTEP", "UTSA", "Western Kentucky",
  "Arkansas Pine Bluff", "Gonzaga", "Saint Mary's", "Creighton", "Dayton",
  "Davidson", "Duquesne", "Fordham", "George Mason", "Georgetown",
  "George Washington", "La Salle", "Loyola Chicago", "Marquette", "Rhode Island",
  "Richmond", "Saint Joseph's", "Saint Louis", "Saint Peter's", "UMass",
  "VCU", "Villanova", "Xavier", "Bucknell", "Colgate",
  "Lafayette", "Lehigh", "Loyola Maryland", "Boston University", "Albany",
  "Binghamton", "Hartford", "UMBC", "New Hampshire", "Stony Brook",
  "Vermont", "Maine", "Pepperdine", "Loyola Marymount", "San Francisco",
  "Santa Clara", "Portland", "Pacific", "Seton Hall", "Providence",
  "St. John's", "DePaul", "Butler", "Detroit", "Milwaukee",
  "Wright State", "Oakland", "Cleveland State", "Green Bay", "IUPUI",
  "Youngstown State", "Northern Kentucky", "Robert Morris", "Central Connecticut", "LIU",
  "Sacred Heart", "Wagner", "Mount St. Mary's", "Quinnipiac", "Saint Francis Brooklyn",
  "Saint Francis PA", "FDU", "Bryant", "Delaware", "Drexel",
  "Elon", "Hofstra", "Northeastern", "Towson", "William & Mary",
  "Charleston", "UNC Wilmington", "Alabama A&M", "Alabama State", "Alcorn State",
  "Bethune-Cookman", "Florida A&M", "Grambling State", "Jackson State", "Mississippi Valley State",
  "Prairie View A&M", "Southern", "Texas Southern", "Norfolk State", "Hampton",
  "Howard", "Morgan State", "North Carolina A&T", "North Carolina Central", "Delaware State",
  "Coppin State", "Maryland Eastern Shore", "South Carolina State", "Savannah State", "American",
  "Holy Cross", "Wichita State", "North Dakota State", "South Dakota State", "Denver",
  "Omaha", "Oral Roberts", "Western Illinois", "South Dakota", "North Dakota",
  "Central Arkansas", "Northern Colorado", "Sacramento State", "Eastern Washington", "Idaho",
  "Idaho State", "Montana", "Montana State", "Portland State", "Weber State",
  "Northern Arizona", "Cal Poly", "Cal State Bakersfield", "Cal State Fullerton", "Cal State Northridge",
  "Long Beach State", "UC Davis", "UC Irvine", "UC Riverside", "UC San Diego",
  "UC Santa Barbara", "Florida Atlantic", "Florida Gulf Coast", "Jacksonville", "Kennesaw State",
  "Liberty", "Lipscomb", "Mercer", "North Alabama", "North Florida",
  "Stetson", "Bellarmine", "Eastern Kentucky", "Jacksonville State", "Murray State",
  "Morehead State", "SEMO", "SIU Edwardsville", "Southeastern Louisiana", "Tennessee State",
  "Tennessee Tech", "UT Martin", "Austin Peay", "Belmont", "Eastern Illinois",
  "Louisiana Tech", "ECU", "UConn", "Princeton", "Harvard",
  "Yale", "Columbia", "Cornell", "Dartmouth", "Penn",
  "Brown", "Ivy League", "Patriot League", "MAAC", "NEC",
];
