// Top 100 most valuable companies by market cap, plus 400+ other well-known public companies
export const companyValuationHints: string[] = [
  // Top 100
  "Apple", "Microsoft", "NVIDIA", "Alphabet", "Amazon",
  "Saudi Aramco", "Meta Platforms", "Berkshire Hathaway", "TSMC", "Broadcom",
  "Tesla", "Eli Lilly", "Walmart", "JPMorgan Chase", "Visa",
  "Novo Nordisk", "UnitedHealth Group", "Mastercard", "Costco", "Johnson & Johnson",
  "Procter & Gamble", "Oracle", "Home Depot", "Netflix", "Samsung",
  "AbbVie", "Coca-Cola", "Bank of America", "Salesforce", "ASML",
  "International Holdings", "AMD", "Merck", "Adobe", "Toyota",
  "Chevron", "ExxonMobil", "Tencent", "ICBC", "Thermo Fisher",
  "McDonald's", "AstraZeneca", "Cisco", "T-Mobile", "Alibaba",
  "PepsiCo", "Accenture", "Morgan Stanley", "Abbott Laboratories", "Wells Fargo",
  "Texas Instruments", "LVMH", "Linde", "Goldman Sachs", "Caterpillar",
  "ServiceNow", "Philip Morris", "General Electric", "Danaher", "Intuitive Surgical",
  "Amgen", "Disney", "Deere & Company", "Nike", "Qualcomm",
  "Uber", "RTX Corporation", "Honeywell", "Booking Holdings", "BlackRock",
  "American Express", "IBM", "S&P Global", "Starbucks", "Union Pacific",
  "Lockheed Martin", "PDD Holdings", "Applied Materials", "Verizon", "TJX Companies",
  "Automatic Data Processing", "Boston Scientific", "Marsh & McLennan", "Prologis", "NextEra Energy",
  "Medtronic", "Pfizer", "ConocoPhillips", "Lam Research", "Gilead Sciences",
  "Chubb", "Citigroup", "Progressive", "Analog Devices", "CME Group",
  "Sherwin-Williams", "KLA Corporation", "Spotify", "Target", "Colgate-Palmolive",
  // Beyond top 100
  "Ford", "GM", "General Motors", "Intel", "AT&T", "Comcast", "Sony", "Nintendo",
  "Dell", "HP", "Hewlett-Packard", "Snap", "Pinterest", "Shopify", "Square", "Block",
  "Palantir", "Snowflake", "CrowdStrike", "Datadog", "Zoom", "PayPal", "eBay",
  "Airbnb", "DoorDash", "Instacart", "Lyft", "Twitter", "X", "Reddit", "Roblox",
  "Unity", "EA", "Electronic Arts", "Activision", "Take-Two", "Warner Bros",
  "Paramount", "Fox", "ViacomCBS", "NBC Universal", "Live Nation", "Roku", "Peloton",
  "FedEx", "UPS", "Boeing", "Airbus", "Raytheon", "Northrop Grumman",
  "General Dynamics", "BAE Systems", "3M", "Dow", "DuPont", "BASF", "Bayer",
  "Siemens", "SAP", "Volkswagen", "BMW", "Mercedes-Benz", "Ferrari", "Porsche",
  "Stellantis", "Honda", "Hyundai", "Kia", "BYD", "Rivian", "Lucid", "NIO",
  "Li Auto", "Fisker", "Carnival", "Royal Caribbean", "Delta", "United Airlines",
  "American Airlines", "Southwest", "JetBlue", "Spirit Airlines", "Hilton", "Marriott",
  "Wyndham", "Expedia", "TripAdvisor", "Zillow", "Redfin", "Coinbase", "Robinhood",
  "SoFi", "Affirm", "Stripe", "Plaid", "Chime", "Fidelity", "Charles Schwab",
  "TD Ameritrade", "E*Trade", "Vanguard", "State Street", "BNY Mellon",
  "Deutsche Bank", "HSBC", "Barclays", "Credit Suisse", "UBS", "BNP Paribas",
  "Societe Generale", "ING", "Santander", "Itau Unibanco", "NuBank", "Grab",
  "Sea Limited", "Shopee", "MercadoLibre", "Reliance Industries", "Infosys", "TCS",
  "Wipro", "HCL Technologies", "Adani Group", "HDFC Bank", "ICICI Bank",
  "State Bank of India", "Baidu", "JD.com", "Meituan", "NetEase", "Xiaomi",
  "Lenovo", "Huawei", "ByteDance", "DiDi", "SenseTime", "Ant Group", "Ping An",
  "China Construction Bank", "Agricultural Bank of China", "Bank of China",
  "PetroChina", "Sinopec", "China Mobile", "SK Hynix", "LG",
  "Hyundai Motor", "POSCO", "KB Financial", "SoftBank", "Mitsubishi", "Mitsui",
  "Fast Retailing", "Keyence", "Shin-Etsu", "Daikin", "Recruit Holdings",
  "Nestle", "Roche", "Novartis", "Zurich Insurance", "ABB", "Swatch",
  "LafargeHolcim", "Richemont", "Sika", "Adecco", "Hermes", "L'Oreal",
  "TotalEnergies", "Sanofi", "Air Liquide", "Schneider Electric",
  "Dassault Systemes", "Pernod Ricard", "Danone", "Kering", "Engie",
  "Unilever", "Shell", "BP", "GlaxoSmithKline", "Diageo", "Rio Tinto",
  "BHP", "Anglo American", "Glencore", "AB InBev", "Heineken", "Volvo",
  "Ericsson", "Atlas Copco", "Investor AB", "SEB", "Nordea", "Novo Holdings",
  "Maersk", "Carlsberg", "Vestas", "Orsted", "Equinor", "DNB", "Yara", "Neste",
  "Nokia", "Kone", "UPM", "Sampo", "Fortum", "Gazprom", "Sberbank", "Lukoil",
  "Rosneft", "Vale", "Petrobras", "Ambev", "BTG Pactual", "WEG", "JBS",
  "Magazine Luiza", "Natura", "Kroger", "Walgreens", "CVS", "Anthem", "Elevance",
  "Cigna", "Humana", "Centene", "Cardinal Health", "McKesson", "AmerisourceBergen",
  "Regeneron", "Vertex", "Moderna", "BioNTech", "Illumina", "Agilent",
  "Edwards Lifesciences", "Stryker", "Zimmer Biomet", "Becton Dickinson", "Baxter",
  "ResMed", "Hologic", "Align Technology", "DexCom", "IDEXX", "Veeva Systems",
  "Splunk", "Workday", "Twilio", "Okta", "ZScaler", "Fortinet",
  "Palo Alto Networks", "SentinelOne", "Carbon Black", "CyberArk", "Elastic",
  "MongoDB", "Confluent", "HashiCorp", "GitLab", "JFrog", "Atlassian", "HubSpot",
  "Zendesk", "Freshworks", "DocuSign", "Monday.com", "Asana", "Notion", "Airtable",
  "Figma", "Canva", "UIPath", "Automation Anywhere", "C3.ai", "Databricks",
  "Teradata", "Cloudera", "MapR", "Nutanix", "Pure Storage", "NetApp",
  "Western Digital", "Seagate", "Micron", "Marvell", "Wolfspeed",
  "ON Semiconductor", "NXP", "STMicroelectronics", "Infineon", "Renesas",
  "MediaTek", "Realtek", "Arm Holdings", "Synopsys", "Cadence", "Ansys",
  "MathWorks", "Autodesk", "PTC", "Siemens Digital", "Dassault", "Bentley Systems",
  "Trimble", "Hexagon", "Garmin", "TomTom", "Fitbit", "GoPro", "Sonos", "Bose",
  "Harman", "Bang & Olufsen", "JBL", "Logitech", "Corsair", "Razer",
  "SteelSeries", "HyperX", "Kraft Heinz", "Mondelez", "General Mills",
  "Kellogg's", "Hershey", "Campbell Soup", "Conagra", "McCormick",
  "Tyson Foods", "Hormel", "Clorox", "Church & Dwight", "Estee Lauder",
  "Bath & Body Works", "Tapestry", "Capri Holdings", "Ralph Lauren", "PVH",
  "Hanesbrands", "VF Corporation", "Lululemon", "Under Armour", "Skechers",
  "Crocs", "On Running", "New Balance", "Puma", "Adidas",
  "T. Rowe Price", "Franklin Templeton", "Invesco", "Legg Mason", "Janus Henderson",
  "Northern Trust", "Raymond James", "Stifel", "Edward Jones", "Jefferies",
  "Lazard", "Evercore", "Moelis", "Houlihan Lokey", "Piper Sandler",
  "KeyCorp", "Regions Financial", "Zions Bancorporation", "Comerica", "M&T Bank",
  "Fifth Third Bancorp", "Huntington Bancshares", "Citizens Financial",
  "Synchrony Financial", "Ally Financial", "Capital One", "Discover",
  "American Tower", "Crown Castle", "Digital Realty", "Equinix", "SBA Communications",
  "Simon Property Group", "Realty Income", "Public Storage", "Welltower",
  "Ventas", "AvalonBay", "Equity Residential", "Essex Property Trust",
  "Duke Energy", "Southern Company", "Dominion Energy", "Exelon", "AES",
  "Entergy", "FirstEnergy", "Eversource", "CenterPoint", "WEC Energy",
  "Xcel Energy", "Consolidated Edison", "Ameren", "Atmos Energy", "NiSource",
];
