// All ~195 sovereign states — every country is a plausible guess
export const countriesColdestHints: string[] = [
  "India", "China", "United States", "Indonesia", "Pakistan",
  "Nigeria", "Brazil", "Bangladesh", "Russia", "Ethiopia",
  "Mexico", "Japan", "Philippines", "Egypt", "DR Congo",
  "Vietnam", "Iran", "Turkey", "Germany", "Thailand",
  "United Kingdom", "France", "Tanzania", "South Africa", "Italy",
  "Kenya", "Myanmar", "Colombia", "South Korea", "Sudan",
  "Uganda", "Spain", "Argentina", "Algeria", "Iraq",
  "Afghanistan", "Poland", "Canada", "Morocco", "Saudi Arabia",
  "Ukraine", "Uzbekistan", "Angola", "Peru", "Malaysia",
  "Mozambique", "Ghana", "Yemen", "Nepal", "Venezuela",
  "Madagascar", "Ivory Coast", "Cameroon", "Australia", "Niger",
  "North Korea", "Taiwan", "Mali", "Sri Lanka", "Burkina Faso",
  "Malawi", "Syria", "Chile", "Kazakhstan", "Zambia",
  "Romania", "Guatemala", "Ecuador", "Senegal", "Netherlands",
  "Chad", "Somalia", "Zimbabwe", "Cambodia", "Guinea",
  "Rwanda", "Benin", "Burundi", "Tunisia", "Bolivia",
  "Belgium", "Cuba", "South Sudan", "Haiti", "Dominican Republic",
  "Czech Republic", "Jordan", "Sweden", "Portugal", "Azerbaijan",
  "Greece", "Hungary", "Honduras", "Tajikistan", "United Arab Emirates",
  "Belarus", "Papua New Guinea", "Israel", "Austria", "Switzerland",
  // Beyond top 100
  "Togo", "Sierra Leone", "Laos", "Paraguay", "Libya",
  "Nicaragua", "Bulgaria", "Kyrgyzstan", "El Salvador", "Turkmenistan",
  "Singapore", "Denmark", "Finland", "Norway", "Slovakia",
  "Ireland", "Costa Rica", "Central African Republic", "New Zealand", "Palestine",
  "Liberia", "Oman", "Mauritania", "Panama", "Kuwait",
  "Croatia", "Moldova", "Georgia", "Eritrea", "Uruguay",
  "Mongolia", "Bosnia and Herzegovina", "Armenia", "Jamaica", "Qatar",
  "Albania", "Lithuania", "Namibia", "Botswana", "Gambia",
  "Gabon", "Lesotho", "Guinea-Bissau", "Slovenia", "North Macedonia",
  "Latvia", "Bahrain", "Equatorial Guinea", "Trinidad and Tobago", "Timor-Leste",
  "Estonia", "Mauritius", "Eswatini", "Djibouti", "Fiji",
  "Cyprus", "Comoros", "Guyana", "Bhutan", "Solomon Islands",
  "Luxembourg", "Montenegro", "Suriname", "Cabo Verde", "Malta",
  "Brunei", "Belize", "Bahamas", "Maldives", "Iceland",
  "Vanuatu", "Barbados", "São Tomé and Príncipe", "Samoa", "Saint Lucia",
  "Kiribati", "Grenada", "Tonga", "Micronesia", "Saint Vincent and the Grenadines",
  "Antigua and Barbuda", "Seychelles", "Andorra", "Dominica", "Marshall Islands",
  "Saint Kitts and Nevis", "Liechtenstein", "Monaco", "San Marino", "Palau",
  "Tuvalu", "Nauru", "Vatican City",
];
