// All ~195 sovereign states — every country is a plausible guess
export const countriesByLifeExpectancyHints: string[] = [
  "Japan", "South Korea", "Andorra", "Switzerland", "Australia",
  "Singapore", "Italy", "Spain", "France", "Norway",
  "Malta", "Sweden", "United Arab Emirates", "Iceland", "Canada",
  "Israel", "Ireland", "Qatar", "Portugal", "Luxembourg",
  "Netherlands", "Belgium", "New Zealand", "Austria", "Denmark",
  "Finland", "Greece", "Cyprus", "Slovenia", "Germany",
  "United Kingdom", "Bahrain", "Chile", "Maldives", "Costa Rica",
  "Taiwan", "Kuwait", "Oman", "Czech Republic", "Albania",
  "Panama", "United States", "Estonia", "Saudi Arabia", "Poland",
  "Croatia", "Slovakia", "Uruguay", "Cuba", "China",
  "Bosnia and Herzegovina", "Lebanon", "Jordan", "Peru", "Colombia",
  "Iran", "Antigua and Barbuda", "Sri Lanka", "Argentina", "North Macedonia",
  "Ecuador", "Turkey", "Montenegro", "Hungary", "Serbia",
  "Malaysia", "Tunisia", "Thailand", "Algeria", "Latvia",
  "Barbados", "Cape Verde", "Lithuania", "Romania", "Brazil",
  "Armenia", "Bulgaria", "Brunei", "Morocco", "Mexico",
  "Vietnam", "Nicaragua", "Georgia", "Libya", "Bahamas",
  "Seychelles", "Samoa", "Paraguay", "El Salvador", "Honduras",
  "Bangladesh", "Tonga", "Dominican Republic", "Grenada", "Fiji",
  "Uzbekistan", "Suriname", "Venezuela", "Indonesia", "Philippines",
  // Beyond top 100
  "Jamaica", "Trinidad and Tobago", "Guatemala", "Saint Lucia", "Belize",
  "Mongolia", "Egypt", "North Korea", "Kyrgyzstan", "Nepal",
  "Bolivia", "India", "Iraq", "Dominica", "Moldova",
  "Saint Vincent and the Grenadines", "Bhutan", "Kazakhstan", "Azerbaijan",
  "Russia", "Tajikistan", "Turkmenistan", "Saint Kitts and Nevis",
  "Pakistan", "Timor-Leste", "Micronesia", "Cambodia", "Guyana",
  "Laos", "Myanmar", "Haiti", "Gabon", "Papua New Guinea",
  "Mauritius", "Solomon Islands", "Comoros", "Vanuatu", "Nauru",
  "Palau", "Marshall Islands", "Kiribati", "Tuvalu",
  "South Africa", "Namibia", "Botswana", "Zimbabwe", "Eswatini",
  "Lesotho", "Kenya", "Tanzania", "Uganda", "Rwanda",
  "Burundi", "Ethiopia", "Eritrea", "Djibouti", "Somalia",
  "Sudan", "South Sudan", "DR Congo", "Congo", "Cameroon",
  "Nigeria", "Ghana", "Ivory Coast", "Senegal", "Mali",
  "Burkina Faso", "Niger", "Guinea", "Guinea-Bissau", "Gambia",
  "Sierra Leone", "Liberia", "Togo", "Benin", "Mauritania",
  "Madagascar", "Malawi", "Mozambique", "Zambia", "Angola",
  "Central African Republic", "Chad", "Equatorial Guinea",
  "Sao Tome and Principe", "San Marino", "Monaco",
  "Liechtenstein", "Vatican City", "Ukraine", "Belarus",
];
