// All countries from the World Happiness Report — every country is a plausible guess
export const countriesByHappinessHints: string[] = [
  "Finland", "Denmark", "Iceland", "Sweden", "Netherlands",
  "Costa Rica", "Norway", "Israel", "Luxembourg", "Mexico",
  "Australia", "New Zealand", "Switzerland", "Belgium", "Ireland",
  "Lithuania", "Austria", "Canada", "Slovenia", "Czech Republic",
  "United Arab Emirates", "Germany", "United Kingdom", "United States", "Belize",
  "Poland", "Taiwan", "Uruguay", "Kosovo", "Kuwait",
  "Serbia", "Saudi Arabia", "France", "Singapore", "Romania",
  "Brazil", "El Salvador", "Spain", "Estonia", "Italy",
  "Panama", "Argentina", "Kazakhstan", "Guatemala", "Chile",
  "Vietnam", "Nicaragua", "Malta", "Thailand", "Slovakia",
  "Latvia", "Oman", "Uzbekistan", "Paraguay", "Japan",
  "Bosnia and Herzegovina", "Philippines", "South Korea", "Bahrain", "Portugal",
  "Colombia", "Ecuador", "Honduras", "Malaysia", "Peru",
  "Russia", "Cyprus", "China", "Hungary", "Trinidad and Tobago",
  "Montenegro", "Croatia", "Jamaica", "Bolivia", "Kyrgyzstan",
  "Dominican Republic", "Mongolia", "Mauritius", "Libya", "Moldova",
  "Greece", "Venezuela", "Indonesia", "Algeria", "Bulgaria",
  "North Macedonia", "Armenia", "Hong Kong", "Albania", "Tajikistan",
  "Georgia", "Nepal", "Laos", "Turkey", "South Africa",
  "Mozambique", "Gabon", "Ivory Coast", "Iran", "Congo",
  // Beyond top 100
  "Iraq", "Guinea", "Namibia", "Cameroon", "Nigeria",
  "Azerbaijan", "Senegal", "Palestine", "Pakistan", "Niger",
  "Ukraine", "Morocco", "Tunisia", "Mauritania", "Kenya",
  "Uganda", "Gambia", "India", "Chad", "Burkina Faso",
  "Benin", "Somalia", "Mali", "Cambodia", "Ghana",
  "Myanmar", "Togo", "Jordan", "Liberia", "Madagascar",
  "Zambia", "Ethiopia", "Sri Lanka", "Bangladesh", "Egypt",
  "Tanzania", "Eswatini", "Lesotho", "Comoros", "Yemen",
  "DR Congo", "Botswana", "Zimbabwe", "Malawi", "Lebanon",
  "Sierra Leone", "Afghanistan",
  // Additional countries not in the report but plausible guesses
  "Syria", "Eritrea", "North Korea", "Cuba", "Haiti",
  "Bhutan", "Papua New Guinea", "Rwanda", "Burundi",
  "Central African Republic", "Sudan", "South Sudan",
  "Suriname", "Guyana", "Fiji", "Samoa", "Tonga",
  "Barbados", "Bahamas", "Antigua and Barbuda", "Grenada",
  "Saint Lucia", "Dominica", "Saint Kitts and Nevis",
  "Saint Vincent and the Grenadines", "Brunei", "Maldives",
  "Timor-Leste", "Djibouti", "Equatorial Guinea",
  "Angola", "Sao Tome and Principe",
];
