// All ~195 sovereign states — every country is a plausible guess
export const countriesByAreaHints: string[] = [
  // Top 100 by area
  "Russia", "Canada", "China", "United States", "Brazil",
  "Australia", "India", "Argentina", "Kazakhstan", "Algeria",
  "DR Congo", "Saudi Arabia", "Mexico", "Indonesia", "Sudan",
  "Libya", "Iran", "Mongolia", "Peru", "Chad",
  "Niger", "Angola", "Mali", "South Africa", "Colombia",
  "Ethiopia", "Bolivia", "Mauritania", "Egypt", "Tanzania",
  "Nigeria", "Venezuela", "Pakistan", "Namibia", "Mozambique",
  "Turkey", "Chile", "Zambia", "Myanmar", "Afghanistan",
  "South Sudan", "France", "Somalia", "Central African Republic", "Ukraine",
  "Madagascar", "Botswana", "Kenya", "Thailand", "Spain",
  "Turkmenistan", "Cameroon", "Papua New Guinea", "Yemen", "Sweden",
  "Uzbekistan", "Morocco", "Iraq", "Paraguay", "Zimbabwe",
  "Norway", "Japan", "Germany", "Republic of the Congo", "Finland",
  "Vietnam", "Malaysia", "Ivory Coast", "Poland", "Oman",
  "Italy", "Philippines", "Ecuador", "Burkina Faso", "New Zealand",
  "Gabon", "Guinea", "United Kingdom", "Uganda", "Ghana",
  "Romania", "Laos", "Guyana", "Belarus", "Kyrgyzstan",
  "Senegal", "Syria", "Cambodia", "Uruguay", "Suriname",
  "Tunisia", "Portugal", "Bangladesh", "Nepal", "Tajikistan",
  "Greece", "Nicaragua", "North Korea", "Malawi", "Eritrea",
  // Beyond top 100
  "Benin", "Honduras", "Liberia", "Bulgaria", "Cuba",
  "Guatemala", "Iceland", "South Korea", "Hungary", "Jordan",
  "Serbia", "Azerbaijan", "Austria", "United Arab Emirates",
  "Czech Republic", "Panama", "Sierra Leone", "Ireland", "Georgia",
  "Sri Lanka", "Lithuania", "Latvia", "Togo", "Croatia",
  "Bosnia and Herzegovina", "Costa Rica", "Slovakia", "Dominican Republic", "Estonia",
  "Denmark", "Netherlands", "Switzerland", "Bhutan", "Guinea-Bissau",
  "Moldova", "Belgium", "Lesotho", "Armenia", "Solomon Islands",
  "Albania", "Equatorial Guinea", "Burundi", "Haiti", "Rwanda",
  "North Macedonia", "Djibouti", "Belize", "Israel", "El Salvador",
  "Slovenia", "Fiji", "Kuwait", "Eswatini", "Timor-Leste",
  "Montenegro", "Bahamas", "Vanuatu", "Qatar", "The Gambia",
  "Jamaica", "Lebanon", "Cyprus", "Palestine", "Brunei",
  "Trinidad and Tobago", "Cape Verde", "Samoa", "Luxembourg", "Mauritius",
  "Comoros", "São Tomé and Príncipe", "Kiribati", "Bahrain", "Dominica",
  "Tonga", "Singapore", "Micronesia", "Saint Lucia", "Andorra",
  "Palau", "Seychelles", "Antigua and Barbuda", "Barbados", "Saint Vincent and the Grenadines",
  "Grenada", "Malta", "Maldives", "Saint Kitts and Nevis", "Marshall Islands",
  "Liechtenstein", "San Marino", "Tuvalu", "Nauru", "Vatican City",
  "Monaco",
];
