// All ~195 sovereign states — every country is a plausible guess
export const countriesByGdpHints: string[] = [
  "United States", "China", "Germany", "Japan", "India",
  "United Kingdom", "France", "Italy", "Brazil", "Canada",
  "Russia", "Mexico", "South Korea", "Australia", "Spain",
  "Indonesia", "Turkey", "Netherlands", "Saudi Arabia", "Switzerland",
  "Poland", "Argentina", "Taiwan", "Belgium", "Sweden",
  "Ireland", "Norway", "Austria", "Israel", "Thailand",
  "United Arab Emirates", "Nigeria", "Malaysia", "Singapore", "South Africa",
  "Egypt", "Philippines", "Vietnam", "Bangladesh", "Denmark",
  "Iran", "Colombia", "Pakistan", "Chile", "Czech Republic",
  "Finland", "Romania", "Portugal", "New Zealand", "Peru",
  "Iraq", "Greece", "Kazakhstan", "Qatar", "Algeria",
  "Hungary", "Kuwait", "Ethiopia", "Morocco", "Ukraine",
  "Cuba", "Ecuador", "Dominican Republic", "Kenya", "Puerto Rico",
  "Guatemala", "Oman", "Bulgaria", "Uzbekistan", "Angola",
  "Luxembourg", "Croatia", "Costa Rica", "Ivory Coast", "Slovakia",
  "Panama", "Sri Lanka", "Lithuania", "Tanzania", "Ghana",
  "Serbia", "Belarus", "Myanmar", "Uruguay", "DR Congo",
  "Azerbaijan", "Slovenia", "Cameroon", "Tunisia", "Bolivia",
  "Jordan", "Libya", "Paraguay", "Bahrain", "Latvia",
  "Nepal", "Uganda", "Estonia", "Cambodia", "Senegal",
  // Beyond top 100
  "Honduras", "Papua New Guinea", "Iceland",
  "Turkmenistan", "Mozambique", "Georgia", "Zambia",
  "North Korea", "Afghanistan", "Sudan", "Yemen",
  "Madagascar", "Niger", "Mali", "Burkina Faso",
  "Malawi", "Syria", "Chad", "Somalia", "Zimbabwe",
  "Guinea", "Rwanda", "Benin", "Burundi",
  "South Sudan", "Haiti",
  "Tajikistan", "Venezuela",
  "Albania", "Armenia", "Bosnia and Herzegovina",
  "North Macedonia", "Namibia", "Botswana", "Gambia",
  "Gabon", "Lesotho", "Guinea-Bissau",
  "Equatorial Guinea", "Trinidad and Tobago", "Timor-Leste",
  "Mauritius", "Eswatini", "Djibouti", "Fiji",
  "Cyprus", "Comoros", "Guyana", "Bhutan", "Solomon Islands",
  "Montenegro", "Suriname", "Cabo Verde", "Malta",
  "Brunei", "Belize", "Bahamas", "Maldives",
  "Vanuatu", "Barbados", "São Tomé and Príncipe", "Samoa", "Saint Lucia",
  "Kiribati", "Grenada", "Tonga", "Micronesia", "Saint Vincent and the Grenadines",
  "Antigua and Barbuda", "Seychelles", "Andorra", "Dominica", "Marshall Islands",
  "Saint Kitts and Nevis", "Liechtenstein", "Monaco", "San Marino", "Palau",
  "Tuvalu", "Nauru", "Vatican City",
  "El Salvador", "Nicaragua", "Kyrgyzstan",
  "Central African Republic", "Palestine", "Liberia", "Mauritania",
  "Moldova", "Eritrea", "Mongolia", "Jamaica",
  "Laos", "Sierra Leone", "Togo",
  "Hong Kong",
];
