export const f1DriversHints: string[] = [
  "Lewis Hamilton", "Michael Schumacher", "Sebastian Vettel", "Max Verstappen", "Alain Prost",
  "Kimi Raikkonen", "Fernando Alonso", "Ayrton Senna", "Rubens Barrichello", "Valtteri Bottas",
  "Nigel Mansell", "Jackie Stewart", "Nelson Piquet", "Niki Lauda", "Charles Leclerc",
  "Lando Norris", "Carlos Sainz", "George Russell", "Sergio Perez", "Daniel Ricciardo",
  "Jenson Button", "Mark Webber", "Felipe Massa", "David Coulthard", "Gerhard Berger",
  "Damon Hill", "Mika Hakkinen", "Jim Clark", "Graham Hill", "Juan Manuel Fangio",
  "Alberto Ascari", "Stirling Moss", "Jack Brabham", "John Surtees", "Phil Hill",
  "Jody Scheckter", "Emerson Fittipaldi", "Mario Andretti", "James Hunt", "Jacques Villeneuve",
  "Gilles Villeneuve", "Alan Jones", "Keke Rosberg", "Nico Rosberg", "Denny Hulme",
  "Jochen Rindt", "Ronnie Peterson", "Carlos Reutemann", "Rene Arnoux", "Patrick Tambay",
  "Didier Pironi", "Michele Alboreto", "Riccardo Patrese", "Jean Alesi", "Ralf Schumacher",
  "Heinz-Harald Frentzen", "Eddie Irvine", "Juan Pablo Montoya", "Giancarlo Fisichella", "Jarno Trulli",
  "Heikki Kovalainen", "Timo Glock", "Robert Kubica", "Nick Heidfeld", "Rosberg",
  "Oscar Piastri", "Pierre Gasly", "Esteban Ocon", "Lance Stroll", "Yuki Tsunoda",
  "Alexander Albon", "Zhou Guanyu", "Kevin Magnussen", "Nico Hulkenberg", "Guanyu Zhou",
  "Logan Sargeant", "Franco Colapinto", "Liam Lawson", "Oliver Bearman", "Isack Hadjar",
  "Gabriel Bortoleto", "Andrea Kimi Antonelli", "Jack Doohan", "Felipe Drugovich", "Kamui Kobayashi",
  "Vitaly Petrov", "Jaime Alguersuari", "Adrian Sutil", "Christijan Albers", "Pedro de la Rosa",
  "Vitantonio Liuzzi", "Sakon Yamamoto", "Luca Badoer", "Jerome d'Ambrosio", "Karun Chandhok",
  "Narain Karthikeyan", "Paul di Resta", "Max Chilton", "Marcus Ericsson", "Pascal Wehrlein",
  "Stoffel Vandoorne", "Brendon Hartley", "Romain Grosjean", "Stefano Modena", "Ivan Capelli",
  "Philippe Alliot", "Pierluigi Martini", "Eric Bernard", "Nicola Larini", "Olivier Panis",
  "Johnny Herbert", "Martin Brundle", "Derek Warwick", "Thierry Boutsen", "Stefan Johansson",
  "Eddie Cheever", "Marc Surer", "Elio de Angelis", "Patrick Depailler", "Clay Regazzoni",
  "Ricardo Rodriguez", "Pedro Rodriguez", "Lorenzo Bandini", "Wolfgang von Trips", "Tony Brooks",
  "Mike Hawthorn", "Peter Collins", "Luigi Musso", "Giuseppe Farina", "Luigi Fagioli",
  "Jose Froilan Gonzalez", "Felice Bonetto", "Onofre Marimon", "Piero Taruffi", "Peter Whitehead",
  "Louis Rosier", "Maurice Trintignant", "Robert Manzon", "Jean Behra", "Harry Schell",
  "Olivier Gendebien", "Willy Mairesse", "Jo Bonnier", "Innes Ireland", "Richie Ginther",
  "Dan Gurney", "Bruce McLaren", "Chris Amon", "Vincenzo Sospiri", "Taki Inoue",
  "Ukyo Katayama", "JJ Lehto", "Mika Salo", "Jos Verstappen", "Pedro Diniz",
  "Esteban Tuero", "Alex Wurz", "Toranosuke Takagi", "Ricardo Zonta", "Shinji Nakano",
  "Tarso Marques", "Gaston Mazzacane", "Yuji Ide", "Franck Montagny", "Tiago Monteiro",
  "Christian Klien", "Scott Speed", "Alex Yoong", "Takuma Sato", "Anthony Davidson",
  "Tonio Liuzzi", "Bruno Senna", "Lucas di Grassi", "Charles Pic", "Andre Lotterer",
  "Simona de Silvestro", "Marussia Team", "HRT", "Virgin Racing", "Caterham",
  "Manor Marussia", "Sauber", "Lotus", "Williams", "Force India",
  "Renault", "Alpine", "McLaren", "Mercedes", "Ferrari",
  "Red Bull Racing", "AlphaTauri", "Racing Bulls", "Haas", "Alfa Romeo",
  "Toro Rosso", "Jordan", "Minardi", "Brawn", "BMW Sauber",
  "Honda Racing", "Toyota", "Super Aguri", "Spyker", "Midland",
  "Prost", "Arrows", "Tyrrell", "Stewart", "BAR",
  "Benetton", "Ligier", "Osella", "ATS", "Brabham",
  "Lotus Racing", "March", "Shadow", "Hesketh", "Vittorio Brambilla",
  "Hans-Joachim Stuck", "Jochen Mass", "Peter Revson", "Tom Pryce", "Rolf Stommelen",
  "Tim Schenken", "John Watson",
];
