export const fastestAnimalsHints: string[] = [
  // === Top 50 (answers) ===
  "Peregrine Falcon", "Golden Eagle", "Gyrfalcon", "White-throated Needletail",
  "Common Swift", "Eurasian Hobby", "Mexican Free-tailed Bat", "Frigatebird",
  "Rock Dove", "Spur-winged Goose", "Red-breasted Merganser", "Black Marlin",
  "Canvasback", "Grey-headed Albatross", "Cheetah", "Sailfish",
  "Swordfish", "Horsefly", "Saker Falcon", "Anna's Hummingbird",
  "Pronghorn", "Springbok", "Quarter Horse", "Blue Wildebeest",
  "Thomson's Gazelle", "Lion", "Blackbuck", "Ostrich",
  "Yellowfin Tuna", "Shortfin Mako Shark", "African Wild Dog", "Jackrabbit",
  "Greyhound", "Kangaroo", "Coyote", "Onager",
  "Zebra", "Eland", "Tiger", "Common Dolphin",
  "Brown Hare", "Hyena", "Giraffe", "Orca",
  "Perentie", "Green Iguana", "Leatherback Sea Turtle", "Black Mamba",
  "Komodo Dragon", "Emu",
  // === Additional animal names (not in top 50) ===
  // -- Birds --
  "Bald Eagle", "Red-tailed Hawk", "Cooper's Hawk", "Sharp-shinned Hawk",
  "Northern Goshawk", "Merlin", "American Kestrel", "Prairie Falcon",
  "Lanner Falcon", "Aplomado Falcon", "Harpy Eagle", "Philippine Eagle",
  "Steller's Sea Eagle", "White-tailed Eagle", "Crowned Eagle", "Martial Eagle",
  "Secretary Bird", "Andean Condor", "California Condor", "Turkey Vulture",
  "Black Vulture", "King Vulture", "Barn Owl", "Snowy Owl",
  "Great Horned Owl", "Barred Owl", "Screech Owl", "Eagle Owl",
  "Tawny Owl", "Long-eared Owl", "Short-eared Owl", "Burrowing Owl",
  "Great Grey Owl", "Northern Hawk Owl", "Elf Owl", "Spotted Owl",
  "American Robin", "Blue Jay", "Northern Cardinal", "House Sparrow",
  "European Starling", "Common Grackle", "Red-winged Blackbird", "Baltimore Oriole",
  "Scarlet Tanager", "Cedar Waxwing", "Bohemian Waxwing", "American Goldfinch",
  "House Finch", "Purple Finch", "Evening Grosbeak", "Pine Siskin",
  "Common Redpoll", "Dark-eyed Junco", "White-throated Sparrow", "Song Sparrow",
  "Chipping Sparrow", "Fox Sparrow", "Swamp Sparrow", "Savannah Sparrow",
  "Eastern Bluebird", "Western Bluebird", "Mountain Bluebird", "Indigo Bunting",
  "Painted Bunting", "Lazuli Bunting", "Rose-breasted Grosbeak", "Black-headed Grosbeak",
  "Ruby-throated Hummingbird", "Rufous Hummingbird", "Calliope Hummingbird",
  "Broad-tailed Hummingbird", "Costa's Hummingbird", "Allen's Hummingbird",
  "Bee Hummingbird", "Sword-billed Hummingbird",
  "Chimney Swift", "Vaux's Swift", "Alpine Swift", "Fork-tailed Swift",
  "Barn Swallow", "Tree Swallow", "Cliff Swallow", "Purple Martin",
  "Bank Swallow", "Northern Rough-winged Swallow",
  "Peregrine Pigeon", "Mourning Dove", "White-winged Dove", "Eurasian Collared-Dove",
  "Common Ground Dove", "Band-tailed Pigeon",
  "Mallard", "Wood Duck", "Northern Pintail", "American Wigeon",
  "Green-winged Teal", "Blue-winged Teal", "Cinnamon Teal", "Northern Shoveler",
  "Gadwall", "Redhead", "Ring-necked Duck", "Greater Scaup",
  "Lesser Scaup", "Common Goldeneye", "Bufflehead", "Hooded Merganser",
  "Common Merganser", "Ruddy Duck", "Harlequin Duck",
  "Canada Goose", "Snow Goose", "Ross's Goose", "Brant",
  "Emperor Goose", "Barnacle Goose", "Greylag Goose", "Egyptian Goose",
  "Mute Swan", "Trumpeter Swan", "Tundra Swan", "Whooper Swan",
  "Black Swan", "Black-necked Swan",
  "Greater Roadrunner", "Ring-necked Pheasant", "Wild Turkey", "Ruffed Grouse",
  "Spruce Grouse", "Blue Grouse", "Greater Sage-Grouse", "Prairie Chicken",
  "Northern Bobwhite", "California Quail", "Gambel's Quail", "Mountain Quail",
  "Chukar Partridge", "Grey Partridge", "Guinea Fowl",
  "Emperor Penguin", "King Penguin", "Adelie Penguin", "Chinstrap Penguin",
  "Gentoo Penguin", "Rockhopper Penguin", "Macaroni Penguin", "African Penguin",
  "Magellanic Penguin", "Little Blue Penguin", "Galapagos Penguin",
  "Common Loon", "Red-throated Loon", "Pacific Loon",
  "Great Blue Heron", "Green Heron", "Black-crowned Night Heron",
  "Great Egret", "Snowy Egret", "Cattle Egret", "Reddish Egret",
  "American Bittern", "Least Bittern",
  "Roseate Spoonbill", "Wood Stork", "White Ibis", "Glossy Ibis",
  "Sandhill Crane", "Whooping Crane",
  "American Flamingo", "Greater Flamingo", "Chilean Flamingo", "Lesser Flamingo",
  "Brown Pelican", "American White Pelican", "Dalmatian Pelican",
  "Double-crested Cormorant", "Anhinga",
  "Osprey", "Northern Harrier", "Rough-legged Hawk", "Broad-winged Hawk",
  "Red-shouldered Hawk", "Swainson's Hawk", "Ferruginous Hawk", "Zone-tailed Hawk",
  "Harris's Hawk", "Mississippi Kite", "Swallow-tailed Kite", "White-tailed Kite",
  "Peafowl", "Peacock", "Golden Pheasant", "Lady Amherst's Pheasant",
  "Cassowary", "Southern Cassowary", "Kiwi", "Rhea", "Greater Rhea",
  "Toucan", "Keel-billed Toucan", "Toco Toucan",
  "Scarlet Macaw", "Blue-and-yellow Macaw", "Hyacinth Macaw", "Military Macaw",
  "African Grey Parrot", "Cockatiel", "Budgerigar", "Cockatoo",
  "Sulphur-crested Cockatoo", "Rose-breasted Cockatoo",
  "Common Raven", "American Crow", "Fish Crow", "Jackdaw",
  "Magpie", "Eurasian Magpie", "Clark's Nutcracker", "Pinyon Jay",
  "Great Spotted Woodpecker", "Pileated Woodpecker", "Downy Woodpecker",
  "Hairy Woodpecker", "Red-bellied Woodpecker", "Northern Flicker",
  "Ivory-billed Woodpecker", "Acorn Woodpecker",
  "Belted Kingfisher", "Common Kingfisher", "Kookaburra",
  "European Bee-eater", "Hoopoe", "Hornbill", "Great Hornbill",
  "Common Cuckoo", "Roadrunner",
  "Wandering Albatross", "Royal Albatross", "Black-browed Albatross",
  "Northern Fulmar", "Sooty Shearwater", "Manx Shearwater",
  "Arctic Tern", "Common Tern", "Royal Tern", "Least Tern",
  "Herring Gull", "Ring-billed Gull", "Laughing Gull", "Great Black-backed Gull",
  "Black Skimmer", "Atlantic Puffin", "Horned Puffin", "Tufted Puffin",
  "Common Murre", "Razorbill",
  // -- Mammals --
  "African Elephant", "Asian Elephant", "White Rhinoceros", "Black Rhinoceros",
  "Indian Rhinoceros", "Sumatran Rhinoceros", "Javan Rhinoceros",
  "Hippopotamus", "Pygmy Hippopotamus",
  "Domestic Cat", "Domestic Dog", "Gray Wolf", "Red Fox", "Arctic Fox",
  "Fennec Fox", "Kit Fox", "Swift Fox", "Gray Fox",
  "Red Wolf", "Ethiopian Wolf", "Maned Wolf", "Dhole", "African Wild Cat",
  "Leopard", "Snow Leopard", "Clouded Leopard", "Jaguar",
  "Cougar", "Mountain Lion", "Puma", "Florida Panther",
  "Cheetah King", "Bobcat", "Lynx", "Canadian Lynx", "Eurasian Lynx",
  "Iberian Lynx", "Caracal", "Serval", "Ocelot", "Margay", "Jaguarundi",
  "Fishing Cat", "Sand Cat", "Pallas's Cat", "Black-footed Cat",
  "Bengal Tiger", "Siberian Tiger", "Sumatran Tiger", "Indochinese Tiger",
  "Malayan Tiger", "South China Tiger",
  "African Lion", "Asiatic Lion",
  "Grizzly Bear", "Brown Bear", "Polar Bear", "American Black Bear",
  "Asian Black Bear", "Sun Bear", "Sloth Bear", "Spectacled Bear",
  "Giant Panda", "Red Panda",
  "Raccoon", "Coati", "Kinkajou", "Cacomistle", "Ring-tailed Cat",
  "River Otter", "Sea Otter", "Giant Otter", "European Otter",
  "Wolverine", "Fisher", "Marten", "Pine Marten", "American Mink",
  "European Mink", "Stoat", "Ermine", "Weasel", "Long-tailed Weasel",
  "Least Weasel", "Ferret", "Black-footed Ferret", "Honey Badger", "Badger",
  "American Badger", "European Badger",
  "Striped Skunk", "Spotted Skunk", "Hog-nosed Skunk",
  "Mongoose", "Meerkat", "Fossa",
  "Spotted Hyena", "Striped Hyena", "Brown Hyena", "Aardwolf",
  "Gorilla", "Western Gorilla", "Eastern Gorilla", "Mountain Gorilla",
  "Chimpanzee", "Bonobo", "Orangutan", "Bornean Orangutan", "Sumatran Orangutan",
  "Gibbon", "Siamang", "Mandrill", "Baboon", "Gelada",
  "Proboscis Monkey", "Howler Monkey", "Spider Monkey", "Capuchin Monkey",
  "Squirrel Monkey", "Tamarin", "Golden Lion Tamarin", "Marmoset",
  "Ring-tailed Lemur", "Aye-aye", "Sifaka", "Indri",
  "Tarsier", "Slow Loris", "Bushbaby",
  "White-tailed Deer", "Mule Deer", "Elk", "Moose", "Caribou", "Reindeer",
  "Red Deer", "Fallow Deer", "Roe Deer", "Sika Deer", "Axis Deer",
  "Sambar Deer", "Muntjac", "Chinese Water Deer", "Pere David's Deer",
  "Pronghorn Antelope", "Impala", "Gazelle", "Grant's Gazelle",
  "Dorcas Gazelle", "Gerenuk", "Hartebeest", "Topi", "Tsessebe",
  "Bongo", "Kudu", "Greater Kudu", "Lesser Kudu", "Nyala", "Sitatunga",
  "Waterbuck", "Reedbuck", "Oryx", "Arabian Oryx", "Gemsbok", "Scimitar Oryx",
  "Sable Antelope", "Roan Antelope", "Addax", "Dik-dik", "Klipspringer",
  "Steenbok", "Duiker", "Bushbuck", "Chamois", "Ibex", "Markhor",
  "Bighorn Sheep", "Dall Sheep", "Mountain Goat", "Domestic Goat",
  "Domestic Sheep", "Barbary Sheep", "Mouflon", "Muskox",
  "American Bison", "European Bison", "Cape Buffalo", "Water Buffalo",
  "Yak", "Gaur", "Banteng", "Anoa",
  "Domestic Cow", "Domestic Horse", "Thoroughbred", "Arabian Horse",
  "Donkey", "Mule", "Przewalski's Horse",
  "Plains Zebra", "Grevy's Zebra", "Mountain Zebra",
  "Wild Boar", "Domestic Pig", "Warthog", "Red River Hog",
  "Giant Forest Hog", "Babirusa", "Peccary", "Collared Peccary",
  "Tapir", "Brazilian Tapir", "Malayan Tapir", "Baird's Tapir",
  "Dromedary Camel", "Bactrian Camel", "Llama", "Alpaca",
  "Vicuna", "Guanaco",
  "Eastern Grey Kangaroo", "Red Kangaroo", "Western Grey Kangaroo",
  "Wallaroo", "Wallaby", "Tree Kangaroo", "Quokka",
  "Koala", "Wombat", "Common Wombat", "Tasmanian Devil",
  "Numbat", "Bilby", "Bandicoot", "Sugar Glider",
  "Virginia Opossum", "Platypus", "Echidna",
  "Eastern Cottontail", "Snowshoe Hare", "Arctic Hare",
  "European Rabbit", "Black-tailed Jackrabbit", "Antelope Jackrabbit",
  "Pika", "American Pika",
  "Eastern Gray Squirrel", "Red Squirrel", "Fox Squirrel",
  "Flying Squirrel", "Ground Squirrel", "Prairie Dog", "Chipmunk",
  "Woodchuck", "Groundhog", "Marmot", "Alpine Marmot",
  "Beaver", "North American Beaver", "European Beaver",
  "Porcupine", "North American Porcupine", "Cape Porcupine",
  "Capybara", "Guinea Pig", "Chinchilla", "Hamster",
  "Gerbil", "House Mouse", "Brown Rat", "Norway Rat",
  "Naked Mole Rat", "Muskrat", "Vole", "Lemming",
  "Aardvark", "Pangolin", "Giant Anteater", "Tamandua",
  "Armadillo", "Nine-banded Armadillo", "Giant Armadillo",
  "Three-toed Sloth", "Two-toed Sloth",
  "Hedgehog", "European Hedgehog", "Tenrec", "Shrew",
  "Star-nosed Mole", "European Mole",
  "Little Brown Bat", "Big Brown Bat", "Fruit Bat", "Flying Fox",
  "Vampire Bat", "Horseshoe Bat", "Long-eared Bat",
  "Blue Whale", "Fin Whale", "Sei Whale", "Humpback Whale",
  "Sperm Whale", "Gray Whale", "Right Whale", "Bowhead Whale",
  "Minke Whale", "Bryde's Whale", "Narwhal", "Beluga Whale",
  "Bottlenose Dolphin", "Spinner Dolphin", "Striped Dolphin",
  "Pacific White-sided Dolphin", "Risso's Dolphin", "Dusky Dolphin",
  "Atlantic Spotted Dolphin", "Pantropical Spotted Dolphin",
  "Harbor Porpoise", "Dall's Porpoise", "Vaquita",
  "Manatee", "West Indian Manatee", "Dugong",
  "Harbor Seal", "Grey Seal", "Harp Seal", "Ringed Seal",
  "Weddell Seal", "Leopard Seal", "Elephant Seal", "Monk Seal",
  "Hooded Seal", "Bearded Seal", "Crabeater Seal",
  "California Sea Lion", "Steller Sea Lion", "South American Sea Lion",
  "Northern Fur Seal", "Antarctic Fur Seal",
  "Walrus",
  // -- Reptiles --
  "American Alligator", "Chinese Alligator",
  "Saltwater Crocodile", "Nile Crocodile", "American Crocodile",
  "Mugger Crocodile", "Dwarf Crocodile", "Gharial", "Caiman",
  "Black Caiman", "Spectacled Caiman",
  "Green Sea Turtle", "Loggerhead Sea Turtle", "Hawksbill Sea Turtle",
  "Olive Ridley Sea Turtle", "Kemp's Ridley Sea Turtle", "Flatback Sea Turtle",
  "Eastern Box Turtle", "Painted Turtle", "Red-eared Slider",
  "Snapping Turtle", "Alligator Snapping Turtle", "Softshell Turtle",
  "Desert Tortoise", "Galapagos Tortoise", "Aldabra Giant Tortoise",
  "Sulcata Tortoise", "Hermann's Tortoise", "Russian Tortoise",
  "King Cobra", "Indian Cobra", "Egyptian Cobra", "Spitting Cobra",
  "Eastern Diamondback Rattlesnake", "Western Diamondback Rattlesnake",
  "Timber Rattlesnake", "Sidewinder",
  "Eastern Coral Snake", "Copperhead", "Cottonmouth", "Water Moccasin",
  "Boa Constrictor", "Green Anaconda", "Yellow Anaconda",
  "Burmese Python", "Reticulated Python", "Ball Python", "Carpet Python",
  "Corn Snake", "King Snake", "Milk Snake", "Rat Snake",
  "Garter Snake", "Gopher Snake", "Bull Snake", "Indigo Snake",
  "Green Tree Python", "Emerald Tree Boa",
  "Inland Taipan", "Eastern Brown Snake", "Tiger Snake",
  "Death Adder", "Common Krait", "Russell's Viper",
  "Gaboon Viper", "Puff Adder", "Fer-de-Lance", "Bushmaster",
  "Boomslang", "Twig Snake", "Green Mamba", "Western Green Mamba",
  "Eastern Green Mamba",
  "Six-lined Racerunner", "Collared Lizard",
  "Marine Iguana", "Rhinoceros Iguana", "Blue Iguana",
  "Bearded Dragon", "Frilled Lizard", "Monitor Lizard",
  "Water Monitor", "Nile Monitor", "Savannah Monitor",
  "Gila Monster", "Mexican Beaded Lizard",
  "Chameleon", "Panther Chameleon", "Veiled Chameleon", "Jackson's Chameleon",
  "Gecko", "Leopard Gecko", "Tokay Gecko", "Day Gecko",
  "Anole", "Green Anole", "Brown Anole",
  "Skink", "Blue-tongued Skink", "Five-lined Skink",
  "Glass Lizard", "Slow Worm", "Tuatara",
  // -- Fish --
  "Great White Shark", "Hammerhead Shark", "Tiger Shark", "Bull Shark",
  "Blue Shark", "Whale Shark", "Basking Shark", "Nurse Shark",
  "Lemon Shark", "Reef Shark", "Blacktip Shark", "Whitetip Shark",
  "Thresher Shark", "Porbeagle", "Goblin Shark", "Megamouth Shark",
  "Greenland Shark", "Mako Shark", "Angel Shark", "Wobbegong",
  "Bluefin Tuna", "Albacore Tuna", "Bigeye Tuna", "Skipjack Tuna",
  "Atlantic Salmon", "Pacific Salmon", "Chinook Salmon", "Sockeye Salmon",
  "Coho Salmon", "Pink Salmon", "Chum Salmon", "Atlantic Cod",
  "Pacific Cod", "Haddock", "Pollock", "Walleye Pollock",
  "Rainbow Trout", "Brown Trout", "Brook Trout", "Lake Trout",
  "Steelhead", "Arctic Char",
  "Largemouth Bass", "Smallmouth Bass", "Striped Bass", "White Bass",
  "Bluegill", "Crappie", "Perch", "Yellow Perch", "Walleye",
  "Northern Pike", "Muskellunge", "Chain Pickerel", "Tiger Muskie",
  "Channel Catfish", "Blue Catfish", "Flathead Catfish",
  "Common Carp", "Koi", "Goldfish",
  "Barracuda", "Great Barracuda",
  "Wahoo", "Mahi-mahi", "Dorado",
  "Tarpon", "Bonefish", "Permit", "Snook",
  "Red Snapper", "Grouper", "Goliath Grouper", "Nassau Grouper",
  "Flounder", "Halibut", "Sole", "Turbot",
  "Blue Marlin", "White Marlin", "Striped Marlin", "Spearfish",
  "Ocean Sunfish", "Mola Mola",
  "Clownfish", "Angelfish", "Butterflyfish", "Surgeonfish",
  "Parrotfish", "Wrasse", "Triggerfish", "Pufferfish",
  "Lionfish", "Scorpionfish", "Stonefish",
  "Flying Fish", "Needlefish", "Garfish",
  "Electric Eel", "Moray Eel", "Conger Eel", "Wolf Eel",
  "Seahorse", "Pipefish", "Sea Dragon",
  "Piranha", "Arapaima", "Peacock Bass",
  "Coelacanth", "Lungfish", "Sturgeon", "Paddlefish",
  "Stingray", "Manta Ray", "Eagle Ray", "Electric Ray",
  "Sawfish", "Guitarfish", "Skate",
  "Remora", "Pilot Fish",
  "Oarfish", "Opah", "Tilefish",
  // -- Amphibians --
  "American Bullfrog", "Green Frog", "Wood Frog", "Spring Peeper",
  "Tree Frog", "Red-eyed Tree Frog", "Poison Dart Frog",
  "Golden Poison Frog", "Blue Poison Dart Frog", "Strawberry Poison Frog",
  "Cane Toad", "American Toad", "Spadefoot Toad", "Fire-bellied Toad",
  "Surinam Toad", "Midwife Toad", "Natterjack Toad",
  "Tiger Salamander", "Spotted Salamander", "Fire Salamander",
  "Red-backed Salamander", "Slimy Salamander",
  "Hellbender", "Giant Salamander", "Chinese Giant Salamander",
  "Mudpuppy", "Axolotl", "Newt", "Eastern Newt", "Rough-skinned Newt",
  "Caecilian",
  // -- Invertebrates / Insects --
  "Dragonfly", "Damselfly", "Monarch Butterfly", "Swallowtail Butterfly",
  "Painted Lady", "Red Admiral", "Cabbage White", "Blue Morpho",
  "Atlas Moth", "Luna Moth", "Hawk Moth", "Sphinx Moth",
  "Honeybee", "Bumblebee", "Carpenter Bee", "Sweat Bee",
  "Yellow Jacket", "Paper Wasp", "Mud Dauber", "Hornet",
  "Asian Giant Hornet", "Tarantula Hawk",
  "House Fly", "Deer Fly", "Tsetse Fly",
  "Mosquito", "Crane Fly", "Robber Fly", "Blow Fly",
  "Fruit Fly", "Dung Beetle", "Rhinoceros Beetle", "Hercules Beetle",
  "Stag Beetle", "Ladybug", "Firefly", "Click Beetle",
  "Tiger Beetle", "Ground Beetle", "Longhorn Beetle", "Jewel Beetle",
  "Praying Mantis", "Walking Stick", "Leaf Insect",
  "Grasshopper", "Cricket", "Katydid", "Locust",
  "Cicada", "Leafhopper", "Aphid",
  "Ant", "Fire Ant", "Leafcutter Ant", "Army Ant", "Bullet Ant",
  "Termite", "Cockroach", "Water Bug",
  "Flea", "Tick", "Chigger", "Mite",
  "Tarantula", "Black Widow", "Brown Recluse", "Wolf Spider",
  "Jumping Spider", "Garden Spider", "Orb Weaver",
  "Scorpion", "Emperor Scorpion", "Bark Scorpion",
  "Centipede", "Millipede",
  // -- Marine invertebrates --
  "Octopus", "Giant Pacific Octopus", "Blue-ringed Octopus",
  "Squid", "Giant Squid", "Colossal Squid", "Humboldt Squid", "Flying Squid",
  "Nautilus", "Cuttlefish",
  "Jellyfish", "Box Jellyfish", "Moon Jellyfish", "Lion's Mane Jellyfish",
  "Portuguese Man-of-War",
  "Lobster", "American Lobster", "Spiny Lobster",
  "Blue Crab", "King Crab", "Hermit Crab", "Horseshoe Crab",
  "Shrimp", "Mantis Shrimp", "Pistol Shrimp", "Krill",
  "Sea Urchin", "Sea Cucumber", "Starfish", "Sea Star",
  "Coral", "Sea Anemone", "Sponge",
  "Conch", "Abalone", "Clam", "Oyster", "Mussel", "Scallop",
  "Snail", "Garden Snail", "Sea Slug", "Nudibranch",
];
