export const forbesBillionairesHints: string[] = [
  "Elon Musk", "Mark Zuckerberg", "Jeff Bezos", "Larry Ellison", "Bernard Arnault",
  "Warren Buffett", "Larry Page", "Sergey Brin", "Amancio Ortega", "Steve Ballmer",
  "Jensen Huang", "Michael Dell", "Rob Walton", "Jim Walton", "Bill Gates",
  "Michael Bloomberg", "Alice Walton", "Mukesh Ambani", "Carlos Slim Helu", "Julia Koch",
  "Françoise Bettencourt Meyers", "David Thomson", "Charles Koch", "Changpeng Zhao", "Gautam Adani",
  "Zhong Shanshan", "Thomas Peterffy", "Stephen Schwarzman", "Jeff Yass", "Tadashi Yanai",
  "Ma Huateng", "Ken Griffin", "Zhang Yiming", "Jacqueline Mars", "John Mars",
  "Prajogo Pangestu", "Shiv Nadar", "Giovanni Ferrero", "Alain Wertheimer", "Gérard Wertheimer",
  "Savitri Jindal", "Lukas Walton", "Robin Zeng", "Mark Mateschitz", "Klaus-Michael Kühne",
  "Abigail Johnson", "Li Ka-shing", "Colin Huang", "Miriam Adelson", "Phil Knight",
  "Reinhold Würth", "Eduardo Saverin", "Rafaela Aponte-Diamant", "Gianluigi Aponte", "MacKenzie Scott",
  "William Ding", "Gina Rinehart", "Melinda French Gates", "Masayoshi Son", "Dieter Schwarz",
  "Dilip Shanghvi", "Len Blavatnik", "Low Tuck Kwong", "Elaine Marshall", "Lee Shau Kee",
  "Lyndal Stephens Greth", "He Xiangjian", "Leonid Mikhelson", "German Larrea Mota Velasco", "Vladimir Lisin",
  "Vagit Alekperov", "Andrea Pignataro", "Eyal Ofer", "Eric Schmidt", "Lei Jun",
  "Alexey Mordashov", "Thomas Frist Jr.", "R. Budi Hartono", "John Menard Jr.", "Iris Fontbona",
  "Vladimir Potanin", "Gennady Timchenko", "Andreas von Bechtolsheim", "Jack Ma", "Emmanuel Besnier",
  "Michael Hartono", "Rupert Murdoch", "Daniel Gilbert", "Henry Samueli", "Diane Hendricks",
  "Kumar Birla", "David Tepper", "Cyrus Poonawalla", "Steve Cohen", "Stefan Quandt",
  "Susanne Klatten", "Wang Chuanfu", "François Pinault", "Takemitsu Takizaki", "Donald Bren",
  // Beyond top 100
  "George Soros", "Ray Dalio", "Paul Singer", "John Paulson", "Carl Icahn",
  "Dan Loeb", "Bill Ackman", "Howard Marks", "Leon Black", "Henry Kravis",
  "George Roberts", "David Rubenstein", "Blackstone", "KKR",
  "Peter Thiel", "Reid Hoffman", "Marc Andreessen", "Ben Horowitz", "Vinod Khosla",
  "Sam Altman", "Patrick Collison", "John Collison", "Brian Chesky", "Travis Kalanick",
  "Dara Khosrowshahi", "Tony Xu", "Logan Green", "John Zimmer", "Bobby Murphy",
  "Evan Spiegel", "Kevin Systrom", "Mike Krieger", "Jan Koum", "Brian Acton",
  "Dustin Moskovitz", "Chris Hughes", "Andrew Mason", "Eric Lefkofsky", "Brad Keywell",
  "Oprah Winfrey", "Jay-Z", "Rihanna", "Paul McCartney", "Mick Jagger",
  "Tiger Woods", "Michael Jordan", "LeBron James", "Roger Federer", "Cristiano Ronaldo",
  "Lionel Messi", "Floyd Mayweather", "Conor McGregor", "Kim Kardashian", "Kylie Jenner",
];
