export const forbesBillionairesHints: string[] = [
  // ===== ORIGINAL TOP 100 (preserved exactly) =====
  "Elon Musk", "Mark Zuckerberg", "Jeff Bezos", "Larry Ellison", "Bernard Arnault",
  "Warren Buffett", "Larry Page", "Sergey Brin", "Amancio Ortega", "Steve Ballmer",
  "Jensen Huang", "Michael Dell", "Rob Walton", "Jim Walton", "Bill Gates",
  "Michael Bloomberg", "Alice Walton", "Mukesh Ambani", "Carlos Slim Helu", "Julia Koch",
  "Françoise Bettencourt Meyers", "David Thomson", "Charles Koch", "Changpeng Zhao", "Gautam Adani",
  "Zhong Shanshan", "Thomas Peterffy", "Stephen Schwarzman", "Jeff Yass", "Tadashi Yanai",
  "Ma Huateng", "Ken Griffin", "Zhang Yiming", "Jacqueline Mars", "John Mars",
  "Prajogo Pangestu", "Shiv Nadar", "Giovanni Ferrero", "Alain Wertheimer", "Gérard Wertheimer",
  "Savitri Jindal", "Lukas Walton", "Robin Zeng", "Mark Mateschitz", "Klaus-Michael Kühne",
  "Abigail Johnson", "Li Ka-shing", "Colin Huang", "Miriam Adelson", "Phil Knight",
  "Reinhold Würth", "Eduardo Saverin", "Rafaela Aponte-Diamant", "Gianluigi Aponte", "MacKenzie Scott",
  "William Ding", "Gina Rinehart", "Melinda French Gates", "Masayoshi Son", "Dieter Schwarz",
  "Dilip Shanghvi", "Len Blavatnik", "Low Tuck Kwong", "Elaine Marshall", "Lee Shau Kee",
  "Lyndal Stephens Greth", "He Xiangjian", "Leonid Mikhelson", "German Larrea Mota Velasco", "Vladimir Lisin",
  "Vagit Alekperov", "Andrea Pignataro", "Eyal Ofer", "Eric Schmidt", "Lei Jun",
  "Alexey Mordashov", "Thomas Frist Jr.", "R. Budi Hartono", "John Menard Jr.", "Iris Fontbona",
  "Vladimir Potanin", "Gennady Timchenko", "Andreas von Bechtolsheim", "Jack Ma", "Emmanuel Besnier",
  "Michael Hartono", "Rupert Murdoch", "Daniel Gilbert", "Henry Samueli", "Diane Hendricks",
  "Kumar Birla", "David Tepper", "Cyrus Poonawalla", "Steve Cohen", "Stefan Quandt",
  "Susanne Klatten", "Wang Chuanfu", "François Pinault", "Takemitsu Takizaki", "Donald Bren",

  // ===== ORIGINAL BEYOND TOP 100 (preserved exactly) =====
  "George Soros", "Ray Dalio", "Paul Singer", "John Paulson", "Carl Icahn",
  "Dan Loeb", "Bill Ackman", "Howard Marks", "Leon Black", "Henry Kravis",
  "George Roberts", "David Rubenstein", "Blackstone", "KKR",
  "Peter Thiel", "Reid Hoffman", "Marc Andreessen", "Ben Horowitz", "Vinod Khosla",
  "Sam Altman", "Patrick Collison", "John Collison", "Brian Chesky", "Travis Kalanick",
  "Dara Khosrowshahi", "Tony Xu", "Logan Green", "John Zimmer", "Bobby Murphy",
  "Evan Spiegel", "Kevin Systrom", "Mike Krieger", "Jan Koum", "Brian Acton",
  "Dustin Moskovitz", "Chris Hughes", "Andrew Mason", "Eric Lefkofsky", "Brad Keywell",
  "Oprah Winfrey", "Jay-Z", "Rihanna", "Paul McCartney", "Mick Jagger",
  "Tiger Woods", "Michael Jordan", "LeBron James", "Roger Federer", "Cristiano Ronaldo",
  "Lionel Messi", "Floyd Mayweather", "Conor McGregor", "Kim Kardashian", "Kylie Jenner",

  // ===== TECH BILLIONAIRES =====
  "Tim Cook", "Satya Nadella", "Sundar Pichai", "Lisa Su", "Pat Gelsinger",
  "Reed Hastings", "Marc Benioff", "Jack Dorsey", "Evan Williams", "Biz Stone",
  "Drew Houston", "Arash Ferdowsi", "Daniel Ek", "Martin Lorentzon", "Garrett Camp",
  "Stewart Butterfield", "Eric Yuan", "Frank Slootman", "Aneel Bhusri", "Aaron Levie",
  "Tony Fadell", "Meg Whitman", "Safra Catz", "Nikesh Arora", "Shantanu Narayen",
  "Brian Krzanich", "Hasso Plattner", "Dietmar Hopp", "Bill McDermott", "Thomas Siebel",
  "Pierre Omidyar", "Judy Faulkner", "Gary Vaynerchuk", "Palmer Luckey", "Travis VanderZanden",
  "Whitney Wolfe Herd", "Vlad Tenev", "Baiju Bhatt", "Brian Armstrong", "Fred Ehrsam",
  "Jared Isaacman", "Robert Pera", "Austin Russell", "David Duffield", "Scott McNealy",
  "Michael Moritz", "John Doerr", "Jim Breyer", "Yuri Milner",
  "Romesh Wadhwani", "Jay Chaudhry", "Tobi Lutke", "Scott Farquhar",
  "Mike Cannon-Brookes", "Melanie Perkins", "Forrest Li",
  "Bobby Lee", "Jihan Wu", "Chris Larsen", "Cameron Winklevoss", "Tyler Winklevoss",
  "Vitalik Buterin", "Sam Bankman-Fried", "Brad Garlinghouse", "Michael Saylor",
  "Max Levchin", "David Sacks", "Chamath Palihapitiya", "Joe Lonsdale", "Alex Karp",
  "Parker Conrad", "Todd McKinnon", "Dario Amodei", "Daniela Amodei",
  "Naveen Jain", "Niklas Zennstrom", "Janus Friis",

  // ===== FINANCE / HEDGE FUND BILLIONAIRES =====
  "James Simons", "David Shaw", "Kenneth Griffin", "Israel Englander", "Chase Coleman",
  "Philippe Laffont", "Andreas Halvorsen", "David Einhorn", "Seth Klarman", "Bruce Kovner",
  "Stanley Druckenmiller", "John Arnold", "Jim Chanos", "Michael Platt", "Alan Howard",
  "Izzy Englander", "Cliff Asness", "Chris Hohn", "Nelson Peltz", "Paul Tudor Jones",
  "Eddie Lampert", "Marc Lasry", "Daniel Och", "Robert Mercer", "Rebekah Mercer",
  "T. Boone Pickens", "Ron Baron", "Mario Gabelli", "Charles Schwab",
  "Ned Johnson", "Jamie Dimon", "Lloyd Blankfein", "Brian Moynihan",
  "John Mack", "Hank Paulson", "Robert Smith", "Vista Equity", "Orlando Bravo",
  "Josh Harris", "Marc Rowan", "Michael Kim", "David Bonderman", "James Coulter",

  // ===== REAL ESTATE BILLIONAIRES =====
  "Donald Trump", "Sam Zell", "Stephen Ross", "Richard LeFrak", "Jeff Sutton",
  "John Sobrato", "Igor Olenicoff", "Micky Arison", "Ted Lerner", "Mortimer Zuckerman",
  "Joseph Tsai", "Wang Jianlin", "Hui Ka Yan", "Yang Huiyan",
  "Peter Woo", "Robert Kuok", "Pan Sutong", "Xu Jiayin",
  "Hariri Family", "Gerald Cavendish Grosvenor",

  // ===== RETAIL / CONSUMER BILLIONAIRES =====
  "Christy Walton", "Ann Walton Kroenke", "Nancy Walton Laurie",
  "Stefan Persson", "Ingvar Kamprad",
  "Karl Albrecht", "Theo Albrecht", "Beate Heister",
  "Charlene de Carvalho-Heineken", "Gerard Heineken",
  "Leonardo Del Vecchio", "Massimo Ferragamo", "Giorgio Armani",
  "Miuccia Prada", "Johann Rupert", "Patrizio Bertelli",
  "Nicolas Puech", "Axel Dumas",
  "James Dyson", "Hans Rausing", "Kirsten Rausing",
  "Erivan Haub", "Karl-Erivan Haub",
  "Kevin Plank", "Sara Blakely",
  "John Donahoe", "Leslie Wexner",
  "Bernard Marcus", "Arthur Blank", "Ken Langone",

  // ===== ENERGY / MINING BILLIONAIRES =====
  "David Koch", "Harold Hamm", "Trevor Rees-Jones", "Kelcy Warren",
  "Richard Kinder", "Terrence Pegula", "Kim Pegula",
  "George Kaiser", "Clive Palmer",
  "Patrice Motsepe", "Ivan Glasenberg", "Andrew Forrest",
  "Lakshmi Mittal", "Aditya Mittal", "Alisher Usmanov",
  "Mikhail Prokhorov", "Roman Abramovich", "Viktor Vekselberg",
  "Mikhail Fridman", "Petr Kellner",
  "Farhad Moshiri", "Anil Agarwal",

  // ===== MEDIA / ENTERTAINMENT BILLIONAIRES =====
  "Bob Iger", "David Zaslav", "Shari Redstone", "Sumner Redstone",
  "John Malone", "Liberty Media", "David Geffen", "Jeffrey Katzenberg",
  "Steven Spielberg", "George Lucas", "Tyler Perry",
  "Peter Jackson", "James Cameron",
  "Haim Saban", "Vince McMahon", "Dana White",
  "Jerry Bruckheimer", "Brian Grazer", "Ron Howard",
  "Michael Eisner", "Barry Diller", "Byron Allen",
  "Ted Turner", "John Kluge", "Si Newhouse",
  "Donald Newhouse", "Lachlan Murdoch", "James Murdoch",
  "Silvio Berlusconi", "Reinhard Mohn",
  "Axel Springer", "Friede Springer", "Mathias Dopfner",
  "Subhash Chandra", "Kalanithi Maran",

  // ===== FOOD / BEVERAGE BILLIONAIRES =====
  "Jorge Paulo Lemann", "Marcel Herrmann Telles", "Carlos Alberto Sicupira",
  "Forrest Mars Jr.", "Pamela Mars",
  "Victoria Mars", "Valerie Mars",
  "Cargill Family", "Pauline MacMillan Keinath", "Whitney MacMillan",
  "August Busch III",
  "Joesley Batista", "Wesley Batista",
  "Dhanin Chearavanont", "Charoen Sirivadhanabhakdi",
  "Robert Rich Jr.", "John Tyson", "Horst Paulmann",
  "Stef Wertheimer", "Serge Dassault",
  "Massimiliana Landini Aleotti", "Augusto Perfetti", "Luca Garavoglia",
  "Theo Muller", "Stefan Reimann-Andersen",
  "Dietrich Mateschitz",

  // ===== PHARMA / HEALTHCARE BILLIONAIRES =====
  "Patrick Soon-Shiong", "Ernesto Bertarelli",
  "Stefano Pessina", "Phillip Frost", "Randal Kirk",
  "Leonard Lauder", "Ronald Lauder", "William Lauder",
  "Hansjoerg Wyss", "Gayle Cook", "Carl Cook",
  "Ronda Stryker", "Jon Stryker",
  "Herbert Wertheim", "Elizabeth Holmes",
  "Adar Poonawalla",
  "Radha Vembu", "Sridhar Vembu",
  "Azim Premji", "Kiran Mazumdar-Shaw",

  // ===== SPORTS TEAM OWNERS =====
  "Stan Kroenke", "Jerry Jones", "Robert Kraft",
  "Stephen Bisciotti", "Shahid Khan", "Jed York",
  "Mark Davis", "Jim Irsay", "Woody Johnson",
  "Steve Tisch", "John Mara", "Dan Snyder",
  "Jerry Reinsdorf", "Mark Cuban", "Tilman Fertitta",
  "Joe Lacob", "Steve Pagliuca", "Wes Edens",
  "Rocky Wirtz", "Daryl Katz", "Philip Anschutz",
  "Todd Boehly",
  "John Henry", "Tom Werner", "Mike Ashley",
  "Joe Lewis", "Daniel Levy",
  "Nasser Al-Khelaifi", "Mansour bin Zayed Al Nahyan",
  "Sheikh Mansour",
  "Dmitry Rybolovlev",
  "Andrea Agnelli",
  "Florentino Perez", "Joan Laporta",
  "Herb Simon",

  // ===== CELEBRITY BILLIONAIRES =====
  "Kanye West", "Dr. Dre", "Diddy", "Sean Combs", "Bono",
  "Madonna", "Barbra Streisand", "Celine Dion", "Elton John", "Bruce Springsteen",
  "Dolly Parton", "Taylor Swift", "Beyoncé", "Drake",
  "Calvin Harris", "Andrew Lloyd Webber",
  "Jerry Seinfeld", "Ellen DeGeneres", "Conan O'Brien",
  "Reese Witherspoon", "Jessica Alba", "Ryan Reynolds", "Blake Lively",
  "George Clooney", "Tom Cruise", "Arnold Schwarzenegger",
  "Dwayne Johnson", "Will Smith", "Tom Hanks",
  "Robert De Niro", "Clint Eastwood",
  "David Beckham", "Magic Johnson", "Shaquille O'Neal",
  "Serena Williams", "Venus Williams",
  "Lewis Hamilton", "Phil Mickelson", "Jack Nicklaus",
  "Roger Staubach", "Michael Schumacher",
  "Eddie Jordan", "Neymar", "Kylian Mbappe",
  "Virat Kohli", "MS Dhoni", "Sachin Tendulkar",

  // ===== INDIAN BILLIONAIRES =====
  "Ratan Tata", "Noel Tata", "Shapoor Mistry", "Pallonji Mistry",
  "Radhakishan Damani", "Nikhil Kamath", "Nithin Kamath",
  "Byju Raveendran", "Bhavish Aggarwal", "Ritesh Agarwal",
  "Rishad Premji",
  "Uday Kotak", "Sunil Bharti Mittal",
  "Anil Ambani", "Rahul Bajaj", "Rajiv Bajaj",
  "Adi Godrej", "Nadir Godrej", "Pirojsha Godrej",
  "Harsh Mariwala", "Yusuf Hamied",
  "Anand Mahindra", "Vijay Mallya", "Nandan Nilekani",
  "Naveen Jindal", "Sajjan Jindal", "Parth Jindal",
  "Ravi Ruia", "Shashi Ruia",
  "Vivek Ranadive",
  "Hemendra Kothari", "Madhu Kapur",

  // ===== CHINESE BILLIONAIRES =====
  "Pony Ma",
  "Li Shufu", "Ren Zhengfei", "Wang Xing",
  "Liu Qiangdong", "Richard Liu", "Zhang Zhidong",
  "Liang Wengen", "Zong Qinghou",
  "Robin Li", "Huang Zheng",
  "Wang Wei", "Zhang Yong",
  "Sun Piaoyang", "Qin Yinglin",
  "Liu Yonghao", "Lu Zhiqiang",
  "Ma Jian", "Chen Bang", "Pan Zhengmin",
  "Ding Lei", "Eric Li",
  "Liu Hanyuan", "Chen Jianhua", "Guo Guangchang",
  "Shu Ping", "Wang Wenyin", "Zhang Fan",
  "Terry Gou", "Tsai Eng-meng",
  "Li Tzar Kuoi",

  // ===== MIDDLE EASTERN BILLIONAIRES =====
  "Prince Alwaleed bin Talal", "Mohammed bin Salman", "MBS",
  "Sultan of Brunei", "Hassanal Bolkiah",
  "Nassef Sawiris", "Naguib Sawiris", "Onsi Sawiris",
  "Mohamed Al Fayed", "Al Fayed Family",
  "Majid Al Futtaim", "Abdulaziz Al Ghurair",
  "Issad Rebrab", "Othman Benjelloun",
  "Najib Mikati", "Taha Mikati", "Bahaa Hariri", "Saad Hariri",
  "Hussain Sajwani", "Mohamed Alabbar",
  "Maan Al-Sanea", "Sulaiman Al Rajhi",
  "Al Nahyan Family", "Al Maktoum Family",
  "Mohammed bin Rashid Al Maktoum",
  "Aliko Dangote",

  // ===== EUROPEAN BILLIONAIRES =====
  "Vincent Bolloré", "Xavier Niel", "Patrick Drahi",
  "Martin Bouygues", "Rodolphe Saadé",
  "Karl Albrecht Jr.", "Theo Albrecht Jr.",
  "Curt Engelhorn", "August von Finck",
  "SAP",
  "Jim Ratcliffe", "Richard Branson", "Denise Coates",
  "James Weston",
  "Hinduja Family", "Srichand Hinduja", "Gopichand Hinduja",
  "Giuseppe De' Longhi",
  "Jorge Lemann",
  "Sandra Ortega Mera", "Juan Roig", "Rafael del Pino",
  "Melker Schorling", "Dan Olsson", "Fredrik Lundberg",
  "Odd Reitan", "Gustav Witzoe", "Kjell Inge Rokke",
  "Frits Goldschmeding",
  "Anders Holch Povlsen", "Niels Peter Louis-Hansen",
  "John Dorrance III",
  "Karel Komarek", "Daniel Kretinsky",
  "Michal Solowow", "Zygmunt Solorz-Zak",
  "Oleg Deripaska", "Pyotr Aven",
  "Andrey Melnichenko", "Suleiman Kerimov",

  // ===== LATIN AMERICAN BILLIONAIRES =====
  "Carlos Slim Domit",
  "Ricardo Salinas Pliego",
  "Alberto Bailleres Gonzalez", "Maria Asuncion Aramburuzabala",
  "Joseph Safra", "Vicky Safra",
  "Alejandro Santo Domingo", "Luis Carlos Sarmiento",
  "Julio Mario Santo Domingo", "Jaime Gilinski",
  "Carlos Rodriguez-Pastor", "Andres Santo Domingo",
  "Alvaro Saieh",
  "Guillermo Luksic",

  // ===== HISTORICAL / DECEASED BILLIONAIRES =====
  "John D. Rockefeller", "Andrew Carnegie", "Cornelius Vanderbilt",
  "Henry Ford", "J.P. Morgan", "Andrew Mellon",
  "Howard Hughes", "Sam Walton", "Walt Disney",
  "John Jacob Astor", "Jay Gould", "Leland Stanford",
  "Steve Jobs", "Paul Allen", "Larry Hillblom",
  "Aga Khan", "Aristotle Onassis",
  "Conrad Hilton", "Barron Hilton",
  "David Rockefeller", "Nelson Rockefeller",
  "Sheldon Adelson", "Kirk Kerkorian", "Marvin Davis",
  "Malcolm Forbes", "Malcolm Forbes Jr.",
  "Ross Perot", "H. Ross Perot Jr.",
  "Eli Broad",
  "Alfred Nobel", "Nikola Tesla",
  "J. Paul Getty", "Gordon Getty",
  "Henry Kaiser", "Estée Lauder",
  "Ray Kroc", "Dave Thomas", "Colonel Sanders",
  "Hugh Hefner",
  "Larry Flynt",
  "George Steinbrenner",

  // ===== FAMOUS FAMILY NAMES =====
  "Rothschild", "Rothschild Family", "Jacob Rothschild",
  "Vanderbilt", "Vanderbilt Family",
  "Getty", "Getty Family", "Mark Getty",
  "Rockefeller", "Rockefeller Family",
  "Carnegie", "Carnegie Family",
  "Astor", "Astor Family",
  "Morgan", "Morgan Family",
  "Ford", "Ford Family", "William Clay Ford",
  "DuPont", "DuPont Family",
  "Hearst", "Hearst Family", "William Randolph Hearst",
  "Hilton", "Hilton Family", "Paris Hilton", "Nicky Hilton",
  "Pritzker", "Pritzker Family", "Penny Pritzker", "Jay Pritzker", "Thomas Pritzker",
  "Bass Family", "Sid Bass", "Lee Bass", "Robert Bass", "Ed Bass",
  "Hunt Family", "Ray Lee Hunt", "Lamar Hunt",
  "Crown Family", "Lester Crown", "James Crown",
  "Mars Family",
  "Walton Family",
  "Koch Family",
  "Murdoch Family",
  "Lauder Family",
  "Sackler Family", "Richard Sackler",
  "Cargill MacMillan Family",
  "Cox Family", "Jim Kennedy", "Blair Parry-Okeden",
  "Johnson Family",
  "Wrigley Family", "William Wrigley Jr.",
  "Busch Family", "August Busch IV",
  "Anheuser-Busch",
  "Ferrero Family",
  "Hermès Family",
  "Porsche Family", "Ferdinand Piëch", "Wolfgang Porsche",
  "BMW Quandt Family",
  "Aldi Family",
  "Ambani Family",
  "Tata Family",
  "Birla Family",
  "Godrej Family",
  "Bajaj Family",
];
