// ~450+ world cities people might guess for global cost of living
// Includes all 327 cities from Numbeo 2025 + major world cities not in dataset
export const globalCitiesCostOfLivingHints: string[] = [
  // Top 100 (the actual answers — Numbeo Cost of Living Index 2025)
  "Zurich", "Lausanne", "Geneva", "New York", "Basel",
  "Bern", "San Francisco", "Honolulu", "Reykjavik", "Boston",
  "Singapore", "Seattle", "Washington DC", "London", "San Diego",
  "Trondheim", "Los Angeles", "Tel Aviv", "Sacramento", "Oslo",
  "Philadelphia", "Hong Kong", "Chicago", "Miami", "Bergen",
  "Atlanta", "Denver", "Copenhagen", "New Orleans", "Portland",
  "Tampa", "Charlotte", "Raleigh", "Pittsburgh", "Paris",
  "Amsterdam", "Sydney", "Minneapolis", "Jerusalem", "Columbus",
  "Canberra", "Aarhus", "Nashville", "Luxembourg", "Munich",
  "Dallas", "Baltimore", "Haarlem", "Surrey", "Brighton",
  "Dublin", "Edinburgh", "Orlando", "Las Vegas", "Haifa",
  "Victoria", "Phoenix", "Helsinki", "Madison", "Lyon",
  "Hamburg", "Cork", "Seoul", "Tucson", "Vancouver",
  "Saint Louis", "Aberdeen", "Milan", "Brussels", "Salt Lake City",
  "Frankfurt", "Stockholm", "Austin", "Rotterdam", "Manchester",
  "Adelaide", "Toronto", "Bristol", "Kelowna", "Cologne",
  "Vienna", "Antwerp", "Calgary", "Melbourne", "Dusseldorf",
  "Glasgow", "Houston", "Boise", "Stuttgart", "Utrecht",
  "Nuremberg", "Eindhoven", "Gent", "Jacksonville", "Berlin",
  "Graz", "Halifax", "Wellington", "Essen", "Auckland",

  // Ranks 101–327 from Numbeo 2025
  "Montpellier", "Ottawa", "Perth", "Bologna", "Karlsruhe",
  "San Antonio", "Bremen", "Toulouse", "Montreal", "Edmonton",
  "Leeds", "The Hague", "Hanover", "Mannheim", "Dubai",
  "Tampere", "Aachen", "Brisbane", "Mississauga", "Liverpool",
  "Birmingham", "Quebec City", "Leipzig", "Gothenburg", "Sheffield",
  "Dresden", "Malmo", "Sliema", "Belfast", "Christchurch",
  "Winnipeg", "Cincinnati", "London (Ontario)", "Groningen", "Limassol",
  "Padova", "Port of Spain", "Tallinn", "Abu Dhabi", "Verona",
  "San Jose (Costa Rica)", "Turin", "Tokyo", "Rome", "Naples",
  "Barcelona", "Madrid", "Ljubljana", "Athens", "Taipei",
  "Doha", "Nicosia", "Montevideo", "Split", "Manama",
  "Riyadh", "Sharjah", "Larnaca", "Thessaloniki", "Prague",
  "Lisbon", "Panama City", "Riga", "Bratislava", "Vilnius",
  "Zagreb", "Warsaw", "Beirut", "Caracas", "Porto",
  "Kosice", "Tirana", "Kaunas", "Seville", "Brno",
  "Malaga", "Kuwait City", "Jeddah", "Valencia", "Plzen",
  "Krakow", "Monterrey", "Muscat", "Yerevan", "Gdansk",
  "Buenos Aires", "Wroclaw", "Istanbul", "Suzhou", "Guatemala City",
  "Amman", "Belgrade", "Braga", "Shanghai", "Sofia",
  "Katowice", "Poznan", "Budapest", "Bucharest", "Phuket",
  "Mexico City", "Santiago", "Lodz", "Constanta", "Cluj-Napoca",
  "Novi Sad", "Bangkok", "Phnom Penh", "Beijing", "Harare",
  "Shenzhen", "Szczecin", "Varna", "Podgorica", "Guangzhou",
  "Ankara", "Antalya", "Brasov", "Merida", "Izmir",
  "Queretaro", "Timisoara", "Manila", "Colombo", "Guadalajara",
  "Burgas", "Banja Luka", "Iasi", "Pattaya", "Debrecen",
  "Kuala Lumpur", "Johannesburg", "Quito", "Sarajevo", "Plovdiv",
  "Tbilisi", "Erbil", "Hangzhou", "Lima", "Ulaanbaatar",
  "Sibiu", "Chisinau", "Accra", "Skopje", "Casablanca",
  "Bursa", "Baghdad", "Cape Town", "Pretoria", "Moscow",
  "Nairobi", "Baku", "Nis", "Lagos", "Sao Paulo",
  "Rabat", "Chiang Mai", "Marrakech", "Mersin", "Batumi",
  "Cuenca", "Durban", "Ho Chi Minh City", "Jakarta", "Almaty",
  "Kyiv", "Rio de Janeiro", "Medellin", "Brasilia", "Hanoi",
  "Tunis", "Chengdu", "Campinas", "Florianopolis", "Astana",
  "Porto Alegre", "Bogota", "Bishkek", "Dnipro", "Kampala",
  "Belo Horizonte", "Tehran", "Minsk", "Algiers", "Saint Petersburg",
  "Mumbai", "Pristina", "Tashkent", "Curitiba", "Odessa",
  "Gurgaon", "Lviv", "Kharkiv", "Kathmandu", "Dhaka",
  "Asuncion", "Bangalore", "Yekaterinburg", "Pune", "Nizhny Novgorod",
  "Delhi", "Kazan", "Noida", "Krasnodar", "Novosibirsk",
  "Kaliningrad", "Ufa", "Rostov-on-Don", "Hyderabad", "Ahmedabad",
  "Chennai", "Tripoli", "Perm", "Islamabad", "Chandigarh",
  "Vadodara", "Cairo", "Kolkata", "Bhubaneswar", "Kochi",
  "Surat", "Jaipur", "Lucknow", "Karachi", "Lahore",
  "Alexandria", "Coimbatore",

  // Additional major world cities not in the Numbeo 2025 dataset
  "Osaka", "Kyoto", "Yokohama", "Nagoya", "Sapporo",
  "Busan", "Incheon", "Daegu", "Gwangju",
  "Chongqing", "Tianjin", "Wuhan", "Nanjing",
  "Xi'an", "Dongguan", "Foshan", "Wuxi", "Nanchang", "Da Nang", "Hai Phong",
  "Yangon", "Mandalay", "Naypyidaw", "Chittagong", "Faisalabad",
  "Kabul", "Kandahar", "Pokhara", "Kandy",
  "Bandar Seri Begawan",
  "Dili",
  "Port Moresby",
  "Surabaya", "Bandung", "Medan", "Semarang", "Palembang",
  "Makassar", "Tangerang", "Quezon City", "Cebu", "Davao",
  "Vientiane", "Luang Prabang", "Siem Reap",
  "Dar es Salaam", "Zanzibar", "Entebbe",
  "Kigali",
  "Addis Ababa", "Kumasi", "Abuja", "Kano", "Ibadan",
  "Dakar",
  "Abidjan", "Yamoussoukro",
  "Douala", "Yaounde",
  "Kinshasa", "Lubumbashi",
  "Luanda",
  "Maputo",
  "Lusaka", "Bulawayo",
  "Gaborone",
  "Windhoek",
  "Antananarivo", "Fez", "Tangier", "Oran", "Constantine", "Benghazi", "Giza", "Luxor",
  "Khartoum", "Omdurman",
  "Mogadishu",
  "Monrovia",
  "Freetown",
  "Conakry",
  "Bamako",
  "Ouagadougou",
  "Niamey",
  "N'Djamena",
  "Libreville",
  "Brazzaville",
  "Bangui",
  "Lome",
  "Porto-Novo", "Cotonou",
  "Nouakchott",
  "Banjul",
  "Bissau",
  "Malabo",
  "Sao Tome",
  "Cape Verde",
  "Juba",
  "Djibouti",
  "Asmara",
  "Moroni",
  "Victoria (Seychelles)",
  "Port Louis (Mauritius)",
  "Leon", "Ciudad Juarez", "Cancun", "Merida (Mexico)",
  "Havana", "Santiago de Cuba",
  "San Juan (Puerto Rico)",
  "Kingston (Jamaica)",
  "Port-au-Prince",
  "Santo Domingo",
  "San Salvador",
  "Tegucigalpa",
  "Managua", "Cali", "Barranquilla", "Cartagena", "Guayaquil", "Arequipa",
  "La Paz", "Santa Cruz", "Valparaiso", "Salvador", "Fortaleza",
  "Recife", "Manaus", "Maracaibo",
  "Georgetown", "Paramaribo",
  "Cayenne", "Dunedin", "Darwin", "Hobart",
  "Suva", "Nadi",
  "Noumea",
  "Papeete",
  "Apia",
  "Nukualofa",
  "Honiara",
  "Port Vila", "Newcastle",
  "Cardiff", "Bruges", "Liege", "Marseille", "Nice",
  "Bordeaux", "Nantes", "Strasbourg", "Lille", "Dortmund", "Stavanger", "Odense", "Turku", "Oulu", "Ostrava", "Chelyabinsk", "Omsk", "Samara", "Voronezh", "Gomel", "Shymkent", "Samarkand", "Osh",
  "Ashgabat",
  "Dushanbe", "Damascus", "Aleppo", "Basra", "Salalah",
  "Sanaa", "Aden", "Mashhad", "Isfahan", "Tabriz", "Shiraz",
];
