// ~450+ world cities people might guess for global cost of living
// Includes all 327 cities from Numbeo 2025 + major world cities not in dataset
export const globalCitiesCostOfLivingHints: string[] = [
  // Top 100 (the actual answers — Numbeo Cost of Living Index 2025)
  "Zurich", "Lausanne", "Geneva", "New York", "Basel",
  "Bern", "San Francisco", "Honolulu", "Reykjavik", "Boston",
  "Singapore", "Seattle", "Washington DC", "London", "San Diego",
  "Trondheim", "Los Angeles", "Tel Aviv", "Sacramento", "Oslo",
  "Philadelphia", "Hong Kong", "Chicago", "Miami", "Bergen",
  "Atlanta", "Denver", "Copenhagen", "New Orleans", "Portland",
  "Tampa", "Charlotte", "Raleigh", "Pittsburgh", "Paris",
  "Amsterdam", "Sydney", "Minneapolis", "Jerusalem", "Columbus",
  "Canberra", "Aarhus", "Nashville", "Luxembourg", "Munich",
  "Dallas", "Baltimore", "Haarlem", "Surrey", "Brighton",
  "Dublin", "Edinburgh", "Orlando", "Las Vegas", "Haifa",
  "Victoria", "Phoenix", "Helsinki", "Madison", "Lyon",
  "Hamburg", "Cork", "Seoul", "Tucson", "Vancouver",
  "Saint Louis", "Aberdeen", "Milan", "Brussels", "Salt Lake City",
  "Frankfurt", "Stockholm", "Austin", "Rotterdam", "Manchester",
  "Adelaide", "Toronto", "Bristol", "Kelowna", "Cologne",
  "Vienna", "Antwerp", "Calgary", "Melbourne", "Dusseldorf",
  "Glasgow", "Houston", "Boise", "Stuttgart", "Utrecht",
  "Nuremberg", "Eindhoven", "Gent", "Jacksonville", "Berlin",
  "Graz", "Halifax", "Wellington", "Essen", "Auckland",

  // Ranks 101–327 from Numbeo 2025
  "Montpellier", "Ottawa", "Perth", "Bologna", "Karlsruhe",
  "San Antonio", "Bremen", "Toulouse", "Montreal", "Edmonton",
  "Leeds", "The Hague", "Hanover", "Mannheim", "Dubai",
  "Tampere", "Aachen", "Brisbane", "Mississauga", "Liverpool",
  "Birmingham", "Quebec City", "Leipzig", "Gothenburg", "Sheffield",
  "Dresden", "Malmo", "Sliema", "Belfast", "Christchurch",
  "Winnipeg", "Cincinnati", "London (Ontario)", "Groningen", "Limassol",
  "Padova", "Port of Spain", "Tallinn", "Abu Dhabi", "Verona",
  "San Jose (Costa Rica)", "Turin", "Tokyo", "Rome", "Naples",
  "Barcelona", "Madrid", "Ljubljana", "Athens", "Taipei",
  "Doha", "Nicosia", "Montevideo", "Split", "Manama",
  "Riyadh", "Sharjah", "Larnaca", "Thessaloniki", "Prague",
  "Lisbon", "Panama City", "Riga", "Bratislava", "Vilnius",
  "Zagreb", "Warsaw", "Beirut", "Caracas", "Porto",
  "Kosice", "Tirana", "Kaunas", "Seville", "Brno",
  "Malaga", "Kuwait City", "Jeddah", "Valencia", "Plzen",
  "Krakow", "Monterrey", "Muscat", "Yerevan", "Gdansk",
  "Buenos Aires", "Wroclaw", "Istanbul", "Suzhou", "Guatemala City",
  "Amman", "Belgrade", "Braga", "Shanghai", "Sofia",
  "Katowice", "Poznan", "Budapest", "Bucharest", "Phuket",
  "Mexico City", "Santiago", "Lodz", "Constanta", "Cluj-Napoca",
  "Novi Sad", "Bangkok", "Phnom Penh", "Beijing", "Harare",
  "Shenzhen", "Szczecin", "Varna", "Podgorica", "Guangzhou",
  "Ankara", "Antalya", "Brasov", "Merida", "Izmir",
  "Queretaro", "Timisoara", "Manila", "Colombo", "Guadalajara",
  "Burgas", "Banja Luka", "Iasi", "Pattaya", "Debrecen",
  "Kuala Lumpur", "Johannesburg", "Quito", "Sarajevo", "Plovdiv",
  "Tbilisi", "Erbil", "Hangzhou", "Lima", "Ulaanbaatar",
  "Sibiu", "Chisinau", "Accra", "Skopje", "Casablanca",
  "Bursa", "Baghdad", "Cape Town", "Pretoria", "Moscow",
  "Nairobi", "Baku", "Nis", "Lagos", "Sao Paulo",
  "Rabat", "Chiang Mai", "Marrakech", "Mersin", "Batumi",
  "Cuenca", "Durban", "Ho Chi Minh City", "Jakarta", "Almaty",
  "Kyiv", "Rio de Janeiro", "Medellin", "Brasilia", "Hanoi",
  "Tunis", "Chengdu", "Campinas", "Florianopolis", "Astana",
  "Porto Alegre", "Bogota", "Bishkek", "Dnipro", "Kampala",
  "Belo Horizonte", "Tehran", "Minsk", "Algiers", "Saint Petersburg",
  "Mumbai", "Pristina", "Tashkent", "Curitiba", "Odessa",
  "Gurgaon", "Lviv", "Kharkiv", "Kathmandu", "Dhaka",
  "Asuncion", "Bangalore", "Yekaterinburg", "Pune", "Nizhny Novgorod",
  "Delhi", "Kazan", "Noida", "Krasnodar", "Novosibirsk",
  "Kaliningrad", "Ufa", "Rostov-on-Don", "Hyderabad", "Ahmedabad",
  "Chennai", "Tripoli", "Perm", "Islamabad", "Chandigarh",
  "Vadodara", "Cairo", "Kolkata", "Bhubaneswar", "Kochi",
  "Surat", "Jaipur", "Lucknow", "Karachi", "Lahore",
  "Alexandria", "Coimbatore",

  // Additional major world cities not in the Numbeo 2025 dataset
  "Osaka", "Kyoto", "Yokohama", "Nagoya", "Sapporo",
  "Busan", "Incheon", "Daegu", "Gwangju",
  "Chongqing", "Tianjin", "Wuhan", "Chongqing", "Nanjing",
  "Xi'an", "Dongguan", "Foshan", "Wuxi", "Nanchang",
  "Ho Chi Minh City", "Da Nang", "Hai Phong",
  "Yangon", "Mandalay", "Naypyidaw",
  "Dhaka", "Chittagong",
  "Karachi", "Lahore", "Faisalabad",
  "Kabul", "Kandahar",
  "Kathmandu", "Pokhara",
  "Colombo", "Kandy",
  "Kuala Lumpur", "Penang", "Johor Bahru",
  "Singapore",
  "Bandar Seri Begawan",
  "Dili",
  "Port Moresby",
  "Surabaya", "Bandung", "Medan", "Semarang", "Palembang",
  "Makassar", "Tangerang",
  "Manila", "Quezon City", "Cebu", "Davao",
  "Vientiane", "Luang Prabang",
  "Phnom Penh", "Siem Reap",
  "Yangon",
  "Nairobi", "Mombasa",
  "Dar es Salaam", "Zanzibar",
  "Kampala", "Entebbe",
  "Kigali",
  "Addis Ababa",
  "Accra", "Kumasi",
  "Lagos", "Abuja", "Kano", "Ibadan",
  "Dakar",
  "Abidjan", "Yamoussoukro",
  "Douala", "Yaounde",
  "Kinshasa", "Lubumbashi",
  "Luanda",
  "Maputo",
  "Lusaka",
  "Harare", "Bulawayo",
  "Gaborone",
  "Windhoek",
  "Antananarivo",
  "Casablanca", "Fez", "Tangier",
  "Tunis", "Sfax",
  "Algiers", "Oran", "Constantine",
  "Tripoli", "Benghazi",
  "Cairo", "Giza", "Alexandria", "Luxor",
  "Khartoum", "Omdurman",
  "Mogadishu",
  "Monrovia",
  "Freetown",
  "Conakry",
  "Bamako",
  "Ouagadougou",
  "Niamey",
  "N'Djamena",
  "Libreville",
  "Brazzaville",
  "Bangui",
  "Lome",
  "Porto-Novo", "Cotonou",
  "Nouakchott",
  "Banjul",
  "Bissau",
  "Malabo",
  "Sao Tome",
  "Cape Verde",
  "Juba",
  "Djibouti",
  "Asmara",
  "Moroni",
  "Victoria (Seychelles)",
  "Port Louis (Mauritius)",
  "Antananarivo",
  "Mexico City", "Guadalajara", "Monterrey", "Tijuana", "Puebla",
  "Leon", "Ciudad Juarez", "Cancun", "Merida (Mexico)",
  "Havana", "Santiago de Cuba",
  "San Juan (Puerto Rico)",
  "Kingston (Jamaica)",
  "Port-au-Prince",
  "Santo Domingo",
  "San Salvador",
  "Tegucigalpa",
  "Managua",
  "San Jose (Costa Rica)",
  "Panama City",
  "Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena",
  "Quito", "Guayaquil",
  "Lima", "Arequipa",
  "La Paz", "Santa Cruz",
  "Asuncion",
  "Montevideo",
  "Buenos Aires", "Cordoba", "Rosario", "Mendoza",
  "Santiago", "Valparaiso",
  "Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza",
  "Recife", "Porto Alegre", "Curitiba", "Belo Horizonte", "Manaus",
  "Caracas", "Maracaibo",
  "Georgetown", "Paramaribo",
  "Cayenne",
  "Auckland", "Wellington", "Christchurch", "Dunedin",
  "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra",
  "Darwin", "Hobart",
  "Suva", "Nadi",
  "Noumea",
  "Papeete",
  "Apia",
  "Nukualofa",
  "Honiara",
  "Port Vila",
  "Reykjavik",
  "Dublin", "Cork", "Galway",
  "London", "Manchester", "Birmingham", "Glasgow", "Edinburgh",
  "Liverpool", "Bristol", "Leeds", "Sheffield", "Newcastle",
  "Cardiff", "Belfast",
  "Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven",
  "Brussels", "Antwerp", "Gent", "Bruges", "Liege",
  "Paris", "Lyon", "Marseille", "Toulouse", "Nice",
  "Bordeaux", "Nantes", "Strasbourg", "Montpellier", "Lille",
  "Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt",
  "Stuttgart", "Dusseldorf", "Leipzig", "Dortmund", "Nuremberg",
  "Dresden", "Hanover", "Bremen", "Essen", "Karlsruhe",
  "Aachen", "Mannheim", "Stuttgart",
  "Vienna", "Graz", "Linz", "Salzburg", "Innsbruck",
  "Zurich", "Geneva", "Basel", "Bern", "Lausanne",
  "Oslo", "Bergen", "Trondheim", "Stavanger",
  "Stockholm", "Gothenburg", "Malmo",
  "Copenhagen", "Aarhus", "Odense",
  "Helsinki", "Tampere", "Turku", "Oulu",
  "Tallinn", "Riga", "Vilnius", "Kaunas",
  "Warsaw", "Krakow", "Wroclaw", "Lodz", "Poznan",
  "Prague", "Brno", "Plzen", "Ostrava",
  "Bratislava", "Kosice",
  "Budapest", "Debrecen",
  "Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta", "Brasov",
  "Sofia", "Plovdiv", "Varna", "Burgas",
  "Belgrade", "Novi Sad", "Nis",
  "Zagreb", "Split",
  "Ljubljana",
  "Sarajevo", "Banja Luka",
  "Skopje",
  "Tirana",
  "Podgorica",
  "Pristina",
  "Nicosia", "Limassol", "Larnaca",
  "Athens", "Thessaloniki",
  "Istanbul", "Ankara", "Izmir", "Antalya", "Bursa", "Mersin",
  "Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg",
  "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Omsk", "Samara",
  "Rostov-on-Don", "Ufa", "Krasnodar", "Perm", "Voronezh",
  "Kyiv", "Kharkiv", "Odessa", "Dnipro", "Lviv",
  "Minsk", "Gomel",
  "Chisinau",
  "Tbilisi", "Batumi",
  "Yerevan",
  "Baku",
  "Almaty", "Astana", "Shymkent",
  "Tashkent", "Samarkand",
  "Bishkek", "Osh",
  "Ashgabat",
  "Dushanbe",
  "Ulaanbaatar",
  "Tel Aviv", "Jerusalem", "Haifa",
  "Beirut",
  "Damascus", "Aleppo",
  "Baghdad", "Erbil", "Basra",
  "Amman",
  "Riyadh", "Jeddah", "Mecca", "Medina", "Dammam",
  "Dubai", "Abu Dhabi", "Sharjah",
  "Doha",
  "Manama",
  "Kuwait City",
  "Muscat", "Salalah",
  "Sanaa", "Aden",
  "Tehran", "Mashhad", "Isfahan", "Tabriz", "Shiraz",
];
