// ~500 artists people might guess for most Grammy Awards
export const grammyAwardsHints: string[] = [
  // Top 100 (the actual answers)
  "Beyonce", "Kendrick Lamar", "Georg Solti", "Chick Corea", "Quincy Jones",
  "Alison Krauss", "John Williams", "Pierre Boulez", "David Frost", "Jay-Z",
  "Stevie Wonder", "Vladimir Horowitz", "Kanye West", "Serban Ghenea", "U2",
  "Vince Gill", "Al Schmitt", "Bruce Springsteen", "Henry Mancini", "Kirk Franklin",
  "Pat Metheny", "Yo-Yo Ma", "Paul McCartney", "Aretha Franklin", "CeCe Winans",
  "Eric Clapton", "Jimmy Sturr", "Lady Gaga", "Tony Bennett", "Alicia Keys",
  "Bela Fleck", "Ray Charles", "Sting", "Tom Elmhirst", "Adele",
  "Bruno Mars", "David Foster", "Itzhak Perlman", "Paul Simon", "Ricky Skaggs",
  "T Bone Burnett", "B.B. King", "Eminem", "Foo Fighters", "Leonard Bernstein",
  "Chet Atkins", "Herbie Hancock", "Phil Ramone", "Taylor Swift", "Babyface",
  "Bonnie Raitt", "Ella Fitzgerald", "Emmylou Harris", "Jack Antonoff", "Michael Jackson",
  "Pharrell Williams", "The Chicks", "Jack White", "John Legend", "Shirley Caesar",
  "Willie Nelson", "Alan Menken", "Billie Eilish", "Bobby McFerrin", "Brandi Carlile",
  "Chris Stapleton", "Joni Mitchell", "Linda Ronstadt", "Tina Turner", "Al Jarreau",
  "Arturo Sandoval", "Bob Dylan", "Carlos Santana", "Chaka Khan", "Dolly Parton",
  "Justin Timberlake", "Mark Ronson", "Norah Jones", "Anderson .Paak", "Buddy Guy",
  "Eddie Palmieri", "Mary J. Blige", "Metallica", "Natalie Cole", "Rihanna",
  "Sheryl Crow", "Skrillex", "Wynton Marsalis", "Andre 3000", "Beck",
  "Carrie Underwood", "Count Basie", "John Mayer", "Kacey Musgraves", "Lauryn Hill",
  "Luther Vandross", "Phil Collins", "Robert Plant", "The Beatles", "Usher",
  // Beyond top 100 — pop, rock, hip-hop, country, R&B, jazz, classical, and more
  // Pop & Rock legends
  "Michael Jackson", "Prince", "Madonna", "Whitney Houston", "Elton John",
  "Billy Joel", "Phil Collins", "Genesis", "Peter Gabriel", "Fleetwood Mac",
  "Stevie Nicks", "The Eagles", "Led Zeppelin", "The Rolling Stones", "The Beatles",
  "John Lennon", "George Harrison", "Ringo Starr", "Bob Dylan", "Neil Young",
  "David Bowie", "Queen", "Freddie Mercury", "The Who", "The Doors",
  "Pink Floyd", "Roger Waters", "Jimi Hendrix", "Janis Joplin", "The Beach Boys",
  "Bee Gees", "ABBA", "Elvis Presley", "Frank Sinatra", "Nat King Cole",
  "Dean Martin", "Bing Crosby", "Sammy Davis Jr.", "Louis Armstrong", "Duke Ellington",
  "Count Basie", "Miles Davis", "Dizzy Gillespie", "Charlie Parker", "Thelonious Monk",
  "John Coltrane", "Billie Holiday", "Sarah Vaughan", "Nina Simone", "Dinah Washington",
  // Modern pop
  "Katy Perry", "P!nk", "Sia", "Lorde",
  "Halsey", "Doja Cat", "Megan Thee Stallion", "Normani", "Camila Cabello",
  "Selena Gomez", "Demi Lovato", "Nick Jonas", "Joe Jonas", "Jonas Brothers",
  "Shawn Mendes", "Charlie Puth", "Khalid", "Bazzi", "Bebe Rexha",
  "Carly Rae Jepsen", "Alessia Cara", "Julia Michaels", "Tove Lo", "Charli XCX",
  "Sabrina Carpenter", "Chappell Roan", "Gracie Abrams", "Finneas",
  "Lana Del Rey", "Phoebe Bridgers", "Hozier", "Lewis Capaldi", "George Ezra",
  "Imagine Dragons", "OneRepublic", "Maroon 5", "Coldplay", "Radiohead",
  "Muse", "Arctic Monkeys", "Oasis", "Blur", "Gorillaz",
  "Green Day", "Blink-182", "Fall Out Boy", "Panic! at the Disco", "My Chemical Romance",
  "Paramore", "Twenty One Pilots", "The Killers", "Kings of Leon", "Vampire Weekend",
  "Arcade Fire", "The National", "Bon Iver", "Fleet Foxes", "Mumford & Sons",
  "The Lumineers", "Of Monsters and Men", "Florence and the Machine",
  // Hip-hop & R&B
  "Nas", "Lil Wayne", "Snoop Dogg", "Dr. Dre",
  "Tupac", "Notorious B.I.G.", "50 Cent", "Ice Cube", "Missy Elliott",
  "Lauryn Hill", "OutKast", "Andre 3000", "Big Boi",
  "J. Cole", "Travis Scott", "Future", "Lil Baby", "Gunna",
  "Young Thug", "21 Savage", "Metro Boomin", "A$AP Rocky", "Tyler the Creator",
  "Frank Ocean", "Usher", "Chris Brown", "Ne-Yo",
  "Trey Songz", "Miguel", "Jeremih", "Bryson Tiller", "6LACK",
  "Summer Walker", "Jazmine Sullivan", "Jhene Aiko", "Kehlani", "Victoria Monet",
  "Erykah Badu", "D'Angelo", "Fugees", "TLC",
  "Destiny's Child", "Boyz II Men", "New Edition", "Bobby Brown", "R. Kelly",
  "Luther Vandross", "Teddy Pendergrass", "Marvin Gaye", "Al Green", "Curtis Mayfield",
  "Smokey Robinson", "The Temptations", "The Supremes", "Diana Ross", "Gladys Knight",
  "Patti LaBelle", "Chaka Khan", "Earth Wind & Fire", "Kool and the Gang",
  "Rick James", "George Clinton", "Parliament-Funkadelic",
  "Run-DMC", "LL Cool J", "Beastie Boys", "Public Enemy", "Wu-Tang Clan",
  "Rakim", "Eric B", "A Tribe Called Quest", "De La Soul", "Roots",
  "Common", "Mos Def", "Talib Kweli", "Lupe Fiasco", "Chance the Rapper",
  "Mac Miller", "Logic", "Pusha T", "2 Chainz", "Rick Ross",
  "DJ Khaled", "Pitbull", "Flo Rida", "T-Pain", "Lil Nas X",
  "Jack Harlow", "Ice Spice", "Glorilla",
  "Nicki Minaj", "Saweetie", "City Girls",
  // Country
  "Johnny Cash", "George Strait", "Alan Jackson", "Garth Brooks", "Brooks & Dunn",
  "Reba McEntire", "George Jones", "Merle Haggard", "Hank Williams", "Patsy Cline",
  "Loretta Lynn", "Tammy Wynette", "Kenny Rogers", "Glen Campbell", "Randy Travis",
  "Toby Keith", "Kenny Chesney", "Jason Aldean", "Luke Bryan", "Blake Shelton",
  "Florida Georgia Line", "Thomas Rhett", "Luke Combs", "Morgan Wallen", "Zach Bryan",
  "Miranda Lambert", "Maren Morris", "Kacey Musgraves", "Brandi Carlile", "Sturgill Simpson",
  "Tyler Childers", "Jason Isbell", "Emmylou Harris", "Rodney Crowell",
  "The Chicks", "Shania Twain", "Faith Hill", "Martina McBride", "LeAnn Rimes",
  "Lainey Wilson", "Jelly Roll", "Hardy", "Parker McCollum",
  // Rock & Metal
  "Aerosmith", "AC/DC", "Black Sabbath", "Ozzy Osbourne", "Iron Maiden",
  "Judas Priest", "Megadeth", "Slayer", "Anthrax", "Pantera",
  "Tool", "System of a Down", "Rage Against the Machine", "Audioslave", "Soundgarden",
  "Pearl Jam", "Alice in Chains", "Nirvana", "Stone Temple Pilots", "Smashing Pumpkins",
  "Red Hot Chili Peppers", "Nine Inch Nails", "Linkin Park", "Korn", "Limp Bizkit",
  "Deftones", "Slipknot", "Disturbed", "Godsmack", "Breaking Benjamin",
  "Three Days Grace", "Evanescence", "Nickelback", "Creed", "Staind",
  "Weezer", "The Strokes", "The White Stripes", "Queens of the Stone Age",
  "Tom Morello",
  // Jazz & Classical
  "Wynton Marsalis", "Diana Krall", "Kurt Elling", "Cecile McLorin Salvant",
  "Robert Glasper", "Kamasi Washington", "Snarky Puppy", "Jacob Collier",
  "Itzhak Perlman", "Vladimir Horowitz", "Leonard Bernstein", "Herbert von Karajan",
  "Andre Previn", "James Levine", "Gustavo Dudamel",
  "Joshua Bell", "Hilary Hahn", "Lang Lang", "Yuja Wang", "Murray Perahia",
  "Renee Fleming", "Luciano Pavarotti", "Jose Carreras", "Andrea Bocelli",
  // Latin
  "J Balvin", "Daddy Yankee", "Ozuna", "Anuel AA",
  "Karol G", "Rosalia", "Maluma", "Rauw Alejandro", "Peso Pluma",
  "Marc Anthony", "Ricky Martin", "Enrique Iglesias", "Gloria Estefan", "Celia Cruz",
  "Juanes", "Carlos Santana", "Luis Miguel", "Vicente Fernandez",
  // Electronic & other
  "Daft Punk", "Skrillex", "Diplo", "Calvin Harris", "David Guetta",
  "Deadmau5", "Marshmello", "Avicii", "Tiesto", "The Chainsmokers",
  "Major Lazer", "Disclosure", "ODESZA", "Flume", "Kygo",
  "Weird Al Yankovic", "Bo Burnham", "Jeff Lynne", "ELO",
  "Bjork", "Massive Attack", "Portishead",
  "Tame Impala", "Glass Animals", "Khruangbin", "Black Pumas",
  // More notable artists
  "Celine Dion", "Cher", "Janet Jackson", "Mariah Carey",
  "Dionne Warwick", "Barbra Streisand", "Linda Ronstadt", "Joni Mitchell", "Carole King",
  "James Taylor", "Cat Stevens", "Simon and Garfunkel", "Art Garfunkel",
  "Crosby Stills Nash & Young", "The Band", "Van Morrison", "Tom Petty",
  "Tom Petty and the Heartbreakers", "Bob Seger", "John Mellencamp", "Steve Winwood",
  "ZZ Top", "Lynyrd Skynyrd", "The Allman Brothers Band", "Creedence Clearwater Revival",
  "Chicago", "Steely Dan", "Toto", "Journey", "Boston", "Foreigner", "REO Speedwagon",
  "Def Leppard", "Bon Jovi", "Van Halen", "Guns N' Roses", "Motley Crue",
  "Poison", "Whitesnake", "Scorpions", "Kiss", "Alice Cooper",
  "Depeche Mode", "The Cure", "New Order", "Joy Division", "R.E.M.",
  "Talking Heads", "Blondie", "The Ramones", "The Clash", "Sex Pistols",
  "The Police", "Annie Lennox", "Eurythmics", "George Michael", "Wham!",
  "Pet Shop Boys", "Duran Duran", "Tears for Fears", "Culture Club",
  "Hall & Oates", "The Isley Brothers", "Commodores", "Lionel Richie",
  "Al Jarreau", "Bobby McFerrin", "Take 6", "Manhattan Transfer",
];
