export const highestGrossingTvShowsHints: string[] = [
  'SpongeBob SquarePants', 'The Simpsons', 'Star Trek', 'Power Rangers', 'American Idol',
  'Sesame Street', 'Scooby-Doo', 'The Big Bang Theory', 'Seinfeld', 'Friends',
  'Game of Thrones', 'Law & Order', 'NCIS', 'ER', 'Yellowstone',
  'CSI', 'South Park', 'The Walking Dead', "Grey's Anatomy", 'Survivor',
  'Family Guy', 'Peppa Pig', 'Two and a Half Men', 'Frasier', 'Stranger Things',
  'The Office', 'Squid Game', 'Breaking Bad', 'Everybody Loves Raymond', 'House',
  'Cheers', 'Baywatch', 'The Crown', 'Modern Family', 'Bridgerton',
  'The Sopranos', 'How I Met Your Mother', 'Desperate Housewives', 'Sex and the City', 'The X-Files',
  'Downton Abbey', 'M*A*S*H', '24', 'Supernatural', 'Lost',
  'The Real Housewives', 'Criminal Minds', 'Dancing with the Stars', 'Home Improvement', 'Full House',
  'Roseanne', 'The Mandalorian', 'Married with Children', 'Mad Men', 'Suits',
  'Beverly Hills, 90210', 'Dexter', 'Ozark', 'Sons of Anarchy', 'NCIS: Los Angeles',
  'Blue Bloods', 'Chicago Fire', 'Hawaii Five-0', 'Bones', 'Narcos',
  'True Blood', 'Shameless', 'Money Heist', 'Cobra Kai', 'The Boys',
  'Westworld', 'Homeland', 'Ted Lasso', 'Succession', 'Boardwalk Empire',
  '30 Rock', 'Parks and Recreation', 'The Wire', 'Wednesday', 'Peaky Blinders',
  'Arrested Development', "It's Always Sunny in Philadelphia", 'The Shield', 'Justified', 'Castle',
  'Psych', 'Monk', 'House of the Dragon', 'Emily in Paris', 'The Last of Us',
  'The Bear', 'Severance', 'Abbott Elementary', 'Only Murders in the Building', 'Umbrella Academy',
  'The Witcher', 'Outer Banks', 'Virgin River', 'Invincible', 'Euphoria',
  // Additional plausible guesses
  'Wheel of Fortune', 'Jeopardy!', 'The Price Is Right', 'The Tonight Show', 'Saturday Night Live',
  'Late Night with David Letterman', 'The Late Show', 'Jimmy Kimmel Live', 'Conan', 'The Daily Show',
  '60 Minutes', 'Dateline NBC', '20/20', 'Primetime Live', 'Good Morning America',
  'Today Show', 'Morning Joe', 'Fox & Friends', 'Meet the Press', 'Face the Nation',
  'The Bachelor', 'The Bachelorette', 'Big Brother', 'Amazing Race', 'The Voice',
  "America's Got Talent", 'So You Think You Can Dance', 'Project Runway', 'Top Chef', 'MasterChef',
  "Hell's Kitchen", 'Kitchen Nightmares', 'Bar Rescue', 'Shark Tank', "Dragon's Den",
  'Undercover Boss', 'The Apprentice', 'Celebrity Apprentice', 'Trading Spaces', 'Flip or Flop',
  'The Young and the Restless', 'General Hospital', 'Days of Our Lives', 'The Bold and the Beautiful', 'All My Children',
  'Empire', 'Power', 'Scandal', 'How to Get Away with Murder', 'Quantico',
  'This Is Us', 'Parenthood', 'Brothers & Sisters', 'Ugly Betty',
  'Prison Break', 'Heroes', 'Alias', 'Fringe', 'Person of Interest',
  'Stargate SG-1', 'Battlestar Galactica', 'Dark Matter', 'Firefly', 'The Expanse',
  'Buffy the Vampire Slayer', 'Angel', 'Charmed', 'Sabrina the Teenage Witch', 'Smallville',
  'Arrow', 'The Flash', 'Supergirl', 'Legends of Tomorrow', 'Black Lightning',
  'Dora the Explorer', 'Paw Patrol', 'Thomas & Friends', 'Bob the Builder', 'Blue Clues',
  'Pokemon', 'Dragon Ball Z', 'Naruto', 'One Piece', 'Andor',
  'Dark', 'Lupin', 'Burn Notice', 'White Collar',
];
