// ~500 movies people might guess for highest production budget
export const highestBudgetMoviesHints: string[] = [
  // Top 100 (the actual answers)
  "Pirates of the Caribbean: On Stranger Tides", "Avengers: Age of Ultron", "Avengers: Endgame", "Avengers: Infinity War", "Pirates of the Caribbean: At World's End",
  "Avatar: The Way of Water", "Justice League", "Star Wars: The Force Awakens", "Spider-Man: No Way Home", "Star Wars: The Last Jedi",
  "Star Wars: The Rise of Skywalker", "Tangled", "Transformers: The Last Knight", "Avatar", "The Lion King (2019)",
  "Spectre", "The Dark Knight Rises", "Toy Story 4", "Captain America: Civil War", "Batman v Superman: Dawn of Justice",
  "The Hobbit: The Battle of the Five Armies", "Frozen II", "Finding Dory", "John Carter", "Incredibles 2",
  "Cars 2", "Men in Black 3", "The Amazing Spider-Man 2", "The Hobbit: The Desolation of Smaug", "Thor: Love and Thunder",
  "Black Widow", "Doctor Strange in the Multiverse of Madness", "Eternals", "Shang-Chi", "Jurassic World: Dominion",
  "No Time to Die", "Solo: A Star Wars Story", "The Batman", "Rogue One", "Man of Steel",
  "X-Men: Dark Phoenix", "The Lone Ranger", "Captain Marvel", "Aquaman", "Thor: Ragnarok",
  "Beauty and the Beast (2017)", "Aladdin (2019)", "Dumbo (2019)", "Ralph Breaks the Internet", "Mulan (2020)",
  "Maleficent: Mistress of Evil", "Tenet", "The Jungle Book (2016)", "Transformers: Dark of the Moon", "Fast & Furious 6",
  "Furious 7", "The Fate of the Furious", "Robin Hood (2018)", "Transformers: Age of Extinction", "Oz the Great and Powerful",
  "Green Lantern", "King Arthur: Legend of the Sword", "A Wrinkle in Time", "Mortal Engines", "The BFG",
  "Terminator: Dark Fate", "Gemini Man", "Cats", "Valerian and the City of a Thousand Planets", "Blade Runner 2049",
  "X-Men: Apocalypse", "Independence Day: Resurgence", "The Mummy (2017)", "Ben-Hur (2016)", "Pan",
  "Tomorrowland", "Warcraft", "Ghost in the Shell", "King Kong (2005)", "Spider-Man 3",
  "Waterworld", "Superman Returns", "Quantum of Solace", "The Chronicles of Narnia: Prince Caspian", "Hugo",
  "Cleopatra", "The Matrix Reloaded", "The Matrix Revolutions", "Troy", "Terminator 3",
  "Wild Wild West", "Titanic", "The Polar Express", "Alexander", "Sahara",
  "Treasure Planet", "The Adventures of Pluto Nash", "Stealth", "The 13th Warrior", "Cutthroat Island",
  // Beyond top 100 — major franchise, CGI-heavy, and blockbuster films
  // MCU
  "Iron Man", "Iron Man 2", "Iron Man 3", "The Avengers", "Thor", "Thor: The Dark World",
  "Captain America: The First Avenger", "Captain America: The Winter Soldier",
  "Guardians of the Galaxy", "Guardians of the Galaxy Vol. 2", "Guardians of the Galaxy Vol. 3",
  "Ant-Man", "Ant-Man and the Wasp", "Ant-Man and the Wasp: Quantumania",
  "Black Panther", "Black Panther: Wakanda Forever", "Spider-Man: Homecoming", "Spider-Man: Far From Home",
  "Doctor Strange", "The Incredible Hulk", "The Marvels",
  // DCEU / DC
  "Wonder Woman", "Wonder Woman 1984", "Aquaman and the Lost Kingdom", "The Flash", "Blue Beetle",
  "Shazam!", "Shazam! Fury of the Gods", "Birds of Prey", "The Suicide Squad", "Suicide Squad",
  "Joker", "Joker: Folie a Deux", "The Dark Knight", "Batman Begins", "Batman Forever",
  "Batman & Robin", "Batman Returns", "Batman (1989)", "Superman", "Superman II",
  "Superman III", "Superman IV",
  // Star Wars
  "Star Wars: Episode I - The Phantom Menace", "Star Wars: Episode II - Attack of the Clones",
  "Star Wars: Episode III - Revenge of the Sith", "A New Hope", "The Empire Strikes Back",
  "Return of the Jedi",
  // Harry Potter / Fantastic Beasts
  "Harry Potter and the Philosopher's Stone", "Harry Potter and the Chamber of Secrets",
  "Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Goblet of Fire",
  "Harry Potter and the Order of the Phoenix", "Harry Potter and the Half-Blood Prince",
  "Harry Potter and the Deathly Hallows Part 1", "Harry Potter and the Deathly Hallows Part 2",
  "Fantastic Beasts and Where to Find Them", "Fantastic Beasts: The Crimes of Grindelwald",
  "Fantastic Beasts: The Secrets of Dumbledore",
  // Lord of the Rings / Hobbit
  "The Lord of the Rings: The Fellowship of the Ring", "The Lord of the Rings: The Two Towers",
  "The Lord of the Rings: The Return of the King", "The Hobbit: An Unexpected Journey",
  // Fast & Furious
  "The Fast and the Furious", "2 Fast 2 Furious", "The Fast and the Furious: Tokyo Drift",
  "Fast & Furious", "Fast Five", "Fast X", "Hobbs & Shaw",
  // Transformers
  "Transformers", "Transformers: Revenge of the Fallen", "Bumblebee", "Transformers: Rise of the Beasts",
  // James Bond
  "Casino Royale", "Skyfall", "GoldenEye", "Die Another Day", "The World Is Not Enough",
  "Tomorrow Never Dies", "License to Kill", "The Living Daylights",
  // Mission: Impossible
  "Mission: Impossible", "Mission: Impossible II", "Mission: Impossible III",
  "Mission: Impossible - Ghost Protocol", "Mission: Impossible - Rogue Nation",
  "Mission: Impossible - Fallout", "Mission: Impossible - Dead Reckoning Part One",
  // Jurassic Park/World
  "Jurassic Park", "The Lost World: Jurassic Park", "Jurassic Park III",
  "Jurassic World", "Jurassic World: Fallen Kingdom",
  // Pirates of the Caribbean
  "Pirates of the Caribbean: The Curse of the Black Pearl", "Pirates of the Caribbean: Dead Men Tell No Tales",
  // Disney live-action & animation
  "Frozen", "Moana", "Moana 2", "Zootopia", "Big Hero 6", "Encanto", "Wish",
  "Raya and the Last Dragon", "Strange World", "Lightyear", "Elemental",
  "The Little Mermaid (2023)", "Cruella", "Jungle Cruise", "Maleficent",
  "Cinderella (2015)", "Alice Through the Looking Glass", "The Nutcracker and the Four Realms",
  "Brave", "Wreck-It Ralph", "Inside Out", "Inside Out 2", "Turning Red", "Luca", "Soul", "Onward",
  "The Good Dinosaur", "Coco", "Cars", "Cars 3", "Toy Story 3",
  "Monsters University", "Monsters Inc.", "Finding Nemo", "Up", "WALL-E", "Ratatouille",
  "The Incredibles", "A Bug's Life",
  // Dreamworks / Illumination
  "Shrek", "Shrek 2", "Shrek the Third", "Shrek Forever After",
  "How to Train Your Dragon", "How to Train Your Dragon 2", "How to Train Your Dragon: The Hidden World",
  "Kung Fu Panda", "Kung Fu Panda 2", "Kung Fu Panda 3", "Kung Fu Panda 4",
  "Madagascar", "Madagascar: Escape 2 Africa", "Madagascar 3: Europe's Most Wanted",
  "Despicable Me", "Despicable Me 2", "Despicable Me 3", "Despicable Me 4",
  "Minions", "Minions: The Rise of Gru", "The Super Mario Bros. Movie",
  "Puss in Boots", "Puss in Boots: The Last Wish", "The Boss Baby", "Trolls", "Trolls World Tour",
  "Sing", "Sing 2", "The Secret Life of Pets", "The Secret Life of Pets 2",
  "Migration", "The Bad Guys", "Spirit Untamed",
  // Other big-budget sci-fi/action
  "Inception", "Interstellar", "Dunkirk", "Oppenheimer",
  "The Matrix", "The Matrix Resurrections", "Ready Player One",
  "Gravity", "The Meg", "The Meg 2: The Trench", "Godzilla (2014)", "Godzilla: King of the Monsters",
  "Godzilla vs. Kong", "Kong: Skull Island", "Pacific Rim", "Pacific Rim: Uprising",
  "Dune", "Dune: Part Two", "Arrival", "Prometheus", "Alien: Covenant", "Alien: Romulus",
  "The Martian", "Ad Astra", "Passengers", "Elysium", "Oblivion", "Edge of Tomorrow",
  "Alita: Battle Angel", "The Jungle Book (1967)", "World War Z",
  "I Am Legend", "War of the Worlds", "Minority Report", "A.I. Artificial Intelligence",
  "2012", "The Day After Tomorrow", "Independence Day", "Godzilla (1998)",
  "Armageddon", "Deep Impact", "The Core", "San Andreas", "Geostorm",
  "Twister", "Twisters", "Rampage",
  // X-Men
  "X-Men", "X2", "X-Men: The Last Stand", "X-Men: First Class", "X-Men: Days of Future Past",
  "Logan", "Deadpool", "Deadpool 2", "Deadpool & Wolverine", "The Wolverine",
  "X-Men Origins: Wolverine", "The New Mutants",
  // Spider-Man (Sony)
  "Spider-Man", "Spider-Man 2", "The Amazing Spider-Man",
  "Spider-Man: Into the Spider-Verse", "Spider-Man: Across the Spider-Verse", "Venom",
  "Venom: Let There Be Carnage", "Morbius", "Madame Web", "Kraven the Hunter",
  // Famous flops and big-budget misses
  "Heaven's Gate", "Ishtar", "The Adventures of Baron Munchausen",
  "Battlefield Earth", "Final Fantasy: The Spirits Within", "Gigli",
  "Catwoman", "Speed Racer", "Mars Needs Moms", "Jupiter Ascending",
  "Gods of Egypt", "Monster Trucks", "Geostorm", "Gemini Man",
  "Dark Phoenix", "Fantastic Four (2015)", "The Mummy Returns",
  "Prince of Persia", "The Sorcerer's Apprentice", "Tron: Legacy",
  "Jack the Giant Slayer", "47 Ronin", "R.I.P.D.", "After Earth",
  "Ender's Game", "The Great Wall", "Ghost in the Shell (2017)",
  "Downsizing", "Moonfall", "Red Notice", "The Gray Man",
  // More blockbusters
  "Top Gun: Maverick", "Barbie", "John Wick: Chapter 4", "Indiana Jones and the Dial of Destiny",
  "Napoleon", "Killers of the Flower Moon", "The Hunger Games", "The Hunger Games: Catching Fire",
  "The Hunger Games: Mockingjay Part 1", "The Hunger Games: Mockingjay Part 2",
  "Twilight", "New Moon", "Eclipse", "Breaking Dawn Part 1", "Breaking Dawn Part 2",
  "The Maze Runner", "Divergent", "The Mortal Instruments",
  "Mad Max: Fury Road", "Furiosa", "Gladiator", "Gladiator II",
  "The Revenant", "The Wolf of Wall Street", "Once Upon a Time in Hollywood",
  "Babylon", "Elvis", "Avatar 3",
  "Casino Royale", "Die Hard", "Lethal Weapon", "Total Recall",
  "Robocop", "Demolition Man", "Last Action Hero", "True Lies",
  "Con Air", "The Rock", "Face/Off", "Pearl Harbor", "Bad Boys for Life",
  "Night at the Museum", "Night at the Museum: Battle of the Smithsonian",
  "Willy Wonka", "Wonka", "Charlie and the Chocolate Factory",
  "The Chronicles of Narnia: The Lion the Witch and the Wardrobe",
  "The Chronicles of Narnia: The Voyage of the Dawn Treader",
  "The Golden Compass", "Eragon", "The Spiderwick Chronicles",
  "Percy Jackson & the Olympians: The Lightning Thief", "Percy Jackson: Sea of Monsters",
  "Clash of the Titans (2010)", "Wrath of the Titans",
  "Snow White and the Huntsman", "The Huntsman: Winter's War",
  "Hansel & Gretel: Witch Hunters", "Seventh Son",
  "Noah", "Exodus: Gods and Kings", "Ben-Hur (2016)",
  "Robin Hood (2010)", "King Arthur (2004)", "Gladiator (2000)",
  "Master and Commander", "Kingdom of Heaven", "The Last Samurai",
  "300", "300: Rise of an Empire", "Immortals",
  "Clash of the Titans", "Jason and the Argonauts",
  "Life of Pi", "Hugo", "The Curious Case of Benjamin Button",
  "The Great Gatsby (2013)", "Cloud Atlas",
  "Tomorrowland", "A Quiet Place", "A Quiet Place Part II",
  "Everything Everywhere All at Once", "Nope", "Us", "Get Out",
  "It", "It Chapter Two", "The Conjuring", "Annihilation",
  "The Wizard of Oz", "Ben-Hur (1959)", "Gone with the Wind",
  "Lawrence of Arabia", "Spartacus", "The Ten Commandments",
  "Doctor Dolittle (2020)", "Dolittle", "Mulan (1998)", "The Lion King (1994)",
  "Beauty and the Beast (1991)", "Aladdin (1992)", "The Little Mermaid (1989)",
  "Pocahontas", "Tarzan", "Atlantis: The Lost Empire", "Treasure Planet",
  "Bolt", "Meet the Robinsons", "Chicken Little", "Home on the Range",
  "Brother Bear", "Dinosaur", "Fantasia 2000", "The Emperor's New Groove",
  "Lilo & Stitch", "Spirit: Stallion of the Cimarron",
  "The Prince of Egypt", "Antz", "Bee Movie", "Megamind",
  "Rise of the Guardians", "Mr. Peabody & Sherman", "Penguins of Madagascar",
  "Abominable", "The Croods", "The Croods: A New Age",
];
