// ~500 highest-grossing movies of all time (worldwide box office)
export const highestGrossingMoviesHints: string[] = [
  // Top 100 (the actual answers)
  "Avatar", "Avengers: Endgame", "Avatar: The Way of Water", "Titanic", "Star Wars: The Force Awakens",
  "Avengers: Infinity War", "Spider-Man: No Way Home", "Inside Out 2", "Jurassic World", "The Lion King",
  "The Avengers", "Furious 7", "Frozen II", "Top Gun: Maverick", "Barbie",
  "Avengers: Age of Ultron", "The Super Mario Bros. Movie", "Black Panther", "Harry Potter and the Deathly Hallows Part 2", "Star Wars: The Last Jedi",
  "Jurassic World: Fallen Kingdom", "Frozen", "Beauty and the Beast", "Incredibles 2", "The Fate of the Furious",
  "Iron Man 3", "Minions", "Captain America: Civil War", "Aquaman", "The Lord of the Rings: The Return of the King",
  "Spider-Man: Far From Home", "Captain Marvel", "Transformers: Dark of the Moon", "Skyfall", "Transformers: Age of Extinction",
  "The Dark Knight Rises", "Joker", "Star Wars: The Rise of Skywalker", "Toy Story 4", "Toy Story 3",
  "Pirates of the Caribbean: Dead Man's Chest", "Rogue One", "Aladdin", "Pirates of the Caribbean: On Stranger Tides", "Despicable Me 3",
  "Finding Dory", "Alice in Wonderland", "Zootopia", "The Hobbit: An Unexpected Journey", "The Dark Knight",
  "Harry Potter and the Philosopher's Stone", "Despicable Me 2", "The Jungle Book", "The Hobbit: The Desolation of Smaug", "The Hobbit: The Battle of the Five Armies",
  "Finding Nemo", "Harry Potter and the Deathly Hallows Part 1", "The Lord of the Rings: The Two Towers", "Shrek 2", "Harry Potter and the Order of the Phoenix",
  "Harry Potter and the Half-Blood Prince", "The Lord of the Rings: The Fellowship of the Ring", "Jurassic Park", "Star Wars: Episode I", "Moana",
  "Guardians of the Galaxy Vol. 2", "Spider-Man: Across the Spider-Verse", "Deadpool & Wolverine", "Thor: Ragnarok", "Oppenheimer",
  "Wonder Woman", "Guardians of the Galaxy Vol. 3", "Doctor Strange in the Multiverse of Madness", "Black Panther: Wakanda Forever", "Spider-Man: Homecoming",
  "It", "Venom", "Bohemian Rhapsody", "The Hunger Games: Catching Fire", "Deadpool",
  "The Amazing Spider-Man", "Shrek the Third", "Mission: Impossible - Fallout", "Spider-Man 3", "The Hunger Games",
  "Inception", "Harry Potter and the Prisoner of Azkaban", "Ice Age: Dawn of the Dinosaurs", "Coco", "Kung Fu Panda 2",
  "Batman v Superman: Dawn of Justice", "Puss in Boots: The Last Wish", "Fast & Furious 6", "Madagascar 3", "Shrek Forever After",
  "X-Men: Days of Future Past", "The Chronicles of Narnia: The Lion the Witch and the Wardrobe", "Gravity", "Maleficent", "The Matrix Reloaded",
  // 101–200
  "The Amazing Spider-Man 2", "Spectre", "Mission: Impossible - Dead Reckoning", "Moana 2", "Interstellar",
  "The Hunger Games: Mockingjay Part 1", "Guardians of the Galaxy", "Shrek", "Doctor Strange", "Kung Fu Panda 3",
  "Jumanji: Welcome to the Jungle", "Man of Steel", "Ice Age: Continental Drift", "Monsters University", "Spider-Man 2",
  "Fast Five", "Spider-Man", "Mission: Impossible - Rogue Nation", "John Wick: Chapter 4", "Independence Day",
  "The Incredibles", "Minions: The Rise of Gru", "Venom: Let There Be Carnage", "Iron Man 2", "Thor: Love and Thunder",
  "Despicable Me", "Dawn of the Planet of the Apes", "Night at the Museum", "How to Train Your Dragon 2", "Mamma Mia!",
  "Cars 2", "Ant-Man and the Wasp", "Twilight: Breaking Dawn Part 2", "Sing", "Kung Fu Panda",
  "Men in Black 3", "Iron Man", "How to Train Your Dragon", "Tangled", "Cars 3",
  "Up", "The Secret Life of Pets", "Big Hero 6", "The Twilight Saga: Eclipse", "Mission: Impossible – Ghost Protocol",
  "Star Wars: Episode III", "The Wandering Earth", "Fast X", "Ne Zha", "The Meg",
  "Ready Player One", "The Lion King (1994)", "Prometheus", "Logan", "2012",
  "Ant-Man and the Wasp: Quantumania", "Ant-Man", "Ralph Breaks the Internet", "X-Men: Apocalypse", "Suicide Squad",
  "Casino Royale", "The Mummy Returns", "The Twilight Saga: New Moon", "Brave", "Men in Black",
  "War of the Worlds", "Madagascar: Escape 2 Africa", "The Hunger Games: Mockingjay Part 2", "Cinderella",
  "Thor: The Dark World", "World War Z", "Die Hard 4.0", "300", "Jaws",
  "Night at the Museum: Battle of the Smithsonian", "Godzilla vs. Kong", "Ratatouille", "I Am Legend",
  "Pacific Rim", "Wreck-It Ralph", "Jumanji: The Next Level", "A Quiet Place Part II", "Dumbo",
  "X-Men: The Last Stand", "Life of Pi", "Twilight: Breaking Dawn Part 1",
  // 201–300
  "The Croods: A New Age", "Soul", "Luca", "Encanto", "Shang-Chi and the Legend of the Ten Rings",
  "No Time to Die", "Free Guy", "Cruella", "Jungle Cruise", "Eternals",
  "Dune", "Black Widow", "The Matrix", "The Hangover", "The Hangover Part II",
  "The Mummy", "Troy", "Ocean's Eleven", "War for the Planet of the Apes", "The Revenant",
  "Deadpool 2", "X-Men: First Class", "The Croods", "Puss in Boots", "Hotel Transylvania 3",
  "San Andreas", "Lucy", "Hotel Transylvania 2", "Rio 2", "Rio",
  "The Lego Movie", "Fantastic Beasts and Where to Find Them", "Fantastic Beasts: The Crimes of Grindelwald",
  "Kong: Skull Island", "Rise of the Planet of the Apes", "Fast & Furious Presents: Hobbs & Shaw",
  "The Boss Baby", "Rampage", "A Star Is Born", "Sing 2", "Peter Rabbit",
  "Monsters Inc.", "Alita: Battle Angel", "Taken 2", "Ted", "The Secret Life of Pets 2",
  "Snow White and the Huntsman", "X-Men", "Willy Wonka", "Sherlock Holmes: A Game of Shadows",
  "Sherlock Holmes", "The Da Vinci Code", "Charlie and the Chocolate Factory",
  "Thor", "Captain America: The Winter Soldier", "Captain America: The First Avenger",
  "E.T. the Extra-Terrestrial", "Star Wars: Episode II", "Star Wars: Episode IV", "Star Wars: Episode V",
  "Star Wars: Episode VI", "The Martian", "Gone Girl", "Gladiator", "The Green Mile",
  "Saving Private Ryan", "Armageddon", "Pearl Harbor", "The Day After Tomorrow", "Mr. & Mrs. Smith",
  "Taken", "Ocean's Twelve", "Ocean's Thirteen", "Angels & Demons", "Inferno",
  "The Bourne Ultimatum", "The Bourne Legacy", "Jason Bourne",
  // 301–400
  "Bolt", "Turbo", "Home", "Ferdinand", "Penguins of Madagascar",
  "The Angry Birds Movie", "The Angry Birds Movie 2", "Onward", "Lightyear", "Turning Red",
  "Elemental", "Wish", "Strange World", "Migration", "Wonka",
  "Aquaman and the Lost Kingdom", "The Flash", "Blue Beetle", "Shazam! Fury of the Gods",
  "Dune: Part Two", "Godzilla x Kong: The New Empire", "Furiosa", "The Fall Guy", "Twisters",
  "Beetlejuice Beetlejuice", "Alien: Romulus", "It Ends with Us", "A Quiet Place: Day One",
  "Despicable Me 4", "Kung Fu Panda 4", "Bad Boys: Ride or Die", "The Garfield Movie",
  "Kingdom of the Planet of the Apes", "Ghostbusters: Frozen Empire", "IF", "Abigail",
  "Godzilla: King of the Monsters", "Godzilla",
  "The Wolverine",
  "Wolverine", "Dark Phoenix",
  "The Great Gatsby", "Les Misérables", "A Beautiful Mind", "Forrest Gump",
  "The Shawshank Redemption", "Pulp Fiction", "Fight Club", "The Silence of the Lambs",
  "Schindler's List", "Braveheart", "Good Will Hunting", "Cast Away", "The Sixth Sense",
  "Notting Hill", "Bridget Jones's Diary", "My Big Fat Greek Wedding", "Pretty Woman",
  "Ghost", "Grease", "Rain Man", "Terminator 2: Judgment Day", "Total Recall",
  "Die Hard", "Die Hard 2", "Die Hard with a Vengeance",
  "Lethal Weapon", "Lethal Weapon 2", "Lethal Weapon 3", "Lethal Weapon 4",
  "Beverly Hills Cop", "Beverly Hills Cop II", "Top Gun",
  "Rocky", "Rocky II", "Rocky III", "Rocky IV", "Creed", "Creed II", "Creed III",
  // 401–500+
  "Back to the Future", "Back to the Future Part II", "Back to the Future Part III",
  "Indiana Jones and the Last Crusade", "Indiana Jones and the Temple of Doom",
  "Indiana Jones and the Kingdom of the Crystal Skull", "Indiana Jones and the Dial of Destiny",
  "Raiders of the Lost Ark", "Jurassic Park III", "The Lost World: Jurassic Park",
  "Jurassic World Dominion", "Mission: Impossible", "Mission: Impossible II", "Mission: Impossible III",
  "The Terminator", "Terminator 3: Rise of the Machines", "Terminator Salvation", "Terminator: Dark Fate",
  "Aliens", "Alien 3", "Alien: Covenant", "Alien Resurrection",
  "Predator", "The Predator", "Prey",
  "Blade Runner", "Blade Runner 2049",
  "The Exorcist", "Halloween", "Scream", "Scream 2", "Scream VI",
  "A Nightmare on Elm Street", "Friday the 13th",
  "The Conjuring", "The Conjuring 2", "The Nun", "Annabelle",
  "Insidious", "Get Out", "Us", "Nope",
  "The Batman", "Batman Begins", "Batman", "Batman Returns", "Batman Forever", "Batman & Robin",
  "Superman", "Superman Returns",
  "Wonder Woman 1984", "Justice League", "Zack Snyder's Justice League",
  "The Notebook", "La La Land", "A Walk to Remember",
  "The Fault in Our Stars", "Me Before You", "Fifty Shades of Grey", "Fifty Shades Darker", "Fifty Shades Freed",
  "Twilight", "The Maze Runner", "The Maze Runner: The Scorch Trials", "Divergent", "Insurgent",
  "Ender's Game", "The Giver", "The Mortal Instruments: City of Bones",
  "Fantastic Four", "Fantastic Four: Rise of the Silver Surfer",
  "Green Lantern", "The Green Hornet",
  "Transformers", "Transformers: Revenge of the Fallen", "Transformers: The Last Knight", "Bumblebee",
  "Pacific Rim: Uprising", "Power Rangers",
  "John Wick", "John Wick: Chapter 2", "John Wick: Chapter 3",
  "The Equalizer", "The Equalizer 2", "The Equalizer 3",
  "Nobody", "Atomic Blonde", "The Gray Man",
  "Knives Out", "Glass Onion", "Murder on the Orient Express", "Death on the Nile",
  "Bullet Train", "Everything Everywhere All at Once",
  "The Whale", "Tar", "Elvis", "Babylon",
  "Once Upon a Time in Hollywood", "Django Unchained", "The Hateful Eight", "Kill Bill: Volume 1", "Kill Bill: Volume 2",
  "Inglourious Basterds", "1917", "Dunkirk", "Hacksaw Ridge", "American Sniper",
  "Fury", "Lone Survivor", "Zero Dark Thirty", "Black Hawk Down",
  "Mad Max: Fury Road", "Mad Max", "The Road Warrior",
  "Gladiator II", "Napoleon", "The Northman",
  "The Wolf of Wall Street", "The Big Short", "Moneyball", "The Social Network",
  "Catch Me If You Can", "The Aviator",
];
