// ~250 film franchises/series for hints
export const highestGrossingFranchisesHints: string[] = [
  // Top 50 (the actual answers)
  "Marvel Cinematic Universe", "Spider-Man", "Star Wars", "Wizarding World", "James Bond",
  "Avengers", "X-Men", "Fast & Furious", "DC Extended Universe", "Batman",
  "Jurassic Park", "Avatar", "Middle-earth", "Despicable Me", "Transformers",
  "Mission: Impossible", "Pirates of the Caribbean", "Shrek", "The Twilight Saga", "The Lion King",
  "The Hunger Games", "Toy Story", "Ice Age", "Superman", "Zootopia",
  "Star Trek", "Kung Fu Panda", "Thor", "Inside Out", "Guardians of the Galaxy",
  "Godzilla", "Madagascar", "Indiana Jones", "Captain America", "How to Train Your Dragon",
  "Iron Man", "Black Panther", "Terminator", "The Conjuring Universe", "Planet of the Apes",
  "Jumanji", "MonsterVerse", "Men in Black", "Rocky", "Finding Nemo",
  "The Matrix", "Cars", "Bourne", "The Incredibles", "Aladdin",
  // Additional franchises
  "Alien", "Predator", "Alien vs. Predator", "Top Gun", "Die Hard",
  "Rambo", "Lethal Weapon", "The Expendables", "John Wick", "Jack Reacher",
  "The Equalizer", "The Purge", "RoboCop", "The Mummy", "G.I. Joe",
  "Ghostbusters", "Back to the Future", "Gremlins", "Beetlejuice",
  "The Chronicles of Narnia", "Percy Jackson", "Maze Runner", "Divergent",
  "Halloween", "Friday the 13th", "A Nightmare on Elm Street", "Scream",
  "Child's Play", "Saw", "Insidious", "Paranormal Activity", "Final Destination",
  "It", "The Ring", "Annabelle", "The Nun", "Evil Dead",
  "Frozen", "Moana", "Encanto", "Tangled", "Wreck-It Ralph",
  "Big Hero 6", "Trolls", "Puss in Boots", "Megamind", "The Boss Baby",
  "Hotel Transylvania", "The Addams Family", "The Bad Guys",
  "National Lampoon", "Home Alone", "Ace Ventura", "Police Academy",
  "Pink Panther", "Beverly Hills Cop", "Rush Hour", "Bad Boys",
  "Scary Movie", "Austin Powers", "Night at the Museum",
  "The Hangover", "Ted", "21 Jump Street", "Kingsman",
  "Ocean's", "The Da Vinci Code", "Taken", "The Transporter",
  "Resident Evil", "Underworld", "National Treasure",
  "The Godfather", "Creed", "Mighty Ducks", "Space Jam",
  "Wonder Woman", "Aquaman", "The Flash", "Shazam", "Green Lantern",
  "Deadpool", "Wolverine", "Venom", "Ant-Man", "Doctor Strange",
  "Black Widow", "Captain Marvel", "Shang-Chi", "Eternals",
  "Paddington", "Peter Rabbit", "Garfield", "The Smurfs",
  "Sonic the Hedgehog", "Detective Pikachu", "Angry Birds",
  "Lego Movie", "Minions", "Penguins of Madagascar",
  "Baahubali", "RRR", "Dangal", "Ip Man",
  "Police Story", "Doraemon", "Dragon Ball",
  "One Piece Film", "Naruto", "Demon Slayer",
  "Jujutsu Kaisen", "Attack on Titan", "My Hero Academia",
  "Wicked", "Mamma Mia", "Grease", "Chicago",
  "Bohemian Rhapsody", "Rocketman", "Elvis",
  "The Dollars Trilogy", "Lone Ranger", "Zorro",
  "Harry Potter", "Fantastic Beasts", "Lord of the Rings", "The Hobbit",
  "Hunger Games", "Catching Fire", "Mockingjay",
  "Fast and Furious", "Furious 7", "F9",
  "Spider-Verse", "Sam Raimi Spider-Man", "Amazing Spider-Man",
  "The Dark Knight Trilogy", "Tim Burton Batman",
  "Nolan Batman", "Snyder Cut",
  "Alien Franchise", "Prometheus", "Covenant",
  "Blade Runner", "Total Recall", "Minority Report",
  "War of the Worlds", "Ready Player One",
  "Clash of the Titans", "Prince of Persia", "Gods of Egypt",
  "King Arthur", "Robin Hood", "Hercules",
  "Croods", "Lightyear", "Elemental", "Wish", "Strange World",
];
