export const highestPayingMajorsHints: string[] = [
  // === Top 50 (answers) ===
  "Computer Science",
  "Computer Engineering",
  "Chemical Engineering",
  "Electrical Engineering",
  "Aerospace Engineering",
  "Industrial Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Physics",
  "Finance",
  "Economics",
  "Business Analytics",
  "Construction Management",
  "General Engineering",
  "Mathematics",
  "Nursing",
  "Information Systems",
  "Accounting",
  "International Relations",
  "Statistics",
  "General Business",
  "Marketing",
  "Business Management",
  "Chemistry",
  "Pharmacy",
  "Medical Technology",
  "Nutrition Sciences",
  "Political Science",
  "Environmental Engineering",
  "Biomedical Engineering",
  "Materials Science",
  "Software Engineering",
  "Journalism",
  "Supply Chain Management",
  "Biochemistry",
  "Architecture",
  "Health Administration",
  "Biology",
  "Actuarial Science",
  "Criminal Justice",
  "Communications",
  "Public Health",
  "Graphic Design",
  "Psychology",
  "English",
  "Sociology",
  "History",
  "Education",
  "Social Work",
  "Fine Arts",
  // === Additional majors (not in top 50) ===
  // -- Engineering --
  "Agricultural Engineering", "Architectural Engineering",
  "Biological Engineering", "Ceramic Engineering", "Geological Engineering",
  "Marine Engineering", "Metallurgical Engineering", "Mining Engineering",
  "Nuclear Engineering", "Ocean Engineering", "Optical Engineering",
  "Petroleum Engineering", "Structural Engineering", "Systems Engineering",
  "Textile Engineering", "Transportation Engineering",
  // -- Computer & IT --
  "Information Technology", "Cybersecurity", "Data Science",
  "Artificial Intelligence", "Game Design", "Web Development",
  "Network Administration", "Cloud Computing", "Database Administration",
  "Computer Graphics", "Human-Computer Interaction", "Robotics",
  "Computer Networking", "Digital Forensics",
  // -- Business & Finance --
  "Entrepreneurship", "Real Estate", "Risk Management",
  "Insurance", "Banking", "International Business",
  "Management Information Systems", "Operations Management",
  "Organizational Leadership", "Hospitality Management",
  "Sports Management", "Event Management", "Fashion Merchandising",
  "Retail Management", "Human Resources Management",
  "Public Administration", "Nonprofit Management",
  "Healthcare Management", "Project Management", "Logistics",
  // -- Sciences --
  "Astronomy", "Astrophysics", "Atmospheric Science",
  "Biophysics", "Botany", "Ecology", "Entomology",
  "Genetics", "Geology", "Geophysics", "Marine Biology",
  "Meteorology", "Microbiology", "Molecular Biology",
  "Neuroscience", "Oceanography", "Paleontology",
  "Pharmacology", "Zoology", "Forensic Science",
  "Environmental Science", "Food Science", "Animal Science",
  "Plant Science", "Soil Science", "Wildlife Biology",
  // -- Health --
  "Pre-Med", "Pre-Dental", "Pre-Veterinary",
  "Dental Hygiene", "Physical Therapy", "Occupational Therapy",
  "Speech-Language Pathology", "Kinesiology",
  "Exercise Science", "Athletic Training", "Respiratory Therapy",
  "Radiologic Technology", "Nuclear Medicine Technology",
  "Clinical Laboratory Science", "Health Informatics",
  "Epidemiology", "Biostatistics", "Global Health",
  "Health Education", "Medical Imaging",
  // -- Arts & Humanities --
  "Art History", "Philosophy", "Religious Studies",
  "Classics", "Comparative Literature", "Creative Writing",
  "Film Studies", "Theater", "Music",
  "Dance", "Photography", "Painting",
  "Sculpture", "Printmaking", "Ceramics",
  "Industrial Design", "Interior Design", "Fashion Design",
  "Animation", "Illustration", "Visual Communications",
  "Music Education", "Music Performance", "Music Theory",
  "Music Production", "Jazz Studies",
  // -- Social Sciences --
  "Anthropology", "Gender Studies", "Ethnic Studies",
  "Geography", "International Studies", "Linguistics",
  "Public Policy", "Urban Planning", "Archaeology",
  "Demography", "Gerontology", "Human Development",
  "Family Studies", "Child Development",
  // -- Education --
  "Elementary Education", "Secondary Education",
  "Special Education", "Early Childhood Education",
  "Educational Leadership", "Curriculum and Instruction",
  "Reading Education", "ESL Education",
  "Physical Education",
  "Art Education", "Mathematics Education",
  "Science Education",
  // -- Communications & Media --
  "Advertising", "Public Relations", "Broadcasting",
  "Digital Media", "Film Production", "Media Studies",
  "Technical Writing", "Speech Communication",
  "Mass Communications", "Telecommunications",
  // -- Languages --
  "Spanish", "French", "German", "Chinese", "Japanese",
  "Arabic", "Russian", "Italian", "Portuguese", "Korean",
  "American Sign Language", "Translation Studies",
  // -- Agriculture --
  "Agricultural Business", "Agricultural Economics",
  "Agronomy", "Horticulture", "Forestry",
  "Natural Resources Management", "Range Management",
  "Agricultural Education", "Viticulture",
  // -- Other --
  "Library Science", "Parks and Recreation",
  "Military Science", "Naval Science",
  "Aviation", "Homeland Security",
  "Fire Science", "Emergency Management",
  "Legal Studies", "Paralegal Studies",
  "Culinary Arts", "Mortuary Science",
  "Textile Science", "Consumer Sciences",
  "Applied Mathematics", "Cognitive Science",
  "Computational Biology", "Urban Studies",
  "Women's Studies", "Peace Studies",
  "Sustainability Studies", "Museum Studies",
  "Archival Studies", "Information Science",
  "Bioinformatics", "Nanotechnology",
  "Renewable Energy", "Environmental Policy",
];
