// ~1800 athletes for hints
export const highestPaidAthletesHints: string[] = [
  // Top 100 (the actual answers)
  "Cristiano Ronaldo", "Lionel Messi", "LeBron James", "Giannis Antetokounmpo", "Kylian Mbappe",
  "Lamar Jackson", "Luka Doncic", "Stephen Curry", "Canelo Alvarez", "Neymar",
  "Jude Bellingham", "Jaylen Brown", "Joe Burrow", "Dak Prescott", "Patrick Mahomes",
  "Erling Haaland", "Karim Benzema", "Nikola Jokic", "Joel Embiid",
  "Kevin Durant", "Jalen Hurts", "Jon Rahm", "Mohamed Salah", "Lewis Hamilton",
  "Scottie Scheffler", "Vinicius Junior", "Max Verstappen",
  "Jimmy Butler", "Kawhi Leonard", "Anthony Edwards", "Aaron Judge", "Shohei Ohtani",
  "Justin Herbert", "Trae Young", "Anthony Davis", "Kyrie Irving", "Paul George",
  "Deshaun Watson", "Karl-Anthony Towns", "Damian Lillard",
  "Bradley Beal", "Devin Booker", "Rudy Gobert", "Mike Trout",
  "Jake Paul", "Naoya Inoue", "Blake Snell", "Riyad Mahrez", "Zach LaVine",
  "Joaquin Niemann", "Jamal Murray", "Lauri Markkanen", "Franz Wagner", "Geno Smith",
  "Domantas Sabonis", "Michael Porter Jr.", "Darius Garland", "Cam Ward", "Tyrese Maxey",
  "Cade Cunningham", "Rashawn Slater", "Gerrit Cole", "Anthony Rendon", "Sam Darnold",
  "Zack Wheeler", "Robert Lewandowski", "Harry Kane", "Zion Williamson",
  "Josh Allen", "Travis Kelce", "Jamal Adams", "Alexander Ovechkin", "Connor McDavid",
  "Tiger Woods", "Roger Federer", "Novak Djokovic", "Rafael Nadal", "Tyson Fury",
  "Conor McGregor", "Kevin De Bruyne", "Bukayo Saka",
  "Sadio Mane", "Marcus Rashford", "Phil Foden", "Rodri", "Florian Wirtz",
  "Jadon Sancho", "Trent Alexander-Arnold", "Declan Rice", "Martin Odegaard", "Bruno Fernandes",
  "Casemiro", "Darwin Nunez", "Federico Valverde", "Bernardo Silva", "Lautaro Martinez",
  "Dani Olmo", "Pedri", "Aurelien Tchouameni", "Eduardo Camavinga", "Achraf Hakimi",
  "Ousmane Dembele", "Randal Kolo Muani", "Bradley Barcola", "Jamal Musiala", "Leroy Sane",
  "Joshua Kimmich", "Serge Gnabry", "Thomas Muller", "Manuel Neuer", "Matthijs de Ligt",
  "Frenkie de Jong", "Raphinha", "Jules Kounde", "Ronald Araujo", "Ferran Torres",

  // ==================== BASKETBALL (NBA) ====================
  // Legends & retired
  "Michael Jordan", "Kobe Bryant", "Kareem Abdul-Jabbar", "Wilt Chamberlain", "Magic Johnson",
  "Larry Bird", "Shaquille O'Neal", "Tim Duncan", "Allen Iverson", "Dwyane Wade",
  "Bill Russell", "Oscar Robertson", "Jerry West", "Hakeem Olajuwon", "Charles Barkley",
  "Karl Malone", "John Stockton", "Patrick Ewing", "Scottie Pippen", "David Robinson",
  "Isiah Thomas", "Reggie Miller", "Ray Allen", "Paul Pierce", "Gary Payton",
  "Jason Kidd", "Steve Nash", "Dirk Nowitzki", "Kevin Garnett", "Vince Carter",
  "Tracy McGrady", "Carmelo Anthony", "Chris Bosh", "Pau Gasol", "Manu Ginobili",
  "Tony Parker", "Yao Ming", "Dikembe Mutombo", "Dennis Rodman", "Ben Wallace",
  "Rasheed Wallace", "Chauncey Billups", "Dwight Howard", "Rajon Rondo", "Derrick Rose",
  "Blake Griffin", "DeAndre Jordan", "LaMarcus Aldridge", "DeMar DeRozan", "Kyle Lowry",
  // Current NBA
  "Chris Paul", "James Harden", "Russell Westbrook", "Ja Morant",
  "Jayson Tatum", "Donovan Mitchell", "Shai Gilgeous-Alexander", "Victor Wembanyama", "Chet Holmgren",
  "Paolo Banchero", "Tyrese Haliburton", "De'Aaron Fox", "Jalen Brunson", "Julius Randle",
  "Bam Adebayo", "Tyler Herro", "Fred VanVleet", "Pascal Siakam", "OG Anunoby",
  "Jalen Williams", "Alperen Sengun", "Evan Mobley", "Scottie Barnes", "Darius Garland",
  "Jaren Jackson Jr.", "Desmond Bane", "Anfernee Simons", "Mikal Bridges", "Cameron Johnson",
  "Myles Turner", "Buddy Hield", "Terry Rozier", "LaMelo Ball", "Lonzo Ball",
  "Brandon Ingram", "Dejounte Murray", "Trey Murphy III", "Herb Jones", "CJ McCollum",
  "Khris Middleton", "Brook Lopez", "Bobby Portis", "Jrue Holiday", "Kristaps Porzingis",
  "Al Horford", "Derrick White", "Marcus Smart", "Robert Williams III", "Malcolm Brogdon",
  "Immanuel Quickley", "RJ Barrett", "Josh Hart", "Donte DiVincenzo", "Isaiah Hartenstein",
  "Nikola Vucevic", "Zach Collins", "Coby White", "Ayo Dosunmu", "Alex Caruso",
  "Deandre Ayton", "Kevin Huerter", "Keegan Murray", "Domantas Sabonis", "Harrison Barnes",
  "Andrew Wiggins", "Jonathan Kuminga", "Moses Moody", "Gary Payton II", "Klay Thompson",
  "Draymond Green", "Chris Duarte", "Bennedict Mathurin", "Aaron Nesmith", "Walker Kessler",
  "Lauri Markkanen", "Jordan Clarkson", "Collin Sexton", "John Collins", "Clint Capela",
  "Bogdan Bogdanovic", "Nikola Jovic", "Jaime Jaquez Jr.", "Josh Giddey", "Luguentz Dort",
  "Jerami Grant", "Caris LeVert", "Keldon Johnson", "Tre Jones", "Jeremy Sochan",
  "Scoot Henderson", "Amen Thompson", "Ausar Thompson", "Gradey Dick", "Cam Thomas",
  "Nick Richards", "Mark Williams", "Brandon Miller", "Taylor Hendricks", "Keyonte George",
  "Dereck Lively II", "Brandin Podziemski", "Trayce Jackson-Davis", "Jarace Walker",
  "Alexandre Sarr", "Zaccharie Risacher", "Reed Sheppard", "Stephon Castle",

  // ==================== FOOTBALL (NFL) ====================
  // Legends & retired
  "Tom Brady", "Aaron Rodgers", "Peyton Manning", "Drew Brees", "Dan Marino",
  "Joe Montana", "Brett Favre", "John Elway", "Terry Bradshaw", "Troy Aikman",
  "Jim Kelly", "Warren Moon", "Steve Young", "Kurt Warner", "Eli Manning",
  "Philip Rivers", "Ben Roethlisberger", "Russell Wilson", "Cam Newton", "Andrew Luck",
  "Tony Romo", "Michael Vick", "Donovan McNabb", "Matt Ryan", "Carson Palmer",
  "Barry Sanders", "Walter Payton", "Jim Brown", "Emmitt Smith", "Adrian Peterson",
  "LaDainian Tomlinson", "Marshawn Lynch", "Le'Veon Bell", "Todd Gurley", "Ezekiel Elliott",
  "Jerry Rice", "Randy Moss", "Terrell Owens", "Calvin Johnson", "Larry Fitzgerald",
  "Andre Johnson", "Antonio Brown", "Julio Jones", "DeAndre Hopkins", "Odell Beckham Jr.",
  "Rob Gronkowski", "Tony Gonzalez", "Shannon Sharpe", "Jason Witten", "Jimmy Graham",
  "J.J. Watt", "Lawrence Taylor", "Ray Lewis", "Dick Butkus", "Deion Sanders",
  "Ed Reed", "Troy Polamalu", "Brian Urlacher", "Luke Kuechly", "Von Miller",
  "Khalil Mack", "Joey Bosa", "Chase Young", "Aidan Hutchinson", "Will Anderson Jr.",
  // Current NFL
  "Tua Tagovailoa", "Jordan Love", "C.J. Stroud", "Bryce Young", "Anthony Richardson",
  "Brock Purdy", "Jared Goff", "Matthew Stafford", "Baker Mayfield", "Kyler Murray",
  "Trevor Lawrence", "Kenny Pickett", "Daniel Jones", "Kirk Cousins", "Derek Carr",
  "Jalen Hurts", "Caleb Williams", "Drake Maye", "Jayden Daniels", "Bo Nix",
  "Nick Bosa", "Micah Parsons", "T.J. Watt", "Myles Garrett", "Aaron Donald",
  "Derrick Henry", "Saquon Barkley", "Christian McCaffrey", "Jonathan Taylor", "Austin Ekeler",
  "Josh Jacobs", "Joe Mixon", "Tony Pollard", "Breece Hall", "Rhamondre Stevenson",
  "Bijan Robinson", "Jahmyr Gibbs", "De'Von Achane", "Kenneth Walker III", "Isiah Pacheco",
  "Tyreek Hill", "Justin Jefferson", "Ja'Marr Chase", "CeeDee Lamb", "Stefon Diggs",
  "A.J. Brown", "DeVonta Smith", "Amon-Ra St. Brown", "Deebo Samuel", "DK Metcalf",
  "Chris Olave", "Garrett Wilson", "Drake London", "Jaylen Waddle", "Davante Adams",
  "Mike Evans", "Chris Godwin", "Keenan Allen", "Puka Nacua", "Nico Collins",
  "Brandon Aiyuk", "Terry McLaurin", "Amari Cooper", "Diontae Johnson", "DJ Moore",
  "George Kittle", "Mark Andrews", "T.J. Hockenson", "Dallas Goedert", "Sam LaPorta",
  "Trent Williams", "Penei Sewell", "Quenton Nelson", "Zack Martin", "Tristan Wirfs",
  "Maxx Crosby", "Chris Jones", "Dexter Lawrence", "Cameron Heyward", "Quinnen Williams",
  "Fred Warner", "Roquan Smith", "Foyesade Oluokun", "Zack Baun", "Lavonte David",
  "Sauce Gardner", "Pat Surtain II", "Jalen Ramsey", "Marshon Lattimore", "Trevon Diggs",
  "Derwin James", "Jessie Bates III", "Budda Baker", "Minkah Fitzpatrick", "Kyle Hamilton",
  "Justin Tucker", "Harrison Butker", "Jake Moody", "Tyler Bass", "Younghoe Koo",

  // ==================== SOCCER / FOOTBALL ====================
  // Legends & retired
  "Pele", "Diego Maradona", "Zinedine Zidane", "Ronaldinho", "Ronaldo Nazario",
  "Thierry Henry", "Andrea Pirlo", "Xavi", "Andres Iniesta", "Sergio Ramos",
  "Gerard Pique", "David Beckham", "Wayne Rooney", "Frank Lampard", "Steven Gerrard",
  "Patrick Vieira", "Dennis Bergkamp", "Roberto Carlos", "Cafu", "Paolo Maldini",
  "Franco Baresi", "Marco van Basten", "Ruud Gullit", "Johan Cruyff", "Franz Beckenbauer",
  "Gerd Muller", "Eusebio", "Alfredo Di Stefano", "Ferenc Puskas", "Bobby Charlton",
  "George Best", "Lev Yashin", "Garrincha", "Rivaldo", "Romario",
  "Raul", "Iker Casillas", "Gianluigi Buffon", "Carles Puyol", "Dani Alves",
  "Samuel Eto'o", "Didier Drogba", "Michael Ballack", "Kaka", "Zlatan Ibrahimovic",
  "Luis Suarez", "Edinson Cavani", "Angel Di Maria", "Giorgio Chiellini", "Leonardo Bonucci",
  "Arjen Robben", "Franck Ribery", "Bastian Schweinsteiger", "Phillip Lahm", "Miroslav Klose",
  "Thomas Muller", "David Villa", "Fernando Torres", "Cesc Fabregas", "Sergio Busquets",
  "Mesut Ozil", "Toni Kroos", "Luka Modric", "Gareth Bale", "James Rodriguez",
  "Pierre-Emerick Aubameyang", "Alexis Sanchez", "Nani", "Robin van Persie", "Michael Owen",
  "Alan Shearer", "Eric Cantona", "Roy Keane", "Paul Scholes", "Ryan Giggs",
  "Rio Ferdinand", "John Terry", "Ashley Cole", "Sol Campbell", "Gary Neville",
  "Peter Schmeichel", "Edwin van der Sar", "Petr Cech", "Oliver Kahn", "Manuel Neuer",
  // Current soccer — Premier League
  "Virgil van Dijk", "Alisson", "Ederson", "Thibaut Courtois",
  "Son Heung-min", "Richarlison", "James Maddison", "Kai Havertz",
  "Gabriel Jesus", "Gabriel Martinelli", "William Saliba", "Ben White", "Leandro Trossard",
  "Ollie Watkins", "Alexander Isak", "Eberechi Eze", "Michael Olise", "Ivan Toney",
  "Dominik Szoboszlai", "Alexis Mac Allister", "Luis Diaz", "Diogo Jota", "Cody Gakpo",
  "Cole Palmer", "Enzo Fernandez", "Moises Caicedo", "Nicolas Jackson", "Noni Madueke",
  "Jarrod Bowen", "Lucas Paqueta", "Mohammed Kudus", "Anthony Gordon", "Harvey Barnes",
  "Bruno Guimaraes", "Sandro Tonali", "Pedro Neto", "Brennan Johnson", "Micky van de Ven",
  "Destiny Udogie", "Yves Bissouma", "Dejan Kulusevski", "Josko Gvardiol", "Jeremy Doku",
  "Julian Alvarez", "Mateo Kovacic", "Jack Grealish", "Erling Haaland",
  // Current soccer — La Liga
  "Antoine Griezmann", "Alvaro Morata", "Jan Oblak",
  "Joao Felix", "Alexander Sorloth", "Ilkay Gundogan", "Gavi", "Ansu Fati",
  "Fermin Lopez", "Marc-Andre ter Stegen", "Lamine Yamal", "Pau Cubarsi",
  "Jude Bellingham", "Vinicius Junior", "Rodrygo", "Arda Guler", "Thibaut Courtois",
  "Antonio Rudiger", "David Alaba", "Eder Militao", "Dani Carvajal",
  // Current soccer — Serie A
  "Dusan Vlahovic", "Victor Osimhen", "Khvicha Kvaratskhelia", "Rafael Leao",
  "Mike Maignan", "Theo Hernandez", "Nicolo Barella", "Hakan Calhanoglu",
  "Alessandro Bastoni", "Paulo Dybala", "Tammy Abraham", "Ciro Immobile",
  "Romelu Lukaku", "Federico Chiesa", "Ademola Lookman", "Gianluca Scamacca",
  // Current soccer — Bundesliga
  "Serge Gnabry", "Harry Kane",
  "Leroy Sane", "Florian Wirtz", "Jamal Musiala",
  "Xavi Simons", "Dani Olmo", "Loïs Openda", "Christopher Nkunku",
  "Nico Schlotterbeck", "Jonathan Tah", "Gregor Kobel",
  // Current soccer — Ligue 1
  "Ousmane Dembele", "Randal Kolo Muani", "Bradley Barcola",
  "Gianluigi Donnarumma", "Marquinhos", "Vitinha", "Warren Zaire-Emery",
  "Jonathan David", "Amine Gouiri", "Alexandre Lacazette",
  // Current soccer — Other leagues / international
  "Cristian Romero", "Emiliano Martinez", "Angel Correa", "Rodrigo De Paul",
  "Emi Buendia", "Thiago Almada", "Kaoru Mitoma", "Takefusa Kubo", "Daichi Kamada",
  "Alphonso Davies", "Jonathan David", "Hwang Hee-chan", "Kim Min-jae",
  "Moises Caicedo", "Pervis Estupinan", "Miguel Almiron",
  "Riyad Mahrez", "Hakim Ziyech", "Achraf Hakimi",
  // MLS
  "Lionel Messi", "Lorenzo Insigne", "Xherdan Shaqiri", "Riqui Puig",
  "Hector Herrera", "Chicharito", "Carlos Vela", "Josef Martinez",
  "Cucho Hernandez", "Lucho Acosta", "Thiago Almada", "Giorgos Giakoumakis",

  // ==================== TENNIS ====================
  // Legends & retired
  "Serena Williams", "Venus Williams", "Pete Sampras", "Andre Agassi", "John McEnroe",
  "Bjorn Borg", "Jimmy Connors", "Boris Becker", "Stefan Edberg", "Ivan Lendl",
  "Arthur Ashe", "Rod Laver", "Ken Rosewall", "Billie Jean King", "Martina Navratilova",
  "Chris Evert", "Steffi Graf", "Monica Seles", "Justine Henin", "Kim Clijsters",
  "Marat Safin", "Lleyton Hewitt", "Andy Roddick", "Gustavo Kuerten", "Jim Courier",
  "Mats Wilander", "Yevgeny Kafelnikov", "Patrick Rafter", "Thomas Muster",
  "Maria Sharapova", "Ana Ivanovic", "Jelena Jankovic", "Amelie Mauresmo", "Lindsay Davenport",
  "Juan Martin del Potro", "David Ferrer", "Jo-Wilfried Tsonga", "Gael Monfils",
  "Andy Murray", "Stan Wawrinka", "Kei Nishikori", "Grigor Dimitrov", "Dominic Thiem",
  "Li Na", "Naomi Osaka", "Ashleigh Barty", "Simona Halep", "Angelique Kerber",
  "Bianca Andreescu", "Victoria Azarenka",
  // Current tennis
  "Carlos Alcaraz", "Jannik Sinner", "Daniil Medvedev", "Alexander Zverev", "Stefanos Tsitsipas",
  "Aryna Sabalenka", "Iga Swiatek", "Coco Gauff", "Jessica Pegula", "Elena Rybakina",
  "Casper Ruud", "Holger Rune", "Felix Auger-Aliassime", "Frances Tiafoe", "Ben Shelton",
  "Taylor Fritz", "Tommy Paul", "Hubert Hurkacz", "Andrey Rublev", "Karen Khachanov",
  "Alex de Minaur", "Lorenzo Musetti", "Ugo Humbert", "Jiri Lehecka", "Jack Draper",
  "Jasmine Paolini", "Qinwen Zheng", "Mirra Andreeva", "Donna Vekic", "Marketa Vondrousova",
  "Ons Jabeur", "Caroline Garcia", "Maria Sakkari", "Karolina Muchova", "Danielle Collins",
  "Madison Keys", "Barbora Krejcikova", "Beatriz Haddad Maia", "Ekaterina Alexandrova",
  "Anna Kalinskaya", "Elina Svitolina", "Emma Raducanu", "Leylah Fernandez",
  "Sebastian Korda", "Christopher Eubanks", "Brandon Nakashima", "Zhizhen Zhang",

  // ==================== BASEBALL (MLB) ====================
  // Legends & retired
  "Babe Ruth", "Hank Aaron", "Willie Mays", "Ted Williams", "Derek Jeter",
  "Alex Rodriguez", "Barry Bonds", "Ken Griffey Jr.", "Mike Piazza", "Cal Ripken Jr.",
  "Jackie Robinson", "Lou Gehrig", "Joe DiMaggio", "Mickey Mantle", "Roberto Clemente",
  "Sandy Koufax", "Nolan Ryan", "Tom Seaver", "Bob Gibson", "Greg Maddux",
  "Roger Clemens", "Pedro Martinez", "Randy Johnson", "Mariano Rivera", "Trevor Hoffman",
  "Tony Gwynn", "Wade Boggs", "Rickey Henderson", "Ozzie Smith", "Craig Biggio",
  "Jeff Bagwell", "Ivan Rodriguez", "Mike Schmidt", "George Brett", "Paul Molitor",
  "Chipper Jones", "Frank Thomas", "Albert Pujols", "David Ortiz", "Ichiro Suzuki",
  "Miguel Cabrera", "Robinson Cano", "CC Sabathia", "Justin Verlander", "Clayton Kershaw",
  "Roy Halladay", "John Smoltz", "Curt Schilling", "Sammy Sosa", "Mark McGwire",
  "Jim Thome", "Eddie Murray", "Andre Dawson", "Ryne Sandberg", "Kirby Puckett",
  // Current MLB
  "Mookie Betts", "Juan Soto", "Ronald Acuna Jr.", "Trea Turner", "Corey Seager",
  "Freddie Freeman", "Bryce Harper", "Manny Machado", "Fernando Tatis Jr.", "Yoshinobu Yamamoto",
  "Julio Rodriguez", "Corbin Carroll", "Bobby Witt Jr.", "Gunnar Henderson", "Elly De La Cruz",
  "Adley Rutschman", "Spencer Strider", "Kodai Senga", "Corbin Burnes", "Shane McClanahan",
  "Logan Webb", "Kevin Gausman", "Marcus Semien", "Jose Ramirez", "Matt Olson",
  "Pete Alonso", "Rafael Devers", "Vladimir Guerrero Jr.", "Bo Bichette", "Wander Franco",
  "Jazz Chisholm Jr.", "Ke'Bryan Hayes", "Austin Riley", "Dansby Swanson", "Carlos Correa",
  "Francisco Lindor", "Marcus Stroman", "Max Scherzer", "Jacob deGrom", "Zack Greinke",
  "Yu Darvish", "Chris Sale", "Max Fried", "Ranger Suarez", "Framber Valdez",
  "Yordan Alvarez", "Kyle Tucker", "Alex Bregman", "Jose Altuve", "Jeremy Pena",
  "Nolan Arenado", "Paul Goldschmidt", "Lars Nootbaar", "Ryan Helsley", "Jordan Walker",
  "Cody Bellinger", "Ian Happ", "Nico Hoerner", "Dansby Swanson", "Christopher Morel",
  "Byron Buxton", "Carlos Rodon", "Royce Lewis", "Edouard Julien", "Pablo Lopez",
  "Emmanuel Clase", "Josh Naylor", "Steven Kwan", "Andres Gimenez", "Shane Bieber",
  "Tyler Glasnow", "Mookie Betts", "Will Smith", "Gavin Lux", "James Outman",
  "Jackson Chourio", "Willy Adames", "Christian Yelich", "Devin Williams", "Freddy Peralta",
  "Masataka Yoshida", "Jarren Duran", "Triston Casas", "Tanner Houck", "Brayan Bello",
  "Anthony Volpe", "Gleyber Torres", "Giancarlo Stanton", "Nestor Cortes", "Luis Gil",
  "Spencer Torkelson", "Riley Greene", "Tarik Skubal", "Kerry Carpenter", "Matt Manning",

  // ==================== GOLF ====================
  // Legends & retired
  "Jack Nicklaus", "Arnold Palmer", "Gary Player", "Tom Watson", "Lee Trevino",
  "Seve Ballesteros", "Nick Faldo", "Greg Norman", "Ernie Els", "Vijay Singh",
  "Fred Couples", "Bernhard Langer", "Ian Woosnam", "Nick Price", "Mark O'Meara",
  "Payne Stewart", "Raymond Floyd", "Hale Irwin", "Johnny Miller", "Chi-Chi Rodriguez",
  // Current golf
  "Phil Mickelson", "Rory McIlroy", "Dustin Johnson", "Brooks Koepka", "Bryson DeChambeau",
  "Xander Schauffele", "Viktor Hovland", "Collin Morikawa", "Jordan Spieth", "Justin Thomas",
  "Patrick Cantlay", "Cameron Smith", "Hideki Matsuyama", "Wyndham Clark", "Brian Harman",
  "Tony Finau", "Will Zalatoris", "Sam Burns", "Max Homa", "Sahith Theegala",
  "Ludvig Aberg", "Tom Kim", "Sungjae Im", "Shane Lowry", "Tommy Fleetwood",
  "Matt Fitzpatrick", "Robert MacIntyre", "Tyrrell Hatton", "Cameron Young", "Keegan Bradley",
  "Russell Henley", "Denny McCarthy", "Davis Riley", "Chris Kirk", "Si Woo Kim",
  "Akshay Bhatia", "Emiliano Grillo", "Adam Scott", "Jason Day", "Adam Hadwin",
  "Corey Conners", "Mackenzie Hughes", "Nick Taylor", "Min Woo Lee", "Lucas Herbert",
  "Joaquin Niemann", "Abraham Ancer", "Sebastian Munoz", "Mito Pereira", "Carlos Ortiz",
  "Nelly Korda", "Jin Young Ko", "Lydia Ko", "Lexi Thompson", "Brooke Henderson",
  "Danielle Kang", "Minjee Lee", "Sei Young Kim", "Inbee Park", "Hyo Joo Kim",
  "Celine Boutier", "Rose Zhang", "Lilia Vu", "Charley Hull", "Georgia Hall",
  "Atthaya Thitikul", "Nasa Hataoka", "Ayaka Furue", "Patty Tavatanakit", "Ally Ewing",

  // ==================== BOXING ====================
  "Muhammad Ali", "Mike Tyson", "Floyd Mayweather", "Manny Pacquiao", "Oleksandr Usyk",
  "Anthony Joshua", "Deontay Wilder", "Terence Crawford", "Errol Spence Jr.", "Ryan Garcia",
  "Sugar Ray Leonard", "Sugar Ray Robinson", "Joe Louis", "Rocky Marciano", "Jack Dempsey",
  "Lennox Lewis", "Evander Holyfield", "George Foreman", "Joe Frazier", "Larry Holmes",
  "Marvin Hagler", "Thomas Hearns", "Roberto Duran", "Oscar De La Hoya", "Roy Jones Jr.",
  "Bernard Hopkins", "Julio Cesar Chavez", "Marco Antonio Barrera", "Erik Morales",
  "Wladimir Klitschko", "Vitali Klitschko", "Amir Khan", "Kell Brook", "Carl Froch",
  "Joe Calzaghe", "Ricky Hatton", "Saul Alvarez", "Gennady Golovkin",
  "Vasyl Lomachenko", "Shakur Stevenson", "Gervonta Davis", "Devin Haney",
  "Jermell Charlo", "Jermall Charlo", "David Benavidez", "Caleb Plant",
  "Dmitry Bivol", "Artur Beterbiev", "Josh Taylor", "Regis Prograis",
  "Teofimo Lopez", "Tank Davis", "Emanuel Navarrete", "Stephen Fulton",
  "Junto Nakatani", "Kazuto Ioka", "Roman Gonzalez", "Juan Francisco Estrada",
  "Nonito Donaire", "Guillermo Rigondeaux", "Tyson Fury", "Daniel Dubois",
  "Zhilei Zhang", "Filip Hrgovic", "Joe Joyce", "Dillian Whyte",

  // ==================== MMA / UFC ====================
  "Conor McGregor", "Israel Adesanya", "Jon Jones", "Khabib Nurmagomedov",
  "Dustin Poirier", "Charles Oliveira", "Islam Makhachev", "Alex Pereira",
  "Sean O'Malley", "Leon Edwards", "Ilia Topuria", "Max Holloway",
  "Alexander Volkanovski", "Kamaru Usman", "Jorge Masvidal", "Nate Diaz",
  "Nick Diaz", "Georges St-Pierre", "Anderson Silva", "Chuck Liddell",
  "Randy Couture", "Tito Ortiz", "Matt Hughes", "Royce Gracie",
  "Brock Lesnar", "Ronda Rousey", "Amanda Nunes", "Valentina Shevchenko",
  "Stipe Miocic", "Daniel Cormier", "Francis Ngannou", "Derrick Lewis",
  "Ciryl Gane", "Tom Aspinall", "Jiri Prochazka", "Glover Teixeira",
  "Jamahal Hill", "Dricus du Plessis", "Sean Strickland", "Robert Whittaker",
  "Paulo Costa", "Marvin Vettori", "Jared Cannonier", "Kelvin Gastelum",
  "Belal Muhammad", "Colby Covington", "Gilbert Burns", "Shavkat Rakhmonov",
  "Michael Chandler", "Justin Gaethje", "Beneil Dariush", "Arman Tsarukyan",
  "Paddy Pimblett", "Bryce Mitchell", "Yair Rodriguez", "Brian Ortega",
  "Merab Dvalishvili", "Henry Cejudo", "Aljamain Sterling", "Dominick Cruz",
  "T.J. Dillashaw", "Petr Yan", "Cody Garbrandt", "Jose Aldo",
  "Weili Zhang", "Rose Namajunas", "Joanna Jedrzejczyk", "Carla Esparza",
  "Alexa Grasso", "Brandon Moreno", "Deiveson Figueiredo", "Alexandre Pantoja",

  // ==================== F1 / MOTORSPORT ====================
  "Michael Schumacher", "Ayrton Senna", "Alain Prost", "Sebastian Vettel", "Fernando Alonso",
  "Charles Leclerc", "Lando Norris", "George Russell", "Oscar Piastri", "Carlos Sainz",
  "Niki Lauda", "Jackie Stewart", "Jim Clark", "Juan Manuel Fangio", "Mika Hakkinen",
  "Nigel Mansell", "Damon Hill", "Jacques Villeneuve", "Jenson Button", "David Coulthard",
  "Mark Webber", "Rubens Barrichello", "Giancarlo Fisichella", "Felipe Massa", "Nico Rosberg",
  "Daniel Ricciardo", "Valtteri Bottas", "Pierre Gasly", "Esteban Ocon", "Yuki Tsunoda",
  "Alexander Albon", "Zhou Guanyu", "Lance Stroll", "Kevin Magnussen", "Nico Hulkenberg",
  "Logan Sargeant", "Nyck de Vries", "Sergio Perez", "Kimi Raikkonen",
  "Dale Earnhardt", "Dale Earnhardt Jr.", "Jeff Gordon", "Jimmie Johnson", "Richard Petty",
  "Mario Andretti", "A.J. Foyt", "Al Unser", "Bobby Unser", "Michael Andretti",
  "Scott Dixon", "Helio Castroneves", "Dario Franchitti", "Will Power", "Josef Newgarden",
  "Alex Palou", "Colton Herta", "Pato O'Ward", "Marcus Ericsson", "Rinus VeeKay",
  "Chase Elliott", "Kyle Larson", "Kyle Busch", "Denny Hamlin", "Martin Truex Jr.",
  "Ryan Blaney", "Christopher Bell", "William Byron", "Ross Chastain", "Tyler Reddick",
  "Bubba Wallace", "Alex Bowman", "Daniel Suarez", "Austin Cindric", "Noah Gragson",

  // ==================== HOCKEY (NHL) ====================
  "Wayne Gretzky", "Mario Lemieux", "Sidney Crosby", "Alex Ovechkin", "Auston Matthews",
  "Nathan MacKinnon", "Leon Draisaitl", "Cale Makar", "David Pastrnak", "Nikita Kucherov",
  "Gordie Howe", "Bobby Orr", "Mark Messier", "Steve Yzerman", "Patrick Roy",
  "Martin Brodeur", "Jaromir Jagr", "Joe Sakic", "Peter Forsberg", "Paul Kariya",
  "Teemu Selanne", "Nicklas Lidstrom", "Chris Chelios", "Ray Bourque", "Brian Leetch",
  "Pavel Bure", "Dominik Hasek", "Roberto Luongo", "Henrik Lundqvist", "Carey Price",
  "Patrick Kane", "Jonathan Toews", "Duncan Keith", "Brent Seabrook", "Marian Hossa",
  "Steven Stamkos", "Victor Hedman", "Andrei Vasilevskiy", "Brayden Point", "Nikita Kucherov",
  "Connor Bedard", "Jack Hughes", "Nico Hischier", "Jesper Bratt", "Timo Meier",
  "Matthew Tkachuk", "Aleksander Barkov", "Sam Reinhart", "Carter Verhaeghe", "Sergei Bobrovsky",
  "Quinn Hughes", "Elias Pettersson", "Brock Boeser", "Thatcher Demko", "J.T. Miller",
  "Mitch Marner", "William Nylander", "John Tavares", "Morgan Rielly", "Joseph Woll",
  "Brad Marchand", "Charlie McAvoy", "David Pastrnak", "Jeremy Swayman", "Linus Ullmark",
  "Artemi Panarin", "Adam Fox", "Igor Shesterkin", "Chris Kreider", "Mika Zibanejad",
  "Kirill Kaprizov", "Matt Boldy", "Joel Eriksson Ek", "Brock Faber", "Filip Gustavsson",
  "Jason Robertson", "Roope Hintz", "Miro Heiskanen", "Jake Oettinger", "Wyatt Johnston",
  "Mikko Rantanen", "Gabriel Landeskog", "Devon Toews", "Alexandar Georgiev", "Valeri Nichushkin",
  "Troy Terry", "Trevor Zegras", "Mason McTavish", "Leo Carlsson", "John Gibson",
  "Tim Stutzle", "Brady Tkachuk", "Drake Batherson", "Josh Norris", "Anton Forsberg",
  "Rasmus Dahlin", "Tage Thompson", "Alex Tuch", "Owen Power", "Ukko-Pekka Luukkonen",
  "Moritz Seider", "Lucas Raymond", "Dylan Larkin", "Patrick Kane", "Alex DeBrincat",
  "Seth Jones", "Zach Werenski", "Johnny Gaudreau", "Patrik Laine", "Elvis Merzlikins",

  // ==================== TRACK & FIELD / OLYMPICS ====================
  "Usain Bolt", "Carl Lewis", "Jesse Owens", "Florence Griffith Joyner", "Michael Johnson",
  "Simone Biles", "Katie Ledecky", "Michael Phelps", "Nadia Comaneci", "Noah Lyles",
  "Sha'Carri Richardson", "Sydney McLaughlin-Levrone", "Mondo Duplantis", "Jakob Ingebrigtsen",
  "Mo Farah", "Haile Gebrselassie", "Eliud Kipchoge", "Kenenisa Bekele", "David Rudisha",
  "Hicham El Guerrouj", "Allyson Felix", "Shelly-Ann Fraser-Pryce", "Elaine Thompson-Herah",
  "Dina Asher-Smith", "Andre De Grasse", "Fred Kerley", "Christian Coleman", "Trayvon Bromell",
  "Erriyon Knighton", "Athing Mu", "Keely Hodgkinson", "Faith Kipyegon", "Beatrice Chebet",
  "Joshua Cheptegei", "Kelvin Kiptum", "Yulimar Rojas", "Miltiadis Tentoglou",
  "Ryan Crouser", "Mutaz Essa Barshim", "Karsten Warholm", "Rai Benjamin",
  "Femke Bol", "Julien Alfred", "Letsile Tebogo", "Quincy Hall", "Cole Hocker",
  "Gabby Thomas", "Tara Davis-Woodhall", "Valarie Allman", "DeAnna Price",
  "Neeraj Chopra", "Anderson Peters", "Jakub Vadlejch", "Marcell Jacobs",
  "Tommie Smith", "Fanny Blankers-Koen", "Paavo Nurmi", "Emil Zatopek",
  "Sebastian Coe", "Steve Ovett", "Roger Bannister", "Jim Thorpe", "Jackie Joyner-Kersee",
  "Bob Beamon", "Dick Fosbury", "Edwin Moses", "Daley Thompson",
  "Marion Jones", "Justin Gatlin", "Asafa Powell", "Yohan Blake", "Tyson Gay",

  // ==================== SWIMMING ====================
  "Mark Spitz", "Ian Thorpe", "Grant Hackett", "Ryan Lochte", "Caeleb Dressel",
  "Caleb Dressel", "Adam Peaty", "Florian Wellbrock", "Kristof Milak",
  "Leon Marchand", "David Popovici", "Pan Zhanle", "Bobby Finke", "Ahmed Hafnaoui",
  "Mollie O'Callaghan", "Ariarne Titmus", "Summer McIntosh", "Regan Smith",
  "Penny Oleksiak", "Emma McKeon", "Sarah Sjostrom", "Katinka Hosszu",
  "Federica Pellegrini", "Missy Franklin", "Katie Hoff", "Natalie Coughlin",
  "Dara Torres", "Jenny Thompson", "Janet Evans", "Pieter van den Hoogenband",
  "Alexander Popov", "Matt Biondi", "Johnny Weissmuller", "Duke Kahanamoku",
  "Sun Yang", "Ning Zetao", "Kosuke Kitajima", "Daiya Seto",

  // ==================== GYMNASTICS ====================
  "Simone Biles", "Nadia Comaneci", "Mary Lou Retton", "Olga Korbut", "Gabby Douglas",
  "Aly Raisman", "McKayla Maroney", "Jordyn Wieber", "Nastia Liukin", "Shawn Johnson",
  "Suni Lee", "Jade Carey", "Jordan Chiles", "Hezly Rivera", "MyKayla Skinner",
  "Kohei Uchimura", "Daiki Hashimoto", "Carlos Yulo", "Epke Zonderland",
  "Vitaly Scherbo", "Alexei Nemov", "Zou Jingyuan", "Zhang Boheng",
  "Rebeca Andrade", "Larisa Latynina", "Vera Caslavska", "Shannon Miller",

  // ==================== CRICKET ====================
  "Sachin Tendulkar", "Virat Kohli", "MS Dhoni", "Rohit Sharma", "Babar Azam",
  "Joe Root", "Ben Stokes", "Steve Smith", "Pat Cummins", "Jasprit Bumrah",
  "Don Bradman", "Viv Richards", "Brian Lara", "Jacques Kallis", "Ricky Ponting",
  "Adam Gilchrist", "Shane Warne", "Muttiah Muralitharan", "Glenn McGrath", "Wasim Akram",
  "Waqar Younis", "Imran Khan", "Kapil Dev", "Sunil Gavaskar", "Rahul Dravid",
  "VVS Laxman", "Anil Kumble", "Harbhajan Singh", "Yuvraj Singh", "Sourav Ganguly",
  "AB de Villiers", "Dale Steyn", "Hashim Amla", "Quinton de Kock", "Kagiso Rabada",
  "Kane Williamson", "Trent Boult", "Tim Southee", "Ross Taylor", "Devon Conway",
  "Shaheen Afridi", "Mohammad Rizwan", "Fakhar Zaman", "Shadab Khan", "Haris Rauf",
  "Travis Head", "Marnus Labuschagne", "David Warner", "Mitchell Starc", "Josh Hazlewood",
  "KL Rahul", "Rishabh Pant", "Shubman Gill", "Suryakumar Yadav", "Hardik Pandya",
  "Ravindra Jadeja", "Mohammed Shami", "Mohammed Siraj", "Ishan Kishan", "Yashasvi Jaiswal",
  "Harry Brook", "Zak Crawley", "Mark Wood", "Ollie Pope", "Jonny Bairstow",
  "Rashid Khan", "Nicholas Pooran", "Shimron Hetmyer", "Andre Russell", "Sunil Narine",

  // ==================== RUGBY ====================
  "Dan Carter", "Jonah Lomu", "Richie McCaw", "Antoine Dupont", "Maro Itoje",
  "Beauden Barrett", "Aaron Smith", "Ardie Savea", "Rieko Ioane", "Jordie Barrett",
  "Siya Kolisi", "Cheslin Kolbe", "Eben Etzebeth", "Pieter-Steph du Toit", "Handre Pollard",
  "Owen Farrell", "Marcus Smith", "Freddie Steward", "Ellis Genge", "Courtney Lawes",
  "Brian O'Driscoll", "Jonny Wilkinson", "Martin Johnson", "Lawrence Dallaglio", "Jason Robinson",
  "Sergio Parisse", "Bryan Habana", "John Eales", "David Campese", "Gareth Edwards",
  "Shane Williams", "George North", "Alun Wyn Jones", "Jonathan Davies", "Taulupe Faletau",
  "Damian Penaud", "Romain Ntamack", "Gregory Alldritt", "Charles Ollivon",

  // ==================== WRESTLING ====================
  "Jordan Burroughs", "Kyle Snyder", "Gable Steveson", "David Taylor", "Kyle Dake",
  "Helen Maroulis", "Tamyra Mensah-Stock", "Yui Susaki", "Risako Kawai",
  "Buvaisar Saitiev", "Abdulrashid Sadulaev", "Alexander Karelin",

  // ==================== CYCLING ====================
  "Lance Armstrong", "Eddy Merckx", "Chris Froome", "Tadej Pogacar", "Jonas Vingegaard",
  "Remco Evenepoel", "Wout van Aert", "Mathieu van der Poel", "Primoz Roglic",
  "Geraint Thomas", "Egan Bernal", "Richard Carapaz", "Mark Cavendish", "Peter Sagan",
  "Caleb Ewan", "Jasper Philipsen", "Julian Alaphilippe", "Tom Pidcock",
  "Miguel Indurain", "Bernard Hinault", "Greg LeMond", "Fausto Coppi", "Jacques Anquetil",
  "Marco Pantani", "Alberto Contador", "Vincenzo Nibali", "Alejandro Valverde",

  // ==================== OTHER SPORTS ====================
  // Surfing
  "Kelly Slater", "John John Florence", "Gabriel Medina", "Filipe Toledo", "Italo Ferreira",
  "Carissa Moore", "Stephanie Gilmore", "Tyler Wright", "Tatiana Weston-Webb",
  // Skiing
  "Lindsey Vonn", "Mikaela Shiffrin", "Marcel Hirscher", "Bode Miller", "Hermann Maier",
  "Ingemar Stenmark", "Alberto Tomba", "Aksel Lund Svindal", "Marco Odermatt", "Henrik Kristoffersen",
  // Skateboarding
  "Tony Hawk", "Nyjah Huston", "Yuto Horigome", "Rayssa Leal", "Sky Brown",
  // Table tennis
  "Ma Long", "Fan Zhendong", "Wang Chuqin", "Sun Yingsha", "Chen Meng",
  // Badminton
  "Viktor Axelsen", "An Se-young", "Tai Tzu-ying", "Kento Momota", "Lee Zii Jia",
  "Lin Dan", "Lee Chong Wei", "Chen Long", "Carolina Marin",
  // Esports
  "Faker", "s1mple", "ZywOo", "NiKo", "dev1ce",
  "Bugha", "MrSavage", "TenZ", "Shroud", "Ninja",
  // Lacrosse
  "Paul Rabil", "Lyle Thompson", "Gary Gait", "Mikey Powell",
  // Volleyball
  "Earvin N'Gapeth", "Wilfredo Leon", "Matt Anderson", "Zhu Ting",
  // Weightlifting
  "Lasha Talakhadze", "Lu Xiaojun", "Shi Zhiyong", "Hidilyn Diaz",
  // Figure skating
  "Yuzuru Hanyu", "Nathan Chen", "Ilia Malinin", "Yuna Kim", "Mao Asada",
  "Alina Zagitova", "Kamila Valieva", "Anna Shcherbakova",
];
