// ~250+ highest-grossing animated films of all time (worldwide box office)
// Source: Wikipedia "List of highest-grossing animated films" (sourced from Box Office Mojo / IMDb Pro)
export const highestGrossingAnimatedMoviesHints: string[] = [
  // Top 50 (the actual answers)
  "Ne Zha 2", "Zootopia 2", "Inside Out 2", "The Lion King", "Frozen II",
  "The Super Mario Bros. Movie", "Frozen", "Incredibles 2", "Minions", "Toy Story 4",
  "Toy Story 3", "Moana 2", "Despicable Me 3", "Finding Dory", "Zootopia",
  "Despicable Me 4", "Despicable Me 2", "The Lion King (1994)", "Finding Nemo", "Minions: The Rise of Gru",
  "Shrek 2", "Ice Age: Dawn of the Dinosaurs", "Ice Age: Continental Drift", "The Secret Life of Pets", "Inside Out",
  "Coco", "Shrek the Third", "Demon Slayer: Infinity Castle", "Shrek Forever After", "Madagascar 3: Europe's Most Wanted",
  "Monsters University", "Ne Zha", "Up", "Mufasa: The Lion King", "Spider-Man: Across the Spider-Verse",
  "Ice Age: The Meltdown", "Kung Fu Panda 2", "Big Hero 6", "Moana", "Sing",
  "Kung Fu Panda", "The Incredibles", "The Super Mario Galaxy Movie", "Ratatouille", "How to Train Your Dragon 2",
  "Madagascar: Escape 2 Africa", "Tangled", "The Croods", "Monsters, Inc.", "Cars 2",
  // 51–100: more CG animated hits
  "Puss in Boots", "The Grinch", "Shrek", "Ice Age", "Madagascar",
  "Toy Story 2", "Toy Story", "A Bug's Life", "Brave", "Cars",
  "Cars 3", "Ralph Breaks the Internet", "Wreck-It Ralph", "Onward", "Encanto",
  "Soul", "Luca", "Turning Red", "Elemental", "Wish",
  "Lightyear", "Sing 2", "The Boss Baby", "The Croods: A New Age", "Home",
  "Penguins of Madagascar", "Despicable Me", "Hotel Transylvania 2", "Hotel Transylvania 3", "Hotel Transylvania",
  "The Angry Birds Movie", "The Angry Birds Movie 2", "Ferdinand", "Bolt", "Turbo",
  "Rio", "Rio 2", "Kung Fu Panda 3", "How to Train Your Dragon", "How to Train Your Dragon: The Hidden World",
  "Puss in Boots: The Last Wish", "The Secret Life of Pets 2", "Migration", "Strange World",
  "Megamind", "Over the Hedge", "The Bad Guys", "Trolls", "Trolls World Tour",
  // 101–150: traditionally animated classics and modern anime
  "Aladdin", "Beauty and the Beast", "Tarzan", "The Jungle Book", "Mulan",
  "Pocahontas", "The Hunchback of Notre Dame", "Hercules", "The Little Mermaid", "Bambi",
  "Cinderella", "Sleeping Beauty", "One Hundred and One Dalmatians", "Snow White and the Seven Dwarfs", "Pinocchio",
  "The Sword in the Stone", "Robin Hood", "The Aristocats", "The Fox and the Hound", "Oliver & Company",
  "The Rescuers", "The Rescuers Down Under", "The Emperor's New Groove", "Brother Bear", "Atlantis: The Lost Empire",
  "Dinosaur", "Home on the Range", "Lilo & Stitch", "Treasure Planet", "The Princess and the Frog",
  "The Prince of Egypt", "Anastasia", "Lady and the Tramp", "Peter Pan",
  "Spirited Away", "Howl's Moving Castle", "Princess Mononoke", "Ponyo", "My Neighbor Totoro",
  "Your Name", "Weathering with You", "Suzume", "The Boy and the Heron", "Arrietty",
  "Demon Slayer: Mugen Train", "One Piece Film: Red", "Jujutsu Kaisen 0", "Pokémon: The First Movie", "Pokémon: The Movie 2000",
  // 151–200: stop-motion, TV-based, and international films
  "Chicken Run", "Wallace & Gromit: The Curse of the Were-Rabbit", "Coraline", "The Nightmare Before Christmas", "Corpse Bride",
  "Fantastic Mr. Fox", "Kubo and the Two Strings", "Shaun the Sheep Movie", "The Boxtrolls", "ParaNorman",
  "The Pirates! In an Adventure with Scientists!", "Early Man", "Isle of Dogs", "Missing Link", "A Shaun the Sheep Movie: Farmageddon",
  "The Little Prince", "Frankenweenie", "James and the Giant Peach", "The Simpsons Movie", "South Park: Bigger, Longer & Uncut",
  "The SpongeBob SquarePants Movie", "The SpongeBob Movie: Sponge Out of Water", "The Rugrats Movie", "Rugrats in Paris: The Movie", "A Boy Named Charlie Brown",
  "Alice in Wonderland", "The Three Caballeros", "Make Mine Music", "Melody Time", "Fun and Fancy Free",
  "The Adventures of Ichabod and Mr. Toad", "Dumbo", "Fantasia", "Fantasia 2000",
  "Winnie the Pooh", "The Many Adventures of Winnie the Pooh", "The Tigger Movie", "Piglet's Big Movie", "Pooh's Heffalump Movie",
  "Bambi II", "The Fox and the Hound 2", "Mulan II", "Tarzan II", "Cinderella III",
  "Mary and Max", "Anomalisa", "Marcel the Shell with Shoes On", "Memoir of a Snail", "The Inventor",
  // 201–260: additional international and niche animated films
  "The First Slam Dunk", "Chainsaw Man: Reze Arc", "Detective Conan: The Million-dollar Pentagram", "Detective Conan: One-eyed Flashback", "Nausicaä of the Valley of the Wind", "Castle in the Sky", "Kiki's Delivery Service", "Only Yesterday", "Pom Poko",
  "Whisper of the Heart", "The Cat Returns", "The Wind Rises", "The Tale of the Princess Kaguya", "When Marnie Was There",
  "The Red Turtle", "Wolfwalkers", "Song of the Sea", "The Secret of Kells", "Tomm Moore",
  "Klaus", "I Lost My Body", "Capernaum", "A Silent Voice", "In This Corner of the World",
  "Doraemon: Nobita's Dinosaur", "Doraemon: Nobita's Great Adventure into the Underworld", "Doraemon: Nobita and the Knights on Dinosaurs",
  "Cheburashka", "Ne Zha (2019)", "White Snake", "The Deer King", "Belle",
  "Chicken Run: Dawn of the Nugget", "DC League of Super-Pets", "Paw Patrol: The Movie", "Paw Patrol: The Mighty Movie",
  "The Lego Movie", "The Lego Batman Movie", "The Lego Movie 2: The Second Part", "The Lego Ninjago Movie", "Kung Fu Panda 4", "The Garfield Movie", "IF", "Ruby Gillman, Teenage Kraken",
  "Luck", "Nimona", "The Mitchells vs. the Machines", "Connected", "Over the Moon", "My Father's Dragon", "The Sea Beast", "Vivo", "Back to the Outback",
];
