// ~500 well-known movies for hints
export const imdbTopMoviesHints: string[] = [
  // Top 100 (the actual answers)
  "The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Lord of the Rings: The Return of the King", "Schindler's List",
  "The Godfather Part II", "12 Angry Men", "The Lord of the Rings: The Fellowship of the Ring", "Inception", "Fight Club",
  "Forrest Gump", "Pulp Fiction", "The Lord of the Rings: The Two Towers", "The Good, the Bad and the Ugly", "Interstellar",
  "The Matrix", "Star Wars: Episode V - The Empire Strikes Back", "GoodFellas", "Seven", "The Silence of the Lambs",
  "Saving Private Ryan", "Star Wars: Episode IV - A New Hope", "The Green Mile", "Terminator 2: Judgment Day", "One Flew Over the Cuckoo's Nest",
  "Spirited Away", "City of God", "Life Is Beautiful", "It's a Wonderful Life", "Seven Samurai",
  "Jai Bhim", "Django Unchained", "Gladiator", "The Prestige", "The Departed",
  "Back to the Future", "Leon: The Professional", "American History X", "The Lion King", "The Usual Suspects",
  "Parasite", "Whiplash", "Alien", "The Intouchables", "The Pianist",
  "Psycho", "Casablanca", "The Kashmir Files", "Rear Window", "Spider-Man: Across the Spider-Verse",
  "Once Upon a Time in the West", "Grave of the Fireflies", "Cinema Paradiso", "Modern Times", "City Lights",
  "The Dark Knight Rises", "Inglourious Basterds", "Avengers: Endgame", "Memento", "Avengers: Infinity War",
  "WALL-E", "The Shining", "Good Will Hunting", "Raiders of the Lost Ark", "Aliens",
  "Spider-Man: Into the Spider-Verse", "Apocalypse Now", "Dune: Part Two", "Coco", "3 Idiots",
  "Amadeus", "The Lives of Others", "Your Name.", "Sunset Boulevard", "The Great Dictator",
  "Paths of Glory", "Joker", "American Beauty", "Up", "Star Wars: Episode VI - Return of the Jedi",
  "Eternal Sunshine of the Spotless Mind", "Toy Story", "Reservoir Dogs", "Braveheart", "Scarface",
  "Requiem for a Dream", "Toy Story 3", "Amelie", "Heat", "2001: A Space Odyssey",
  "Oldboy", "Dr. Strangelove", "Princess Mononoke", "Once Upon a Time in America", "The Hunt",
  "North by Northwest", "Lawrence of Arabia", "Das Boot", "Singin' in the Rain", "A Separation",
  // 101-500
  "The Wolf of Wall Street", "Batman Begins", "Oppenheimer", "No Country for Old Men", "Jurassic Park",
  "Inside Out", "Vertigo", "Gone with the Wind", "Citizen Kane", "Full Metal Jacket",
  "The Truman Show", "M", "A Clockwork Orange", "Dangal", "The Apartment",
  "Come and See", "Rang De Basanti", "Harakiri", "Witness for the Prosecution", "The Sting",
  "Ikiru", "Hamilton", "Incendies", "Taxi Driver", "Snatch",
  "To Kill a Mockingbird", "The Thing", "Rashomon", "Bicycle Thieves", "Double Indemnity",
  "L.A. Confidential", "Indiana Jones and the Last Crusade", "My Neighbor Totoro", "Top Gun: Maverick",
  "There Will Be Blood", "Monty Python and the Holy Grail", "Shutter Island",
  "Se7en", "The Big Lebowski", "Blade Runner 2049", "The Grand Budapest Hotel", "Fargo",
  "The Social Network", "Catch Me If You Can", "Howl's Moving Castle", "Kill Bill: Vol. 1", "The Sixth Sense",
  "12 Years a Slave", "The Bridge on the River Kwai", "No Time to Die",
  "The Terminator", "Pan's Labyrinth", "Mad Max: Fury Road", "Trainspotting", "V for Vendetta",
  "Ratatouille", "Finding Nemo", "The Exorcist", "Arrival", "Jaws",
  "Rocky", "The Revenant", "Deadpool & Wolverine", "Blade Runner", "Children of Men",
  "The Princess Bride", "Gran Torino", "A Beautiful Mind", "Casino", "The Deer Hunter",
  "Donnie Darko", "Puss in Boots: The Last Wish", "Hacksaw Ridge", "The Banshees of Inisherin",
  "The Lighthouse", "Portrait of a Lady on Fire", "Moonlight", "Roma", "Marriage Story",
  "Knives Out", "Get Out", "Hereditary", "Midsommar", "The Witch",
  "Everything Everywhere All at Once", "Once Upon a Time in Hollywood", "1917", "Ford v Ferrari",
  "Little Women", "Jojo Rabbit", "The Irishman", "Uncut Gems", "Black Swan", "The Shape of Water", "Three Billboards Outside Ebbing, Missouri",
  "Dunkirk", "La La Land", "Manchester by the Sea", "Spotlight", "The Big Short",
  "Room", "Birdman", "Boyhood", "The Imitation Game", "Gone Girl",
  "Nightcrawler", "Her", "Gravity", "Dallas Buyers Club", "Silver Linings Playbook", "Life of Pi", "Argo", "The Artist", "Hugo",
  "Drive", "Midnight in Paris", "The King's Speech", "127 Hours",
  "Black Panther", "Logan", "Deadpool", "John Wick", "Baby Driver",
  "The Martian", "Ex Machina", "Sicario", "The Hateful Eight", "Bridge of Spies", "Inside Out 2", "Barbie", "Tenet", "Soul",
  "Luca", "Raya and the Last Dragon", "Cruella", "Free Guy", "Shang-Chi",
  "Dune", "No Way Home", "The Batman", "Elvis",
  "Nope", "Glass Onion", "Prey", "The Fabelmans", "Tar",
  "Babylon", "Avatar: The Way of Water", "Smile", "M3GAN", "Barbarian",
  "The Menu", "Triangle of Sadness", "Decision to Leave", "RRR", "The Whale",
  "Aftersun", "Women Talking", "Killers of the Flower Moon", "Past Lives", "Asteroid City",
  "The Holdovers", "Poor Things", "Anatomy of a Fall", "The Zone of Interest", "American Fiction",
  "Saltburn", "Iron Claw", "May December", "Maestro", "All Quiet on the Western Front", "John Wick: Chapter 4", "Guardians of the Galaxy Vol. 3", "Mission: Impossible - Dead Reckoning",
  "Indiana Jones and the Dial of Destiny", "The Super Mario Bros. Movie", "Napoleon", "The Creator", "Wonka",
  "Civil War", "Challengers", "The Fall Guy", "Furiosa", "A Quiet Place: Day One", "Twisters", "Alien: Romulus", "Beetlejuice Beetlejuice",
  "The Substance", "Anora", "Conclave", "Wicked", "Gladiator II",
  "Nosferatu", "A Complete Unknown", "Moana 2", "Mufasa: The Lion King",
  "The Brutalist", "Emilia Perez", "September 5",
  "Titanic", "Avatar", "E.T. the Extra-Terrestrial", "Star Wars: The Force Awakens",
  "The Wizard of Oz", "Ben-Hur", "West Side Story", "My Fair Lady", "The Sound of Music",
  "Chinatown", "Annie Hall", "The French Connection", "Patton", "The Godfather Part III", "Platoon", "Rain Man",
  "Dances with Wolves", "Unforgiven", "The Fugitive", "Philadelphia", "Shakespeare in Love", "Traffic", "Moulin Rouge!", "Chicago",
  "Million Dollar Baby", "Crash", "Slumdog Millionaire", "The Hurt Locker", "Green Book", "Nomadland", "CODA"];
