// ~500 well-known TV shows for hints
export const imdbTopTvShowsHints: string[] = [
  // Top 100 (the actual answers)
  "Breaking Bad", "Band of Brothers", "Planet Earth", "Planet Earth II", "Chernobyl",
  "Avatar: The Last Airbender", "The Wire", "Blue Planet II", "Cosmos", "Bluey",
  "Game of Thrones", "The Sopranos", "Cosmos: A Spacetime Odyssey", "Our Planet", "The World at War",
  "Attack on Titan", "Fullmetal Alchemist: Brotherhood", "Sherlock", "Better Call Saul", "The Office",
  "Rick and Morty", "Arcane", "One Piece", "Hunter x Hunter", "The Last Dance",
  "Batman: The Animated Series", "The Twilight Zone", "Death Note", "Seinfeld", "Firefly",
  "Gravity Falls", "Cowboy Bebop", "The West Wing", "Frieren: Beyond Journey's End", "Nathan for You",
  "Friends", "True Detective", "Fargo", "Succession", "It's Always Sunny in Philadelphia",
  "BoJack Horseman", "Dragon Ball Z", "Curb Your Enthusiasm", "Freaks and Geeks", "When They See Us",
  "Vinland Saga", "Fawlty Towers", "Last Week Tonight with John Oliver", "Pride and Prejudice", "Steins;Gate",
  "Monty Python's Flying Circus", "Chappelle's Show", "Blackadder Goes Forth", "Peaky Blinders", "Black Mirror",
  "House", "Dark", "Narcos", "South Park", "Ted Lasso",
  "Invincible", "Mad Men", "Downton Abbey", "Twin Peaks", "Fleabag",
  "Naruto: Shippuden", "Rome", "Battlestar Galactica", "Six Feet Under", "Star Trek: The Next Generation",
  "The X-Files", "Stranger Things", "Dexter", "The Boys", "The Mandalorian",
  "House of Cards", "Daredevil", "The Simpsons", "Mindhunter", "Severance",
  "Arrested Development", "Parks and Recreation", "Yellowstone", "The Crown", "Andor",
  "Shogun", "One Punch Man", "Demon Slayer", "Boardwalk Empire", "The Last of Us",
  "The Queen's Gambit", "Vikings", "Mr. Robot", "The Bear", "Hannibal",
  "Community", "Modern Family", "The Penguin", "Brooklyn Nine-Nine", "Suits",
  // 101-500 additional well-known TV shows
  "Lost", "The Walking Dead", "Homeland", "American Horror Story",
  "Grey's Anatomy", "How I Met Your Mother", "The Big Bang Theory", "Two and a Half Men",
  "Criminal Minds", "NCIS", "Law & Order: SVU", "CSI: Crime Scene Investigation",
  "The Good Place", "Schitt's Creek", "Ozark", "Killing Eve", "Westworld",
  "Penny Dreadful", "The Witcher", "Bridgerton", "Emily in Paris", "You",
  "13 Reasons Why", "Squid Game", "Money Heist", "Lupin",
  "Narcos: Mexico", "The Umbrella Academy", "Cobra Kai", "Outer Banks",
  "Wednesday", "The Haunting of Hill House", "The Haunting of Bly Manor",
  "Midnight Mass", "The Fall of the House of Usher", "Archive 81",
  "Dahmer", "Monsters", "Baby Reindeer", "Ripley", "Beef",
  "White Lotus", "Mare of Easttown", "Sharp Objects", "Big Little Lies",
  "Euphoria", "Insecure", "Atlanta", "Barry", "Hacks",
  "Abbott Elementary", "Only Murders in the Building", "Reservation Dogs",
  "Pachinko", "Slow Horses", "For All Mankind", "Foundation",
  "Silo", "Loki", "WandaVision", "Hawkeye", "Moon Knight",
  "Ms. Marvel", "She-Hulk", "Secret Invasion", "Agatha All Along",
  "House of the Dragon", "The Rings of Power", "Wheel of Time",
  "The Sandman", "Good Omens", "American Gods", "Preacher",
  "Lucifer", "Supernatural", "The Vampire Diaries", "Teen Wolf",
  "Buffy the Vampire Slayer", "Angel", "Charmed", "Xena: Warrior Princess",
  "Doctor Who", "Torchwood", "Black Adder", "The IT Crowd",
  "Peep Show", "Inbetweeners", "Misfits", "Skins", "Luther",
  "Line of Duty", "Bodyguard", "Happy Valley", "Broadchurch", "Catastrophe", "Derry Girls",
  "Normal People", "Conversations with Friends", "The Responder",
  "Top Boy", "Gangs of London", "SAS: Rogue Heroes",
  "The Americans", "Justified", "Deadwood", "Carnivale",
  "Oz", "The Shield", "Sons of Anarchy", "Mayans M.C.",
  "Power", "Snowfall", "Cloak and Dagger",
  "24", "Alias", "Fringe", "Person of Interest", "Halt and Catch Fire", "Silicon Valley",
  "Entourage", "Ballers", "Veep", "The Newsroom",
  "Studio 60 on the Sunset Strip", "Sports Night",
  "ER", "Scrubs", "The Good Doctor", "New Amsterdam",
  "Chicago Fire", "Chicago P.D.", "Chicago Med", "9-1-1",
  "Station 19", "The Rookie", "Blue Bloods", "FBI",
  "Bones", "Castle", "Elementary", "Psych", "White Collar",
  "Burn Notice", "Covert Affairs", "Chuck",
  "30 Rock", "Unbreakable Kimmy Schmidt", "Superstore", "What We Do in the Shadows", "Ghosts",
  "Archer", "Bob's Burgers", "King of the Hill",
  "Family Guy", "American Dad", "Futurama", "Disenchantment",
  "Adventure Time", "Steven Universe", "Regular Show",
  "Over the Garden Wall", "Samurai Jack", "Primal",
  "Invader Zim", "Courage the Cowardly Dog", "Ed Edd n Eddy",
  "Dexter's Laboratory", "The Powerpuff Girls", "Animaniacs",
  "Pinky and the Brain", "Tiny Toon Adventures",
  "Rugrats", "Hey Arnold!", "Doug", "Ren & Stimpy",
  "SpongeBob SquarePants", "Fairly OddParents", "Danny Phantom",
  "Jimmy Neutron", "Avatar: The Legend of Korra",
  "Young Justice", "Teen Titans", "Justice League",
  "Batman Beyond", "Superman: The Animated Series",
  "X-Men: The Animated Series", "X-Men '97", "Spider-Man: The Animated Series",
  "Spectacular Spider-Man", "Wolverine and the X-Men",
  "My Hero Academia", "Jujutsu Kaisen", "Chainsaw Man",
  "Spy x Family", "Dragon Ball Super", "Naruto",
  "Bleach", "Mob Psycho 100",
  "Neon Genesis Evangelion", "Serial Experiments Lain",
  "Paranoia Agent", "Monster", "Berserk",
  "Legend of the Galactic Heroes", "Ghost in the Shell: Stand Alone Complex",
  "Psycho-Pass", "Code Geass", "Death Parade",
  "Erased", "Made in Abyss", "The Promised Neverland",
  "Haikyuu!!", "Slam Dunk", "Kuroko's Basketball",
  "Your Lie in April", "Clannad: After Story", "Violet Evergarden",
  "March Comes in Like a Lion", "A Place Further Than the Universe",
  "Odd Taxi", "Bocchi the Rock!", "Dandadan",
  "Blue Eye Samurai", "Fallout", "Daredevil: Born Again",
  "Reacher", "Jack Ryan", "Bosch", "The Night Manager",
  "The Night Of", "True Detective: Night Country", "Under the Banner of Heaven",
  "Dopesick", "Painkiller", "The Dropout", "WeCrashed", "Super Pumped",
  "Inventing Anna", "Bad Blood", "The Morning Show", "Shrinking", "Platonic",
  "Lessons in Chemistry", "Presumed Innocent", "Bad Monkey",
  "Disclaimer", "Black Bird", "All the Light We Cannot See", "A Man in Full",
  "The Gilded Age", "1883", "1923",
  "Yellowjackets", "From", "Evil", "The Leftovers",
  "Station Eleven", "Tales from the Loop", "Devs",
  "Maniac", "Russian Doll", "The OA",
  "Sense8", "Altered Carbon", "Love, Death & Robots",
  "The Expanse", "Raised by Wolves",
  "Counterpart", "Dark Matter", "Beacon 23",
];
