// ~250+ fast food and restaurant chain names for hints
// Sources: Wikipedia "List of the largest fast food restaurant chains" and
//          "List of fast food restaurant chains" (2024–2025 data)
export const largestFastFoodChainsHints: string[] = [
  // Top 50 (the actual answers)
  "Mixue Ice Cream & Tea", "McDonald's", "Starbucks", "Subway", "KFC",
  "Luckin Coffee", "Domino's", "Wallace", "Burger King", "Pizza Hut",
  "Dunkin' Donuts", "Krispy Kreme", "Hunt Brothers Pizza", "Cotti Coffee", "Good me",
  "Tastien", "Auntea Jenny", "Taco Bell", "ChaPanda", "Baskin-Robbins",
  "Wendy's", "Dairy Queen", "Chagee", "Tianlala", "Tim Hortons",
  "Papa John's", "Little Caesars", "Costa Coffee", "Hey Tea", "Carl's Jr.",
  "Popeyes", "bbq Chicken", "Sonic Drive-In", "Arby's", "Chipotle",
  "Champion Pizza", "Chick-fil-A", "Jimmy John's", "Dicos", "Jersey Mike's",
  "Jack in the Box", "Greggs", "Panda Express", "Panera Bread", "Pelicana Chicken",
  "Sukiya", "Naixue", "Pala Hamburger", "Auntie Anne's", "Chester's",

  // Ranks 51–117 from the same Wikipedia list
  "Chooks-to-Go", "Mi Bibimbap", "NewYobo", "Jollibee", "Church's Texas Chicken",
  "MOS Burger", "Dodo Pizza", "Cinnabon", "WingStreet", "Five Guys",
  "Waffle House", "Quiznos", "Ichibanya", "Papa Murphy's", "Home Original Chicken",
  "Telepizza", "Kebab Turki Baba Rafi", "Firehouse Subs", "Long John Silver's",
  "Buffalo Wild Wings", "Orange Julius", "Bob's", "A&W Restaurants", "MrBeast Burger",
  "85°C Bakery Cafe", "Culver's", "Vkusno i Tochka", "Zaxby's", "Olive Garden",
  "Nando's", "Checkers and Rally's", "Wetherspoons", "Qdoba", "BreadTalk",
  "Häagen-Dazs", "Raising Cane's", "Café Coffee Day", "Bojangles'", "Whataburger",
  "Moe's Southwest Grill", "Pizza Pizza", "Rita's Italian Ice", "Mang Inasal",
  "Smoothie King", "Sbarro", "Chuck E. Cheese", "Pita Pit", "Kungfu",
  "Boost Juice", "Del Taco", "Steak 'n Shake", "Wimpy", "Steers",
  "Captain D's", "Da Niang Dumpling", "Brioche Dorée", "Charleys Philly Steaks",
  "Hesburger", "Round Table Pizza", "Freddy's Frozen Custard", "Shakey's Pizza", "Shake Shack",

  // Additional chains from Wikipedia "List of fast food restaurant chains"
  "In-N-Out Burger", "White Castle", "Wingstop", "Slim Chickens", "Dave's Hot Chicken",
  "MOD Pizza", "Blaze Pizza", "Smashburger", "BurgerFi", "Habit Burger Grill",
  "El Pollo Loco", "Pollo Campero", "Tropical Smoothie Cafe", "Jamba Juice", "Wetzel's Pretzels",
  "Auntie Anne's", "Cinnabon", "Schlotzsky's", "McAlister's Deli", "Jason's Deli",
  "Potbelly Sandwich Works", "Which Wich?", "Penn Station East Coast Subs", "Port of Subs", "Firehouse Subs",
  "Noodles & Company", "Freshii", "Sweetgreen", "Saladworks", "Salad and Go",
  "Cicis Pizza", "Donatos Pizza", "Godfather's Pizza", "Mazzio's", "Fox's Pizza Den",
  "Pizza Ranch", "Marco's Pizza", "Jet's Pizza", "Hungry Howie's", "Pizza Inn",
  "Johnny Rockets", "Red Robin", "Denny's", "IHOP", "Perkins Restaurant",
  "Wahlburgers", "Shake Shack", "Portillo's", "Culver's", "Steak Escape",
  "Krystal", "Checkers", "Rally's", "Jack's", "Hardee's",
  "Roy Rogers Restaurants", "Arctic Circle Restaurants", "Fatburger", "Burgerville", "Good Times",
  "Cook Out", "Braum's", "Sonic", "Whataburger", "Steak 'n Shake",
  "Wienerschnitzel", "Hot Dog on a Stick", "Nathan's Famous", "Dog Haus", "Portillo's",
  "Baja Fresh", "Rubio's", "Moe's", "Qdoba", "Taco Bueno",
  "Taco Cabana", "Del Taco", "Taco John's", "Taco Time", "Taco del Mar",
  "Lotteria", "MOS Burger", "Freshness Burger", "Mos Burger", "First Kitchen",
  "Yoshinoya", "Sukiya", "Hotto Motto", "Sushiro", "Kura",
  "Marugame Seimen", "Pepper Lunch", "Gyukaku", "Ootoya", "Nakau",
  "Marrybrown", "Texas Chicken", "The Chicken Rice Shop", "Old Chang Kee", "Jollibee",
  "Mang Inasal", "Chowking", "Greenwich Pizza", "Yellow Cab Pizza Co.", "Max's Restaurant",
  "Bonchon Chicken", "KyoChon", "bbq Chicken", "Nene Chicken", "Mom's Touch",
  "Paris Baguette", "Tous les Jours", "Tom N Toms Coffee", "Caffe Bene", "Two Some Place",
  "Cafe de Coral", "Fairwood", "Ting Hsin International Group", "85°C Bakery Cafe", "St-Hubert",
  "Harvey's", "Mary Brown's Chicken", "A&W Canada", "Pizza Pizza", "Boston Pizza",
  "Panago", "Greco Pizza", "Cora", "Tim Hortons", "Second Cup",
  "Pret a Manger", "Leon", "Greggs", "Wetherspoons", "Nando's",
  "Wagamama", "YO! Sushi", "itsu", "Franco Manca", "Five Guys",
  "Wimpy", "Burger King", "KFC", "McDonald's", "Subway",
  "Harry Ramsden's", "West Cornwall Pasty", "Wasabi", "Tortilla", "Benito's Hat",
  "Abrakebabra", "Eddie Rocket's", "Supermac's", "Apache Pizza", "Four Star Pizza",
  "Hesburger", "Sibylla", "Max Hamburgers", "Dodo Pizza", "Teremok",
  "Vkusno i Tochka", "Sbarro", "PizzaExpress", "Vapiano", "Nordsee",
  "FEBO", "Kochlöffel", "Flunch", "Quick", "Brioche Dorée",
  "Rodilla", "Telepizza", "La Tagliatella", "Bocatta", "Pans & Company",
  "Giraffas", "Bob's Brazil", "Habib's", "Rei do Mate", "Spoleto",
  "Bembos", "Hamburguesas El Corral", "Juan Maestro", "Frisby", "El Corral",
  "Galito's", "Nando's", "Chicken Licken", "Steers", "Wimpy South Africa",
  "Roman's Pizza", "Debonairs Pizza", "Kudu", "Hungry Lion",
  "Al Baik", "Shawarmer", "Koud", "The Pizza Company", "Bonchon",
  "Ajisen Ramen", "Yoshinoya", "Gyukaku", "Mos Burger",
  "Caribou Coffee", "The Coffee Bean & Tea Leaf", "Peet's Coffee", "Dutch Bros", "Scooter's Coffee",
  "Biggby Coffee", "Gloria Jean's Coffees", "Coffee Beanery", "Aroma Espresso Bar", "Second Cup",
  "Insomnia Cookies", "Crumbl Cookies", "Nothing Bundt Cakes", "Great American Cookies",
  "Dippin' Dots", "Cold Stone Creamery", "Marble Slab Creamery", "Orange Leaf", "Menchie's",
  "Tropical Smoothie", "Jamba", "Booster Juice", "Planet Smoothie",
];
