// Top 100 largest US colleges by enrollment plus 400+ additional US colleges and universities
export const largestCollegePopulationsHints: string[] = [
  // Top 100
  "University of Central Florida", "Texas A&M", "Ohio State", "Florida International University", "University of Florida",
  "Liberty University", "Arizona State", "University of Texas at Austin", "Michigan State", "Penn State",
  "University of Minnesota", "University of Illinois Urbana-Champaign", "Florida State", "Purdue", "Indiana University",
  "University of South Florida", "University of Michigan", "Rutgers", "University of Houston", "NYU",
  "University of Wisconsin-Madison", "University of Arizona", "University of Georgia", "Georgia State", "University of Washington",
  "University of North Texas", "University of Maryland", "UCLA", "Texas State", "University of Alabama",
  "University of Cincinnati", "Virginia Tech", "University of Kentucky", "Iowa State", "Temple",
  "UC Berkeley", "University of Colorado Boulder", "University of Iowa", "NC State", "University of Oklahoma",
  "University of Tennessee", "University of Oregon", "Brigham Young University", "University of Nebraska", "University of South Carolina",
  "University of Missouri", "California State University Northridge", "University of Kansas", "California State University Fullerton", "University of North Carolina at Charlotte",
  "Auburn", "San Diego State", "Colorado State", "University of Connecticut", "West Virginia University",
  "Oregon State", "University of Utah", "University of Pittsburgh", "Clemson", "Boston University",
  "George Mason University", "University of Nevada Las Vegas", "Baylor", "SUNY Buffalo", "Syracuse",
  "San Jose State", "Louisiana State University", "University of Arkansas", "California State University Long Beach", "University of Mississippi",
  "Wayne State University", "University of New Mexico", "Kent State", "Portland State", "Old Dominion University",
  "University of Memphis", "Towson University", "Northern Arizona University", "California State Polytechnic Pomona", "Florida Atlantic University",
  "East Carolina University", "University of Louisville", "Western Michigan University", "Central Michigan University", "Kansas State",
  "University of Denver", "Kennesaw State", "USC", "Texas Tech", "Mississippi State",
  "Oklahoma State", "UNC Chapel Hill", "Washington State", "University of Delaware", "Ball State",
  "Illinois State", "Stony Brook University", "University of Massachusetts Amherst", "Miami University (Ohio)", "Northeastern",
  // Beyond top 100 — Ivy League & elite privates
  "MIT", "Stanford", "Harvard", "Caltech", "Duke",
  "Johns Hopkins", "UPenn", "Northwestern", "Yale", "Princeton",
  "Columbia", "University of Chicago", "Cornell", "Rice", "Dartmouth",
  "Vanderbilt", "Notre Dame", "Georgetown", "Carnegie Mellon", "Emory",
  "University of Virginia", "Washington University in St. Louis",
  "Wake Forest", "Tufts", "UC Santa Barbara",
  "University of Rochester", "Boston College", "Georgia Tech",
  "UC Irvine", "UC San Diego", "William & Mary",
  "Brandeis", "Case Western Reserve", "Villanova",
  "Lehigh", "Pepperdine", "Rensselaer Polytechnic Institute",
  "Santa Clara University", "George Washington University",
  "University of Miami", "Fordham", "Stevens Institute of Technology",
  "Drexel", "Loyola Marymount", "Gonzaga",
  "Marquette", "Howard", "SMU", "SUNY Binghamton",
  "University of Vermont", "Colorado School of Mines",
  // Other state universities
  "University of Alaska Fairbanks", "University of Alaska Anchorage",
  "University of Hawaii", "University of Hawaii Manoa",
  "University of Idaho", "University of Montana",
  "University of Wyoming", "University of North Dakota",
  "University of South Dakota", "North Dakota State",
  "South Dakota State", "University of Maine",
  "University of New Hampshire", "University of Rhode Island",
  "University of Nevada Reno",
  "UC Davis", "UC Riverside", "UC Merced", "UC Santa Cruz",
  "California State University Sacramento", "California State University Los Angeles",
  "California State University Dominguez Hills", "California State University San Bernardino",
  "California State University Bakersfield", "California State University Chico",
  "California State University East Bay", "California State University Stanislaus",
  "California State University Monterey Bay", "California State University Channel Islands",
  "California State University San Marcos", "Humboldt State", "Sonoma State",
  "Cal Poly San Luis Obispo", "Fresno State",
  "San Francisco State", "Sacramento State",
  // SUNY and CUNY systems
  "SUNY Albany", "SUNY Geneseo", "SUNY Oswego",
  "SUNY Plattsburgh", "SUNY Potsdam", "SUNY New Paltz", "SUNY Oneonta",
  "SUNY Cortland", "SUNY Fredonia", "SUNY Brockport",
  "CUNY Baruch", "CUNY Hunter", "CUNY Brooklyn College", "CUNY Queens College",
  "CUNY City College", "CUNY John Jay", "CUNY Lehman",
  // Big state schools
  "University of Illinois Chicago", "Southern Illinois University",
  "Northern Illinois University", "Eastern Illinois University", "Western Illinois University",
  "Eastern Michigan University", "Northern Michigan University", "Grand Valley State",
  "Saginaw Valley State", "Ferris State", "Lake Superior State",
  "Bowling Green State", "Ohio University", "University of Akron",
  "Wright State", "Youngstown State", "Cleveland State",
  "University of Toledo", "University of Dayton",
  "Indiana State", "Purdue Fort Wayne", "Ball State University",
  "University of Northern Iowa", "University of Wisconsin Milwaukee",
  "University of Wisconsin La Crosse", "University of Wisconsin Eau Claire",
  "University of Wisconsin Oshkosh", "University of Wisconsin Stevens Point",
  "University of Wisconsin Whitewater", "University of Wisconsin Green Bay",
  "University of Wisconsin Stout", "University of Wisconsin Platteville",
  "Minnesota State Mankato", "Minnesota State Moorhead",
  "University of Northern Colorado", "University of Southern Mississippi",
  "Middle Tennessee State", "East Tennessee State",
  "Tennessee State", "Austin Peay State",
  "Appalachian State", "UNC Greensboro", "UNC Wilmington",
  "UNC Asheville", "Western Carolina", "Fayetteville State",
  "James Madison University", "Radford University",
  "University of Mary Washington", "Longwood University",
  "Norfolk State", "Virginia State",
  "Salisbury University",
  "Frostburg State", "Coppin State", "Bowie State",
  "University of Maryland Baltimore County",
  "Marshall University", "Shepherd University",
  "West Virginia State",
  "Georgia Southern", "Valdosta State", "University of West Georgia",
  "Albany State", "Fort Valley State",
  "Jacksonville State", "Troy University",
  "University of South Alabama", "University of North Alabama",
  "Alabama A&M", "Alabama State",
  "Florida Gulf Coast", "University of North Florida",
  "University of West Florida",
  "Eastern Kentucky", "Western Kentucky", "Murray State",
  "Morehead State", "Northern Kentucky",
  "University of Louisiana Lafayette", "University of Louisiana Monroe",
  "Louisiana Tech", "McNeese State", "Nicholls State",
  "Southeastern Louisiana", "Northwestern State",
  "University of Texas Arlington", "University of Texas Dallas",
  "University of Texas El Paso", "University of Texas San Antonio",
  "University of Texas Rio Grande Valley", "Stephen F. Austin",
  "Sam Houston State", "Lamar University", "Tarleton State",
  "Prairie View A&M", "Texas Southern",
  "University of Arkansas Little Rock", "University of Arkansas Pine Bluff",
  "Arkansas State", "Henderson State",
  "Wichita State", "Emporia State", "Fort Hays State", "Pittsburg State",
  // Liberal arts colleges
  "Williams", "Amherst", "Swarthmore", "Pomona", "Bowdoin",
  "Middlebury", "Wellesley", "Carleton", "Claremont McKenna",
  "Haverford", "Colby", "Hamilton", "Grinnell", "Davidson",
  "Colgate", "Harvey Mudd", "Wesleyan", "Vassar", "Bates",
  "Colorado College", "Oberlin", "Macalester", "Kenyon", "Bucknell",
  "Lafayette", "Whitman", "Reed", "Scripps", "Barnard",
  "Bryn Mawr", "Smith", "Mount Holyoke",
  // HBCUs
  "Morehouse", "Spelman", "Tuskegee", "Hampton",
  "Fisk", "Clark Atlanta", "Florida A&M", "North Carolina A&T",
  "Grambling State", "Southern University", "Jackson State",
  "Morgan State", "Delaware State", "Alcorn State",
  "Bethune-Cookman", "Dillard", "Xavier University of Louisiana",
  "Lincoln University", "Langston University",
  "Winston-Salem State", "Elizabeth City State",
  // Service academies
  "West Point", "Naval Academy", "Air Force Academy",
  "Coast Guard Academy", "Merchant Marine Academy",
  // Other well-known privates
  "Brown", "Creighton", "Loyola University Chicago",
  "American University", "Catholic University",
  "Seton Hall", "Fairfield", "Providence College", "DePaul",
  "Duquesne", "University of San Diego", "University of San Francisco",
  "Xavier University", "St. Louis University",
  "Hofstra", "Adelphi", "Quinnipiac", "Sacred Heart", "Marist",
  "Elon", "High Point", "Rollins", "Stetson", "Mercer",
  "Samford", "Belmont", "Lipscomb", "TCU", "Chapman",
  "Whitworth", "University of Puget Sound", "Seattle University",
  "University of Portland", "Willamette", "Lewis & Clark",
  "University of the Pacific",
  "Worcester Polytechnic Institute", "Rose-Hulman", "Olin College",
  "Cooper Union", "Rochester Institute of Technology",
  "Illinois Institute of Technology", "New Jersey Institute of Technology",
  "Clarkson", "Kettering", "Missouri University of Science and Technology",
  "Michigan Technological University",
  "Ithaca College", "St. Lawrence University",
  "Siena", "Le Moyne", "Canisius", "St. Bonaventure",
  "Manhattan College", "Pace University",
  "Babson", "Bentley", "Bryant",
  "Emerson", "Suffolk University",
  "College of the Holy Cross", "Clark University",
  "Brigham Young University Idaho", "Brigham Young University Hawaii",
  "Southern New Hampshire University", "Western Governors University",
  "Grand Canyon University", "Full Sail University",
  "National University", "Capella University", "Walden University",
  "DeVry University", "University of Phoenix",
  "Strayer University", "Kaplan University",
];
