// ~500 largest cities/urban areas in the world
export const largestCitiesHints: string[] = [
  // Top 100 (the actual answers)
  "Tokyo", "Delhi", "Shanghai", "Dhaka", "Cairo",
  "Beijing", "Mumbai", "Mexico City", "Osaka", "São Paulo",
  "Chongqing", "Karachi", "Istanbul", "Kinshasa", "Lagos",
  "Buenos Aires", "Kolkata", "Manila", "Guangzhou", "Tianjin",
  "Lahore", "Bangalore", "Rio de Janeiro", "Shenzhen", "Moscow",
  "Chennai", "Bogota", "Jakarta", "Paris", "Lima",
  "Bangkok", "Hyderabad", "Seoul", "Nagoya", "London",
  "Chengdu", "Tehran", "Nanjing", "Ho Chi Minh City", "Luanda",
  "Ahmedabad", "Kuala Lumpur", "Xi'an", "Hong Kong", "Dongguan",
  "Hangzhou", "Foshan", "Shenyang", "Riyadh", "Baghdad",
  "Santiago", "Surat", "Madrid", "Suzhou", "Pune",
  "Harbin", "Houston", "Dallas", "Toronto", "Dar es Salaam",
  "Miami", "Belo Horizonte", "Singapore", "Philadelphia", "Atlanta",
  "Fukuoka", "Khartoum", "Barcelona", "Johannesburg", "Saint Petersburg",
  "Qingdao", "Dalian", "Washington DC", "Yangon", "Alexandria",
  "Jinan", "Guadalajara", "Melbourne", "Sydney", "Zhengzhou",
  "New York City", "Chittagong", "Changsha", "Addis Ababa", "Nairobi",
  "Taipei", "Los Angeles", "Chicago", "Abidjan", "Monterrey",
  "Casablanca", "Wuhan", "Jaipur", "Berlin", "Cape Town",
  "Kabul", "Kunming", "Changchun", "Medellín", "Brasília",
  // 101–200
  "Ankara", "Jeddah", "Durban", "Pyongyang", "Algiers",
  "Hefei", "Wenzhou", "Shantou", "Fuzhou", "Xiamen",
  "Taiyuan", "Shijiazhuang", "Ürümqi", "Guiyang", "Nanning",
  "Lanzhou", "Wuxi", "Ningbo", "Nanchang", "Zibo",
  "Tangshan", "Baotou", "Handan", "Xuzhou", "Yantai",
  "Faisalabad", "Rawalpindi", "Multan", "Gujranwala", "Peshawar",
  "Lucknow", "Kanpur", "Nagpur", "Indore", "Patna",
  "Bhopal", "Vadodara", "Coimbatore", "Ludhiana", "Agra",
  "Visakhapatnam", "Nashik", "Ranchi", "Varanasi", "Madurai",
  "Meerut", "Rajkot", "Srinagar", "Aurangabad", "Jodhpur",
  "Kampala", "Lusaka", "Maputo", "Harare", "Accra",
  "Kumasi", "Bamako", "Ouagadougou", "Conakry", "Lomé",
  "Mogadishu", "Douala", "Yaoundé", "Lubumbashi", "Brazzaville",
  "Antananarivo", "Dakar", "Niamey", "N'Djamena", "Freetown",
  "Monrovia", "Lilongwe", "Kigali", "Bujumbura", "Nouakchott",
  "Port-au-Prince", "Tegucigalpa", "Guatemala City", "San Salvador", "Managua",
  "San José", "Panama City", "Havana", "Santo Domingo", "Kingston",
  "Quito", "La Paz", "Asunción", "Montevideo", "Caracas",
  "Maracaibo", "Valencia", "Cali", "Barranquilla", "Cartagena",
  "Arequipa", "Trujillo", "Guayaquil", "Curitiba", "Recife",
  // 201–300
  "Porto Alegre", "Salvador", "Fortaleza", "Manaus", "Belém",
  "Goiânia", "Campinas", "Vitória", "Santos", "Florianópolis",
  "San Francisco", "Seattle", "Boston", "Denver", "Phoenix",
  "San Diego", "Minneapolis", "Detroit", "St. Louis", "Tampa",
  "Orlando", "Charlotte", "Portland", "Pittsburgh", "Las Vegas",
  "Austin", "Nashville", "Indianapolis", "Columbus", "San Antonio",
  "Kansas City", "Cincinnati", "Cleveland", "Milwaukee", "Raleigh",
  "Sacramento", "Salt Lake City", "Hartford", "Jacksonville", "Memphis",
  "Richmond", "Buffalo", "Birmingham", "Louisville", "Oklahoma City",
  "Tucson", "El Paso", "Albuquerque", "Omaha", "Honolulu",
  "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa",
  "Winnipeg", "Quebec City", "Hamilton", "Halifax", "Victoria",
  "Rome", "Milan", "Naples", "Turin", "Palermo",
  "Genoa", "Florence", "Bologna", "Catania", "Venice",
  "Lisbon", "Porto", "Amsterdam", "Rotterdam", "The Hague",
  "Brussels", "Antwerp", "Vienna", "Zurich", "Geneva",
  "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart",
  "Düsseldorf", "Dresden", "Leipzig", "Hanover", "Nuremberg",
  "Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań",
  "Prague", "Budapest", "Bucharest", "Sofia", "Belgrade",
  // 301–400
  "Zagreb", "Ljubljana", "Bratislava", "Vilnius", "Riga",
  "Tallinn", "Helsinki", "Stockholm", "Oslo", "Copenhagen",
  "Dublin", "Edinburgh", "Glasgow", "Manchester", "Birmingham",
  "Leeds", "Liverpool", "Bristol", "Sheffield", "Newcastle",
  "Nottingham", "Cardiff", "Belfast", "Athens", "Thessaloniki",
  "Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk",
  "Minsk", "Tbilisi", "Yerevan", "Baku", "Tashkent",
  "Almaty", "Astana", "Bishkek", "Dushanbe", "Ashgabat",
  "Ulaanbaatar", "Kathmandu", "Colombo", "Hanoi", "Da Nang",
  "Hai Phong", "Phnom Penh", "Vientiane", "Mandalay", "Chittagong",
  "Surabaya", "Bandung", "Medan", "Semarang", "Makassar",
  "Palembang", "Depok", "Tangerang", "Bekasi", "Batam",
  "Cebu City", "Davao", "Zamboanga", "Quezon City", "Caloocan",
  "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju",
  "Sapporo", "Kobe", "Kyoto", "Hiroshima", "Sendai",
  "Kitakyushu", "Yokohama", "Kawasaki", "Chiba", "Niigata",
  "Muscat", "Doha", "Abu Dhabi", "Dubai", "Kuwait City",
  "Manama", "Amman", "Beirut", "Damascus", "Aleppo",
  "Tel Aviv", "Jerusalem", "Haifa", "Mecca", "Medina",
  "Dammam", "Basra", "Mosul", "Erbil", "Kirkuk",
  // 401–500+
  "Port Moresby", "Suva", "Auckland", "Wellington", "Christchurch",
  "Perth", "Adelaide", "Brisbane", "Gold Coast", "Canberra",
  "Hobart", "Darwin", "Newcastle", "Wollongong",
  "Tirana", "Skopje", "Podgorica", "Sarajevo", "Pristina",
  "Chisinau", "Nicosia", "Reykjavik", "Luxembourg City", "Monaco",
  "Andorra la Vella", "Valletta", "San Marino",
  "Rabat", "Marrakech", "Fez", "Tangier", "Tunis",
  "Sfax", "Tripoli", "Benghazi", "Misrata",
  "Mombasa", "Zanzibar", "Arusha", "Dodoma",
  "Bulawayo", "Pretoria", "Port Elizabeth", "Bloemfontein",
  "Windhoek", "Gaborone", "Maseru", "Mbabane",
  "Port Louis", "Victoria", "Moroni", "Djibouti",
  "Asmara", "Juba", "Bangui", "Libreville", "Malabo",
  "São Tomé", "Praia",
  "Belmopan", "Nassau", "Bridgetown", "Port of Spain",
  "Georgetown", "Paramaribo", "Cayenne",
  "San Juan", "Havana", "Port-au-Prince",
  "Punta Cana", "Cancún", "Acapulco", "Tijuana",
  "Puebla", "León", "Querétaro", "Mérida", "Toluca",
  "Chihuahua", "Saltillo", "Hermosillo", "Culiacán", "Morelia",
  "Veracruz", "Aguascalientes", "San Luis Potosí", "Tampico",
];
