// ~800 Broadway/Off-Broadway/West End show names for autocomplete hints
export const longestRunningBroadwayShowsHints: string[] = [
  // Top 100 (the actual answers)
  "The Phantom of the Opera", "Chicago", "The Lion King", "Wicked", "Cats",
  "Les Misérables", "A Chorus Line", "Oh! Calcutta!", "Mamma Mia!", "The Book of Mormon",
  "Beauty and the Beast", "Rent", "Jersey Boys", "Aladdin", "Miss Saigon",
  "Hamilton", "42nd Street", "Grease", "Fiddler on the Roof", "Life with Father",
  "Tobacco Road", "Hello, Dolly!", "My Fair Lady", "Hairspray", "Mary Poppins",
  "Harry Potter and the Cursed Child", "Avenue Q", "Kinky Boots", "The Producers",
  "Beautiful: The Carole King Musical", "Annie", "Cabaret", "Man of La Mancha",
  "Rock of Ages", "Abie's Irish Rose", "Hadestown", "Oklahoma!", "Moulin Rouge!",
  "Smokey Joe's Cafe", "Pippin", "South Pacific", "The Magic Show", "Six",
  "Aida", "Gemini", "Deathtrap", "Harvey", "Dancin'", "La Cage aux Folles", "Hair",
  "MJ the Musical", "Dear Evan Hansen", "The Wiz", "Come from Away", "Born Yesterday",
  "Crazy for You", "Ain't Misbehavin'", "The Best Little Whorehouse in Texas",
  "Spamalot", "Mary, Mary", "Evita", "The Voice of the Turtle", "Matilda the Musical",
  "Waitress", "Jekyll & Hyde", "Barefoot in the Park", "Dreamgirls", "Mame",
  "Same Time, Next Year", "Arsenic and Old Lace", "The Sound of Music", "Me and My Girl",
  "& Juliet", "How to Succeed in Business Without Really Trying", "Hellzapoppin",
  "The Music Man", "Funny Girl", "Mummenschanz", "Billy Elliot the Musical",
  "School of Rock", "Movin' Out", "Brighton Beach Memoirs", "Angel Street", "Lightnin'",
  "Promises, Promises", "The King and I", "Cactus Flower", "Torch Song Trilogy",
  "Sleuth", "1776", "Equus", "Sugar Babies", "Guys and Dolls", "In the Heights",
  "Amadeus", "Once", "Memphis", "Beetlejuice", "Stomp",

  // ==================== GOLDEN AGE MUSICALS (1940s-1960s) ====================
  "Annie Get Your Gun", "Carousel", "Pal Joey", "Brigadoon", "Call Me Madam",
  "Wonderful Town", "The Pajama Game", "Damn Yankees", "West Side Story", "Candide",
  "Gypsy", "The Unsinkable Molly Brown", "Little Me", "Bye Bye Birdie", "Oliver!",
  "Golden Boy", "Camelot", "Do I Hear a Waltz?", "I Do! I Do!", "Applause",
  "Company", "Follies", "A Little Night Music", "Sweeney Todd", "Barnum",
  "Woman of the Year", "Nine", "On the Town", "Gentlemen Prefer Blondes",
  "Flower Drum Song", "The Most Happy Fella", "Bells Are Ringing",
  "No No Nanette", "Show Boat", "Porgy and Bess", "Lady in the Dark",
  "Kiss Me Kate", "Where's Charley?", "Peter Pan", "The Boy Friend",
  "Plain and Fancy", "Silk Stockings", "Li'l Abner", "New Girl in Town",
  "Redhead", "Take Me Along", "Destry Rides Again", "Irma La Douce",
  "Carnival!", "How to Succeed in Business Without Really Trying",
  "A Funny Thing Happened on the Way to the Forum", "She Loves Me",
  "110 in the Shade", "Sweet Charity", "Mame", "I Do! I Do!",

  // ==================== CLASSIC PLAYS ====================
  "Death of a Salesman", "A Streetcar Named Desire", "The Glass Menagerie",
  "Long Day's Journey into Night", "A View from the Bridge", "Waiting for Godot",
  "Cat on a Hot Tin Roof", "The Crucible", "All My Sons", "The Iceman Cometh",
  "Our Town", "Of Mice and Men", "The Children's Hour", "Blithe Spirit",
  "The Importance of Being Earnest", "Private Lives", "Design for Living",
  "The Philadelphia Story", "The Women", "The Heiress", "Bus Stop",
  "Witness for the Prosecution", "Separate Tables", "Look Back in Anger",
  "The Birthday Party", "The Homecoming", "Rosencrantz and Guildenstern Are Dead",
  "The Odd Couple", "Plaza Suite", "The Sunshine Boys", "California Suite",
  "Chapter Two", "The Real Thing", "Noises Off", "Biloxi Blues",
  "Broadway Bound", "Lost in Yonkers", "Lend Me a Tenor", "Rumors",
  "The Heidi Chronicles", "The Piano Lesson", "Two Trains Running",
  "Three Tall Women", "Who's Afraid of Virginia Woolf?",

  // ==================== 1970s-1980s MUSICALS ====================
  "Pacific Overtures", "The Act", "Ballroom", "Big River",
  "Into the Woods", "The Mystery of Edwin Drood", "Song and Dance",
  "Starlight Express", "Chess", "Jerome Robbins' Broadway", "Grand Hotel",
  "City of Angels", "The Will Rogers Follies", "Five Guys Named Moe",
  "Jelly's Last Jam", "The Who's Tommy", "Kiss of the Spider Woman",
  "Passion", "Sunset Boulevard", "Victor/Victoria",

  // ==================== 1990s-2000s MUSICALS ====================
  "Bring in 'da Noise, Bring in 'da Funk", "Titanic", "Side Show",
  "The Full Monty", "Contact", "Fosse", "Jane Eyre", "Urinetown",
  "Thoroughly Modern Millie", "The 25th Annual Putnam County Spelling Bee",
  "The Color Purple", "Spring Awakening", "Dirty Rotten Scoundrels",
  "The Light in the Piazza", "Caroline or Change", "Assassins",
  "The Drowsy Chaperone", "Xanadu", "Next to Normal", "Ghost the Musical",
  "Newsies", "Anything Goes", "Sister Act", "Finian's Rainbow",
  "The Scottsboro Boys", "Bring It On",

  // ==================== 2010s MUSICALS ====================
  "Priscilla Queen of the Desert", "War Horse", "Nice Work If You Can Get It",
  "Rodgers + Hammerstein's Cinderella", "Motown the Musical",
  "A Gentleman's Guide to Love & Murder", "If/Then", "Hedwig and the Angry Inch",
  "The Last Ship", "Fun Home", "Something Rotten!", "Shuffle Along",
  "Natasha, Pierre & the Great Comet of 1812", "Groundhog Day", "Bandstand",
  "Once on This Island", "Frozen", "Mean Girls", "Tootsie",
  "Jagged Little Pill", "Flying Over Sunset", "American Idiot",
  "Ain't Too Proud", "Tina: The Tina Turner Musical", "The Cher Show",
  "Summer: The Donna Summer Musical", "Head Over Heels",

  // ==================== 2020s MUSICALS ====================
  "Company", "Paradise Square", "Mr. Saturday Night", "Into the Woods",
  "The Music Man", "American Buffalo", "KPOP", "Almost Famous",
  "Some Like It Hot", "Shucked", "New York, New York", "Here Lies Love",
  "Suffs", "The Notebook", "The Outsiders", "Hell's Kitchen", "Appropriate",
  "Boop! The Betty Boop Musical", "Dead Outlaw", "Buena Vista Social Club",
  "Back to the Future", "Lempicka", "Water for Elephants",
  "The Great Gatsby", "Smash", "Gypsy", "Maybe Happy Ending",

  // ==================== NOTABLE PLAYS (MODERN ERA) ====================
  "Copenhagen", "The Invention of Love", "The Coast of Utopia", "Democracy",
  "The History Boys", "The Pillowman", "The Lieutenant of Inishmore", "Doubt",
  "August: Osage County", "Race", "Other Desert Cities", "Seminar",
  "Vanya and Sonia and Masha and Spike", "Disgraced",
  "The Curious Incident of the Dog in the Night-Time", "It's Only a Play",
  "The Humans", "Oslo", "A Doll's House Part 2", "Sweat", "Ink",
  "The Ferryman", "Slave Play", "The Sound Inside", "To Kill a Mockingbird",
  "Leopoldstadt", "The Inheritance", "Sea Wall / A Life", "The Minutes",
  "Hangmen", "Take Me Out", "The Lehman Trilogy",
  "Good Night, Oscar", "Stereophonic", "An Enemy of the People",
  "The Notebook", "Purlie Victorious", "Prayer for the French Republic",
  "The Outsiders", "Water for Elephants", "Swept Away",

  // ==================== OFF-BROADWAY FAVORITES ====================
  "The Fantasticks", "Little Shop of Horrors", "Steel Magnolias",
  "Driving Miss Daisy", "I Love You, You're Perfect, Now Change",
  "Blue Man Group", "De La Guarda", "Altar Boyz", "[title of show]",
  "Bloody Bloody Andrew Jackson", "Passing Strange", "The 39 Steps",
  "The Normal Heart", "Love! Valour! Compassion!", "Falsettos",
  "March of the Falsettos", "The Mystery of Irma Vep", "A New Brain",
  "Floyd Collins", "Songs for a New World", "Tick, Tick... Boom!",
  "The Last Five Years", "Forbidden Broadway", "Perfect Crime",
  "Tony n' Tina's Wedding", "Nunsense", "Menopause the Musical",
  "Drunk Shakespeare", "Sleep No More", "Puffs",
  "Be More Chill", "What the Constitution Means to Me",

  // ==================== WEST END / BRITISH IMPORTS ====================
  "Blood Brothers", "Aspects of Love", "Educating Rita", "Arcadia",
  "Closer", "The Blue Room", "The Judas Kiss", "Art", "Copenhagen",
  "The Seafarer", "Jerusalem", "Billy Elliot", "Matilda",
  "The Woman in Black", "Les Misérables", "Miss Saigon",
  "Joseph and the Amazing Technicolor Dreamcoat", "Jesus Christ Superstar",
  "Evita", "The Mousetrap", "An Inspector Calls",
  "The Play That Goes Wrong", "Life of Pi", "Operation Mincemeat",
  "My Neighbor Totoro", "Cabaret",

  // ==================== JUKEBOX / CATALOG MUSICALS ====================
  "Mamma Mia!", "Jersey Boys", "Rock of Ages", "Beautiful",
  "American Idiot", "Motown the Musical", "Ain't Too Proud",
  "Tina: The Tina Turner Musical", "MJ the Musical", "The Cher Show",
  "Head Over Heels", "& Juliet", "Girl from the North Country",
  "Jagged Little Pill", "Moulin Rouge!", "Escape to Margaritaville",
  "On Your Feet!", "Summer: The Donna Summer Musical",
  "A Night with Janis Joplin", "Smokey Joe's Cafe",

  // ==================== FAMILY / DISNEY SHOWS ====================
  "The Lion King", "Aladdin", "Beauty and the Beast", "Frozen",
  "The Little Mermaid", "Tarzan", "Mary Poppins", "Newsies",
  "Shrek the Musical", "Charlie and the Chocolate Factory",
  "Elf the Musical", "SpongeBob SquarePants: The Musical",
  "Tuck Everlasting", "Anastasia", "Mrs. Doubtfire",

  // ==================== REVIVALS ====================
  "Sweeney Todd", "The Drowsy Chaperone", "South Pacific", "Finian's Rainbow",
  "A Little Night Music", "How to Succeed in Business Without Really Trying",
  "Porgy and Bess", "Annie", "Pippin", "The King and I",
  "Hello, Dolly!", "My Fair Lady", "Funny Girl", "Into the Woods",
  "Company", "Cabaret", "Cats", "West Side Story", "Caroline, or Change",
  "Merrily We Roll Along", "Parade", "Sweeney Todd", "The Wiz",
  "Once Upon a Mattress", "Gypsy", "Chicago",

  // ==================== DANCE / SPECTACLE ====================
  "Riverdance", "Lord of the Dance", "Stomp", "Blue Man Group",
  "Tap Dance Kid", "Fosse", "Contact", "Burn the Floor",
  "Forever Tango", "Tango Argentino",
];
