// ~500 songs for Billboard Hot 100 longest-charting hints
// Format: "Song Name - Artist Name"
export const longestChartingHot100Hints: string[] = [
  // Top 100 (the actual answers) — all-time most total weeks on the Billboard Hot 100
  "Lose Control - Teddy Swims",
  "Heat Waves - Glass Animals",
  "Blinding Lights - The Weeknd",
  "Beautiful Things - Benson Boone",
  "Radioactive - Imagine Dragons",
  "Sail - AWOLNATION",
  "Levitating - Dua Lipa",
  "I'm Yours - Jason Mraz",
  "Wildflower - Billie Eilish",
  "A Bar Song (Tipsy) - Shaboozey",
  "All I Want for Christmas Is You - Mariah Carey",
  "Rockin' Around the Christmas Tree - Brenda Lee",
  "Jingle Bell Rock - Bobby Helms",
  "Stay - The Kid Laroi & Justin Bieber",
  "Last Night - Morgan Wallen",
  "Believer - Imagine Dragons",
  "Thunder - Imagine Dragons",
  "Natural - Imagine Dragons",
  "Enemy - Imagine Dragons",
  "Demons - Imagine Dragons",
  "Old Town Road - Lil Nas X ft. Billy Ray Cyrus",
  "Shape of You - Ed Sheeran",
  "Bad Guy - Billie Eilish",
  "Someone You Loved - Lewis Capaldi",
  "Drivers License - Olivia Rodrigo",
  "Good 4 U - Olivia Rodrigo",
  "Traitor - Olivia Rodrigo",
  "Anti-Hero - Taylor Swift",
  "Cruel Summer - Taylor Swift",
  "Shake It Off - Taylor Swift",
  "Blank Space - Taylor Swift",
  "Lover - Taylor Swift",
  "cardigan - Taylor Swift",
  "Style - Taylor Swift",
  "Love Story (Taylor's Version) - Taylor Swift",
  "Uptown Funk - Mark Ronson ft. Bruno Mars",
  "Happy - Pharrell Williams",
  "Rolling in the Deep - Adele",
  "Someone Like You - Adele",
  "Easy on Me - Adele",
  "Hello - Adele",
  "Watermelon Sugar - Harry Styles",
  "As It Was - Harry Styles",
  "Late Night Talking - Harry Styles",
  "Adore You - Harry Styles",
  "Sunflower - Post Malone & Swae Lee",
  "Rockstar - Post Malone ft. 21 Savage",
  "Circles - Post Malone",
  "Congratulations - Post Malone",
  "White Iverson - Post Malone",
  "God's Plan - Drake",
  "One Dance - Drake",
  "Hotline Bling - Drake",
  "In My Feelings - Drake",
  "Nice for What - Drake",
  "Starboy - The Weeknd ft. Daft Punk",
  "Save Your Tears - The Weeknd",
  "Die For You - The Weeknd",
  "Can't Feel My Face - The Weeknd",
  "The Hills - The Weeknd",
  "Despacito - Luis Fonsi ft. Daddy Yankee",
  "Perfect - Ed Sheeran",
  "Thinking Out Loud - Ed Sheeran",
  "Photograph - Ed Sheeran",
  "Bad Habits - Ed Sheeran",
  "Counting Stars - OneRepublic",
  "Apologize - Timbaland ft. OneRepublic",
  "Treat You Better - Shawn Mendes",
  "Señorita - Shawn Mendes & Camila Cabello",
  "Stitches - Shawn Mendes",
  "In My Blood - Shawn Mendes",
  "Dance Monkey - Tones and I",
  "Closer - The Chainsmokers ft. Halsey",
  "Don't Let Me Down - The Chainsmokers ft. Daya",
  "Something Just Like This - The Chainsmokers & Coldplay",
  "Havana - Camila Cabello ft. Young Thug",
  "Never Be the Same - Camila Cabello",
  "7 Rings - Ariana Grande",
  "Thank U, Next - Ariana Grande",
  "Problem - Ariana Grande ft. Iggy Azalea",
  "Into You - Ariana Grande",
  "No Tears Left to Cry - Ariana Grande",
  "Rain on Me - Lady Gaga & Ariana Grande",
  "Shallow - Lady Gaga & Bradley Cooper",
  "Die with a Smile - Lady Gaga & Bruno Mars",
  "24K Magic - Bruno Mars",
  "That's What I Like - Bruno Mars",
  "Locked Out of Heaven - Bruno Mars",
  "Just the Way You Are - Bruno Mars",
  "Grenade - Bruno Mars",
  "Flowers - Miley Cyrus",
  "Wrecking Ball - Miley Cyrus",
  "Stay With Me - Sam Smith",
  "Unholy - Sam Smith & Kim Petras",
  "All of Me - John Legend",
  "HUMBLE. - Kendrick Lamar",
  "DNA. - Kendrick Lamar",
  "Not Like Us - Kendrick Lamar",
  "Peaches - Justin Bieber ft. Daniel Caesar & Giveon",
  "Love Yourself - Justin Bieber",
  "What Do You Mean? - Justin Bieber",
  "Sorry - Justin Bieber",
  // 101–200 additional popular hits for hints
  "Sicko Mode - Travis Scott",
  "Goosebumps - Travis Scott",
  "Industry Baby - Lil Nas X & Jack Harlow",
  "Montero (Call Me by Your Name) - Lil Nas X",
  "Lean On - Major Lazer & DJ Snake ft. MO",
  "Cheap Thrills - Sia",
  "Chandelier - Sia",
  "Elastic Heart - Sia",
  "New Rules - Dua Lipa",
  "Don't Start Now - Dua Lipa",
  "Physical - Dua Lipa",
  "Levitating - Dua Lipa ft. DaBaby",
  "One Kiss - Calvin Harris & Dua Lipa",
  "Girls Like You - Maroon 5 ft. Cardi B",
  "Sugar - Maroon 5",
  "Memories - Maroon 5",
  "Animals - Maroon 5",
  "Maps - Maroon 5",
  "Moves Like Jagger - Maroon 5 ft. Christina Aguilera",
  "This Is America - Childish Gambino",
  "Redbone - Childish Gambino",
  "Mood - 24kGoldn ft. iann dior",
  "Snowman - Sia",
  "Dynamite - BTS",
  "Butter - BTS",
  "Permission to Dance - BTS",
  "My Universe - Coldplay & BTS",
  "Yellow - Coldplay",
  "The Scientist - Coldplay",
  "Clocks - Coldplay",
  "Fix You - Coldplay",
  "A Sky Full of Stars - Coldplay",
  "Adventure of a Lifetime - Coldplay",
  "Heather - Conan Gray",
  "Maniac - Conan Gray",
  "Found Heaven - Conan Gray",
  "Vampire - Olivia Rodrigo",
  "brutal - Olivia Rodrigo",
  "deja vu - Olivia Rodrigo",
  "favorite crime - Olivia Rodrigo",
  "enough for you - Olivia Rodrigo",
  "hope ur ok - Olivia Rodrigo",
  "happier - Olivia Rodrigo",
  "lacy - Olivia Rodrigo",
  "bad idea right? - Olivia Rodrigo",
  "get him back! - Olivia Rodrigo",
  "Murder on the Dancefloor - Sophie Ellis-Bextor",
  "Espresso - Sabrina Carpenter",
  "Please Please Please - Sabrina Carpenter",
  "Nonsense - Sabrina Carpenter",
  "feather - Sabrina Carpenter",
  "Taste - Sabrina Carpenter",
  "Bed Chem - Sabrina Carpenter",
  "Compass - Sabrina Carpenter",
  "Short n' Sweet - Sabrina Carpenter",
  "Running Up That Hill - Kate Bush",
  "Hound Dog - Elvis Presley",
  "Jailhouse Rock - Elvis Presley",
  "Suspicious Minds - Elvis Presley",
  "Don't Be Cruel - Elvis Presley",
  "Are You Lonesome Tonight? - Elvis Presley",
  "Love Me Tender - Elvis Presley",
  "In the Ghetto - Elvis Presley",
  "A Little Less Conversation - Elvis Presley",
  "I Want to Hold Your Hand - The Beatles",
  "Hey Jude - The Beatles",
  "Let It Be - The Beatles",
  "Come Together - The Beatles",
  "Yesterday - The Beatles",
  "Something - The Beatles",
  "Help! - The Beatles",
  "We Can Work It Out - The Beatles",
  "Twist and Shout - The Beatles",
  "A Hard Day's Night - The Beatles",
  "Bohemian Rhapsody - Queen",
  "We Will Rock You - Queen",
  "We Are the Champions - Queen",
  "Don't Stop Me Now - Queen",
  "Somebody to Love - Queen",
  "Radio Ga Ga - Queen",
  "I Want to Break Free - Queen",
  "Under Pressure - Queen & David Bowie",
  "Killer Queen - Queen",
  "Another One Bites the Dust - Queen",
  "Hotel California - Eagles",
  "Take It Easy - Eagles",
  "Life in the Fast Lane - Eagles",
  "Desperado - Eagles",
  "Lyin' Eyes - Eagles",
  "One of These Nights - Eagles",
  "New Kid in Town - Eagles",
  "Heartache Tonight - Eagles",
  "The Long Run - Eagles",
  "I Can't Tell You Why - Eagles",
  "Born to Run - Bruce Springsteen",
  "Dancing in the Dark - Bruce Springsteen",
  "Hungry Heart - Bruce Springsteen",
  "Glory Days - Bruce Springsteen",
  "I'm on Fire - Bruce Springsteen",
  "Streets of Philadelphia - Bruce Springsteen",
  "Brilliant Disguise - Bruce Springsteen",
  "Tunnel of Love - Bruce Springsteen",
  "Human Touch - Bruce Springsteen",
  "The Rising - Bruce Springsteen",
  "Billie Jean - Michael Jackson",
  "Beat It - Michael Jackson",
  "Thriller - Michael Jackson",
  "Black or White - Michael Jackson",
  "Man in the Mirror - Michael Jackson",
  "Don't Stop 'Til You Get Enough - Michael Jackson",
  "Rock with You - Michael Jackson",
  "Off the Wall - Michael Jackson",
  "Bad - Michael Jackson",
  "Smooth Criminal - Michael Jackson",
  "Respect - Aretha Franklin",
  "Chain of Fools - Aretha Franklin",
  "I Say a Little Prayer - Aretha Franklin",
  "Think - Aretha Franklin",
  "A Natural Woman - Aretha Franklin",
  "Until You Come Back to Me - Aretha Franklin",
  "Spanish Harlem - Aretha Franklin",
  "Baby I Love You - Aretha Franklin",
  "Call Me - Blondie",
  "Heart of Glass - Blondie",
  "Rapture - Blondie",
  "The Tide Is High - Blondie",
  "One Way or Another - Blondie",
  "Hanging on the Telephone - Blondie",
  "I Love Rock 'n' Roll - Joan Jett & The Blackhearts",
  "Bad Reputation - Joan Jett",
  "Eye of the Tiger - Survivor",
  "Don't You (Forget About Me) - Simple Minds",
  "Take My Breath Away - Berlin",
  "Every Breath You Take - The Police",
  "Roxanne - The Police",
  "Don't Stand So Close to Me - The Police",
  "Message in a Bottle - The Police",
  "Walking on Sunshine - Katrina and the Waves",
  "Girls Just Want to Have Fun - Cyndi Lauper",
  "Time After Time - Cyndi Lauper",
  "True Colors - Cyndi Lauper",
  "Material Girl - Madonna",
  "Like a Virgin - Madonna",
  "Papa Don't Preach - Madonna",
  "Like a Prayer - Madonna",
  "Vogue - Madonna",
  "Take a Bow - Madonna",
  "Frozen - Madonna",
  "Ray of Light - Madonna",
  "Music - Madonna",
  "Hung Up - Madonna",
  "Smells Like Teen Spirit - Nirvana",
  "Come as You Are - Nirvana",
  "In Bloom - Nirvana",
  "Heart-Shaped Box - Nirvana",
  "All Apologies - Nirvana",
  "Lithium - Nirvana",
  "Rape Me - Nirvana",
  "Jeremy - Pearl Jam",
  "Black - Pearl Jam",
  "Better Man - Pearl Jam",
  "Alive - Pearl Jam",
  "Hunger Strike - Temple of the Dog",
  "Under the Bridge - Red Hot Chili Peppers",
  "Give It Away - Red Hot Chili Peppers",
  "Californication - Red Hot Chili Peppers",
  "Scar Tissue - Red Hot Chili Peppers",
  "By the Way - Red Hot Chili Peppers",
  "Can't Stop - Red Hot Chili Peppers",
  "Dani California - Red Hot Chili Peppers",
  "Dark Necessities - Red Hot Chili Peppers",
  "Mr. Brightside - The Killers",
  "Somebody Told Me - The Killers",
  "Jealousy - The Killers",
  "All These Things That I've Done - The Killers",
  "Human - The Killers",
  "Smile - Katy Perry",
  "Roar - Katy Perry",
  "Dark Horse - Katy Perry",
  "Firework - Katy Perry",
  "Teenage Dream - Katy Perry",
  "California Gurls - Katy Perry ft. Snoop Dogg",
  "E.T. - Katy Perry ft. Kanye West",
  "Wide Awake - Katy Perry",
  "I Kissed a Girl - Katy Perry",
  "Hot N Cold - Katy Perry",
  "Tik Tok - Kesha",
  "We R Who We R - Kesha",
  "Your Love Is My Drug - Kesha",
  "Blow - Kesha",
  "Timber - Pitbull ft. Kesha",
  "Give Me Everything - Pitbull ft. Ne-Yo",
  "International Love - Pitbull ft. Chris Brown",
  "Feel This Moment - Pitbull ft. Christina Aguilera",
  "Empire State of Mind - Jay-Z ft. Alicia Keys",
  "Run This Town - Jay-Z ft. Rihanna & Kanye West",
  "99 Problems - Jay-Z",
  "Niggas in Paris - Jay-Z & Kanye West",
  "Fancy - Iggy Azalea ft. Charli XCX",
  "Black Widow - Iggy Azalea ft. Rita Ora",
  "Work - Rihanna ft. Drake",
  "Umbrella - Rihanna",
  "Needed Me - Rihanna",
  "We Found Love - Rihanna ft. Calvin Harris",
  "Diamonds - Rihanna",
  "Stay - Rihanna ft. Mikky Ekko",
  "Pour It Up - Rihanna",
  "B*tch Better Have My Money - Rihanna",
  "Wild Thoughts - DJ Khaled ft. Rihanna & Bryson Tiller",
  "Love the Way You Lie - Eminem ft. Rihanna",
  "The Monster - Eminem ft. Rihanna",
  "Not Afraid - Eminem",
  "Rap God - Eminem",
  "Lose Yourself - Eminem",
  "Without Me - Eminem",
  "Slim Shady - Eminem",
  "The Real Slim Shady - Eminem",
  "Stan - Eminem ft. Dido",
  "Mockingbird - Eminem",
  "SICKO MODE - Travis Scott",
  "Antidote - Travis Scott",
  "Highest in the Room - Travis Scott",
  "Goosebumps - Travis Scott ft. Kendrick Lamar",
  "FE!N - Travis Scott ft. Playboi Carti",
  "K-Pop - Travis Scott",
  "Escape Plan - Travis Scott",
  "FEELit - Travis Scott",
  "Carousel - Travis Scott",
  "Mamacita - Travis Scott",
  "WAP - Cardi B ft. Megan Thee Stallion",
  "Bodak Yellow - Cardi B",
  "Money - Cardi B",
  "I Like It - Cardi B ft. Bad Bunny & J Balvin",
  "Bartier Cardi - Cardi B",
  "Drip - Cardi B ft. Migos",
  "Up - Cardi B",
  "Bad and Boujee - Migos ft. Lil Uzi Vert",
  "Versace - Migos",
  "Slippery - Migos ft. Gucci Mane",
  "MotorSport - Migos ft. Nicki Minaj & Cardi B",
  "Stir Fry - Migos",
  "Walk It Talk It - Migos ft. Drake",
  "Supastars - Migos",
  "Superstars - Migos",
  "Ric Flair Drip - 21 Savage & Offset",
  "Bank Account - 21 Savage",
  "X - 21 Savage",
  "A Lot - 21 Savage ft. J. Cole",
  "Immortal - 21 Savage",
  "Knife Talk - Drake ft. 21 Savage & Project Pat",
  "Jimmy Cooks - Drake ft. 21 Savage",
  "Rich Flex - Drake & 21 Savage",
  "Major Distribution - Drake & 21 Savage",
  "Middle of the Ocean - Drake & 21 Savage",
  "Spin Bout U - Drake & 21 Savage",
  "Privileged Rappers - 21 Savage & Drake",
  "Tequila - Dan + Shay",
  "Speechless - Dan + Shay",
  "10,000 Hours - Dan + Shay & Justin Bieber",
  "I Should Probably Go to Bed - Dan + Shay",
  "From the Ground Up - Dan + Shay",
  "Body Like a Back Road - Sam Hunt",
  "Make You Miss Me - Sam Hunt",
  "Leave the Night On - Sam Hunt",
  "Take Your Time - Sam Hunt",
  "Hard to Forget - Sam Hunt",
  "Kinfolks - Sam Hunt",
  "Tennessee Whiskey - Chris Stapleton",
  "Nobody to Blame - Chris Stapleton",
  "Fire Away - Chris Stapleton",
  "Broken Halos - Chris Stapleton",
  "Either Way - Chris Stapleton",
  "Starting Over - Chris Stapleton",
  "Fancy Like - Walker Hayes",
  "You Proof - Morgan Wallen",
  "Sand in My Boots - Morgan Wallen",
  "Wasted on You - Morgan Wallen",
  "More Than My Hometown - Morgan Wallen",
  "7 Summers - Morgan Wallen",
  "Whiskey Glasses - Morgan Wallen",
  "Chasin' You - Morgan Wallen",
  "Cover Me Up - Morgan Wallen",
  "Thought You Should Know - Morgan Wallen",
  "Everything I Love - Morgan Wallen",
  "One Thing at a Time - Morgan Wallen",
  "Cowgirls - Morgan Wallen ft. ERNEST",
  "I Ain't Worried - OneRepublic",
  "No Vacancy - OneRepublic",
  "Stop and Stare - OneRepublic",
  "Secrets - OneRepublic",
  "Feel Again - OneRepublic",
  "Wherever I Go - OneRepublic",
  "West Coast - OneRepublic",
  "Good Life - OneRepublic",
  "Rescue Me - OneRepublic",
  "Didn't I - OneRepublic",
  "Run - OneRepublic",
  "Better Days - OneRepublic",
  "Ordinary (Alex Warren song) - Alex Warren",
  "Burning House - Cam",
  "Merry Go 'Round - Kacey Musgraves",
  "Follow Your Arrow - Kacey Musgraves",
  "Space Cowboy - Kacey Musgraves",
  "High Horse - Kacey Musgraves",
  "Rainbow - Kacey Musgraves",
  "Happy & Sad - Kacey Musgraves",
  "Golden Hour - Kacey Musgraves",
  "Butterflies - Kacey Musgraves",
  "Easy - Kacey Musgraves",
  "Slow Burn - Kacey Musgraves",
  "Velvet Elvis - Zach Bryan",
  "Something in the Orange - Zach Bryan",
  "Heavy Eyes - Zach Bryan",
  "I Remember Everything - Zach Bryan ft. Kacey Musgraves",
  "Quittin Time - Zach Bryan",
  "Oklahoma Smokeshow - Zach Bryan",
  "Smaller Acts - Zach Bryan",
  "Burn Burn Burn - Zach Bryan",
  "Pink Skies - Zach Bryan",
  "Dawns - Zach Bryan ft. Maggie Rogers",
  "Revival - Zach Bryan",
  "Open the Gate - Zach Bryan",
  "Better - Zach Bryan",
  "Tourniquet - Zach Bryan",
  "Overtime - Zach Bryan",
  "I've Been Sober - Zach Bryan",
  "Leaving - Zach Bryan",
  "Highway Boys - Zach Bryan",
  "Music for a Sushi Restaurant - Harry Styles",
  "Grapejuice - Harry Styles",
  "Cinema - Harry Styles",
  "Keep Driving - Harry Styles",
  "Satellite - Harry Styles",
  "Boyfriends - Harry Styles",
  "Daydreaming - Harry Styles",
  "Love of My Life - Harry Styles",
  "Matilda - Harry Styles",
  "Golden - Harry Styles",
  "Falling - Harry Styles",
  "Canyon Moon - Harry Styles",
  "Treat People with Kindness - Harry Styles",
  "She - Harry Styles",
  "Fine Line - Harry Styles",
  "Cherry - Harry Styles",
  "Lights Up - Harry Styles",
  "Sunflower Vol. 6 - Harry Styles",
  "Sweet Creature - Harry Styles",
  "Two Ghosts - Harry Styles",
  "Sign of the Times - Harry Styles",
  "Carolina - Harry Styles",
];
