// ~500 well-known river names (top 100 are the actual answers; the rest are hints/distractors)
export const longestRiversHints: string[] = [
  // Top 100 (the actual answers)
  "Nile", "Amazon", "Yangtze", "Mississippi", "Yenisey",
  "Yellow River", "Ob", "Río de la Plata", "Congo", "Amur",
  "Lena", "Mekong", "Mackenzie", "Niger", "Brahmaputra",
  "Murray", "Tocantins", "Volga", "Euphrates", "Madeira",
  "Purús", "Yukon", "Indus", "São Francisco", "Syr Darya",
  "Salween", "Saint Lawrence", "Rio Grande", "Lower Tunguska", "Colorado",
  "Danube", "Irrawaddy", "Zambezi", "Vilyuy", "Ganges",
  "Amu Darya", "Japurá", "Nelson", "Paraguay", "Kolyma",
  "Pilcomayo", "Upper Ob", "Ishim", "Orange", "Ural",
  "Juruá", "Arkansas", "Songhua", "Olenyok", "Dnieper",
  "Aldan", "Ubangi", "Negro", "Columbia", "Tapajós",
  "Pearl", "Red River", "Kasai", "Ohio", "Orinoco",
  "Tarim", "Xingu", "Jubba", "Brazos", "Northern Salado",
  "Içá", "Vitim", "Chenab", "Tigris", "Don",
  "Stony Tunguska", "Pechora", "Kama", "Limpopo", "Chulym",
  "Guaviare", "Marañón", "Indigirka", "Platte", "Senegal",
  "Khatanga", "Upper Jubba", "Uruguay", "Churchill", "Blue Nile",
  "Okavango", "Volta", "Beni", "Shilka", "Tobol",
  "Alazeya", "Kafue", "Yalong", "Magdalena", "Han",
  "Kura", "Oka", "Upper Murray", "Yana", "Pecos",

  // Additional well-known rivers (hints / distractors)
  // Europe
  "Rhine", "Elbe", "Seine", "Loire", "Rhône",
  "Thames", "Tagus", "Douro", "Ebro", "Garonne",
  "Vistula", "Oder", "Dniester", "Neva", "Western Dvina",
  "Daugava", "Neman", "Vltava", "Main", "Moselle",
  "Saale", "Meuse", "Scheldt", "Weser", "Ems",
  "Trent", "Severn", "Mersey", "Clyde", "Shannon",
  "Liffey", "Dee", "Exe", "Wye", "Avon",
  "Po", "Tiber", "Arno", "Adige", "Piave",
  "Ebro", "Guadalquivir", "Minho", "Tejo", "Júcar",
  "Axios", "Maritsa", "Vardar", "Sava", "Drava",
  "Mur", "Inn", "Salzach", "Traun", "Isar",
  "Tisza", "Prut", "Siret", "Olt", "Argeș",
  "Desna", "Pripyat", "Sozh", "Berezina", "Neman",
  "Nemunas", "Gauja", "Emajõgi", "Pärnu", "Narva",
  "Kemijoki", "Oulujoki", "Kokemäenjoki", "Glomma", "Göta",
  "Dalälven", "Ångermanälven", "Umeälven", "Luleälven", "Torne",
  "Vuoksi", "Svir", "Volkhov", "Onega", "Mezen",
  "Seversky Donets", "Khopyor", "Voronezh", "Oka", "Klyazma",

  // Asia
  "Ganga", "Yamuna", "Godavari", "Krishna", "Narmada",
  "Tapti", "Kaveri", "Mahanadi", "Chambal", "Betwa",
  "Sutlej", "Beas", "Ravi", "Jhelum", "Kabul",
  "Helmand", "Hari", "Oxus", "Zeravshan", "Panj",
  "Karun", "Karkeh", "Zayanderud", "Qezel Ozan", "Safid",
  "Aras", "Kura", "Araks", "Çoruh", "Sakarya",
  "Kızılırmak", "Yeşilırmak", "Büyük Menderes", "Küçük Menderes", "Seyhan",
  "Orontes", "Jordan", "Litani", "Yarmouk", "Tigris",
  "Shatt al-Arab", "Karun", "Diyala", "Greater Zab", "Lesser Zab",
  "Ghaghara", "Kosi", "Gandak", "Son", "Damodar",
  "Mahanadi", "Brahmani", "Baitarani", "Subarnarekha", "Hooghly",
  "Meghna", "Jamuna", "Padma", "Tista", "Buriganga",
  "Irrawaddy", "Chindwin", "Salween", "Sittang", "Rakhine",
  "Chao Phraya", "Mun", "Ping", "Wang", "Nan",
  "Mekong", "Nam Ou", "Nam Khan", "Se Kong", "Se San",
  "Red River", "Ma River", "Da River", "Dong Nai", "Mekong",
  "Yalu", "Tumen", "Han", "Nakdong", "Geum",
  "Liao", "Songhua", "Mudanjiang", "Tumen", "Nen",
  "Huai", "Qiantang", "Min", "Jialing", "Wu",
  "Lancang", "Nujiang", "Yalong", "Dadu", "Minjiang",
  "Kaidu", "Ili", "Ertix", "Tarim", "Yarkand",
  "Selenga", "Onon", "Kherlen", "Orkhon", "Tuul",
  "Angara", "Barguzin", "Selenga", "Uda", "Biryusa",
  "Kolyma", "Indigirka", "Yana", "Lena", "Aldan",

  // Africa
  "Nile", "Congo", "Niger", "Zambezi", "Limpopo",
  "Orange", "Senegal", "Volta", "Benue", "Kasai",
  "Ubangi", "Lomami", "Kagera", "Ruvuma", "Rufiji",
  "Tana", "Jubba", "Shebelle", "Awash", "Omo",
  "Atbarah", "Sobat", "Bahr el Ghazal", "White Nile", "Blue Nile",
  "Chari", "Logone", "Sanaga", "Nyong", "Ogooué",
  "Kwilu", "Kwango", "Sankuru", "Lualaba", "Lukuga",
  "Luapula", "Kafue", "Kabompo", "Lungwebungu", "Cuando",
  "Okavango", "Cuito", "Cuando", "Cunene", "Cuanza",
  "Caledon", "Vaal", "Fish", "Sundays", "Tugela",
  "Mthatha", "Umgeni", "Umfolozi", "Pungwe", "Save",
  "Buzi", "Lúrio", "Rovuma", "Ruvuma", "Shire",
  "Gambia", "Casamance", "Kolenté", "Moa", "Sewa",
  "Rokel", "Bandama", "Sassandra", "Komoe", "Mono",
  "Oueme", "Volta", "Ankobra", "Pra", "Densu",
  "Ogun", "Osun", "Cross", "Gongola", "Sokoto",
  "Komadougou", "Yobe", "Hadejia", "Benue", "Anambra",
  "Betsiboka", "Tsiribihina", "Mangoky", "Onilahý", "Sofia",
  "Mahavavy", "Manambolo", "Onilahy", "Rianila", "Mangoro",
  "Draa", "Moulouya", "Oum Er-Rbia", "Sebou", "Bou Regreg",
  "Chelif", "Medjerda", "Nyanga", "Kouilou", "Fimi",

  // North America
  "Missouri", "Mississippi", "Ohio", "Tennessee", "Cumberland",
  "Arkansas", "Red River", "Brazos", "Colorado", "Platte",
  "Kansas", "Republican", "Cimarron", "Canadian", "Pecos",
  "Gila", "Salt", "Verde", "Hassayampa", "Agua Fria",
  "Sacramento", "San Joaquin", "American", "Feather", "Trinity",
  "Klamath", "Rogue", "Willamette", "Deschutes", "John Day",
  "Columbia", "Snake", "Clearwater", "Salmon", "Payette",
  "Boise", "Bruneau", "Owyhee", "Malheur", "Grande Ronde",
  "Yakima", "Wenatchee", "Okanogan", "Skagit", "Snohomish",
  "Cowlitz", "Lewis", "Nooksack", "Stillaguamish", "Skykomish",
  "Fraser", "Thompson", "Chilcotin", "Nechako", "Stuart",
  "Peace", "Athabasca", "Smoky", "Wapiti", "Hay",
  "Mackenzie", "Liard", "South Nahanni", "Peel", "Arctic Red",
  "Slave", "Hay", "Buffalo", "Fond du Lac", "Clearwater",
  "Saskatchewan", "North Saskatchewan", "South Saskatchewan", "Red Deer", "Bow",
  "Oldman", "St. Mary", "Milk", "Souris", "Assiniboine",
  "Winnipeg", "English", "Albany", "Moose", "Abitibi",
  "Ottawa", "Mattawa", "Rideau", "Gatineau", "Lievre",
  "Saint-Maurice", "Saguenay", "Manicouagan", "Aux Outardes", "Moisie",
  "Romaine", "Koksoak", "Eastmain", "Rupert", "Nottaway",
  "Harricana", "Broadback", "Pontiac", "Abitibi", "Montreal",
  "Detroit", "Saint Clair", "Trent", "Humber", "Don",
  "Niagara", "Welland", "Grand", "Thames", "Sydenham",
  "Nelson", "Churchill", "Seal", "Hayes", "Severn",
  "Winisk", "Attawapiskat", "Ekwan", "Missinaibi", "Groundhog",
  "Yukon", "Tanana", "Koyukuk", "Porcupine", "White",
  "Copper", "Susitna", "Matanuska", "Kenai", "Kasilof",
  "Kuskokwim", "Nushagak", "Kvichak", "Naknek", "Alagnak",
  "Hudson", "Delaware", "Susquehanna", "Potomac", "Shenandoah",
  "James", "Roanoke", "Tar", "Neuse", "Cape Fear",
  "Pee Dee", "Santee", "Cooper", "Edisto", "Savannah",
  "Ogeechee", "Altamaha", "Ocmulgee", "Oconee", "Flint",
  "Chattahoochee", "Tallapoosa", "Coosa", "Alabama", "Tombigbee",
  "Black Warrior", "Cahaba", "Tennessee", "Clinch", "Powell",
  "Holston", "Nolichucky", "French Broad", "Pigeon", "Hiawassee",
  "Watauga", "New", "Kanawha", "Gauley", "Elk",
  "Greenbrier", "Cheat", "Monongahela", "Youghiogheny", "Allegheny",
  "Clarion", "West Branch Susquehanna", "Juniata", "Lehigh", "Schuylkill",
  "Brandywine", "Christina", "Raritan", "Passaic", "Hackensack",
  "Connecticut", "Housatonic", "Quinnipiac", "Merrimack", "Saco",
  "Kennebec", "Androscoggin", "Penobscot", "Saint Croix", "Saint John",
  "Miramichi", "Restigouche", "Matapédia", "Chaudière", "Etchemin",
  "Champlain", "Richelieu", "Yamaska", "Saint Francis", "Nicolet",
  "Des Moines", "Rock", "Illinois", "Kankakee", "Fox",
  "Vermilion", "Mackinaw", "Sangamon", "Kaskaskia", "Big Muddy",
  "Wisconsin", "Chippewa", "Black", "Flambeau", "Eau Claire",
  "Menominee", "Peshtigo", "Fox", "Wolf", "Sheboygan",
  "Minnesota", "Blue Earth", "Cottonwood", "Yellow Medicine", "Redwood",
  "Crow Wing", "Pine", "Rum", "Saint Croix", "Namekagon",
  "Cedar", "Iowa", "Skunk", "Wapsipinicon", "Maquoketa",
  "Turkey", "Upper Iowa", "Root", "Zumbro", "Cannon",
  "Platte", "Loup", "Elkhorn", "Niobrara", "White",
  "Cheyenne", "Moreau", "Grand", "James", "Big Sioux",
  "Vermillion", "Big Sioux", "Floyd", "Boyer", "Nishnabotna",
  "Big Blue", "Little Blue", "Republican", "Smoky Hill", "Saline",
  "Solomon", "Arkansas", "Purgatoire", "Huerfano", "Apishapa",
  "Fountain", "South Platte", "Cache la Poudre", "Big Thompson", "St. Vrain",

  // South America
  "Amazon", "Orinoco", "Paraná", "Paraguay", "Uruguay",
  "São Francisco", "Araguaia", "Tocantins", "Madeira", "Tapajós",
  "Xingu", "Purús", "Juruá", "Negro", "Branco",
  "Japurá", "Içá", "Javari", "Juruena", "Arinos",
  "Teles Pires", "Verde", "Cuiabá", "São Lourenço", "Itiquira",
  "Guaporé", "Mamoré", "Beni", "Madre de Dios", "Heath",
  "Tambopata", "Inambari", "Urubamba", "Vilcanota", "Apurímac",
  "Mantaro", "Ene", "Tambo", "Ucayali", "Huallaga",
  "Marañón", "Pastaza", "Tigre", "Corrientes", "Napo",
  "Putumayo", "Vaupés", "Guainía", "Atabapo", "Ventuari",
  "Caura", "Caroní", "Paragua", "Aro", "Cuyuní",
  "Essequibo", "Mazaruni", "Potaro", "Rupununi", "Berbice",
  "Corantijn", "Commewine", "Suriname", "Saramacca", "Coppename",
  "Oyapock", "Approuague", "Maroni", "Sinnamary", "Mana",
  "Cauca", "Magdalena", "Sinú", "Atrato", "San Jorge",
  "Cesar", "Lebrija", "Sogamoso", "Carare", "La Miel",
  "Bogotá", "Saldaña", "Patía", "Mira", "Guayas",
  "Daule", "Babahoyo", "Pastaza", "Santiago", "Zamora",
  "Jubones", "Santa Rosa", "Tumbes", "Chira", "Piura",
  "Chancay", "Rímac", "Lurín", "Mala", "Cañete",
  "Pisco", "Ica", "Acari", "Ocoña", "Camaná",
  "Tambo", "Osmore", "Locumba", "Sama", "Caplina",
  "Loa", "Elqui", "Limarí", "Choapa", "Aconcagua",
  "Maipo", "Rapel", "Itata", "Biobío", "Imperial",
  "Toltén", "Valdivia", "Bueno", "Puelo", "Petrohué",
  "Palena", "Cisnes", "Aysén", "Baker", "Pascua",
  "Serrano", "Gallegos", "Coig", "Chico", "Santa Cruz",
  "Deseado", "Chubut", "Negro", "Colorado", "Salado",
  "Diamante", "Atuel", "Tunuyán", "Mendoza", "Bermejo",
  "Pilcomayo", "Juramento", "Dulce", "Hondo", "Primero",
  "Segundo", "Tercero", "Cuarto", "Quinto", "Conlara",
  "Jacuí", "Taquari", "Pelotas", "Canoas", "Pelotas",
  "Ijuí", "Piratini", "Jaguarão", "Quaraí", "Uruguay",
  "Ibicuí", "Quaraí", "Pelotas", "Corrientes", "Miriñay",

  // Australia and Oceania
  "Murray", "Darling", "Murrumbidgee", "Lachlan", "Macquarie",
  "Bogan", "Castlereagh", "Namoi", "Gwydir", "McIntyre",
  "Condamine", "Balonne", "Warrego", "Paroo", "Bulloo",
  "Cooper", "Thomson", "Barcoo", "Georgina", "Diamantina",
  "Flinders", "Leichhardt", "Gregory", "Gilbert", "Mitchell",
  "Burdekin", "Fitzroy", "Dawson", "Mackenzie", "Isaac",
  "Pioneer", "Bowen", "Burnett", "Mary", "Brisbane",
  "Logan", "Tweed", "Richmond", "Clarence", "Manning",
  "Hunter", "Hawkesbury", "Shoalhaven", "Snowy", "Mitta Mitta",
  "Goulburn", "Campaspe", "Loddon", "Avoca", "Wimmera",
  "Hopkins", "Moorabool", "Barwon", "Latrobe", "Thomson",
  "Mitchell", "Tambo", "Brodribb", "Snowy", "Towamba",
  "Murchison", "Gascoyne", "Ashburton", "Fortescue", "De Grey",
  "Ord", "Fitzroy", "Kimberley", "Drysdale", "Pentecost",
  "Victoria", "Daly", "Adelaide", "South Alligator", "East Alligator",
  "Roper", "Wilton", "McArthur", "Calvert", "Robinson",
  "Sepik", "Fly", "Purari", "Kikori", "Strickland",
  "Markham", "Ramu", "Mamberamo", "Digul", "Memberamo",
  "Waikato", "Clutha", "Waitaki", "Rangitikei", "Whanganui",

  // Siberia / Russian Far East (not already in top 100)
  "Ob", "Irtysh", "Tobol", "Ishim", "Tura",
  "Tavda", "Konda", "Severnaya Sosva", "Pelym", "Lozva",
  "Tom", "Chulym", "Ket", "Vasyugan", "Tara",
  "Om", "Irtish", "Inya", "Berd", "Berdan",
  "Yenisey", "Angara", "Kan", "Mana", "Iya",
  "Birusa", "Uda", "Ona", "Us", "Abakan",
  "Tuba", "Sysym", "Kazyr", "Amyl", "Kebezh",
  "Lower Tunguska", "Bakhta", "Sym", "Kets", "Elot",
  "Stony Tunguska", "Nizhnyaya Tunguska", "Ilimpea", "Tetere", "Chambé",
  "Lena", "Vitim", "Olyokma", "Aldan", "Amga",
  "Belaya", "Uchur", "Maya", "Timpton", "Notora",
  "Verkhoyansk", "Yana", "Adycha", "Dulgalakh", "Bytantay",
  "Indigirka", "Moma", "Selennyakh", "Nelemnoye", "Omolon",
  "Kolyma", "Anadyr", "Penzhina", "Gizhiga", "Taui",
  "Amur", "Shilka", "Onon", "Ingoda", "Nercha",
  "Argun", "Zeya", "Bureya", "Bikin", "Khor",
  "Ussuri", "Sungari", "Nora", "Selemdzha", "Tomm",
];
