// ~500 well-known river names (top 100 are the actual answers; the rest are hints/distractors)
export const longestRiversHints: string[] = [
  // Top 100 (the actual answers)
  "Nile", "Amazon", "Yangtze", "Mississippi", "Yenisey",
  "Yellow River", "Ob", "Río de la Plata", "Congo", "Amur",
  "Lena", "Mekong", "Mackenzie", "Niger", "Brahmaputra",
  "Murray", "Tocantins", "Volga", "Euphrates", "Madeira",
  "Purús", "Yukon", "Indus", "São Francisco", "Syr Darya",
  "Salween", "Saint Lawrence", "Rio Grande", "Lower Tunguska", "Colorado",
  "Danube", "Irrawaddy", "Zambezi", "Vilyuy", "Ganges",
  "Amu Darya", "Japurá", "Nelson", "Paraguay", "Kolyma",
  "Pilcomayo", "Upper Ob", "Ishim", "Orange", "Ural",
  "Juruá", "Arkansas", "Songhua", "Olenyok", "Dnieper",
  "Aldan", "Ubangi", "Negro", "Columbia", "Tapajós",
  "Pearl", "Red River", "Kasai", "Ohio", "Orinoco",
  "Tarim", "Xingu", "Jubba", "Brazos", "Northern Salado",
  "Içá", "Vitim", "Chenab", "Tigris", "Don",
  "Stony Tunguska", "Pechora", "Kama", "Limpopo", "Chulym",
  "Guaviare", "Marañón", "Indigirka", "Platte", "Senegal",
  "Khatanga", "Upper Jubba", "Uruguay", "Churchill", "Blue Nile",
  "Okavango", "Volta", "Beni", "Shilka", "Tobol",
  "Alazeya", "Kafue", "Yalong", "Magdalena", "Han",
  "Kura", "Oka", "Upper Murray", "Yana", "Pecos",

  // Additional well-known rivers (hints / distractors)
  // Europe
  "Rhine", "Elbe", "Seine", "Loire", "Rhône",
  "Thames", "Tagus", "Douro", "Ebro", "Garonne",
  "Vistula", "Oder", "Dniester", "Neva", "Western Dvina",
  "Daugava", "Neman", "Vltava", "Main", "Moselle",
  "Saale", "Meuse", "Scheldt", "Weser", "Ems",
  "Trent", "Severn", "Mersey", "Clyde", "Shannon",
  "Liffey", "Dee", "Exe", "Wye", "Avon",
  "Po", "Tiber", "Arno", "Adige", "Piave", "Guadalquivir", "Minho", "Tejo", "Júcar",
  "Axios", "Maritsa", "Vardar", "Sava", "Drava",
  "Mur", "Inn", "Salzach", "Traun", "Isar",
  "Tisza", "Prut", "Siret", "Olt", "Argeș",
  "Desna", "Pripyat", "Sozh", "Berezina", "Nemunas", "Gauja", "Emajõgi", "Pärnu", "Narva",
  "Kemijoki", "Oulujoki", "Kokemäenjoki", "Glomma", "Göta",
  "Dalälven", "Ångermanälven", "Umeälven", "Luleälven", "Torne",
  "Vuoksi", "Svir", "Volkhov", "Onega", "Mezen",
  "Seversky Donets", "Khopyor", "Voronezh", "Klyazma",

  // Asia
  "Ganga", "Yamuna", "Godavari", "Krishna", "Narmada",
  "Tapti", "Kaveri", "Mahanadi", "Chambal", "Betwa",
  "Sutlej", "Beas", "Ravi", "Jhelum", "Kabul",
  "Helmand", "Hari", "Oxus", "Zeravshan", "Panj",
  "Karun", "Karkeh", "Zayanderud", "Qezel Ozan", "Safid",
  "Aras", "Araks", "Çoruh", "Sakarya",
  "Kızılırmak", "Yeşilırmak", "Büyük Menderes", "Küçük Menderes", "Seyhan",
  "Orontes", "Jordan", "Litani", "Yarmouk", "Shatt al-Arab", "Diyala", "Greater Zab", "Lesser Zab",
  "Ghaghara", "Kosi", "Gandak", "Son", "Damodar", "Brahmani", "Baitarani", "Subarnarekha", "Hooghly",
  "Meghna", "Jamuna", "Padma", "Tista", "Buriganga", "Chindwin", "Sittang", "Rakhine",
  "Chao Phraya", "Mun", "Ping", "Wang", "Nan", "Nam Ou", "Nam Khan", "Se Kong", "Se San", "Ma River", "Da River", "Dong Nai", "Yalu", "Tumen", "Nakdong", "Geum",
  "Liao", "Mudanjiang", "Nen",
  "Huai", "Qiantang", "Min", "Jialing", "Wu",
  "Lancang", "Nujiang", "Dadu", "Minjiang",
  "Kaidu", "Ili", "Ertix", "Yarkand",
  "Selenga", "Onon", "Kherlen", "Orkhon", "Tuul",
  "Angara", "Barguzin", "Uda", "Biryusa", // Africa
  "Benue", "Lomami", "Kagera", "Ruvuma", "Rufiji",
  "Tana", "Shebelle", "Awash", "Omo",
  "Atbarah", "Sobat", "Bahr el Ghazal", "White Nile", "Chari", "Logone", "Sanaga", "Nyong", "Ogooué",
  "Kwilu", "Kwango", "Sankuru", "Lualaba", "Lukuga",
  "Luapula", "Kabompo", "Lungwebungu", "Cuando",
  "Caledon", "Vaal", "Fish", "Sundays", "Tugela",
  "Mthatha", "Umgeni", "Umfolozi", "Pungwe", "Save",
  "Buzi", "Lúrio", "Rovuma", "Shire",
  "Gambia", "Casamance", "Kolenté", "Moa", "Sewa",
  "Rokel", "Bandama", "Sassandra", "Komoe", "Mono",
  "Oueme", "Ankobra", "Pra", "Densu",
  "Ogun", "Osun", "Cross", "Gongola", "Sokoto",
  "Komadougou", "Yobe", "Hadejia", "Anambra",
  "Betsiboka", "Tsiribihina", "Mangoky", "Onilahý", "Sofia",
  "Mahavavy", "Manambolo", "Rianila", "Mangoro",
  "Draa", "Moulouya", "Oum Er-Rbia", "Sebou", "Bou Regreg",
  "Chelif", "Medjerda", "Nyanga", "Kouilou", "Fimi",

  // North America
  "Missouri", "Tennessee", "Cumberland", "Kansas", "Republican", "Cimarron", "Canadian", "Gila", "Salt", "Verde", "Hassayampa", "Agua Fria",
  "Sacramento", "San Joaquin", "American", "Feather", "Trinity",
  "Klamath", "Rogue", "Willamette", "Deschutes", "John Day", "Snake", "Clearwater", "Salmon", "Payette",
  "Boise", "Bruneau", "Owyhee", "Malheur", "Grande Ronde",
  "Yakima", "Wenatchee", "Okanogan", "Skagit", "Snohomish",
  "Cowlitz", "Lewis", "Nooksack", "Stillaguamish", "Skykomish",
  "Fraser", "Thompson", "Chilcotin", "Nechako", "Stuart",
  "Peace", "Athabasca", "Smoky", "Wapiti", "Hay", "Liard", "South Nahanni", "Peel", "Arctic Red",
  "Slave", "Buffalo", "Fond du Lac", "Saskatchewan", "North Saskatchewan", "South Saskatchewan", "Red Deer", "Bow",
  "Oldman", "St. Mary", "Milk", "Souris", "Assiniboine",
  "Winnipeg", "English", "Albany", "Moose", "Abitibi",
  "Ottawa", "Mattawa", "Rideau", "Gatineau", "Lievre",
  "Saint-Maurice", "Saguenay", "Manicouagan", "Aux Outardes", "Moisie",
  "Romaine", "Koksoak", "Eastmain", "Rupert", "Nottaway",
  "Harricana", "Broadback", "Pontiac", "Montreal",
  "Detroit", "Saint Clair", "Humber", "Niagara", "Welland", "Grand", "Sydenham", "Seal", "Hayes", "Winisk", "Attawapiskat", "Ekwan", "Missinaibi", "Groundhog", "Tanana", "Koyukuk", "Porcupine", "White",
  "Copper", "Susitna", "Matanuska", "Kenai", "Kasilof",
  "Kuskokwim", "Nushagak", "Kvichak", "Naknek", "Alagnak",
  "Hudson", "Delaware", "Susquehanna", "Potomac", "Shenandoah",
  "James", "Roanoke", "Tar", "Neuse", "Cape Fear",
  "Pee Dee", "Santee", "Cooper", "Edisto", "Savannah",
  "Ogeechee", "Altamaha", "Ocmulgee", "Oconee", "Flint",
  "Chattahoochee", "Tallapoosa", "Coosa", "Alabama", "Tombigbee",
  "Black Warrior", "Cahaba", "Clinch", "Powell",
  "Holston", "Nolichucky", "French Broad", "Pigeon", "Hiawassee",
  "Watauga", "New", "Kanawha", "Gauley", "Elk",
  "Greenbrier", "Cheat", "Monongahela", "Youghiogheny", "Allegheny",
  "Clarion", "West Branch Susquehanna", "Juniata", "Lehigh", "Schuylkill",
  "Brandywine", "Christina", "Raritan", "Passaic", "Hackensack",
  "Connecticut", "Housatonic", "Quinnipiac", "Merrimack", "Saco",
  "Kennebec", "Androscoggin", "Penobscot", "Saint Croix", "Saint John",
  "Miramichi", "Restigouche", "Matapédia", "Chaudière", "Etchemin",
  "Champlain", "Richelieu", "Yamaska", "Saint Francis", "Nicolet",
  "Des Moines", "Rock", "Illinois", "Kankakee", "Fox",
  "Vermilion", "Mackinaw", "Sangamon", "Kaskaskia", "Big Muddy",
  "Wisconsin", "Chippewa", "Black", "Flambeau", "Eau Claire",
  "Menominee", "Peshtigo", "Wolf", "Sheboygan",
  "Minnesota", "Blue Earth", "Cottonwood", "Yellow Medicine", "Redwood",
  "Crow Wing", "Pine", "Rum", "Namekagon",
  "Cedar", "Iowa", "Skunk", "Wapsipinicon", "Maquoketa",
  "Turkey", "Upper Iowa", "Root", "Zumbro", "Cannon", "Loup", "Elkhorn", "Niobrara", "Cheyenne", "Moreau", "Big Sioux",
  "Vermillion", "Floyd", "Boyer", "Nishnabotna",
  "Big Blue", "Little Blue", "Smoky Hill", "Saline",
  "Solomon", "Purgatoire", "Huerfano", "Apishapa",
  "Fountain", "South Platte", "Cache la Poudre", "Big Thompson", "St. Vrain",

  // South America
  "Paraná", "Araguaia", "Branco", "Javari", "Juruena", "Arinos",
  "Teles Pires", "Cuiabá", "São Lourenço", "Itiquira",
  "Guaporé", "Mamoré", "Madre de Dios", "Heath",
  "Tambopata", "Inambari", "Urubamba", "Vilcanota", "Apurímac",
  "Mantaro", "Ene", "Tambo", "Ucayali", "Huallaga", "Pastaza", "Tigre", "Corrientes", "Napo",
  "Putumayo", "Vaupés", "Guainía", "Atabapo", "Ventuari",
  "Caura", "Caroní", "Paragua", "Aro", "Cuyuní",
  "Essequibo", "Mazaruni", "Potaro", "Rupununi", "Berbice",
  "Corantijn", "Commewine", "Suriname", "Saramacca", "Coppename",
  "Oyapock", "Approuague", "Maroni", "Sinnamary", "Mana",
  "Cauca", "Sinú", "Atrato", "San Jorge",
  "Cesar", "Lebrija", "Sogamoso", "Carare", "La Miel",
  "Bogotá", "Saldaña", "Patía", "Mira", "Guayas",
  "Daule", "Babahoyo", "Santiago", "Zamora",
  "Jubones", "Santa Rosa", "Tumbes", "Chira", "Piura",
  "Chancay", "Rímac", "Lurín", "Mala", "Cañete",
  "Pisco", "Acari", "Ocoña", "Camaná", "Osmore", "Locumba", "Sama", "Caplina",
  "Loa", "Elqui", "Limarí", "Choapa", "Aconcagua",
  "Maipo", "Rapel", "Itata", "Biobío", "Imperial",
  "Toltén", "Valdivia", "Bueno", "Puelo", "Petrohué",
  "Palena", "Cisnes", "Aysén", "Baker", "Pascua",
  "Serrano", "Gallegos", "Coig", "Chico", "Santa Cruz",
  "Deseado", "Chubut", "Salado",
  "Diamante", "Atuel", "Tunuyán", "Mendoza", "Bermejo",
  "Segundo", "Tercero", "Cuarto", "Quinto", "Conlara",
  "Jacuí", "Taquari", "Pelotas", "Canoas", "Ijuí", "Piratini", "Jaguarão", "Quaraí", "Ibicuí", "Miriñay",

  // Australia and Oceania
  "Bogan", "Castlereagh", "Namoi", "Gwydir", "McIntyre",
  "Condamine", "Balonne", "Warrego", "Paroo", "Bulloo", "Thomson", "Barcoo", "Georgina", "Diamantina",
  "Flinders", "Leichhardt", "Gregory", "Gilbert", "Mitchell",
  "Burdekin", "Fitzroy", "Dawson", "Isaac",
  "Pioneer", "Bowen", "Burnett", "Mary", "Brisbane",
  "Logan", "Tweed", "Richmond", "Clarence", "Manning",
  "Hunter", "Hawkesbury", "Shoalhaven", "Snowy", "Mitta Mitta",
  "Goulburn", "Campaspe", "Loddon", "Avoca", "Wimmera",
  "Hopkins", "Moorabool", "Barwon", "Latrobe", "Brodribb", "Towamba",
  "Murchison", "Gascoyne", "Ashburton", "Fortescue", "De Grey",
  "Ord", "Kimberley", "Drysdale", "Pentecost",
  "Victoria", "Daly", "Adelaide", "South Alligator", "East Alligator",
  "Roper", "Wilton", "McArthur", "Calvert", "Robinson",
  "Sepik", "Fly", "Purari", "Kikori", "Strickland",
  "Markham", "Ramu", "Mamberamo", "Digul", "Memberamo",
  "Waikato", "Clutha", "Waitaki", "Rangitikei", "Whanganui",

  // Siberia / Russian Far East (not already in top 100)
  "Irtysh", "Tura",
  "Tavda", "Konda", "Severnaya Sosva", "Pelym", "Lozva",
  "Tom", "Ket", "Vasyugan", "Tara",
  "Om", "Irtish", "Inya", "Berd", "Berdan", "Kan", "Iya",
  "Birusa", "Ona", "Us", "Abakan",
  "Tuba", "Sysym", "Kazyr", "Amyl", "Kebezh", "Bakhta", "Sym", "Kets", "Elot",
  "Belaya", "Uchur", "Maya", "Timpton", "Notora",
  "Verkhoyansk", "Adycha", "Dulgalakh", "Bytantay", "Moma", "Selennyakh", "Nelemnoye", "Omolon", "Ingoda", "Nercha",
  "Argun", "Zeya", "Bureya", "Bikin", "Khor",
  "Ussuri", "Sungari", "Nora", "Selemdzha", "Tomm",
];
