export const longestRunningTvSeriesHints: string[] = [
  // Top 50 (the ranked items)
  'Unser Sandmännchen', 'Minuto de Dios', 'Krishi Darshan', 'General Hospital', 'Guiding Light',
  'Days of Our Lives', 'A Chat with Glendora', 'As the World Turns', 'Eat Bulaga!', 'The Young and the Restless',
  'Des chiffres et des lettres', 'Aktuelle Kamera', 'Access Hollywood', 'Coronation Street', 'One Life to Live',
  'All My Children', 'Barátok közt', 'Emmerdale', '100 Huntley Street', 'AM Plaza',
  'Sandmännchen', 'TV Slagalica', 'The Price Is Right', 'The Bold and the Beautiful', 'Search for Tomorrow',
  'Neighbours', 'Jeopardy!', 'Another World', 'Gute Zeiten, schlechte Zeiten', 'Arul Neeram',
  'Hometown Report', 'Home and Away', 'Munshi', 'Countdown', "Waratte Iitomo!",
  'Pobol y Cwm', 'Wheel of Fortune', 'Striscia la notizia', 'Shortland Street', 'Les Guignols',
  'Bom Dia & Companhia', 'Unter uns', 'The Edge of Night', 'Love of Life', 'Saber y ganar',
  'Familie', 'Tritiyo Matra', 'Goede tijden, slechte tijden', 'EastEnders', 'Play School',

  // Additional international soap operas and long-runners
  'Un posto al sole', 'Enjoy Yourself Tonight', 'Dom-2', 'Judge Judy', 'Malhação',
  'Larry King Live', 'Blokken', 'Hollyoaks', 'Rasoi Show', 'The View',
  'Thuis', '7de Laan', 'Lingo', 'Le Juste Prix', 'Isidingo',
  'Blue Peter', 'The Secret Storm', 'Bobino', 'Fair City', 'The Doctors',
  'Jaka to melodia?', "L'eredità", 'Yeh Rishta Kya Kehlata Hai', 'Ulice', 'The Merv Griffin Show',
  'Crossroads', 'Salatut elämät', 'Sesame Street', 'Egoli: Place of Gold', 'Plus belle la vie',
  'Verbotene Liebe', 'The Oprah Winfrey Show', 'Alles was zählt', 'Doctors', 'Taarak Mehta Ka Ooltah Chashmah',
  'Sturm der Liebe', 'Late Show with David Letterman', 'Generations', 'Klan', 'Slavi\'s Show',
  'Marienhof', 'Rote Rosen', 'The Daily Show', 'Binnelanders', 'The One Show',
  'Na Wspólnej', 'Goenkale', 'Pierwsza miłość', 'Jackanory', 'Tinsel',
  'Ryan\'s Hope', 'Lampsi', 'Scandal!', 'Muvhango', 'Family Feud',
  'Hotel Cæsar', 'Just for Laughs Gags', 'American Bandstand', 'Captain Kangaroo', 'Hollywood Squares',

  // US primetime and talk shows
  'The Simpsons', 'Law & Order: Special Victims Unit', 'Saturday Night Live', 'NCIS',
  'Grey\'s Anatomy', 'Survivor', 'The Amazing Race', 'Big Brother', 'The Bachelor',
  'America\'s Got Talent', 'Dancing with the Stars', 'American Idol', 'So You Think You Can Dance',
  'The Price Is Right (1972)', 'The Tonight Show', 'Late Night', 'Late Show', 'The Late Late Show',
  'Live with Kelly and Mark', 'Good Morning America', 'Today', 'Meet the Press', 'Face the Nation',
  '60 Minutes', '20/20', 'Dateline NBC', 'CBS Evening News', 'ABC World News Tonight',
  'Entertainment Tonight', 'Inside Edition', 'Extra', 'Access Hollywood Live', 'E! News',
  'WWE Raw', 'WWE SmackDown', 'Law & Order', 'Criminal Minds', 'CSI',
  'ER', 'House', 'NCIS: Los Angeles', 'Blue Bloods', 'Chicago Fire',
  'The Wonderful World of Disney', 'Gunsmoke', 'The Red Skelton Show',
  'Lassie', 'The Ed Sullivan Show', 'Hee Haw', 'The Lawrence Welk Show',
  'Soul Train', 'Cops', 'America\'s Most Wanted', 'Power Rangers',
  'America\'s Funniest Home Videos', 'The Simpsons', 'South Park', 'Family Guy',
  'SpongeBob SquarePants', 'The X-Files', 'Supernatural', 'Buffy the Vampire Slayer',
  'Star Trek: The Next Generation', 'M*A*S*H', 'Cheers', 'Friends', 'Seinfeld',
  'The Big Bang Theory', 'Modern Family', 'The Office', 'Parks and Recreation',
  'The Real Housewives of Orange County', 'The Real World', 'The Challenge',
  'Dr. Phil', 'Maury', 'The Jerry Springer Show', 'The Ellen DeGeneres Show',
  'Jimmy Kimmel Live!', 'The Daily Show with Trevor Noah', 'Real Time with Bill Maher',
  'Washington Week', 'Inside Edition', 'Judge Mathis', 'The People\'s Court',
  'Divorce Court', 'Concentration', 'What\'s My Line?',
  'Masterpiece', 'Nova', 'Frontline', 'American Experience', 'Austin City Limits',
  'Mister Rogers\' Neighborhood', 'Reading Rainbow', 'Arthur', 'Barney & Friends',
  'Dora the Explorer', 'It\'s Always Sunny in Philadelphia', 'Curb Your Enthusiasm',
  'Firing Line', 'The Phil Donahue Show',

  // International (non-US, non-anime)
  'Neighbours (AU)', 'Home and Away (AU)', 'Sale of the Century (AU)', 'Wheel of Fortune (AU)',
  'Shortland Street (NZ)', 'Fair City (IE)', 'Pobol y Cwm (UK/Wales)',
  'Gute Zeiten, schlechte Zeiten (DE)', 'Unter uns (DE)', 'Verbotene Liebe (DE)',
  'Alles was zählt (DE)', 'Sturm der Liebe (DE)', 'Marienhof (DE)', 'Rote Rosen (DE)',
  'Familie (BE)', 'Blokken (BE)', 'Thuis (BE)',
  'Goede tijden, slechte tijden (NL)', 'Lingo (NL)',
  'Plus belle la vie (FR)', 'Les Guignols (FR)', 'Des chiffres et des lettres (FR)',
  'Striscia la notizia (IT)', 'Un posto al sole (IT)',
  'Saber y ganar (ES)', 'Goenkale (ES)',
  'TV Slagalica (RS)', 'Lampsi (GR)',
  'Hotel Cæsar (NO)', 'Lykkehjulet (DK)',
  'Salatut elämät (FI)', 'Klan (PL)', 'Na Wspólnej (PL)', 'Pierwsza miłość (PL)',
  'Ulice (CZ)', 'Barátok közt (HU)', 'Jóban Rosszban (HU)',
  '7de Laan (ZA)', 'Generations (ZA)', 'Isidingo (ZA)', 'Binnelanders (ZA)',
  'Scandal! (ZA)', 'Muvhango (ZA)', 'Egoli: Place of Gold (ZA)',
  'Tinsel (NG)', 'Dom-2 (RU)', 'Susana Giménez (AR)',
  'Malhação (BR)', 'Bom Dia & Companhia (BR)',

  // Anime
  'Sazae-san', 'Nintama Rantarō', 'Ojarumaru', 'Oyako Club', 'Doraemon',
  'Soreike! Anpanman', 'Chibi Maruko-chan', 'Crayon Shin-chan', 'Case Closed',
  'One Piece', 'Naruto', 'Naruto: Shippuden', 'Dragon Ball Z', 'Dragon Ball Super',
  'Bleach', 'Fairy Tail', 'Pokémon', 'Hamtaro', 'Sgt. Frog', 'Boruto',
  'KochiKame: Tokyo Beat Cops', 'Atashin\'chi', 'Ikkyū-san', 'Ninja Hattori-kun',
  'Shima Shima Tora no Shimajirō', 'Hanakappa',
];
