export const mlbPlayersHints: string[] = [
  "Babe Ruth", "Barry Bonds", "Willie Mays", "Ty Cobb", "Henry Aaron",
  "Tris Speaker", "Honus Wagner", "Stan Musial", "Rogers Hornsby", "Eddie Collins",
  "Ted Williams", "Alex Rodriguez", "Lou Gehrig", "Rickey Henderson", "Mickey Mantle",
  "Mel Ott", "Nap Lajoie", "Frank Robinson", "Mike Schmidt", "Joe Morgan",
  "Albert Pujols", "Carl Yastrzemski", "Eddie Mathews", "Cal Ripken Jr.", "Roberto Clemente",
  "Cap Anson", "Adrian Beltre", "Jimmie Foxx", "Al Kaline", "Wade Boggs",
  "George Brett", "Chipper Jones", "Mike Trout", "Charlie Gehringer", "George Davis",
  "Roger Connor", "Ken Griffey Jr.", "Rod Carew", "Jeff Bagwell", "Pete Rose",
  "Joe DiMaggio", "Dan Brouthers", "Brooks Robinson", "Arky Vaughan", "Robin Yount",
  "Luke Appling", "Ozzie Smith", "Bobby Wallace", "Sam Crawford", "Paul Molitor",
  "Johnny Bench", "Lou Whitaker", "Bill Dahlen", "Paul Waner", "Reggie Jackson",
  "Frank Thomas", "Jim Thome", "Larry Walker", "Harry Heilmann", "Rafael Palmeiro",
  "Frankie Frisch", "Derek Jeter", "Bobby Grich", "Alan Trammell", "Johnny Mize",
  "Mookie Betts", "Roberto Alomar", "Billy Hamilton", "Tim Raines", "Willie McCovey",
  "Ernie Banks", "Tony Gwynn", "Ivan Rodriguez", "Craig Biggio", "Willie Stargell",
  "Edgar Martinez", "Joe Torre", "Ron Santo", "Mike Piazza", "Ichiro Suzuki",
  "Vladimir Guerrero", "Dave Winfield", "Gary Sheffield", "Carlos Beltran", "Manny Ramirez",
  "Andre Dawson", "Jim Rice", "David Ortiz", "Miguel Cabrera", "Freddie Freeman",
  "Jose Ramirez", "Bryce Harper", "Juan Soto", "Ronald Acuna Jr.", "Corey Seager",
  "Trea Turner", "Matt Olson", "Shohei Ohtani", "Yordan Alvarez", "Julio Rodriguez",
  "Walter Johnson", "Cy Young", "Roger Clemens", "Grover Alexander", "Kid Nichols",
  "Tom Seaver", "Christy Mathewson", "Lefty Grove", "Greg Maddux", "Randy Johnson",
  "Warren Spahn", "Phil Niekro", "Bert Blyleven", "Eddie Plank", "Steve Carlton",
  "Gaylord Perry", "Bob Gibson", "Tim Keefe", "Robin Roberts", "Fergie Jenkins",
  "Pedro Martinez", "John Clarkson", "Mike Mussina", "Justin Verlander", "Nolan Ryan",
  "Clayton Kershaw", "Tom Glavine", "Curt Schilling", "Zack Greinke", "Max Scherzer",
  "Old Hoss Radbourn", "Pud Galvin", "Ted Lyons", "Red Ruffing", "Juan Marichal",
  "Don Drysdale", "Carl Hubbell", "Whitey Ford", "Bob Feller", "Jim Palmer",
  "Don Sutton", "Tommy John", "Early Wynn", "Sandy Koufax", "John Smoltz",
  "Kevin Brown", "Jack Morris", "David Cone", "Andy Pettitte", "CC Sabathia",
  "Orel Hershiser", "Roy Halladay", "David Price", "Zack Wheeler", "Gerrit Cole",
  "Jacob deGrom", "Chris Sale", "Max Fried", "Corbin Burnes", "Spencer Strider",
  "Luis Castillo", "Dylan Cease", "Logan Webb", "Freddy Peralta", "Joe Musgrove",
  "Shane Bieber", "Tyler Glasnow", "Blake Snell", "Yu Darvish", "Masahiro Tanaka",
  "Cole Hamels", "Madison Bumgarner", "Felix Hernandez", "Corey Kluber", "Dallas Keuchel",
  "Marcus Stroman", "Sonny Gray", "Aaron Nola", "Jose Quintana", "Charlie Morton",
  "Lance Lynn", "Taijuan Walker", "Patrick Corbin", "Jameson Taillon", "Jack Flaherty",
  "Jose Berrios", "Sandy Alcantara", "Framber Valdez", "Nestor Cortes", "Ranger Suarez",
  "Chris Bassitt", "Nathan Eovaldi", "Jon Lester", "Jake Arrieta", "Noah Syndergaard",
  "Brandon Woodruff", "Pablo Lopez", "Adam Wainwright", "Mike Scott", "Sammy Sosa",
  "Mark McGwire", "Harmon Killebrew", "Eddie Murray", "Fred McGriff", "Carlos Delgado",
  "Jose Canseco", "Adam Dunn", "Nelson Cruz", "Andruw Jones", "Juan Gonzalez",
  "Giancarlo Stanton", "Albert Belle", "Ryan Howard", "Mike Napoli", "Jay Buhner",
  "Carlos Lee", "Aramis Ramirez", "Jason Giambi", "Manny Machado", "Nolan Arenado",
  "Edwin Encarnacion", "Prince Fielder", "David Wright", "Alfonso Soriano", "Curtis Granderson",
  "Justin Upton", "Evan Longoria", "Paul Konerko", "Billy Williams", "Dwight Evans",
  "Jim Edmonds", "Lance Berkman", "Gary Carter", "Graig Nettles", "Dale Murphy",
  "Lee May", "Norm Cash", "Rocky Colavito", "Orlando Cepeda", "Tony Perez",
  "George Foster", "Boog Powell", "Gil Hodges", "Jack Clark", "Joe Adcock",
  "Hank Greenberg", "Ralph Kiner", "Duke Snider", "Ted Kluszewski", "Johnny Damon",
  "Torii Hunter", "Jeff Kent", "Moises Alou", "Bobby Abreu", "Chili Davis",
  "Luis Gonzalez", "Todd Helton", "Scott Rolen", "Andres Galarraga", "George Bell",
  "Matt Williams", "Kevin Mitchell", "Vinny Castilla", "Robin Ventura", "Troy Glaus",
  "Richie Sexson", "Mo Vaughn", "Cecil Fielder", "Khris Davis", "Pete Alonso",
  "Kyle Schwarber", "Aaron Judge", "Salvador Perez", "Mickey Lolich", "Frank Tanana",
  "David Wells", "Tim Lincecum", "Vida Blue", "Dennis Eckersley", "Mark Langston",
  "Jack McDowell", "Kevin Appier", "Jamie Moyer", "Kevin Millwood", "Mark Buehrle",
  "Javier Vazquez", "Livan Hernandez", "Bartolo Colon", "A.J. Burnett", "John Lackey",
  "Jake Peavy", "Tim Hudson", "Hideo Nomo", "Johan Santana", "Roy Oswalt",
  "Josh Beckett", "Rick Reuschel", "Dwight Gooden", "Bret Saberhagen", "David Stewart",
  "Frank Viola", "Kevin Gross", "Danny Darwin", "Jim Clancy", "Bob Welch",
  "Fernando Valenzuela", "Tom Candiotti", "Chuck Finley", "Kenny Rogers", "Andy Benes",
  "Freddy Garcia", "Esteban Loaiza", "Mike Hampton", "Darryl Kile", "Rick Sutcliffe",
  "Doug Drabek", "John Tudor", "Mike Moore", "Dennis Martinez", "Jose Rijo",
  "Sam McDowell", "Hal Newhouser", "Bob Lemon", "Dizzy Dean", "Dazzy Vance",
  "Rube Waddell", "Mordecai Brown", "Addie Joss", "Joe McGinnity", "Vic Willis",
  "Jack Chesbro", "Eddie Cicotte", "Red Faber", "Herb Pennock", "Waite Hoyt",
  "Dizzy Trout", "Tex Hughson", "Virgil Trucks", "Billy Pierce", "Jim Bunning",
  "Catfish Hunter", "Luis Tiant", "Wilbur Wood", "Fernando Tatis Jr.", "Wander Franco",
  "Bobby Witt Jr.", "Gunnar Henderson", "Elly De La Cruz", "Corbin Carroll", "CJ Abrams",
  "Jackson Merrill", "Jackson Chourio", "Junior Caminero", "Marcell Ozuna", "Adolis Garcia",
  "Rafael Devers", "Marcus Semien", "Bo Bichette", "Willy Adames", "Vladimir Guerrero Jr.",
  "Austin Riley", "Dansby Swanson", "Alex Bregman", "Xander Bogaerts", "Francisco Lindor",
  "Tommy Edman", "Jose Altuve", "Ozzie Albies", "Cody Bellinger", "J.D. Martinez",
  "Christian Yelich", "Rhys Hoskins", "Max Muncy", "Javier Baez", "Jorge Soler",
  "Anthony Rizzo", "Josh Donaldson", "Kris Bryant", "Paul Goldschmidt", "Andrew McCutchen",
  "Starling Marte", "Brandon Crawford", "Buster Posey", "Joey Votto", "Anthony Rendon",
  "Trey Mancini", "Michael Brantley", "Yoan Moncada", "Tim Anderson", "Eloy Jimenez",
  "Luis Robert", "Byron Buxton", "Carlos Correa", "George Springer", "Teoscar Hernandez",
  "Ketel Marte", "Cedric Mullins", "Jake Cronenworth", "Ha-Seong Kim", "Lars Nootbaar",
  "Willson Contreras", "J.T. Realmuto", "Sean Murphy", "Adley Rutschman", "William Contreras",
  "Cal Raleigh", "Spencer Torkelson", "Riley Greene", "Kerry Carpenter", "Matt Chapman",
  "Nico Hoerner", "Seiya Suzuki", "Ian Happ", "Michael Harris II", "Spencer Schwellenbach",
  "Reynaldo Lopez", "Seth Lugo", "Tanner Bibee", "Emmanuel Clase", "Ryan Helsley",
  "Josh Hader", "Edwin Diaz", "Kenley Jansen", "Craig Kimbrel", "Aroldis Chapman",
  "Devin Williams", "Robert Suarez", "Alexis Diaz", "Mason Miller", "Paul Skenes",
  "Tarik Skubal", "Yoshinobu Yamamoto", "Hunter Brown", "Ronel Blanco", "Mariano Rivera",
  "Trevor Hoffman", "Billy Wagner", "Lee Smith", "Rollie Fingers", "Goose Gossage",
  "Bruce Sutter", "John Franco", "Tom Henke", "Jeff Reardon", "Dan Quisenberry",
  "Sparky Lyle", "Hoyt Wilhelm", "Phil Regan", "Roberto Hernandez", "Bobby Doerr",
  "Nellie Fox", "Joe Cronin", "Earle Combs", "Bill Terry", "Hack Wilson",
  "Chuck Klein", "Joe Medwick", "Enos Slaughter", "Red Schoendienst", "Pee Wee Reese",
  "Phil Rizzuto", "Roy Campanella", "Don Newcombe", "Richie Ashburn", "Tony Oliva",
  "Kirby Puckett", "Kent Hrbek", "Ryne Sandberg", "Mark Grace", "Kerry Wood",
  "Ferguson Jenkins", "Carlton Fisk", "Yogi Berra", "Bill Dickey", "Mickey Cochrane",
  "Gabby Hartnett", "Dave Parker", "Bill Mazeroski", "Dick Groat", "Bob Friend",
  "Dave Concepcion", "Eric Davis", "Ken Griffey Sr.", "Barry Larkin", "Joe Mauer",
  "Ozzie Guillen", "Omar Vizquel", "Kenny Lofton", "Larry Doby", "Lou Brock",
  "Bob Forsch", "Whitey Herzog", "Tommy Herr", "Vince Coleman", "Willie McGee",
  "Joaquin Andujar", "Chris Carpenter", "Yadier Molina", "Matt Carpenter", "Kolten Wong",
  "Harrison Bader", "Nolan Gorman", "Tyler O'Neill", "Jordan Walker", "George Sisler",
  "Eddie Gaedel", "Satchel Paige", "Josh Gibson", "Cool Papa Bell", "Jackie Robinson",
  "Tommy Lasorda", "Steve Garvey", "Ron Cey", "Bill Russell", "Davey Lopes",
  "Kirk Gibson", "Nomar Garciaparra", "Johnny Pesky", "Dom DiMaggio", "Fred Lynn",
  "Thurman Munson", "Don Mattingly", "Bernie Williams", "Jorge Posada", "Mark Teixeira",
  "Robinson Cano", "Dave McNally", "Mike Cuellar", "Tino Martinez", "Alvin Davis",
  "Harold Reynolds", "Charlie Blackmon", "Ubaldo Jimenez", "Troy Tulowitzki", "Adrian Gonzalez",
  "Benito Santiago", "Stephen Strasburg", "Ryan Zimmerman", "David Justice", "Raul Mondesi",
  "Shawn Green", "J.D. Drew", "Ray Lankford", "Brian Jordan", "Charles Nagy",
  "Travis Hafner", "Grady Sizemore", "Asdrubal Cabrera", "Shin-Soo Choo", "Michael Young",
  "Pudge Rodriguez", "Ruben Sierra", "Rusty Greer", "Josh Hamilton", "Ian Kinsler",
  "Elvis Andrus", "Magglio Ordonez", "Jermaine Dye", "Jose Abreu", "Andrew Vaughn",
  "Harold Baines", "Minnie Minoso", "Luis Aparicio", "Shoeless Joe Jackson", "Nicholas Castellanos",
  "Casey Mize", "Ryan Mountcastle", "Jackson Holliday", "Grayson Rodriguez", "Al Rosen",
  "Herb Score", "Joe Sewell", "Stan Coveleski", "Darryl Strawberry", "Keith Hernandez",
  "Jose Reyes", "Matt Harvey", "Bo Jackson", "Frank White", "Mike Sweeney",
  "Willie Wilson", "Hal McRae", "Amos Otis", "Paul Splittorff", "Dennis Leonard",
  "Mark Gubicza", "Jeff Montgomery", "Cecil Cooper", "Ryan Braun", "Francisco Liriano",
  "Joe Ryan", "Royce Lewis", "Luis Severino", "Gleyber Torres", "Anthony Volpe",
  "Jazz Chisholm Jr.", "Carlos Rodon", "Robbie Ray", "Hyun-Jin Ryu", "Kevin Gausman",
  "Yusei Kikuchi", "Alek Manoah", "Ross Stripling", "Mitch White", "Jordan Romano",
  "Roberto Osuna", "Jose Bautista", "Joe Carter", "John Olerud", "Dave Stieb",
  "Ricky Romero", "Brandon Morrow", "R.A. Dickey", "J.A. Happ", "Jared Walsh",
  "Jo Adell", "Logan O'Hoppe", "Reid Detmers", "Patrick Sandoval", "Tim Salmon",
  "Garrett Anderson", "Darin Erstad", "Don Baylor", "Kendrys Morales", "Will Smith",
  "Walker Buehler", "Julio Urias", "Dustin May", "Tony Gonsolin", "Bobby Miller",
  "Maury Wills", "Brandon Belt", "Matt Cain", "Jung Hoo Lee", "Nick Castellanos",
  "Cristopher Sanchez", "Brandon Phillips", "Eugenio Suarez", "Jonathan India", "Hunter Greene",
  "Matt McLain", "Randy Arozarena", "Shane McClanahan", "Drew Rasmussen", "Pie Traynor",
  "Ke'Bryan Hayes", "Mitch Keller", "Oneil Cruz", "Christopher Morel", "Shota Imanaga",
  "Justin Steele", "Josh Naylor", "Steven Kwan", "Cristian Javier", "Alex Verdugo",
  "Triston Casas", "Masataka Yoshida", "Tanner Houck", "Brayan Bello", "Josh Jung",
  "Nathaniel Lowe", "Jon Gray", "Leody Taveras", "Miles Mikolas", "Masyn Winn",
  "MJ Melendez", "Cole Ragans", "Brady Singer", "Mitch Haniger", "Garrett Crochet",
  "Wilber Flores", "Michael King", "Zac Gallen", "Lourdes Gurriel Jr.", "Jake McCarthy",
  "David Bednar", "Felix Bautista", "Ryan Pressly", "Liam Hendriks", "Raisel Iglesias",
  "Camilo Doval", "Clay Holmes", "Carlos Estevez", "Pete Fairbanks", "Paul Sewald",
  "Andres Munoz", "Taylor Rogers", "Jhoan Duran", "Evan Phillips", "Daniel Bard",
  "Jim McCormick", "Fred Clarke", "Charlie Hough", "Dick Allen", "Bobby Bonds",
  "Jerry Koosman", "Jim Kaat", "Greg Luzinski",
];
