// ~500 most-viewed YouTube music videos (kworb.net / Wikipedia)
export const mostViewedYoutubeMusicVideosHints: string[] = [
  // Top 100 — the actual ranked answers
  "Despacito - Luis Fonsi",
  "See You Again - Wiz Khalifa",
  "Shape of You - Ed Sheeran",
  "Gangnam Style - PSY",
  "Axel F - Crazy Frog",
  "Uptown Funk - Mark Ronson",
  "Dame Tu Cosita - El Chombo",
  "Shree Hanuman Chalisa - Gulshan Kumar",
  "Waka Waka - Shakira",
  "Counting Stars - OneRepublic",
  "Sugar - Maroon 5",
  "Roar - Katy Perry",
  "Dark Horse - Katy Perry",
  "Perfect - Ed Sheeran",
  "Sorry - Justin Bieber",
  "Let Her Go - Passenger",
  "Girls Like You - Maroon 5",
  "Thinking Out Loud - Ed Sheeran",
  "Faded - Alan Walker",
  "Lean On - Major Lazer & DJ Snake",
  "Bailando - Enrique Iglesias",
  "Blank Space - Taylor Swift",
  "Shake It Off - Taylor Swift",
  "Let It Go - Idina Menzel",
  "Mi Gente - J Balvin",
  "Baby - Justin Bieber",
  "We Don't Talk Anymore - Charlie Puth",
  "Closer - The Chainsmokers",
  "New Rules - Dua Lipa",
  "Hello - Adele",
  "Stressed Out - twenty one pilots",
  "The Lazy Song - Bruno Mars",
  "Rockabye - Clean Bandit",
  "Chantaje - Shakira",
  "Con Calma - Daddy Yankee & Snow",
  "Calma Remix - Pedro Capó & Farruko",
  "Love The Way You Lie - Eminem",
  "Work from Home - Fifth Harmony",
  "Believer - Imagine Dragons",
  "Sunflower - Post Malone & Swae Lee",
  "This Is What You Came For - Calvin Harris & Rihanna",
  "Chandelier - Sia",
  "Rolling in the Deep - Adele",
  "Criminal - Natti Natasha & Ozuna",
  "A Thousand Years - Christina Perri",
  "Taki Taki - DJ Snake",
  "On The Floor - Jennifer Lopez & Pitbull",
  "Starboy - The Weeknd",
  "All About That Bass - Meghan Trainor",
  "Alone - Marshmello",
  "Treat You Better - Shawn Mendes",
  "Numb - Linkin Park",
  "All of Me - John Legend",
  "Rude - MAGIC!",
  "Mayores - Becky G & Bad Bunny",
  "In Da Club - 50 Cent",
  "Somebody That I Used To Know - Gotye",
  "No Me Conoce Remix - Jhay Cortez & J. Balvin & Bad Bunny",
  "Te Bote Remix - Casper & Nio García & Darell",
  "Diamonds - Rihanna",
  "Party Rock Anthem - LMFAO",
  "Wake Me Up - Avicii",
  "That's What I Like - Bruno Mars",
  "Something Just Like This - The Chainsmokers & Coldplay",
  "Échame La Culpa - Luis Fonsi & Demi Lovato",
  "Someone Like You - Adele",
  "APT. - ROSÉ & Bruno Mars",
  "Worth It - Fifth Harmony",
  "November Rain - Guns N' Roses",
  "Side To Side - Ariana Grande",
  "Lovely - Billie Eilish & Khalid",
  "Love Me Like You Do - Ellie Goulding",
  "Nunca Es Suficiente - Los Ángeles Azules",
  "Thunder - Imagine Dragons",
  "Take On Me - a-ha",
  "DDU-DU DDU-DU - BLACKPINK",
  "Dusk Till Dawn - ZAYN",
  "Without Me - Eminem",
  "Propuesta Indecente - Romeo Santos",
  "Heathens - twenty one pilots",
  "X (EQUIS) - Nicky Jam & J. Balvin",
  "China - Anuel AA & Daddy Yankee & Karol G",
  "Sin Pijama - Becky G & Natti Natasha",
  "What Do You Mean? - Justin Bieber",
  "Don't Let Me Down - The Chainsmokers",
  "The Hills - The Weeknd",
  "Dance Monkey - Tones and I",
  "Con Altura - Rosalía & J Balvin",
  "Déjala Que Vuelva - Piso 21",
  "Life Is Good - Future & Drake",
  "Hymn For The Weekend - Coldplay",
  "In The End - Linkin Park",
  "Ay Vamos - J. Balvin",
  "Human - Rag'n'Bone Man",
  "Kill This Love - BLACKPINK",
  "Smells Like Teen Spirit - Nirvana",
  "Just The Way You Are - Bruno Mars",
  "What's Up - 4 Non Blondes",
  "Titanium - David Guetta & Sia",
  // 101–200
  "Hotline Bling - Drake",
  "Bang Bang - Jessie J & Ariana Grande & Nicki Minaj",
  "Save Your Tears - The Weeknd",
  "Dura - Daddy Yankee",
  "Dynamite - BTS",
  "Billie Jean - Michael Jackson",
  "Una Lady Como Tú - Manuel Turizo",
  "Not Afraid - Eminem",
  "El Farsante Remix - Ozuna & Romeo Santos",
  "Havana - Camila Cabello",
  "Me Rehúso - Danny Ocean",
  "Paradise - Coldplay",
  "Bohemian Rhapsody - Queen",
  "Bad Romance - Lady Gaga",
  "Just Give Me A Reason - P!nk",
  "Watch Me (Whip/Nae Nae) - Silentó",
  "Gangsta's Paradise - Coolio",
  "Vente Pa' Ca - Ricky Martin & Maluma",
  "Felices los 4 - Maluma",
  "Cheap Thrills - Sia & Sean Paul",
  "Let Me Love You - DJ Snake & Justin Bieber",
  "Thrift Shop - Macklemore & Ryan Lewis",
  "Señorita - Shawn Mendes & Camila Cabello",
  "CAN'T STOP THE FEELING! - Justin Timberlake",
  "Robarte un Beso - Carlos Vives & Sebastián Yatra",
  "Andas En Mi Cabeza - Chino y Nacho & Daddy Yankee",
  "Bum Bum Tam Tam - MC Fioti",
  "Reggaetón Lento - CNCO",
  "Sweet Child O' Mine - Guns N' Roses",
  "Boy With Luv - BTS",
  "Unforgettable - French Montana & Swae Lee",
  "Se Preparó - Ozuna",
  "I'm The One - DJ Khaled & Justin Bieber",
  "I Will Always Love You - Whitney Houston",
  "BOOMBAYAH - BLACKPINK",
  "Swalla - Jason Derulo",
  "Do I Wanna Know? - Arctic Monkeys",
  "Animals - Martin Garrix",
  "Say You Won't Let Go - James Arthur",
  "Shallow - Lady Gaga & Bradley Cooper",
  "Call Me Maybe - Carly Rae Jepsen",
  "Zombie - The Cranberries",
  "Love Yourself - Justin Bieber",
  "Dilemma - Nelly & Kelly Rowland",
  "La Bicicleta - Carlos Vives & Shakira",
  "Halo - Beyoncé",
  "24K Magic - Bruno Mars",
  "I Took A Pill In Ibiza - Mike Posner",
  "Hips Don't Lie - Shakira",
  "Attention - Charlie Puth",
  "Shaky Shaky - Daddy Yankee",
  "Summer - Calvin Harris",
  "Taste - Tyga & Offset",
  "Never Gonna Give You Up - Rick Astley",
  "Corazón - Maluma",
  "7 Years - Lukas Graham",
  "You Belong With Me - Taylor Swift",
  "La Gozadera - Gente de Zona & Marc Anthony",
  "DÁKITI - Bad Bunny & Jhay Cortez",
  "Gentleman - PSY",
  "I Like It - Cardi B & Bad Bunny & J Balvin",
  "I Want It That Way - Backstreet Boys",
  "Adventure Of A Lifetime - Coldplay",
  "Hey Mama - David Guetta",
  "Congratulations - Post Malone",
  "Poker Face - Lady Gaga",
  "Thunderstruck - AC/DC",
  "Bring Me To Life - Evanescence",
  "Stitches - Shawn Mendes",
  "How Deep Is Your Love - Calvin Harris & Disciples",
  "Barbie Girl - Aqua",
  "What Makes You Beautiful - One Direction",
  "Still D.R.E. - Dr. Dre & Snoop Dogg",
  "Danza Kuduro - Don Omar & Lucenzo",
  "God's Plan - Drake",
  "Secreto - Anuel AA & Karol G",
  "Mía - Bad Bunny & Drake",
  "Bad Blood - Taylor Swift",
  "Girls Just Want To Have Fun - Cyndi Lauper",
  "Adiós Amor - Christian Nodal",
  "Burn - Ellie Goulding",
  "DNA - BTS",
  "Ride - twenty one pilots",
  "Every Breath You Take - The Police",
  "Die With A Smile - Lady Gaga & Bruno Mars",
  "BEBE - 6ix9ine & Anuel AA",
  "Tusa - Karol G & Nicki Minaj",
  "Nothing Else Matters - Metallica",
  "SUBEME LA RADIO - Enrique Iglesias",
  "Smack That - Akon & Eminem",
  "It's My Life - Bon Jovi",
  "Timber - Pitbull & Ke$ha",
  "Last Friday Night - Katy Perry",
  "7 rings - Ariana Grande",
  "Too Good At Goodbyes - Sam Smith",
  "Somewhere over the Rainbow - Israel Kamakawiwoʻole",
  "Look What You Made Me Do - Taylor Swift",
  "MIC Drop Remix - BTS",
  "Firework - Katy Perry",
  "Radioactive - Imagine Dragons",
  "Rap God - Eminem",
  "Loyal - Chris Brown",
  // 201–300
  "Chop Suey! - System Of A Down",
  "Careless Whisper - George Michael",
  "When I Was Your Man - Bruno Mars",
  "Sign of the Times - Harry Styles",
  "Happy - Pharrell Williams",
  "Beautiful Girls - Sean Kingston",
  "El Perdedor - Enrique Iglesias",
  "AS IF IT'S YOUR LAST - BLACKPINK",
  "El Perdón - Nicky Jam & Enrique Iglesias",
  "El Amante - Nicky Jam",
  "Like a Stone - Audioslave",
  "Photograph - Ed Sheeran",
  "Work - Rihanna & Drake",
  "TQG - Karol G & Shakira",
  "Alone - Alan Walker",
  "Ahora Dice - Chris Jedi & J. Balvin & Ozuna",
  "How Far I'll Go - Auli'i Cravalho",
  "Otra Vez - Zion & Lennox & J Balvin",
  "Limbo - Daddy Yankee",
  "Old Town Road - Lil Nas X & Billy Ray Cyrus",
  "Mockingbird - Eminem",
  "Problem - Ariana Grande",
  "BICHOTA - Karol G",
  "No Lie - Sean Paul & Dua Lipa",
  "Symphony - Clean Bandit & Zara Larsson",
  "Rain Over Me - Pitbull & Marc Anthony",
  "Cheerleader - OMI",
  "Creep - Radiohead",
  "Mirrors - Justin Timberlake",
  "Livin' On A Prayer - Bon Jovi",
  "Back To Black - Amy Winehouse",
  "There's Nothing Holdin' Me Back - Shawn Mendes",
  "Losing My Religion - R.E.M.",
  "I Feel It Coming - The Weeknd & Daft Punk",
  "Bon Appétit - Katy Perry & Migos",
  "The Final Countdown - Europe",
  "Dernière Danse - Indila",
  "Elastic Heart - Sia",
  "La la la - Naughty Boy & Sam Smith",
  "MOONLIGHT - XXXTENTACION",
  "IDOL - BTS",
  "SICKO MODE - Travis Scott & Drake",
  "FAKE LOVE - BTS",
  "Happier - Marshmello & Bastille",
  "La Mordidita - Ricky Martin",
  "Bad and Boujee - Migos",
  "How You Like That - BLACKPINK",
  "Californication - Red Hot Chili Peppers",
  "La La La (Brazil 2014) - Shakira",
  "Safari - J Balvin & Pharrell Williams",
  "Never Say Never - Justin Bieber",
  "You Are The Reason - Calum Scott",
  "Calm Down - Rema & Selena Gomez",
  "Provenza - Karol G",
  "Hot N Cold - Katy Perry",
  "Bad Guy - Billie Eilish",
  "The Scientist - Coldplay",
  "La Bebe Remix - Yng Lvcas & Peso Pluma",
  "Borro Cassette - Maluma",
  "Give Me Everything - Pitbull & Ne-Yo",
  "Waiting For Love - Avicii",
  "Where Are Ü Now - Skrillex & Diplo & Justin Bieber",
  "Lonely - Akon",
  "Wild Thoughts - DJ Khaled & Rihanna",
  "Eres Mía - Romeo Santos",
  "Total Eclipse of the Heart - Bonnie Tyler",
  "We Are Young - fun. & Janelle Monáe",
  "rockstar - Post Malone & 21 Savage",
  "SAD! - XXXTENTACION",
  "Adicto - Tainy & Anuel AA & Ozuna",
  "CALLAÍTA - Bad Bunny",
  "Where Is The Love? - The Black Eyed Peas",
  "6 AM - J Balvin & Farruko",
  "Yellow - Coldplay",
  "Vivir Mi Vida - Marc Anthony",
  "no tears left to cry - Ariana Grande",
  "Culpables - Karol G & Anuel AA",
  "Michael Jackson - They Don't Care About Us",
  "FRIENDS - Marshmello & Anne-Marie",
  "The Spectre - Alan Walker",
  "PILLOWTALK - ZAYN",
  "Beat It - Michael Jackson",
  "Stay With Me - Sam Smith",
  "Bitter Sweet Symphony - The Verve",
  "Habits (Stay High) - Tove Lo",
  "Say It Right - Nelly Furtado",
  "Someone You Loved - Lewis Capaldi",
  "Demons - Imagine Dragons",
  "Play Hard - David Guetta & Ne-Yo & Akon",
  "Turn Down for What - DJ Snake & Lil Jon",
  "Grenade - Bruno Mars",
  "Meant to Be - Bebe Rexha & Florida Georgia Line",
  "Better - Khalid",
  // 301–400+
  "Africa - Toto",
  "Blinding Lights - The Weeknd",
  "Anti-Hero - Taylor Swift",
  "As It Was - Harry Styles",
  "Cruel Summer - Taylor Swift",
  "Levitating - Dua Lipa",
  "Watermelon Sugar - Harry Styles",
  "drivers license - Olivia Rodrigo",
  "good 4 u - Olivia Rodrigo",
  "Peaches - Justin Bieber",
  "Industry Baby - Lil Nas X & Jack Harlow",
  "Montero (Call Me by Your Name) - Lil Nas X",
  "Butter - BTS",
  "Permission to Dance - BTS",
  "Vampire - Olivia Rodrigo",
  "Flowers - Miley Cyrus",
  "Unholy - Sam Smith & Kim Petras",
  "About Damn Time - Lizzo",
  "Easy on Me - Adele",
  "Running Up That Hill - Kate Bush",
  "Break My Soul - Beyoncé",
  "Espresso - Sabrina Carpenter",
  "Please Please Please - Sabrina Carpenter",
  "Paint the Town Red - Doja Cat",
  "Kill Bill - SZA",
  "Golden Hour - JVKE",
  "Die For You - The Weeknd",
  "Save Your Tears - The Weeknd & Ariana Grande",
  "Stargazing - Travis Scott",
  "Goosebumps - Travis Scott",
  "HIGHEST IN THE ROOM - Travis Scott",
  "Not Like Us - Kendrick Lamar",
  "Luther - Kendrick Lamar & SZA",
  "All the Stars - Kendrick Lamar & SZA",
  "HUMBLE. - Kendrick Lamar",
  "Money Trees - Kendrick Lamar",
  "Swimming Pools - Kendrick Lamar",
  "Started from the Bottom - Drake",
  "In My Feelings - Drake",
  "Nice for What - Drake",
  "One Dance - Drake",
  "Controlla - Drake",
  "Too Good - Drake & Rihanna",
  "Laugh Now Cry Later - Drake",
  "Knife Talk - Drake",
  "Way 2 Sexy - Drake",
  "Lose Yourself - Eminem",
  "Stan - Eminem",
  "The Real Slim Shady - Eminem",
  "River - Eminem & Ed Sheeran",
  "Godzilla - Eminem & Juice WRLD",
  "Stronger - Kanye West",
  "Gold Digger - Kanye West",
  "Heartless - Kanye West",
  "Runaway - Kanye West",
  "All of the Lights - Kanye West",
  "Ultralight Beam - Kanye West",
  "Power - Kanye West",
  "Crawling - Linkin Park",
  "Breaking the Habit - Linkin Park",
  "What I've Done - Linkin Park",
  "Somewhere I Belong - Linkin Park",
  "One Step Closer - Linkin Park",
  "Faint - Linkin Park",
  "Toxicity - System Of A Down",
  "B.Y.O.B. - System Of A Down",
  "Enter Sandman - Metallica",
  "Master of Puppets - Metallica",
  "Fade to Black - Metallica",
  "The Unforgiven - Metallica",
  "Back in Black - AC/DC",
  "Highway to Hell - AC/DC",
  "TNT - AC/DC",
  "You Shook Me All Night Long - AC/DC",
  "Hells Bells - AC/DC",
  "Welcome to the Jungle - Guns N' Roses",
  "Paradise City - Guns N' Roses",
  "Patience - Guns N' Roses",
  "Mr. Brightside - The Killers",
  "Human - The Killers",
  "Somebody Told Me - The Killers",
  "Come As You Are - Nirvana",
  "Heart-Shaped Box - Nirvana",
  "In Bloom - Nirvana",
  "Lithium - Nirvana",
  "Under the Bridge - Red Hot Chili Peppers",
  "Scar Tissue - Red Hot Chili Peppers",
  "By the Way - Red Hot Chili Peppers",
  "Dani California - Red Hot Chili Peppers",
  "Dark Necessities - Red Hot Chili Peppers",
  "Everybody Hurts - R.E.M.",
  "Man on the Moon - R.E.M.",
  "Wonderwall - Oasis",
  "Champagne Supernova - Oasis",
  "Fix You - Coldplay",
  "Clocks - Coldplay",
  "Viva la Vida - Coldplay",
  "A Sky Full of Stars - Coldplay",
  "Higher Power - Coldplay",
  "Stairway to Heaven - Led Zeppelin",
  "Whole Lotta Love - Led Zeppelin",
  "Kashmir - Led Zeppelin",
  "Hotel California - Eagles",
  "Take It Easy - Eagles",
  "Desperado - Eagles",
  "Dream On - Aerosmith",
  "Walk This Way - Aerosmith",
  "I Don't Want to Miss a Thing - Aerosmith",
  "Thriller - Michael Jackson",
  "Smooth Criminal - Michael Jackson",
  "Bad - Michael Jackson",
  "Purple Rain - Prince",
  "When Doves Cry - Prince",
  "Like a Prayer - Madonna",
  "Material Girl - Madonna",
  "Vogue - Madonna",
  "Hung Up - Madonna",
  "Toxic - Britney Spears",
  "Baby One More Time - Britney Spears",
  "Oops!... I Did It Again - Britney Spears",
  "Whenever Wherever - Shakira",
  "She Wolf - Shakira",
  "Umbrella - Rihanna",
  "We Found Love - Rihanna",
  "Needed Me - Rihanna",
  "Love on the Brain - Rihanna",
  "Work - Rihanna",
  "Bitch Better Have My Money - Rihanna",
  "Set Fire to the Rain - Adele",
  "Skyfall - Adele",
  "When We Were Young - Adele",
  "Water Under the Bridge - Adele",
  "Send My Love - Adele",
  "Teenage Dream - Katy Perry",
  "California Gurls - Katy Perry",
  "I Kissed a Girl - Katy Perry",
  "Wide Awake - Katy Perry",
  "Part of Me - Katy Perry",
  "Just Dance - Lady Gaga",
  "Born This Way - Lady Gaga",
  "Alejandro - Lady Gaga",
  "Paparazzi - Lady Gaga",
  "Telephone - Lady Gaga",
  "The Edge of Glory - Lady Gaga",
  "Wrecking Ball - Miley Cyrus",
  "Party in the U.S.A. - Miley Cyrus",
  "We Can't Stop - Miley Cyrus",
  "Love Story - Taylor Swift",
  "We Are Never Getting Back Together - Taylor Swift",
  "Style - Taylor Swift",
  "Wildest Dreams - Taylor Swift",
  "Cardigan - Taylor Swift",
  "August - Taylor Swift",
  "Enchanted - Taylor Swift",
  "Fearless - Taylor Swift",
  "22 - Taylor Swift",
  "Haunted - Taylor Swift",
  "Open Arms - Journey",
  "Separate Ways - Journey",
  "Rosanna - Toto",
  "Hold the Line - Toto",
  "Everybody Wants to Rule the World - Tears for Fears",
  "Shout - Tears for Fears",
  "Mad World - Gary Jules",
  "Enjoy the Silence - Depeche Mode",
  "Just Can't Get Enough - Depeche Mode",
  "Personal Jesus - Depeche Mode",
  "Blue Monday - New Order",
  "True Faith - New Order",
  "Bizarre Love Triangle - New Order",
  "Roxanne - The Police",
  "Message in a Bottle - The Police",
  "Karma Chameleon - Culture Club",
  "Do You Really Want to Hurt Me - Culture Club",
  "Time After Time - Cyndi Lauper",
  "True Colors - Cyndi Lauper",
  "Ray of Light - Madonna",
  "Stayin' Alive - Bee Gees",
  "How Deep Is Your Love - Bee Gees",
  "Night Fever - Bee Gees",
  "September - Earth Wind & Fire",
  "Let's Groove - Earth Wind & Fire",
  "Superstition - Stevie Wonder",
  "Isn't She Lovely - Stevie Wonder",
  "Sir Duke - Stevie Wonder",
  "Respect - Aretha Franklin",
  "Chain of Fools - Aretha Franklin",
  "I Wanna Dance with Somebody - Whitney Houston",
  "Greatest Love of All - Whitney Houston",
  "Simply the Best - Tina Turner",
  "Private Dancer - Tina Turner",
];
