// Top 100 most visited websites plus 400+ additional plausible guesses
export const mostVisitedWebsitesHints: string[] = [
  // Top 100
  "Google", "YouTube", "Facebook", "Wikipedia", "Reddit",
  "Twitter", "X", "Instagram", "Amazon", "Yahoo",
  "WhatsApp", "TikTok", "Pornhub", "Microsoft", "ChatGPT",
  "LinkedIn", "Netflix", "Bing", "Weather.com", "DuckDuckGo",
  "Twitch", "Microsoft Office", "Yandex", "Discord", "Samsung",
  "Quora", "eBay", "Roblox", "Apple", "Pinterest",
  "Zoom", "Telegram", "ESPN", "CNN", "Spotify",
  "Fandom", "Walmart", "XVIDEOS", "Stack Overflow", "Zillow",
  "GitHub", "BBC", "PayPal", "Canva", "Target",
  "Indeed", "IMDb", "Naver", "Imgur", "Etsy",
  "Craigslist", "Hulu", "Baidu", "The New York Times", "Fox News",
  "Tumblr", "Archive.org", "Investopedia", "Snapchat", "Dropbox",
  "Reuters", "Aliexpress", "Notion", "Medium", "Hugging Face",
  "Adobe", "Temu", "Figma", "Best Buy", "Home Depot",
  "USPS", "UPS", "FedEx", "Chase", "Bank of America",
  "Costco", "Booking.com", "Airbnb", "TripAdvisor", "Yelp",
  "WebMD", "Healthline", "Nike", "SHEIN", "Ikea",
  "Lowes", "Grammarly", "Wordreference", "Deepl", "The Washington Post",
  "The Guardian", "NBC News", "CBS News", "ABC News", "Bloomberg",
  "CNBC", "MarketWatch", "Glassdoor", "Coursera", "Khan Academy",
  "Duolingo",
  // Beyond top 100 — additional plausible guesses
  "Vimeo", "Dailymotion", "SoundCloud", "Bandcamp", "Last.fm",
  "MySpace", "Flickr", "DeviantArt", "ArtStation", "Behance",
  "Dribbble", "Product Hunt", "AngelList", "Crunchbase", "TechCrunch",
  "Wired", "The Verge", "Ars Technica", "Engadget", "Gizmodo",
  "Mashable", "BuzzFeed", "Vice", "Vox", "Slate",
  "Salon", "HuffPost", "Business Insider", "Forbes", "Fortune",
  "Inc", "Entrepreneur", "Fast Company", "Axios", "Politico",
  "The Hill", "The Atlantic", "The New Yorker", "Time", "Newsweek",
  "NPR", "PBS", "Al Jazeera", "RT", "Sky News",
  "Deutsche Welle", "France24", "NHK", "Xinhua", "South China Morning Post",
  "Wall Street Journal", "Financial Times", "Economist", "Barrons", "SeekingAlpha",
  "Motley Fool", "Yahoo Finance", "Google Finance", "Robinhood", "Coinbase",
  "Binance", "Kraken", "Gemini", "Crypto.com", "CoinMarketCap",
  "CoinGecko", "OpenSea", "Rarible", "Foundation", "Steam",
  "Epic Games Store", "GOG", "Humble Bundle", "itch.io", "Metacritic",
  "IGN", "GameSpot", "Polygon", "Kotaku", "PC Gamer",
  "Rock Paper Shotgun", "GamesRadar", "Eurogamer", "Nintendo", "PlayStation",
  "Xbox", "Blizzard", "Riot Games", "EA", "Ubisoft",
  "Square Enix", "Bandai Namco", "Capcom", "Sega", "Konami",
  "Bethesda", "CD Projekt Red", "Valve", "Unity", "Unreal Engine",
  "Godot", "Scratch", "CodePen", "JSFiddle", "Replit",
  "Glitch", "Vercel", "Netlify", "Heroku", "DigitalOcean",
  "AWS", "Google Cloud", "Azure", "Cloudflare", "Fastly",
  "Akamai", "WordPress", "Wix", "Squarespace", "Webflow",
  "Shopify", "BigCommerce", "WooCommerce", "Magento", "PrestaShop",
  "Drupal", "Joomla", "Ghost", "Substack", "Revue",
  "Mailchimp", "Constant Contact", "SendGrid", "HubSpot", "Salesforce",
  "Zendesk", "Intercom", "Freshdesk", "Jira", "Confluence",
  "Trello", "Asana", "Monday.com", "ClickUp", "Basecamp",
  "Todoist", "Evernote", "OneNote", "Google Docs", "Google Sheets",
  "Google Slides", "Microsoft Word", "Microsoft Excel", "Microsoft PowerPoint", "LibreOffice",
  "OpenOffice", "Airtable", "Coda", "Almanac", "Roam Research",
  "Obsidian", "Logseq", "Bear", "Ulysses", "Scrivener",
  "Overleaf", "LaTeX", "Wolfram Alpha", "Desmos", "GeoGebra",
  "Symbolab", "Photomath", "Brilliant", "edX", "Udemy",
  "Skillshare", "Masterclass", "LinkedIn Learning", "Pluralsight", "Codecademy",
  "freeCodeCamp", "The Odin Project", "LeetCode", "HackerRank", "Codewars",
  "Exercism", "Project Euler", "Kaggle", "Towards Data Science", "Analytics Vidhya",
  "DataCamp", "Udacity", "MIT OpenCourseWare", "Stanford Online", "Harvard Online",
  "Yale Open Courses", "OpenAI", "Anthropic", "Google DeepMind", "Midjourney",
  "Stable Diffusion", "DALL-E", "Runway", "Pika", "ElevenLabs",
  "Suno", "Claude", "Perplexity", "You.com", "Brave Search",
  "Ecosia", "Startpage", "Searx", "Qwant", "Mojeek",
  "Neeva", "Kagi", "Apple Music", "Tidal", "Deezer",
  "Pandora", "iHeartRadio", "Amazon Music", "YouTube Music", "SiriusXM",
  "Audiomack", "Mixcloud", "8tracks", "Genius", "AZLyrics",
  "MetroLyrics", "MusixMatch", "Songkick", "Bandsintown", "StubHub",
  "Ticketmaster", "LiveNation", "SeatGeek", "Vivid Seats", "Dice",
  "Resident Advisor", "Foursquare", "OpenTable", "Resy", "TheFork",
  "Zomato", "Swiggy", "Uber Eats", "DoorDash", "Grubhub",
  "Postmates", "Instacart", "FreshDirect", "Ocado", "Amazon Fresh",
  "Walmart Grocery", "Kroger", "Whole Foods", "Trader Joe's",
  "Sam's Club", "BJ's", "Aldi", "Lidl", "Tesco",
  "Sainsbury's", "Asda", "Morrisons", "Carrefour", "REWE",
  "Edeka", "Migros", "Coop",
];
