// ~500 most-streamed songs on Spotify (all-time)
export const mostStreamedSongsHints: string[] = [
  // Top 100 (the actual answers)
  "Blinding Lights", "Shape of You", "Someone You Loved", "As It Was", "Sunflower",
  "Dance Monkey", "Starboy", "Closer", "One Dance", "Believer",
  "Rockstar", "Heat Waves", "Stay", "Watermelon Sugar", "Lovely",
  "Don't Start Now", "Señorita", "Perfect", "Lucid Dreams", "Bohemian Rhapsody",
  "Say You Won't Let Go", "Thinking Out Loud", "God's Plan", "Save Your Tears", "Bad Guy",
  "Levitating", "Circles", "Without Me", "Thunder", "I'm Gonna Be (500 Miles)",
  "Shallow", "Love Yourself", "Happier", "Photograph", "Let Her Go",
  "Counting Stars", "Cruel Summer", "Anti-Hero", "Peaches", "Take Me to Church",
  "Riptide", "Sugar", "Jocelyn Flores", "SAD!", "Flowers",
  "Drivers License", "Sweater Weather", "7 Rings", "Sicko Mode", "Despacito",
  "Lean On", "Havana", "Stressed Out", "New Rules", "All of Me",
  "Mood", "Girls Like You", "Old Town Road", "Radioactive", "Uptown Funk",
  "Sorry", "Treat You Better", "There's Nothing Holdin' Me Back", "Something Just Like This", "Thank U Next",
  "High Hopes", "Heather", "XO Tour Llif3", "I Don't Care", "Congratulations",
  "Youngblood", "HUMBLE.", "Feel Good Inc.", "I Ain't Worried", "Dynamite",
  "Attention", "Die For You", "What Makes You Beautiful", "Ride", "Smells Like Teen Spirit",
  "Vampire", "Bad Habits", "Under the Bridge", "Dandelions", "Glimpse of Us",
  "Can't Hold Us", "River Flows in You", "Die with a Smile", "Golden Hour", "Thinkin Bout You",
  "Memories", "Before You Go", "Until I Found You", "Snowman", "Physical",
  "Unstoppable", "Gym Class Heroes: Stereo Hearts", "I Wanna Be Yours", "Put Your Records On", "Tongue Tied",
  // 101–200
  "Happier Than Ever", "Montero (Call Me by Your Name)", "Kiss Me More", "Positions", "Butter",
  "Deja Vu", "Good 4 U", "Traitor", "Brutal",
  "Astronaut in the Ocean", "Beggin'", "Industry Baby", "Stay With Me", "Pompeii",
  "Somebody That I Used to Know", "Royals", "Wake Me Up", "Hey Brother", "Waiting for Love",
  "The Nights", "Levels", "I Took a Pill in Ibiza", "Let Me Love You", "Cold Water",
  "Faded", "Alone", "Cheap Thrills", "This Is What You Came For", "Don't Let Me Down",
  "Roses", "Habits (Stay High)", "Rather Be", "All About That Bass", "Shake It Off",
  "Blank Space", "Style", "Wildest Dreams", "Bad Blood", "Love Story",
  "You Belong with Me", "We Are Never Getting Back Together", "22", "Enchanted", "Cardigan",
  "Willow", "August", "Betty", "Exile", "Invisible String",
  "Espresso", "Please Please Please", "Taste", "Lunch", "Bed Chem",
  "Lovin on Me", "Greedy", "Paint the Town Red", "Snooze", "Kill Bill",
  "Creepin'", "Calm Down", "Unholy", "Late Night Talking",
  "About Damn Time", "Running Up That Hill", "Break My Soul", "Easy on Me", "Ghost",
  "Cold Heart", "Shivers", "My Universe",
  "Take My Breath", "Essence", "Good Days",
  "Doja", "Need to Know", "Woman", "Best Friend", "Thot Shit",
  "Savage Love", "Life Goes On", "Permission to Dance", "Boy with Luv",
  "Fake Love", "DNA", "Spring Day", "Blood Sweat & Tears", "Fire",
  "How You Like That", "Lovesick Girls", "Kill This Love", "DDU-DU DDU-DU", "Boombayah",
  // 201–300
  "Wonderwall", "Don't Look Back in Anger", "Champagne Supernova", "Creep", "Karma Police",
  "No Surprises", "Fake Plastic Trees", "Yellow", "The Scientist", "Fix You",
  "Clocks", "Viva la Vida", "Paradise", "A Sky Full of Stars",
  "Hymn for the Weekend", "Adventure of a Lifetime", "Higher Power",
  "Mr. Brightside", "Somebody Told Me", "Human", "Smile Like You Mean It",
  "Come As You Are", "In Bloom", "Lithium", "Heart-Shaped Box", "All Apologies",
  "Californication", "Scar Tissue", "Otherside", "By the Way",
  "Can't Stop", "Dani California", "Snow (Hey Oh)", "Dark Necessities",
  "Losing My Religion", "Everybody Hurts", "Shiny Happy People", "Man on the Moon",
  "Where the Streets Have No Name", "With or Without You", "One", "Beautiful Day", "Vertigo",
  "Still Haven't Found What I'm Looking For", "Sunday Bloody Sunday",
  "Stairway to Heaven", "Whole Lotta Love", "Kashmir", "Black Dog", "Rock and Roll",
  "Hotel California", "Take It Easy", "Desperado", "Life in the Fast Lane",
  "Dream On", "Walk This Way", "Sweet Emotion", "I Don't Want to Miss a Thing",
  "Livin' on a Prayer", "You Give Love a Bad Name", "Wanted Dead or Alive", "It's My Life",
  "Sweet Child O' Mine", "Welcome to the Jungle", "Paradise City", "November Rain", "Patience",
  "Every Breath You Take", "Roxanne", "Message in a Bottle", "Don't Stand So Close to Me",
  "Africa", "Rosanna", "Hold the Line",
  "Billie Jean", "Thriller", "Beat It", "Smooth Criminal", "Bad",
  "Stayin' Alive", "How Deep Is Your Love", "Night Fever", "More Than a Woman",
  "September", "Let's Groove", "Boogie Wonderland",
  "Superstition", "Isn't She Lovely", "Sir Duke", "I Wish",
  // 301–400
  "Redbone", "Awaken My Love", "This Is America", "3005", "Heartbeat",
  "HIGHEST IN THE ROOM", "goosebumps", "Antidote", "Butterfly Effect",
  "STARGAZING", "STOP TRYING TO BE GOD", "COFFEE BEAN",
  "Hotline Bling", "Started from the Bottom", "Hold On We're Going Home", "Best I Ever Had",
  "Controlla", "Too Good", "Passionfruit", "Nice for What",
  "In My Feelings", "Laugh Now Cry Later", "What's Next", "Knife Talk", "Way 2 Sexy",
  "Money Trees", "Swimming Pools", "Poetic Justice", "Bitch Don't Kill My Vibe", "LOVE.",
  "LOYALTY.", "DNA.", "ELEMENT.", "All the Stars", "Not Like Us",
  "Alright", "King Kunta", "i", "These Walls",
  "Lose Yourself", "Stan", "The Real Slim Shady", "Mockingbird",
  "Rap God", "Love the Way You Lie", "Not Afraid", "River", "Godzilla",
  "Stronger", "Gold Digger", "Heartless", "Runaway", "All of the Lights",
  "Power", "Flashing Lights", "Bound 2", "Ultralight Beam", "Father Stretch My Hands",
  "Numb", "In the End", "Crawling", "Breaking the Habit", "What I've Done",
  "New Divide", "Somewhere I Belong", "One Step Closer", "Faint",
  "Chop Suey!", "Toxicity", "B.Y.O.B.", "Aerials", "Lonely Day",
  "Enter Sandman", "Nothing Else Matters", "Master of Puppets", "Fade to Black",
  "Seek & Destroy", "Wherever I May Roam", "The Unforgiven",
  "Back in Black", "Thunderstruck", "Highway to Hell", "T.N.T.", "You Shook Me All Night Long",
  "Hells Bells", "For Those About to Rock",
  // 401–500+
  "Poker Face", "Bad Romance", "Just Dance", "Born This Way", "Alejandro",
  "Paparazzi", "Telephone", "The Edge of Glory", "Always Remember Us This Way",
  "Toxic", "Baby One More Time", "Oops!... I Did It Again", "Womanizer", "Gimme More",
  "Hips Don't Lie", "Whenever Wherever", "Waka Waka", "She Wolf", "Loca",
  "Umbrella", "We Found Love", "Diamonds", "Work",
  "Needed Me", "Love on the Brain", "Kiss It Better", "Bitch Better Have My Money",
  "Rolling in the Deep", "Someone Like You", "Set Fire to the Rain", "Hello",
  "Skyfall", "When We Were Young", "Water Under the Bridge", "Send My Love",
  "Firework", "Roar", "Dark Horse", "Teenage Dream", "California Gurls",
  "Hot N Cold", "I Kissed a Girl", "Wide Awake", "Part of Me",
  "Wrecking Ball", "Party in the U.S.A.", "We Can't Stop", "The Climb",
  "Used to Be Young", "Midnight Sky",
  "Call Me Maybe", "Good Time", "I Really Like You", "Run Away with Me",
  "Get Lucky", "One More Time", "Around the World", "Harder Better Faster Stronger", "Instant Crush",
  "I Feel It Coming", "After Hours",
  "The Hills", "Can't Feel My Face", "Earned It", "Often",
  "Electric Feel", "Kids", "Time to Pretend", "Little Dark Age",
  "Pumped Up Kicks", "Sit Next to Me", "Houdini",
  "Take on Me", "Enjoy the Silence", "Just Can't Get Enough", "Personal Jesus",
  "Blue Monday", "True Faith", "Bizarre Love Triangle",
  "Don't Stop Believin'", "Separate Ways", "Open Arms",
  "Everybody Wants to Rule the World", "Shout", "Mad World",
  "The Sun Always Shines on T.V.",
  "Karma Chameleon", "Do You Really Want to Hurt Me",
  "Girls Just Want to Have Fun", "Time After Time", "True Colors",
  "Like a Prayer", "Material Girl", "Vogue", "Hung Up", "Ray of Light",
  "Purple Rain", "When Doves Cry", "Let's Go Crazy", "Kiss", "1999",
  "Respect", "Chain of Fools", "(You Make Me Feel Like) A Natural Woman",
  "I Will Always Love You", "Greatest Love of All", "I Wanna Dance with Somebody",
  "What's Love Got to Do with It", "Private Dancer", "Simply the Best",
];
