// ~500 scientific paper descriptions for hints
// Format: "First Author — Short Description (Year)"
export const mostCitedScientificPapersHints: string[] = [
  // Top 100 (the actual answers)
  "Lowry — Protein measurement with the Folin phenol reagent (1951)",
  "Laemmli — Cleavage of structural proteins during bacteriophage T4 assembly (1970)",
  "Bradford — Rapid method for quantitation of microgram quantities of protein (1976)",
  "Sanger — DNA sequencing with chain-terminating inhibitors (1977)",
  "Chomczynski — Single-step RNA isolation by acid guanidinium thiocyanate (1987)",
  "Towbin — Electrophoretic transfer of proteins to nitrocellulose sheets (1979)",
  "Lee — Colle-Salvetti correlation-energy formula as a DFT functional (1988)",
  "Becke — Density-functional thermochemistry III: role of exact exchange (1993)",
  "Murashige — Revised medium for rapid growth and bioassays with tobacco tissue (1962)",
  "Thompson — CLUSTAL W: improving progressive multiple sequence alignment (1994)",
  "Kaplan — Nonparametric estimation from incomplete observations (1958)",
  "Altschul — Basic Local Alignment Search Tool (1990)",
  "Sheldrick — A short history of SHELX (2008)",
  "Altschul — Gapped BLAST and PSI-BLAST (1997)",
  "Saiki — Primer-directed enzymatic amplification of DNA with Taq polymerase (1988)",
  "Perdew — Generalized gradient approximation made simple (1996)",
  "Kresse — Efficient iterative schemes for ab initio total-energy calculations (1996)",
  "Folstein — Mini-mental state: practical method for grading cognitive state (1975)",
  "Saitou — The neighbor-joining method for reconstructing phylogenetic trees (1987)",
  "Felsenstein — Confidence limits on phylogenies using the bootstrap (1985)",
  "Bland — Statistical methods for assessing agreement between two methods (1986)",
  "Shannon — Revised effective ionic radii in halides and chalcogenides (1976)",
  "Otwinowski — Processing of X-ray diffraction data in oscillation mode (1997)",
  "Cox — Regression models and life-tables (1972)",
  "Kresse — Ab initio molecular dynamics for liquid metals (1993)",
  "Mosmann — Rapid colorimetric assay for cellular growth and survival (1983)",
  "Livak — Analysis of relative gene expression using the 2(-Delta Delta Ct) method (2001)",
  "Thompson — The CLUSTAL X interface for progressive alignment (1997)",
  "Hohenberg — Inhomogeneous electron gas (1964)",
  "Kohn — Self-consistent equations including exchange and correlation effects (1965)",
  "Lipinski — Experimental and computational approaches to estimate solubility (1997)",
  "Becke — Density-functional exchange-energy approximation (1988)",
  "Perdew — Self-interaction correction to density-functional approximations (1981)",
  "Kresse — From ultrasoft pseudopotentials to the projector augmented-wave method (1999)",
  "Iijima — Helical microtubules of graphitic carbon (1991)",
  "Dewar — Development and use of quantum mechanical molecular models: AM1 (1985)",
  "Bligh — A rapid method of total lipid extraction and purification (1959)",
  "Edgar — MUSCLE: multiple sequence alignment with high accuracy (2004)",
  "Felsenstein — PHYLIP: phylogeny inference package (1989)",
  "Berman — The Protein Data Bank (2000)",
  "Pearson — Improved tools for biological sequence comparison: FASTA (1988)",
  "Henikoff — Amino acid substitution matrices from protein blocks: BLOSUM (1992)",
  "Needleman — A general method for search of similarities in amino acid sequences (1970)",
  "Benjamini — Controlling the false discovery rate (1995)",
  "Woese — Towards a natural system of organisms: Archaea, Bacteria, Eucarya (1990)",
  "Watts — Collective dynamics of small-world networks (1998)",
  "Barabasi — Emergence of scaling in random networks (1999)",
  "Akaike — A new look at statistical model identification (1974)",
  "Tamura — MEGA5: molecular evolutionary genetics analysis (2011)",
  "Kumar — MEGA: molecular evolutionary genetics analysis (1994)",
  "Higgins — CLUSTAL: progressive multiple sequence alignment (1988)",
  "Laskowski — PROCHECK: stereochemical quality of protein structures (1993)",
  "Kraulis — MOLSCRIPT: detailed and schematic plots of protein structures (1991)",
  "Jones — Improved methods for building protein models in electron density maps (1991)",
  "Li — Fast and accurate short read alignment with Burrows-Wheeler Aligner (2009)",
  "Vogelstein — A genetic model for colorectal tumorigenesis (1990)",
  "Woese — Bacterial evolution via 16S rRNA phylogenetic analysis (1987)",
  "Benjamini — The control of the false discovery rate under dependency (2001)",
  "Tamura — MEGA4: molecular evolutionary genetics analysis (2007)",
  "Duncan — Multiple range and multiple F-tests (1955)",
  "Li — The sequence alignment/map format and SAMtools (2009)",
  "Langmead — Ultrafast alignment of short DNA sequences: Bowtie (2009)",
  "Greenwald — Measuring individual differences in implicit cognition: IAT (1998)",
  "Bondi — Van der Waals volumes and radii (1964)",
  "Price — Principal components analysis corrects for stratification in GWAS (2006)",
  "Barrett — Haploview: analysis and visualization of LD and haplotype maps (2005)",
  "Purcell — PLINK: whole-genome association and population-based linkage analysis (2007)",
  "Trapnell — Transcript assembly and quantification by RNA-seq: Cufflinks (2010)",
  "Anders — Differential expression analysis for sequence count data: DESeq (2010)",
  "van der Maaten — Visualizing data using t-SNE (2008)",
  "Robinson — edgeR: differential expression analysis of digital gene expression data (2010)",
  "Wright — The interpretation of population structure by F-statistics (1965)",
  "Tajima — Statistical method for testing the neutral mutation hypothesis (1989)",
  "Kim — TopHat: discovering splice junctions with RNA-seq (2009)",
  "DeLano — The PyMOL molecular graphics system (2002)",
  "Subramanian — Gene set enrichment analysis: GSEA (2005)",
  "Ashburner — Gene ontology: tool for the unification of biology (2000)",
  "Collaborative Computational Project No. 4 — The CCP4 suite (1994)",
  "Murshudov — Refinement of macromolecular structures by maximum likelihood: REFMAC (1997)",
  "McKenna — The Genome Analysis Toolkit: GATK (2010)",
  "DePristo — A framework for variation discovery using next-gen sequencing: GATK (2011)",
  "Storey — Statistical significance for genome-wide studies (2003)",
  "Pruitt — NCBI Reference Sequence project: RefSeq (2005)",
  "Benson — GenBank (2000)",
  "Bateman — The Pfam protein families database (2002)",
  "Moher — PRISMA: preferred reporting items for systematic reviews (2009)",
  "Higgins — Measuring inconsistency in meta-analyses: I-squared (2003)",
  "DerSimonian — Meta-analysis in clinical trials: random effects model (1986)",
  "Egger — Bias in meta-analysis detected by a simple graphical test (1997)",
  "Devereux — A comprehensive set of sequence analysis programs for the VAX (1984)",
  "Kumar — MEGA2: molecular evolutionary genetics analysis (2001)",
  "Read — Improved Fourier coefficients for maps using phases from partial structures (1986)",
  "Brunger — X-PLOR: a system for X-ray crystallography and NMR (1992)",
  "Adams — PHENIX: a comprehensive Python-based system for macromolecular structure (2010)",
  "Bayly — A well-behaved electrostatic potential based method: RESP charges (1993)",
  "Spearman — The proof and measurement of association between two things (1904)",
  "Pearson — On the criterion that a given system of deviations: chi-squared test (1900)",
  "Schwarz — Estimating the dimension of a model: Bayesian information criterion (1978)",
  "Hanahan — The hallmarks of cancer (2000)",
  "Hanahan — Hallmarks of cancer: the next generation (2011)",

  // Additional well-known papers — Molecular Biology & Genetics
  "Watson — Molecular structure of nucleic acids: a structure for DNA (1953)",
  "Meselson — The replication of DNA in Escherichia coli (1958)",
  "Jacob — Genetic regulatory mechanisms in the synthesis of proteins (1961)",
  "Avery — Studies on the chemical nature of the substance inducing transformation (1944)",
  "Mullis — Specific enzymatic amplification of DNA in vitro (1987)",
  "Southern — Detection of specific sequences among DNA fragments: Southern blot (1975)",
  "Fire — Potent and specific genetic interference by double-stranded RNA (1998)",
  "Crick — On protein synthesis: the central dogma (1958)",
  "Sanger — The amino-acid sequence in the phenylalanyl chain of insulin (1951)",
  "Maxam — A new method for sequencing DNA: chemical sequencing (1977)",
  "Collins — Initial sequencing and analysis of the human genome (2001)",
  "Venter — The sequence of the human genome: shotgun sequencing (2001)",
  "Lander — International Human Genome Sequencing Consortium (2001)",
  "Doudna — A programmable dual-RNA-guided DNA endonuclease: CRISPR-Cas9 (2012)",
  "Zhang — Multiplex genome engineering using CRISPR-Cas systems (2013)",

  // Biochemistry
  "Edman — A method for the determination of amino acid sequence: Edman degradation (1949)",
  "Porter — The hydrolysis of rabbit y-globulin by papain: antibody structure (1958)",
  "Berg — Biochemical and genetic studies with sRNA ligases: recombinant DNA (1972)",
  "Boyer — Construction of biologically functional bacterial plasmids in vitro (1973)",
  "Kohler — Continuous cultures of fused cells: monoclonal antibodies (1975)",
  "Burnette — Western blotting: electrophoretic transfer of proteins (1981)",
  "Ames — Carcinogens are mutagens: the Ames test (1973)",
  "de Duve — The lysosome: discovery of the organelle (1955)",

  // Cell Biology
  "Hayflick — The serial cultivation of human diploid cell strains: Hayflick limit (1961)",
  "Nurse — CDC2 protein kinase homolog that controls cell cycle (1987)",
  "Evans — Establishment of pluripotential cells from mouse embryos: ES cells (1981)",
  "Kerr — Apoptosis: a basic biological phenomenon in tissue kinetics (1972)",
  "Hengartner — C. elegans cell survival gene ced-9 is a homolog of bcl-2 (1994)",
  "Sulston — Post-embryonic cell lineages of C. elegans: apoptosis genetics (1977)",

  // Structural Biology
  "Kendrew — A three-dimensional model of the myoglobin molecule (1958)",
  "Perutz — Structure of haemoglobin (1960)",
  "Ramachandran — Stereochemistry of polypeptide chain configurations (1963)",
  "Rossmann — The detection of sub-units: molecular replacement method (1962)",

  // Neuroscience
  "Hodgkin — A quantitative description of membrane current in nerve (1952)",
  "Hubel — Receptive fields of single neurones in the cat's striate cortex (1959)",
  "Bliss — Long-lasting potentiation of synaptic transmission in the dentate area (1973)",
  "O'Keefe — The hippocampus as a spatial map: place cells (1971)",
  "Raichle — A default mode of brain function: default mode network (2001)",
  "Ogawa — Brain magnetic resonance imaging with contrast: BOLD fMRI (1990)",

  // Immunology
  "Burnet — The clonal selection theory of acquired immunity (1959)",
  "Doherty — A biological role for the major histocompatibility antigens: MHC (1974)",
  "Tonegawa — Somatic generation of antibody diversity: V(D)J recombination (1976)",
  "Medzhitov — Innate immunity: Toll-like receptors review (2000)",
  "Janeway — Approaching the asymptote: evolution and revolution in immunology (1989)",

  // Physics
  "Einstein — On the electrodynamics of moving bodies: special relativity (1905)",
  "Einstein — Does the inertia of a body depend on its energy content: E=mc2 (1905)",
  "Einstein — The foundation of the general theory of relativity (1916)",
  "Bohr — On the constitution of atoms and molecules: Bohr model (1913)",
  "Heisenberg — Quantum theoretical re-interpretation of kinematic relations (1925)",
  "Schrodinger — Quantization as an eigenvalue problem: wave mechanics (1926)",
  "Dirac — The quantum theory of the electron: Dirac equation (1928)",
  "Planck — On the theory of the law of energy distribution: quantum hypothesis (1900)",
  "Anderson — The positive electron: positron discovery (1932)",
  "Bell — On the Einstein Podolsky Rosen paradox: Bell's theorem (1964)",
  "Aspect — Experimental tests of Bell's inequalities: quantum entanglement (1982)",
  "Josephson — Possible new effects in superconductive tunnelling (1962)",
  "Bardeen — Microscopic theory of superconductivity: BCS theory (1957)",
  "Geim — Electric field effect in atomically thin carbon films: graphene (2004)",
  "Binnig — Scanning tunneling microscopy: STM invention (1982)",
  "Purcell — Resonance absorption by nuclear magnetic moments: NMR (1946)",
  "Lauterbur — Image formation by induced local interactions: MRI (1973)",
  "Anderson — Absence of diffusion in certain random lattices: localization (1958)",
  "Wilson — The renormalization group and the epsilon expansion (1972)",
  "Higgs — Broken symmetries and the masses of gauge bosons (1964)",
  "Weinberg — A model of leptons: electroweak unification (1967)",
  "Penzias — A measurement of excess antenna temperature at 4080 Mc/s: CMB (1965)",
  "Hubble — A relation between distance and radial velocity: expanding universe (1929)",
  "Hawking — Particle creation by black holes: Hawking radiation (1975)",
  "Schwarzschild — On the gravitational field of a mass point (1916)",
  "Chandrasekhar — The maximum mass of ideal white dwarfs (1931)",
  "Fermi — Possible production of elements of atomic number higher than 92 (1934)",

  // Chemistry
  "Pauling — The nature of the chemical bond (1931)",
  "Pauling — The configuration of polypeptide chains in proteins: alpha helix (1951)",
  "Lewis — The atom and the molecule: Lewis structures (1916)",
  "Woodward — The conservation of orbital symmetry (1965)",
  "Suzuki — Palladium catalyzed cross-coupling reactions (1979)",
  "Heck — Palladium-catalyzed vinylic hydrogen substitution: Heck reaction (1972)",
  "Kroto — C60: Buckminsterfullerene: fullerene discovery (1985)",
  "Novoselov — Two-dimensional atomic crystals: graphene (2005)",
  "Bednorz — Possible high-Tc superconductivity in Ba-La-Cu-O (1986)",
  "Tarascon — Issues and challenges facing rechargeable lithium batteries (2001)",
  "Goodenough — LiFePO4 cathode material for lithium batteries (1997)",

  // Environmental / Earth Sciences
  "Keeling — Concentration and isotopic abundances of atmospheric CO2 (1960)",
  "Arrhenius — On the influence of carbonic acid on temperature: global warming (1896)",
  "Molina — Stratospheric sink for chlorofluoromethanes: ozone depletion (1974)",
  "Lorenz — Deterministic nonperiodic flow: chaos theory (1963)",
  "Hansen — Climate sensitivity: analysis of feedback mechanisms (1984)",
  "Tyndall — On the absorption and radiation of heat by gases: greenhouse effect (1861)",
  "Broecker — Thermohaline circulation: ocean conveyor belt (1991)",

  // Ecology and Evolution
  "Darwin — On the origin of species: natural selection (1859)",
  "Mendel — Experiments on plant hybridization: genetics foundations (1866)",
  "Hardy — Mendelian proportions in a mixed population: Hardy-Weinberg (1908)",
  "Fisher — The genetical theory of natural selection (1930)",
  "Kimura — Evolutionary rate at the molecular level: neutral theory (1968)",
  "May — Stability and complexity in model ecosystems (1973)",
  "MacArthur — The theory of island biogeography (1967)",

  // Mathematics and Computer Science
  "Shannon — A mathematical theory of communication: information theory (1948)",
  "Turing — Computing machinery and intelligence: Turing test (1950)",
  "Turing — On computable numbers: the Turing machine (1936)",
  "Nash — Equilibrium points in N-person games: Nash equilibrium (1950)",
  "Dijkstra — A note on two problems in connexion with graphs: shortest path (1959)",
  "Cortes — Support-vector networks: SVM (1995)",
  "Rumelhart — Learning representations by back-propagating errors (1986)",
  "LeCun — Gradient-based learning applied to document recognition: CNN (1998)",
  "Hochreiter — Long short-term memory: LSTM (1997)",
  "Goodfellow — Generative adversarial networks: GANs (2014)",
  "Vaswani — Attention is all you need: Transformer architecture (2017)",
  "Mikolov — Distributed representations of words: Word2Vec (2013)",
  "Devlin — BERT: pre-training of deep bidirectional transformers (2018)",
  "Krizhevsky — ImageNet classification with deep convolutional neural networks (2012)",
  "He — Deep residual learning for image recognition: ResNet (2016)",
  "Breiman — Random forests (2001)",
  "Tibshirani — Regression shrinkage and selection via the lasso (1996)",

  // Social Sciences and Psychology
  "Kahneman — Prospect theory: an analysis of decision under risk (1979)",
  "Tversky — Judgment under uncertainty: heuristics and biases (1974)",
  "Milgram — Behavioral study of obedience (1963)",
  "Bandura — Self-efficacy: toward a unifying theory of behavioral change (1977)",
  "Maslow — A theory of human motivation: hierarchy of needs (1943)",
  "Festinger — A theory of cognitive dissonance (1957)",
  "Beck — An inventory for measuring depression: BDI (1961)",
  "Hamilton — A rating scale for depression: HAM-D (1960)",
  "Engle — Autoregressive conditional heteroscedasticity: ARCH model (1982)",
  "Granger — Investigating causal relations by econometric models (1969)",
  "Fama — Efficient capital markets: a review of theory and empirical work (1970)",
  "Cronbach — Coefficient alpha and the internal structure of tests (1951)",
  "Cohen — A coefficient of agreement for nominal scales: kappa (1960)",

  // Physiology and Medicine
  "Fleming — On the antibacterial action of cultures of a Penicillium (1929)",
  "Banting — The internal secretion of the pancreas: insulin (1922)",
  "Yalow — Immunoassay of endogenous plasma insulin: radioimmunoassay (1960)",
  "Doll — The mortality of doctors in relation to smoking habits (1954)",
  "Bradford Hill — The environment and disease: association or causation? (1965)",

  // Epidemiology and Clinical Medicine
  "Rose — Sick individuals and sick populations: prevention paradox (1985)",
  "Sackett — Bias in analytic research (1979)",

  // Bioinformatics additional
  "Dayhoff — A model of evolutionary change in proteins: PAM matrices (1978)",
  "Langmead — Fast gapped-read alignment with Bowtie 2 (2012)",
  "Zhang — MACS: model-based analysis of ChIP-seq (2008)",
  "Bailey — Fitting a mixture model by expectation maximization: MEME (1994)",

  // More widely-known papers
  "Hubel — Receptive fields, binocular interaction in cat visual cortex (1962)",
  "Penrose — Gravitational collapse and space-time singularities (1965)",
  "Feynman — Space-time approach to quantum electrodynamics (1949)",
  "Gell-Mann — A schematic model of baryons and mesons: quarks (1964)",
  "Yang — Conservation of isotopic spin and isotopic gauge invariance (1954)",
  "Dirac — Quantum mechanics of many-electron systems (1929)",
  "Born — Zur Quantenmechanik: matrix mechanics (1925)",
  "Fermi — Thermodynamics of irreversible processes: Fermi-Dirac statistics (1926)",
  "Boltzmann — On the relationship between entropy and probability (1877)",
  "Maxwell — A dynamical theory of the electromagnetic field (1865)",
  "Faraday — Experimental researches in electricity (1832)",
  "Newton — Philosophiae naturalis principia mathematica (1687)",
  "Lavoisier — Elementary treatise on chemistry (1789)",
  "Dalton — A new system of chemical philosophy: atomic theory (1808)",
  "Mendeleev — The relation between the properties and atomic weights: periodic table (1869)",
  "Curie — Radioactive substances: radium and polonium (1898)",
  "Rutherford — The scattering of alpha and beta particles: nuclear model (1911)",
  "Boyle — New experiments physico-mechanical: Boyle's law (1662)",
  "Hooke — Micrographia: cell discovery (1665)",
  "Pasteur — Germ theory and its applications to medicine (1861)",
  "Koch — The etiology of tuberculosis: Koch's postulates (1882)",
  "Leeuwenhoek — Observations of little animals: microscopy (1677)",
  "Harvey — De motu cordis: blood circulation (1628)",
  "Vesalius — De humani corporis fabrica: human anatomy (1543)",
  "Copernicus — De revolutionibus orbium coelestium: heliocentric model (1543)",
  "Galileo — Dialogue concerning the two chief world systems (1632)",
  "Kepler — Astronomia nova: laws of planetary motion (1609)",
  "Linne — Systema naturae: biological taxonomy (1735)",
  "Lamarck — Philosophie zoologique: theory of inheritance (1809)",
  "Wallace — On the tendency of varieties to depart indefinitely (1858)",
  "Lyell — Principles of geology: uniformitarianism (1830)",
  "Wegener — The origin of continents and oceans: continental drift (1915)",
  "Hess — History of ocean basins: seafloor spreading (1962)",
  "Vine — Magnetic anomalies over oceanic ridges (1963)",
  "Chadwick — Possible existence of a neutron (1932)",
  "Compton — A quantum theory of the scattering of X-rays: Compton effect (1923)",
  "de Broglie — Recherches sur la theorie des quanta: wave-particle duality (1924)",
  "Pauli — On the connexion between spin and statistics: exclusion principle (1940)",
  "Yukawa — On the interaction of elementary particles: meson theory (1935)",
  "Noether — Invariante variationsprobleme: Noether's theorem (1918)",
  "Bernoulli — Hydrodynamica: Bernoulli's principle (1738)",
  "Euler — Mechanica: mathematical physics foundations (1736)",
  "Fourier — Theorie analytique de la chaleur: Fourier transform (1822)",
  "Gauss — Disquisitiones arithmeticae: number theory (1801)",
  "Riemann — On the hypotheses which lie at the basis of geometry (1854)",
  "Godel — On formally undecidable propositions: incompleteness theorems (1931)",
  "von Neumann — Mathematical foundations of quantum mechanics (1932)",
  "Wiener — Cybernetics: or control and communication (1948)",
  "Church — An unsolvable problem of elementary number theory: lambda calculus (1936)",
];
