// ~500 notable Instagram accounts (celebrities, athletes, brands, influencers)
export const mostFollowedInstagramHints: string[] = [
  // Top 100 (the actual answers)
  "Instagram", "Cristiano Ronaldo", "Lionel Messi", "Selena Gomez", "Kylie Jenner",
  "Dwayne Johnson", "Ariana Grande", "Kim Kardashian", "Beyoncé", "Khloé Kardashian",
  "Nike", "Kendall Jenner", "Justin Bieber", "Taylor Swift", "Virat Kohli",
  "Jennifer Lopez", "Kourtney Kardashian", "National Geographic", "Neymar", "Miley Cyrus",
  "Katy Perry", "Nicki Minaj", "Zendaya", "Kevin Hart", "Cardi B",
  "Real Madrid", "LeBron James", "FC Barcelona", "Rihanna", "Ellen DeGeneres",
  "Billie Eilish", "Drake", "Demi Lovato", "Chris Brown", "UEFA Champions League",
  "NASA", "Lisa", "Jennie", "Shakira", "David Beckham",
  "Gigi Hadid", "Priyanka Chopra", "Bad Bunny", "Premier League", "Kylian Mbappé",
  "Snoop Dogg", "Khaby Lame", "Dua Lipa", "Vin Diesel", "Travis Scott",
  "Shraddha Kapoor", "Narendra Modi", "BLACKPINK", "Lionel Messi Fan Club", "Maluma",
  "Paris Saint-Germain", "BTS", "Ronaldinho", "J Balvin", "Camila Cabello",
  "Manchester United", "Formula 1", "Marshmello", "Will Smith", "Karol G",
  "Lil Nas X", "Post Malone", "Selena Gomez Fan Page", "Jason Derulo", "Gal Gadot",
  "Conor McGregor", "Hailey Bieber", "Zac Efron", "Bella Hadid", "PUBG Mobile",
  "Sergio Ramos", "Hardik Pandya", "Deepika Padukone", "Alia Bhatt", "Neha Kakkar",
  "Anushka Sharma", "The Rock (Fan Page)", "Ryan Reynolds", "Manchester City", "Tom Holland",
  "Juventus", "Marvel", "Salman Khan", "Akshay Kumar", "James Rodriguez",
  "Bayern Munich", "WWE", "Marcelo", "Ozil", "Gerard Piqué",
  "Lewis Hamilton", "Mohamed Salah", "Chelsea FC", "Gareth Bale", "Netflix",
  // 101–200: More celebrities, athletes, and brands
  "Adele", "Ed Sheeran", "Bruno Mars", "The Weeknd", "Harry Styles",
  "Olivia Rodrigo", "Doja Cat", "SZA", "Megan Thee Stallion", "Lizzo",
  "Lady Gaga", "Madonna", "Britney Spears", "Christina Aguilera", "Mariah Carey",
  "Eminem", "Kanye West", "Jay-Z", "Lil Wayne", "50 Cent",
  "Ice Cube", "Dr. Dre", "Wiz Khalifa", "Chance the Rapper",
  "Tyler, the Creator", "Kendrick Lamar", "J. Cole", "21 Savage", "Future",
  "Lil Baby", "DaBaby", "Jack Harlow", "Offset", "Quavo",
  "Takeoff", "Young Thug", "Gunna", "Polo G", "Roddy Ricch",
  "Robert Downey Jr.", "Chris Hemsworth", "Scarlett Johansson", "Chris Evans", "Chris Pratt",
  "Tom Hanks", "Leonardo DiCaprio", "Brad Pitt", "Angelina Jolie", "Jennifer Aniston",
  "Sandra Bullock", "Julia Roberts", "Meryl Streep", "Nicole Kidman", "Reese Witherspoon",
  "Margot Robbie", "Ana de Armas", "Florence Pugh", "Timothée Chalamet", "Pedro Pascal",
  "Keanu Reeves", "Ryan Gosling", "Jason Momoa", "Henry Cavill", "Idris Elba",
  "Morgan Freeman", "Samuel L. Jackson", "Denzel Washington", "Will Ferrell", "Jim Carrey",
  "Adam Sandler", "Ben Affleck", "Matt Damon", "Jake Gyllenhaal", "Oscar Isaac",
  "Jared Leto", "Mark Ruffalo", "Jeremy Renner", "Paul Rudd", "Sebastian Stan",
  "Millie Bobby Brown", "Emma Watson", "Emma Stone", "Anne Hathaway", "Natalie Portman",
  "Charlize Theron", "Cate Blanchett", "Kate Winslet", "Amy Adams", "Rachel McAdams",
  "Dakota Johnson", "Sydney Sweeney", "Jenna Ortega", "Hailee Steinfeld", "Joey King",
  "Zoe Saldaña", "Lupita Nyong'o", "Viola Davis", "Kerry Washington", "Halle Berry",
  // 201–300: Athletes and sports
  "Erling Haaland", "Jude Bellingham", "Vinicius Jr.", "Luka Modrić", "Toni Kroos",
  "Robert Lewandowski", "Karim Benzema", "Antoine Griezmann", "Paul Pogba", "N'Golo Kanté",
  "Kevin De Bruyne", "Jack Grealish", "Marcus Rashford", "Bukayo Saka", "Phil Foden",
  "Pedri", "Gavi", "Jamal Musiala", "Florian Wirtz", "Lamine Yamal",
  "Zlatan Ibrahimović", "Wayne Rooney", "Frank Lampard", "Steven Gerrard", "Andrea Pirlo",
  "Gianluigi Buffon", "Paolo Maldini", "Thierry Henry", "Zinedine Zidane", "Ronaldo Nazário",
  "Diego Maradona", "Pelé", "Johan Cruyff",
  "Roger Federer", "Rafael Nadal", "Novak Djokovic", "Serena Williams", "Naomi Osaka",
  "Carlos Alcaraz", "Coco Gauff", "Stefanos Tsitsipas", "Alexander Zverev",
  "Stephen Curry", "Kevin Durant", "Giannis Antetokounmpo", "Luka Dončić", "Jayson Tatum",
  "Ja Morant", "Zion Williamson", "Anthony Edwards", "Nikola Jokić", "Joel Embiid",
  "Jimmy Butler", "Devin Booker", "Damian Lillard", "Russell Westbrook", "James Harden",
  "Kobe Bryant", "Michael Jordan", "Shaquille O'Neal", "Magic Johnson", "Larry Bird",
  "Tom Brady", "Patrick Mahomes", "Travis Kelce", "Aaron Rodgers", "Odell Beckham Jr.",
  "Lamar Jackson", "Justin Jefferson", "CeeDee Lamb", "Tyreek Hill",
  "Mike Trout", "Shohei Ohtani", "Aaron Judge", "Mookie Betts", "Bryce Harper",
  "Usain Bolt", "Simone Biles", "Michael Phelps", "Katie Ledecky", "Sha'Carri Richardson",
  "Tiger Woods", "Rory McIlroy", "Jon Rahm", "Dustin Johnson",
  "Max Verstappen", "Charles Leclerc", "Lando Norris", "Carlos Sainz", "Daniel Ricciardo",
  "Fernando Alonso", "Sebastian Vettel", "Ayrton Senna",
  // 301–400: Influencers, YouTubers, creators, brands
  "MrBeast", "PewDiePie", "Markiplier", "Jacksepticeye", "KSI",
  "Logan Paul", "Jake Paul", "David Dobrik", "Emma Chamberlain", "Addison Rae",
  "Charli D'Amelio", "Dixie D'Amelio", "Bella Poarch", "Bretman Rock",
  "James Charles", "Jeffree Star", "NikkieTutorials", "Jackie Aina", "Patrick Starrr",
  "Chiara Ferragni", "Camila Coelho", "Negin Mirsalehi", "Huda Kattan", "Nabela Noor",
  "Rosé", "Jisoo", "V (BTS)", "Jungkook", "Jimin",
  "RM", "Suga", "Jin", "J-Hope",
  "IU", "Song Hye-kyo", "Lee Min-ho", "Park Seo-joon", "Kim Soo-hyun",
  "Adidas", "Gucci", "Louis Vuitton", "Chanel", "Dior",
  "Prada", "Versace", "Balenciaga", "Fendi", "Hermès",
  "Zara", "H&M", "Uniqlo", "Supreme", "Off-White",
  "Apple", "Samsung", "Google", "Tesla", "SpaceX",
  "Amazon", "Microsoft", "Meta", "Coca-Cola", "Pepsi",
  "McDonald's", "Starbucks", "Red Bull", "GoPro", "Lego",
  "Disney", "Pixar", "Warner Bros.", "Universal Pictures", "Sony Pictures",
  "HBO", "Spotify", "YouTube", "TikTok", "Twitter",
  "9GAG", "LADbible", "Humans of New York", "Beautiful Destinations",
  "Vogue", "GQ", "Cosmopolitan", "Elle", "Harper's Bazaar",
  "Sports Illustrated", "ESPN", "Bleacher Report", "433",
  // 401–500+: More accounts across categories
  "Liverpool FC", "Arsenal", "Tottenham Hotspur", "Atlético Madrid", "AC Milan",
  "Inter Milan", "Napoli", "Borussia Dortmund", "Ajax", "Benfica",
  "Flamengo", "Boca Juniors", "River Plate", "Al-Hilal", "Al-Nassr",
  "LA Lakers", "Golden State Warriors", "Boston Celtics", "Chicago Bulls", "Miami Heat",
  "NFL", "NBA", "MLB", "NHL", "UFC",
  "AEW", "Boxing", "MotoGP", "IndyCar",
  "Olympics", "FIFA World Cup", "Copa America", "Euro Championship",
  "Oprah Winfrey", "Michelle Obama", "Barack Obama", "Joe Biden", "Elon Musk",
  "Bill Gates", "Mark Zuckerberg", "Jeff Bezos", "Warren Buffett",
  "Gordon Ramsay", "Guy Fieri", "Salt Bae", "Jamie Oliver", "Bobby Flay",
  "Kylie Cosmetics", "Fenty Beauty", "Rare Beauty", "Charlotte Tilbury", "MAC Cosmetics",
  "Victoria's Secret", "Sports Illustrated Swimsuit", "Playboy",
  "Daddy Yankee", "Ozuna", "Anuel AA", "Rauw Alejandro",
  "Rosalía", "Anitta", "Becky G", "Natti Natasha", "Farruko",
  "Peso Pluma", "Feid", "Myke Towers", "Jhayco",
  "Ranveer Singh", "Shah Rukh Khan", "Amitabh Bachchan", "Katrina Kaif", "Kareena Kapoor",
  "Sachin Tendulkar", "MS Dhoni", "Rohit Sharma", "KL Rahul",
  "Rashid Khan", "Babar Azam", "Shaheen Afridi",
  "Neeraj Chopra", "PV Sindhu", "Mary Kom",
  "Gigi Gorgeous", "Lilly Singh", "Superwoman", "Technical Guruji", "CarryMinati",
  "Bhuvan Bam", "Ashish Chanchlani", "Round2Hell",
];
