// ~500 museum names for autocomplete hints
export const mostVisitedMuseumsHints: string[] = [
  // Top 50 (the actual answers)
  "Louvre", "National Museum of China", "Vatican Museums", "Shenzhen Museum",
  "National Museum of Korea", "British Museum", "China Science and Technology Museum",
  "Natural History Museum", "Metropolitan Museum of Art", "Nanjing Museum",
  "American Museum of Natural History", "Tate Modern", "Hubei Provincial Museum",
  "Shanghai Museum East", "National Gallery of Art", "Musée d'Orsay",
  "National Museum of Anthropology", "State Russian Museum", "State Hermitage Museum",
  "Victoria and Albert Museum", "Prado Museum", "Centre Pompidou", "National Gallery",
  "Musée National d'Histoire Naturelle", "National Air and Space Museum",
  "Mevlana Museum", "National Museum of Natural History", "Galleria degli Uffizi",
  "National Museum of Natural Science", "London Science Museum",
  "Museum of Modern Art", "National Museum of Nature and Science", "M+",
  "State Tretyakov Gallery", "Rijksmuseum", "Tokyo National Museum",
  "Art Gallery of New South Wales", "National Museum of Scotland",
  "Royal Museums Greenwich", "Galleria dell'Accademia",
  "Smithsonian Museum of American History", "National Gallery Singapore",
  "21st Century Museum of Contemporary Art", "National Science and Technology Museum",
  "National Palace Museum", "National Museum in Kraków", "Van Gogh Museum",
  "The National Art Center, Tokyo", "California Science Center", "China National Silk Museum",

  // ==================== UNITED STATES ====================
  "Art Institute of Chicago", "Los Angeles County Museum of Art",
  "Philadelphia Museum of Art", "Museum of Fine Arts, Boston",
  "San Francisco Museum of Modern Art", "Whitney Museum of American Art",
  "Guggenheim Museum", "Brooklyn Museum", "Cleveland Museum of Art",
  "Detroit Institute of Arts", "Minneapolis Institute of Art",
  "Denver Art Museum", "Dallas Museum of Art", "Houston Museum of Fine Arts",
  "Nelson-Atkins Museum of Art", "Cincinnati Art Museum", "Toledo Museum of Art",
  "National Portrait Gallery", "Hirshhorn Museum",
  "National Museum of African American History and Culture",
  "National Museum of the American Indian",
  "United States Holocaust Memorial Museum", "National Constitution Center",
  "Liberty Science Center", "Field Museum", "Shedd Aquarium",
  "Adler Planetarium", "Museum of Science and Industry",
  "Boston Museum of Science", "Franklin Institute",
  "Carnegie Museum of Natural History", "Carnegie Museum of Art",
  "Peabody Museum of Natural History", "Cooper Hewitt",
  "Morgan Library & Museum", "Frick Collection",
  "Isabella Stewart Gardner Museum", "Peabody Essex Museum",
  "Henry Ford Museum", "Denver Museum of Nature and Science",
  "Natural History Museum of Los Angeles County", "Exploratorium",
  "California Academy of Sciences", "High Museum of Art",
  "New Orleans Museum of Art", "Speed Art Museum",
  "Indianapolis Museum of Art", "Columbus Museum of Art",
  "Crystal Bridges Museum of American Art", "Kimbell Art Museum",
  "Nasher Sculpture Center", "Blanton Museum of Art",
  "Heard Museum", "Musical Instrument Museum",
  "Portland Art Museum", "Seattle Art Museum",
  "Museum of Pop Culture", "Intrepid Sea, Air & Space Museum",
  "National September 11 Memorial & Museum", "Tenement Museum",
  "Strong National Museum of Play", "Corning Museum of Glass",
  "Norman Rockwell Museum", "Amon Carter Museum of American Art",

  // ==================== UNITED KINGDOM ====================
  "Ashmolean Museum", "Fitzwilliam Museum", "Scottish National Gallery",
  "Tate Britain", "Tate Liverpool", "Tate St Ives",
  "Wallace Collection", "Courtauld Gallery", "Dulwich Picture Gallery",
  "Sir John Soane's Museum", "Museum of London", "Horniman Museum",
  "Pitt Rivers Museum", "Yorkshire Museum",
  "Birmingham Museum and Art Gallery", "Manchester Museum",
  "Manchester Art Gallery", "Whitworth Art Gallery",
  "Walker Art Gallery", "National Railway Museum",
  "Royal Armouries Museum", "Kelvingrove Art Gallery and Museum",
  "Burrell Collection", "National Galleries of Scotland",
  "Imperial War Museum", "Churchill War Rooms",
  "Tate Modern", "Design Museum",

  // ==================== FRANCE ====================
  "Musée de l'Orangerie", "Musée Rodin", "Palais de Tokyo",
  "Musée Picasso", "Musée Carnavalet", "Musée de Cluny",
  "Musée de l'Armée", "Musée des Arts et Métiers",
  "Musée du Quai Branly", "Musée Marmottan Monet",
  "Fondation Louis Vuitton", "Musée Guimet",
  "Château de Versailles", "Musée des Beaux-Arts de Lyon",
  "Centre Pompidou-Metz", "Musée Matisse",
  "Musée Chagall", "Fondation Maeght",
  "Musée des Impressionnismes Giverny",

  // ==================== GERMANY ====================
  "Alte Pinakothek", "Neue Pinakothek", "Pinakothek der Moderne",
  "Deutsches Museum", "Gemäldegalerie", "Altes Museum",
  "Neues Museum", "Pergamon Museum", "Bode Museum",
  "Hamburger Kunsthalle", "Städel Museum", "Museum Ludwig",
  "Wallraf-Richartz-Museum", "Staatsgalerie Stuttgart",
  "Senckenberg Natural History Museum",

  // ==================== ITALY ====================
  "Borghese Gallery", "Capitoline Museums", "Castel Sant'Angelo",
  "Palazzo Reale", "Museo di Capodimonte", "Pinacoteca di Brera",
  "Pinacoteca Ambrosiana", "Castello Sforzesco",
  "Peggy Guggenheim Collection", "Palazzo Ducale",
  "Palazzo Pitti", "Museo Nazionale del Bargello",
  "National Archaeological Museum of Naples",

  // ==================== SPAIN ====================
  "Museo Reina Sofía", "Thyssen-Bornemisza Museum",
  "Guggenheim Bilbao", "MACBA", "MNAC",
  "Picasso Museum", "Fundació Joan Miró",

  // ==================== NETHERLANDS ====================
  "Anne Frank House", "Stedelijk Museum Amsterdam",
  "NEMO Science Museum", "Mauritshuis",
  "Kröller-Müller Museum", "Frans Hals Museum",
  "Museum het Rembrandthuis", "Boijmans Van Beuningen Museum",

  // ==================== REST OF EUROPE ====================
  "Albertina", "Belvedere", "Natural History Museum Vienna",
  "Leopold Museum", "Kunstmuseum Basel", "Foundation Beyeler",
  "Vasa Museum", "ABBA Museum", "Skansen",
  "Moderna Museet", "Louisiana Museum of Modern Art",
  "Ny Carlsberg Glyptotek", "Viking Ship Museum",
  "Munch Museum", "Pushkin State Museum of Fine Arts",
  "Kremlin Armoury", "POLIN Museum",
  "Auschwitz-Birkenau Museum", "Hungarian National Museum",
  "Museum of Fine Arts Budapest",

  // ==================== MIDDLE EAST ====================
  "Topkapi Palace Museum", "Istanbul Archaeology Museum",
  "Israel Museum", "Yad Vashem", "Tel Aviv Museum of Art",
  "Egyptian Museum", "Grand Egyptian Museum",
  "Louvre Abu Dhabi", "National Museum of Qatar",

  // ==================== ASIA ====================
  "National Museum of India", "Palace Museum",
  "Shaanxi History Museum", "Capital Museum",
  "Shanghai Museum", "Suzhou Museum",
  "Beijing Natural History Museum", "Guangdong Museum",
  "Taipei Fine Arts Museum", "Tokyo Metropolitan Art Museum",
  "National Museum of Modern Art, Tokyo", "Mori Art Museum",
  "teamLab Borderless", "Kyoto National Museum",
  "Hiroshima Peace Memorial Museum", "War Memorial of Korea",
  "Leeum Samsung Museum of Art", "National Museum of Singapore",
  "Asian Civilisations Museum", "Bangkok National Museum",
  "Angkor National Museum",

  // ==================== AMERICAS (non-US) ====================
  "Royal Ontario Museum", "Art Gallery of Ontario",
  "Canadian Museum of History", "National Gallery of Canada",
  "Vancouver Art Gallery", "Musée des beaux-arts de Montréal",
  "Museo Nacional de Bellas Artes", "MALBA",
  "Museu de Arte de São Paulo", "Museo Soumaya",
  "Museo Frida Kahlo", "Museo del Oro", "Museo Larco",
  "Palacio de Bellas Artes",

  // ==================== AFRICA / OCEANIA ====================
  "Apartheid Museum", "Iziko South African Museum",
  "Nairobi National Museum", "Ethiopian National Museum",
  "Australian War Memorial", "Museum of New Zealand Te Papa Tongarewa",
  "Auckland War Memorial Museum", "Queensland Museum",
  "Powerhouse Museum", "Australian Museum",
];
