// Top 100 most populous US cities plus 400+ additional US cities people might guess
export const mostPopulousCitiesUsaHints: string[] = [
  // Top 100
  "New York City", "Los Angeles", "Chicago", "Houston", "Phoenix",
  "Philadelphia", "San Antonio", "San Diego", "Dallas", "Jacksonville",
  "Austin", "San Jose", "Fort Worth", "Columbus", "Charlotte",
  "Indianapolis", "San Francisco", "Seattle", "Denver", "Nashville",
  "Washington DC", "Oklahoma City", "El Paso", "Las Vegas", "Memphis",
  "Louisville", "Portland", "Baltimore", "Milwaukee", "Albuquerque",
  "Tucson", "Fresno", "Sacramento", "Mesa", "Kansas City",
  "Atlanta", "Omaha", "Colorado Springs", "Raleigh", "Long Beach",
  "Virginia Beach", "Miami", "Oakland", "Minneapolis", "Tampa",
  "Tulsa", "Arlington", "New Orleans", "Bakersfield", "Wichita",
  "Aurora", "Cleveland", "Anaheim", "Henderson", "Honolulu",
  "Riverside", "Santa Ana", "Corpus Christi", "Lexington", "Stockton",
  "St. Paul", "Cincinnati", "Irvine", "Greensboro", "Pittsburgh",
  "Lincoln", "Durham", "Orlando", "St. Louis", "Plano",
  "Anchorage", "Newark", "Chandler", "Chula Vista", "Gilbert",
  "Reno", "North Las Vegas", "Madison", "Fort Wayne", "Lubbock",
  "St. Petersburg", "Laredo", "Irving", "Chesapeake", "Norfolk",
  "Jersey City", "Winston-Salem", "Scottsdale", "Boise", "Fremont",
  "Richmond", "Garland", "Baton Rouge", "Tacoma", "San Bernardino",
  "Spokane", "Hialeah", "Des Moines", "Modesto", "Birmingham",
  // Beyond top 100 — state capitals
  "Montgomery", "Juneau", "Little Rock", "Hartford",
  "Dover", "Tallahassee", "Springfield",
  "Topeka", "Frankfort", "Annapolis", "Lansing",
  "Jackson", "Jefferson City", "Helena", "Carson City",
  "Concord", "Trenton", "Santa Fe", "Albany",
  "Bismarck", "Salem", "Harrisburg", "Providence",
  "Columbia", "Pierre", "Charleston", "Cheyenne",
  "Olympia", "Augusta", "Montpelier", "Salt Lake City",
  // Major cities by region — Northeast
  "Boston", "Buffalo", "Rochester", "Syracuse", "Yonkers",
  "White Plains", "New Rochelle", "Stamford", "Bridgeport", "New Haven",
  "Waterbury", "Warwick", "Cranston",
  "Pawtucket", "Worcester", "Lowell", "Cambridge",
  "Brockton", "New Bedford", "Fall River", "Quincy", "Newton",
  "Somerville", "Brookline", "Bangor", "Lewiston",
  "Manchester", "Nashua", "Burlington", "Rutland",
  "Scranton", "Allentown", "Bethlehem", "Reading", "Erie",
  "Lancaster", "York", "Wilkes-Barre", "State College",
  "Camden", "Paterson", "Elizabeth", "Hoboken",
  "Hackensack", "Atlantic City", "Princeton",
  // Mid-Atlantic & Southeast
  "Alexandria", "Hampton", "Newport News", "Roanoke",
  "Lynchburg", "Charlottesville", "Fredericksburg", "Danville",
  "Wilmington", "Fayetteville", "Asheville", "Greenville",
  "High Point", "Gastonia", "Cary", "Apex",
  "Chapel Hill", "Huntersville", "Kannapolis",
  "Myrtle Beach", "Rock Hill", "Hilton Head",
  "Spartanburg", "Florence", "Sumter",
  "Savannah", "Macon", "Athens",
  "Valdosta", "Marietta", "Roswell", "Sandy Springs",
  "Gainesville", "Daytona Beach",
  "Fort Lauderdale", "West Palm Beach", "Coral Springs", "Pembroke Pines",
  "Hollywood", "Miramar", "Pompano Beach", "Clearwater",
  "Cape Coral", "Fort Myers", "Sarasota", "Bradenton",
  "Lakeland", "Deltona", "Palm Bay", "Melbourne",
  "Kissimmee", "Ocala", "Pensacola", "Panama City",
  "Key West", "Naples", "Port St. Lucie", "Boca Raton",
  "Deerfield Beach", "Boynton Beach", "Delray Beach",
  // South & Gulf Coast
  "Huntsville", "Mobile", "Tuscaloosa", "Hoover", "Dothan",
  "Decatur", "Gadsden", "Auburn",
  "Biloxi", "Gulfport", "Hattiesburg", "Meridian", "Tupelo",
  "Shreveport", "Lafayette", "Lake Charles", "Monroe",
  "Kenner", "Metairie", "Slidell", "Houma",
  "Fort Smith", "Jonesboro",
  "Pine Bluff", "Conway", "Rogers", "Bentonville",
  "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro",
  "Franklin", "Hendersonville", "Johnson City", "Kingsport",
  // Midwest
  "Detroit", "Grand Rapids", "Ann Arbor", "Flint",
  "Kalamazoo", "Saginaw", "Dearborn", "Livonia",
  "Sterling Heights", "Warren", "Troy", "Southfield",
  "Toledo", "Akron", "Dayton", "Youngstown",
  "Canton", "Parma", "Lorain", "Elyria",
  "Evansville", "South Bend", "Carmel",
  "Fishers", "Bloomington", "Muncie", "Terre Haute",
  "Hammond", "Gary",
  "Naperville", "Joliet", "Rockford",
  "Elgin", "Peoria", "Champaign",
  "Normal", "Waukegan", "Cicero",
  "Evanston", "Oak Park", "Schaumburg", "Bolingbrook",
  "Green Bay", "Kenosha", "Racine", "Appleton",
  "Waukesha", "Oshkosh", "Eau Claire", "La Crosse",
  "Janesville", "Fond du Lac", "Sheboygan",
  "Duluth", "Brooklyn Park",
  "Plymouth", "Maple Grove", "Woodbury", "St. Cloud",
  "Mankato", "Moorhead",
  "Cedar Rapids", "Davenport", "Sioux City", "Iowa City",
  "Waterloo", "Council Bluffs", "Ames", "Dubuque",
  "Sioux Falls", "Rapid City", "Aberdeen",
  "Fargo", "Grand Forks", "Minot",
  "Overland Park", "Olathe", "Lawrence", "Shawnee",
  "Manhattan", "Salina", "Hutchinson",
  "St. Joseph", "Independence",
  "Lee's Summit", "Blue Springs",
  // Mountain West
  "Billings", "Missoula", "Great Falls", "Bozeman",
  "Casper", "Laramie", "Gillette",
  "Idaho Falls", "Nampa", "Pocatello",
  "Provo", "Ogden", "Sandy", "Orem", "West Jordan",
  "West Valley City", "Layton", "South Jordan", "Lehi", "Logan",
  "Tempe", "Glendale", "Surprise",
  "Goodyear", "Avondale", "Flagstaff", "Yuma",
  "Lake Havasu City", "Prescott", "Sierra Vista", "Marana",
  "Fort Collins", "Lakewood", "Thornton", "Arvada",
  "Westminster", "Centennial", "Pueblo", "Boulder",
  "Greeley", "Longmont", "Loveland", "Broomfield",
  // Southwest & Texas
  "Amarillo", "Brownsville", "McAllen", "Midland",
  "Odessa", "Beaumont", "Abilene", "Round Rock",
  "Pearland", "Sugar Land", "Carrollton", "Denton",
  "Lewisville", "Allen", "Tyler", "Waco",
  "Killeen", "College Station", "Bryan", "San Marcos",
  "Temple", "Pflugerville", "Georgetown",
  "Las Cruces", "Rio Rancho", "Farmington",
  // Pacific & West Coast
  "Pasadena", "Torrance", "Pomona",
  "Escondido", "Sunnyvale", "Hayward",
  "Roseville", "Elk Grove", "Santa Clara", "Santa Rosa",
  "Rancho Cucamonga", "Oceanside", "Ontario", "Garden Grove",
  "Oxnard", "Ventura", "Santa Barbara", "San Mateo",
  "Redwood City", "Palo Alto", "Mountain View", "Milpitas",
  "Antioch", "Berkeley",
  "Daly City", "South San Francisco", "Vallejo", "Fairfield",
  "Vacaville", "Visalia", "Clovis", "Turlock", "Merced",
  "Chico", "Redding", "Napa", "Petaluma",
  "San Luis Obispo", "Santa Maria", "Lompoc",
  "Thousand Oaks", "Simi Valley", "Camarillo", "Moorpark",
  "Palmdale", "Victorville", "Fontana",
  "Moreno Valley", "Corona", "Murrieta", "Temecula",
  "Hemet", "Indio", "Palm Springs", "Palm Desert",
  "El Centro", "Carlsbad", "Vista", "Encinitas",
  "Eugene", "Bend", "Medford", "Corvallis",
  "Gresham", "Hillsboro", "Beaverton",
  "Lake Oswego", "Tigard", "Tualatin",
  "Bellevue", "Everett", "Kent", "Renton",
  "Federal Way", "Bellingham",
  "Yakima", "Kennewick", "Richland", "Pasco",
  "Vancouver", "Redmond", "Kirkland",
  "Shoreline", "Burien", "Sammamish", "Issaquah",
  // Other notable cities
  "Santa Cruz", "Sedona",
  "Park City", "Aspen", "Vail", "Telluride",
  "Martha's Vineyard", "Nantucket",
];
