export const mostFollowedTwitterHints: string[] = [
  // Top 100 (the actual answers)
  "Elon Musk", "Barack Obama", "Donald Trump", "Narendra Modi", "Cristiano Ronaldo",
  "Rihanna", "NASA", "Justin Bieber", "Katy Perry", "Taylor Swift",
  "Lady Gaga", "Kim Kardashian", "YouTube", "Virat Kohli", "Bill Gates",
  "Ellen DeGeneres", "CNN", "X (Twitter)", "CNN Breaking News", "Neymar",
  "Selena Gomez", "PMO India", "ESPN", "The New York Times", "UEFA Champions League",
  "BBC Breaking News", "Real Madrid CF", "LeBron James", "Justin Timberlake", "BTS",
  "FC Barcelona", "NBA", "Shakira", "Premier League", "Amitabh Bachchan",
  "BTS Official", "Akshay Kumar", "Demi Lovato", "PlayStation", "Jimmy Fallon",
  "Britney Spears", "Salman Khan", "BBC World News", "SportsCenter", "SpaceX",
  "Miley Cyrus", "Shah Rukh Khan", "Sachin Tendulkar", "Manchester United FC", "Joe Biden",
  "Mohamed Salah", "Fabrizio Romano", "Pope Leo XIV", "Fortnite", "ABC News",
  "Gerard Piqué", "Manchester City", "Ed Sheeran", "Al Arabiya", "Felipe Neto",
  "Netflix France", "Ibai Llanos", "The Associated Press", "Donald Trump Jr.", "Binance",
  "Rafael Nadal", "Al-Waleed bin Talal", "Kylian Mbappé", "Beyoncé", "BBC News UK",
  "Diddy", "Sports", "Tim Cook", "The Times of India", "Billboard",
  "Nintendo of America", "EXO", "Microsoft", "Netflix Thailand", "BT21",
  "Tucker Carlson", "ENHYPEN", "CGTN", "World Health Organization", "Jair Bolsonaro",
  "Formula 1", "Indian National Congress", "China Xinhua News", "HuffPost", "The Guardian",
  "Changpeng Zhao", "Programa Pânico", "TED Talks", "Fantástico", "BLACKPINK",
  "Russell Brand", "Emmanuel Macron", "Serena Williams", "Andrés Manuel López Obrador", "Niall Horan",
  // Beyond top 100 (additional plausible guesses)
  "Ariana Grande", "Bruno Mars", "Eminem", "Drake", "Kanye West", "Travis Scott",
  "Cardi B", "Nicki Minaj", "Post Malone", "Billie Eilish", "Olivia Rodrigo", "Harry Styles",
  "One Direction", "The Weeknd", "Doja Cat", "Lizzo", "Dua Lipa", "Charlie Puth",
  "Shawn Mendes", "Camila Cabello", "Halsey", "Lana Del Rey", "Sam Smith", "Adele",
  "Roger Federer", "Tiger Woods", "Michael Jordan", "Kobe Bryant",
  "Stephen Curry", "Kevin Durant", "Giannis Antetokounmpo", "Lionel Messi", "Neymar Jr.",
  "Ronaldo", "Zlatan Ibrahimovic", "David Beckham", "Wayne Rooney", "Rio Ferdinand",
  "BBC", "Reuters", "AP News", "Washington Post", "The Economist", "TIME",
  "Google", "Apple", "Amazon", "Netflix", "Disney", "HBO",
  "White House", "NASA JPL", "Tesla", "OpenAI",
  "Joe Rogan", "Jimmy Kimmel", "Stephen Colbert", "Trevor Noah", "Conan O'Brien",
  "Oprah Winfrey", "Ryan Reynolds", "Dwayne Johnson", "Kevin Hart",
];
