// Top 100 most used English words plus 500+ additional common English words
export const mostUsedEnglishWordsHints: string[] = [
  // Top 100
  "the", "be", "to", "of", "and",
  "a", "in", "that", "have", "I",
  "it", "for", "not", "on", "with",
  "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from",
  "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one",
  "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about",
  "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time",
  "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good",
  "some", "could", "them", "see", "other",
  "than", "then", "now", "look", "only",
  "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how",
  "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any",
  "these", "give", "day", "most", "us",
  // Beyond top 100 — common verbs
  "run", "walk", "talk", "tell", "ask",
  "try", "call", "need", "help", "start",
  "show", "play", "move", "live", "feel",
  "put", "read", "keep", "let", "begin",
  "seem", "leave", "turn", "hear", "pay",
  "bring", "write", "sit", "stand", "lose",
  "hold", "learn", "change", "lead", "understand",
  "watch", "follow", "stop", "speak", "create",
  "grow", "open", "close", "win", "build",
  "offer", "remember", "consider", "appear", "buy",
  "wait", "serve", "die", "send", "expect",
  "stay", "fall", "cut", "reach", "kill",
  "remain", "suggest", "raise", "pass", "sell",
  "require", "report", "decide", "pull", "develop",
  "eat", "drink", "sleep", "drive", "fly",
  "draw", "break", "spend", "carry", "happen",
  "set", "pick", "add", "meet", "catch",
  "throw", "push", "fill", "save", "cover",
  "teach", "sing", "fight", "drop", "share",
  "smile", "laugh", "cry", "jump", "dance",
  "swim", "climb", "ride", "shake", "hang",
  "hit", "wake", "miss", "touch", "wish",
  "finish", "love", "hate", "hope", "worry",
  "believe", "agree", "argue", "explain", "mean",
  "allow", "become", "choose", "continue", "include",
  "involve", "receive", "suppose", "wonder",
  // Common nouns
  "man", "woman", "child", "hand", "head",
  "place", "house", "world", "life", "school",
  "country", "city", "number", "water", "money",
  "story", "fact", "part", "side", "thing",
  "name", "family", "group", "problem", "point",
  "word", "food", "car", "body", "mind",
  "face", "door", "room", "friend", "mother",
  "father", "night", "home", "line", "end",
  "power", "state", "area", "land", "game",
  "system", "program", "question", "book", "idea",
  "eye", "case", "kind", "company", "team",
  "light", "table", "law", "girl", "boy",
  "son", "daughter", "brother", "sister", "wife",
  "husband", "baby", "job", "office", "war",
  "king", "street", "air", "picture", "month",
  "week", "hour", "minute", "second", "morning",
  "class", "form", "reason", "music", "person",
  "heart", "voice", "road", "bed", "dog",
  "cat", "tree", "fire", "field", "river",
  "sea", "floor", "wall", "window", "ground",
  "garden", "church", "box", "paper", "town",
  "color", "age", "art", "sun",
  "moon", "star", "sky", "earth", "rain",
  "snow", "wind", "stone", "hill", "mountain",
  "island", "lake", "forest", "farm", "horse",
  "bird", "fish", "flower", "boat", "ship",
  "letter", "market", "store", "phone", "bank",
  "army", "court", "god", "death",
  "doctor", "teacher", "student", "queen",
  "president", "police", "soldier", "sport", "film",
  "movie", "song", "news", "health", "price",
  "oil", "ball", "cup", "glass", "bag",
  "chair", "hat", "shoe", "dress", "shirt",
  "coat", "ring", "card", "key", "sign",
  "bridge", "park", "corner", "train", "bus",
  "plan", "type", "record", "model", "gift",
  "pain", "blood", "skin", "hair", "arm",
  "leg", "foot", "finger", "mouth", "nose",
  "ear", "tooth", "neck", "shoulder", "knee",
  "brain", "bone", "muscle", "stomach", "chest",
  // Common adjectives
  "big", "small", "old", "young", "long",
  "great", "little", "right", "left", "high",
  "low", "large", "real", "hard", "far",
  "late", "early", "fast", "slow", "hot",
  "cold", "dark", "bright", "strong", "weak",
  "deep", "wide", "thin", "thick", "short",
  "tall", "heavy", "full", "empty", "clean",
  "dirty", "quiet", "loud", "soft", "rough",
  "smooth", "wet", "dry", "rich", "poor",
  "happy", "sad", "angry", "afraid", "safe",
  "dangerous", "beautiful", "ugly", "important", "possible",
  "free", "clear", "easy", "difficult", "simple",
  "certain", "special", "different", "same", "true",
  "false", "wrong", "whole", "own", "next",
  "last", "past", "present", "future", "local",
  "public", "private", "black", "white",
  "red", "blue", "green", "yellow", "brown",
  "dead", "alive", "sick", "healthy", "tired",
  "ready", "busy", "broken", "sharp", "flat",
  "sweet", "sour", "bitter", "fresh", "raw",
  "rare", "wild", "strange", "crazy", "nice",
  "bad", "fine", "pretty", "common", "popular",
  "famous", "foreign", "ancient", "modern", "recent",
  "natural", "human", "political", "social", "economic",
  "military", "religious", "legal", "medical", "financial",
  // Common adverbs and prepositions
  "very", "really", "quite", "almost", "always",
  "never", "often", "sometimes", "usually", "already",
  "still", "yet", "here", "away", "together",
  "alone", "again", "once", "soon", "however",
  "perhaps", "maybe", "too", "enough",
  "between", "against", "through", "during", "before",
  "above", "below", "under", "behind",
  "beside", "near", "off", "around", "along",
  "across", "down", "inside", "outside", "toward",
  // Common pronouns and determiners
  "each", "every", "both", "few", "many",
  "much", "more", "less", "another", "such",
  "several", "either",
  "neither", "nobody", "nothing", "someone", "something",
  "anyone", "anything", "everyone", "everything", "myself",
  "himself", "herself", "itself", "themselves", "whose",
  // Common conjunctions and function words
  "while", "since", "until", "although", "though",
  "whether", "unless", "else", "rather",
  "indeed", "thus", "therefore", "hence", "besides",
  "meanwhile", "moreover", "nevertheless", "otherwise", "instead",
  // Additional common words
  "answer", "attention", "board", "century", "chance",
  "choice", "condition", "control", "culture", "direction",
  "education", "effect", "effort", "energy", "environment",
  "example", "experience", "figure", "force",
  "general", "growth", "history", "industry", "information",
  "interest", "language", "level", "material", "matter",
  "measure", "member", "method", "moment", "movement",
  "nature", "order",
  "period", "piece", "policy", "position",
  "pressure", "process", "product", "quality", "range",
  "rate", "region", "relationship", "research", "resource",
  "result", "role", "rule", "science", "section",
  "sense", "service", "society", "source", "space",
  "stage", "structure", "study", "subject", "success",
  "support", "technology", "test", "theory", "thought",
  "trade", "training", "truth", "value",
  "view", "weather", "weight", "bit",
  "deal", "goal", "issue", "loss", "stuff",
  "task", "term", "unit", "risk", "step",
  "club", "edge", "mark", "shape", "site",
  "spot", "track", "wave", "band", "crowd",
  "pair", "path", "race", "scale", "scene",
  "screen", "skill", "speed", "stock",
  "style", "supply", "theme", "tool",
  "trip", "trust", "variety", "version",
  "volume", "waste", "youth", "advice", "argument",
  "beginning", "bottom", "breath", "career", "challenge",
  "collection", "comfort", "communication", "community", "comparison",
  "competition", "complaint", "connection", "construction", "conversation",
  "definition", "demand", "description", "design", "detail",
  "development", "discussion", "distance", "document", "doubt",
  "drawing", "election", "equipment", "establishment", "evening",
  "event", "evidence", "explanation", "expression", "failure",
  "feature", "flight", "function",
  "generation", "holiday", "hospital", "imagination", "impact",
  "improvement", "independence", "instruction", "intention", "introduction",
  "investment", "judgment", "knowledge", "league", "length",
  "lesson", "library", "limit", "location", "magazine",
  "manner", "meaning", "message", "middle", "mistake",
  "mixture", "network", "notice", "object", "occasion",
  "operation", "opinion", "option", "outcome", "painting",
  "patience", "pattern", "payment", "percentage", "performance",
  "permission", "pleasure", "population", "possession", "possibility",
  "practice", "preference", "preparation", "principle", "priority",
  "progress", "promise", "property", "protection", "purpose",
  "reaction", "reality", "recipe", "reference",
  "religion", "reputation", "request", "requirement", "respect",
  "response", "responsibility", "restaurant", "revolution", "reward",
  "safety", "sample", "satisfaction", "secretary", "selection",
  "sentence", "setting", "signal", "situation", "solution",
  "somewhere", "statement", "storage", "stranger", "strategy",
  "strength", "suggestion", "surprise", "sympathy", "temperature",
  "tension", "tradition", "understanding", "vehicle", "village",
  "warning", "weakness", "weekend", "welcome", "winner",
  "winter",
];
