// ~1800 songs for hints
export const mostStreamedSongsHints: string[] = [
  // Top 100 (the actual answers)
  "Blinding Lights", "Shape of You", "Someone You Loved", "As It Was", "Sunflower",
  "Dance Monkey", "Starboy", "Closer", "One Dance", "Believer",
  "Rockstar", "Heat Waves", "Stay", "Watermelon Sugar", "Lovely",
  "Don't Start Now", "Señorita", "Perfect", "Lucid Dreams", "Bohemian Rhapsody",
  "Say You Won't Let Go", "Thinking Out Loud", "God's Plan", "Save Your Tears", "Bad Guy",
  "Levitating", "Circles", "Without Me", "Thunder", "I'm Gonna Be (500 Miles)",
  "Shallow", "Love Yourself", "Happier", "Photograph", "Let Her Go",
  "Counting Stars", "Cruel Summer", "Anti-Hero", "Peaches", "Take Me to Church",
  "Riptide", "Sugar", "Jocelyn Flores", "SAD!", "Flowers",
  "Drivers License", "Sweater Weather", "7 Rings", "Sicko Mode", "Despacito",
  "Lean On", "Havana", "Stressed Out", "New Rules", "All of Me",
  "Mood", "Girls Like You", "Old Town Road", "Radioactive", "Uptown Funk",
  "Sorry", "Treat You Better", "There's Nothing Holdin' Me Back", "Something Just Like This", "Thank U Next",
  "High Hopes", "Heather", "XO Tour Llif3", "I Don't Care", "Congratulations",
  "Youngblood", "HUMBLE.", "Feel Good Inc.", "I Ain't Worried", "Dynamite",
  "Attention", "Die For You", "What Makes You Beautiful", "Ride", "Smells Like Teen Spirit",
  "Vampire", "Bad Habits", "Under the Bridge", "Dandelions", "Glimpse of Us",
  "Can't Hold Us", "River Flows in You", "Die with a Smile", "Golden Hour", "Thinkin Bout You",
  "Memories", "Before You Go", "Until I Found You", "Snowman", "Physical",
  "Unstoppable", "Gym Class Heroes: Stereo Hearts", "I Wanna Be Yours", "Put Your Records On", "Tongue Tied",

  // ==================== 2020s POP / HITS ====================
  "Happier Than Ever", "Montero (Call Me by Your Name)", "Kiss Me More", "Positions", "Butter",
  "Deja Vu", "Good 4 U", "Traitor", "Brutal", "Favorite Crime",
  "Astronaut in the Ocean", "Beggin'", "Industry Baby", "Stay With Me", "Pompeii",
  "Espresso", "Please Please Please", "Taste", "Lunch", "Bed Chem",
  "Lovin on Me", "Greedy", "Paint the Town Red", "Snooze", "Kill Bill",
  "Creepin'", "Calm Down", "Unholy", "Late Night Talking",
  "About Damn Time", "Running Up That Hill", "Break My Soul", "Easy on Me", "Ghost",
  "Cold Heart", "Shivers", "My Universe",
  "Take My Breath", "Essence", "Good Days",
  "Doja", "Need to Know", "Woman", "Best Friend", "Thot Shit",
  "Savage Love", "Life Goes On", "Permission to Dance", "Boy with Luv",
  "Fake Love", "DNA", "Spring Day", "Blood Sweat & Tears", "Fire",
  "How You Like That", "Lovesick Girls", "Kill This Love", "DDU-DU DDU-DU", "Boombayah",
  "Water", "Fukumean", "Search & Rescue", "Rich Flex", "Jimmy Cooks",
  "Superhero", "All My Life", "Cupid", "Seven", "Standing Next to You",
  "Daylight", "Strangers", "Stick Season", "Feather", "Vampire",
  "Last Night", "Fast Car", "What Was I Made For?", "I'm Good (Blue)",
  "Unholy", "Flowers", "As It Was", "Boy's a Liar Pt. 2", "Escapism",
  "Ceilings", "Made You Look", "Calm Down", "Under the Influence",
  "Lavender Haze", "Karma", "Bejeweled", "Midnight Rain", "Snow on the Beach",
  "Maroon", "Anti-Hero", "Mastermind", "Vigilante Shit", "Question...?",
  "Die with a Smile", "APT.", "That's So True", "Birds of a Feather",
  "Taste", "Good Luck Babe!", "Too Sweet", "Beautiful Things",
  "Lose Control", "Million Dollar Baby", "Saturn", "End of Beginning",
  "Fortnight", "I Can Do It with a Broken Heart", "So Long London", "Down Bad",
  "The Smallest Man Who Ever Lived", "I Can Fix Him (No Really I Can)",
  "Not Like Us", "Euphoria", "Meet the Grahams", "Like That",
  "Texas Hold 'Em", "16 Carriages", "Jolene", "Bodyguard",
  "A Bar Song (Tipsy)", "I Had Some Help", "Lose Control",
  "Pink Pony Club", "HOT TO GO!", "Good Luck Babe!",
  "Nasty", "Yeah Glo!", "Wanna Be", "360",

  // ==================== 2010s POP ====================
  "Somebody That I Used to Know", "Royals", "Wake Me Up", "Hey Brother", "Waiting for Love",
  "The Nights", "Levels", "I Took a Pill in Ibiza", "Let Me Love You", "Cold Water",
  "Faded", "Alone", "Cheap Thrills", "This Is What You Came For", "Don't Let Me Down",
  "Roses", "Habits (Stay High)", "Rather Be", "All About That Bass", "Shake It Off",
  "Blank Space", "Style", "Wildest Dreams", "Bad Blood", "Love Story",
  "You Belong with Me", "We Are Never Getting Back Together", "22", "Enchanted", "Cardigan",
  "Willow", "August", "Betty", "Exile", "Invisible String",
  "Call Me Maybe", "Good Time", "I Really Like You", "Run Away with Me",
  "Happy", "Get Lucky", "One More Time", "Around the World", "Harder Better Faster Stronger",
  "Instant Crush", "I Feel It Coming", "After Hours",
  "The Hills", "Can't Feel My Face", "Earned It", "Often",
  "Chandelier", "Elastic Heart", "Cheap Thrills", "Unstoppable", "Titanium",
  "We Found Love", "Diamonds", "Work", "Needed Me", "Love on the Brain",
  "Firework", "Roar", "Dark Horse", "Teenage Dream", "California Gurls",
  "Hot N Cold", "I Kissed a Girl", "Wide Awake", "Part of Me",
  "Wrecking Ball", "Party in the U.S.A.", "We Can't Stop", "The Climb",
  "Problem", "Bang Bang", "Break Free", "Into You", "No Tears Left to Cry",
  "Side to Side", "Dangerous Woman", "One Last Time", "Love Me Harder",
  "Fancy", "Black Widow", "Work from Home", "Worth It",
  "Uptown Funk", "Locked Out of Heaven", "When I Was Your Man", "Just the Way You Are",
  "Grenade", "Treasure", "That's What I Like", "24K Magic", "Finesse",
  "Can't Stop the Feeling!", "Mirrors", "Cry Me a River", "Rock Your Body",
  "Sorry", "What Do You Mean?", "Love Yourself", "Baby", "Boyfriend",
  "Intentions", "Yummy", "Peaches", "Ghost", "Holy",
  "Pillowtalk", "Dusk Till Dawn", "Let Me", "I Don't Wanna Live Forever",
  "Stitches", "There's Nothing Holdin' Me Back", "Treat You Better", "Mercy",
  "In My Blood", "Señorita", "Wonder",
  "New Rules", "Don't Start Now", "Levitating", "Physical", "Break My Heart",
  "IDGAF", "Kiss and Make Up", "Electricity",
  "Havana", "Señorita", "Never Be the Same", "Crying in the Club",
  "Taki Taki", "I Like It", "Bodak Yellow", "WAP", "Up",
  "Be Alright", "2002", "Lush Life", "Cool", "Love Me Like You Do",
  "Burn", "On My Own",
  "Stitches", "Youth", "Mercy", "Ruin",
  "We Don't Talk Anymore", "Attention", "How Long", "Light Switch",
  "Stay", "Boyfriend", "Dangerously",
  "All of Me", "Love in the Dark", "Ordinary People",
  "Thinking Out Loud", "Photograph", "Castle on the Hill", "Galway Girl",
  "Happier", "Perfect", "Shape of You",

  // ==================== CLASSIC ROCK ====================
  "Wonderwall", "Don't Look Back in Anger", "Champagne Supernova", "Live Forever", "Supersonic",
  "Creep", "Karma Police", "No Surprises", "Fake Plastic Trees", "Paranoid Android",
  "Yellow", "The Scientist", "Fix You", "Clocks", "Viva la Vida",
  "Paradise", "A Sky Full of Stars", "Hymn for the Weekend", "Adventure of a Lifetime", "Higher Power",
  "Mr. Brightside", "Somebody Told Me", "Human", "Smile Like You Mean It", "When You Were Young",
  "Come As You Are", "In Bloom", "Lithium", "Heart-Shaped Box", "All Apologies",
  "Californication", "Scar Tissue", "Otherside", "By the Way", "Can't Stop",
  "Dani California", "Snow (Hey Oh)", "Dark Necessities", "Give It Away", "Under the Bridge",
  "Losing My Religion", "Everybody Hurts", "Shiny Happy People", "Man on the Moon",
  "Where the Streets Have No Name", "With or Without You", "One", "Beautiful Day", "Vertigo",
  "Still Haven't Found What I'm Looking For", "Sunday Bloody Sunday", "Pride (In the Name of Love)",
  "Stairway to Heaven", "Whole Lotta Love", "Kashmir", "Black Dog", "Rock and Roll",
  "Hotel California", "Take It Easy", "Desperado", "Life in the Fast Lane", "New Kid in Town",
  "Dream On", "Walk This Way", "Sweet Emotion", "I Don't Want to Miss a Thing",
  "Livin' on a Prayer", "You Give Love a Bad Name", "Wanted Dead or Alive", "It's My Life",
  "Sweet Child O' Mine", "Welcome to the Jungle", "Paradise City", "November Rain", "Patience",
  "Every Breath You Take", "Roxanne", "Message in a Bottle", "Don't Stand So Close to Me",
  "Africa", "Rosanna", "Hold the Line",
  "Billie Jean", "Thriller", "Beat It", "Smooth Criminal", "Bad", "The Way You Make Me Feel",
  "Stayin' Alive", "How Deep Is Your Love", "Night Fever", "More Than a Woman",
  "September", "Let's Groove", "Boogie Wonderland", "Shining Star",
  "Superstition", "Isn't She Lovely", "Sir Duke", "I Wish", "Higher Ground",
  "Bohemian Rhapsody", "We Will Rock You", "We Are the Champions", "Don't Stop Me Now",
  "Somebody to Love", "Under Pressure", "Another One Bites the Dust", "Radio Ga Ga",
  "Imagine", "Come Together", "Let It Be", "Hey Jude", "Yesterday",
  "Here Comes the Sun", "Something", "Twist and Shout", "A Day in the Life",
  "Norwegian Wood", "Strawberry Fields Forever", "Eleanor Rigby", "Blackbird",
  "In My Life", "Help!", "I Want to Hold Your Hand", "She Loves You",
  "Satisfaction", "Paint It Black", "Sympathy for the Devil", "Gimme Shelter",
  "Start Me Up", "Jumpin' Jack Flash", "Wild Horses", "Brown Sugar",
  "Purple Haze", "All Along the Watchtower", "Hey Joe", "Voodoo Child",
  "The Wind Cries Mary", "Little Wing", "Crosstown Traffic",
  "Light My Fire", "Riders on the Storm", "Break On Through", "People Are Strange",
  "Baba O'Riley", "Won't Get Fooled Again", "My Generation", "Behind Blue Eyes", "Pinball Wizard",
  "Smoke on the Water", "Highway Star", "Child in Time", "Space Truckin'",
  "Wish You Were Here", "Comfortably Numb", "Another Brick in the Wall", "Money",
  "Time", "Brain Damage", "Breathe", "Us and Them", "Shine On You Crazy Diamond",
  "Free Bird", "Simple Man", "Sweet Home Alabama", "Tuesday's Gone",
  "Black Sabbath", "Paranoid", "Iron Man", "War Pigs", "Children of the Grave",
  "Fortunate Son", "Have You Ever Seen the Rain", "Bad Moon Rising", "Down on the Corner",
  "Born to Run", "Thunder Road", "Dancing in the Dark", "Glory Days",
  "I'm on Fire", "The River", "Badlands", "Hungry Heart",
  "More Than a Feeling", "Don't Look Back", "Peace of Mind",
  "Carry on Wayward Son", "Dust in the Wind", "Point of Know Return",
  "Ramblin' Man", "Whipping Post", "Midnight Rider", "Jessica",
  "Layla", "Wonderful Tonight", "Tears in Heaven", "Sunshine of Your Love",
  "Barracuda", "Crazy on You", "Magic Man", "Alone",
  "Tom Sawyer", "Limelight", "The Spirit of Radio", "Closer to the Heart",
  "Sultans of Swing", "Money for Nothing", "Walk of Life", "Brothers in Arms",

  // ==================== HIP-HOP / RAP ====================
  "Redbone", "This Is America", "3005", "Heartbeat",
  "HIGHEST IN THE ROOM", "goosebumps", "Antidote", "Butterfly Effect",
  "STARGAZING", "STOP TRYING TO BE GOD", "COFFEE BEAN", "FE!N",
  "Hotline Bling", "Started from the Bottom", "Hold On We're Going Home", "Best I Ever Had",
  "Controlla", "Too Good", "Passionfruit", "Nice for What",
  "In My Feelings", "Laugh Now Cry Later", "What's Next", "Knife Talk", "Way 2 Sexy",
  "Money Trees", "Swimming Pools", "Poetic Justice", "Bitch Don't Kill My Vibe", "LOVE.",
  "LOYALTY.", "DNA.", "ELEMENT.", "All the Stars", "Not Like Us",
  "Alright", "King Kunta", "i", "These Walls", "Money Trees",
  "Lose Yourself", "Stan", "The Real Slim Shady", "Mockingbird",
  "Rap God", "Love the Way You Lie", "Not Afraid", "River", "Godzilla",
  "Without Me", "Cleaning Out My Closet", "Sing for the Moment", "Like Toy Soldiers",
  "Stronger", "Gold Digger", "Heartless", "Runaway", "All of the Lights",
  "Power", "Flashing Lights", "Bound 2", "Ultralight Beam", "Father Stretch My Hands",
  "Juicy", "Big Poppa", "Hypnotize", "Mo Money Mo Problems", "One More Chance",
  "C.R.E.A.M.", "Protect Ya Neck", "Triumph", "Da Mystery of Chessboxin'",
  "Gin and Juice", "Drop It Like It's Hot", "Beautiful", "Still D.R.E.",
  "Nuthin' but a 'G' Thang", "California Love", "Changes", "Dear Mama", "Hit 'Em Up",
  "Ambitionz Az a Ridah", "All Eyez on Me", "How Do U Want It",
  "Roses", "Hey Ya!", "Ms. Jackson", "Bombs Over Baghdad", "So Fresh So Clean",
  "Hard Knock Life", "Empire State of Mind", "N****s in Paris", "Run This Town",
  "99 Problems", "Izzo (H.O.V.A.)", "Song Cry", "Dirt Off Your Shoulder",
  "A Milli", "6 Foot 7 Foot", "Lollipop", "Go DJ", "Mrs. Officer",
  "In Da Club", "Many Men", "21 Questions", "Candy Shop", "P.I.M.P.",
  "Tipsy", "Yeah!", "Low", "Right Round", "International Love",
  "Hot in Herre", "Dilemma", "Ride wit Me", "Country Grammar",
  "Crank That", "Kiss Me Thru the Phone", "Pretty Boy Swag",
  "Black and Yellow", "See You Again", "Roll Up", "Work Hard Play Hard",
  "Panda", "Tiimmy Turner", "Praise the Lord (Da Shine)", "A$AP Forever",
  "1Train", "Peso", "Goldie", "Sundress",
  "XO Tour Llif3", "The Way Life Goes", "Money Longer", "20 Min",
  "Bad and Boujee", "Walk It Talk It", "Motorsport", "Stir Fry",
  "Mask Off", "Low Life", "March Madness", "Jumpman",
  "Rockstar", "Sunflower", "Congratulations", "Better Now",
  "Circles", "White Iverson", "I Fall Apart", "Psycho",
  "HUMBLE.", "Sicko Mode", "Mo Bamba", "Ransom",
  "Lucid Dreams", "All Girls Are the Same", "Robbery", "Bandit",
  "Moonwalking in Calabasas", "RAPSTAR", "Dior",
  "First Day Out", "Lifestyle", "Wasted", "Lemonade",
  "No Role Modelz", "Wet Dreamz", "Middle Child", "Power Trip",
  "A Lot", "Bank Account", "Savage Mode", "Glock in My Lap",
  "Hot", "Savage", "Body", "Cash Shit", "Captain Hook",
  "Say So", "Kiss Me More", "Need to Know", "Streets", "Woman",
  "Thotiana", "Rack City", "Loyal", "Ayo", "Gyalchester",
  "Walk It Like I Talk It", "Drip Too Hard", "My Dawg", "Yes Indeed",
  "Life Is Good", "Way 2 Sexy", "Wants and Needs",
  "Wait for U", "Major Distribution", "Pushin P", "Thought I Was Playing",
  "Sky", "Off the Grid", "Hurricane", "Jail", "Moon",
  "DONDA", "Jesus Walks", "Through the Wire", "Touch the Sky",

  // ==================== R&B / SOUL ====================
  "Blinding Lights", "After Hours", "Save Your Tears", "Sacrifice",
  "Kiss Land", "The Morning", "House of Balloons", "Wicked Games",
  "Best Part", "Come Through", "No Guidance", "Heat", "Drown",
  "Trip", "Exchange", "Come and See Me", "The London", "Slide",
  "Redbone", "That's What I Like", "Versace on the Floor", "Leave the Door Open",
  "Smokin Out the Window", "Skate", "Silk Sonic Intro",
  "Boo'd Up", "Trip", "Focus", "Better", "Damages",
  "Love Galore", "The Weekend", "Garden", "Good Days", "Kiss Me More",
  "Snooze", "Kill Bill", "Shirt", "Broken Clocks", "Love Deluxe",
  "No One", "If I Ain't Got You", "Fallin'", "Girl on Fire", "Empire State of Mind",
  "Halo", "Crazy in Love", "Drunk in Love", "Single Ladies", "Irreplaceable",
  "Lemonade", "Formation", "Freedom", "Sorry", "Love on Top",
  "Yeah!", "Confessions Part II", "My Boo", "Burn", "U Got It Bad", "Nice & Slow",
  "Untitled (How Does It Feel)", "Pony", "Bump N' Grind", "Ignition (Remix)",
  "End of the Road", "I'll Make Love to You", "On Bended Knee", "One Sweet Day",
  "No Scrubs", "Waterfalls", "Creep", "Don't Go Chasing Waterfalls",
  "Say My Name", "Jumpin' Jumpin'", "Bills Bills Bills", "Bootylicious",
  "We Belong Together", "Always Be My Baby", "Fantasy", "Hero",
  "Vision of Love", "Emotions", "Dreamlover", "Heartbreaker",
  "Let's Stay Together", "Tired of Being Alone", "How Can You Mend a Broken Heart",
  "Ain't No Sunshine", "Lean on Me", "Just the Two of Us", "Lovely Day",
  "Sexual Healing", "Let's Get It On", "What's Going On", "I Heard It Through the Grapevine",
  "Mercy Mercy Me", "Inner City Blues",
  "My Girl", "Just My Imagination", "Papa Was a Rollin' Stone",
  "I Want You Back", "ABC", "I'll Be There", "Rockin' Robin",
  "Signed Sealed Delivered", "For Once in My Life", "You Are the Sunshine of My Life",
  "At Last", "A Sunday Kind of Love",

  // ==================== COUNTRY ====================
  "Old Town Road", "Body Like a Back Road", "Meant to Be", "Die a Happy Man",
  "Cruise", "Wagon Wheel", "Tennessee Whiskey", "Dirt Road Anthem",
  "Before He Cheats", "Jesus Take the Wheel", "Blown Away", "Something in the Water",
  "Need You Now", "Speechless",
  "Jolene", "9 to 5", "I Will Always Love You", "Coat of Many Colors",
  "Friends in Low Places", "The Dance", "The Thunder Rolls", "If Tomorrow Never Comes",
  "Boot Scootin' Boogie", "Achy Breaky Heart",
  "Ring of Fire", "I Walk the Line", "Folsom Prison Blues", "Man in Black",
  "On the Road Again", "Blue Eyes Crying in the Rain", "Always on My Mind",
  "Mama Tried", "Okie from Muskogee", "Today I Started Loving You Again",
  "Your Cheatin' Heart", "Hey Good Lookin'", "I'm So Lonesome I Could Cry",
  "He Stopped Loving Her Today", "The Chair", "Amarillo by Morning",
  "Islands in the Stream", "The Gambler", "Lucille", "Coward of the County",
  "Take Me Home, Country Roads", "Thank God I'm a Country Boy",
  "Strawberry Wine", "Fancy", "She's in Love with the Boy",
  "Last Night", "Fast Car", "You Proof", "Wasted on You",
  "I Remember Everything", "Rich Men North of Richmond", "Try That in a Small Town",
  "Something in the Orange", "Chasin' You", "Cover Me Up",
  "Whiskey Glasses", "More Than My Hometown", "Sand in My Boots",
  "Tequila", "Beautiful Crazy", "One Thing at a Time",
  "I Ain't Worried", "Buy Dirt", "Beers on Me",
  "Fancy Like", "AA", "Broadway Girls",
  "The Bones", "10,000 Hours", "What Ifs", "Thinking 'Bout You",
  "Heartland", "Drink in My Hand", "Drunk on a Plane",
  "Springsteen", "Drunk on You", "Country Girl (Shake It for Me)",
  "Chicken Fried", "Free", "Knee Deep", "Cold Beer Calling My Name",

  // ==================== EDM / DANCE / ELECTRONIC ====================
  "Titanium", "Without You", "She Wolf", "Hey Mama", "Turn Down for What",
  "Levels", "Wake Me Up", "Faded", "Alone", "Darkside",
  "Something Just Like This", "Closer", "Roses", "Don't Let Me Down", "Paris",
  "Lean On", "Where Are Ü Now", "Cold Water", "Let Me Love You", "Light It Up",
  "This Is What You Came For", "We Found Love", "Feel So Close", "Sweet Nothing",
  "Summer", "How Deep Is Your Love", "I Gotta Feeling", "Boom Boom Pow",
  "The Time (Dirty Bit)", "Where Is the Love?",
  "Clarity", "Stay the Night", "Beautiful Now", "The Middle",
  "Don't You Worry Child", "Save the World", "Greyhound", "More Than You Know",
  "In the Name of Love", "Scared to Be Lonely", "So Far Away", "Animals",
  "Tremor", "Tsunami", "Epic", "Mammoth",
  "Strobe", "Ghosts 'n' Stuff", "I Remember", "Some Chords",
  "Sandstorm", "Better Off Alone", "Children", "Insomnia",
  "Blue (Da Ba Dee)", "Kernkraft 400", "Satisfaction", "Call on Me",
  "Sun Is Shining", "Cola", "Deep Down", "Praise You",
  "Right Here Right Now", "Star Guitar", "Galvanize", "Block Rockin' Beats",
  "Born Slippy", "Firestarter", "Breathe", "Smack My Bitch Up",
  "Around the World", "Da Funk", "Voyager", "Within",
  "Bangarang", "Scary Monsters and Nice Sprites", "First of the Year", "Cinema",
  "Sun & Moon", "On My Way Home", "You Got to Go", "Northern Soul",
  "Opus", "Reload", "Hey Baby", "Sweet Disposition",
  "Runaway (U & I)", "Sun & Moon", "Thing Called Love", "Another Chance",
  "Cola", "Nobody Cares", "Body", "Move Your Body",
  "Piece of Your Heart", "Remember", "Head & Heart", "Lasting Lover",
  "Flowers", "Miracle", "Turn Me On", "Latch",
  "White Noise", "You & Me", "Disclosure",
  "One Kiss", "Electricity", "Tidal Wave", "New Rules",
  "Finally", "Show Me Love", "No Limit", "Be My Lover",

  // ==================== LATIN / REGGAETON ====================
  "Despacito", "Mi Gente", "Dura", "Échame La Culpa",
  "Bailando", "Súbeme La Radio", "El Perdón", "Hero",
  "La Bicicleta", "Chantaje", "Waka Waka", "Hips Don't Lie",
  "Whenever Wherever", "She Wolf", "Loca", "Try Everything",
  "Taki Taki", "I Like It", "MIA", "China",
  "Con Calma", "Gasolina", "Dákiti", "La Noche de Anoche",
  "Yonaguni", "Moscow Mule", "Un Verano Sin Ti", "Me Porto Bonito",
  "Titi Me Pregunto", "Efecto", "Ojitos Lindos", "Callaíta",
  "Safaera", "Yo Perreo Sola", "La Canción", "Si Veo a Tu Mamá",
  "Te Boté", "Sech", "Otro Atardecer", "La Difícil",
  "Hawái", "MAMIII", "BESO", "TQG", "Shakira: Bzrp Music Sessions",
  "La Bebe", "Luna", "Tú No Vive Así",
  "Baila Conmigo", "El Favor", "X", "Con Altura",
  "Vivir Mi Vida", "Bailar", "On the Floor",
  "Livin' La Vida Loca", "She Bangs", "The Cup of Life",
  "Felices los 4", "Corazón", "Vente Pa' Ca", "El Amante",
  "Obsesión", "La Tortura", "Lento", "Criminal",
  "Pa Ti", "Lonely", "Agua",
  "MONACO", "WHERE SHE GOES", "Un x100to",

  // ==================== K-POP / J-POP / ASIAN POP ====================
  "Dynamite", "Butter", "Permission to Dance", "Boy with Luv", "Fake Love",
  "DNA", "Spring Day", "Blood Sweat & Tears", "Fire", "IDOL",
  "ON", "Black Swan", "Life Goes On", "Yet to Come", "Run BTS",
  "How You Like That", "Lovesick Girls", "Kill This Love", "DDU-DU DDU-DU", "Boombayah",
  "Pink Venom", "Shut Down", "Whistle", "Playing with Fire", "As If It's Your Last",
  "LALISA", "MONEY", "SOS", "ROCKSTAR", "On the Ground",
  "Solo", "Flower", "Cupid", "Eve Psyche & the Bluebeard's Wife",
  "APT.", "Mantra", "Like a Flower",
  "Super Shy", "OMG", "Attention", "Ditto", "Hype Boy",
  "ETA", "Cool with You", "Get Up", "Bubble Gum",
  "Next Level", "Savage", "Drama", "Supernova", "Better Things",
  "Love Dive", "After LIKE", "I AM", "Eleven", "HEYA",
  "Psycho", "Bad Boy", "Peek-a-Boo", "Red Flavor", "Russian Roulette",
  "Feel My Rhythm", "Queencard", "Nxde", "Tomboy", "LATATA",
  "Very Nice", "Don't Wanna Cry", "Super", "God of Music",
  "Growl", "Love Shot", "Tempo", "Monster", "Call Me Baby",
  "Fantastic Baby", "Bang Bang Bang", "Haru Haru", "Blue",
  "Ring Ding Dong", "Lucifer", "Sherlock", "View",
  "Gangnam Style", "Gentleman", "Daddy",
  "TT", "What Is Love?", "Cheer Up", "Fancy", "Feel Special",
  "Like Ooh-Ahh", "Dance the Night Away", "I Can't Stop Me",
  "God's Menu", "Back Door", "MANIAC", "S-Class", "LALALALA",
  "Chk Chk Boom", "Thunderous", "MIROH",
  "Gurenge", "Idol", "SPECIALZ", "Zankyosanka",
  "Shinzou wo Sasageyo", "Unravel", "Cruel Angel's Thesis",
  "Lemon", "Pretender", "Dry Flower", "KICK BACK",

  // ==================== ALTERNATIVE / INDIE ====================
  "Electric Feel", "Kids", "Time to Pretend", "Little Dark Age",
  "Pumped Up Kicks", "Sit Next to Me", "Houdini",
  "Take on Me", "Enjoy the Silence", "Just Can't Get Enough", "Personal Jesus",
  "Blue Monday", "True Faith", "Bizarre Love Triangle",
  "Don't Stop Believin'", "Separate Ways", "Open Arms",
  "Everybody Wants to Rule the World", "Shout", "Mad World",
  "Karma Chameleon", "Do You Really Want to Hurt Me",
  "Girls Just Want to Have Fun", "Time After Time", "True Colors",
  "Heat Waves", "Gooey", "Black Mambo", "Space Ghost Coast to Coast",
  "Sweater Weather", "Afraid", "Wiped Out!", "Daddy Issues",
  "Are You Bored Yet?", "Supalonely", "Miss You",
  "Do I Wanna Know?", "R U Mine?", "Fluorescent Adolescent", "505",
  "I Bet You Look Good on the Dancefloor", "Snap Out of It", "Why'd You Only Call Me When You're High?",
  "Somebody Else", "Love Me", "Robbers", "Chocolate",
  "The Sound", "It's Not Living (If It's Not with You)", "If You're Too Shy",
  "Obstacle 1", "Evil", "Slow Hands", "PDA", "Rest My Chemistry",
  "Two Door Cinema Club", "What You Know", "Undercover Martyn", "Sun",
  "Tongue Tied", "Shake Me Down", "Come a Little Closer", "Back Against the Wall",
  "Electric Love", "High Hopes", "Cocoon", "Best Friend",
  "Home", "Hey There Delilah", "1234",
  "The Less I Know the Better", "Let It Happen", "Feels Like We Only Go Backwards",
  "Eventually", "Borderline", "Lost in Yesterday", "Breathe Deeper",
  "Young Folks", "1901", "Lisztomania",
  "Skinny Love", "Re: Stacks", "Holocene", "Perth",
  "Stolen Dance", "Talk Too Much", "Lovesick", "Reckless",
  "Take Me Out", "No Cars Go", "Ready to Start", "Everything Now",
  "Dog Days Are Over", "Shake It Out", "Ship to Wreck", "Cosmic Love",
  "Under the Bridge", "Give It Away", "By the Way", "Scar Tissue",
  "Two Weeks", "Oblivion", "Genesis", "Venus Fly",
  "A-Punk", "Oxford Comma", "Unbelievers", "Harmony Hall",
  "Naive", "Rehab", "Valerie", "Back to Black",
  "You Know I'm No Good", "Tears Dry on Their Own", "Love Is a Losing Game",
  "Video Games", "Summertime Sadness", "Born to Die", "Young and Beautiful",
  "West Coast", "High by the Beach", "Doin' Time", "Venice Bitch",
  "Norman Fucking Rockwell", "Mariners Apartment Complex",

  // ==================== METAL / HARD ROCK ====================
  "Numb", "In the End", "Crawling", "Breaking the Habit", "What I've Done",
  "New Divide", "Somewhere I Belong", "One Step Closer", "Faint",
  "Chop Suey!", "Toxicity", "B.Y.O.B.", "Aerials", "Lonely Day",
  "Enter Sandman", "Nothing Else Matters", "Master of Puppets", "Fade to Black",
  "Seek & Destroy", "Wherever I May Roam", "The Unforgiven", "One",
  "Back in Black", "Thunderstruck", "Highway to Hell", "T.N.T.", "You Shook Me All Night Long",
  "Hells Bells", "For Those About to Rock", "Shoot to Thrill", "Dirty Deeds Done Dirt Cheap",
  "Walk", "Cowboys from Hell", "Cemetery Gates", "This Love", "Mouth for War",
  "Bodies", "Last Resort", "Scars", "Between Angels and Insects",
  "Down with the Sickness", "Stupify", "Inside the Fire", "Indestructible",
  "My Own Summer (Shove It)", "Change (In the House of Flies)", "Be Quiet and Drive",
  "Freak on a Leash", "Falling Away from Me", "Here to Stay", "Got the Life",
  "Before I Forget", "Duality", "Wait and Bleed", "Psychosocial", "Snuff",
  "The Devil in I", "Unsainted", "Sulfur", "Dead Memories",
  "Ace of Spades", "Overkill", "Killed by Death",
  "Hallowed Be Thy Name", "The Trooper", "Fear of the Dark", "Run to the Hills",
  "Raining Blood", "Angel of Death", "Seasons in the Abyss",
  "Peace Sells", "Holy Wars", "Tornado of Souls", "Symphony of Destruction",
  "Roots Bloody Roots", "Refuse/Resist", "Chaos A.D.",
  "Du Hast", "Sonne", "Ich Will", "Amerika",
  "Schism", "Lateralus", "Sober", "Forty Six & 2", "Ænema",
  "Killing in the Name", "Bulls on Parade", "Bombtrack", "Guerrilla Radio",
  "Prayer of the Refugee", "Savior", "Swing Life Away",
  "The Pretender", "Everlong", "My Hero", "Learn to Fly", "Best of You",
  "Monkey Wrench", "Times Like These", "Walk", "All My Life",
  "Under the Bridge", "Give It Away", "Dani California",

  // ==================== POP LEGENDS / CLASSICS ====================
  "Poker Face", "Bad Romance", "Just Dance", "Born This Way", "Alejandro",
  "Paparazzi", "Telephone", "The Edge of Glory", "Always Remember Us This Way",
  "Toxic", "Baby One More Time", "Oops!... I Did It Again", "Womanizer", "Gimme More",
  "Like a Prayer", "Material Girl", "Vogue", "Hung Up", "Ray of Light",
  "La Isla Bonita", "Papa Don't Preach", "Express Yourself", "Frozen",
  "Purple Rain", "When Doves Cry", "Let's Go Crazy", "Kiss", "1999",
  "Little Red Corvette", "Raspberry Beret", "Pop Life",
  "Respect", "Chain of Fools", "(You Make Me Feel Like) A Natural Woman",
  "I Will Always Love You", "Greatest Love of All", "I Wanna Dance with Somebody",
  "How Will I Know", "I'm Every Woman", "The Greatest Love of All",
  "What's Love Got to Do with It", "Private Dancer", "Simply the Best",
  "Rolling in the Deep", "Someone Like You", "Set Fire to the Rain", "Hello",
  "Skyfall", "When We Were Young", "Water Under the Bridge", "Send My Love",
  "Umbrella", "We Found Love", "Diamonds", "Work",
  "Wrecking Ball", "Party in the U.S.A.", "We Can't Stop", "The Climb",
  "Used to Be Young", "Midnight Sky", "Flowers",
  "Don't Speak", "Just a Girl", "It's My Life", "Hella Good",
  "MMMBop", "Where Is the Love?", "Beautiful Soul",
  "Genie in a Bottle", "What a Girl Wants", "Come On Over Baby", "Fighter",
  "Beautiful", "Dirrty", "Ain't No Other Man",
  "Since U Been Gone", "Behind These Hazel Eyes", "Because of You", "Breakaway",
  "Complicated", "Sk8er Boi", "I'm with You", "Girlfriend", "My Happy Ending",
  "A Thousand Miles", "Don't Let Me Get Me", "Who Knew", "So What",
  "Raise Your Glass", "Just Give Me a Reason", "What About Us",
  "Beautiful Day", "Unwritten", "Pocketful of Sunshine", "1000 Miles",
  "Mr. Jones", "Iris", "Slide", "Name",
  "Drops of Jupiter", "Meet Virginia", "Hey Soul Sister",
  "Smooth", "Maria Maria", "Supernatural",
  "Creep", "No Scrubs", "I Don't Want to Miss a Thing", "Truly Madly Deeply",
  "Torn", "I Love You Always Forever", "Lovefool",
  "Semi-Charmed Life", "Jumper", "How's It Going to Be",
  "Closing Time", "Steal My Sunshine", "Sex and Candy",
  "Barely Breathing", "Flagpole Sitta", "Inside Out",
  "Every Morning", "Fly", "Walkin' on the Sun",
  "All Star", "Accidentally in Love",
  "Ocean Eyes", "Lovely", "When the Party's Over", "Bury a Friend", "Bad Guy",
  "Happier Than Ever", "Therefore I Am", "Everything I Wanted", "My Future",
  "TV", "Goldwing", "NDA", "Lost Cause", "Your Power",
  "Daylight", "LUNCH", "BIRDS OF A FEATHER", "CHIHIRO",

  // ==================== MISCELLANEOUS VIRAL / THROWBACKS ====================
  "Never Gonna Give You Up", "Together Forever", "Take On Me",
  "Africa", "Separate Ways", "Don't Stop Believin'",
  "Toxic", "Mr. Brightside", "Somebody That I Used to Know",
  "I Gotta Feeling", "Payphone", "Maps", "Sugar", "Moves Like Jagger",
  "This Love", "She Will Be Loved", "Sunday Morning", "Harder to Breathe",
  "Wonderwall", "Creep", "Jolene", "Landslide", "Dreams",
  "Go Your Own Way", "The Chain", "Everywhere", "Little Lies",
  "Rhiannon", "Gold Dust Woman", "Sara", "Gypsy",
  "Don't Stop", "Tusk", "Hold Me",
  "Dancing Queen", "Mamma Mia", "Waterloo", "Gimme! Gimme! Gimme!",
  "S.O.S.", "Fernando", "The Winner Takes It All", "Knowing Me Knowing You",
  "Lay All Your Love on Me", "Does Your Mother Know", "Super Trouper",
  "Just Like Heaven", "Lovesong", "Friday I'm in Love", "Boys Don't Cry",
  "Pictures of You", "Close to Me", "Lullaby",
  "Love Will Tear Us Apart", "She's Lost Control", "Atmosphere",
  "Sweet Dreams", "Here Comes the Rain Again", "Would I Lie to You?",
  "Under Pressure", "Somebody to Love", "Don't Stop Me Now",
  "Space Oddity", "Heroes", "Let's Dance", "Starman", "Life on Mars?",
  "Changes", "Ziggy Stardust", "Rebel Rebel", "Ashes to Ashes",
  "Sledgehammer", "In Your Eyes", "Solsbury Hill",
  "Shout", "Everybody Wants to Rule the World", "Mad World", "Head Over Heels",
  "Take On Me", "The Sun Always Shines on T.V.",
  "Tainted Love", "Sex on Fire", "Use Somebody", "Somebody That I Used to Know",
  "Radioactive", "Demons", "Thunder", "Believer", "Natural",
  "Counting Stars", "Apologize", "Stop and Stare", "Good Life",
  "Stressed Out", "Heathens", "Ride", "Car Radio", "Chlorine",
  "My Blood", "Jumpsuit", "Nico and the Niners",
  "Fireflies", "Good Time", "Vanilla Twilight",
  "Budapest", "Let Her Go", "Riptide", "Home",
  "Ho Hey", "Stubborn Love", "Angela",
  "Little Talks", "Dirty Paws", "King and Lionheart",
  "Pompeii", "Flaws", "Bad Blood", "Things We Lost in the Fire",
  "I Will Wait", "The Cave", "Little Lion Man", "Sigh No More",
  "Wake Me Up When September Ends", "Boulevard of Broken Dreams", "Holiday",
  "American Idiot", "Basket Case", "When I Come Around", "Good Riddance",
  "21 Guns", "Jesus of Suburbia", "Brain Stew",
  "All the Small Things", "What's My Age Again?", "I Miss You", "Dammit",
  "The Rock Show", "First Date", "Feeling This",
  "In Too Deep", "Fat Lip", "Still Waiting", "Walking Disaster",
  "My Own Worst Enemy", "The Middle", "Sweetness",
  "Ocean Avenue", "Only One", "Rough Landing Holly",
  "Sugar We're Goin Down", "Thnks fr th Mmrs", "Dance Dance", "A Little Less Sixteen Candles",
  "I Write Sins Not Tragedies", "Nine in the Afternoon", "Lying Is the Most Fun",
  "Misery Business", "Decode", "That's What You Get", "Still into You",
  "Hard Times", "Rose-Colored Boy", "Fake Happy", "This Is Why",
  "Welcome to the Black Parade", "Helena", "I'm Not Okay", "Teenagers",
  "Famous Last Words", "The Ghost of You", "Na Na Na",
  "Bring Me to Life", "My Immortal", "Going Under",
  "Headstrong", "Bodies", "One Thing",
  "It's Not Over", "Home", "Kryptonite", "When Worlds Collide",
];
