export const mostVisitedNationalParksHints: string[] = [
  // All 63 US National Parks (same as main list items)
  "Great Smoky Mountains", "Zion", "Grand Canyon", "Yellowstone", "Rocky Mountain",
  "Yosemite", "Acadia", "Olympic", "Grand Teton", "Glacier",
  "Joshua Tree", "Cuyahoga Valley", "Indiana Dunes", "Gateway Arch", "Bryce Canyon",
  "Hot Springs", "New River Gorge", "Shenandoah", "Mount Rainier", "Arches",
  "Death Valley", "Hawaii Volcanoes", "Capitol Reef", "Sequoia", "Badlands",
  "Saguaro", "Canyonlands", "Mammoth Cave", "Everglades", "Glacier Bay",
  "Theodore Roosevelt", "Haleakala", "White Sands", "Kings Canyon", "Redwood",
  "Big Bend", "Petrified Forest", "Biscayne", "Crater Lake", "Wind Cave",
  "Mesa Verde", "Denali", "Carlsbad Caverns", "Great Sand Dunes", "Virgin Islands",
  "Kenai Fjords", "Lassen Volcanic", "Pinnacles", "Black Canyon of the Gunnison", "Channel Islands",
  "Congaree", "Guadalupe Mountains", "Voyageurs", "Great Basin", "Dry Tortugas",
  "Wrangell-St. Elias", "Katmai", "Isle Royale", "National Park of American Samoa", "Lake Clark",
  "Kobuk Valley", "North Cascades", "Gates of the Arctic",

  // National Monuments (NPS-managed)
  "Admiralty Island", "African Burial Ground", "Agate Fossil Beds", "Agua Fria",
  "Alibates Flint Quarries", "Aniakchak", "Avi Kwa Ame", "Aztec Ruins",
  "Bandelier", "Basin and Range", "Bears Ears", "Berryessa Snow Mountain",
  "Birmingham Civil Rights", "Booker T. Washington", "Browns Canyon", "Buck Island Reef",
  "Cabrillo", "California Coastal", "Camp Hale-Continental Divide", "Camp Nelson",
  "Canyon de Chelly", "Canyons of the Ancients", "Cape Krusenstern", "Capulin Volcano",
  "Carrizo Plain", "Casa Grande Ruins", "Cascade-Siskiyou", "Castillo de San Marcos",
  "Castle Clinton", "Castle Mountains", "Cedar Breaks", "Cesar E. Chavez",
  "Charles Young Buffalo Soldiers", "Chimney Rock", "Chiricahua", "Chuckwalla",
  "Colorado", "Craters of the Moon", "Devils Postpile", "Devils Tower",
  "Dinosaur", "Effigy Mounds", "El Malpais", "El Morro",
  "Florissant Fossil Beds", "Fort Frederica", "Fort Matanzas", "Fort McHenry",
  "Fort Monroe", "Fort Pulaski", "Fort Stanwix", "Fort Union",
  "Fossil Butte", "George Washington Birthplace", "George Washington Carver", "Giant Sequoia",
  "Gila Cliff Dwellings", "Gold Butte", "Governors Island", "Grand Canyon-Parashant",
  "Grand Portage", "Grand Staircase-Escalante", "Hagerman Fossil Beds", "Hanford Reach",
  "Hohokam Pima", "Hovenweep", "Ironwood Forest", "Jewel Cave",
  "John Day Fossil Beds", "Kasha-Katuwe Tent Rocks", "Katahdin Woods and Waters", "Lava Beds",
  "Little Bighorn Battlefield", "Marianas Trench", "Misty Fjords", "Mojave Trails",
  "Montezuma Castle", "Mount Saint Helens", "Muir Woods", "Natural Bridges",
  "Navajo", "Newberry", "Northeast Canyons and Seamounts", "Oregon Caves",
  "Organ Mountains-Desert Peaks", "Organ Pipe Cactus", "Papahanaumokuakea", "Petroglyph",
  "Pipe Spring", "Pipestone", "Pompeys Pillar", "Poverty Point",
  "Rainbow Bridge", "Rio Grande del Norte", "Rose Atoll", "Russell Cave",
  "Salinas Pueblo Missions", "San Gabriel Mountains", "San Juan Islands", "Sand to Snow",
  "Santa Rosa and San Jacinto Mountains", "Scotts Bluff", "Sonoran Desert", "Statue of Liberty",
  "Stonewall", "Sunset Crater Volcano", "Timpanogos Cave", "Tonto",
  "Tule Lake", "Tule Springs Fossil Beds", "Tuzigoot", "Upper Missouri River Breaks",
  "Vermilion Cliffs", "Virgin Islands Coral Reef", "Waco Mammoth", "Walnut Canyon",
  "Wupatki", "Yucca House",

  // National Recreation Areas (NPS-managed)
  "Amistad National Recreation Area", "Bighorn Canyon National Recreation Area",
  "Boston Harbor Islands National Recreation Area", "Chattahoochee River National Recreation Area",
  "Chickasaw National Recreation Area", "Curecanti National Recreation Area",
  "Delaware Water Gap National Recreation Area", "Gateway National Recreation Area",
  "Gauley River National Recreation Area", "Glen Canyon National Recreation Area",
  "Golden Gate National Recreation Area", "Lake Chelan National Recreation Area",
  "Lake Mead National Recreation Area", "Lake Meredith National Recreation Area",
  "Lake Roosevelt National Recreation Area", "Ross Lake National Recreation Area",
  "Santa Monica Mountains National Recreation Area", "Whiskeytown National Recreation Area",

  // National Seashores & Lakeshores
  "Assateague Island National Seashore", "Canaveral National Seashore",
  "Cape Cod National Seashore", "Cape Hatteras National Seashore",
  "Cape Lookout National Seashore", "Cumberland Island National Seashore",
  "Fire Island National Seashore", "Gulf Islands National Seashore",
  "Padre Island National Seashore", "Point Reyes National Seashore",
  "Indiana Dunes National Lakeshore", "Apostle Islands National Lakeshore",
  "Pictured Rocks National Lakeshore", "Sleeping Bear Dunes National Lakeshore",

  // National Parkways & Scenic Trails
  "Blue Ridge Parkway", "Natchez Trace Parkway", "George Washington Memorial Parkway",
  "John D. Rockefeller Jr. Memorial Parkway", "Appalachian National Scenic Trail",
  "Ice Age National Scenic Trail", "Potomac Heritage National Scenic Trail",

  // Other notable NPS units
  "Antietam National Battlefield", "Gettysburg National Military Park",
  "Yellowstone National Park", "Grand Canyon National Park",
  "Chesapeake and Ohio Canal National Historical Park",
  "Harpers Ferry National Historical Park",
  "Independence National Historical Park",
  "Lowell National Historical Park",
  "Manassas National Battlefield Park",
  "Shenandoah National Park",
  "Valley Forge National Historical Park",
];
