export const mostTranslatedBooksHints: string[] = [
  // Top 50 (same as items)
  "The Bible", "The Little Prince", "The Adventures of Pinocchio", "Dao De Jing", "The Pilgrim's Progress",
  "The Communist Manifesto", "Alice's Adventures in Wonderland", "Grimm's Fairy Tales", "Steps to Christ", "Don Quixote",
  "Andersen's Fairy Tales", "The Book of Mormon", "Asterix", "The Quran", "The Way to Happiness",
  "The Prophet", "The Upright Revolution", "The Adventures of Tintin", "Luther's Small Catechism", "The Imitation of Christ",
  "Harry Potter", "Winnie-the-Pooh", "The Diary of a Young Girl", "Das Kapital", "The Kon-Tiki Expedition",
  "Pippi Longstocking", "The Alchemist", "Diary of a Wimpy Kid", "Sophie's World", "The Adventures of Huckleberry Finn",
  "Nineteen Eighty-Four", "Through the Looking-Glass", "The Isha Upanishad", "The Tirukkural", "Kalevala",
  "Quo Vadis", "Uncle Tom's Cabin", "The Wonderful Adventures of Nils", "The Bhagavad Gita", "The Hobbit",
  "The Good Soldier Švejk", "The Lord of the Rings", "Things Fall Apart", "A Doll's House", "The Divine Comedy",
  "Seven Brief Lessons on Physics", "Never Let Me Go", "The Boy in the Striped Pyjamas", "The House at Pooh Corner", "Autobiography of a Yogi",

  // Additional well-known books for hints (ranks 51+)
  "Heidi", "Little Red Book", "Out Stealing Horses", "One Hundred Years of Solitude", "The Chronicles of Narnia",
  "The Bridge on the Drina", "The Stranger", "The Very Hungry Caterpillar", "The Da Vinci Code", "The Moomins",
  "Invisible Cities", "Atonement", "The Great Gatsby", "The Kite Runner", "Solaris",
  "A Series of Unfortunate Events", "The Leopard", "Hunger", "Miffy", "Paddington Bear",
  "A Song of Ice and Fire", "Discworld", "Perfume", "Anne of Green Gables", "Norwegian Wood",
  "The Tale of Peter Rabbit", "Totto-Chan: The Little Girl at the Window",
  "Gone With the Wind", "Atlas Shrugged", "Buddenbrooks", "The Pillars of the Earth", "The Tale of Genji",
  "Ender's Game", "The No. 1 Ladies' Detective Agency", "The Spiderwick Chronicles",

  // Classic literature
  "Pride and Prejudice", "Jane Eyre", "Wuthering Heights", "Sense and Sensibility", "Emma",
  "War and Peace", "Anna Karenina", "Crime and Punishment", "The Brothers Karamazov", "The Idiot",
  "Madame Bovary", "Les Misérables", "The Count of Monte Cristo", "The Three Musketeers", "Twenty Thousand Leagues Under the Sea",
  "Journey to the Center of the Earth", "Around the World in Eighty Days", "The Hunchback of Notre-Dame", "Germinal", "Nana",
  "Faust", "The Sorrows of Young Werther", "Siddhartha", "Steppenwolf", "Narcissus and Goldmund",
  "Metamorphosis", "The Trial", "The Castle", "In the Penal Colony", "Amerika",
  "Death in Venice", "Buddenbrooks", "The Magic Mountain", "Doctor Faustus", "Confessions of Felix Krull",
  "The Name of the Rose", "Foucault's Pendulum", "The Island of the Day Before", "Baudolino", "Numero Zero",
  "If on a winter's night a traveler", "Our Ancestors", "Baron in the Trees", "The Cloven Viscount", "The Nonexistent Knight",
  "Swann's Way", "In the Shadow of Young Girls in Flower", "The Guermantes Way", "Sodom and Gomorrah", "Time Regained",

  // 20th Century classics
  "The Old Man and the Sea", "For Whom the Bell Tolls", "A Farewell to Arms", "The Sun Also Rises", "A Moveable Feast",
  "Of Mice and Men", "The Grapes of Wrath", "East of Eden", "Cannery Row", "Travels with Charley",
  "To Kill a Mockingbird", "Go Set a Watchman", "In Cold Blood", "Breakfast at Tiffany's", "Other Voices Other Rooms",
  "Brave New World", "Point Counter Point", "Eyeless in Gaza", "Island", "Crome Yellow",
  "Animal Farm", "Homage to Catalonia", "Burmese Days", "Keep the Aspidistra Flying", "Coming Up for Air",
  "Fahrenheit 451", "The Martian Chronicles", "Something Wicked This Way Comes", "Dandelion Wine", "The Illustrated Man",
  "Slaughterhouse-Five", "Cat's Cradle", "Breakfast of Champions", "Player Piano", "Mother Night",
  "Catch-22", "Something Happened", "Good as Gold", "God Knows", "Picture This",
  "Lolita", "Pale Fire", "Ada or Ardor", "The Real Life of Sebastian Knight", "Invitation to a Beheading",
  "The Handmaid's Tale", "Oryx and Crake", "The Blind Assassin", "Alias Grace", "Cat's Eye",
  "Beloved", "Song of Solomon", "Sula", "The Bluest Eye", "Jazz",
  "One Flew Over the Cuckoo's Nest", "Sometimes a Great Notion", "The Electric Kool-Aid Acid Test",
  "On the Road", "Dharma Bums", "Big Sur", "Desolation Angels",
  "The Bell Jar", "Ariel", "The Colossus", "Johnny Panic and the Bible of Dreams",
  "Catcher in the Rye", "Nine Stories", "Franny and Zooey", "Raise High the Roof Beam Carpenters",
  "Lord of the Flies", "The Inheritors", "Pincher Martin", "Free Fall", "The Spire",
  "A Clockwork Orange", "Earthly Powers", "The Wanting Seed", "Honey for the Bears",

  // Contemporary fiction and non-fiction
  "The Da Vinci Code", "Angels & Demons", "Inferno", "Digital Fortress", "The Lost Symbol",
  "The Girl with the Dragon Tattoo", "The Girl Who Played with Fire", "The Girl Who Kicked the Hornet's Nest",
  "Gone Girl", "The Girl on the Train", "Big Little Lies", "Where the Crawdads Sing", "Little Fires Everywhere",
  "The Help", "The Secret Life of Bees", "Educated", "Becoming", "The Glass Castle",
  "Born a Crime", "I Know Why the Caged Bird Sings", "The Color Purple", "Their Eyes Were Watching God",
  "The Fault in Our Stars", "Looking for Alaska", "An Abundance of Katherines", "Paper Towns", "Turtles All the Way Down",
  "The Hunger Games", "Catching Fire", "Mockingjay", "Divergent", "Insurgent",
  "The Maze Runner", "The Scorch Trials", "The Death Cure",
  "Twilight", "New Moon", "Eclipse", "Breaking Dawn",
  "The Notebook", "A Walk to Remember", "Message in a Bottle", "Nights in Rodanthe", "The Last Song",
  "Project Hail Mary", "The Martian", "Weir's The Martian", "Artemis",
  "The Hitchhiker's Guide to the Galaxy", "The Restaurant at the End of the Universe", "Life the Universe and Everything",
  "Ready Player One", "Ready Player Two", "Ender's Shadow", "Speaker for the Dead",
  "A Brief History of Time", "The Grand Design", "Black Holes and Baby Universes",
  "Thinking Fast and Slow", "The Tipping Point", "Outliers", "Blink", "What the Dog Saw",
  "Sapiens", "Homo Deus", "21 Lessons for the 21st Century",
  "The Power of Now", "A New Earth", "Stillness Speaks",
  "How to Win Friends and Influence People", "Think and Grow Rich", "The 7 Habits of Highly Effective People",
  "The Secret", "The Power", "The Magic",
  "12 Rules for Life", "Beyond Order",
];
