// ~500 Wikipedia article titles for hints
export const mostVisitedWikipediaHints: string[] = [
  // Top 100 (the actual answers)
  "Cleopatra", "XXXTentacion", "2024 United States presidential election", "Kamala Harris", "Donald Trump",
  "Indian Premier League", "Deadpool & Wolverine", "Project 2025", "ChatGPT", "Elon Musk",
  "Taylor Swift", "2020 United States presidential election", "United States", "2024 Summer Olympics", "Joe Biden",
  "UEFA Euro 2024", "Lyle and Erik Menendez", "Cristiano Ronaldo", "Kalki 2898 AD", "J. D. Vance",
  "Sean Combs", "Robert F. Kennedy Jr.", "Dune: Part Two", "Sabrina Carpenter", "Liam Payne",
  "Griselda Blanco", "Jimmy Carter", "Pushpa 2: The Rule", "World War II", "Tim Walz",
  "Sex", "India", "Sydney Sweeney", "Mike Tyson", "House of the Dragon",
  "J. Robert Oppenheimer", "Alia Bhatt", "Chappell Roan", "Poor Things", "Oppenheimer",
  "Lionel Messi", "Saltburn", "Dune", "Premier League", "Barry Keoghan",
  "Inside Out 2", "Israel-Hamas war", "UEFA Champions League", "Imane Khelif", "Gladiator II",
  "Simone Biles", "Ariana Grande", "O. J. Simpson", "Bob Marley", "2016 United States presidential election",
  "Wicked", "Eminem", "Barack Obama", "Adolf Hitler", "Napoleon",
  "Elizabeth II", "Ryan Reynolds", "Blake Lively", "Civil War", "Russian invasion of Ukraine",
  "United Kingdom", "Timothee Chalamet", "LeBron James", "Michael Jackson", "Dua Lipa",
  "Charles III", "Zendaya", "Billie Eilish", "Jake Paul vs. Mike Tyson", "Alien: Romulus",
  "John F. Kennedy", "2024 ICC Men's T20 World Cup", "Elvis Presley", "Keir Starmer", "Kingdom of the Planet of the Apes",
  "Lady Gaga", "Travis Kelce", "Fallout", "The Bear", "Israel",
  "September 11 attacks", "Tulsi Gabbard", "Joker: Folie a Deux", "Lamine Yamal", "Richard Gadd",
  "Jeffrey Epstein", "Scarlett Johansson", "WrestleMania XL", "Twisters", "Yellowstone",
  "Wicked the musical", "Nikki Haley", "Glen Powell", "Madame Web", "Jake Paul",
  // 101-500 additional well-visited Wikipedia articles
  "Jennifer Lopez", "2026 FIFA World Cup", "Real Madrid CF", "Australia",
  "Keanu Reeves", "Ronald Reagan", "Dwayne Johnson", "Patrick Mahomes",
  "Russia", "Amy Winehouse", "Beetlejuice Beetlejuice", "World War I",
  "Baby Reindeer", "Ryan Gosling", "Manchester United F.C.",
  "Tom Cruise", "Kylian Mbappe", "Bruce Willis", "Vladimir Putin",
  "China", "Caitlin Clark", "Emma Stone", "Nicole Kidman", "Japan",
  "Anne Hathaway", "Cillian Murphy", "Iran", "New York City",
  "Albert Einstein", "Jeffrey Dahmer", "Michael Jordan",
  "Queen Victoria", "The Eras Tour", "Kendrick Lamar", "Singapore",
  "Clint Eastwood", "Canada", "Liverpool F.C.", "Virat Kohli",
  "Kanye West", "Franklin D. Roosevelt", "George W. Bush",
  "Abraham Lincoln", "Bill Clinton", "Arnold Schwarzenegger",
  "Tom Brady", "Angelina Jolie", "Leonardo DiCaprio",
  "Ben Affleck", "Snoop Dogg", "Alexander the Great",
  "Game of Thrones", "Novak Djokovic", "Turkey", "Celine Dion",
  "MrBeast", "Germany", "Selena Gomez", "Eurovision Song Contest 2024",
  "Robin Williams", "Robert F. Kennedy", "Beyonce", "Muhammad Ali",
  "Bob Dylan", "FC Barcelona", "The Holocaust", "Vietnam War",
  "Narendra Modi", "Brad Pitt", "Pakistan", "Bangladesh",
  "Freddie Mercury", "Mahatma Gandhi", "Taiwan",
  "Charli XCX", "Bridgerton", "American Civil War",
  "Benjamin Netanyahu", "Interstellar", "Robert Downey Jr.",
  "Ottoman Empire", "France", "Philippines", "Olivia Rodrigo",
  "Netflix", "George Washington", "Jesus", "Periodic table",
  "Lewis Hamilton", "Maggie Smith", "Tupac Shakur",
  "Joseph Stalin", "Marilyn Monroe", "Rihanna",
  "Winston Churchill", "Katy Perry", "Henry VIII",
  "Carlos Alcaraz", "Joaquin Phoenix", "Jude Bellingham",
  "Catherine, Princess of Wales", "Artificial intelligence",
  "Mark Wahlberg", "English language", "Drake",
  "Marvel Cinematic Universe", "Justin Bieber", "Steve Jobs",
  "Nicolas Cage", "Julia Roberts", "Henry Cavill",
  "South Africa", "The Beatles", "Jennifer Aniston",
  "Diana, Princess of Wales", "Richard Nixon",
  "Jeff Bezos", "Roman Empire", "Theodore Roosevelt",
  "Post Malone", "Jason Momoa", "Saudi Arabia",
  "Prince", "Solar eclipse", "David Bowie", "Florence Pugh",
  "Madonna", "Syrian civil war", "Stephen Curry", "Lana Del Rey",
  "Kobe Bryant", "Pedro Pascal", "Julius Caesar",
  "Denzel Washington", "John Cena", "Rafael Nadal",
  "Kim Kardashian", "Tom Hanks", "Hugh Jackman",
  "Arsenal F.C.", "Tom Holland", "Grey's Anatomy",
  "Linkin Park", "Margot Robbie", "Alexei Navalny",
  "Mexico", "Pablo Escobar", "Brazil", "Demi Moore",
  "Shohei Ohtani", "Christopher Nolan", "Dark web",
  "Miley Cyrus", "Chris Hemsworth", "Spain",
  "Kevin Costner", "Neymar", "Hong Kong",
  "Stephen Hawking", "Harry Potter", "North Korea",
  "London", "Adam Sandler", "Hezbollah",
  "Bradley Cooper", "Zac Efron", "Emmanuel Macron",
  "Copa America", "Greek alphabet", "Apple Inc.",
  "Max Verstappen", "Michael Phelps", "David Beckham",
  "Telegram", "Syria", "Martin Luther King Jr.",
  "Climate change", "COVID-19 pandemic", "Bitcoin",
  "SpaceX", "Tesla", "TikTok", "YouTube",
  "Facebook", "Twitter", "Instagram", "Wikipedia",
  "Google", "Amazon", "Microsoft", "Eiffel Tower",
  "Taj Mahal", "Great Wall of China", "Statue of Liberty",
  "Mount Everest", "Grand Canyon", "Yellowstone",
  "Moon", "Mars", "Sun", "Solar System",
  "Black hole", "DNA", "Evolution", "Quantum mechanics",
  "Theory of relativity", "Gravity", "Atom",
  "Democracy", "Communism", "Capitalism", "Fascism",
  "United Nations", "NATO", "European Union",
  "Africa", "Asia", "Europe", "South America",
  "Antarctica", "Arctic", "Pacific Ocean", "Atlantic Ocean",
];
