export const mostCommonPhobiasHints: string[] = [
  // === Top 50 (answers) ===
  "Arachnophobia", "Ophidiophobia", "Acrophobia", "Aerophobia", "Cynophobia",
  "Astraphobia", "Trypanophobia", "Agoraphobia", "Claustrophobia", "Glossophobia",
  "Mysophobia", "Hemophobia", "Thanatophobia", "Nyctophobia", "Aquaphobia",
  "Entomophobia", "Emetophobia", "Dentophobia", "Trypophobia", "Pyrophobia",
  "Coulrophobia", "Zoophobia", "Atychiphobia", "Nosophobia", "Xenophobia",
  "Necrophobia", "Nosocomephobia", "Monophobia", "Ornithophobia", "Ailurophobia",
  "Thalassophobia", "Tokophobia", "Philophobia", "Iatrophobia", "Haphephobia",
  "Enochlophobia", "Somniphobia", "Gamophobia", "Autophobia", "Chronophobia",
  "Decidophobia", "Pediophobia", "Ombrophobia", "Telephonophobia", "Ergophobia",
  "Pogonophobia", "Megalophobia", "Omphalophobia", "Nomophobia",
  "Hippopotomonstrosesquippedaliophobia",
  // === Additional phobias (not in top 50) ===
  "Ablutophobia", "Achluophobia", "Acousticophobia", "Agliophobia", "Aichmophobia",
  "Algophobia", "Amaxophobia", "Androphobia", "Anginophobia", "Anthophobia",
  "Anthropophobia", "Apeirophobia", "Apiphobia", "Arithmophobia", "Astrophobia",
  "Atelophobia", "Aulophobia", "Automatonophobia", "Bacteriophobia", "Barophobia",
  "Basophobia", "Bathmophobia", "Bathophobia", "Batrachophobia", "Bibliophobia",
  "Botanophobia", "Brontophobia", "Bufonophobia", "Cacophobia", "Cainophobia",
  "Carcinophobia", "Cardiophobia", "Catoptrophobia", "Cenophobia", "Ceraunophobia",
  "Chaetophobia", "Chemophobia", "Cherophobia", "Chionophobia", "Chiroptophobia",
  "Chromophobia", "Cibophobia", "Coimetrophobia", "Coprophobia", "Cremnophobia",
  "Cyberphobia", "Demophobia", "Demonophobia", "Dendrophobia", "Dermatophobia",
  "Didaskaleinophobia", "Dikephobia", "Dipsophobia", "Domatophobia", "Doraphobia",
  "Dromophobia", "Dystychiphobia", "Ecclesiophobia", "Eisoptrophobia", "Electrophobia",
  "Eleutherophobia", "Ephebiphobia", "Equinophobia", "Frigophobia", "Galeophobia",
  "Gelotophobia", "Geniophobia", "Genophobia", "Genuphobia", "Gerascophobia",
  "Gerontophobia", "Globophobia", "Graphophobia", "Gynophobia", "Hadephobia",
  "Halitophobia", "Hedonophobia", "Heliophobia", "Helminthophobia", "Herpetophobia",
  "Hierophobia", "Hodophobia", "Hydrophobia", "Hygrophobia", "Hylophobia",
  "Hypnophobia", "Ichthyophobia", "Kainolophobia", "Kakorrhaphiophobia",
  "Katagelophobia", "Kenophobia", "Koumpounophobia", "Lachanophobia",
  "Lepidopterophobia", "Leukophobia", "Ligyrophobia", "Lilapsophobia",
  "Limnophobia", "Lockiophobia", "Logophobia", "Lygophobia", "Mageirocophobia",
  "Mechanophobia", "Melanophobia", "Melissophobia", "Microphobia", "Mottephobia",
  "Musophobia", "Myrmecophobia", "Nebulaphobia", "Neophobia", "Noctiphobia",
  "Obesophobia", "Octophobia", "Odontophobia", "Olfactophobia", "Ophthalmophobia",
  "Optophobia", "Osmophobia", "Panophobia", "Papyrophobia", "Parasitophobia",
  "Paraskavedekatriaphobia", "Pathophobia", "Peccatiphobia", "Pediculophobia",
  "Pentheraphobia", "Pharmacophobia", "Phasmophobia", "Phengophobia", "Phobophobia",
  "Phonophobia", "Photophobia", "Plutophobia", "Pnigophobia", "Politicophobia",
  "Prosophobia", "Pteromerhanophobia", "Pupaphobia", "Radiophobia", "Ranidaphobia",
  "Rhytiphobia", "Samhainophobia", "Sarmassophobia", "Satanophobia", "Sciophobia",
  "Scotophobia", "Selachophobia", "Selenophobia", "Siderodromophobia",
  "Sociophobia", "Spectrophobia", "Spheksophobia", "Stasiphobia", "Stenophobia",
  "Symmetrophobia", "Tachophobia", "Technophobia", "Tetraphobia", "Thermophobia",
  "Tonitrophobia", "Topophobia", "Traumatophobia", "Triskaidekaphobia",
  "Uranophobia", "Vaccinophobia", "Venustraphobia", "Verbophobia", "Verminophobia",
  "Vestiphobia", "Xanthophobia", "Zelophobia", "Wiccaphobia",
  // More phobias
  "Scoleciphobia", "Rupophobia", "Symbolophobia",
  "Rhypophobia", "Sitophobia", "Scopophobia", "Sinistrophobia",
  "Soteriophobia", "Stasibasiphobia", "Stygiophobia", "Suriphobia",
  "Syngenesophobia", "Tabophobia", "Tapinophobia", "Teratophobia",
  "Testophobia", "Textophobia", "Theophobia", "Tocophobia",
  "Tomophobia", "Toxiphobia", "Tremophobia",
  "Tropophobia", "Urophobia", "Vitricophobia",
  "Amychophobia", "Anemophobia", "Angrophobia",
  "Argyrophobia", "Arsonphobia", "Asymmetriphobia",
  "Athazagoraphobia", "Ataxophobia", "Bacillophobia",
  "Cancerophobia", "Carnophobia", "Catapedaphobia", "Cnidophobia",
  "Coitophobia", "Contreltophobia", "Crystallophobia", "Deipnophobia",
  "Dementophobia", "Ecophobia",
  "Elurophobia", "Eosophobia", "Epistaxiophobia", "Febriphobia",
  "Francophobia", "Geliophobia", "Gephyrophobia", "Germanophobia",
  "Gymnophobia", "Hamartophobia", "Heresyphobia", "Heterophobia",
  "Homichlophobia", "Homophobia", "Hyalophobia", "Hypegiaphobia",
  "Kainophobia",
  "Kleptophobia", "Koniophobia", "Kopophobia", "Laliophobia",
  "Levophobia", "Macrophobia", "Maniaphobia",
  "Meningitophobia", "Menophobia", "Merinthophobia", "Metallophobia",
  "Metathesiophobia", "Mnemophobia", "Molysomophobia",
  "Motorphobia", "Mythophobia", "Myxophobia", "Nucleomituphobia",
  "Ochophobia", "Oikophobia",
  "Oneirophobia", "Onomatophobia", "Opiophobia",
  "Ouranophobia", "Pagophobia",
  "Panthophobia", "Pedophobia", "Peladophobia", "Peniaphobia",
  "Phagophobia", "Phalacrophobia", "Philemaphobia",
  "Phronemophobia", "Pluviophobia", "Poinephobia",
  "Ponophobia", "Potamophobia", "Proctophobia", "Psellismophobia",
  "Pteronophobia", "Pyrexiophobia",
  // === "Fear of X" descriptions for answer items ===
  "Fear of Spiders", "Fear of Snakes", "Fear of Heights", "Fear of Flying",
  "Fear of Dogs", "Fear of Thunder", "Fear of Lightning", "Fear of Needles",
  "Fear of Open Spaces", "Fear of Enclosed Spaces", "Fear of Public Speaking",
  "Fear of Germs", "Fear of Blood", "Fear of Death", "Fear of the Dark",
  "Fear of Water", "Fear of Insects", "Fear of Vomiting", "Fear of Dentists",
  "Fear of Holes", "Fear of Fire", "Fear of Clowns", "Fear of Animals",
  "Fear of Failure", "Fear of Disease", "Fear of Strangers", "Fear of Dead Things",
  "Fear of Hospitals", "Fear of Being Alone", "Fear of Birds", "Fear of Cats",
  "Fear of the Ocean", "Fear of Childbirth", "Fear of Love", "Fear of Doctors",
  "Fear of Being Touched", "Fear of Crowds", "Fear of Sleep", "Fear of Marriage",
  "Fear of Isolation", "Fear of Time", "Fear of Decisions", "Fear of Dolls",
  "Fear of Rain", "Fear of Phone Calls", "Fear of Work", "Fear of Beards",
  "Fear of Large Objects", "Fear of Belly Buttons", "Fear of No Phone",
  "Fear of Long Words",
  // === "Fear of X" descriptions for NON-answer phobias ===
  "Fear of Bathing", "Fear of Pain", "Fear of Sharp Objects",
  "Fear of Driving", "Fear of Men", "Fear of Flowers",
  "Fear of People", "Fear of Infinity", "Fear of Bees",
  "Fear of Numbers", "Fear of Robots", "Fear of Bacteria",
  "Fear of Depth", "Fear of Frogs", "Fear of Books",
  "Fear of Plants", "Fear of Toads", "Fear of Ugliness",
  "Fear of Novelty", "Fear of Cancer", "Fear of the Heart",
  "Fear of Mirrors", "Fear of Poop",
  "Fear of Chemicals", "Fear of Happiness", "Fear of Snow",
  "Fear of Bats", "Fear of Color", "Fear of Food",
  "Fear of Cemeteries", "Fear of Trees",
  "Fear of Skin", "Fear of Learning", "Fear of Justice",
  "Fear of Alcohol", "Fear of Home", "Fear of Speed",
  "Fear of Electricity", "Fear of Freedom",
  "Fear of Teenagers", "Fear of Horses", "Fear of Cold",
  "Fear of Sharks", "Fear of Laughing", "Fear of Chins",
  "Fear of Sex", "Fear of Knees", "Fear of Aging",
  "Fear of the Elderly", "Fear of Balloons", "Fear of Writing",
  "Fear of Women", "Fear of Bad Breath",
  "Fear of Pleasure", "Fear of the Sun", "Fear of Worms",
  "Fear of Reptiles", "Fear of Religion", "Fear of Travel",
  "Fear of Swallowing", "Fear of Baldness", "Fear of Kissing",
  "Fear of Thinking", "Fear of Crossing Bridges",
  "Fear of Nudity", "Fear of Sinning",
  "Fear of Fog", "Fear of Ice", "Fear of Everything",
  "Fear of Children", "Fear of Poverty",
  "Fear of Dreams", "Fear of Stars",
  "Fear of Rivers", "Fear of Fevers",
  "Fear of Strings", "Fear of Metal", "Fear of Change",
  "Fear of Memory", "Fear of Contamination",
  "Fear of Vehicles", "Fear of Myths", "Fear of Slime",
  "Fear of Nuclear Weapons",
  "Fear of Buttons", "Fear of Vegetables",
  "Fear of Butterflies", "Fear of Moths",
  "Fear of Mice", "Fear of Ants",
  "Fear of Technology", "Fear of the Number Four",
  "Fear of the Number Thirteen", "Fear of Gravity",
  "Fear of Stings", "Fear of Dust",
  "Fear of Fatigue", "Fear of Speaking",
  "Fear of Surgery", "Fear of Hurricanes",
  "Fear of Cooking", "Fear of Darkness",
  "Fear of Phobias", "Fear of Noise", "Fear of Light",
  "Fear of Wealth", "Fear of Choking",
  "Fear of Satan", "Fear of Shadows",
  "Fear of Ghosts", "Fear of Wasps",
  "Fear of Stillness", "Fear of Trains",
  "Fear of the Left", "Fear of the Right",
  "Fear of Madness", "Fear of Nosebleeds",
  "Fear of Witchcraft", "Fear of Jealousy",
  "Fear of Clothing", "Fear of Heresy",
  "Fear of Dizziness", "Fear of Glass",
  "Fear of Responsibility",
  "Fear of Friday the 13th",
  "Fear of Being Forgotten",
  "Fear of Disorder",
  "Fear of Asymmetry", "Fear of Scratching",
  "Fear of Wind", "Fear of Anger",
  "Fear of Silver", "Fear of Arson",
  "Fear of Meningitis", "Fear of Menstruation",
];
