export const mostDangerousJobsHints: string[] = [
  // === Top 50 (answers) ===
  "Logging Workers",
  "Aircraft Pilots and Flight Engineers",
  "Roofers",
  "Fishing and Hunting Workers",
  "Structural Iron and Steel Workers",
  "Refuse and Recyclable Material Collectors",
  "Helpers, Construction Trades",
  "Farmers, Ranchers, and Agricultural Managers",
  "Heavy and Tractor-Trailer Truck Drivers",
  "Power Line Installers and Repairers",
  "Mining Machine Operators",
  "Grounds Maintenance Workers",
  "Construction Laborers",
  "Operating Engineers and Construction Equipment Operators",
  "First-Line Supervisors of Construction Workers",
  "Electricians",
  "Industrial Machinery Mechanics",
  "Maintenance and Repair Workers",
  "Delivery Truck Drivers",
  "Painters, Construction and Maintenance",
  "Police Officers",
  "Firefighters",
  "Carpenters",
  "Plumbers, Pipefitters, and Steamfitters",
  "First-Line Supervisors of Mechanics",
  "Industrial Truck and Tractor Operators",
  "Automotive Service Technicians",
  "Welders, Cutters, and Brazers",
  "Highway Maintenance Workers",
  "Taxi Drivers and Chauffeurs",
  "Bus Drivers",
  "Logging Equipment Operators",
  "Crane and Tower Operators",
  "Derrick, Rotary Drill, and Service Unit Operators",
  "Hoist and Winch Operators",
  "Explosives Workers and Blasters",
  "Underground Mining Machine Operators",
  "Oil and Gas Extraction Workers",
  "First-Line Supervisors of Farming Workers",
  "Forestry Workers",
  "Animal Slaughterers and Meat Packers",
  "Cement Masons and Concrete Finishers",
  "Drywall Installers and Tapers",
  "Sheet Metal Workers",
  "Glaziers",
  "Septic Tank Servicers and Sewer Pipe Cleaners",
  "Earth Drillers",
  "Hazardous Materials Removal Workers",
  "Ambulance Drivers and Attendants",
  "Correctional Officers",
  // === Additional job titles (not in top 50) ===
  // -- Construction & Trades --
  "Brickmasons and Blockmasons", "Stonemasons", "Tile and Stone Setters",
  "Insulation Workers", "Paving Equipment Operators", "Pile Driver Operators",
  "Plasterers and Stucco Masons", "Reinforcing Iron and Rebar Workers",
  "Terrazzo Workers and Finishers", "Boilermakers", "Elevator Installers and Repairers",
  "Fence Erectors", "Rail-Track Laying and Maintenance Equipment Operators",
  "Riggers", "Solar Panel Installers", "Wind Turbine Technicians",
  "Telecommunications Line Installers", "Pipefitters", "Steamfitters",
  "HVAC Mechanics and Installers", "Millwrights", "Mobile Heavy Equipment Mechanics",
  "Outdoor Power Equipment Mechanics", "Signal and Track Switch Repairers",
  // -- Transportation --
  "Locomotive Engineers", "Railroad Conductors", "Railroad Brake Operators",
  "Ship Engineers", "Ship and Boat Captains", "Sailors and Marine Oilers",
  "Motorboat Operators", "Bridge and Lock Tenders", "Parking Attendants",
  "Traffic Technicians", "Transportation Inspectors", "Air Traffic Controllers",
  "Airfield Operations Specialists", "Flight Attendants", "Airline Pilots",
  "Commercial Pilots", "Helicopter Pilots", "Cargo and Freight Agents",
  "Dispatchers", "Freight Movers", "Material Moving Workers",
  "Conveyor Operators", "Loading Machine Operators",
  // -- Emergency & Protective Services --
  "Detectives and Criminal Investigators", "Fish and Game Wardens",
  "Parking Enforcement Workers", "Transit Police", "Fire Inspectors",
  "Forest Fire Inspectors", "Forest Firefighters", "Wildland Firefighters",
  "Emergency Medical Technicians", "Paramedics", "Lifeguards",
  "Crossing Guards", "Security Guards", "Private Detectives and Investigators",
  "Bailiffs", "Animal Control Workers", "Probation Officers",
  "TSA Screeners", "Border Patrol Agents", "US Marshals",
  // -- Agriculture & Nature --
  "Farmworkers and Laborers", "Nursery Workers", "Agricultural Inspectors",
  "Graders and Sorters of Agricultural Products", "Animal Breeders",
  "Veterinary Assistants", "Pesticide Handlers and Sprayers",
  "Tree Trimmers and Pruners", "Fallers", "Log Graders and Scalers",
  "Forest and Conservation Technicians", "Park Rangers", "Soil Scientists",
  "Conservation Scientists", "Environmental Compliance Inspectors",
  "Fish Hatchery Workers", "Arborists", "Beekeepers",
  // -- Mining & Extraction --
  "Continuous Mining Machine Operators", "Mine Cutting Machine Operators",
  "Rock Splitters", "Roof Bolters", "Petroleum Engineers",
  "Geological Technicians", "Mine Safety Engineers", "Quarry Workers",
  "Blasters", "Core Drillers", "Well Drillers",
  // -- Manufacturing & Industrial --
  "Foundry Workers", "Furnace Operators", "Heat Treating Equipment Operators",
  "Forging Machine Operators", "Metal Pourers and Casters",
  "Molding Machine Operators", "Cutting Machine Operators",
  "Grinding Machine Operators", "Lathe Operators", "Milling Machine Operators",
  "Punch Press Operators", "Rolling Machine Operators", "Sawing Machine Operators",
  "Woodworking Machine Operators", "Chemical Plant Operators",
  "Chemical Equipment Operators", "Petroleum Pump Operators",
  "Water Treatment Plant Operators", "Power Plant Operators",
  "Nuclear Power Reactor Operators", "Stationary Engineers",
  "Packaging Machine Operators", "Food Batchmakers",
  "Textile Machine Operators", "Printing Press Operators",
  "Laundry Workers", "Dry Cleaning Workers",
  // -- Office & Service (low risk for contrast) --
  "Accountants", "Administrative Assistants", "Bank Tellers", "Cashiers",
  "Customer Service Representatives", "Data Entry Clerks", "Dental Hygienists",
  "Financial Analysts", "Graphic Designers", "Human Resources Specialists",
  "Insurance Claims Clerks", "Librarians", "Market Research Analysts",
  "Paralegals", "Pharmacists", "Photographers", "Real Estate Agents",
  "Receptionists", "Social Workers", "Software Developers",
  "Teachers", "Technical Writers", "Translators", "Travel Agents",
  "Web Developers", "Writers and Authors",
  // -- Healthcare --
  "Registered Nurses", "Licensed Practical Nurses", "Nursing Assistants",
  "Home Health Aides", "Dental Assistants", "Medical Assistants",
  "Pharmacy Technicians", "Physical Therapists", "Occupational Therapists",
  "Respiratory Therapists", "Radiologic Technicians", "Surgical Technologists",
  "Phlebotomists", "Emergency Room Technicians", "Medical Laboratory Technicians",
  // -- Other dangerous/physical jobs --
  "Commercial Divers", "Stunt Performers", "Bomb Disposal Technicians",
  "Smokejumpers", "High-Rise Window Cleaners", "Steeplejacks",
  "Ironworkers", "Linemen", "Cell Tower Climbers",
  "Underwater Welders", "Demolition Workers", "Asbestos Abatement Workers",
  "Lead Abatement Workers", "Nuclear Decontamination Technicians",
  "Pyrotechnicians", "Test Pilots", "Crop Dusters",
  "Bull Riders", "Rodeo Cowboys", "Lumberjacks",
  "Deep Sea Fishermen", "Crab Fishermen", "Alaskan Fishermen",
  "Mine Rescue Workers", "Disaster Response Workers",
  // -- General labor --
  "Janitors and Cleaners", "Landscapers", "Warehouse Workers",
  "Dock Workers", "Longshoremen", "Baggage Handlers",
  "Package Handlers", "Stockers", "Forklift Operators",
  "Hand Laborers", "Construction Helpers", "Roustabouts",
  "Deckhands", "Stagehands", "Movers",
  // -- Specialty --
  "Chimney Sweeps", "Pest Control Workers", "Locksmiths",
  "Couriers and Messengers", "Meter Readers", "Mail Carriers",
  "Refuse Collectors", "Street Sweeper Operators", "Snow Plow Operators",
  "Tow Truck Drivers", "Armored Car Drivers", "Ice Road Truckers",
  "Hotshot Drivers", "Tanker Truck Drivers", "Flatbed Truck Drivers",
  "Auto Body Repairers", "Tire Repairers", "Bicycle Repairers",
  "Small Engine Mechanics", "Marine Mechanics", "Aircraft Mechanics",
  "Avionics Technicians", "Railroad Car Repairers",
  "Electric Motor Repairers", "Transformer Repairers",
  "Computer Repair Technicians", "Appliance Repairers",
  "Coin Machine Servicers", "Musical Instrument Tuners",
];
