export const mostFollowedTwitterHints: string[] = [
  // === TOP 100 (actual answers) ===
  "Elon Musk", "Barack Obama", "Donald Trump", "Narendra Modi", "Cristiano Ronaldo",
  "Rihanna", "NASA", "Justin Bieber", "Katy Perry", "Taylor Swift",
  "Lady Gaga", "Kim Kardashian", "YouTube", "Virat Kohli", "Bill Gates",
  "Ellen DeGeneres", "CNN", "X (Twitter)", "CNN Breaking News", "Neymar",
  "Selena Gomez", "PMO India", "ESPN", "The New York Times", "UEFA Champions League",
  "BBC Breaking News", "Real Madrid CF", "LeBron James", "Justin Timberlake", "BTS",
  "FC Barcelona", "NBA", "Shakira", "Premier League", "Amitabh Bachchan",
  "BTS Official", "Akshay Kumar", "Demi Lovato", "PlayStation", "Jimmy Fallon",
  "Britney Spears", "Salman Khan", "BBC World News", "SportsCenter", "SpaceX",
  "Miley Cyrus", "Shah Rukh Khan", "Sachin Tendulkar", "Manchester United FC", "Joe Biden",
  "Mohamed Salah", "Fabrizio Romano", "Pope Leo XIV", "Fortnite", "ABC News",
  "Gerard Piqué", "Manchester City", "Ed Sheeran", "Al Arabiya", "Felipe Neto",
  "Netflix France", "Ibai Llanos", "The Associated Press", "Donald Trump Jr.", "Binance",
  "Rafael Nadal", "Al-Waleed bin Talal", "Kylian Mbappé", "Beyoncé", "BBC News UK",
  "Diddy", "Sports", "Tim Cook", "The Times of India", "Billboard",
  "Nintendo of America", "EXO", "Microsoft", "Netflix Thailand", "BT21",
  "Tucker Carlson", "ENHYPEN", "CGTN", "World Health Organization", "Jair Bolsonaro",
  "Formula 1", "Indian National Congress", "China Xinhua News", "HuffPost", "The Guardian",
  "Changpeng Zhao", "Programa Pânico", "TED Talks", "Fantástico", "BLACKPINK",
  "Russell Brand", "Emmanuel Macron", "Serena Williams", "Andrés Manuel López Obrador", "Niall Horan",

  // === MUSICIANS / POP STARS ===
  "Ariana Grande", "Bruno Mars", "Eminem", "Drake", "Kanye West", "Travis Scott",
  "Cardi B", "Nicki Minaj", "Post Malone", "Billie Eilish", "Olivia Rodrigo", "Harry Styles",
  "One Direction", "The Weeknd", "Doja Cat", "Lizzo", "Dua Lipa", "Charlie Puth",
  "Shawn Mendes", "Camila Cabello", "Halsey", "Lana Del Rey", "Sam Smith", "Adele",
  "Bad Bunny", "J Balvin", "Daddy Yankee", "Ozuna", "Maluma", "Anuel AA",
  "Rosalía", "Karol G", "Becky G", "Luis Fonsi", "Enrique Iglesias",
  "Pitbull", "Marc Anthony", "Romeo Santos", "Juanes", "Carlos Vives",
  "Arijit Singh", "Shreya Ghoshal", "Neha Kakkar", "Badshah", "Yo Yo Honey Singh",
  "A.R. Rahman", "Sonu Nigam", "Armaan Malik",
  "TWICE", "Stray Kids", "NCT", "ATEEZ", "SEVENTEEN", "GOT7", "TXT",
  "Lisa", "Jennie", "Jisoo", "Rosé",
  "RM", "Jin", "SUGA", "j-hope", "Jimin", "V", "Jungkook",
  "PSY", "IU", "Red Velvet", "aespa", "ITZY", "NewJeans", "LE SSERAFIM",
  "Jay-Z", "Kendrick Lamar", "J. Cole", "Megan Thee Stallion", "Lil Nas X",
  "SZA", "Tyler, The Creator", "21 Savage", "Future", "Lil Wayne",
  "Snoop Dogg", "Ice Cube", "50 Cent", "Wiz Khalifa", "Chance the Rapper",
  "Pharrell Williams", "will.i.am", "John Legend", "Alicia Keys", "Mariah Carey",
  "Jennifer Lopez", "Sia", "P!nk", "Elton John", "Coldplay",
  "Imagine Dragons", "Maroon 5", "Linkin Park", "Green Day", "Foo Fighters",
  "Metallica", "The Rolling Stones", "Paul McCartney", "Mick Jagger",
  "Avril Lavigne", "Paramore", "Panic! at the Disco",
  "Anitta", "Lil Baby", "Juice WRLD", "XXXTENTACION", "Mac Miller",
  "Marshmello", "DJ Khaled", "Calvin Harris", "David Guetta", "Tiësto",
  "Deadmau5", "Skrillex", "Diplo", "Steve Aoki", "Martin Garrix",
  "Zedd", "Avicii", "The Chainsmokers",
  "Liam Payne", "Louis Tomlinson", "Zayn Malik",
  "Meghan Trainor", "Jason Derulo", "Sean Paul",
  "Wyclef Jean", "Lauryn Hill",

  // === ATHLETES ===
  // Soccer
  "Lionel Messi", "Zlatan Ibrahimovic", "David Beckham", "Wayne Rooney", "Rio Ferdinand",
  "Sergio Ramos", "Karim Benzema", "Luka Modric", "Toni Kroos", "Antoine Griezmann",
  "Paul Pogba", "Gareth Bale", "Robert Lewandowski", "Erling Haaland", "Jude Bellingham",
  "Vinicius Jr.", "Pedri", "Gavi", "Bukayo Saka", "Marcus Rashford",
  "Jack Grealish", "James Rodriguez", "Marcelo", "Dani Alves", "Sergio Agüero",
  "Luis Suárez", "Edinson Cavani", "Romelu Lukaku", "Virgil van Dijk",
  "Trent Alexander-Arnold", "Son Heung-min", "Harry Kane",
  "Mesut Özil", "Eden Hazard", "Alexis Sánchez",
  "Sadio Mané", "Pierre-Emerick Aubameyang", "Kaka",
  // Basketball
  "Stephen Curry", "Kevin Durant", "Giannis Antetokounmpo",
  "Kyrie Irving", "James Harden", "Russell Westbrook", "Anthony Davis",
  "Luka Doncic", "Ja Morant", "Jayson Tatum", "Zion Williamson",
  "Damian Lillard", "Chris Paul", "Klay Thompson", "Draymond Green",
  "Kawhi Leonard", "Jimmy Butler", "Joel Embiid", "Nikola Jokic",
  "Shaquille O'Neal", "Kobe Bryant", "Michael Jordan",
  // Tennis
  "Roger Federer", "Novak Djokovic", "Andy Murray",
  "Naomi Osaka", "Coco Gauff", "Carlos Alcaraz", "Venus Williams",
  // Cricket
  "Rohit Sharma", "MS Dhoni", "Hardik Pandya", "Ravindra Jadeja",
  "Jasprit Bumrah", "KL Rahul", "Rishabh Pant",
  "Babar Azam", "Shahid Afridi", "Wasim Akram",
  "Kumar Sangakkara", "AB de Villiers", "David Warner",
  "Ben Stokes", "Joe Root",
  // F1
  "Lewis Hamilton", "Max Verstappen", "Charles Leclerc", "Lando Norris",
  "Daniel Ricciardo", "Fernando Alonso", "Sebastian Vettel", "George Russell",
  // Golf
  "Tiger Woods", "Rory McIlroy", "Jordan Spieth", "Dustin Johnson",
  // Boxing / MMA
  "Conor McGregor", "Floyd Mayweather", "Manny Pacquiao",
  "Canelo Álvarez", "Anthony Joshua", "Tyson Fury",
  "Khabib Nurmagomedov", "Nate Diaz", "Israel Adesanya", "Dana White",
  // NFL
  "Tom Brady", "Patrick Mahomes", "Travis Kelce", "Odell Beckham Jr.",
  "Aaron Rodgers", "Russell Wilson", "Lamar Jackson", "Dak Prescott",
  "Rob Gronkowski", "JJ Watt",
  // Track & Field / Olympics
  "Usain Bolt", "Simone Biles", "Michael Phelps",
  // Other sports
  "Tony Hawk", "Lindsey Vonn",

  // === POLITICIANS / WORLD LEADERS ===
  "Hillary Clinton", "Bernie Sanders", "Kamala Harris", "Mike Pence",
  "Alexandria Ocasio-Cortez", "Ted Cruz", "Ron DeSantis", "Marco Rubio",
  "Elizabeth Warren", "Nancy Pelosi", "Mitt Romney", "Al Gore",
  "George W. Bush", "Bill Clinton",
  "Justin Trudeau", "Boris Johnson", "Rishi Sunak", "Volodymyr Zelenskyy",
  "Angela Merkel", "Pedro Sánchez", "Recep Tayyip Erdogan",
  "Benjamin Netanyahu", "Imran Khan", "Mahathir Mohamad",
  "Luiz Inácio Lula da Silva", "Alberto Fernández", "Gustavo Petro",
  "Pope Francis", "Dalai Lama",
  "Arvind Kejriwal", "Rahul Gandhi", "Amit Shah",
  "Nikki Haley", "Vivek Ramaswamy", "Gavin Newsom",
  "Barack Obama Foundation",

  // === ACTORS / ENTERTAINERS ===
  "Dwayne Johnson", "Ryan Reynolds", "Kevin Hart",
  "Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Chris Pratt",
  "Tom Holland", "Zendaya", "Margot Robbie", "Gal Gadot",
  "Vin Diesel", "Priyanka Chopra", "Deepika Padukone", "Alia Bhatt",
  "Ranveer Singh", "Hrithik Roshan", "Ajay Devgn", "Anushka Sharma",
  "Will Smith", "Jada Pinkett Smith",
  "Leonardo DiCaprio", "Brad Pitt", "Angelina Jolie", "Jennifer Aniston",
  "Scarlett Johansson", "Emma Watson", "Millie Bobby Brown",
  "Tom Hanks", "Samuel L. Jackson", "Morgan Freeman",
  "Ryan Gosling", "Timothée Chalamet", "Florence Pugh", "Ana de Armas",
  "Jason Momoa", "Mark Ruffalo", "Hugh Jackman", "Keanu Reeves",
  "Benedict Cumberbatch", "Pedro Pascal",
  "Reese Witherspoon", "Kerry Washington", "Mindy Kaling",
  "Lupita Nyong'o", "Viola Davis", "Cate Blanchett",
  "Jackie Chan", "Jet Li",

  // === NEWS ORGANIZATIONS / MEDIA ===
  "BBC", "Reuters", "AP News", "Washington Post", "The Economist", "TIME",
  "Fox News", "MSNBC", "NBC News", "CBS News", "Bloomberg",
  "Al Jazeera English", "Al Jazeera", "Sky News", "France 24",
  "BBC Sport", "The Wall Street Journal", "Financial Times",
  "The Independent", "Daily Mail", "New York Post",
  "NPR", "PBS NewsHour", "C-SPAN",
  "Vox", "VICE", "BuzzFeed News", "Axios",
  "India Today", "NDTV", "Republic TV", "Aaj Tak",
  "NHK World", "Deutsche Welle", "RT",
  "Univision", "Telemundo",
  "The Telegraph", "The Sun",
  "Breitbart News", "The Hill", "Politico",

  // === TECH COMPANIES / TECH LEADERS ===
  "Google", "Apple", "Amazon", "Netflix", "Disney", "HBO",
  "Tesla", "OpenAI",
  "Meta", "Instagram", "WhatsApp", "Facebook",
  "TikTok", "Snapchat", "Reddit", "LinkedIn", "Pinterest", "Tumblr",
  "Uber", "Airbnb", "Spotify", "Dropbox", "Slack",
  "Samsung", "Intel", "AMD", "NVIDIA",
  "Mark Zuckerberg", "Jeff Bezos", "Sundar Pichai", "Satya Nadella",
  "Jack Dorsey", "Sam Altman", "Jensen Huang",
  "Sheryl Sandberg", "Marissa Mayer",
  "Android", "Windows", "Xbox",
  "GitHub", "Stack Overflow",
  "Coinbase", "Ethereum", "Bitcoin",

  // === SPORTS LEAGUES / TEAMS ===
  "NFL", "NHL", "MLB", "MLS", "LaLiga", "Bundesliga", "Serie A", "Ligue 1",
  "WWE", "UFC", "PGA Tour", "ATP Tour", "WTA",
  "FIFA World Cup", "Olympics", "ICC Cricket",
  "Liverpool FC", "Chelsea FC", "Arsenal FC", "Tottenham Hotspur",
  "Juventus", "AC Milan", "Inter Milan", "Bayern Munich",
  "Paris Saint-Germain", "Borussia Dortmund", "Atlético de Madrid",
  "Los Angeles Lakers", "Golden State Warriors", "Boston Celtics",
  "New York Knicks", "Chicago Bulls", "Miami Heat",
  "Dallas Cowboys", "New England Patriots",
  "New York Yankees", "LA Dodgers",
  "India Cricket Team", "Pakistan Cricket Team",

  // === YOUTUBERS / INFLUENCERS / INTERNET PERSONALITIES ===
  "MrBeast", "PewDiePie", "Markiplier", "Jacksepticeye",
  "Logan Paul", "Jake Paul", "KSI", "MKBHD",
  "Lilly Singh", "David Dobrik", "Emma Chamberlain",
  "Charli D'Amelio", "Addison Rae", "Khaby Lame",
  "Ninja", "Pokimane", "Shroud", "TimTheTatman", "xQc",
  "Dream", "TommyInnit", "Technoblade",
  "Casey Neistat", "Linus Tech Tips",
  "MatPat", "Dude Perfect",
  "Philip DeFranco", "H3H3", "iJustine",
  "Zach King", "Brent Rivera",
  "Hasan Piker", "Valkyrae", "Ludwig",
  "Bella Poarch", "Bretman Rock",
  "Smosh", "Rhett & Link",
  "CarryMinati", "Bhuvan Bam", "Ashish Chanchlani",
  "Technical Guruji", "T-Series",
  "Whindersson Nunes", "El Rubius", "AuronPlay", "TheGrefg",
  "Fernanfloo", "Luisito Comunica", "Juanpa Zurita",
  "Jeffree Star", "James Charles", "NikkieTutorials",

  // === BRANDS ===
  // Fashion
  "Nike", "Adidas", "Gucci", "Louis Vuitton", "Chanel",
  "Puma", "Zara", "H&M", "Versace", "Prada", "Dior",
  "Balenciaga", "Supreme", "Off-White", "Calvin Klein",
  // Food & Beverage
  "McDonald's", "Coca-Cola", "Pepsi", "Starbucks", "KFC",
  "Burger King", "Taco Bell", "Wendy's", "Domino's", "Pizza Hut",
  "Red Bull", "Monster Energy",
  // Tech / Gaming
  "Samsung Mobile", "OnePlus", "Xiaomi",
  "Nintendo", "EA Sports", "Rockstar Games",
  "Epic Games", "Riot Games", "Blizzard Entertainment",
  "Call of Duty", "Minecraft", "Roblox", "League of Legends",
  "Valorant", "GTA", "FIFA", "Madden NFL",
  // Auto
  "Ferrari", "Lamborghini", "Mercedes-Benz", "BMW",
  "Porsche", "Audi", "Ford", "Toyota", "Chevrolet",
  "NASCAR",

  // === TV PERSONALITIES / HOSTS ===
  "Oprah Winfrey", "Joe Rogan", "Jimmy Kimmel", "Stephen Colbert",
  "Trevor Noah", "Conan O'Brien",
  "James Corden", "Seth Meyers", "John Oliver",
  "Ryan Seacrest", "Andy Cohen",
  "Dr. Phil", "Dr. Oz",
  "Gordon Ramsay", "Guy Fieri",
  "Bear Grylls", "Steve Harvey",
  "Tyra Banks", "Heidi Klum",
  "Simon Cowell", "Howie Mandel",
  "Anderson Cooper", "Rachel Maddow", "Don Lemon", "Sean Hannity",
  "Ben Shapiro", "Piers Morgan", "Megyn Kelly",
  "Kapil Sharma",

  // === AUTHORS / PUBLIC INTELLECTUALS ===
  "J.K. Rowling", "Stephen King", "Neil Gaiman", "Margaret Atwood",
  "Paulo Coelho", "Haruki Murakami",
  "Malcolm Gladwell", "Yuval Noah Harari", "Jordan Peterson",
  "Noam Chomsky", "Neil deGrasse Tyson", "Bill Nye",
  "Malala Yousafzai", "Greta Thunberg",
  "Richard Dawkins", "Nassim Nicholas Taleb",
  "Elon Musk Foundation", "Melinda French Gates",
  "Naval Ravikant", "Tim Ferriss", "Gary Vaynerchuk",

  // === RELIGIOUS LEADERS ===
  "Joel Osteen", "Rick Warren", "T.D. Jakes",
  "Sadhguru", "Sri Sri Ravi Shankar",

  // === COMEDIANS ===
  "Dave Chappelle", "Jerry Seinfeld", "Chris Rock",
  "Amy Schumer", "Ali Wong", "Hasan Minhaj",
  "Ricky Gervais", "Russell Howard", "Michael McIntyre",
  "Gabriel Iglesias", "Jeff Dunham",
  "Kumail Nanjiani",

  // === ORGANIZATIONS (UN, WHO, NGOs) ===
  "United Nations", "UNICEF", "WHO",
  "World Economic Forum", "World Bank", "IMF",
  "Amnesty International", "Human Rights Watch",
  "Greenpeace", "WWF", "Red Cross",
  "UNHCR", "WFP",
  "Gates Foundation", "Clinton Foundation",
  "European Union", "NATO", "African Union",

  // === MISCELLANEOUS ===
  "White House", "NASA JPL", "National Geographic",
  "The Nobel Prize", "Guinness World Records",
  "Wikipedia", "Wikileaks",
  "Anonymous", "4chan",
  "Marvel", "DC Comics", "Star Wars",
  "Harry Potter", "Game of Thrones",
  "The Simpsons", "South Park", "Rick and Morty",
  "SpongeBob", "Pokémon",
  "The Onion", "Babylon Bee",
  "TMZ", "E! News", "People Magazine",
  "Vogue", "GQ", "Rolling Stone", "Pitchfork",
  "Complex", "Hypebeast", "Bleacher Report",
  "Barstool Sports", "The Athletic",
  "CERN", "MIT", "Harvard", "Stanford", "Oxford",
  "FBI", "CIA", "Pentagon",
];
