// Top 100 most popular subreddits plus 600+ additional plausible guesses
export const mostPopularSubredditsHints: string[] = [
  // === Top 100 answers ===
  "r/funny", "r/AskReddit", "r/gaming", "r/worldnews", "r/todayilearned",
  "r/aww", "r/Music", "r/movies", "r/memes", "r/science",
  "r/Showerthoughts", "r/pics", "r/news", "r/Jokes", "r/space",
  "r/videos", "r/books", "r/askscience", "r/mildlyinteresting", "r/EarthPorn",
  "r/food", "r/GetMotivated", "r/LifeProTips", "r/gadgets", "r/sports",
  "r/Art", "r/dataisbeautiful", "r/Futurology", "r/personalfinance", "r/Documentaries",
  "r/UpliftingNews", "r/photoshopbattles", "r/technology", "r/OldSchoolCool", "r/tifu",
  "r/history", "r/nottheonion", "r/DIY", "r/IAmA", "r/listentothis",
  "r/philosophy", "r/nosleep", "r/wholesomememes", "r/television", "r/InternetIsBeautiful",
  "r/nba", "r/gifs", "r/pcmasterrace", "r/creepy", "r/interestingasfuck",
  "r/WallStreetBets", "r/TwoXChromosomes", "r/Fitness", "r/Unexpected", "r/soccer",
  "r/WritingPrompts", "r/nfl", "r/cats", "r/buildapc", "r/CrazyFuckingVideos",
  "r/facepalm", "r/dankmemes", "r/worldpolitics", "r/anime", "r/MadeMeSmile",
  "r/Minecraft", "r/relationship_advice", "r/leagueoflegends", "r/AmItheAsshole", "r/politics",
  "r/dogs", "r/PublicFreakout", "r/pokemon", "r/nextfuckinglevel", "r/StarWars",
  "r/BlackPeopleTwitter", "r/Tinder", "r/NatureIsFuckingLit", "r/CFB", "r/comics",
  "r/baseball", "r/Cooking", "r/MapPorn", "r/hiphopheads", "r/me_irl",
  "r/AskMen", "r/AskWomen", "r/whowouldwin", "r/Marvel", "r/wallpaper",
  "r/Android", "r/apple", "r/MurderedByWords", "r/programming", "r/OutOfTheLoop",
  "r/oddlysatisfying", "r/hockey", "r/IdiotsInCars", "r/HolUp", "r/HistoryMemes",

  // === Gaming ===
  "r/Overwatch", "r/FortNiteBR", "r/DestinyTheGame", "r/GrandTheftAutoV",
  "r/RocketLeague", "r/Terraria", "r/StardewValley", "r/EldenRing",
  "r/DarkSouls", "r/Fallout", "r/skyrim", "r/zelda",
  "r/nintendo", "r/PS5", "r/XboxSeriesX", "r/Steam",
  "r/GameDeals", "r/IndieGaming", "r/retrogaming", "r/boardgames",
  "r/chess", "r/Valorant", "r/apexlegends", "r/CallOfDuty",
  "r/GlobalOffensive", "r/deadbydaylight", "r/Genshin_Impact", "r/HonkaiStarRail",
  "r/FIFA", "r/AnimalCrossing", "r/NintendoSwitch", "r/PS4",
  "r/xboxone", "r/PSVR", "r/Diablo", "r/WorldOfWarcraft",
  "r/wow", "r/classicwow", "r/ffxiv", "r/FinalFantasy",
  "r/MonsterHunter", "r/borderlands", "r/Cyberpunk2077", "r/BaldursGate3",
  "r/Starfield", "r/HogwartsLegacy", "r/PalWorld", "r/Helldivers",
  "r/Satisfactory", "r/factorio", "r/KerbalSpaceProgram", "r/NoMansSkyTheGame",
  "r/Sims4", "r/CitiesSkylines", "r/CrusaderKings", "r/eu4",
  "r/hoi4", "r/Stellaris", "r/totalwar", "r/CivilizationVI",
  "r/2007scape", "r/runescape", "r/pathofexile", "r/lostark",
  "r/Dota2", "r/Rainbow6", "r/Warframe", "r/DeepRockGalactic",
  "r/SmashBros", "r/StreetFighter", "r/FighterZ", "r/Tekken",
  "r/emulation", "r/SteamDeck", "r/pcgaming", "r/truegaming",
  "r/patientgamers", "r/GamePhysics", "r/speedrun", "r/gaming_irl",

  // === Film & TV ===
  "r/Fantasy", "r/scifi", "r/horror", "r/TrueFilm",
  "r/MovieDetails", "r/NetflixBestOf", "r/MovieSuggestions", "r/TheWire",
  "r/BreakingBad", "r/gameofthrones", "r/StrangerThings", "r/TheBoys",
  "r/marvelstudios", "r/DC_Cinematic", "r/batman", "r/harrypotter",
  "r/lotr", "r/ATLA", "r/OnePiece", "r/naruto",
  "r/dbz", "r/ShingekiNoKyojin", "r/MyHeroAcademia", "r/JujutsuKaisen",
  "r/DemonSlayer", "r/HouseOfTheDragon", "r/TheLastOfUs", "r/Succession",
  "r/BetterCallSaul", "r/TheExpanse", "r/Yellowstone", "r/Severance",
  "r/Shogun", "r/TheMandalorianTV", "r/StarTrek", "r/DoctorWho",
  "r/Supernatural", "r/TheOffice", "r/PandR", "r/BrooklynNineNine",
  "r/Seinfeld", "r/IASIP", "r/Futurama", "r/simpsons",
  "r/southpark", "r/rickandmorty", "r/BobsBurgers", "r/KingOfTheHill",
  "r/arcane", "r/invincible", "r/WandaVision", "r/Loki",
  "r/Suits", "r/Dexter", "r/Lost", "r/Frasier",
  "r/Letterboxd", "r/criterion", "r/boxoffice", "r/Oscars",

  // === Finance & Crypto ===
  "r/investing", "r/stocks", "r/CryptoCurrency", "r/Bitcoin",
  "r/ethereum", "r/options", "r/RealEstate", "r/povertyfinance",
  "r/frugal", "r/financialindependence", "r/Fire", "r/Bogleheads",
  "r/dividends", "r/ValueInvesting", "r/StockMarket", "r/algotrading",
  "r/CryptoMarkets", "r/dogecoin", "r/solana", "r/cardano",
  "r/NFT", "r/defi", "r/pennystocks", "r/thetagang",
  "r/fatFIRE", "r/leanfire", "r/FinancialPlanning", "r/tax",

  // === Relationships & Life ===
  "r/relationships", "r/dating_advice", "r/Bumble", "r/OkCupid",
  "r/Marriage", "r/Parenting", "r/pregnant", "r/BabyBumps",
  "r/beyondthebump", "r/MomForAMinute", "r/DadForAMinute", "r/Divorce",
  "r/DeadBedrooms", "r/datingoverthirty", "r/hingeapp", "r/OnlineDating",

  // === Health & Fitness ===
  "r/AskDocs", "r/medical", "r/Health", "r/nutrition",
  "r/loseit", "r/gainit", "r/running", "r/bodybuilding",
  "r/CrossFit", "r/yoga", "r/Swimming", "r/cycling",
  "r/keto", "r/intermittentfasting", "r/1200isplenty", "r/EatCheapAndHealthy",
  "r/xxfitness", "r/StrongerByScience", "r/weightlifting", "r/homegym",
  "r/flexibility", "r/SkincareAddiction", "r/MakeupAddiction", "r/FancyFollicles",

  // === Sports ===
  "r/golf", "r/tennis", "r/MMA", "r/boxing",
  "r/SquaredCircle", "r/formula1", "r/NASCAR", "r/Cricket",
  "r/rugbyunion", "r/volleyball", "r/skiing", "r/snowboarding",
  "r/surfing", "r/climbing", "r/fantasyfootball", "r/fantasybaseball",
  "r/fantasybball", "r/sportsbook", "r/CollegeBasketball", "r/Premierleague",
  "r/LigaMX", "r/Bundesliga", "r/LaLiga", "r/SerieA",
  "r/chelseafc", "r/LiverpoolFC", "r/Gunners", "r/reddevils",
  "r/Barca", "r/realmadrid", "r/MCFC", "r/Tottenham",
  "r/Lakers", "r/warriors", "r/NYKnicks", "r/bostonceltics",
  "r/chicagobulls", "r/heat", "r/sixers", "r/mavericks",
  "r/49ers", "r/Patriots", "r/GreenBayPackers", "r/cowboys",
  "r/KansasCityChiefs", "r/ravens", "r/eagles", "r/buffalobills",
  "r/NYYankees", "r/Dodgers", "r/Braves", "r/Astros",

  // === Outdoors & Travel ===
  "r/hiking", "r/camping", "r/backpacking", "r/travel",
  "r/solotravel", "r/digitalnomad", "r/Shoestring", "r/roadtrip",
  "r/vanlife", "r/overlanding", "r/NationalPark", "r/WildernessBackpacking",
  "r/ultralight", "r/CampingGear", "r/fishing", "r/flyfishing",
  "r/kayaking", "r/canoeing", "r/scuba", "r/MTB",

  // === Photography & Art ===
  "r/photography", "r/itookapicture", "r/ExposurePorn", "r/photocritique",
  "r/streetphotography", "r/analog", "r/SonyAlpha", "r/Nikon",
  "r/DigitalArt", "r/drawing", "r/painting", "r/PixelArt",
  "r/Watercolor", "r/AbstractArt", "r/ArtHistory", "r/museum",

  // === Food & Drink ===
  "r/FoodPorn", "r/MealPrepSunday", "r/GifRecipes", "r/slowcooking",
  "r/Baking", "r/Breadit", "r/Coffee", "r/tea",
  "r/beer", "r/wine", "r/cocktails", "r/smoking",
  "r/BBQ", "r/grilling", "r/Sourdough", "r/KitchenConfidential",
  "r/ramen", "r/sushi", "r/Pizza", "r/steak",
  "r/castiron", "r/PressureCooking", "r/VeganRecipes", "r/vegetarian",
  "r/ketorecipes", "r/budgetfood", "r/AskCulinary", "r/Cheesemaking",

  // === Hobbies & Crafts ===
  "r/gardening", "r/houseplants", "r/IndoorGarden", "r/succulents",
  "r/woodworking", "r/metalworking", "r/3Dprinting", "r/knitting",
  "r/crochet", "r/sewing", "r/crafts", "r/Lego",
  "r/modelmakers", "r/minipainting", "r/DnD", "r/rpg",
  "r/magicTCG", "r/Warhammer", "r/Warhammer40k", "r/Gunpla",
  "r/Aquariums", "r/ReefTank", "r/Bonsai", "r/orchids",
  "r/quilting", "r/Embroidery", "r/Ceramics", "r/Pottery",
  "r/Leathercraft", "r/Blacksmith", "r/Jewelrymaking", "r/Calligraphy",

  // === Music ===
  "r/guitar", "r/drums", "r/piano", "r/WeAreTheMusicMakers",
  "r/edmproduction", "r/hiphop101", "r/ifyoulikeblank", "r/radiohead",
  "r/KendrickLamar", "r/TaylorSwift", "r/popheads", "r/indieheads",
  "r/Metal", "r/punk", "r/Jazz", "r/ClassicalMusic",
  "r/vinyl", "r/audiophile", "r/headphones", "r/Bass",
  "r/Songwriting", "r/musictheory", "r/makinghiphop", "r/ableton",
  "r/synthesizers", "r/modular", "r/electronicmusic", "r/trance",
  "r/DnB", "r/dubstep", "r/House", "r/techno",
  "r/Kanye", "r/Eminem", "r/beatles", "r/pinkfloyd",
  "r/ToolBand", "r/Metallica", "r/Nirvana", "r/Coldplay",
  "r/Muse", "r/arcticmonkeys", "r/oasis", "r/FrankOcean",

  // === Tech & Battlestations ===
  "r/battlestations", "r/MechanicalKeyboards", "r/monitors", "r/hardware",
  "r/overclocking", "r/homelab", "r/DataHoarder", "r/selfhosted",
  "r/sysadmin", "r/networking", "r/netsec", "r/cybersecurity",
  "r/SmartHome", "r/homeassistant", "r/raspberry_pi", "r/arduino",
  "r/Tablets", "r/GooglePixel", "r/OnePlus", "r/GalaxyS",
  "r/iphone", "r/mac", "r/Windows10", "r/Windows11",
  "r/ChromeOS", "r/techsupport", "r/buildapcsales", "r/laptops",

  // === Programming & Dev ===
  "r/learnprogramming", "r/webdev", "r/javascript", "r/python",
  "r/golang", "r/rust", "r/cpp", "r/java",
  "r/csharp", "r/swift", "r/reactjs", "r/angular",
  "r/node", "r/django", "r/flask", "r/Linux",
  "r/Ubuntu", "r/archlinux", "r/compsci", "r/MachineLearning",
  "r/datascience", "r/engineering", "r/devops", "r/gamedev",
  "r/ArtificialIntelligence", "r/ChatGPT", "r/LocalLLaMA", "r/StableDiffusion",
  "r/singularity", "r/Futurism", "r/Automate", "r/robotics",

  // === Science & Education ===
  "r/AskHistorians", "r/AskPhilosophy", "r/AskEconomics", "r/AskEngineers",
  "r/linguistics", "r/math", "r/physics", "r/chemistry",
  "r/biology", "r/Astronomy", "r/geology", "r/neuroscience",
  "r/psychology", "r/sociology", "r/anthropology", "r/Paleontology",
  "r/climate", "r/environment", "r/RenewableEnergy", "r/energy",
  "r/HomeworkHelp", "r/SAT", "r/ApplyingToCollege", "r/GradSchool",
  "r/college", "r/lawschool", "r/medicalschool", "r/EngineeringStudents",

  // === Discussion & Meta ===
  "r/AskRedditAfterDark", "r/NoStupidQuestions", "r/explainlikeimfive", "r/changemyview",
  "r/unpopularopinion", "r/TrueOffMyChest", "r/confessions", "r/self",
  "r/CasualConversation", "r/AMA", "r/DoesAnybodyElse", "r/TooAfraidToAsk",
  "r/TheoryOfReddit", "r/findareddit", "r/SubredditDrama", "r/bestof",

  // === Humor & Memes ===
  "r/mildlyinfuriating", "r/therewasanattempt", "r/KidsAreFuckingStupid", "r/Wellthatsucks",
  "r/TIHI", "r/blursedimages", "r/cursedcomments", "r/rareinsults",
  "r/BrandNewSentence", "r/SuspiciouslySpecific", "r/SelfAwarewolves", "r/LeopardsAteMyFace",
  "r/NotMyJob", "r/CrappyDesign", "r/assholedesign", "r/softwaregore",
  "r/ProgrammerHumor", "r/iamverysmart", "r/im14andthisisdeep", "r/gatekeeping",
  "r/ChoosingBeggars", "r/entitledparents", "r/BoneAppleTea", "r/engrish",
  "r/comedyheaven", "r/okbuddyretard", "r/shitposting", "r/196",
  "r/technicallythetruth", "r/AbsoluteUnits", "r/2meirl4meirl", "r/starterpacks",
  "r/coolguides", "r/Infographics", "r/educationalgifs", "r/DataArt",

  // === Stories & Revenge ===
  "r/ProRevenge", "r/MaliciousCompliance", "r/pettyrevenge", "r/NuclearRevenge",
  "r/legaladvice", "r/bestoflegaladvice", "r/IDontWorkHereLady", "r/talesfromtechsupport",
  "r/talesfromretail", "r/TalesFromYourServer", "r/StoriesAboutKevin", "r/PointlessStories",

  // === Work & Career ===
  "r/antiwork", "r/WorkReform", "r/recruitinghell", "r/Teachers",
  "r/nursing", "r/medicine", "r/pharmacy", "r/ITCareerQuestions",
  "r/cscareerquestions", "r/jobs", "r/resumes", "r/careerguidance",
  "r/freelance", "r/Entrepreneur", "r/smallbusiness", "r/startups",

  // === Animals ===
  "r/AnimalsBeingDerps", "r/AnimalsBeingBros", "r/AnimalsBeingJerks", "r/NatureIsMetal",
  "r/rarepuppers", "r/Zoomies", "r/Catloaf", "r/IllegallySmolCats",
  "r/tuckedinkitties", "r/blep", "r/Rabbits", "r/hamsters",
  "r/parrots", "r/snakes", "r/reptiles", "r/frogs",
  "r/birdwatching", "r/whales", "r/sharks", "r/Awwducational",

  // === Location Subreddits ===
  "r/AskAnAmerican", "r/AskEurope", "r/unitedkingdom", "r/canada",
  "r/australia", "r/india", "r/germany", "r/france",
  "r/japan", "r/korea", "r/brazil", "r/mexico",
  "r/nyc", "r/losangeles", "r/chicago", "r/sanfrancisco",
  "r/seattle", "r/Austin", "r/portland", "r/Denver",
  "r/london", "r/toronto", "r/ireland", "r/Scotland",
  "r/newzealand", "r/Philippines", "r/europe", "r/texas",

  // === Misc & Niche ===
  "r/ADHD", "r/autism", "r/Anxiety", "r/depression",
  "r/mentalhealth", "r/offmychest", "r/SuicideWatch", "r/DecidingToBeBetter",
  "r/getdisciplined", "r/selfimprovement", "r/Meditation", "r/Stoicism",
  "r/minimalism", "r/ZeroWaste", "r/BuyItForLife", "r/Frisson",
  "r/AbandonedPorn", "r/UrbanExploration", "r/CozyPlaces", "r/RoomPorn",
  "r/malelivingspace", "r/femalelivingspace", "r/HomeDecorating", "r/InteriorDesign",
  "r/Cartography", "r/vexillology", "r/heraldry", "r/PropagandaPosters",
  "r/ColorizedHistory", "r/HistoryPorn", "r/OldPhotosInRealLife", "r/TheWayWeWere",
  "r/RetroFuturism", "r/Cyberpunk", "r/ImaginaryLandscapes", "r/ImaginaryMonsters",
  "r/WritersGroup", "r/DestructiveReaders", "r/KeepWriting", "r/screenwriting",
  "r/tipofmytongue", "r/RBI", "r/UnresolvedMysteries", "r/TrueCrime",
  "r/conspiracytheories", "r/HighStrangeness", "r/Paranormal", "r/Glitch_in_the_Matrix",
  "r/Dreams", "r/LucidDreaming", "r/Psychonaut", "r/DMT",
  "r/cars", "r/Autos", "r/Trucks", "r/Mustang",
  "r/BMW", "r/Porsche", "r/Tesla", "r/electricvehicles",
  "r/motorcycles", "r/bikecommuting", "r/bicycling", "r/FixedGearBicycle",
  "r/fashionadvice", "r/malefashionadvice", "r/femalefashionadvice", "r/streetwear",
  "r/sneakers", "r/watches", "r/EDC", "r/Goodyearwelt",
  "r/FrugalMaleFashion", "r/ThriftStoreHauls", "r/Flipping", "r/DealHunters",
  "r/savedyouaclick", "r/trackers", "r/privacy",
  "r/VPN", "r/piracy", "r/cordcutters", "r/YouShouldKnow",
];
