export const mostStreamedSpotifyArtistsHints: string[] = [
  // ===== TOP 100 (the actual answers) =====
  "Taylor Swift", "Drake", "Bad Bunny", "The Weeknd", "Ariana Grande",
  "Ed Sheeran", "Billie Eilish", "Eminem", "Kanye West", "Post Malone",
  "BTS", "Justin Bieber", "Bruno Mars", "Rihanna", "Coldplay",
  "Travis Scott", "Kendrick Lamar", "Dua Lipa", "J Balvin", "Imagine Dragons",
  "Juice WRLD", "Lana Del Rey", "Lady Gaga", "David Guetta", "XXXTENTACION",
  "Future", "Ozuna", "Chris Brown", "Nicki Minaj", "Rauw Alejandro",
  "Lil Wayne", "Anuel AA", "21 Savage", "SZA", "KAROL G",
  "Khalid", "Lil Baby", "Arijit Singh", "Maroon 5", "Beyoncé",
  "Maluma", "Feid", "Calvin Harris", "Myke Towers", "Lil Uzi Vert",
  "Linkin Park", "J. Cole", "Peso Pluma", "Sia", "Young Thug",
  "Doja Cat", "Shakira", "Morgan Wallen", "Farruko", "Shawn Mendes",
  "Sam Smith", "Queen", "One Direction", "Harry Styles", "Metro Boomin",
  "Adele", "Gunna", "Arctic Monkeys", "Pritam", "Katy Perry",
  "Tyler, The Creator", "Selena Gomez", "Olivia Rodrigo", "Ty Dolla $ign", "Junior H",
  "The Beatles", "Nicky Jam", "Halsey", "Playboi Carti", "Wiz Khalifa",
  "Fuerza Regida", "Pitbull", "Frank Ocean", "Die drei ???", "JAY-Z",
  "A$AP Rocky", "The Chainsmokers", "Miley Cyrus", "Marshmello", "Sabrina Carpenter",
  "Cardi B", "Twenty One Pilots", "Disney", "Michael Jackson", "Camila Cabello",
  "Arcángel", "Red Hot Chili Peppers", "$uicideboy$", "OneRepublic", "Avicii",
  "Snoop Dogg", "DaBaby", "50 Cent", "Romeo Santos", "Natanael Cano",

  // ===== POP (global mainstream) =====
  "Demi Lovato", "Nick Jonas", "Jonas Brothers", "Charlie Puth", "Meghan Trainor",
  "Lizzo", "Bebe Rexha", "Ava Max", "Anne-Marie", "Rita Ora",
  "Ellie Goulding", "Zara Larsson", "Tove Lo", "Alessia Cara", "Rachel Platten",
  "Troye Sivan", "Lorde", "Charli XCX", "Kim Petras", "Rina Sawayama",
  "P!nk", "Mariah Carey", "Celine Dion", "Madonna", "Britney Spears",
  "Christina Aguilera", "Janet Jackson", "Whitney Houston", "Robbie Williams",
  "Tate McRae", "Gracie Abrams", "Chappell Roan", "Reneé Rapp", "Madison Beer",
  "Conan Gray", "Bazzi", "Lauv", "Jeremy Zucker", "Chelsea Cutler",
  "Why Don't We", "5 Seconds of Summer", "The Vamps", "Little Mix",
  "Spice Girls", "Backstreet Boys", "NSYNC", "Kylie Minogue", "Danna Paola",
  "Aitana", "Tini", "Becky G", "Anitta", "Rosalía",
  "Grimes", "Alicia Keys", "John Legend", "Jason Derulo", "Sean Kingston",

  // ===== HIP-HOP / RAP =====
  "Lil Nas X", "Jack Harlow", "Rod Wave", "Polo G",
  "Moneybagg Yo", "Lil Durk", "42 Dugg", "EST Gee", "Rylo Rodriguez",
  "Megan Thee Stallion", "Ice Spice", "GloRilla", "Latto", "Flo Milli",
  "Nas", "The Notorious B.I.G.", "Tupac", "DMX", "Wu-Tang Clan",
  "Lil Yachty", "Denzel Curry", "JID", "Earthgang", "Bas",
  "Mac Miller", "Logic", "Chance the Rapper", "Childish Gambino", "Kid Cudi",
  "ScHoolboy Q", "Ab-Soul", "Isaiah Rashad", "Vince Staples", "Freddie Gibbs",
  "Pusha T", "2 Chainz", "Big Sean", "Meek Mill", "French Montana",
  "Migos", "Quavo", "Offset", "Takeoff", "Rae Sremmurd",
  "Lil Tecca", "Smokepurpp", "Trippie Redd", "NBA YoungBoy", "Kodak Black",
  "YNW Melly", "Pop Smoke", "Fivio Foreign", "Central Cee", "Dave",
  "Stormzy", "Skepta", "AJ Tracey", "Aitch", "Headie One",
  "J Hus", "Tion Wayne", "Russ Millions", "Digga D", "Slowthai",
  "Little Simz", "Knucks", "Loyle Carner",
  "Missy Elliott", "Busta Rhymes", "Ludacris", "T.I.", "Gucci Mane",
  "Rick Ross", "Joyner Lucas", "NF", "Tech N9ne", "Hopsin",
  "Cordae", "Aminé", "Smino", "Saba", "Noname",
  "Tyler ICU", "Don Toliver", "Baby Keem", "Yeat",

  // ===== LATIN / REGGAETON =====
  "Daddy Yankee", "Don Omar", "Wisin", "Yandel",
  "Bad Gyal", "C. Tangana",
  "Paulo Londra", "Bizarrap", "Trueno", "Duki", "Cazzu", "Nicki Nicole",
  "Jhay Cortez", "Lunay", "Sech", "Dalex",
  "Luis Fonsi", "Enrique Iglesias", "Ricky Martin", "Marc Anthony",
  "Aventura", "Prince Royce", "Sebastián Yatra", "Manuel Turizo", "Camilo",
  "Carlos Vives", "Juanes", "J Quiles", "De La Ghetto", "Zion & Lennox",
  "Tego Calderón", "Plan B", "Wisin & Yandel",
  "Mora", "Jay Wheeler", "Pedro Capó", "Reik", "Morat",
  "Christian Nodal", "Grupo Frontera", "Los Ángeles Azules", "Banda MS",
  "Lenin Ramírez", "Calibre 50", "T3R Elemento", "Eslabon Armado",
  "Luis Miguel", "Alejandro Sanz", "Julieta Venegas", "Mon Laferte",
  "María Becerra", "Tiago PZK", "Emilia", "YSY A", "Neo Pistea",
  "Elena Rose", "Danny Ocean", "Lasso",

  // ===== K-POP =====
  "BLACKPINK", "TWICE", "Stray Kids", "SEVENTEEN", "aespa",
  "NewJeans", "IVE", "LE SSERAFIM", "ITZY", "Red Velvet",
  "EXO", "GOT7", "NCT 127", "NCT Dream", "ENHYPEN",
  "TXT", "ATEEZ", "Monsta X", "Super Junior", "SHINee",
  "BIGBANG", "2NE1", "Wonder Girls", "Girls' Generation", "f(x)",
  "PSY", "IU", "Jennie", "Lisa (BLACKPINK)", "Rosé",
  "Jungkook", "Jimin", "V", "Suga", "RM",
  "ZICO", "Dean", "Crush", "Jay Park", "pH-1",
  "(G)I-DLE", "MAMAMOO", "Hwasa", "Chung Ha", "Sunmi",
  "NMIXX", "Kep1er", "VIVIZ",

  // ===== ROCK / ALTERNATIVE =====
  "Panic! at the Disco", "Fall Out Boy", "My Chemical Romance", "Green Day", "Blink-182",
  "Paramore", "Hayley Williams", "Bring Me the Horizon", "Architects", "Sleep Token",
  "Radiohead", "Tame Impala",
  "Gorillaz", "Alt-J", "Foster the People", "Vampire Weekend", "The National",
  "The Killers", "Muse", "Foo Fighters", "Nirvana", "Pearl Jam",
  "Oasis", "Blur", "The Smiths", "The Cure", "Depeche Mode",
  "The Strokes", "Interpol", "Yeah Yeah Yeahs", "Bloc Party", "Franz Ferdinand",
  "Cage the Elephant", "The Black Keys", "The White Stripes", "Jack White",
  "Arcade Fire", "Modest Mouse", "Death Cab for Cutie", "The Postal Service",
  "Weezer", "Jimmy Eat World", "Dashboard Confessional", "Brand New",
  "The 1975", "Glass Animals", "Wallows", "Dayglow", "Still Woozy",
  "Royal Blood", "Nothing But Thieves", "Highly Suspect", "Kaleo",
  "Maneskin", "Greta Van Fleet", "Inhaler", "Fontaines D.C.", "Turnstile",
  "System of a Down", "Rage Against the Machine", "Tool", "Deftones",
  "Kings of Leon", "The Lumineers", "Of Monsters and Men", "Hozier",

  // ===== R&B / SOUL =====
  "Giveon", "Lucky Daye", "H.E.R.", "Jazmine Sullivan", "Ari Lennox",
  "Silk Sonic", "Anderson .Paak", "Thundercat", "Flying Lotus",
  "Daniel Caesar", "6LACK", "Brent Faiyaz", "Summer Walker", "Jhené Aiko",
  "Kehlani", "Snoh Aalegra", "Jorja Smith", "Ella Mai", "Normani",
  "Tinashe", "Tyla", "Victoria Monét", "Chloe x Halle", "Chlöe",
  "Miguel", "The-Dream", "Jeremih", "Trey Songz", "Bryson Tiller",
  "PARTYNEXTDOOR", "Jacquees", "dvsn", "Roy Woods",
  "Usher", "Ne-Yo", "Akon", "Mario", "Omarion",
  "Mary J. Blige", "Lauryn Hill", "Erykah Badu", "D'Angelo", "Maxwell",
  "Stevie Wonder", "Marvin Gaye", "Aretha Franklin", "Al Green", "Otis Redding",

  // ===== EDM / ELECTRONIC / DANCE =====
  "Flume", "Disclosure", "Caribou",
  "Martin Garrix", "Tiësto", "Kygo", "Zedd", "Alan Walker",
  "Skrillex", "Diplo", "Major Lazer", "DJ Snake", "Afrojack",
  "Steve Aoki", "Deadmau5", "Alesso", "Swedish House Mafia", "Armin van Buuren",
  "Above & Beyond", "Kaskade", "Illenium", "Said the Sky", "Dabin",
  "ODESZA", "Rufus Du Sol", "Lane 8", "Bonobo", "Four Tet",
  "Fred again..", "Bicep", "Jamie xx", "Floating Points",
  "Fisher", "Chris Lake", "Dom Dolla", "John Summit", "Vintage Culture",
  "Elderbrook", "Meduza", "Regard", "Joel Corry", "Jax Jones",
  "Oliver Heldens", "Don Diablo", "R3HAB", "Galantis", "Lost Frequencies",
  "Daft Punk", "Justice", "Kavinsky", "M83", "Gesaffelstein",
  "The Prodigy", "Fatboy Slim", "Chemical Brothers", "Underworld",

  // ===== COUNTRY =====
  "Luke Combs", "Chris Stapleton", "Blake Shelton", "Carrie Underwood", "Thomas Rhett",
  "Dierks Bentley", "Kenny Chesney", "Tim McGraw", "Toby Keith", "Brad Paisley",
  "Zach Bryan", "Bailey Zimmerman", "Hardy", "Jelly Roll", "Oliver Anthony",
  "Jason Aldean", "Luke Bryan", "Sam Hunt", "Kane Brown", "Dan + Shay",
  "Florida Georgia Line", "Keith Urban", "Eric Church", "Garth Brooks",
  "Dolly Parton", "Johnny Cash", "Willie Nelson", "Waylon Jennings",
  "George Strait", "Alan Jackson", "Reba McEntire", "Shania Twain",
  "Kacey Musgraves", "Maren Morris", "Miranda Lambert", "Carly Pearce",
  "Old Dominion", "Midland", "Brothers Osborne", "Zac Brown Band",
  "Lainey Wilson", "Tyler Childers", "Sturgill Simpson", "Colter Wall",

  // ===== INDIE / FOLK =====
  "Bon Iver", "Fleet Foxes", "Iron & Wine", "Sufjan Stevens", "Elliott Smith",
  "Mac DeMarco", "Rex Orange County", "Clairo", "girl in red", "beabadoobee",
  "Phoebe Bridgers", "Boygenius", "Lucy Dacus", "Julien Baker",
  "The War on Drugs", "Big Thief", "Adrianne Lenker", "Angel Olsen", "Waxahatchee",
  "Father John Misty", "Lord Huron", "The Head and the Heart", "Vance Joy",
  "Mumford & Sons",
  "Edward Sharpe & the Magnetic Zeros", "The Avett Brothers",
  "Neutral Milk Hotel", "The Decemberists", "Andrew Bird",
  "Mitski", "Japanese Breakfast", "Snail Mail", "Soccer Mommy", "Alex G",
  "Dijon", "Dominic Fike", "Omar Apollo", "Steve Lacy",
  "Khruangbin", "Unknown Mortal Orchestra", "King Gizzard & the Lizard Wizard",

  // ===== METAL / HARD ROCK =====
  "Metallica", "Iron Maiden", "Slayer", "Megadeth", "Anthrax",
  "Black Sabbath", "Judas Priest", "Motorhead", "Dio", "Ozzy Osbourne",
  "Slipknot", "Korn", "Limp Bizkit", "Disturbed", "Godsmack",
  "Avenged Sevenfold", "Bullet for My Valentine", "Trivium", "Killswitch Engage",
  "Parkway Drive", "August Burns Red", "As I Lay Dying", "The Devil Wears Prada",
  "Polyphia", "Animals as Leaders", "Periphery", "Meshuggah", "Gojira",
  "Ghost", "Spiritbox", "Bad Omens", "Motionless in White", "Ice Nine Kills",
  "Five Finger Death Punch", "Volbeat", "Shinedown", "Breaking Benjamin",
  "Three Days Grace", "Papa Roach", "Chevelle", "Seether",
  "Rammstein", "Nightwish", "Epica", "Within Temptation", "Powerwolf",

  // ===== CLASSIC ROCK =====
  "Led Zeppelin", "Pink Floyd", "The Rolling Stones", "The Who", "The Doors",
  "AC/DC", "Aerosmith", "Guns N' Roses", "Bon Jovi", "Def Leppard",
  "U2", "The Police", "Sting", "Dire Straits", "Fleetwood Mac",
  "Eagles", "Creedence Clearwater Revival", "The Beach Boys", "Lynyrd Skynyrd",
  "Journey", "Boston", "Foreigner", "Toto", "Kansas",
  "Deep Purple", "Rush", "Yes", "Genesis", "Phil Collins",
  "Elton John", "Billy Joel", "Bruce Springsteen", "Tom Petty", "Bob Dylan",
  "Jimi Hendrix", "Eric Clapton", "Santana", "Stevie Ray Vaughan",
  "David Bowie", "Prince", "George Michael", "Hall & Oates",
  "Van Halen", "Kiss", "ZZ Top", "Scorpions", "Thin Lizzy",

  // ===== BOLLYWOOD / INDIAN MUSIC =====
  "A.R. Rahman", "Shreya Ghoshal", "Atif Aslam", "Neha Kakkar", "Jubin Nautiyal",
  "Armaan Malik", "Badshah", "Honey Singh", "Guru Randhawa", "Harrdy Sandhu",
  "Diljit Dosanjh", "AP Dhillon", "Sidhu Moose Wala", "Karan Aujla",
  "Raftaar", "Divine", "Emiway Bantai", "MC Stan", "King",
  "Vishal-Shekhar", "Shankar-Ehsaan-Loy", "Amit Trivedi", "Sachin-Jigar",
  "Kumar Sanu", "Udit Narayan", "Sonu Nigam", "Lata Mangeshkar", "Kishore Kumar",
  "B Praak", "Darshan Raval", "Nucleya", "Ritviz",

  // ===== AFROBEATS / AFRICAN MUSIC =====
  "Burna Boy", "Wizkid", "Davido", "Tems", "Rema",
  "Asake", "Fireboy DML", "Omah Lay", "CKay", "Joeboy",
  "Tiwa Savage", "Yemi Alade", "Mr Eazi", "Patoranking",
  "Diamond Platnumz", "Sauti Sol", "Khaligraph Jones",
  "Black Coffee", "Master KG", "Focalistic",
  "Shatta Wale", "Sarkodie", "Stonebwoy", "Black Sherif",
  "Ayra Starr", "Ruger", "Bnxn",

  // ===== J-POP =====
  "YOASOBI", "Ado", "Kenshi Yonezu", "LiSA (J-pop)", "Official HIGE DANdism",
  "King Gnu", "Mrs. GREEN APPLE", "Fujii Kaze", "Vaundy", "Aimer",
  "Radwimps", "ONE OK ROCK", "BABYMETAL", "Perfume", "Utada Hikaru",
  "AKB48", "Nogizaka46", "Hatsune Miku", "Eve", "Yorushika",
  "Yama", "imase", "Tatsuro Yamashita", "Mariya Takeuchi",

  // ===== CLASSICAL / SOUNDTRACK COMPOSERS =====
  "Hans Zimmer", "John Williams", "Ludovico Einaudi", "Yiruma",
  "Ennio Morricone", "Howard Shore", "Danny Elfman", "Alexandre Desplat",
  "Max Richter", "Ólafur Arnalds", "Nils Frahm", "Joep Beving",
  "Lang Lang", "Yo-Yo Ma", "André Rieu", "Andrea Bocelli", "Il Divo",
  "2Cellos", "Lindsey Stirling", "Vanessa-Mae",

  // ===== ONE-HIT WONDERS / VIRAL ARTISTS =====
  "Tones and I", "Arizona Zervas", "24kGoldn", "Jawsh 685",
  "Masked Wolf", "SAINt JHN", "Trevor Daniel", "Internet Money",
  "Tai Verdes", "Surfaces", "Powfu", "Ruth B.",
  "Lewis Capaldi", "Dean Lewis", "Dermot Kennedy", "James Arthur",
  "Labrinth", "Tom Odell", "George Ezra", "Rag'n'Bone Man",
  "Passenger", "Gotye",
  "Walk the Moon", "MAGIC!", "OMI", "Lukas Graham",
  "Silentó", "Fetty Wap", "Desiigner", "Ayo & Teo",
  "Lil Pump", "Bhad Bhabie",
  "Tommy Richman", "Benson Boone", "Teddy Swims", "Noah Kahan",
];
