// ~250 beverages for hints
export const mostConsumedBeveragesHints: string[] = [
  // Top 50 (the actual answers)
  "Water", "Tea", "Coffee", "Milk", "Beer",
  "Carbonated Soft Drinks", "Fruit Juice", "Wine", "Spirits", "Sports & Energy Drinks",
  "Black Tea", "Green Tea", "Herbal Tea", "Oolong Tea", "Masala Chai",
  "Matcha", "Espresso", "Drip Coffee", "Instant Coffee", "Iced Coffee",
  "Coca-Cola", "Pepsi", "Sprite", "Fanta", "7UP",
  "Dr Pepper", "Mountain Dew", "Ginger Ale", "Snow Beer", "Budweiser",
  "Heineken", "Corona", "Tsingtao", "Stella Artois", "Guinness",
  "Red Wine", "White Wine", "Sparkling Wine", "Baijiu", "Vodka",
  "Whiskey", "Rum", "Gin", "Tequila", "Brandy",
  "Orange Juice", "Red Bull", "Gatorade", "Apple Juice", "Chocolate Milk",
  // Additional beverages
  "Sparkling Water", "Tonic Water", "Coconut Water", "Mineral Water",
  "Alkaline Water", "Seltzer Water", "Flavored Water",
  "White Tea", "Pu-erh Tea", "Rooibos Tea", "Chamomile Tea",
  "Peppermint Tea", "Hibiscus Tea", "Bubble Tea", "Kombucha",
  "Iced Tea", "Arnold Palmer", "Yerba Mate", "Jasmine Tea",
  "Earl Grey", "English Breakfast Tea", "Darjeeling Tea", "Sencha",
  "Americano", "Macchiato", "Cortado", "Cold Brew",
  "Nitro Cold Brew", "Frappuccino", "Vietnamese Coffee",
  "Turkish Coffee", "Greek Coffee", "Cappuccino", "Latte",
  "Flat White", "Mocha", "Affogato",
  "Grapefruit Juice", "Cranberry Juice", "Grape Juice",
  "Pineapple Juice", "Tomato Juice", "Carrot Juice",
  "Pomegranate Juice", "Mango Juice", "Lemonade",
  "Watermelon Juice", "Beet Juice", "Celery Juice",
  "Guava Juice", "Passion Fruit Juice",
  "Whole Milk", "Skim Milk", "Buttermilk", "Kefir",
  "Lassi", "Mango Lassi", "Ayran", "Horchata",
  "Strawberry Milk", "Milkshake",
  "Almond Milk", "Oat Milk", "Soy Milk", "Rice Milk",
  "Hemp Milk", "Cashew Milk", "Coconut Milk",
  "RC Cola", "Root Beer", "A&W Root Beer", "Orange Crush",
  "Sunkist", "Cream Soda", "Birch Beer", "Cheerwine",
  "Jarritos", "Irn-Bru", "Lucozade", "Ribena",
  "Mirinda", "Schweppes", "Barq's",
  "Rockstar Energy", "Monster Energy", "Celsius",
  "Bang Energy", "5-hour Energy", "NOS Energy",
  "Reign Energy", "Sting Energy", "Pocari Sweat",
  "Powerade", "Vitamin Water", "PRIME Hydration",
  "Pedialyte", "Propel Water", "Liquid I.V.",
  "Coors Light", "Miller Lite", "Pabst Blue Ribbon",
  "Modelo", "Dos Equis", "Tecate",
  "Victoria Bitter", "Kingfisher", "Asahi",
  "Sapporo", "Kirin", "Tiger Beer",
  "Chang Beer", "Singha", "Tusker",
  "Castle Lager", "Brahma", "Quilmes",
  "Hard Cider", "Angry Orchard", "Strongbow",
  "Non-Alcoholic Beer", "Radler", "Shandy",
  "Cabernet Sauvignon", "Merlot", "Pinot Noir",
  "Syrah", "Malbec", "Zinfandel",
  "Chardonnay", "Sauvignon Blanc", "Pinot Grigio",
  "Riesling", "Moscato", "Prosecco",
  "Champagne", "Cava", "Rose Wine",
  "Port Wine", "Sherry", "Sangria", "Mulled Wine",
  "Johnnie Walker", "Jack Daniel's", "Jim Beam",
  "Jameson", "Maker's Mark", "Absolut Vodka",
  "Grey Goose", "Smirnoff", "Bacardi",
  "Captain Morgan", "Havana Club", "Patron",
  "Jose Cuervo", "Hendrick's Gin", "Tanqueray",
  "Bombay Sapphire", "Baileys", "Kahlua",
  "Malibu", "Campari", "Aperol Spritz",
  "Margarita", "Mojito", "Pina Colada",
  "Moscow Mule", "Mimosa", "Bloody Mary",
  "Long Island Iced Tea", "Gin & Tonic", "Old Fashioned",
  "Negroni", "Daiquiri", "Manhattan", "Cosmopolitan",
  "Pulque", "Chicha", "Kvass", "Amazake",
  "Milo", "Horlicks", "Ovaltine",
  "Ensure", "Boost", "Pedialyte",
  "Yakult", "Actimel",
];
