export const mostStreamedSpotifyArtistsHints: string[] = [
  // Top 100 (the actual answers)
  "Taylor Swift", "Drake", "Bad Bunny", "The Weeknd", "Ariana Grande",
  "Ed Sheeran", "Billie Eilish", "Eminem", "Kanye West", "Post Malone",
  "BTS", "Justin Bieber", "Bruno Mars", "Rihanna", "Coldplay",
  "Travis Scott", "Kendrick Lamar", "Dua Lipa", "J Balvin", "Imagine Dragons",
  "Juice WRLD", "Lana Del Rey", "Lady Gaga", "David Guetta", "XXXTENTACION",
  "Future", "Ozuna", "Chris Brown", "Nicki Minaj", "Rauw Alejandro",
  "Lil Wayne", "Anuel AA", "21 Savage", "SZA", "KAROL G",
  "Khalid", "Lil Baby", "Arijit Singh", "Maroon 5", "Beyoncé",
  "Maluma", "Feid", "Calvin Harris", "Myke Towers", "Lil Uzi Vert",
  "Linkin Park", "J. Cole", "Peso Pluma", "Sia", "Young Thug",
  "Doja Cat", "Shakira", "Morgan Wallen", "Farruko", "Shawn Mendes",
  "Sam Smith", "Queen", "One Direction", "Harry Styles", "Metro Boomin",
  "Adele", "Gunna", "Arctic Monkeys", "Pritam", "Katy Perry",
  "Tyler, The Creator", "Selena Gomez", "Olivia Rodrigo", "Ty Dolla $ign", "Junior H",
  "The Beatles", "Nicky Jam", "Halsey", "Playboi Carti", "Wiz Khalifa",
  "Fuerza Regida", "Pitbull", "Frank Ocean", "Die drei ???", "JAY-Z",
  "A$AP Rocky", "The Chainsmokers", "Miley Cyrus", "Marshmello", "Sabrina Carpenter",
  "Cardi B", "Twenty One Pilots", "Disney", "Michael Jackson", "Camila Cabello",
  "Arcángel", "Red Hot Chili Peppers", "$uicideboy$", "OneRepublic", "Avicii",
  "Snoop Dogg", "DaBaby", "50 Cent", "Romeo Santos", "Natanael Cano",
  // Beyond top 100 (additional plausible guesses)
  "Daddy Yankee", "Don Omar", "Wisin", "Yandel",
  "Becky G", "Anitta", "Karol G", "Rosalía", "Bad Gyal", "C. Tangana",
  "Paulo Londra", "Bizarrap", "Trueno", "Duki", "Cazzu", "Nicki Nicole",
  "Jhay Cortez", "Lunay", "Sech", "Dalex",
  "Luke Combs", "Chris Stapleton", "Blake Shelton", "Carrie Underwood", "Thomas Rhett",
  "Dierks Bentley", "Kenny Chesney", "Tim McGraw", "Toby Keith", "Brad Paisley",
  "Lil Nas X", "Jack Harlow", "Rod Wave", "Polo G",
  "Moneybagg Yo", "Lil Durk", "42 Dugg", "EST Gee", "Rylo Rodriguez",
  "Giveon", "Lucky Daye", "H.E.R.", "Jazmine Sullivan", "Ari Lennox",
  "Silk Sonic", "Anderson .Paak", "Thundercat", "Flying Lotus",
  "Radiohead", "Tame Impala", "Flume", "Disclosure", "Caribou",
  "Gorillaz", "Alt-J", "Foster the People", "Vampire Weekend", "The National",
  "Panic! at the Disco", "Fall Out Boy", "My Chemical Romance", "Green Day", "Blink-182",
  "Paramore", "Hayley Williams", "Bring Me the Horizon", "Architects", "Sleep Token",
];
