// Top 100 most common jobs in the US (BLS OEWS May 2024) plus 600+ additional
// real occupation titles drawn from the Bureau of Labor Statistics Standard
// Occupational Classification (SOC) system.
// Source: https://www.bls.gov/oes/current/oes_nat.htm
export const mostCommonJobsHints: string[] = [
  // ── Top 100 answers (ranked by employment) ─────────────────────────────
  "Home Health and Personal Care Aides",
  "Fast Food and Counter Workers",
  "Retail Salespersons",
  "Registered Nurses",
  "Cashiers",
  "General and Operations Managers",
  "Office Clerks, General",
  "Laborers and Material Movers",
  "Customer Service Representatives",
  "Stockers and Order Fillers",
  "Janitors and Cleaners",
  "Waiters and Waitresses",
  "Software Developers",
  "Secretaries and Administrative Assistants",
  "Heavy and Tractor-Trailer Truck Drivers",
  "First-Line Supervisors of Retail Sales Workers",
  "Light Truck Drivers",
  "Accountants and Auditors",
  "Teaching Assistants",
  "Elementary School Teachers",
  "Construction Laborers",
  "Maintenance and Repair Workers",
  "Food Preparation Workers",
  "Cooks, Restaurant",
  "Medical Assistants",
  "Landscaping and Groundskeeping Workers",
  "Security Guards",
  "Nursing Assistants",
  "First-Line Supervisors of Food Workers",
  "Bookkeeping and Accounting Clerks",
  "Management Analysts",
  "Market Research Analysts",
  "Project Management Specialists",
  "Childcare Workers",
  "First-Line Supervisors of Office Workers",
  "Secondary School Teachers",
  "Electricians",
  "Carpenters",
  "Receptionists and Information Clerks",
  "Licensed Practical Nurses",
  "Financial Managers",
  "Substitute Teachers",
  "Human Resources Specialists",
  "Sales Representatives, Wholesale",
  "Industrial Truck Operators",
  "Bartenders",
  "Dental Assistants",
  "Maids and Housekeeping Cleaners",
  "Plumbers and Pipefitters",
  "Insurance Sales Agents",
  "Pharmacy Technicians",
  "Social Workers",
  "Passenger Vehicle Drivers",
  "Lawyers",
  "Computer Systems Analysts",
  "Personal Financial Advisors",
  "Property and Real Estate Managers",
  "Hairdressers and Cosmetologists",
  "Automotive Service Technicians",
  "Executive Secretaries",
  "Cooks, Fast Food",
  "Substance Abuse Counselors",
  "Firefighters",
  "Physicians",
  "Loan Officers",
  "Paramedics and EMTs",
  "Machinists",
  "Welders",
  "Bus Drivers, School",
  "Compliance Officers",
  "Civil Engineers",
  "Computer User Support Specialists",
  "Mechanical Engineers",
  "Preschool Teachers",
  "Physical Therapists",
  "First-Line Supervisors of Construction Workers",
  "Sales Managers",
  "Computer and Information Systems Managers",
  "Pharmacists",
  "Real Estate Agents",
  "Painters, Construction",
  "Police Officers",
  "Medical Secretaries",
  "Correctional Officers",
  "Paralegals and Legal Assistants",
  "Veterinary Technicians",
  "Graphic Designers",
  "Roofers",
  "Training and Development Specialists",
  "Clinical Laboratory Technicians",
  "Purchasing Agents",
  "Dental Hygienists",
  "Environmental Scientists",
  "Network and Systems Administrators",
  "Speech-Language Pathologists",
  "Interpreters and Translators",
  "Occupational Therapists",
  "Web Developers",
  "Database Administrators",
  "Veterinarians",

  // ── Additional BLS occupations (not in the top 100) ────────────────────
  // A–B
  "Accountants",
  "Actors",
  "Actuaries",
  "Acupuncturists",
  "Administrative Law Judges",
  "Adult Literacy Teachers",
  "Advertising Managers",
  "Advertising Sales Agents",
  "Aerospace Engineers",
  "Agricultural Engineers",
  "Agricultural Inspectors",
  "Agricultural Workers",
  "Air Traffic Controllers",
  "Aircraft Mechanics",
  "Aircraft Pilots",
  "Airline Pilots",
  "Ambulance Drivers",
  "Amusement Park Attendants",
  "Anesthesiologists",
  "Animal Breeders",
  "Animal Control Workers",
  "Animal Trainers",
  "Anthropologists",
  "Appraisers",
  "Arbitrators",
  "Architects",
  "Archivists",
  "Art Directors",
  "Athletic Trainers",
  "Atmospheric Scientists",
  "Audiologists",
  "Audio Engineers",
  "Automotive Body Repairers",
  "Automotive Glass Installers",
  "Avionics Technicians",
  "Baggage Porters",
  "Bailiffs",
  "Bakers",
  "Bank Tellers",
  "Barbers",
  "Bicycle Repairers",
  "Bill Collectors",
  "Biochemists",
  "Bioinformatics Scientists",
  "Biological Technicians",
  "Biomedical Engineers",
  "Boilermakers",
  "Brickmasons",
  "Broadcast Technicians",
  "Brokerage Clerks",
  "Budget Analysts",
  "Bus Drivers, Transit",
  "Butchers",
  "Buyers",

  // C
  "Cabinetmakers",
  "Camera Operators",
  "Captains of Water Vessels",
  "Cardiovascular Technologists",
  "Cargo Agents",
  "Cartographers",
  "Cement Masons",
  "Chefs",
  "Chemical Engineers",
  "Chemical Technicians",
  "Chemists",
  "Chief Executives",
  "Child and Family Social Workers",
  "Chiropractors",
  "Choreographers",
  "City Planners",
  "Claims Adjusters",
  "Clergy",
  "Clinical Psychologists",
  "Coaches",
  "Coating Machine Operators",
  "Commercial Divers",
  "Commercial Pilots",
  "Communications Equipment Operators",
  "Community Health Workers",
  "Compensation Managers",
  "Computer Hardware Engineers",
  "Computer Network Architects",
  "Computer Programmers",
  "Computer Science Teachers",
  "Concierges",
  "Conservation Scientists",
  "Construction Inspectors",
  "Construction Managers",
  "Control and Valve Installers",
  "Conveyor Operators",
  "Coroners",
  "Correspondence Clerks",
  "Cost Estimators",
  "Counseling Psychologists",
  "Court Reporters",
  "Craft Artists",
  "Crane Operators",
  "Credit Analysts",
  "Credit Counselors",
  "Crossing Guards",
  "Curators",
  "Customs Brokers",
  "Customs Officers",
  "Cutting Machine Operators",

  // D
  "Dancers",
  "Data Entry Keyers",
  "Data Scientists",
  "Demonstrators",
  "Dentists",
  "Dermatologists",
  "Derrick Operators",
  "Desktop Publishers",
  "Detectives",
  "Diagnostic Medical Sonographers",
  "Diesel Mechanics",
  "Dietitians",
  "Dining Room Attendants",
  "Dispatchers",
  "Door-to-Door Sales Workers",
  "Drafters",
  "Dredge Operators",
  "Drilling Machine Operators",
  "Drywall Installers",
  "Duty Officers",

  // E
  "Earth Drillers",
  "Economists",
  "Editors",
  "Education Administrators",
  "Electrical Engineers",
  "Electrical Installers",
  "Electrical Power Line Workers",
  "Electromechanical Technicians",
  "Electronic Equipment Assemblers",
  "Electronics Engineers",
  "Elevator Installers",
  "Embalmers",
  "Emergency Management Directors",
  "Engine Assemblers",
  "Engineering Managers",
  "Engineering Technicians",
  "Entertainers",
  "Environmental Compliance Inspectors",
  "Environmental Engineers",
  "Environmental Health Specialists",
  "Epidemiologists",
  "Etchers",
  "Excavating Machine Operators",
  "Exercise Physiologists",
  "Explosive Workers",
  "Extraction Workers",

  // F
  "Fabric Cutters",
  "Fabricators",
  "Farm Equipment Mechanics",
  "Farm Labor Contractors",
  "Farm Workers",
  "Fashion Designers",
  "Fence Erectors",
  "Fiberglass Laminators",
  "File Clerks",
  "Film Editors",
  "Financial Analysts",
  "Financial Clerks",
  "Financial Examiners",
  "Fire Inspectors",
  "Fish and Game Wardens",
  "Fishing Workers",
  "Fitness Trainers",
  "Flight Attendants",
  "Floor Layers",
  "Floor Sanders",
  "Floral Designers",
  "Florists",
  "Food Batchmakers",
  "Food Scientists",
  "Food Service Managers",
  "Foreign Language Teachers",
  "Forensic Science Technicians",
  "Forest Fire Inspectors",
  "Foresters",
  "Foundry Workers",
  "Fundraisers",
  "Funeral Attendants",
  "Funeral Directors",
  "Furnace Operators",
  "Furniture Finishers",

  // G
  "Gaming Cage Workers",
  "Gaming Dealers",
  "Gaming Managers",
  "Gaming Surveillance Officers",
  "Gas Compressor Operators",
  "Gas Plant Operators",
  "Gem Cutters",
  "Geneticists",
  "Geographers",
  "Geological Technicians",
  "Geologists",
  "Geoscientists",
  "Glaziers",
  "Graders",
  "Grinding Machine Operators",
  "Groundskeepers",

  // H
  "Hazardous Materials Removal Workers",
  "Health Educators",
  "Health Information Technologists",
  "Health Services Managers",
  "Hearing Aid Specialists",
  "Heat Treating Operators",
  "Helpers, Brickmasons",
  "Helpers, Electricians",
  "Helpers, Painters",
  "Helpers, Plumbers",
  "Highway Maintenance Workers",
  "Historians",
  "Home Appliance Repairers",
  "Home Economics Teachers",
  "Home Inspectors",
  "Hosts and Hostesses",
  "Hotel Desk Clerks",
  "Human Resources Assistants",
  "Human Resources Managers",
  "HVAC Technicians",
  "Hydrologists",

  // I
  "Illustrators",
  "Immigration Officers",
  "Industrial Designers",
  "Industrial Engineers",
  "Industrial Machinery Mechanics",
  "Industrial Production Managers",
  "Information Security Analysts",
  "Inspectors",
  "Instructional Coordinators",
  "Insulation Workers",
  "Insurance Adjusters",
  "Insurance Appraisers",
  "Insurance Claims Clerks",
  "Insurance Underwriters",
  "Interior Designers",
  "Ironworkers",

  // J
  "Jewelers",
  "Judges",
  "Judicial Law Clerks",

  // K
  "Kindergarten Teachers",
  "Kitchen Workers",

  // L
  "Lab Technicians",
  "Labor Relations Specialists",
  "Land Surveyors",
  "Lathe Operators",
  "Laundry Workers",
  "Law Clerks",
  "Leather Workers",
  "Legal Secretaries",
  "Legislators",
  "Librarians",
  "Library Assistants",
  "Library Technicians",
  "Lifeguards",
  "Loan Interviewers",
  "Locksmiths",
  "Locomotive Engineers",
  "Logging Workers",
  "Logisticians",

  // M
  "Machine Feeders",
  "Magnetic Resonance Imaging Technologists",
  "Mail Carriers",
  "Mail Clerks",
  "Makeup Artists",
  "Mammography Technicians",
  "Manufactured Building Installers",
  "Marine Biologists",
  "Marine Engineers",
  "Marriage and Family Therapists",
  "Massage Therapists",
  "Material Engineers",
  "Material Recording Clerks",
  "Materials Scientists",
  "Mathematicians",
  "Meat Packers",
  "Mediators",
  "Medical Equipment Preparers",
  "Medical Equipment Repairers",
  "Medical Records Specialists",
  "Medical Scientists",
  "Medical Transcriptionists",
  "Meeting Planners",
  "Mental Health Counselors",
  "Metal Workers",
  "Meteorologists",
  "Meter Readers",
  "Microbiologists",
  "Middle School Teachers",
  "Milling Machine Operators",
  "Millwrights",
  "Mine Shuttle Car Operators",
  "Mining Engineers",
  "Mining Machine Operators",
  "Mobile Home Installers",
  "Models",
  "Molding Machine Operators",
  "Morticians",
  "Motion Picture Projectionists",
  "Motorboat Mechanics",
  "Motorcycle Mechanics",
  "Museum Technicians",
  "Music Directors",
  "Musicians",

  // N
  "Natural Sciences Managers",
  "Naval Architects",
  "Neonatal Nurses",
  "Network Architects",
  "New Accounts Clerks",
  "News Analysts",
  "Nuclear Engineers",
  "Nuclear Medicine Technologists",
  "Nuclear Power Reactor Operators",
  "Nuclear Technicians",
  "Nurse Anesthetists",
  "Nurse Midwives",
  "Nurse Practitioners",
  "Nutritionists",

  // O
  "Obstetricians",
  "Occupational Health Technicians",
  "Occupational Safety Specialists",
  "Office Machine Operators",
  "Operating Engineers",
  "Operations Research Analysts",
  "Ophthalmic Laboratory Technicians",
  "Ophthalmic Medical Technicians",
  "Opticians",
  "Optometrists",
  "Oral Surgeons",
  "Order Clerks",
  "Orderlies",
  "Orthodontists",
  "Orthoptists",
  "Orthotists",

  // P
  "Packaging Machine Operators",
  "Packers",
  "Painting Machine Operators",
  "Paleontologists",
  "Paper Goods Machine Operators",
  "Paperhangers",
  "Park Rangers",
  "Parking Attendants",
  "Parking Enforcement Officers",
  "Parts Salespersons",
  "Pathologists",
  "Patient Representatives",
  "Paving Equipment Operators",
  "Payroll Clerks",
  "Pediatricians",
  "Personal Care Attendants",
  "Pest Control Workers",
  "Petroleum Engineers",
  "Petroleum Pump Operators",
  "Phlebotomists",
  "Photoengravers",
  "Photographers",
  "Photographic Process Workers",
  "Physical Therapist Aides",
  "Physical Therapist Assistants",
  "Physician Assistants",
  "Physicists",
  "Pile Driver Operators",
  "Pilots",
  "Pipefitters",
  "Plasterers",
  "Plating Machine Operators",
  "Podiatrists",
  "Political Scientists",
  "Postal Service Clerks",
  "Postal Service Mail Sorters",
  "Postal Workers",
  "Postmasters",
  "Poultry Cutters",
  "Power Distributors",
  "Power Plant Operators",
  "Precision Instrument Repairers",
  "Printing Press Operators",
  "Private Detectives",
  "Probation Officers",
  "Procurement Clerks",
  "Producers",
  "Production Clerks",
  "Production Supervisors",
  "Proofreaders",
  "Prosthetists",
  "Protective Service Workers",
  "Psychiatric Aides",
  "Psychiatric Technicians",
  "Psychiatrists",
  "Psychologists",
  "Public Relations Managers",
  "Public Relations Specialists",
  "Pump Operators",

  // Q
  "Quality Control Analysts",
  "Quality Control Inspectors",

  // R
  "Radiation Therapists",
  "Radio Operators",
  "Radiologic Technologists",
  "Radiologists",
  "Railroad Brake Operators",
  "Railroad Conductors",
  "Railroad Workers",
  "Range Managers",
  "Real Estate Brokers",
  "Recreational Therapists",
  "Recreational Vehicle Service Technicians",
  "Recycling Workers",
  "Refractory Materials Repairers",
  "Refrigeration Mechanics",
  "Refuse Collectors",
  "Rehabilitation Counselors",
  "Reinforcing Iron Workers",
  "Religious Workers",
  "Reporters",
  "Reservation Agents",
  "Residential Advisors",
  "Respiratory Therapists",
  "Retail Buyers",
  "Riggers",
  "Rock Splitters",
  "Rotary Drill Operators",

  // S
  "Safety Engineers",
  "Sailors",
  "Sales Engineers",
  "Sawing Machine Operators",
  "School Bus Monitors",
  "School Counselors",
  "School Psychologists",
  "Segmental Pavers",
  "Semiconductor Processors",
  "Septic Tank Servicers",
  "Set Designers",
  "Sewing Machine Operators",
  "Sheet Metal Workers",
  "Ship Engineers",
  "Ship Loaders",
  "Shipping Clerks",
  "Shoe Machine Operators",
  "Signal Repairers",
  "Skincare Specialists",
  "Slaughterers",
  "Social Science Research Assistants",
  "Social Service Assistants",
  "Sociologists",
  "Software Quality Assurance Analysts",
  "Soil Scientists",
  "Solar Photovoltaic Installers",
  "Sonographers",
  "Sound Engineering Technicians",
  "Sound Engineers",
  "Special Education Teachers",
  "Speech Therapists",
  "Sports Officials",
  "Stationary Engineers",
  "Statistical Assistants",
  "Statisticians",
  "Steamfitters",
  "Stock Clerks",
  "Stonemasons",
  "Structural Iron Workers",
  "Structural Metal Fabricators",
  "Substance Abuse Social Workers",
  "Subway Operators",
  "Surgeons",
  "Surgical Assistants",
  "Surgical Technologists",
  "Survey Researchers",
  "Surveyors",
  "Switchboard Operators",

  // T
  "Tailers",
  "Tailors",
  "Tank Car Loaders",
  "Taper Operators",
  "Tax Examiners",
  "Tax Preparers",
  "Taxi Drivers",
  "Technical Writers",
  "Telecommunications Equipment Installers",
  "Telecommunications Workers",
  "Telemarketers",
  "Telephone Operators",
  "Terrazzo Workers",
  "Textile Bleaching Operators",
  "Textile Machine Operators",
  "Theatrical Makeup Artists",
  "Tile Setters",
  "Timing Device Assemblers",
  "Tire Builders",
  "Tire Repairers",
  "Title Examiners",
  "Tool and Die Makers",
  "Tool Grinders",
  "Tour Guides",
  "Traffic Technicians",
  "Transit Police",
  "Transportation Inspectors",
  "Transportation Managers",
  "Travel Agents",
  "Travel Guides",
  "Tree Trimmers",
  "Tutors",
  "Typists",

  // U
  "Umpires",
  "Upholsterers",
  "Urban Planners",
  "Ushers",
  "Utility Meter Readers",

  // V
  "Valets",
  "Vending Machine Servicers",
  "Veterinary Assistants",

  // W
  "Wastewater Treatment Operators",
  "Watch Repairers",
  "Water Treatment Operators",
  "Web Administrators",
  "Weighers",
  "Welding Machine Operators",
  "Wellhead Pumpers",
  "Wind Turbine Technicians",
  "Woodworkers",
  "Word Processors",
  "Writers",

  // X–Z
  "X-Ray Technicians",
  "Youth Workers",
  "Zoologists",
  "Zookeepers",

  // ── More occupations (miscellaneous BLS & O*NET titles) ────────────────
  "Acrobats",
  "Adhesive Bonding Machine Operators",
  "Administrative Services Managers",
  "Agricultural Technicians",
  "Air Conditioning Mechanics",
  "Airport Security Screeners",
  "Anesthesiologist Assistants",
  "Appliance Repairers",
  "Aquaculture Workers",
  "Arborists",
  "Assessors",
  "Astronomers",
  "Audio-Visual Equipment Technicians",
  "Auditors",
  "Automated Teller Machine Servicers",
  "Baker Helpers",
  "Biofuels Technicians",
  "Biological Scientists",
  "Biostatisticians",
  "Blockchain Engineers",
  "Boat Builders",
  "Bookbinders",
  "Broadcast Engineers",
  "Building Inspectors",
  "Bus Mechanics",
  "Business Intelligence Analysts",
  "Cardiologists",
  "Cardiovascular Surgeons",
  "Casino Hosts",
  "Casters",
  "Cemetery Workers",
  "Certified Public Accountants",
  "Chemical Plant Operators",
  "Child Life Specialists",
  "Chimney Sweeps",
  "Clinical Nurse Specialists",
  "Cloud Engineers",
  "CNC Machine Operators",
  "Coal Mine Workers",
  "Collections Agents",
  "Commodities Traders",
  "Communications Managers",
  "Community Service Managers",
  "Computer Forensics Analysts",
  "Computer Numerical Control Programmers",
  "Conservation Technicians",
  "Construction Equipment Operators",
  "Copy Editors",
  "Cosmetologists",
  "Couriers",
  "Court Administrators",
  "Credit Managers",
  "Crime Scene Investigators",
  "Criminologists",
  "Critical Care Nurses",
  "Crop Duster Pilots",
  "Culinarians",
  "Customs Inspectors",
  "Cyber Security Analysts",
  "Cytotechnologists",
  "Dance Teachers",
  "Day Care Workers",
  "Deck Officers",
  "Delivery Drivers",
  "Demolition Workers",
  "Dental Lab Technicians",
  "DevOps Engineers",
  "Dialysis Technicians",
  "Disc Jockeys",
  "Distribution Managers",
  "Dog Groomers",
  "Domestic Workers",
  "Drilling Engineers",
  "Drone Operators",
  "Drug Counselors",
  "Dry Cleaning Workers",
  "Drywall Finishers",
  "E-Commerce Analysts",
  "Ecologists",
  "Electric Motor Repairers",
  "Electrical Drafters",
  "Electroplaters",
  "Emergency Dispatchers",
  "Emergency Room Nurses",
  "Emergency Room Physicians",
  "Energy Auditors",
  "Energy Engineers",
  "Enrollment Counselors",
  "Environmental Consultants",
  "Environmental Technicians",
  "Equine Veterinarians",
  "Ergonomists",
  "Estimators",
  "Event Planners",
  "Evidence Technicians",
  "Executive Chefs",
  "Exercise Trainers",
  "Exhibit Designers",
  "Expeditors",
  "Explosives Technicians",
  "Extension Agents",
  "Facilities Managers",
  "Factory Workers",
  "Family Physicians",
  "Farm Managers",
  "Farriers",
  "Film Directors",
  "Film Producers",
  "Financial Planners",
  "Fire Chiefs",
  "Fire Protection Engineers",
  "First Responders",
  "Fish Hatchery Managers",
  "Fitters",
  "Fleet Managers",
  "Flight Engineers",
  "Flight Instructors",
  "Food Inspectors",
  "Food Technologists",
  "Forensic Accountants",
  "Forestry Technicians",
  "Fraud Examiners",
  "Freight Agents",
  "Front Desk Agents",
  "Fuel Cell Engineers",
  "Game Wardens",
  "Garage Door Installers",
  "Gardeners",
  "Gas Station Attendants",
  "General Practitioners",
  "Genetic Counselors",
  "Geophysicists",
  "Geriatricians",
  "Glass Blowers",
  "Golf Course Superintendents",
  "Grain Elevator Operators",
  "Grant Writers",
  "Greenhouse Workers",
  "Guidance Counselors",
  "Gynecologists",
  "Harbor Masters",
  "Health Inspectors",
  "Healthcare Social Workers",
  "Hearing Officers",
  "Heavy Equipment Operators",
  "Helicopter Pilots",
  "Highway Engineers",
  "Histotechnologists",
  "Home Stagers",
  "Homeland Security Agents",
  "Hospice Workers",
  "Hospital Administrators",
  "Hotel Managers",
  "Housekeepers",
  "Housing Inspectors",
  "Hydraulic Engineers",
  "Hydrographic Surveyors",
  "Immigration Lawyers",
  "Immunologists",
  "Import Specialists",
  "Industrial Hygienists",
  "Infectious Disease Specialists",
  "Intelligence Analysts",
  "Intensive Care Nurses",
  "Interior Decorators",
  "Internists",
  "Inventory Clerks",
  "Investment Bankers",
  "IT Managers",
  "IT Specialists",
  "Janitorial Supervisors",
  "Job Coaches",
  "Kennel Attendants",
  "Lab Assistants",
  "Laboratory Managers",
  "Lamination Workers",
  "Land Acquisition Agents",
  "Landscape Architects",
  "Laser Technicians",
  "Lathers",
  "Lead Abatement Workers",
  "Lease Operators",
  "Loan Processors",
  "Long Haul Truck Drivers",
  "Loss Prevention Specialists",
  "Lumber Graders",
  "Machine Shop Supervisors",
  "Mail Handlers",
  "Maintenance Supervisors",
  "Managed Care Coordinators",
  "Manicurists",
  "Manufacturing Engineers",
  "Map Technicians",
  "Marine Mechanics",
  "Market Research Interviewers",
  "Marketing Managers",
  "Marketing Specialists",
  "Master Electricians",
  "Mechanical Drafters",
  "Mechanical Inspectors",
  "Media Buyers",
  "Medical Billing Specialists",
  "Medical Coders",
  "Medical Directors",
  "Medical Dosimetrists",
  "Medical Illustrators",
  "Medical Lab Scientists",
  "Medical Technologists",
  "Merchandise Displayers",
  "Metal Fabricators",
  "Midwives",
  "Military Officers",
  "Mining Safety Inspectors",
  "Mixers",
  "Mobile Crane Operators",
  "Molecular Biologists",
  "Mortgage Brokers",
  "MRI Technologists",
  "Multimedia Artists",
  "Museum Curators",
  "Music Teachers",
  "Music Therapists",
  "Nail Technicians",
  "Nanoscience Technicians",
  "Naturopathic Physicians",
  "Navigators",
  "Neonatal Intensive Care Nurses",
  "Nephrologists",
  "Neurologists",
  "Neuropsychologists",
  "Neurosurgeons",
  "Night Auditors",
  "Notaries",
  "Nuclear Monitoring Technicians",
  "Nurse Educators",
  "Nursing Home Administrators",
  "Nutrition Consultants",
  "Occupational Health Nurses",
  "Oceanographers",
  "Office Managers",
  "Oil Field Workers",
  "Oncologists",
  "Operating Room Nurses",
  "Operations Managers",
  "Ophthalmologists",
  "Optical Engineers",
  "Orthodontic Assistants",
  "Outdoor Recreation Workers",
  "Outreach Workers",
  "Paint Sprayers",
  "Parachute Riggers",
  "Park Naturalists",
  "Patent Agents",
  "Patent Examiners",
  "Pawnbrokers",
  "Paymaster",
  "Pediatric Nurses",
  "Perfusionists",
  "Personal Trainers",
  "Pet Sitters",
  "Petroleum Geologists",
  "Pharmaceutical Sales Representatives",
  "Photo Editors",
  "Physical Science Technicians",
  "Pipeline Workers",
  "Plant Managers",
  "Plant Scientists",
  "Podiatric Medical Assistants",
  "Police Dispatchers",
  "Police Sergeants",
  "Pool Technicians",
  "Postal Inspectors",
  "Pottery Workers",
  "Poultry Scientists",
  "Press Secretaries",
  "Prevention Specialists",
  "Principals",
  "Print Binding Workers",
  "Process Servers",
  "Product Managers",
  "Production Assistants",
  "Program Coordinators",
  "Program Directors",
  "Program Managers",
  "Proof Machine Operators",
  "Property Appraisers",
  "Property Inspectors",
  "Prosthodontists",
  "Psychiatric Nurses",
  "Public Defenders",
  "Public Health Educators",
  "Public Safety Dispatchers",
  "Pulmonologists",
  "Pump Mechanics",
  "Quarry Workers",
  "Radar Technicians",
  "Radio Announcers",
  "Railroad Engineers",
  "Ranch Hands",
  "Reading Specialists",
  "Recreation Coordinators",
  "Recycling Coordinators",
  "Regional Planners",
  "Registered Dietitians",
  "Regulatory Affairs Specialists",
  "Relay Technicians",
  "Research Assistants",
  "Research Scientists",
  "Reservation Clerks",
  "Restaurant Managers",
  "Revenue Agents",
  "Rheumatologists",
  "Robotics Engineers",
  "Roller Operators",
  "Rotary Press Operators",
  "Safety Inspectors",
  "Sales Clerks",
  "Sanitation Workers",
  "Sawmill Workers",
  "School Administrators",
  "School Librarians",
  "School Nurses",
  "Scientific Illustrators",
  "Scuba Diving Instructors",
  "Securities Traders",
  "Security Consultants",
  "Seismologists",
  "Service Station Attendants",
  "Shipfitters",
  "Sign Language Interpreters",
  "Signal Workers",
  "Silviculturists",
  "Ski Patrol Workers",
  "Social Media Managers",
  "Software Architects",
  "Software Testers",
  "Solar Energy Technicians",
  "Sous Chefs",
  "Spa Managers",
  "Stage Managers",
  "Station Agents",
  "Steamfitters and Pipefitters",
  "Steel Workers",
  "Stenographers",
  "Stock Brokers",
  "Studio Engineers",
  "Stunt Performers",
  "Superintendent of Schools",
  "Supply Chain Managers",
  "Surgeon Assistants",
  "Swimming Pool Servicers",
  "Systems Engineers",
  "Tank Cleaners",
  "Tattoo Artists",
  "Teacher Aides",
  "Technical Illustrators",
  "Technology Directors",
  "Telecommunications Analysts",
  "Television Producers",
  "Test Pilots",
  "Textile Designers",
  "Theatrical Directors",
  "Tool Makers",
  "Tow Truck Drivers",
  "Tower Crane Operators",
  "Toxicologists",
  "Traffic Engineers",
  "Train Engineers",
  "Translators",
  "Transplant Coordinators",
  "Transportation Planners",
  "Trauma Surgeons",
  "Treasury Analysts",
  "Truck Dispatchers",
  "Tugboat Captains",
  "Turbine Operators",
  "UX Designers",
  "Ultrasound Technicians",
  "Undercover Agents",
  "University Professors",
  "Urologists",
  "Utility Workers",
  "Vascular Surgeons",
  "Vehicle Inspectors",
  "Venture Capitalists",
  "Veterinary Pathologists",
  "Veterinary Surgeons",
  "Video Editors",
  "Video Game Designers",
  "Vocational Counselors",
  "Vocational Nurses",
  "Volunteer Coordinators",
  "Warehouse Workers",
  "Waste Management Workers",
  "Water Quality Technicians",
  "Weather Forecasters",
  "Wedding Planners",
  "Wildfire Fighters",
  "Wildlife Biologists",
  "Wildlife Officers",
  "Wine Makers",
  "Wireless Technicians",
  "Wood Pattern Makers",
  "Woodworking Machine Operators",
  "Workers Compensation Specialists",
  "Yacht Captains",
  "Yoga Instructors",
  "Youth Counselors",
  "Zoning Inspectors",
];
