// ~600 podcast names for autocomplete hints
export const mostPopularPodcastsHints: string[] = [
  // Top 100 (the actual answers)
  "The Joe Rogan Experience", "Crime Junkie", "The Daily", "Call Her Daddy",
  "SmartLess", "Stuff You Should Know", "This American Life",
  "This Past Weekend w/ Theo Von", "Dateline NBC",
  "New Heights with Jason & Travis Kelce", "Morbid", "Bad Friends",
  "The Megyn Kelly Show", "Rotten Mango", "The Breakfast Club", "Radiolab",
  "MrBallen Podcast: Strange, Dark & Mysterious Stories",
  "The MeidasTouch Podcast", "The Mel Robbins Podcast", "The Tucker Carlson Show",
  "Million Dollaz Worth of Game", "TED Talks Daily", "My Favorite Murder",
  "Pod Save America", "Club Shay Shay", "Conan O'Brien Needs a Friend",
  "Dumb Blonde", "Planet Money", "Not Gonna Lie with Kylie Kelce",
  "Impaulsive with Logan Paul", "Murder, Mystery & Makeup", "The Basement Yard",
  "The Moth", "The Diary Of A CEO with Steven Bartlett", "Candace",
  "No Jumper", "Up First from NPR", "Good Hang with Amy Poehler",
  "The Shawn Ryan Show", "The Pat McAfee Show", "Distractible",
  "Pardon My Take", "The Joe Budden Podcast", "Huberman Lab",
  "The 85 South Show", "How I Built This with Guy Raz",
  "The Charlie Kirk Show", "The Ben Shapiro Show", "The Bill Simmons Podcast",
  "Armchair Expert with Dax Shepard", "Dan Bongino Show", "The Ramsey Show",
  "Fresh Air", "NPR News Now", "On Purpose with Jay Shetty", "48 Hours",
  "Serial", "Morning Wire", "The Ezra Klein Show",
  "Stuff You Missed in History Class", "Wait Wait... Don't Tell Me!",
  "Hidden Brain", "Behind the Bastards", "The Tim Dillon Show",
  "2 Bears, 1 Cave", "Park Predators", "The Oprah Podcast",
  "Joel Osteen Podcast", "Dark Downeast", "The Bible in a Year",
  "Lex Fridman Podcast", "The Glenn Beck Program", "The Mark Levin Podcast",
  "Cold Case Files", "True Crime with Kendall Rae",
  "The Dan Le Batard Show with Stugotz", "Las Culturistas",
  "Small Town Murder", "American History Tellers",
  "Crime Stories with Nancy Grace", "The Way I Heard It with Mike Rowe",
  "Giggly Squad", "Pod Save the World", "The Bulwark Podcast",
  "Freakonomics Radio", "The Why Files", "The Matt Walsh Show",
  "The Journal.", "Money Rehab with Nicole Lapin", "Pivot",
  "The Herd with Colin Cowherd", "Sword and Scale", "The Dan Patrick Show",
  "Last Podcast on the Left", "Anything Goes with Emma Chamberlain",
  "Two Ts in a Pod", "The Jordan B. Peterson Podcast", "Today, Explained",
  "Flagrant", "Kill Tony",

  // ==================== TRUE CRIME ====================
  "Your Own Backyard", "Casefile True Crime", "Generation Why",
  "In the Dark", "Criminal", "Scam Goddess", "True Crime Obsessed",
  "Something Was Wrong", "Dr. Death", "Over My Dead Body",
  "CounterClock", "Dirty John", "American Scandal",
  "The Shrink Next Door", "Swindled", "Up and Vanished",
  "S-Town", "Accused", "The Vanished", "The Deck",
  "Unsolved Murders: True Crime Stories", "True Crime Garage",
  "Anatomy of Murder", "Court Junkie", "Trace Evidence",
  "Culpable", "Bear Brook", "Chameleon", "Heaven's Gate",
  "Betrayal", "Dead and Gone", "Blood Ties",
  "To Live and Die in LA", "Root of Evil", "Catch and Kill",
  "Broken Harts", "American Predator", "And That's Why We Drink",
  "Let's Not Meet", "True Crime All the Time",
  "Red Collar", "Unsolved Mysteries",

  // ==================== COMEDY & ENTERTAINMENT ====================
  "Bill Burr's Monday Morning Podcast", "How Did This Get Made?",
  "Comedy Bang! Bang!", "My Brother, My Brother and Me",
  "Pod Meets World", "Fly on the Wall with Dana Carvey and David Spade",
  "Chicks in the Office", "Normal Gossip", "Maintenance Phase",
  "You're Wrong About", "Sounds Like a Cult",
  "Baby, This Is Keke Palmer", "Girls Gotta Eat",
  "Betches Sup", "Dear Hank and John", "Tigerbelly",
  "Brilliant Idiots", "The Fighter and the Kid",
  "Good One: A Podcast About Jokes", "WTF with Marc Maron",
  "The Adam Carolla Show", "Office Ladies",

  // ==================== NEWS & POLITICS ====================
  "The NPR Politics Podcast", "The Rachel Maddow Show",
  "On the Media", "Throughline", "Code Switch", "Reveal",
  "The Indicator from Planet Money", "Vox Conversations",
  "Making Sense with Sam Harris", "The Rest Is Politics",
  "The Remnant with Jonah Goldberg", "Blocked and Reported",
  "Strict Scrutiny", "Pantsuit Politics", "Pod Save the People",
  "Stay Tuned with Preet", "Global News Podcast",
  "The Intelligence", "The Argument", "Matter of Opinion",
  "Verdict with Ted Cruz", "Ruthless Podcast",

  // ==================== TECHNOLOGY ====================
  "Darknet Diaries", "Hard Fork", "The Vergecast",
  "Waveform: The MKBHD Podcast", "Search Engine with PJ Vogt",
  "Decoder with Nilay Patel", "All-In Podcast", "Acquired",
  "Techmeme Ride Home", "Syntax.fm",
  "Software Engineering Daily", "Recode Decode",
  "On with Kara Swisher", "Masters of Scale",

  // ==================== BUSINESS & FINANCE ====================
  "The Tim Ferriss Show", "Invest Like the Best",
  "We Study Billionaires", "Marketplace", "Motley Fool Money",
  "Earn Your Leisure", "The Prof G Pod with Scott Galloway",
  "The School of Greatness", "The Ed Mylett Show",
  "Entrepreneurs on Fire", "The James Altucher Show",
  "WorkLife with Adam Grant", "HBR IdeaCast",
  "The Twenty Minute VC", "My First Million",
  "Founders Podcast", "The GaryVee Audio Experience",
  "The Patrick Bet-David Podcast", "The Game with Alex Hormozi",
  "Impact Theory with Tom Bilyeu", "Young and Profiting",

  // ==================== HEALTH & SCIENCE ====================
  "Science Vs", "Ologies with Alie Ward",
  "StarTalk Radio with Neil deGrasse Tyson",
  "10% Happier with Dan Harris", "We Can Do Hard Things",
  "The Ultimate Human with Gary Brecka",
  "Peter Attia Drive", "The Happiness Lab",
  "Therapy for Black Girls", "The Goop Podcast",
  "Rich Roll Podcast", "Found My Fitness",
  "Mind Pump", "The Model Health Show",

  // ==================== HISTORY & EDUCATION ====================
  "Dan Carlin's Hardcore History", "Revolutions",
  "99% Invisible", "TED Radio Hour", "Revisionist History",
  "In Our Time", "Fall of Civilizations Podcast",
  "The History of Rome", "You're Dead to Me",
  "Everything Everywhere Daily", "The Rest Is History",
  "Slow Burn", "Cautionary Tales", "Philosophize This!",
  "Conversations with Tyler", "Short Wave",
  "Science Friday", "Overheard at National Geographic",

  // ==================== SPORTS ====================
  "ESPN Daily", "The Ryen Russillo Podcast", "The Lowe Post",
  "The Fantasy Footballers", "Rich Eisen Show",
  "Bussin' With the Boys", "Men in Blazers",
  "Effectively Wild", "All the Smoke", "Nightcap with Shannon Sharpe",
  "Spittin' Chiclets", "Full Send Podcast",
  "Fore Play Golf Podcast", "30 for 30 Podcasts",
  "The Ringer NBA Show", "The Ringer NFL Show",
  "Locked On NFL", "Locked On NBA",
  "Gil's Arena", "KG Certified",

  // ==================== MUSIC ====================
  "Song Exploder", "Disgraceland", "Drink Champs",
  "New Rory & Mal", "Questlove Supreme",
  "Broken Record with Rick Rubin", "Switched on Pop",
  "Strong Songs",

  // ==================== STORYTELLING & FICTION ====================
  "Welcome to Night Vale", "The NoSleep Podcast",
  "The Adventure Zone", "Magnus Archives",
  "Alice Isn't Dead", "Limetown", "Homecoming",
  "Blackout", "The Black Tapes", "Archive 81",
  "Midnight Burger", "The White Vault",

  // ==================== SOCIETY & CULTURE ====================
  "Pop Culture Happy Hour", "The Rewatchables",
  "If Books Could Kill", "Death, Sex & Money",
  "The Sporkful", "Gastropod", "The Splendid Table",
  "No Such Thing as a Fish", "My Dad Wrote a Porno",
  "Off Menu with Ed Gamble and James Acaster",
  "The Adam Buxton Podcast", "Getting Curious with Jonathan Van Ness",
  "Dare to Lead with Brené Brown", "Unlocking Us",
  "Oprah's Super Soul", "On Being with Krista Tippett",
  "Snap Judgment", "Love and Radio", "Heavyweight",
  "Embedded", "Invisibilia", "1619 Project",
  "Nice White Parents",

  // ==================== RELIGION & SPIRITUALITY ====================
  "The Bible Project Podcast", "Gospel in Life with Tim Keller",
  "The Rise and Fall of Mars Hill", "The RobCast with Rob Bell",
  "Tara Brach", "The Minimalists Podcast",

  // ==================== PARENTING ====================
  "Good Inside with Dr. Becky Kennedy", "Unruffled with Janet Lansbury",
  "The Longest Shortest Time", "One Bad Mother",

  // ==================== BUSINESS EXTRAS ====================
  "Business Wars", "StartUp Podcast", "Side Hustle School",
  "The Tony Robbins Podcast", "Lenny's Podcast",
  "The Indie Hackers Podcast", "a16z Podcast",
  "Noah Kagan Presents", "Developer Tea",
  "The Knowledge Project with Shane Parrish",
];
