export const nbaPlayersHints: string[] = [
  // === All-Time Career Points & Minutes Top 100 ===
  "LeBron James", "Kareem Abdul-Jabbar", "Karl Malone", "Kobe Bryant", "Kevin Durant",
  "Michael Jordan", "Dirk Nowitzki", "Wilt Chamberlain", "Julius Erving", "Moses Malone",
  "Shaquille O'Neal", "Carmelo Anthony", "James Harden", "Dan Issel", "Elvin Hayes",
  "Russell Westbrook", "Oscar Robertson", "Hakeem Olajuwon", "Dominique Wilkins", "George Gervin",
  "DeMar DeRozan", "Tim Duncan", "Kevin Garnett", "Stephen Curry", "Vince Carter",
  "Alex English", "Paul Pierce", "Rick Barry", "John Havlicek", "Reggie Miller",
  "Jerry West", "Artis Gilmore", "Patrick Ewing", "Ray Allen", "Allen Iverson",
  "Charles Barkley", "Robert Parish", "Adrian Dantley", "Dwyane Wade", "Elgin Baylor",
  "Chris Paul", "Damian Lillard", "Clyde Drexler", "Gary Payton", "Larry Bird",
  "Hal Greer", "Giannis Antetokounmpo", "Walt Bellamy", "Pau Gasol", "Bob Pettit",
  "David Robinson", "LaMarcus Aldridge", "Mitch Richmond", "Joe Johnson", "Tom Chambers",
  "Antawn Jamison", "John Stockton", "Bernard King", "Clifford Robinson", "Walter Davis",
  "Dwight Howard", "Tony Parker", "Terry Cummings", "Jamal Crawford", "Anthony Davis",
  "Paul George", "Bob Lanier", "Eddie Johnson", "Gail Goodrich", "Reggie Theus",
  "Dale Ellis", "Scottie Pippen", "Jason Terry", "Chet Walker", "Isiah Thomas",
  "Bob McAdoo", "Zach Randolph", "Mark Aguirre", "Dolph Schayes", "Kyrie Irving",
  "Tracy McGrady", "Glen Rice", "Dave Bing", "Brook Lopez", "Devin Booker",
  "Nikola Jokic", "World B. Free", "Calvin Murphy", "Lou Hudson", "Chris Mullin",
  "Bailey Howell", "Lenny Wilkens", "Magic Johnson", "Shawn Marion", "Nikola Vucevic",
  "Rudy Gay", "Rolando Blackman", "Otis Thorpe", "Jason Kidd", "Earl Monroe",
  "Andre Miller", "Jack Sikma", "Sam Perkins", "Derek Harper", "Jeff Hornacek",
  "Mark Jackson", "Buck Williams",

  // === Current Stars ===
  "Jayson Tatum", "Luka Doncic", "Joel Embiid", "Ja Morant", "Shai Gilgeous-Alexander",
  "Anthony Edwards", "Trae Young", "Donovan Mitchell", "Zion Williamson", "Cade Cunningham",
  "Scottie Barnes", "Evan Mobley", "Paolo Banchero", "Victor Wembanyama", "Chet Holmgren",
  "Jalen Brunson", "Tyrese Haliburton", "Tyrese Maxey", "De'Aaron Fox", "Darius Garland",
  "Desmond Bane", "Anfernee Simons", "Franz Wagner", "Jabari Smith Jr.", "Jalen Green",
  "Brandon Ingram", "Mikal Bridges", "Cameron Johnson", "Jalen Williams", "Lauri Markkanen",
  "Alperen Sengun", "Amen Thompson", "Scoot Henderson", "Brandon Miller", "Gradey Dick",
  "Jaime Jaquez Jr.", "Dereck Lively II", "Keyonte George", "Ausar Thompson",

  // === Recent Stars / Active Veterans ===
  "Jimmy Butler", "Kawhi Leonard", "Bradley Beal", "Zach LaVine", "Jaylen Brown",
  "Julius Randle", "Pascal Siakam", "OG Anunoby", "Domantas Sabonis", "Bam Adebayo",
  "Fred VanVleet", "Jrue Holiday", "Khris Middleton", "Karl-Anthony Towns", "Rudy Gobert",
  "Jarrett Allen", "Miles Bridges", "Terry Rozier", "D'Angelo Russell", "Jordan Poole",
  "Andrew Wiggins", "Jonathan Kuminga", "Klay Thompson", "Draymond Green", "Chris Boucher",
  "Derrick White", "Marcus Smart", "Malcolm Brogdon", "Buddy Hield", "Harrison Barnes",
  "Kevin Love", "Blake Griffin", "DeAndre Jordan", "DeMarcus Cousins", "Marc Gasol",
  "Al Horford", "Andre Drummond", "Hassan Whiteside", "Tobias Harris", "Seth Curry",
  "RJ Barrett", "Evan Fournier", "Kemba Walker", "Otto Porter Jr.", "Marvin Bagley III",
  "Ben Simmons", "Collin Sexton", "John Collins", "Clint Capela", "Myles Turner",
  "Tyler Herro", "Immanuel Quickley", "Josh Hart", "Austin Reaves", "Tre Jones",
  "Dillon Brooks", "Herbert Jones", "Trey Murphy III", "CJ McCollum", "Jonas Valanciunas",
  "Bogdan Bogdanovic", "Bojan Bogdanovic", "Nikola Jovic", "Ivica Zubac", "Norman Powell",
  "Aaron Gordon", "Michael Porter Jr.", "Jamal Murray", "Kentavious Caldwell-Pope",
  "Alex Caruso", "Coby White", "Ayo Dosunmu", "Patrick Williams",
  "Josh Giddey", "Luguentz Dort", "Isaiah Joe", "Cason Wallace",
  "Dejounte Murray", "Tari Eason", "Jabari Walker",

  // === 2000s Stars ===
  "Steve Nash", "Yao Ming", "Tim Hardaway", "Alonzo Mourning", "Latrell Sprewell",
  "Rasheed Wallace", "Ben Wallace", "Chauncey Billups", "Richard Hamilton", "Tayshaun Prince",
  "Amare Stoudemire", "Shawn Kemp", "Gilbert Arenas", "Caron Butler",
  "Elton Brand", "Corey Maggette", "Baron Davis", "Mike Bibby", "Peja Stojakovic",
  "Chris Webber", "Manu Ginobili", "Andre Iguodala", "Tyson Chandler", "Lamar Odom",
  "Chris Bosh", "Michael Redd", "Richard Jefferson", "Jermaine O'Neal", "Ron Artest",
  "Al Jefferson", "Josh Smith", "David West", "Luol Deng", "Emeka Okafor",
  "Carlos Boozer", "Mehmet Okur", "Mike Miller", "Shane Battier", "Kirk Hinrich",
  "Kenyon Martin", "Marcus Camby", "Rajon Rondo", "Nene", "Anderson Varejao",
  "Joakim Noah", "Derrick Rose", "Tyreke Evans", "Brandon Roy",
  "Danny Granger", "Stephen Jackson", "Monta Ellis", "David Lee", "Josh Howard",
  "Gerald Wallace", "Thaddeus Young", "Kyle Lowry", "DeMarre Carroll",

  // === 1990s Stars ===
  "Penny Hardaway", "Horace Grant", "Dennis Rodman", "Detlef Schrempf", "Derrick Coleman",
  "Larry Johnson", "Vin Baker", "Jamal Mashburn", "Allan Houston", "Mookie Blaylock",
  "Dikembe Mutombo", "Rik Smits", "Mahmoud Abdul-Rauf", "Nick Van Exel",
  "Cedric Ceballos", "Sam Cassell", "Antonio McDyess", "Shareef Abdur-Rahim",
  "Stephon Marbury", "Jason Williams", "Damon Stoudamire",
  "Kerry Kittles", "Eddie Jones", "P.J. Brown", "Anthony Mason",
  "Grant Hill", "Juwan Howard", "Christian Laettner", "Jerry Stackhouse",
  "Terrell Brandon", "Rod Strickland", "John Starks", "Derek Anderson",
  "Antonio Davis", "Theo Ratliff", "Raef LaFrentz", "Keith Van Horn",

  // === 1980s Stars ===
  "James Worthy", "Kevin McHale", "Dennis Johnson", "Danny Ainge", "Nate McMillan",
  "Jack Marin", "Otis Birdsong", "Sidney Moncrief", "Terry Porter", "Kevin Johnson",
  "Jeff Malone", "Kiki Vandeweghe", "Fat Lever", "Lafayette Lever", "Xavier McDaniel",
  "Sleepy Floyd", "Doc Rivers", "Chuck Person",
  "Hersey Hawkins", "Derrick McKey", "Dan Majerle", "Jeff Ruland",
  "Tree Rollins", "Robert Reid", "Michael Cooper", "Norm Nixon", "Jamaal Wilkes",
  "Maurice Cheeks", "Andrew Toney", "Bob Gross", "Jim Paxson", "Mychal Thompson",
  "Larry Nance", "Brad Daugherty", "Craig Ehlo", "Hot Rod Williams",
  "Kelly Tripucka", "Bill Laimbeer", "Vinnie Johnson", "Joe Dumars",
  "A.C. Green", "James Edwards", "Sam Mitchell", "Alvin Robertson", "Kevin Willis",

  // === 1970s Stars ===
  "Willis Reed", "Dave DeBusschere", "Bill Bradley", "Walt Frazier", "Dave Cowens",
  "Jo Jo White", "Paul Silas", "Nate Archibald", "Pete Maravich", "Spencer Haywood",
  "Connie Hawkins", "Bob Boozer", "Tom Heinsohn", "Bill Sharman", "Bob Cousy",
  "Bill Russell", "Phil Chenier", "Cazzie Russell", "Wes Unseld", "Bobby Jones",
  "George McGinnis", "Billy Cunningham", "Norm Van Lier", "Dick Barnett",
  "Archie Clark", "Bob Love", "Jerry Sloan", "Nate Thurmond",
  "Paul Westphal", "Bob Dandridge", "Dick Van Arsdale",
  "Tom Van Arsdale", "Zelmo Beaty", "Rudy Tomjanovich",

  // === 1960s / Early Stars ===
  "Sam Jones", "K.C. Jones", "John Kerr", "Cliff Hagan", "Ed Macauley",
  "Jerry Lucas", "Wayne Embry", "Richie Guerin", "Dick McGuire", "Harry Gallatin",
  "Slater Martin", "George Mikan", "Jim Pollard", "Vern Mikkelsen", "Larry Foust",
  "Neil Johnston", "Paul Arizin", "Joe Fulks", "Andy Phillip",

  // === International Stars ===
  "Drazen Petrovic", "Arvydas Sabonis", "Toni Kukoc", "Vlade Divac",
  "Sarunas Marciulionis", "Luc Longley", "Andrew Bogut",
  "Serge Ibaka", "Steven Adams", "Ricky Rubio", "Goran Dragic",
  "Dennis Schroder", "Dario Saric", "Kristaps Porzingis", "Jusuf Nurkic",
  "Nikola Mirotic", "Sandro Mamukelashvili", "Deni Avdija",
  "Luka Garza", "Killian Hayes",

  // === Notable Role Players / Journeymen ===
  "Robert Covington", "Trevor Ariza", "P.J. Tucker", "Jae Crowder", "Danny Green",
  "J.J. Redick", "Kyle Korver", "Channing Frye", "Boris Diaw", "Matt Barnes",
  "James Jones", "Mike Dunleavy Jr.", "Luke Walton",
  "Rafer Alston", "Mike James", "Earl Watson", "Beno Udrih",
  "Jose Calderon", "Leandro Barbosa", "Patty Mills", "Matthew Dellavedova",
  "Ish Smith", "E'Twaun Moore", "T.J. McConnell", "Derrick Jones Jr.",
  "Torrey Craig", "Bismack Biyombo", "Robin Lopez", "Enes Freedom",
  "Mason Plumlee", "Cody Zeller", "Ersan Ilyasova", "Nemanja Bjelica",
  "Montrezl Harrell", "Bobby Portis", "Nerlens Noel",
  "Thomas Bryant", "Gorgui Dieng", "Kelly Olynyk", "Aron Baynes",
  "JaVale McGee", "Dwight Powell", "Maxi Kleber", "Dorian Finney-Smith",
  "Reggie Bullock", "Tim Hardaway Jr.", "Spencer Dinwiddie", "Shake Milton",

  // === Recent Draft Picks / Young Players ===
  "Zach Edey", "Alexandre Sarr", "Reed Sheppard", "Donovan Clingan",
  "Stephon Castle", "Matas Buzelis", "Ron Holland", "Tidjane Salaun",
  "Dalton Knecht", "Bub Carrington", "Yves Missi", "Tristan da Silva",
  "Devin Carter", "Kyle Filipowski", "Johnny Furphy",
  "Dyson Daniels", "Mark Williams", "Walker Kessler",
  "Keegan Murray", "Jaden Ivey", "Bennedict Mathurin", "Johnny Davis",
  "Ochai Agbaji", "Jalen Duren", "AJ Griffin",
  "Patrick Baldwin Jr.", "Ryan Rollins",
  "Cam Thomas", "Day'Ron Sharpe", "Keon Johnson",
  "James Bouknight", "Ziaire Williams",
  "Herb Jones", "Quentin Grimes", "Chris Duarte",

  // === All-Star / Notable Players 2010s ===
  "Gordon Hayward", "Mike Conley", "Isaiah Thomas",
  "Avery Bradley", "Brandon Bass", "Jeff Green", "Kendrick Perkins", "Glen Davis",
  "Paul Millsap", "Derrick Favors", "Enes Kanter",
  "Danilo Gallinari", "Wilson Chandler", "Arron Afflalo", "J.R. Smith",
  "Iman Shumpert", "Lance Stephenson", "George Hill", "C.J. Miles",
  "Roy Hibbert", "Nene Hilario", "Kenneth Faried", "Ty Lawson",
  "Wesley Matthews", "Nicolas Batum", "Will Barton",
  "Chandler Parsons", "Patrick Beverley",
  "Bryn Forbes", "Lonnie Walker IV", "Keldon Johnson", "Devin Vassell",
  "Josh Richardson", "Kelly Oubre Jr.", "Richaun Holmes",
  "De'Andre Hunter", "Cam Reddish", "Kevin Huerter",

  // === Classic Legends / HOF ===
  "Clyde Lovellette", "Bob Davies", "Bobby Wanzer", "Al Cervi",
  "Buddy Jeannette", "Max Zaslofsky",
  "Ed Sadowski", "Carl Braun", "Sweetwater Clifton", "Earl Lloyd",
  "Chuck Cooper", "Maurice Stokes", "Jack Twyman",
  "Len Chappell", "Johnny Green", "Dave Gambee", "Leroy Ellis",
  "Happy Hairston", "Jimmy Walker",
  "Austin Carr", "Bingo Smith", "Campy Russell",
  "Mike Mitchell", "Johnny Moore", "Alvin Adams",

  // === Additional Modern Players ===
  "Lonzo Ball", "LaMelo Ball", "Cole Anthony", "R.J. Hampton",
  "Precious Achiuwa", "Isaac Okoro", "Obi Toppin",
  "Saddiq Bey", "Gary Trent Jr.", "Malachi Flynn",
  "Aleksej Pokusevski", "Aaron Wiggins",
  "Tre Mann", "Josh Christopher", "Usman Garuba",
  "Jalen Suggs", "Wendell Carter Jr.", "Markelle Fultz",
  "Jonathan Isaac", "Mo Bamba", "Chuma Okeke",
  "Corey Kispert", "Rui Hachimura",
  "Kyle Kuzma", "Daniel Gafford", "Jordan Clarkson",
  "Jarred Vanderbilt", "Malik Beasley", "Nickeil Alexander-Walker",
  "Naz Reid", "Jaden McDaniels",
  "Taurean Prince", "Kevin Knox", "Dennis Smith Jr.",
  "Elfrid Payton", "Frank Ntilikina", "Mitchell Robinson",
  "Miles McBride",

  // === Additional Retired Stars ===
  "Anfernee Hardaway", "Muggsy Bogues", "Dell Curry", "Rex Chapman",
  "Dana Barros", "Dino Radja",
  "Eric Montross", "Gheorghe Muresan", "Manute Bol",
  "Mark Price", "John Williams", "Danny Ferry",
  "Steve Kerr", "Bill Wennington", "Jud Buechler",
  "John Paxson", "B.J. Armstrong", "Stacey King",
  "Ron Harper", "Robert Horry", "Derek Fisher", "Rick Fox",
  "Elden Campbell",
  "Doug Christie", "Hedo Turkoglu",
  "Bobby Jackson", "Scot Pollard", "Brad Miller",
  "Chris Gatling", "Adonal Foyle",
  "Erick Dampier", "Michael Finley",
  "Sean Elliott", "Avery Johnson", "Malik Rose",
  "Bruce Bowen", "Fabricio Oberto",

  // === More Players ===
  "JJ Barea", "Ben Gordon", "Chris Duhon", "Tyrus Thomas",
  "Drew Gooden", "Mo Williams", "Larry Hughes",
  "Deron Williams", "Andrei Kirilenko",
  "Matt Harpring",
  "Zydrunas Ilgauskas", "Eric Snow",
  "Aaron McKie", "George Lynch",
  "Tyrone Hill", "Kenny Anderson",
  "Jayson Williams", "Jason Collins", "Nenad Krstic",
  "Travis Outlaw", "Martell Webster", "Joel Przybilla",
  "Steve Blake", "Zach Collins", "Meyers Leonard",
  "Nassir Little", "Jerami Grant",
  "Reggie Jackson", "Luke Kennard", "Stanley Johnson", "Langston Galloway",
  "Isaiah Stewart", "Boban Marjanovic", "Wayne Ellington",
  "Moritz Wagner", "Donte DiVincenzo", "Pat Connaughton",
  "Mike Muscala", "Al-Farouq Aminu", "Allen Crabbe",
  "Evan Turner", "Gerald Henderson",
  "Michael Kidd-Gilchrist",
  "PJ Washington",
];
