export const nbaCareerPointsHints: string[] = [
  "LeBron James", "Kareem Abdul-Jabbar", "Karl Malone", "Kobe Bryant", "Kevin Durant",
  "Michael Jordan", "Dirk Nowitzki", "Wilt Chamberlain", "Julius Erving", "Moses Malone",
  "James Harden", "Shaquille O'Neal", "Carmelo Anthony", "Dan Issel", "Elvin Hayes",
  "Russell Westbrook", "Hakeem Olajuwon", "DeMar DeRozan", "Oscar Robertson", "Dominique Wilkins",
  "George Gervin", "Tim Duncan", "Stephen Curry", "Paul Pierce", "John Havlicek",
  "Kevin Garnett", "Vince Carter", "Alex English", "Rick Barry", "Reggie Miller",
  "Jerry West", "Artis Gilmore", "Patrick Ewing", "Ray Allen", "Allen Iverson",
  "Charles Barkley", "Robert Parish", "Adrian Dantley", "Dwyane Wade", "Elgin Baylor",
  "Chris Paul", "Damian Lillard", "Clyde Drexler", "Gary Payton", "Larry Bird",
  "Hal Greer", "Giannis Antetokounmpo", "Walt Bellamy", "Pau Gasol", "Bob Pettit",
  "David Robinson", "LaMarcus Aldridge", "Mitch Richmond", "Joe Johnson", "Tom Chambers",
  "Antawn Jamison", "John Stockton", "Bernard King", "Clifford Robinson", "Walter Davis",
  "Dwight Howard", "Tony Parker", "Terry Cummings", "Jamal Crawford", "Anthony Davis",
  "Paul George", "Bob Lanier", "Eddie Johnson", "Gail Goodrich", "Reggie Theus",
  "Dale Ellis", "Scottie Pippen", "Jason Terry", "Chet Walker", "Isiah Thomas",
  "Bob McAdoo", "Zach Randolph", "Mark Aguirre", "Dolph Schayes", "Kyrie Irving",
  "Tracy McGrady", "Glen Rice", "Dave Bing", "Brook Lopez", "Devin Booker",
  "Nikola Jokic", "World B. Free", "Calvin Murphy", "Lou Hudson", "Chris Mullin",
  "Lenny Wilkens", "Bailey Howell", "Magic Johnson", "Shawn Marion", "Nikola Vucevic",
  "Rudy Gay", "Rolando Blackman", "Otis Thorpe", "Jason Kidd", "Earl Monroe",
  // Additional plausible guesses
  "Klay Thompson", "Draymond Green", "Kevin Love", "Blake Griffin", "DeAndre Jordan",
  "DeMarcus Cousins", "Marc Gasol", "Al Horford", "Andre Drummond", "Hassan Whiteside",
  "Jimmy Butler", "Kawhi Leonard", "Paul George", "Bradley Beal", "Zach LaVine",
  "Jayson Tatum", "Jaylen Brown", "Donovan Mitchell", "Trae Young", "Luka Doncic",
  "Joel Embiid", "Ben Simmons", "Tobias Harris", "Seth Curry", "Tyrese Maxey",
  "Julius Randle", "RJ Barrett", "Evan Fournier", "Kemba Walker", "Terry Rozier",
  "De'Aaron Fox", "Buddy Hield", "Harrison Barnes", "Otto Porter Jr.", "Marvin Bagley III",
  "Victor Wembanyama", "Chet Holmgren", "Paolo Banchero", "Jabari Smith Jr.", "Jalen Duren",
  "Scottie Barnes", "Evan Mobley", "Franz Wagner", "Cole Anthony", "R.J. Hampton",
  "Willis Reed", "Dave DeBusschere", "Dick Barnett", "Bill Bradley", "Monroe",
  "Nate Archibald", "Pete Maravich", "Spencer Haywood", "Connie Hawkins", "Bob Boozer",
  "Bailey Howell", "Tom Heinsohn", "Bill Sharman", "Bob Cousy", "Bill Russell",
  "Wes Unseld", "Elvin Hayes", "Phil Chenier", "Cazzie Russell", "Dave Cowens",
];
