export const nflCareerPprHints: string[] = [
  'Tom Brady', 'Drew Brees', 'Aaron Rodgers', 'Jerry Rice', 'Peyton Manning',
  'Brett Favre', 'Matthew Stafford', 'Ben Roethlisberger', 'Philip Rivers', 'Matt Ryan',
  'Dan Marino', 'Larry Fitzgerald', 'Russell Wilson', 'Emmitt Smith', 'Terrell Owens',
  'John Elway', 'Fran Tarkenton', 'Tony Gonzalez', 'Marshall Faulk', 'Eli Manning',
  'Randy Moss', 'LaDainian Tomlinson', 'Walter Payton', 'Marvin Harrison', 'Cris Carter',
  'Frank Gore', 'Steve Smith Sr.', 'Reggie Wayne', 'Anquan Boldin', 'Andre Johnson',
  'Isaac Bruce', 'Antonio Gates', 'Adrian Peterson', 'Brandon Marshall', 'Torry Holt',
  'Tim Brown', 'Wes Welker', 'Antonio Brown', 'Chad Johnson', 'Hines Ward',
  'Darren Sproles', 'Calvin Johnson', 'Rob Gronkowski', 'Barry Sanders', 'Thurman Thomas',
  'Marcus Allen', 'Edgerrin James', 'Shaun Alexander', 'Jamaal Charles', 'Chris Johnson',
  'Maurice Jones-Drew', 'Steven Jackson', 'Jamal Lewis', 'Greg Olsen', 'Shannon Sharpe',
  'Michael Irvin', 'Jimmy Smith', 'Keenan McCardell', 'Rod Smith', 'Art Monk',
  'Ricky Watters', 'Michael Pittman Sr.', 'Eric Moulds', 'Donald Driver', 'Keyshawn Johnson',
  'Derrick Mason', 'Vincent Jackson', 'Dez Bryant', 'Julio Jones', 'A.J. Green',
  'Demaryius Thomas', 'Eric Decker', 'Jeremy Maclin', 'Mike Wallace', 'Golden Tate',
  'Roddy White', 'Pierre Garcon', 'Hakeem Nicks', 'Stevie Johnson', 'Miles Austin',
  'Santonio Holmes', 'Vernon Davis', 'Owen Daniels', 'Dallas Clark', 'Deion Branch',
  'Plaxico Burress', 'Steve Smith (Baltimore)', 'Victor Cruz', 'Kevin Curtis', 'Percy Harvin',
  'Dwayne Bowe', 'Reggie Bush', 'Cordarrelle Patterson', 'Chris Ivory', 'BenJarvus Green-Ellis',
  'DeAngelo Williams', 'DeMarco Murray', 'Fred Jackson', 'Arian Foster', 'Danny Woodhead',
  // Additional plausible guesses
  'Patrick Mahomes', 'Josh Allen', 'Lamar Jackson', 'Justin Herbert', 'Joe Burrow',
  'Dak Prescott', 'Kirk Cousins', 'Ryan Tannehill', 'Baker Mayfield', 'Jalen Hurts',
  'Justin Fields', 'Tua Tagovailoa', 'Trevor Lawrence', 'Mac Jones', 'Zach Wilson',
  'Cooper Kupp', 'Davante Adams', 'Tyreek Hill', 'Stefon Diggs', 'DeAndre Hopkins',
  'Diontae Johnson', 'Jaylen Waddle', "Ja'Marr Chase", 'Justin Jefferson',
  'CeeDee Lamb', 'Michael Pittman Jr.', 'Amon-Ra St. Brown', 'Garrett Wilson', "Wan'Dale Robinson",
  'Travis Kelce', 'Mark Andrews', 'Darren Waller', 'Hunter Henry', 'Kyle Pitts',
  'Dalton Schultz', 'Dawson Knox', 'Cole Kmet', 'Pat Freiermuth', 'Tyler Higbee',
  'Derrick Henry', 'Dalvin Cook', 'Jonathan Taylor', 'Austin Ekeler', 'Nick Chubb',
  'Josh Jacobs', 'Miles Sanders', 'Tony Pollard', 'Aaron Jones', 'David Montgomery',
  'Saquon Barkley', 'Christian McCaffrey', 'Alvin Kamara', 'Joe Mixon', 'Ezekiel Elliott',
  'Leonard Fournette', 'Kareem Hunt', 'James Conner', 'Damien Harris', 'Sony Michel',
  'Odell Beckham Jr.', 'Sterling Sharpe', 'Isaac Curtis', 'Paul Warfield', 'Lance Alworth',
  'Harold Jackson', 'Drew Pearson', 'Tony Hill', 'Mike Renfro', 'Butch Johnson',
];
