// Shared NFL player hints for all NFL career stat lists
// 650+ NFL player names covering QBs, RBs, WRs, TEs, and defensive stars

export const nflPlayersHints: string[] = [
  // === QUARTERBACKS ===
  "Tom Brady", "Drew Brees", "Aaron Rodgers", "Peyton Manning", "Brett Favre",
  "Patrick Mahomes", "Josh Allen", "Lamar Jackson", "Joe Burrow", "Justin Herbert",
  "Jalen Hurts", "Tua Tagovailoa", "Trevor Lawrence", "C.J. Stroud", "Caleb Williams",
  "Bryce Young", "Anthony Richardson", "Will Levis", "Drake Maye", "Jayden Daniels",
  "Matthew Stafford", "Ben Roethlisberger", "Philip Rivers", "Matt Ryan", "Dan Marino",
  "Russell Wilson", "Eli Manning", "John Elway", "Fran Tarkenton", "Dan Fouts",
  "Warren Moon", "Joe Montana", "Steve Young", "Troy Aikman", "Jim Kelly",
  "Terry Bradshaw", "Johnny Unitas", "Roger Staubach", "Bob Griese", "Sonny Jurgensen",
  "Roman Gabriel", "Ken Stabler", "Bart Starr", "Joe Namath", "Len Dawson",
  "Norm Snead", "John Hadl", "Jim Hart", "Archie Manning", "Ken Anderson",
  "Danny White", "Phil Simms", "Jim Plunkett", "Brian Sipe", "Ron Jaworski",
  "Boomer Esiason", "Randall Cunningham", "Jim Everett", "Dave Krieg", "Vinny Testaverde",
  "Drew Bledsoe", "Kerry Collins", "Jeff George", "Steve McNair", "Mark Brunell",
  "Jeff Garcia", "Rich Gannon", "Trent Green", "Brad Johnson", "Jake Plummer",
  "Donovan McNabb", "Michael Vick", "Tony Romo", "Jay Cutler", "Matt Hasselbeck",
  "Carson Palmer", "Alex Smith", "Cam Newton", "Andy Dalton", "Joe Flacco",
  "Ryan Fitzpatrick", "Sam Bradford", "Ryan Tannehill", "Kirk Cousins", "Derek Carr",
  "Dak Prescott", "Baker Mayfield", "Jared Goff", "Jameis Winston", "Marcus Mariota",
  "Teddy Bridgewater", "Nick Foles", "Case Keenum", "Tyrod Taylor", "Jacoby Brissett",
  "Jimmy Garoppolo", "Gardner Minshew", "Daniel Jones", "Mac Jones", "Zach Wilson",
  "Justin Fields", "Sam Darnold", "Kyler Murray", "Trey Lance", "Kenny Pickett",
  "Matt Schaub", "Chad Pennington", "David Garrard", "Byron Leftwich", "Kyle Orton",
  "Matt Cassel", "Josh McCown", "Geno Smith", "Deshaun Watson", "Matt Moore",
  "Chad Henne", "Blaine Gabbert", "Mike Glennon", "Brian Hoyer", "AJ McCarron",
  "Brock Osweiler", "Mitchell Trubisky", "Sam Howell", "Aidan Hutchinson",

  // === RUNNING BACKS ===
  "Emmitt Smith", "Walter Payton", "Frank Gore", "Barry Sanders", "Adrian Peterson",
  "Curtis Martin", "LaDainian Tomlinson", "Jerome Bettis", "Eric Dickerson", "Tony Dorsett",
  "Jim Brown", "Marshall Faulk", "Edgerrin James", "Marcus Allen", "Franco Harris",
  "Thurman Thomas", "Fred Taylor", "Steven Jackson", "Derrick Henry", "Corey Dillon",
  "Ottis Anderson", "Jamal Lewis", "Ricky Williams", "Chris Johnson", "Thomas Jones",
  "Warrick Dunn", "Tiki Barber", "Clinton Portis", "Shaun Alexander", "Marshawn Lynch",
  "Matt Forte", "Earnest Byner", "Eddie George", "Herschel Walker", "James Brooks",
  "Roger Craig", "Gerald Riggs", "Terrell Davis", "Robert Smith", "Garrison Hearst",
  "Ahman Green", "Priest Holmes", "Ricky Watters", "Dorsey Levens", "Charlie Garner",
  "Lamar Smith", "Michael Turner", "Willis McGahee", "Cedric Benson", "Ronnie Brown",
  "Larry Johnson", "DeAngelo Williams", "Jonathan Stewart", "Ray Rice", "Arian Foster",
  "Reggie Bush", "Darren McFadden", "LeGarrette Blount", "Alfred Morris", "DeMarco Murray",
  "Jamaal Charles", "Maurice Jones-Drew", "Darren Sproles", "Danny Woodhead",
  "Le'Veon Bell", "Todd Gurley", "LeSean McCoy", "David Johnson", "Ezekiel Elliott", "Dalvin Cook",
  "Saquon Barkley", "Nick Chubb", "Josh Jacobs", "Alvin Kamara", "Christian McCaffrey",
  "Joe Mixon", "Austin Ekeler", "Aaron Jones", "Jonathan Taylor", "Tony Pollard",
  "David Montgomery", "Miles Sanders", "James Conner", "Kareem Hunt", "Leonard Fournette",
  "Sony Michel", "Damien Harris", "Kenyan Drake", "Melvin Gordon", "Devonta Freeman",
  "Lamar Miller", "Carlos Hyde", "Jordan Howard", "Marlon Mack", "Phillip Lindsay",
  "Chris Carson", "Rashaad Penny", "Raheem Mostert", "J.K. Dobbins", "Travis Etienne",
  "Kenneth Walker III", "Breece Hall", "Bijan Robinson", "Jahmyr Gibbs", "Isiah Pacheco",
  "De'Von Achane", "Chris Ivory", "BenJarvus Green-Ellis", "Fred Jackson",
  "Cordarrelle Patterson", "Natrone Means", "Antowain Smith", "Kevin Faulk",
  "Brian Westbrook", "Duce Staley", "Stephen Davis", "Jamal Anderson",
  "Robert Edwards", "Olandis Gary", "Mike Anderson", "Tatum Bell",
  "O.J. Simpson", "Earl Campbell", "John Riggins", "Larry Csonka",
  "Floyd Little", "Joe Perry", "Lenny Moore", "Hugh McElhenny", "Marion Motley",
  "Red Grange", "Bronko Nagurski",

  // === WIDE RECEIVERS ===
  "Jerry Rice", "Larry Fitzgerald", "Terrell Owens", "Randy Moss", "Isaac Bruce",
  "Tim Brown", "Steve Smith Sr.", "Marvin Harrison", "Reggie Wayne", "Andre Johnson",
  "Anquan Boldin", "Henry Ellard", "Torry Holt", "Art Monk", "Calvin Johnson",
  "Antonio Brown", "Brandon Marshall", "Hines Ward", "Chad Johnson", "Derrick Mason",
  "Rod Smith", "Donald Driver", "Eric Moulds", "Jimmy Smith", "Keenan McCardell",
  "Keyshawn Johnson", "Vincent Jackson", "Dez Bryant", "Julio Jones", "A.J. Green",
  "Demaryius Thomas", "Eric Decker", "Jeremy Maclin", "Mike Wallace", "Golden Tate",
  "Roddy White", "Pierre Garcon", "Hakeem Nicks", "Stevie Johnson", "Miles Austin",
  "Santonio Holmes", "Deion Branch", "Plaxico Burress", "Victor Cruz", "Kevin Curtis",
  "Percy Harvin", "Dwayne Bowe", "Wes Welker", "Michael Irvin", "Sterling Sharpe",
  "Cris Carter", "Andre Reed", "Irving Fryar", "James Lofton", "Gary Clark",
  "Mark Clayton", "Mark Duper", "Wesley Walker", "Steve Largent", "John Stallworth",
  "Lynn Swann", "Charlie Joiner", "Drew Pearson", "Harold Carmichael", "Cliff Branch",
  "Harold Jackson", "Tony Hill", "Mike Renfro", "Butch Johnson", "Paul Warfield",
  "Lance Alworth", "Don Maynard", "Charley Taylor", "Bob Hayes", "Fred Biletnikoff",
  "Otis Taylor", "Gene Washington", "Haven Moses", "Roy Green", "Ahmad Rashad",
  "Wes Chandler", "Carlos Carson", "Al Toon", "Webster Slaughter", "Brian Blades",
  "Herman Moore", "Brett Perriman", "Yancey Thigpen", "Carl Pickens", "Terance Mathis",
  "Joey Galloway", "Muhsin Muhammad", "Derrick Alexander", "Joe Horn", "Laveranues Coles",
  "Santana Moss", "Lee Evans", "Marques Colston", "Greg Jennings", "Jordy Nelson",
  "Randall Cobb", "Emmanuel Sanders", "T.Y. Hilton", "Doug Baldwin", "Larry Centers",
  "Steve Smith (Baltimore)", "Isaac Curtis",
  "Cooper Kupp", "Davante Adams", "Tyreek Hill", "Stefon Diggs", "DeAndre Hopkins",
  "Odell Beckham Jr.", "Mike Evans", "Keenan Allen", "CeeDee Lamb", "Justin Jefferson",
  "Ja'Marr Chase", "Amon-Ra St. Brown", "Garrett Wilson", "Chris Olave", "Drake London",
  "Jaylen Waddle", "Michael Pittman Jr.", "Diontae Johnson", "Wan'Dale Robinson",
  "DJ Moore", "Terry McLaurin", "Brandin Cooks", "Allen Robinson", "Robert Woods",
  "Tyler Lockett", "Adam Thielen", "D.K. Metcalf", "Amari Cooper", "Michael Thomas",
  "Kenny Golladay", "Courtland Sutton", "Jerry Jeudy", "Rashod Bateman",
  "Christian Kirk", "Darnell Mooney", "George Pickens", "Jaxon Smith-Njigba",
  "Puka Nacua", "Zay Flowers", "Marvin Harrison Jr.",
  "A.J. Brown", "DeVonta Smith", "Nico Collins", "Tank Dell",
  "Malik Nabers", "Rome Odunze", "Brian Thomas Jr.",

  // === TIGHT ENDS ===
  "Tony Gonzalez", "Travis Kelce", "Rob Gronkowski", "Antonio Gates", "Jason Witten",
  "Shannon Sharpe", "Greg Olsen", "Vernon Davis", "Dallas Clark", "Owen Daniels",
  "Jimmy Graham", "Zach Ertz", "George Kittle", "Darren Waller", "Mark Andrews",
  "Hunter Henry", "Kyle Pitts", "Dalton Schultz", "Dawson Knox", "Cole Kmet",
  "Pat Freiermuth", "Tyler Higbee", "T.J. Hockenson", "Evan Engram", "David Njoku",
  "Ozzie Newsome", "Kellen Winslow", "Dave Casper", "Mike Ditka", "John Mackey",
  "Keith Jackson", "Ben Coates", "Wesley Walls", "Todd Heap", "Alge Crumpler",
  "Jeremy Shockey", "Chris Cooley", "Heath Miller", "Marcedes Lewis",
  "Brent Jones", "Jay Novacek", "Frank Wycheck",
  "Sam LaPorta", "Dalton Kincaid", "Trey McBride",

  // === DEFENSIVE PLAYERS ===
  "Lawrence Taylor", "Reggie White", "Bruce Smith", "Deion Sanders", "Ray Lewis",
  "Dick Butkus", "Jack Lambert", "Mike Singletary", "Ronnie Lott", "Ed Reed",
  "Troy Polamalu", "Brian Dawkins", "Charles Woodson", "Champ Bailey", "Darrelle Revis",
  "J.J. Watt", "Aaron Donald", "Von Miller", "Khalil Mack", "Myles Garrett",
  "T.J. Watt", "Nick Bosa", "Micah Parsons", "Patrick Surtain II", "Sauce Gardner",
  "Derwin James", "Budda Baker", "Fred Warner", "Bobby Wagner", "Darius Leonard",
  "Lavonte David", "Demario Davis", "Roquan Smith", "Dexter Lawrence", "Chris Jones",
  "Cameron Jordan", "Calais Campbell", "Julius Peppers", "Jason Pierre-Paul",
  "DeMarcus Ware", "Terrell Suggs", "Dwight Freeney", "Robert Mathis", "Jason Taylor",
  "Zach Thomas", "Junior Seau", "Derrick Thomas", "Kevin Greene", "Rickey Jackson",
  "Andre Tippett", "Derrick Brooks", "Brian Urlacher", "Patrick Willis", "Luke Kuechly",
  "Ray Nitschke", "Joe Greene", "Alan Page", "Bob Lilly", "Merlin Olsen",
  "Gino Marchetti", "Deacon Jones", "Jack Youngblood", "Howie Long", "Michael Strahan",
  "Richard Dent", "Charles Haley", "Chris Doleman", "Neil Smith",
  "Rod Woodson", "Mel Blount", "Dick Lane", "Herb Adderley", "Willie Brown",
  "Mike Haynes", "Ty Law", "Ronde Barber", "Aeneas Williams",
  "Kenny Easley", "Steve Atwater", "John Lynch", "Bob Sanders",
  "Kam Chancellor", "Earl Thomas", "Tyrann Mathieu", "Justin Simmons",

  // === SPECIAL TEAMS / MULTI-POSITION ===
  "Devin Hester", "Dante Hall", "Josh Cribbs", "Eric Metcalf", "Brian Mitchell",
  "Gale Sayers",

  // === ADDITIONAL HISTORICAL QBs ===
  "Y.A. Tittle", "Otto Graham", "Sid Luckman", "Bobby Layne", "Norm Van Brocklin",
  "George Blanda", "Jim Finks", "Billy Kilmer", "Craig Morton", "Joe Theismann",
  "Doug Williams", "Bernie Kosar", "Neil Lomax", "Tommy Kramer", "Steve DeBerg",
  "Steve Grogan", "Vince Ferragamo", "Dan Pastorini", "James Harris",

  // === ADDITIONAL HISTORICAL RBs ===
  "Leroy Kelly", "Larry Brown", "Chuck Foreman", "William Andrews", "Billy Sims",
  "George Rogers", "Curt Warner", "Joe Morris", "Neal Anderson", "Dalton Hilliard",
  "Bobby Humphrey", "Ickey Woods", "Christian Okoye", "Barry Word", "Harvey Martin",
  "Robert Newhouse", "Sam Cunningham", "Mark van Eeghen", "Pete Johnson", "Wendell Tyler",
  "James Wilder", "Gerald Willhite", "Mike Pruitt", "Greg Pruitt", "Mark Higgs",

  // === ADDITIONAL MODERN RBs ===
  "Najee Harris", "Rhamondre Stevenson", "Brian Robinson Jr.", "Tyler Allgeier",
  "Rachaad White", "Chuba Hubbard", "Javonte Williams", "Dameon Pierce",
  "Kyren Williams", "Zack Moss", "Jerome Ford", "Jaylen Warren",

  // === ADDITIONAL MODERN WRs ===
  "DeAndre Carter", "Rashid Shaheed", "Quentin Johnston", "Josh Downs",
  "Jayden Reed", "Ladd McConkey", "Xavier Worthy", "Khalil Shakir",
  "Marquise Brown", "JuJu Smith-Schuster", "Jarvis Landry", "Julian Edelman",
  "Danny Amendola", "Cole Beasley", "Sammy Watkins", "Kelvin Benjamin",
  "Mike Williams", "Will Fuller", "John Brown", "Robby Anderson",
  "Curtis Samuel", "Mecole Hardman", "Kadarius Toney", "Elijah Moore",
  "Treylon Burks", "Chris Godwin", "Tyler Boyd", "Tee Higgins",
  "Deebo Samuel", "Brandon Aiyuk",

  // === ADDITIONAL HISTORICAL WRs ===
  "Don Hutson", "Raymond Berry", "Tommy McDonald", "Bobby Mitchell", "Pete Pihos",
  "Elroy Hirsch", "Crazy Legs Hirsch", "Del Shofner", "Boyd Dowler",
  "Carroll Dale", "Frank Clarke", "Bob Chandler", "Dave Parks",

  // === ADDITIONAL HISTORICAL TEs ===
  "Jackie Smith", "Riley Odoms", "Russ Francis", "Todd Christensen", "Mark Bavaro",
  "Jimmie Giles", "Rodney Holman",

  // === KICKERS (common guesses) ===
  "Adam Vinatieri", "Morten Andersen", "Gary Anderson", "Jason Elam", "John Kasay",
  "Matt Prater", "Justin Tucker", "Harrison Butker", "Sebastian Janikowski",

  // === COACHES (common wrong guesses but good hints) ===
  "Bill Belichick", "Vince Lombardi", "Don Shula", "Tom Landry",
  "John Madden", "Bill Walsh", "Joe Gibbs", "Chuck Noll", "Andy Reid",

  // === Additional PPR list players ===
  "Michael Pittman Sr.",
];
