export const pgaGolfersHints: string[] = [
  "Tiger Woods", "Sam Snead", "Jack Nicklaus", "Ben Hogan", "Arnold Palmer",
  "Byron Nelson", "Billy Casper", "Walter Hagen", "Cary Middlecoff", "Gene Sarazen",
  "Tom Watson", "Lloyd Mangrum", "Phil Mickelson", "Vijay Singh", "Horton Smith",
  "Harry Cooper", "Jimmy Demaret", "Leo Diegel", "Gene Littler", "Paul Runyan",
  "Lee Trevino", "Henry Picard", "Tommy Armour", "Macdonald Smith", "Johnny Miller",
  "Dutch Harrison", "Doug Ford", "Gary Player", "Hale Irwin", "Nick Price",
  "Raymond Floyd", "Lanny Wadkins", "Ben Crenshaw", "Hubert Green", "Davis Love III",
  "Tom Kite", "Greg Norman", "Fred Couples", "David Duval", "Curtis Strange",
  "Larry Nelson", "Bruce Crampton", "Jim Furyk", "Mark O'Meara", "Justin Leonard",
  "Brooks Koepka", "Justin Thomas", "Rory McIlroy", "Jordan Spieth", "Dustin Johnson",
  "Scottie Scheffler", "Jon Rahm", "Justin Rose", "Matt Kuchar", "Rickie Fowler",
  "Adam Scott", "Bubba Watson", "Zach Johnson", "Webb Simpson", "Jason Day",
  "Sergio Garcia", "Patrick Reed", "Brandt Snedeker", "Ernie Els", "Retief Goosen",
  "Stewart Cink", "Steve Stricker", "Luke Donald", "Henrik Stenson", "Padraig Harrington",
  "Paul Azinger", "Peter Jacobsen", "Mark Calcavecchia", "Tom Lehman", "Steve Elkington",
  "Jose Maria Olazabal", "Colin Montgomerie", "Lee Janzen", "Scott Hoch", "Hal Sutton",
  "Corey Pavin", "Fuzzy Zoeller", "Andy North", "Tommy Aaron", "Dan Sikes",
  "Don January", "Miller Barber", "Jerry Barber", "Bob Charles", "Julius Boros",
  "Tony Lema", "George Archer", "Charles Coody", "Gay Brewer", "Orville Moody",
  "Dow Finsterwald", "Art Wall", "Jack Burke Jr.", "Doug Sanders", "Chandler Harper",
  "Mike Souchak", "Ken Venturi", "Marty Furgol", "Jay Hebert", "Lionel Hebert",
  "Jimmy Thomson", "Denny Shute", "Ralph Guldahl", "Craig Wood", "Bobby Locke",
  "Clayton Heafner", "Sam Byrd", "Tony Penna", "Jim Ferrier", "Chick Harbert",
  "Bob Goalby", "Deane Beman", "Dave Hill", "Bruce Fleisher", "Rocco Mediate",
  "Len Mattiace", "Chris DiMarco", "Loren Roberts", "Kirk Triplett", "Jeff Sluman",
  "Tom Purtzer", "Mark Brooks", "Mark McNulty", "Mark McCumber", "Jerry Pate",
  "Bob Tway", "John Cook", "Nick Faldo", "Ian Woosnam", "Sandy Lyle",
  "David Graham", "Bruce Lietzke", "Jay Haas", "Scott Simpson", "Wayne Levi",
  "Kenny Perry", "Jim Colbert", "Craig Stadler", "John Mahaffey", "Don Pooley",
  "Mike Reid", "Nick Watney", "Ryan Palmer", "Luke List", "Max Homa",
  "Patrick Cantlay", "Xander Schauffele", "Collin Morikawa", "Viktor Hovland", "Hideki Matsuyama",
  "Cameron Smith", "Joaquin Niemann", "Tony Finau", "Gary Woodland", "Billy Horschel",
  "Kevin Kisner", "Keegan Bradley", "Bryson DeChambeau", "Sungjae Im", "Si Woo Kim",
  "Corey Conners", "Tom Hoge", "Sam Burns", "Sahith Theegala", "Ludvig Aberg",
  "Wyndham Clark", "Akshay Bhatia", "Nick Taylor", "Min Woo Lee", "Taylor Pendrith",
  "Chris Kirk", "Eric Cole", "Hayden Springer", "Robert MacIntyre", "Tom Kim",
  "Camilo Villegas", "Adam Hadwin", "Charl Schwartzel", "Louis Oosthuizen", "Martin Kaymer",
  "Thomas Bjorn", "Fred Funk", "Vaughn Taylor", "Boo Weekley", "D.A. Points",
  "Kenny Knox", "Lee Westwood", "Francesco Molinari", "Tommy Fleetwood", "Ian Poulter",
  "Graeme McDowell", "Darren Clarke", "Stephen Ames", "Trevor Immelman", "Mike Weir",
  "Stuart Appleby", "Geoff Ogilvy", "Aaron Baddeley", "Robert Allenby", "Charles Howell III",
  "Harrison Frazar", "Brendon Todd", "Kevin Na", "Chez Reavie", "J.T. Poston",
  "Cameron Champ", "Joel Dahmen", "Maverick McNealy", "Matt Fitzpatrick", "Shane Lowry",
  "Chris Riley", "Kevin Sutherland", "Scott Verplank", "Bob Estes", "Bob Gilder",
  "Andy Bean", "J.C. Snead", "Gibby Gilbert", "Calvin Peete", "Chi Chi Rodriguez",
  "Rod Funseth", "Don Massengale", "Bert Yancey", "Gardner Dickinson", "Bobby Nichols",
  "Frank Beard", "Bob Rosburg", "Ted Kroll", "Freddie Haas", "Johnny Bulla",
  "Toney Penna", "Ed Furgol", "Dick Mayer", "Tommy Bolt", "Ed Dudley",
  "Johnny Palmer", "Alex Noren", "Rafa Cabrera Bello", "Emiliano Grillo", "Jhonattan Vegas",
  "Pat Perez", "Matt Every", "Danny Lee", "Jimmy Walker", "Kevin Streelman",
];
