// Top 100 most popular male names in the US plus 400+ additional male first names
export const popularMaleNamesHints: string[] = [
  // Top 100
  "James", "Robert", "John", "Michael", "David",
  "William", "Richard", "Joseph", "Thomas", "Charles",
  "Christopher", "Daniel", "Matthew", "Anthony", "Mark",
  "Donald", "Steven", "Paul", "Andrew", "Joshua",
  "Kenneth", "Kevin", "Brian", "George", "Timothy",
  "Ronald", "Edward", "Jason", "Jeffrey", "Ryan",
  "Jacob", "Gary", "Nicholas", "Eric", "Jonathan",
  "Stephen", "Larry", "Justin", "Scott", "Brandon",
  "Benjamin", "Samuel", "Raymond", "Gregory", "Frank",
  "Alexander", "Patrick", "Jack", "Dennis", "Jerry",
  "Tyler", "Aaron", "Jose", "Nathan", "Henry",
  "Adam", "Douglas", "Zachary", "Peter", "Kyle",
  "Noah", "Ethan", "Jeremy", "Walter", "Christian",
  "Keith", "Roger", "Terry", "Austin", "Sean",
  "Gerald", "Carl", "Harold", "Dylan", "Arthur",
  "Lawrence", "Jordan", "Jesse", "Bryan", "Billy",
  "Bruce", "Gabriel", "Joe", "Logan", "Albert",
  "Willie", "Alan", "Eugene", "Elijah", "Randy",
  "Wayne", "Vincent", "Philip", "Bobby", "Johnny",
  "Howard", "Liam", "Mason", "Aiden", "Oliver",
  // Beyond top 100
  "Abraham", "Adrian", "Alejandro", "Alex", "Alfred",
  "Andre", "Angel", "Angelo", "Archie", "Axel",
  "Barrett", "Beau", "Blake", "Braden", "Brady",
  "Brock", "Caleb", "Cameron", "Carlton", "Carson",
  "Carter", "Cedric", "Chase", "Clark", "Clay",
  "Clayton", "Cliff", "Clinton", "Cody", "Colby",
  "Cole", "Colton", "Connor", "Cooper", "Curtis",
  "Dakota", "Dalton", "Damon", "Dane", "Dante",
  "Darius", "Darren", "Dean", "Deandre", "Demetrius",
  "Derek", "Desmond", "Devin", "Devon", "Dominic",
  "Drake", "Drew", "Dustin", "Earl", "Edgar",
  "Edmund", "Edwin", "Eli", "Elliott", "Emanuel",
  "Emilio", "Emmanuel", "Enrique", "Ernesto", "Everett",
  "Ezra", "Felix", "Fernando", "Finn", "Francisco",
  "Franklin", "Frederick", "Garrett", "Grant", "Grayson",
  "Harrison", "Harvey", "Hector", "Hugo", "Hunter",
  "Ian", "Isaac", "Isaiah", "Ivan", "Jace",
  "Jaden", "Jamal", "Jameson", "Jared", "Jarrett",
  "Jarvis", "Jasper", "Javier", "Jay", "Jayden",
  "Jaylen", "Jefferson", "Jeremiah", "Jerome", "Joaquin",
  "Joel", "Jonah", "Jonas", "Jorge", "Josiah",
  "Juan", "Julian", "Julius", "Justice", "Kai",
  "Kane", "Keegan", "Kellen", "Kelvin", "Kendall",
  "Kennedy", "Khalil", "King", "Kirk", "Knox",
  "Kobe", "Lance", "Landon", "Lane", "Layne",
  "Lee", "Leon", "Leonard", "Leroy", "Levi",
  "Lewis", "Lincoln", "Lionel", "Lloyd", "Louis",
  "Luca", "Lucas", "Luis", "Luke", "Luther",
  "Maddox", "Malcolm", "Manuel", "Marco", "Marcus",
  "Mario", "Marshall", "Martin", "Marvin", "Mateo",
  "Maurice", "Maverick", "Max", "Maximus", "Maxwell",
  "Melvin", "Miles", "Mitchell", "Mohamed", "Myles",
  "Nathaniel", "Neil", "Nelson", "Neville", "Nico",
  "Noel", "Norman", "Omar", "Oscar", "Otto",
  "Owen", "Pablo", "Parker", "Paxton", "Pedro",
  "Percy", "Perry", "Pierce", "Preston", "Prince",
  "Rafael", "Ralph", "Raul", "Ray", "Reginald",
  "Reid", "Rex", "Ricardo", "Riley", "River",
  "Roberto", "Roderick", "Rodney", "Ronan", "Ronnie",
  "Rory", "Ross", "Rowan", "Roy", "Ruben",
  "Russell", "Ryder", "Salvador", "Santiago", "Saul",
  "Sawyer", "Shane", "Sheldon", "Sherman", "Sidney",
  "Simon", "Solomon", "Spencer", "Sterling", "Stuart",
  "Tanner", "Taylor", "Theodore", "Tobias", "Todd",
  "Trent", "Trevor", "Tristan", "Troy", "Tucker",
  "Vernon", "Victor", "Wade", "Walker", "Warren",
  "Wendell", "Wesley", "Weston", "Wiley", "Winston",
  "Wyatt", "Xavier", "Zane", "Zion", "Zander",
  "Abe", "Ace", "Aidan", "Aldo", "Alec",
  "Alfredo", "Alonzo", "Alvin", "Amos", "Anderson",
  "Andres", "Angus", "Antoine", "Antonio",
  "Ari", "Armando", "Arnold", "Asher", "Atlas",
  "August", "Augustus", "Avery", "Beckham", "Bennett",
  "Benson", "Bentley", "Bernard", "Blaine", "Bodhi",
  "Boris", "Brad", "Bradley", "Braxton", "Brendan",
  "Brennan", "Brett", "Brody", "Brooks", "Byron",
  "Callum", "Calvin", "Camden", "Carey", "Casey",
  "Cason", "Cassius", "Cecil", "Chandler", "Charlie",
  "Chester", "Clyde", "Colt", "Conner", "Conrad",
  "Corey", "Cornelius", "Craig", "Cristian", "Cruz",
  "Cyrus", "Dallas", "Damian", "Damien", "Danny",
  "Darian", "Darrell", "Darryl", "Darwin", "Dawson",
  "Dax", "Declan", "Dillon", "Dirk", "Donovan",
  "Dorian", "Duke", "Duncan", "Dwight", "Easton",
  "Eddie", "Edison", "Elias", "Ellis", "Emerson",
  "Emmett", "Enzo", "Esteban", "Evan", "Fabian",
  "Fletcher", "Floyd", "Forrest", "Foster", "Francis",
  "Franco", "Fritz", "Gage", "Gannon", "Garrison",
  "Gene", "Geoffrey", "Gilbert", "Glenn", "Grady",
  "Graham", "Griffin", "Grover", "Gunner", "Gustavo",
  "Guy", "Hank", "Harlan", "Harley",
  "Harris", "Hayes", "Heath", "Hendrix", "Herman",
  "Holden", "Homer", "Horace", "Houston", "Hubert",
  "Hudson", "Hugh", "Ignacio", "Ira", "Irving",
  "Ismael", "Israel", "Issac", "Jackson", "Jagger",
  "Jake", "Jamari", "Jamie", "Jamison",
  "Jase", "Jaxon", "Jaxson", "Jeff", "Jensen",
  "Jesus", "Jett", "Jim", "Jimmy", "Johnathan",
  "Johnnie", "Jon", "Jordy", "Julio", "Junior",
  "Kareem", "Karl", "Kasen", "Keaton",
  "Kian", "Killian", "Kingsley", "Kolby", "Kristopher",
  "Kurt", "Kyler", "Lamar", "Lawson",
  "Lennox", "Leo", "Leonardo", "Lester",
  "Lorenzo", "Louie", "Lucian", "Mack", "Magnus",
  "Major", "Malik", "Marcel", "Marcos", "Marlon",
  "Marquis", "Mathew", "Matthias", "Maximo", "Merle",
  "Micah", "Mike", "Miller", "Milo", "Monroe",
  "Montgomery", "Morgan", "Morris", "Moses", "Muhammad",
  "Murphy", "Nash", "Ned", "Nehemiah", "Nolan",
  "Oakley", "Odin", "Oren", "Orion", "Orlando",
  "Otis", "Palmer", "Paolo", "Patricio", "Pearson",
  "Phoenix", "Porter", "Quentin", "Quincy", "Quinn",
  "Quinton", "Ramiro", "Ramon", "Randall", "Raylan",
  "Remy", "Rhett", "Roscoe", "Royce",
  "Rudolph", "Rufus", "Sage", "Sam", "Samson",
  "Sebastian", "Sergio", "Seth", "Silas", "Skyler",
  "Soren", "Stanley", "Stefan", "Sullivan", "Terrance",
  "Terrence", "Thaddeus", "Theo", "Tim",
  "Titus", "Toby", "Tom", "Tommy", "Tony",
  "Trace", "Travis", "Tyrell", "Tyrone", "Tyson",
  "Ulysses", "Vance", "Vaughn", "Virgil", "Waldo",
  "Wallace", "Ward", "Watson", "Wells", "Willard",
  "Winslow", "Wolfgang", "Woody", "Xander", "Yosef",
  "Zach", "Zachariah", "Zack", "Zavier", "Zeke",
];
