// Top 100 most popular female names in the US plus 400+ additional female first names
export const popularFemaleNamesHints: string[] = [
  // Top 100
  "Mary", "Patricia", "Jennifer", "Linda", "Barbara",
  "Elizabeth", "Susan", "Jessica", "Sarah", "Karen",
  "Lisa", "Nancy", "Betty", "Margaret", "Sandra",
  "Ashley", "Dorothy", "Kimberly", "Emily", "Donna",
  "Michelle", "Carol", "Amanda", "Melissa", "Deborah",
  "Stephanie", "Rebecca", "Sharon", "Laura", "Cynthia",
  "Kathleen", "Amy", "Angela", "Shirley", "Anna",
  "Brenda", "Pamela", "Emma", "Nicole", "Helen",
  "Samantha", "Katherine", "Christine", "Debra", "Rachel",
  "Carolyn", "Janet", "Catherine", "Maria", "Heather",
  "Diane", "Ruth", "Julie", "Olivia", "Joyce",
  "Virginia", "Victoria", "Kelly", "Lauren", "Christina",
  "Joan", "Evelyn", "Judith", "Megan", "Andrea",
  "Cheryl", "Hannah", "Jacqueline", "Martha", "Gloria",
  "Teresa", "Ann", "Sara", "Madison", "Frances",
  "Kathryn", "Janice", "Jean", "Abigail", "Alice",
  "Judy", "Sophia", "Grace", "Denise", "Amber",
  "Doris", "Marilyn", "Danielle", "Beverly", "Isabella",
  "Theresa", "Diana", "Natalie", "Brittany", "Charlotte",
  "Marie", "Kayla", "Alexis", "Lori", "Ava",
  // Beyond top 100
  "Aaliyah", "Abby", "Ada", "Addison", "Adelaide",
  "Adeline", "Adriana", "Adrienne", "Agnes", "Aileen",
  "Aimee", "Ainsley", "Aisha", "Alaina", "Alana",
  "Alexa", "Alexandria", "Alicia", "Alina", "Alison",
  "Allison", "Alma", "Alyssa", "Amara", "Amelia",
  "Anastasia", "Anita", "Annabelle", "Annie", "April",
  "Aria", "Ariana", "Arianna", "Arielle", "Arlene",
  "Athena", "Aubrey", "Audrey", "Aurora", "Autumn",
  "Bailey", "Beatrice", "Bella", "Bernadette", "Beth",
  "Bethany", "Bianca", "Bonnie", "Bridget", "Brianna",
  "Brielle", "Brooke", "Brooklyn", "Caitlin", "Callie",
  "Cameron", "Camille", "Candace", "Candy", "Cara",
  "Carly", "Carmen", "Caroline", "Cassandra", "Cassidy",
  "Cecilia", "Celeste", "Chantal", "Charity", "Chelsea",
  "Cheyenne", "Claire", "Clara", "Claudia", "Colleen",
  "Connie", "Cora", "Corinne", "Courtney", "Crystal",
  "Dahlia", "Daisy", "Dakota", "Dallas", "Dana",
  "Daphne", "Darcy", "Dawn", "Deanna", "Delilah",
  "Desiree", "Destiny", "Devon", "Diamond", "Dominique",
  "Eden", "Edith", "Eileen", "Elaine", "Eleanor",
  "Elena", "Elise", "Ella", "Ellen", "Eloise",
  "Elsie", "Ember", "Emery", "Emmeline", "Erica",
  "Erin", "Esmeralda", "Estella", "Esther", "Eva",
  "Evangeline", "Eve", "Faith", "Fatima", "Faye",
  "Felicia", "Fern", "Fiona", "Flora", "Francesca",
  "Freya", "Gabriela", "Gabriella", "Gail", "Genevieve",
  "Georgia", "Geraldine", "Gina", "Giselle", "Gladys",
  "Glenda", "Gretchen", "Gwen", "Gwendolyn",
  "Hadley", "Hailey", "Hallie", "Harmony", "Harper",
  "Harriet", "Hazel", "Heidi", "Helena", "Holly",
  "Hope", "Ida", "Imani", "Imogen", "Inez",
  "Ingrid", "Irene", "Iris", "Isabel", "Isabelle",
  "Isla", "Ivy", "Jaclyn", "Jade", "Jamie",
  "Jane", "Janelle", "Jasmine", "Jeanette", "Jenna",
  "Jenny", "Jewel", "Jillian", "Joanna", "Jocelyn",
  "Jolene", "Josephine", "Joy", "Juana", "Juanita",
  "Julia", "Juliana", "Julianne", "Juliet", "June",
  "Justice", "Kaia", "Kaitlyn", "Kara", "Kate",
  "Katelyn", "Katharine", "Katie", "Katrina", "Kay",
  "Kaylee", "Keely", "Keira", "Kelley", "Kelsey",
  "Kendall", "Kennedy", "Kendra", "Kerry", "Khloe",
  "Kiara", "Kimberley", "Kinsley", "Kira", "Kristen",
  "Kristin", "Kristina", "Kylie", "Lacey", "Lana",
  "Larissa", "Laurel", "Leah", "Leilani", "Lena",
  "Leona", "Leslie", "Lila", "Liliana", "Lillian",
  "Lily", "Livia", "Logan", "Lola", "London",
  "Lorelei", "Lorena", "Lorraine", "Louisa", "Lucia",
  "Lucille", "Lucy", "Luna", "Lydia", "Lyla",
  "Lynn", "Mabel", "Mackenzie", "Macy", "Maddison",
  "Madeline", "Maeve", "Maggie", "Maisie", "Makayla",
  "Mallory", "Mandy", "Mara", "Marcella", "Marcia",
  "Margot", "Mariah", "Marian", "Marina", "Marissa",
  "Marlene", "Matilda", "Maura", "Maxine", "Maya",
  "Mckenna", "Melanie", "Melody", "Mercedes", "Meredith",
  "Mia", "Michaela", "Michele", "Mikayla", "Mila",
  "Millicent", "Mimi", "Mindy", "Miranda", "Miriam",
  "Molly", "Monica", "Morgan", "Myra", "Nadine",
  "Nadia", "Naomi", "Nellie", "Neva", "Nia",
  "Nina", "Noelle", "Nora", "Norma", "Olive",
  "Ophelia", "Paige", "Paisley", "Paloma",
  "Pandora", "Paris", "Parker", "Patience", "Paula",
  "Pauline", "Pearl", "Penelope", "Penny", "Phoebe",
  "Piper", "Polly", "Poppy", "Priscilla", "Quinn",
  "Rachael", "Raquel", "Raven", "Reagan", "Reese",
  "Regina", "Renee", "Rhiannon", "Riley", "Rita",
  "Roberta", "Robin", "Rochelle", "Rosa", "Rosalie",
  "Rose", "Rosemary", "Rowan", "Roxanne", "Ruby",
  "Sabrina", "Sadie", "Sage", "Sally", "Sasha",
  "Savanna", "Savannah", "Scarlett", "Selena", "Serena",
  "Shayla", "Shelby", "Shelley", "Sierra", "Simone",
  "Sienna", "Skye", "Skylar", "Sloane", "Sonia",
  "Sonya", "Stacy", "Stella", "Summer", "Sutton",
  "Sydney", "Sylvia", "Tabitha", "Talia", "Tamara",
  "Tammy", "Tanya", "Tara", "Tatiana", "Taylor",
  "Thea", "Tiffany", "Tina", "Tracy", "Trinity",
  "Trisha", "Trudy", "Valentina", "Valerie", "Vanessa",
  "Vera", "Veronica", "Violet", "Vivian", "Vivienne",
  "Wanda", "Wendy", "Whitney", "Willa", "Willow",
  "Winnie", "Winter", "Wren", "Yasmin", "Yolanda",
  "Zelda", "Zoe", "Zora",
  // Additional names
  "Angelica", "Angelina", "Angie", "Anne", "Annette",
  "Antoinette", "Ariel", "Arlena", "Aspen", "Astrid",
  "Bambi", "Becca", "Belinda", "Belle", "Bernice",
  "Bertie", "Bettina", "Billie", "Blair", "Blanche",
  "Blythe", "Brandi", "Brandy", "Bree",
  "Bria", "Brianne", "Brit", "Britney", "Brynn",
  "Cadence", "Caitlyn", "Camila", "Carina", "Carla",
  "Carlotta", "Carrie", "Catalina", "Cathleen", "Cecily",
  "Celina", "Chandra", "Charlene", "Christa", "Christy",
  "Cindy", "Clementine", "Colette", "Coral", "Cordelia",
  "Corina", "Cornelia", "Dalia", "Darla", "Darlene",
  "Davina", "Deirdre", "Della", "Demi", "Dina",
  "Dixie", "Dolores", "Dora", "Doreen",
  "Ebony", "Echo", "Effie", "Elana", "Electra",
  "Elisa", "Eliza", "Elvira", "Emilia", "Enid",
  "Erika", "Estelle", "Ethel", "Etta", "Eugenia",
  "Eunice", "Felicity", "Florence", "Francine",
  "Frieda", "Gemma", "Geneva", "Gianna",
  "Gigi", "Gillian", "Ginger", "Goldie", "Gracie",
  "Greer", "Greta", "Hattie", "Haven",
  "Hayley", "Helene", "Henrietta", "Hilary",
  "Hilda", "Honor", "Ilene", "Iliana", "Imelda",
  "Ina", "India", "Ione", "Irma", "Isa",
  "Ivette", "Ivonne", "Ivory", "Izzy", "Jacinta",
  "Jackie", "Jada", "Jaime", "Jana", "Janine",
  "Jaqueline", "Jayda", "Jazmin", "Jeanne", "Jemma",
  "Jessie", "Jill", "Jo", "Joanne", "Jodi",
  "Josie", "Julieta", "Julissa", "Justine", "Kamila",
  "Kari", "Karla", "Kassidy", "Kathy",
  "Kaya", "Kaydee", "Keisha", "Kelli",
  "Kim", "Kyla", "Laila", "Lainey", "Laney",
  "Latasha", "Latoya", "Laurie", "Laverne", "Lawanda",
  "Lea", "Leigh", "Leticia",
  "Lexie", "Lia", "Liana", "Libby", "Liesel",
  "Lina", "Lindy", "Lois", "Loretta", "Lorna",
  "Lottie", "Lou", "Luann", "Lucinda", "Lulu",
  "Luz", "Lynnette", "Madeleine", "Madelyn", "Mae",
  "Magdalena", "Mai", "Malia", "Mamie", "Marcy",
  "Margo", "Marguerite", "Maribel", "Marigold", "Marlena",
  "Marley", "Marta", "Martina", "Maureen", "Meadow",
  "Meg", "Melinda", "Mercy", "Meryl",
  "Michellle", "Millie", "Mina", "Minerva",
  "Misty", "Mitzi", "Moira", "Mona", "Monique",
  "Muriel", "Myrtle", "Nan", "Natasha", "Nell",
  "Nettie", "Nikki", "Nikita", "Nola", "Norah",
  "Odette", "Olga", "Opal", "Ora",
  "Patsy", "Patty", "Peggy", "Petra", "Pia",
  "Portia", "Prudence", "Raina", "Ramona", "Randi",
  "Rayna", "Reba", "Regan", "Rena", "Rhea",
  "Rhonda", "Rihanna", "Rina", "Rosalind", "Rosanna",
  "Roseanne", "Rosie", "Rowena", "Roxie", "Rubi",
  "Ruthie", "Sabrena", "Salma", "Sandy",
  "Shari", "Sharlene", "Shauna", "Shawna",
  "Sheena", "Sheila", "Shelly", "Sheri", "Sherri",
  "Sherry", "Shirleen", "Sondra", "Stacey",
  "Star", "Stefanie", "Stormy", "Sue", "Sunny",
  "Susanne", "Suzanne", "Suzette", "Sybil", "Tameka",
  "Tanisha", "Taryn", "Tasha", "Tawny", "Teri",
  "Terri", "Tess", "Tessa", "Thalia", "Thomasina",
  "Tiana", "Tierra", "Toni", "Tonya", "Treasure",
  "Tricia", "Trixie", "Ursula", "Veda", "Velma",
  "Venus", "Verna", "Vicky", "Viola",
  "Wendi", "Winifred", "Xena", "Ximena",
  "Yara", "Yesenia", "Yvette", "Yvonne", "Zara",
  "Zelma", "Zena", "Zinnia", "Zoey", "Zuri",
];
