// QS World University Rankings 2026 top 100 plus ~400 additional universities worldwide
export const qsWorldUniversityRankingsHints: string[] = [
  // Top 100 (QS 2026)
  "MIT", "Imperial College London", "Stanford", "University of Oxford", "Harvard",
  "University of Cambridge", "ETH Zurich", "NUS", "UCL", "Caltech",
  "University of Hong Kong", "NTU Singapore", "University of Chicago", "Peking University", "UPenn",
  "Cornell", "Tsinghua University", "UC Berkeley", "University of Melbourne", "UNSW Sydney",
  "Yale", "EPFL", "TU Munich", "Johns Hopkins", "Princeton",
  "University of Sydney", "McGill", "Université Paris Sciences et Lettres", "University of Toronto", "Fudan University",
  "King's College London", "Australian National University", "Chinese University of Hong Kong", "University of Edinburgh", "University of Manchester",
  "Monash University", "University of Tokyo", "Columbia", "Seoul National University", "UBC",
  "Institut Polytechnique de Paris", "Northwestern", "University of Queensland", "HKUST", "University of Michigan",
  "UCLA", "Delft University of Technology", "Shanghai Jiao Tong University", "Zhejiang University", "Yonsei University",
  "University of Bristol", "Carnegie Mellon", "University of Amsterdam", "Hong Kong Polytechnic", "NYU",
  "LSE", "Kyoto University", "LMU Munich", "University of Malaya", "KU Leuven",
  "Korea University", "Duke", "City University of Hong Kong", "National Taiwan University", "University of Auckland",
  "UC San Diego", "KFUPM", "UT Austin", "Brown", "UIUC",
  "Université Paris-Saclay", "Lund University", "Sorbonne Université", "University of Warwick", "Trinity College Dublin",
  "University of Birmingham", "University of Western Australia", "KTH Royal Institute of Technology", "University of Glasgow", "Universität Heidelberg",
  "University of Washington", "Adelaide University", "Penn State", "Universidad de Buenos Aires", "Tokyo Institute of Technology",
  "University of Leeds", "University of Southampton", "Boston University", "Freie Universität Berlin", "Purdue",
  "Osaka University", "University of Sheffield", "Uppsala University", "Durham University", "University of Alberta",
  "University of Technology Sydney", "University of Nottingham", "KIT Karlsruhe", "Politecnico di Milano", "University of Zurich",
  // Ranks 101-200 (QS 2026)
  "University of Copenhagen", "POSTECH", "Nanjing University", "Utrecht University", "Lomonosov Moscow State University",
  "RWTH Aachen", "Technical University of Denmark", "Universidade de São Paulo", "Tohoku University", "Queen Mary University of London",
  "University of Wisconsin–Madison", "Qatar University", "University of St Andrews", "Aalto University", "UC Davis",
  "Pontificia Universidad Católica de Chile", "University of Helsinki", "University College Dublin", "Leiden University", "Rice University",
  "University of Oslo", "University of Waterloo", "Georgia Tech", "IIT Delhi", "RMIT University",
  "Sungkyunkwan University", "National University of Malaysia", "Sapienza University of Rome", "IIT Bombay", "Humboldt-Universität zu Berlin",
  "Aarhus University", "University of Bath", "USTC", "Universiti Putra Malaysia", "Universiti Sains Malaysia",
  "UNAM", "Newcastle University", "University of Bologna", "Macquarie University", "Eindhoven University of Technology",
  "Erasmus University Rotterdam", "UNC Chapel Hill", "King Saud University", "Texas A&M", "TU Berlin",
  "USC", "Stockholm University", "University of Groningen", "University of Liverpool", "University of Cape Town",
  "Western University Canada", "University of Vienna", "Universiti Teknologi Malaysia", "Wageningen University", "University of Exeter",
  "University of Geneva", "Lancaster University", "University of Basel", "Hanyang University", "Universitat de Barcelona",
  "Michigan State", "Ghent University", "King Abdulaziz University", "Nagoya University", "Chalmers University of Technology",
  "Al-Farabi Kazakh National University", "Washington University in St. Louis", "Université de Montréal", "University of York", "Hokkaido University",
  "Kyushu University", "Universitat Autònoma de Barcelona", "Arizona State University", "McMaster University", "University of Chile",
  "National Tsing Hua University", "Khalifa University", "Tongji University", "UC Santa Barbara", "IIT Madras",
  "Cardiff University", "Emory University", "Curtin University", "University of Bern", "University of Wollongong",
  "Wuhan University", "Universidad Complutense de Madrid", "Tecnológico de Monterrey", "University of Indonesia", "Ohio State University",
  "Queen's University Canada", "UCLouvain", "Universität Hamburg", "University of Reading", "Vrije Universiteit Amsterdam",
  "Waseda University", "TU Wien", "University of Otago", "NYCU Taiwan", "Queen's University Belfast",
  // Ranks 201-300 (QS 2026)
  "Universität Freiburg", "University of Gothenburg", "National Cheng Kung University", "University of Twente", "ENS Lyon",
  "Universidad Autónoma de Madrid", "Deakin University", "University of Bonn", "University of Maryland", "University of Minnesota",
  "University of Calgary", "Universidad de Los Andes Colombia", "University of Florida", "University of Lausanne", "University of Tübingen",
  "IIT Kharagpur", "Keio University", "TU Dresden", "IISc Bangalore", "University of Ottawa",
  "Chulalongkorn University", "IIT Kanpur", "Tel Aviv University", "Universitas Gadjah Mada", "Loughborough University",
  "Queensland University of Technology", "University of Newcastle Australia", "Université Libre de Bruxelles", "UAE University", "Massey University",
  "University of Lisbon", "FAU Erlangen-Nürnberg", "La Trobe University", "UNICAMP", "University of Padua",
  "University of Rochester", "American University of Beirut", "Universidade do Porto", "Maastricht University", "Hebrew University of Jerusalem",
  "Victoria University of Wellington", "Politecnico di Torino", "University of Göttingen", "Hamad bin Khalifa University", "Hong Kong Baptist University",
  "University College Cork", "Beijing Normal University", "Dartmouth", "UMass Amherst", "Vanderbilt",
  "Universiti Teknologi Petronas", "University of Strathclyde", "TU Darmstadt", "Bandung Institute of Technology", "Harbin Institute of Technology",
  "Tianjin University", "Université Paris 1", "Beijing Institute of Technology", "Universidad Nacional de Colombia", "University of Canterbury",
  "University of Aberdeen", "Universidad de Navarra", "University of Surrey", "Charles University Prague", "Universitat Pompeu Fabra",
  "Norwegian University of Science and Technology", "Griffith University", "Middle East Technical University", "University of Warsaw", "NC State",
  "University of Virginia", "Sun Yat-sen University", "University of Milan", "University of Sussex", "Radboud University",
  "University of Antwerp", "University of Pittsburgh", "Georgetown", "University of Macau", "Dalhousie University",
  "University of Galway", "University of Waikato", "University of Arizona", "University of Bergen", "University of the Witwatersrand",
  "Swansea University", "UC Irvine", "Case Western Reserve", "Notre Dame", "Istanbul Technical University",
  "University of Colorado Boulder", "Université Paris Cité",
  // Additional well-known universities worldwide not in top 300
  // North America
  "Tufts", "Wake Forest", "Rice University", "UC Santa Cruz", "UC Riverside",
  "Brandeis", "University of Miami", "George Washington University", "American University", "Howard University",
  "Tulane", "Fordham", "Marquette", "Baylor", "SMU",
  "Texas Christian University", "Lehigh", "William & Mary", "Boston College", "Rensselaer Polytechnic Institute",
  "Colorado School of Mines", "Harvey Mudd", "Pomona College", "Bowdoin", "Williams College",
  "Amherst", "Swarthmore", "Wellesley", "Carleton College", "Claremont McKenna",
  "Haverford", "Grinnell", "Vassar", "Wesleyan", "Colgate",
  "Middlebury", "Bryn Mawr", "Smith College", "Oberlin", "Reed College",
  "Indiana University", "University of Oregon", "University of Iowa", "University of Kansas", "University of Kentucky",
  "Florida State University", "University of South Carolina", "University of Georgia", "Virginia Tech", "Rutgers",
  "University of Texas Dallas", "University of Houston", "SUNY Buffalo", "SUNY Stony Brook", "University of Cincinnati",
  "University of Louisville", "University of Tennessee", "University of Alabama", "Clemson", "Auburn",
  "University of Maryland Baltimore County", "George Mason", "Temple University", "Drexel", "Northeastern",
  // Europe
  "University of Warwick", "University of Leicester", "University of Dundee", "Heriot-Watt University", "University of East Anglia",
  "Maynooth University", "Dublin City University", "University of Limerick", "Université de Strasbourg", "University of Bordeaux",
  "Université de Lille", "Université de Lyon", "Université Grenoble Alpes", "University of Salamanca", "University of Granada",
  "University of Valencia", "University of Seville", "Universitat de Valencia", "University of Padua", "University of Florence",
  "University of Pisa", "Politecnico di Bari", "University of Naples Federico II", "University of Turin", "Ca' Foscari Venice",
  "University of Trento", "University of Zurich", "University of Geneva", "EPFL Lausanne", "University of St. Gallen",
  "TU Graz", "University of Innsbruck", "University of Salzburg", "Ghent University", "University of Liège",
  "KU Leuven", "Copenhagen Business School", "University of Southern Denmark", "Tampere University", "University of Turku",
  "University of Oulu", "Stockholm University", "Linköping University", "Umeå University", "University of Gothenburg",
  "Leiden University", "Groningen University", "Maastricht University", "Tilburg University", "VU Amsterdam",
  "University of Warsaw", "Jagiellonian University", "Warsaw University of Technology", "Wrocław University", "AGH Kraków",
  "Charles University", "Czech Technical University", "Masaryk University", "Palacký University", "University of Vienna",
  "University of Graz", "Vienna University of Technology", "University of Regensburg", "LMU Munich", "Heidelberg University",
  "University of Frankfurt", "University of Stuttgart", "University of Mannheim", "Ruhr University Bochum", "TU Braunschweig",
  "University of Münster", "University of Kiel", "University of Halle", "University of Jena", "University of Mainz",
  "Eberhard Karls Universität Tübingen", "University of Würzburg", "University of Constance", "Bielefeld University",
  // Asia-Pacific
  "Osaka Metropolitan University", "Nagoya Institute of Technology", "Tokyo University of Science", "Waseda University", "Keio University",
  "Ritsumeikan University", "Doshisha University", "Kobe University", "Hiroshima University", "Tsukuba University",
  "Yokohama National University", "Tokyo Institute of Technology", "Korea Advanced Institute of Science and Technology",
  "Hanyang University", "Sogang University", "Ewha Womans University", "KAIST", "Sungkyunkwan University",
  "National Taiwan Normal University", "National Sun Yat-sen University", "National Chiao Tung University",
  "Renmin University of China", "Wuhan University", "Central South University", "Xiamen University", "Tongji University",
  "Beihang University", "Beijing University of Posts and Telecommunications", "Southeast University", "University of Electronic Science and Technology of China",
  "Huazhong University of Science and Technology", "Xi'an Jiaotong University", "University of Science and Technology Beijing",
  "University of Malaya", "Universiti Teknologi Malaysia", "International Islamic University Malaysia", "Sunway University",
  "National University of Singapore", "Singapore Management University", "Singapore University of Technology and Design",
  "Chulalongkorn University", "Mahidol University", "Kasetsart University", "KMUTT", "Thammasat University",
  "University of the Philippines", "Ateneo de Manila", "De La Salle University",
  "IIT Roorkee", "IIT Guwahati", "University of Delhi", "Jawaharlal Nehru University", "Jadavpur University",
  "University of Hyderabad", "Anna University", "BITS Pilani", "Manipal University",
  "University of Auckland", "Victoria University Wellington", "AUT Auckland", "University of Waikato", "Lincoln University NZ",
  // Latin America & Africa & Middle East
  "Universidad de Chile", "Pontificia Universidad Católica Argentina", "Universidad de Buenos Aires",
  "Universidad Nacional Autónoma de México", "Tecnológico de Monterrey", "UNAM", "Universidad de los Andes Colombia",
  "Universidad Nacional de Colombia", "Universidade de São Paulo", "UNICAMP", "PUC-Rio", "UFRJ",
  "Universidad de Chile", "Universidad de Costa Rica", "Universidad Simón Bolívar Venezuela",
  "University of Cape Town", "Stellenbosch University", "University of Pretoria", "University of the Witwatersrand",
  "Cairo University", "American University in Cairo", "University of Nairobi", "Makerere University",
  "King Abdulaziz University", "King Fahd University of Petroleum", "King Saud University", "American University of Beirut",
  "Bogazici University", "Middle East Technical University", "Bilkent University", "Hacettepe University", "Istanbul University",
  "Hebrew University of Jerusalem", "Tel Aviv University", "Technion", "Weizmann Institute of Science",
];
