// Top 100 safest US cities (NeighborhoodScout 2023, based on FBI UCR 2021 data)
// plus ~400 additional US cities people might guess
export const safestCitiesUsaHints: string[] = [
  // Top 100 (the actual answers)
  "Ridgefield, CT", "Franklin, MA", "Lake in the Hills, IL", "Marshfield, MA", "Arlington, MA",
  "Fulshear, TX", "Zionsville, IN", "Lexington, MA", "Muskego, WI", "Rexburg, ID",
  "Independence, KY", "Oswego, IL", "Milton, MA", "Needham, MA", "White Lake, MI",
  "Avon Lake, OH", "Madison, MS", "Wakefield, MA", "Windsor, CO", "South Kingstown, RI",
  "Colleyville, TX", "West Bloomfield, MI", "Johns Creek, GA", "Billerica, MA", "Mason, OH",
  "Reading, MA", "North Andover, MA", "Wellesley, MA", "Mundelein, IL", "Brandon, MS",
  "Cumberland, RI", "Andover, MA", "Edwardsville, IL", "Little Elm, TX", "Merrimack, NH",
  "Waltham, MA", "Wylie, TX", "Commerce Township, MI", "Milton, GA", "Melrose, MA",
  "Ballwin, MO", "North Kingstown, RI", "Beverly, MA", "Rochester Hills, MI", "Keller, TX",
  "Shrewsbury, MA", "Dracut, MA", "Prosper, TX", "Newton, MA", "Friendswood, TX",
  "McHenry, IL", "Fort Mill, SC", "Wallingford, CT", "Caledonia, WI", "Belmont, MA",
  "De Pere, WI", "Flower Mound, TX", "Easton, MA", "Highland Park, IL", "Carmel, IN",
  "Sachse, TX", "Algonquin, IL", "Hendersonville, TN", "San Luis, AZ", "Fishers, IN",
  "Perrysburg, OH", "Lake Stevens, WA", "Cheshire, CT", "Milford, MA", "Saratoga Springs, UT",
  "Bella Vista, AR", "Princeton, NJ", "Bluffton, SC", "Novi, MI", "Chelmsford, MA",
  "Amherst, MA", "Rosemount, MN", "Gloucester, MA", "Syracuse, UT", "Waukee, IA",
  "Mequon, WI", "Westfield, IN", "Spring Hill, TN", "Upper Arlington, OH", "Rahway, NJ",
  "Montclair, NJ", "Greenwich, CT", "Hutto, TX", "Vestavia Hills, AL", "Brownsburg, IN",
  "Wilmette, IL", "New Milford, CT", "Hilliard, OH", "Royal Oak, MI", "Derry, NH",
  "Dublin, OH", "West Warwick, RI", "Watertown, MA", "Walpole, MA", "Kaysville, UT",
  // Additional US cities by region — Northeast
  "Boston, MA", "Cambridge, MA", "Quincy, MA", "Somerville, MA", "Lowell, MA",
  "Springfield, MA", "Worcester, MA", "Brockton, MA", "New Bedford, MA", "Fall River, MA",
  "Framingham, MA", "Haverhill, MA", "Plymouth, MA", "Medford, MA", "Peabody, MA",
  "Lynn, MA", "Malden, MA", "Barnstable, MA", "Weymouth, MA", "Taunton, MA",
  "Hartford, CT", "New Haven, CT", "Bridgeport, CT", "Stamford, CT", "Waterbury, CT",
  "Norwalk, CT", "Danbury, CT", "New Britain, CT", "Meriden, CT", "West Haven, CT",
  "Providence, RI", "Cranston, RI", "Pawtucket, RI", "Warwick, RI", "East Providence, RI",
  "Manchester, NH", "Nashua, NH", "Concord, NH", "Dover, NH", "Portsmouth, NH",
  "Burlington, VT", "Essex Junction, VT", "Rutland, VT",
  "Portland, ME", "Lewiston, ME", "Bangor, ME", "Auburn, ME", "Biddeford, ME",
  "New York City, NY", "Brooklyn, NY", "Buffalo, NY", "Rochester, NY", "Syracuse, NY",
  "Albany, NY", "Yonkers, NY", "White Plains, NY", "New Rochelle, NY", "Schenectady, NY",
  "Utica, NY", "Troy, NY", "Binghamton, NY", "Ithaca, NY", "Saratoga Springs, NY",
  "Newark, NJ", "Jersey City, NJ", "Paterson, NJ", "Elizabeth, NJ", "Trenton, NJ",
  "Camden, NJ", "Edison, NJ", "Woodbridge, NJ", "Hoboken, NJ", "New Brunswick, NJ",
  "Hackensack, NJ", "Atlantic City, NJ", "Morristown, NJ",
  "Philadelphia, PA", "Pittsburgh, PA", "Allentown, PA", "Erie, PA", "Reading, PA",
  "Scranton, PA", "Bethlehem, PA", "Lancaster, PA", "Harrisburg, PA", "York, PA",
  "Baltimore, MD", "Frederick, MD", "Rockville, MD", "Gaithersburg, MD", "Annapolis, MD",
  "Wilmington, DE", "Dover, DE",
  // Mid-Atlantic & Southeast
  "Washington, DC",
  "Virginia Beach, VA", "Norfolk, VA", "Chesapeake, VA", "Richmond, VA", "Newport News, VA",
  "Alexandria, VA", "Hampton, VA", "Roanoke, VA", "Lynchburg, VA", "Charlottesville, VA",
  "Charlotte, NC", "Raleigh, NC", "Greensboro, NC", "Durham, NC", "Winston-Salem, NC",
  "Fayetteville, NC", "Cary, NC", "Wilmington, NC", "High Point, NC", "Asheville, NC",
  "Columbia, SC", "Charleston, SC", "North Charleston, SC", "Rock Hill, SC", "Greenville, SC",
  "Spartanburg, SC", "Myrtle Beach, SC", "Hilton Head, SC", "Florence, SC", "Sumter, SC",
  "Atlanta, GA", "Columbus, GA", "Augusta, GA", "Macon, GA", "Savannah, GA",
  "Athens, GA", "Sandy Springs, GA", "Roswell, GA", "Marietta, GA", "Alpharetta, GA",
  "Jacksonville, FL", "Miami, FL", "Tampa, FL", "Orlando, FL", "St. Petersburg, FL",
  "Hialeah, FL", "Tallahassee, FL", "Fort Lauderdale, FL", "Port St. Lucie, FL", "Pembroke Pines, FL",
  "Cape Coral, FL", "Hollywood, FL", "Gainesville, FL", "Miramar, FL", "Coral Springs, FL",
  "Clearwater, FL", "West Palm Beach, FL", "Lakeland, FL", "Pompano Beach, FL", "Boca Raton, FL",
  "Sarasota, FL", "Fort Myers, FL", "Daytona Beach, FL", "Pensacola, FL", "Palm Bay, FL",
  "Naples, FL", "Key West, FL", "Kissimmee, FL", "Ocala, FL", "Deltona, FL",
  // South
  "Birmingham, AL", "Montgomery, AL", "Huntsville, AL", "Mobile, AL", "Tuscaloosa, AL",
  "Hoover, AL", "Auburn, AL", "Dothan, AL", "Decatur, AL", "Gadsden, AL",
  "Jackson, MS", "Gulfport, MS", "Hattiesburg, MS", "Biloxi, MS", "Meridian, MS",
  "Tupelo, MS", "Southaven, MS", "Olive Branch, MS",
  "Memphis, TN", "Nashville, TN", "Knoxville, TN", "Chattanooga, TN", "Clarksville, TN",
  "Murfreesboro, TN", "Franklin, TN", "Johnson City, TN", "Kingsport, TN", "Cookeville, TN",
  "New Orleans, LA", "Baton Rouge, LA", "Shreveport, LA", "Lafayette, LA", "Lake Charles, LA",
  "Kenner, LA", "Monroe, LA", "Houma, LA", "Metairie, LA", "Bossier City, LA",
  "Little Rock, AR", "Fort Smith, AR", "Fayetteville, AR", "Jonesboro, AR", "Conway, AR",
  "Springdale, AR", "Rogers, AR", "Bentonville, AR", "Pine Bluff, AR",
  "Louisville, KY", "Lexington, KY", "Bowling Green, KY", "Owensboro, KY", "Covington, KY",
  // Midwest
  "Chicago, IL", "Aurora, IL", "Naperville, IL", "Joliet, IL", "Rockford, IL",
  "Springfield, IL", "Elgin, IL", "Peoria, IL", "Champaign, IL", "Waukegan, IL",
  "Cicero, IL", "Bloomington, IL", "Normal, IL", "Evanston, IL", "Decatur, IL",
  "Detroit, MI", "Grand Rapids, MI", "Warren, MI", "Sterling Heights, MI", "Ann Arbor, MI",
  "Lansing, MI", "Flint, MI", "Dearborn, MI", "Livonia, MI", "Troy, MI",
  "Kalamazoo, MI", "Saginaw, MI", "Muskegon, MI", "Holland, MI", "Battle Creek, MI",
  "Columbus, OH", "Cleveland, OH", "Cincinnati, OH", "Toledo, OH", "Akron, OH",
  "Dayton, OH", "Parma, OH", "Canton, OH", "Youngstown, OH", "Lorain, OH",
  "Indianapolis, IN", "Fort Wayne, IN", "Evansville, IN", "South Bend, IN", "Hammond, IN",
  "Gary, IN", "Bloomington, IN", "Muncie, IN", "Terre Haute, IN", "Lafayette, IN",
  "Milwaukee, WI", "Madison, WI", "Green Bay, WI", "Kenosha, WI", "Racine, WI",
  "Appleton, WI", "Waukesha, WI", "Oshkosh, WI", "Eau Claire, WI", "Janesville, WI",
  "La Crosse, WI", "Fond du Lac, WI", "Sheboygan, WI",
  "Minneapolis, MN", "St. Paul, MN", "Rochester, MN", "Duluth, MN", "Brooklyn Park, MN",
  "Plymouth, MN", "Maple Grove, MN", "Woodbury, MN", "St. Cloud, MN", "Bloomington, MN",
  "Mankato, MN", "Moorhead, MN",
  "Des Moines, IA", "Cedar Rapids, IA", "Davenport, IA", "Sioux City, IA", "Iowa City, IA",
  "Waterloo, IA", "Council Bluffs, IA", "Ames, IA", "Dubuque, IA",
  "Sioux Falls, SD", "Rapid City, SD", "Aberdeen, SD", "Pierre, SD",
  "Fargo, ND", "Bismarck, ND", "Grand Forks, ND", "Minot, ND",
  "Omaha, NE", "Lincoln, NE", "Bellevue, NE", "Grand Island, NE", "Kearney, NE",
  "Kansas City, MO", "St. Louis, MO", "Springfield, MO", "Independence, MO", "Columbia, MO",
  "Lee's Summit, MO", "O'Fallon, MO", "St. Joseph, MO", "St. Charles, MO",
  "Wichita, KS", "Overland Park, KS", "Kansas City, KS", "Olathe, KS", "Topeka, KS",
  "Lawrence, KS", "Shawnee, KS", "Manhattan, KS", "Salina, KS",
  // Mountain West & Southwest
  "Denver, CO", "Colorado Springs, CO", "Aurora, CO", "Fort Collins, CO", "Lakewood, CO",
  "Thornton, CO", "Arvada, CO", "Westminster, CO", "Pueblo, CO", "Boulder, CO",
  "Greeley, CO", "Longmont, CO", "Loveland, CO", "Broomfield, CO", "Centennial, CO",
  "Albuquerque, NM", "Las Cruces, NM", "Rio Rancho, NM", "Santa Fe, NM", "Roswell, NM",
  "Farmington, NM",
  "Phoenix, AZ", "Tucson, AZ", "Mesa, AZ", "Chandler, AZ", "Gilbert, AZ",
  "Glendale, AZ", "Scottsdale, AZ", "Tempe, AZ", "Surprise, AZ", "Peoria, AZ",
  "Goodyear, AZ", "Avondale, AZ", "Flagstaff, AZ", "Yuma, AZ", "Prescott, AZ",
  "Lake Havasu City, AZ", "Sierra Vista, AZ",
  "Las Vegas, NV", "Henderson, NV", "North Las Vegas, NV", "Reno, NV", "Sparks, NV",
  "Carson City, NV",
  "Salt Lake City, UT", "West Valley City, UT", "Provo, UT", "West Jordan, UT", "Orem, UT",
  "Ogden, UT", "St. George, UT", "Layton, UT", "South Jordan, UT", "Lehi, UT",
  "Logan, UT", "Murray, UT",
  "Boise, ID", "Nampa, ID", "Meridian, ID", "Idaho Falls, ID", "Pocatello, ID",
  "Twin Falls, ID", "Coeur d'Alene, ID",
  "Billings, MT", "Missoula, MT", "Great Falls, MT", "Bozeman, MT", "Helena, MT",
  "Casper, WY", "Cheyenne, WY", "Laramie, WY", "Gillette, WY",
  // Texas
  "Houston, TX", "San Antonio, TX", "Dallas, TX", "Austin, TX", "Fort Worth, TX",
  "El Paso, TX", "Arlington, TX", "Corpus Christi, TX", "Plano, TX", "Laredo, TX",
  "Lubbock, TX", "Irving, TX", "Garland, TX", "Amarillo, TX", "Frisco, TX",
  "McKinney, TX", "Brownsville, TX", "Killeen, TX", "Grand Prairie, TX", "Pasadena, TX",
  "Denton, TX", "Midland, TX", "McAllen, TX", "Mesquite, TX", "Waco, TX",
  "Abilene, TX", "Odessa, TX", "Round Rock, TX", "Carrollton, TX", "Beaumont, TX",
  "Sugar Land, TX", "Pearland, TX", "Lewisville, TX", "Allen, TX", "Tyler, TX",
  "College Station, TX", "Edinburg, TX", "San Marcos, TX", "Temple, TX", "Georgetown, TX",
  "New Braunfels, TX", "Pflugerville, TX", "Conroe, TX", "Baytown, TX",
  // Pacific & West Coast
  "Los Angeles, CA", "San Diego, CA", "San Jose, CA", "San Francisco, CA", "Fresno, CA",
  "Sacramento, CA", "Long Beach, CA", "Oakland, CA", "Bakersfield, CA", "Anaheim, CA",
  "Santa Ana, CA", "Riverside, CA", "Stockton, CA", "Irvine, CA", "Chula Vista, CA",
  "Fremont, CA", "Modesto, CA", "San Bernardino, CA", "Fontana, CA", "Moreno Valley, CA",
  "Glendale, CA", "Huntington Beach, CA", "Santa Clarita, CA", "Garden Grove, CA", "Oceanside, CA",
  "Rancho Cucamonga, CA", "Ontario, CA", "Corona, CA", "Elk Grove, CA", "Palmdale, CA",
  "Lancaster, CA", "Salinas, CA", "Escondido, CA", "Torrance, CA", "Sunnyvale, CA",
  "Pomona, CA", "Santa Rosa, CA", "Visalia, CA", "Pasadena, CA", "Hayward, CA",
  "Roseville, CA", "Concord, CA", "Vallejo, CA", "Victorville, CA", "Ventura, CA",
  "Thousand Oaks, CA", "Berkeley, CA", "Santa Clara, CA", "Oxnard, CA", "Murrieta, CA",
  "Temecula, CA", "Antioch, CA", "San Mateo, CA", "Clovis, CA", "El Monte, CA",
  "Palm Springs, CA", "Santa Barbara, CA", "Palo Alto, CA", "Mountain View, CA", "Chico, CA",
  "Redding, CA", "Napa, CA", "Petaluma, CA", "San Luis Obispo, CA", "Santa Maria, CA",
  "Seattle, WA", "Spokane, WA", "Tacoma, WA", "Vancouver, WA", "Bellevue, WA",
  "Kent, WA", "Everett, WA", "Renton, WA", "Federal Way, WA", "Bellingham, WA",
  "Kirkland, WA", "Redmond, WA", "Yakima, WA", "Kennewick, WA", "Richland, WA",
  "Olympia, WA", "Sammamish, WA",
  "Portland, OR", "Eugene, OR", "Salem, OR", "Gresham, OR", "Hillsboro, OR",
  "Beaverton, OR", "Bend, OR", "Medford, OR", "Corvallis, OR",
  "Anchorage, AK", "Fairbanks, AK", "Juneau, AK",
  "Honolulu, HI", "Pearl City, HI", "Hilo, HI",
  // Oklahoma
  "Oklahoma City, OK", "Tulsa, OK", "Norman, OK", "Broken Arrow, OK", "Lawton, OK",
  "Edmond, OK", "Stillwater, OK", "Enid, OK", "Muskogee, OK",
];
