// ~250 sporting events by attendance (top 50 are the answers; rest are plausible guesses)
// Sources: Wikipedia List of men's association football attendance records,
//          topendsports.com, Guinness World Records, various sport-specific Wikipedia articles
export const sportingEventsAttendanceHints: string[] = [
  // Top 50 (the actual answers)
  "Brazil vs Uruguay – World Cup (1950)",
  "Flamengo vs Fluminense – Campeonato Carioca Final (1963)",
  "Brazil vs Paraguay – World Cup Qualifier (1969)",
  "Brazil vs Paraguay – World Cup Qualifier (1954)",
  "Collision in Korea – Pro Wrestling (1995)",
  "Brazil vs Spain – World Cup (1950)",
  "Brazil vs Uruguay – Copa América (1989)",
  "Brazil vs Chile – World Cup Qualifier (1989)",
  "Scotland vs England – Home International (1937)",
  "Celtic vs Aberdeen – Scottish Cup Final (1937)",
  "Brazil vs Yugoslavia – World Cup (1950)",
  "Rangers vs Hibernian – Scottish Cup (1948)",
  "Brazil vs Sweden – World Cup (1950)",
  "Celtic vs Leeds United – European Cup Semi-Final (1970)",
  "Rangers vs Greenock Morton – Scottish Cup (1948)",
  "Celtic vs Rangers – Scottish Cup (1969)",
  "Benfica vs Porto – Primeira Liga (1987)",
  "East Bengal vs Mohun Bagan – Federation Cup (1997)",
  "Julio César Chávez vs Greg Haugen – Boxing (1993)",
  "Real Madrid vs AC Milan – European Cup Semi-Final (1956)",
  "Brazil vs Argentina – Copa América (1979)",
  "Iran vs Australia – World Cup Qualifier (1997)",
  "Scotland vs England – Home International (1948)",
  "Bolivia vs Argentina – Copa América (1926)",
  "Bolton Wanderers vs West Ham – FA Cup Final (1923)",
  "Persib Bandung vs PSMS Medan – Perserikatan Final (1985)",
  "Real Madrid vs Eintracht Frankfurt – European Cup Final (1960)",
  "India vs Sri Lanka – Cricket World Cup Semi-Final (1996)",
  "Rangers vs Celtic – Old Firm Derby (1939)",
  "1999 NRL Grand Final – Melbourne vs St George Illawarra",
  "Carlton vs Collingwood – VFL Grand Final (1970)",
  "Celtic vs Hibernian – Scottish Cup (1937)",
  "Brazil vs Uruguay – Campeonato Sul-Americano (1949)",
  "Argentina vs West Germany – World Cup Final (1986)",
  "Los Angeles Dodgers vs Boston Red Sox – MLB Exhibition (2008)",
  "Mexico vs Brazil – CONCACAF Gold Cup (1999)",
  "Super Bowl XIV – Pittsburgh Steelers vs Los Angeles Rams (1980)",
  "Scotland vs England – Home International (1933)",
  "African Cup of Nations Final – Egypt vs Cameroon (1986)",
  "Celtic vs Rangers – Old Firm League (1938)",
  "Celtic vs Motherwell – Scottish Cup Final (1931)",
  "Melbourne Cup – Horse Racing (2003)",
  "Real Madrid vs ACF Fiorentina – European Cup Final (1957)",
  "Battle at Bristol – Virginia Tech vs Tennessee (2016)",
  "Notre Dame vs USC – College Football (1927)",
  "Waste Management Phoenix Open – Golf (2018)",
  "Kentucky Derby – Horse Racing (2015)",
  "Indianapolis 500 – IndyCar (2016)",
  "FBR Open Golf Tournament – Scottsdale (2008)",
  "2010 NBA All-Star Game – Dallas (2010)",

  // Additional plausible guesses (not in top 50)
  // World Cup matches
  "Brazil vs Mexico – World Cup (1950)",
  "Uruguay vs Sweden – World Cup Final (1950)",
  "Brazil vs England – World Cup (1970)",
  "Germany vs France – World Cup Semi-Final (2014)",
  "Brazil vs Germany – World Cup Semi-Final (2014)",
  "Argentina vs Netherlands – World Cup Final (2022)",
  "Brazil vs Italy – World Cup Final (1994)",
  "France vs Brazil – World Cup Final (1998)",
  "Germany vs Argentina – World Cup Final (2014)",
  "Spain vs Netherlands – World Cup Final (2010)",
  "Brazil vs France – World Cup Quarter-Final (2006)",
  "Italy vs West Germany – World Cup Final (1982)",
  "Argentina vs England – World Cup Quarter-Final (1986)",
  "Brazil vs Italy – World Cup (1982)",
  "West Germany vs England – World Cup Final (1966)",
  "Italy vs Brazil – World Cup Final (1970)",
  "Hungary vs Uruguay – World Cup Semi-Final (1954)",
  "France vs Germany – World Cup Semi-Final (2018)",
  "England vs West Germany – World Cup Final (1966)",
  "Brazil vs Czechoslovakia – World Cup (1962)",

  // European football
  "Barcelona vs Real Madrid – El Clásico (2003)",
  "Manchester United vs Bayern Munich – Champions League Final (1999)",
  "Liverpool vs AC Milan – Champions League Final (2005)",
  "Barcelona vs Manchester United – Champions League Final (2011)",
  "Real Madrid vs Liverpool – Champions League Final (2018)",
  "Chelsea vs Bayern Munich – Champions League Final (2012)",
  "Juventus vs Barcelona – Champions League Final (2015)",
  "Atletico Madrid vs Real Madrid – Champions League Final (2014)",
  "Real Madrid vs Juventus – Champions League Final (2017)",
  "Manchester City vs Inter Milan – Champions League Final (2023)",
  "Celtic vs Inter Milan – European Cup Final (1967)",
  "Ajax vs Juventus – European Cup Final (1973)",
  "Tottenham vs Liverpool – Champions League Final (2019)",
  "Real Madrid vs Valencia – La Liga (1955)",
  "Rangers vs Celtic – Scottish Premier League (2000)",
  "Arsenal vs Manchester United – FA Cup Final (1979)",
  "Chelsea vs Liverpool – FA Cup Final (2012)",
  "England vs Germany – European Championship (1996)",
  "France vs Spain – European Championship Final (1984)",
  "USSR vs Yugoslavia – European Championship Final (1960)",
  "West Germany vs Belgium – European Championship Final (1980)",
  "Italy vs Yugoslavia – European Championship (1968)",
  "Germany vs Spain – European Championship Final (2008)",

  // American sports
  "Super Bowl I – Green Bay Packers vs Kansas City Chiefs (1967)",
  "Super Bowl III – New York Jets vs Baltimore Colts (1969)",
  "Super Bowl IX – Pittsburgh Steelers vs Minnesota Vikings (1975)",
  "Super Bowl XI – Oakland Raiders vs Minnesota Vikings (1977)",
  "Super Bowl XIII – Pittsburgh Steelers vs Dallas Cowboys (1979)",
  "Super Bowl XVIII – Los Angeles Raiders vs Washington Redskins (1984)",
  "Super Bowl XXVII – Dallas Cowboys vs Buffalo Bills (1993)",
  "Super Bowl LI – New England Patriots vs Atlanta Falcons (2017)",
  "Super Bowl LV – Tampa Bay Buccaneers vs Kansas City Chiefs (2021)",
  "Super Bowl LVIII – Kansas City Chiefs vs San Francisco 49ers (2024)",
  "World Series Game 7 – Chicago Cubs vs Cleveland Indians (2016)",
  "World Series Game 7 – Boston Red Sox vs St. Louis Cardinals (2013)",
  "1994 World Series – Montreal Expos vs (cancelled)",
  "MLB All-Star Game – Dodger Stadium (1980)",
  "Army vs Notre Dame – College Football (1924)",
  "Michigan vs Ohio State – The Big Game (2006)",
  "Alabama vs Georgia – CFP Championship (2018)",
  "Ohio State vs Michigan – College Football (2016)",
  "Texas vs Oklahoma – Red River Showdown (2008)",
  "Penn State vs Michigan – College Football (1994)",
  "Big Chill at the Big House – Michigan vs Michigan State Hockey (2010)",
  "New York Giants vs Dallas Cowboys – NFL Regular Season (2009)",
  "NFL International Series – Jacksonville Jaguars vs New England Patriots (2015)",
  "NBA Finals Game 7 – Cleveland Cavaliers vs Golden State Warriors (2016)",
  "NBA Finals Game 7 – Los Angeles Lakers vs Boston Celtics (2010)",

  // Cricket
  "India vs England – Test Match Eden Gardens (1982)",
  "India vs Pakistan – Cricket World Cup Semi-Final (2011)",
  "India vs West Indies – Test Match Eden Gardens (1976)",
  "India vs England – ODI Eden Gardens (2002)",
  "Australia vs England – Ashes Test Lords (2005)",
  "India vs Pakistan – Test Match Chepauk (1999)",
  "West Indies vs England – Test Match (1968)",
  "Australia vs India – Cricket World Cup Final (2003)",
  "West Indies vs England – Test Match Barbados (1935)",
  "Australia vs England – Ashes Test MCG (1961)",
  "India vs Sri Lanka – Cricket World Cup Final (2011)",
  "Australia vs New Zealand – Cricket World Cup Final (2015)",

  // Horse racing
  "Epsom Derby – Horse Racing (1913)",
  "Epsom Derby – Horse Racing (1934)",
  "Grand National – Aintree Racecourse (1927)",
  "Grand National – Aintree Racecourse (2023)",
  "Cheltenham Gold Cup – Horse Racing (2023)",
  "Preakness Stakes – Horse Racing (2021)",
  "Belmont Stakes – Horse Racing (2004)",
  "Breeders' Cup Classic – Horse Racing (2008)",
  "Royal Ascot – Horse Racing (2019)",
  "Prix de l'Arc de Triomphe – Longchamp (2022)",

  // Australian sports
  "St Kilda vs Hawthorn – VFL Grand Final (1971)",
  "Collingwood vs Carlton – AFL Grand Final (2010)",
  "Geelong vs Collingwood – AFL Grand Final (2011)",
  "Sydney vs Hawthorn – AFL Grand Final (2012)",
  "Richmond vs Adelaide – AFL Grand Final (2017)",
  "Geelong vs Sydney – AFL Grand Final (2022)",
  "State of Origin Game 1 – NSW vs Queensland (2022)",
  "State of Origin Game 3 – Queensland vs NSW (2015)",
  "Australia vs New Zealand – Rugby League World Cup Final (1977)",
  "Australia vs Great Britain – Rugby League World Cup Final (1995)",
  "Australia vs New Zealand – Rugby Union Test (2003)",
  "South Africa vs New Zealand – Rugby World Cup Final (2023)",
  "Australia vs England – Rugby World Cup Final (2003)",
  "New Zealand vs France – Rugby World Cup Final (2011)",
  "New Zealand vs South Africa – Rugby World Cup Final (2015)",

  // Boxing
  "Muhammad Ali vs Joe Frazier – Thrilla in Manila (1975)",
  "Muhammad Ali vs George Foreman – Rumble in the Jungle (1974)",
  "Sugar Ray Leonard vs Thomas Hearns (1981)",
  "Oscar De La Hoya vs Felix Trinidad (1999)",
  "Floyd Mayweather vs Manny Pacquiao (2015)",
  "Tyson Fury vs Deontay Wilder III (2021)",
  "Anthony Joshua vs Andy Ruiz Jr. II (2019)",
  "Daniel Dubois vs Anthony Joshua (2024)",
  "Mike Tyson vs Lennox Lewis (2002)",
  "Evander Holyfield vs Riddick Bowe II (1993)",
  "Joe Louis vs Max Schmeling II (1938)",
  "Rocky Marciano vs Jersey Joe Walcott (1952)",

  // Motor racing
  "Indianapolis 500 – IndyCar (1950)",
  "Indianapolis 500 – IndyCar (1960)",
  "Indianapolis 500 – IndyCar (1970)",
  "Indianapolis 500 – IndyCar (1994)",
  "Formula 1 Italian Grand Prix – Monza (2019)",
  "Formula 1 British Grand Prix – Silverstone (2022)",
  "Formula 1 Australian Grand Prix – Melbourne (2023)",
  "Formula 1 Monaco Grand Prix (2023)",
  "Formula 1 Abu Dhabi Grand Prix (2021)",
  "24 Hours of Le Mans (2019)",
  "Daytona 500 – NASCAR (1979)",
  "Daytona 500 – NASCAR (2001)",
  "NASCAR Brickyard 400 – Indianapolis Motor Speedway (1994)",
  "Moto GP Spanish Grand Prix – Jerez (2023)",

  // Golf
  "The Masters – Augusta National (1986)",
  "US Open – Bethpage Black (2002)",
  "US Open – Pebble Beach (2000)",
  "The Open Championship – St Andrews (2010)",
  "Ryder Cup – Brookline (1999)",
  "Ryder Cup – Medinah (2012)",
  "Ryder Cup – Gleneagles (2014)",
  "Ryder Cup – Paris (2018)",

  // Olympics
  "1936 Summer Olympics Opening Ceremony – Berlin",
  "1948 Summer Olympics Opening Ceremony – London",
  "1968 Summer Olympics Opening Ceremony – Mexico City",
  "1996 Summer Olympics Opening Ceremony – Atlanta",
  "2008 Summer Olympics Opening Ceremony – Beijing",
  "2012 Summer Olympics Opening Ceremony – London",
  "2024 Summer Olympics Opening Ceremony – Paris",
  "1980 Winter Olympics Ski Jumping – Lake Placid",
  "1952 Winter Olympics Ski Jumping – Oslo",

  // Tennis
  "Wimbledon Men's Final – Roger Federer vs Rafael Nadal (2008)",
  "US Open Women's Final – Serena Williams vs Victoria Azarenka (2012)",
  "French Open Men's Final – Rafael Nadal vs Novak Djokovic (2012)",
  "Australian Open Men's Final – Novak Djokovic vs Rafael Nadal (2012)",
  "Battle of the Sexes – Billie Jean King vs Bobby Riggs (1973)",

  // Misc / other sports
  "1994 FIFA World Cup Final – Brazil vs Italy, Rose Bowl",
  "Real Madrid vs Manchester United – ICC Game at Michigan Stadium (2014)",
  "ICC Cricket World Cup Final – West Indies vs England (1979)",
  "ICC Cricket World Cup Final – India vs Pakistan (2011 Semi)",
  "NFL Pro Bowl – Aloha Stadium Honolulu (2004)",
  "Harlem Globetrotters world attendance records (1950s–1960s)",
  "Houston Livestock Show & Rodeo (2011)",
  "National Horse Show – Madison Square Garden (1920)",
];
