export const stadiumsHints: string[] = [
  "Rungrado 1st of May Stadium", "Michigan Stadium", "Beaver Stadium", "Ohio Stadium", "Kyle Field",
  "Neyland Stadium", "Tiger Stadium", "Bryant-Denny Stadium", "Darrell K Royal-Texas Memorial Stadium", "Sanford Stadium",
  "Camp Nou", "AT&T Stadium", "Estadio Azteca", "MetLife Stadium", "Rose Bowl",
  "Cotton Bowl", "Los Angeles Memorial Coliseum", "Lambeau Field", "Arrowhead Stadium", "Hard Rock Stadium",
  "Allegiant Stadium", "SoFi Stadium", "Mercedes-Benz Stadium", "Lincoln Financial Field", "Soldier Field",
  "Paul Brown Stadium", "Highmark Stadium", "Ford Field", "Lucas Oil Stadium", "State Farm Stadium",
  "Levi's Stadium", "Bank of America Stadium", "FedExField", "EverBank Stadium", "Nissan Stadium",
  "M&T Bank Stadium", "GEHA Field at Arrowhead Stadium", "Gillette Stadium", "NRG Stadium", "Lumen Field",
  "U.S. Bank Stadium", "Acrisure Stadium", "Caesars Superdome", "Raymond James Stadium", "Empower Field at Mile High",
  "Jordan-Hare Stadium", "Memorial Stadium", "Davis Wade Stadium", "Williams-Brice Stadium", "Vaught-Hemingway Stadium",
  "Ross-Ade Stadium", "Spartan Stadium", "Camp Randall Stadium", "Rice-Eccles Stadium", "Kinnick Stadium",
  "Memorial Stadium (Nebraska)", "Autzen Stadium", "Husky Stadium", "Sun Devil Stadium", "Folsom Field",
  "Stanford Stadium", "California Memorial Stadium", "Martin Stadium", "Reser Stadium", "Wembley Stadium",
  "Old Trafford", "Anfield", "Emirates Stadium", "Tottenham Hotspur Stadium", "Stamford Bridge",
  "Etihad Stadium", "San Siro", "Allianz Arena", "Signal Iduna Park", "Santiago Bernabeu",
  "Wanda Metropolitano", "Mestalla", "Parc des Princes", "Stade de France", "Olympiastadion",
  "Millennium Stadium", "Principality Stadium", "Twickenham Stadium", "Murrayfield Stadium", "Aviva Stadium",
  "Croke Park", "Wembley Arena", "MCG", "Melbourne Cricket Ground", "Eden Gardens",
  "Narendra Modi Stadium", "Salt Lake Stadium", "Azadi Stadium", "Borg El Arab Stadium", "FNB Stadium",
  "Moses Mabhida Stadium", "Stade des Martyrs", "Japan National Stadium", "Tokyo Dome", "Nissan Stadium (Yokohama)",
  "Saitama Stadium", "Workers' Stadium", "Beijing National Stadium", "Shanghai Stadium", "Rajamangala Stadium",
  "Bukit Jalil National Stadium", "Gelora Bung Karno Stadium", "Saitama Super Arena", "Seoul World Cup Stadium", "Daegu Stadium",
  "Busan Asiad Stadium", "Incheon Munhak Stadium", "Panathenaic Stadium", "Olympic Stadium (Athens)", "Luzhniki Stadium",
  "Krestovsky Stadium", "Olimpiyskiy Stadium", "Olympic Stadium (Kyiv)", "Olimpiysky (Baku)", "Olympic Stadium (Berlin)",
  "Volksparkstadion", "BayArena", "Veltins-Arena", "Red Bull Arena", "Puskas Arena",
  "Stadionul National", "Arena Nationala", "Maksimir Stadium", "Marakana", "Estadio Centenario",
  "Maracana", "Estadio Monumental", "Estadio Mineirao", "Allianz Parque", "Estadio Nacional",
  "Estadio Olimpico", "Estadio Jalisco", "Estadio BBVA", "Estadio Akron", "Rose Bowl Stadium",
  "Citi Field", "Yankee Stadium", "Dodger Stadium", "Fenway Park", "Wrigley Field",
  "Oriole Park at Camden Yards", "Busch Stadium", "Target Field", "American Family Field", "PNC Park",
  "Great American Ball Park", "Kauffman Stadium", "Progressive Field", "Citizens Bank Park", "Petco Park",
  "Chase Field", "Coors Field", "Oakland Coliseum", "T-Mobile Park", "loanDepot Park",
  "Truist Park", "Tropicana Field", "Angel Stadium", "Minute Maid Park", "Globe Life Field",
  "Madison Square Garden", "Barclays Center", "TD Garden", "United Center", "Scotiabank Arena",
  "Bell Centre", "Little Caesars Arena", "Xcel Energy Center", "Nationwide Arena", "Climate Pledge Arena",
  "Capital One Arena", "PNC Arena", "Amerant Bank Arena", "Amalie Arena", "Indian Wells Tennis Garden",
  "Arthur Ashe Stadium", "Louis Armstrong Stadium", "Centre Court", "Rod Laver Arena", "Stade Philippe Chatrier",
  "Suzanne Lenglen Court", "Ernst-Happel-Stadion", "Parken Stadium", "Ullevi", "Ullevaal Stadion",
  "Olympic Stadium (Helsinki)", "Aviva Stadium (Dublin)", "Estadi Olimpic Lluis Companys", "Estadio da Luz", "Jose Alvalade",
  "Dragao", "Giuseppe Meazza", "Stadio Olimpico", "Stadio Diego Armando Maradona", "Stadio San Nicola",
  "Stadio Franchi", "Stadio Dall'Ara", "Unipol Domus", "Juventus Stadium", "Allianz Stadium",
  "Signal Iduna Park (Dortmund)", "Allianz Arena (Munich)", "MHPArena", "Volkswagen Arena", "Borussia-Park",
  "Coface Arena", "Schwarzwald-Stadion", "Voith-Arena", "Rheinenergiestadion", "Estadio Nuevo Mirandilla",
  "Estadio Benito Villamarin", "Ramon Sanchez Pizjuan", "El Madrigal", "Estadio de Balaidos", "Reale Arena",
  "San Mames", "El Sadar", "Mendizorroza", "La Romareda", "Iaia Stadium",
  "Belarus National Olympic Stadium", "Stade Olympique", "Olimpiyskiy (Kyiv)", "King Saud University Stadium", "King Fahd International Stadium",
  "Prince Faisal bin Fahd Stadium", "Mohammed V Stadium", "Stade Mohammed V", "Stade Ahmadou Ahidjo", "Stade Leopold Senghor",
  "Stade du 5 Juillet 1962", "Stade Mustapha Tchaker", "Al Janoub Stadium", "Lusail Stadium", "Al Bayt Stadium",
  "Khalifa International Stadium", "Education City Stadium", "Ahmad bin Ali Stadium", "Stadium 974", "Al Thumama Stadium",
  "Dubai International Stadium", "Zayed Sports City Stadium", "Mohammed bin Zayed Stadium", "Hazza bin Zayed Stadium", "Cardiff City Stadium",
  "Liberty Stadium", "Swansea.com Stadium", "St James' Park", "Stadium of Light", "Riverside Stadium",
  "Molineux Stadium", "King Power Stadium", "St Mary's Stadium", "Vitality Stadium", "Turf Moor",
  "Bramall Lane", "Hillsborough Stadium", "Kenilworth Road", "The Hawthorns", "Villa Park",
  "Craven Cottage", "Selhurst Park", "Elland Road", "Portman Road", "Carrow Road",
  "Oakwell", "Pride Park", "City Ground", "Amex Stadium", "Brentford Community Stadium",
  "Kirklees Stadium", "DW Stadium", "bet365 Stadium", "Cardiff Arms Park", "Croke Park (Dublin)",
  "Lansdowne Road", "Thomond Park", "RDS Arena", "Parc Y Scarlets", "Notre Dame Stadium",
  "Michie Stadium", "Falcon Stadium", "Navy-Marine Corps Memorial Stadium", "Cajun Field", "Gerald J. Ford Stadium",
  "Protective Stadium", "Doak Campbell Stadium", "Ben Hill Griffin Stadium", "Williams-Brice Stadium (SC)", "Faurot Field",
  "Mountaineer Field", "Heinz Field", "Ryan Field", "Beaver Stadium (Penn State)", "Kibbie Dome",
  "Albertsons Stadium", "LaVell Edwards Stadium", "Stanford Stadium (California)", "Levi's Stadium (49ers)", "Gator Bowl",
  "Orange Bowl", "Liberty Bowl Memorial Stadium", "Alamodome", "Tropical Park", "Aloha Stadium",
  "Hawaii Stadium", "Cheney Stadium", "Memorial Stadium (Clemson)", "Carter-Finley Stadium", "Wallace Wade Stadium",
  "Scott Stadium", "Lane Stadium", "Kenan Memorial Stadium", "Dowdy-Ficklen Stadium", "Brooks Field",
  "Bobby Dodd Stadium", "Louisiana Superdome", "Mackay Stadium", "TCF Bank Stadium", "Huntington Bank Stadium",
  "Holt Arena", "Gerald R. Ford Stadium", "Bill Snyder Family Stadium", "David Booth Kansas Memorial Stadium", "Boone Pickens Stadium",
  "Amon G. Carter Stadium", "Gaylord Family Oklahoma Memorial Stadium", "Jones AT&T Stadium", "Rice Stadium", "TDECU Stadium",
  "Nippert Stadium", "Rentschler Field", "Fenway Park (Boston)", "Gillette Stadium (Foxborough)", "Rentschler Field (UConn)",
  "Beaver Stadium (State College)", "Yale Bowl", "Harvard Stadium", "Princeton Stadium", "Celtic Park",
  "Ibrox Stadium", "Hampden Park",
];
