export const tallestMountainsHints: string[] = [
  // Top 100 (same as main list)
  "Mount Everest", "K2", "Kangchenjunga", "Lhotse", "Makalu",
  "Cho Oyu", "Dhaulagiri I", "Manaslu", "Nanga Parbat", "Annapurna I",
  "Gasherbrum I", "Broad Peak", "Gasherbrum II", "Shishapangma", "Gyachung Kang",
  "Annapurna II", "Gasherbrum IV", "Himalchuli", "Distaghil Sar", "Ngadi Chuli",
  "Khunyang Chhish", "Masherbrum", "Nanda Devi", "Chomo Lonzo", "Batura Sar",
  "Rakaposhi", "Namcha Barwa", "Kanjut Sar", "Kamet", "Dhaulagiri II",
  "Saltoro Kangri", "Kumbhakarna", "Tirich Mir", "Gurla Mandhata", "Saser Kangri I",
  "Chogolisa", "Kongur Tagh", "Shispare", "Trivor", "Gangkhar Puensum",
  "Gongga Shan", "Annapurna III", "Skyang Kangri", "Changtse", "Kula Kangri",
  "Kongur Tiube", "Mamostong Kangri", "Saser Kangri II E", "Muztagh Ata", "Ismoil Somoni Peak",
  "Saser Kangri III", "Noshaq", "Pumari Chhish", "Passu Sar", "Yukshin Gardan Sar",
  "Teram Kangri I", "Jongsong Peak", "Malubiting", "Gangapurna", "Jengish Chokusu",
  "K12", "Ganesh I", "Sia Kangri", "Momhil Sar", "Kabru North",
  "Skil Brum", "Haramosh Peak", "Istor-o-Nal", "Ghent Kangri", "Ultar",
  "Rimo I", "Churen Himal", "Teram Kangri III", "Sherpi Kangri", "Labuche Kang",
  "Kirat Chuli", "Saraghrar", "Jomolhari", "Chamlang", "Chongtar",
  "Baltoro Kangri", "Siguang Ri", "The Crown", "Gyala Peri", "Porong Ri",
  "Baintha Brakk", "Yutmaru Sar", "K6", "Kangpenqing", "Muztagh Tower",
  "Mana Peak", "Diran", "Labuche Kang III", "Putha Hiunchuli", "Apsarasas Kangri",
  "Mukut Parbat", "Rimo III", "Langtang Lirung", "Karjiang", "Annapurna South",
  // Sub-peaks and satellite summits often discussed
  "Nuptse", "Gasherbrum III", "Annapurna IV", "Lhotse Middle", "Lhotse Shar",
  "Kangchenjunga South", "Kangchenjunga West", "Kangchenjunga Middle", "Kabru South",
  "Kanchenjunga", "Yalung Kang",
  // Famous lower peaks on the Seven Summits list
  "Aconcagua", "Denali", "Mount Kilimanjaro", "Mount Elbrus", "Mount Vinson",
  "Puncak Jaya", "Mount Kosciuszko", "Mont Blanc", "Mount Logan",
  // Famous Himalayan and Karakoram peaks not in top 100
  "Dhaulagiri III", "Dhaulagiri IV", "Dhaulagiri V", "Dhaulagiri VI", "Annapurna V", "Himlung Himal", "Kang Guru", "Peri Himal",
  "Baudha Himal", "Cheo Himal", "Dome Blanc", "Cho Polu", "Baruntse",
  "Mera Peak", "Island Peak", "Lobuche East", "Lobuche West", "Pokalde",
  "Chhukung Ri", "Kongma Tse", "Nirekha", "Kusum Kangkaru",
  "Ama Dablam", "Thamserku", "Kangtega", "Kusum Kangaru", "Kwangde Ri",
  "Taboche", "Tramserku", "Numbur", "Shorong Yul Lha", "Gauri Shankar",
  "Melungtse", "Parchamo", "Ramdung Go",
  "Pumori", "Lingtren", "Khumbutse", "Cho La Peak",
  "Dorje Lhakpa", "Phurbi Ghyachu", "Madiya",
  "Langtang Ri", "Gang Chhenpo", "Naya Kanga", "Paldor Peak",
  "Himal Chuli West", "Buddha Himal", "Ratna Chuli",
  "Kanguru", "Chulu East", "Chulu West", "Pisang Peak",
  "Tilicho Peak", "Nilgiri North", "Nilgiri South", "Nilgiri Middle",
  "Tukuche Peak", "Ghustung North", "Sita Chuchura",
  "Mukut Himal", "Saribung Peak", "Kang La Peaks",
  "Nanda Devi East", "Nanda Kot", "Panch Chuli", "Panch Chuli II",
  "Trisul", "Dunagiri", "Changabang", "Kalanka", "Hardeol",
  "Tirsuli", "Milam Glacier", "Rishi Pahar", "Devtoli",
  "Kedarnath Peak", "Kedar Dome", "Jogin I", "Jogin II", "Jogin III",
  "Bhrigupanth", "Gangotri III", "Satopanth", "Shivling", "Meru Peak", "Thalay Sagar", "Bhagirathi I",
  "Bhagirathi II", "Bhagirathi III", "Sudarshan Parbat",
  "Srikanta", "Bandarpunch", "Jaonli", "Srikanth",
  "K3", "K4", "K5", "K6 East", "K7", "K7 West", "K8",
  "Gasherbrum V", "Gasherbrum VI", "Chiring Peak",
  "Mitre Peak", "Trango Tower", "Great Trango Tower",
  "Uli Biaho Tower", "Lobsang Spire", "Namlesse Tower",
  "Nameless Tower", "Paiju Peak", "Urdok I", "Urdok II",
  "Khalkhal", "Koser Gunge", "Quz Sar", "Yazghil Sar",
  "Batura II", "Batura III", "Batura IV", "Batura V",
  "Shispare Sar", "Tupopdan", "Bojohagur Duanasir",
  "Spantik", "Chogolisa East", "Chogolisa West",
  "Apsarasas II", "Apsarasas III", "Ghent Kangri III",
  "Saltoro Kangri II", "Bilafond La",
  "K10", "Sherpi Kangri II",
  "Rimo II", "Rimo IV", "Siachen Muztagh",
  "Teram Kangri II", "Singhi Kangri",
  "Pk 7000", "Pk 6900",
  // Hindu Kush
  "Koyo Zom", "Udren Zom", "Gul Lasht Zom", "Saraighar",
  "Koh-e Baba Tangi", "Akher Chioh", "Koh-e Urgend",
  // Pamirs
  "Lenin Peak", "Korzhenevskaya Peak", "Peak Revolution", "Peak Karl Marx",
  "Peak Engels", "Muztagh Ata North", "Kongur Tiube East", "Shakhdara Range",
  "Kauffmann Peak", "Zaalai Range",
  // Tian Shan
  "Khan Tengri", "Pik Pobeda", "Mramornaya Stena",
  // Caucasus
  "Dykh Tau", "Shkhara", "Koshtan Tau", "Janga",
  "Kazbek", "Mount Tetnuld", "Mount Ushba",
  // Americas
  "Ojos del Salado", "Monte Pissis", "Huascaran", "Llullaillaco",
  "Tres Cruces", "Nevado Sajama", "Chimborazo", "Cayambe",
  "Antisana", "Cotopaxi", "Coropuna", "Ampato", "Solimana",
  "Yerupaja", "Salcantay", "Ausangate", "Chopicalqui", "Chearoco",
  "Alpamayo", "Artesonraju", "Vallunaraju", "Ishinca",
  "Mount Fairweather", "Mount Saint Elias", "Mount Foraker",
  "Mount Hunter", "Mount Bear", "Mount Vancouver",
  "Mount Steele", "Mount Wood", "Mount Churchill",
  // Africa
  "Mount Kenya", "Mount Stanley", "Mount Speke", "Mount Baker",
  "Margherita Peak", "Alexandra Peak", "Ras Dejen",
  // Europe / Caucasus
  "Monte Rosa", "Dom", "Weisshorn", "Matterhorn", "Dent Blanche",
  "Grand Combin", "Finsteraarhorn", "Zinalrothorn", "Aletschhorn",
  "Bietschhorn", "Jungfrau", "Monch", "Eiger", "Schreckhorn",
  "Grosses Fiescherhorn", "Grossglockner", "Piz Bernina",
  // Notable volcanic peaks
  "Mauna Kea", "Mauna Loa", "Mount Rainier", "Mount Whitney",
  "Pico de Orizaba", "Popocatepetl", "Iztaccihuatl",
  "Mount Fuji", "Etna", "Vesuvius",
  // Antarctica
  "Mount Sidley", "Mount Erebus", "Mount Murphy",
  // Oceania
  "Puncak Trikora", "Puncak Mandala", "Mount Wilhelm",
  "Mount Victoria", "Mount Kinabalu",
];
