export const tallestBuildingsHints: string[] = [
  // === Top 100 (same as main list) ===
  "Burj Khalifa", "Merdeka 118", "Shanghai Tower", "Mecca Royal Clock Tower",
  "Ping An Finance Centre", "Lotte World Tower", "One World Trade Center",
  "Guangzhou CTF Finance Centre", "Tianjin CTF Finance Centre", "CITIC Tower",
  "Taipei 101", "Shanghai World Financial Center", "International Commerce Centre",
  "Wuhan Greenland Center", "Central Park Tower", "Lakhta Center", "Landmark 81",
  "International Land-Sea Center", "The Exchange 106", "Changsha IFS Tower 1",
  "Petronas Tower 1", "Petronas Tower 2", "Zifeng Tower",
  "Suzhou International Financial Center", "Wuhan Center", "Willis Tower", "KK100",
  "Guangzhou International Finance Center", "111 West 57th Street",
  "Shandong International Financial Center", "One Vanderbilt", "432 Park Avenue",
  "Marina 101", "Trump International Hotel and Tower", "270 Park Avenue",
  "Minying International Trade Center T2", "Jin Mao Tower",
  "Nanjing Financial City Phase II Plot C Tower 1", "Princess Tower",
  "Al Hamra Tower", "International Finance Centre", "Haeundae LCT The Sharp Landmark Tower",
  "Ningbo Central Plaza", "Guangxi China Resources Tower",
  "Guiyang International Financial Center T1", "Iconic Tower",
  "China Merchants Bank Global Headquarters Main Tower", "China Resources Tower",
  "23 Marina", "CITIC Plaza", "Citymark Centre", "Shum Yip Upperhills Tower 1",
  "30 Hudson Yards", "Public Investment Fund Tower", "Shun Hing Square",
  "Eton Place Dalian Tower 1", "Autograph Tower", "Logan Century Center 1",
  "Burj Mohammed bin Rashid", "Empire State Building", "Elite Residence",
  "Riverview Plaza", "Guangdong Business Center", "Dabaihui Plaza", "Central Plaza",
  "Federation Tower", "Hengfeng Guiyang Center Tower 1",
  "Dalian International Trade Center", "Shanghai International Trade Center Tower 1",
  "Kempinski The Boulevard Dubai", "Haitian Center Tower 2",
  "Golden Eagle Tiandi Tower A", "Bank of China Tower", "Bank of America Tower",
  "Ciel Dubai Marina", "St. Regis Chicago", "Almas Tower",
  "Ping An Finance Center Jinan", "Huiyun Center", "Hanking Center",
  "Greenland Group Suzhou Center", "City Tower 1", "Gevora Hotel",
  "Galaxy World Tower 1", "Galaxy World Tower 2", "Il Primo Tower",
  "JW Marriott Marquis Dubai Tower 1", "JW Marriott Marquis Dubai Tower 2",
  "Emirates Office Tower", "Raffles City Chongqing T3N", "Raffles City Chongqing T4N",
  "OKO South Tower", "CBRT Tower", "The Marina Torch",
  "SkyTower at Pinnacle One Yonge", "Forum 66 Tower 1", "The Pinnacle",
  "Xi'an Glory International Financial Center", "Spring City 66", "85 Sky Tower",

  // === Well-known skyscrapers worldwide (NOT in top 100) ===
  // Asia 300-349m
  "The Center", "Xiamen International Center", "Shimao Global Financial Center",
  "Four Seasons Place Kuala Lumpur", "ADNOC Headquarters",
  "One Shenzhen Bay Tower 7", "Uptown Tower",
  "LCT The Sharp Residential Tower A", "Chongqing World Financial Center",
  "Yun Ding Tower", "Wuxi IFS", "Hilton Wenzhou City Center",
  "Suning Plaza Zhenjiang", "Hengqin International Finance Center",
  "Tianjin Modern City Office Tower", "Tianjin World Financial Center",
  "SLS Dubai Hotel and Residences", "DAMAC Residenze",
  "Twin Towers Guiyang East Tower", "Twin Towers Guiyang West Tower",
  "AMA Tower", "Shengjing Finance Plaza T2",
  "LCT The Sharp Residential Tower B", "Parc1 Tower I",
  "Shimao International Plaza", "Rose Rayhaan by Rotana",
  "The Address Residence Fountain View III", "Regalia",
  "Minsheng Bank Building", "Ryugyong Hotel", "One Za'abeel Tower 1",
  "China World Trade Center Tower III", "Yuexiu Global Financial Center",
  "Guangxi Financial Investment Center", "Jiulong Lake Knowledge Tower",
  "Keangnam Hanoi Landmark Tower", "The Index", "Longxi International Hotel",
  "Al Yaqoub Tower", "Suning Plaza Wuxi", "Golden Eagle Tiandi Tower B",
  "Baoneng Center", "Azabudai Hills Main Tower", "Deji Plaza II",
  "The Landmark", "Wenzhou World Trade Center", "Heartland 66 Office Tower",
  "Burj Al Arab", "Nina Tower", "Aon Center Chicago",
  "875 North Michigan Avenue",

  // Asia 250-300m
  "Pearl River Tower", "Jumeirah Emirates Towers Hotel", "Burj Rafal",
  "Cayan Tower", "Etihad Tower 2", "Baiyoke Tower II",
  "Kingdom Centre", "Gate of the Orient", "Abeno Harukas",
  "Yokohama Landmark Tower", "SEG Plaza", "Ocean Heights",
  "King Power MahaNakhon", "Magnolias Waterfront Residences",
  "Telekom Tower", "Abu Dhabi Plaza",

  // USA famous skyscrapers
  "Comcast Technology Center", "Wilshire Grand Center", "3 World Trade Center",
  "Salesforce Tower San Francisco", "The Brooklyn Tower", "53W53",
  "Chrysler Building", "The New York Times Building", "The Spiral",
  "Bank of America Plaza Atlanta", "U.S. Bank Tower",
  "Franklin Center", "One57", "JPMorgan Chase Tower",
  "35 Hudson Yards", "1 Manhattan West", "Two Prudential Plaza",
  "Wells Fargo Plaza", "50 Hudson Yards", "4 World Trade Center",
  "Comcast Center", "311 South Wacker Drive", "70 Pine Street",
  "Key Tower", "One Liberty Place", "Columbia Center",
  "40 Wall Street", "Bank of America Plaza Dallas",
  "Citigroup Center", "Williams Tower", "99 Hudson Street",
  "Renaissance Tower", "10 Hudson Yards", "Truist Plaza",
  "Bank of America Corporate Center", "8 Spruce Street",
  "900 North Michigan", "Panorama Tower", "Trump World Tower",
  "425 Park Avenue", "Water Tower Place", "Aqua Chicago",
  "Transamerica Pyramid", "30 Rockefeller Plaza", "Chase Tower Chicago",
  "Two Liberty Place", "Rainier Square Tower", "Park Tower Chicago",
  "Devon Energy Center", "One Bennett Park", "U.S. Steel Tower",
  "56 Leonard Street", "CitySpire Center", "MetLife Building",
  "Woolworth Building", "200 Clarendon Street",

  // Europe famous buildings
  "Neva Tower", "Mercury City Tower", "Varso Tower", "The Shard",
  "Eurasia Tower", "City of Capitals Moscow Tower",
  "22 Bishopsgate", "Grand Tower Frankfurt", "Commerzbank Tower",
  "Istanbul Sapphire", "Messeturm", "Torre de Cristal", "Torre Cepsa",
  "Karlatornet", "Evolution Tower", "Moscow State University",
  "Palace of Culture and Science", "One Canada Square",
  "Tour First", "UniCredit Tower", "Heron Tower",
  "Leadenhall Building", "DC Tower 1", "HSB Turning Torso",
  "Tour Montparnasse", "Omniturm", "Main Tower", "Tower 185",
  "30 St Mary Axe", "Tower 42",

  // South America
  "Gran Torre Santiago", "Yachthouse Residence Club", "One Tower Sao Paulo",
  "Alvear Tower", "Parque Central Complex", "BD Bacata",
  "Titanium La Portada", "Torre Colpatria", "Coltejer Building",
  "Edifício Itália", "Altino Arantes Building",

  // Oceania
  "Q1 Gold Coast", "Australia 108", "Eureka Tower", "Brisbane Skytower",
  "Crown Sydney", "Aurora Melbourne Central", "Rialto Towers",
  "Chifley Tower",

  // Africa
  "Alamein Iconic Tower", "Great Mosque of Algiers Tower",
  "Mohammed VI Tower", "The Leonardo", "Carlton Centre",
  "Britam Tower",

  // Canada
  "First Canadian Place", "Scotia Plaza", "Aura Toronto",
  "The Bow Calgary", "Commerce Court West", "Stantec Tower",

  // Historic and iconic buildings people might guess
  "Petronas Towers", "World Trade Center", "Twin Towers",
  "Sears Tower", "John Hancock Center", "Aon Center",
  "Prudential Tower", "MetLife Tower", "Flatiron Building",
  "Woolworth Tower", "Chrysler Tower", "Rockefeller Center",
  "One Liberty Plaza", "7 World Trade Center", "2 World Trade Center",
  "5 World Trade Center", "Deutsche Bank Center",
  "Hudson Yards", "Salesforce Tower", "Comcast Building",
  "AT&T Building", "Sony Tower", "IBM Building",
  "General Motors Building", "Pan Am Building",
  "Tribune Tower", "Wrigley Building", "Marina City",
  "Lake Point Tower", "Hancock Tower Boston",
  "Prudential Center Boston", "Bank of China Hong Kong",
  "Cheung Kong Centre", "Hopewell Centre",
  "Central Plaza Hong Kong", "The Gateway Hong Kong",
  "China World Trade Center",
  "Baiyoke Tower", "Menara Telekom", "Menara KL",

  // Famous towers people might guess (not buildings but common guesses)
  "CN Tower", "Tokyo Tower", "Tokyo Skytree", "Eiffel Tower",
  "Oriental Pearl Tower", "Canton Tower", "Ostankino Tower",
  "Willis Tower Chicago", "Space Needle", "Stratosphere Tower",
  "Berliner Fernsehturm", "Sky Tower Auckland",

  // Middle East
  "Jeddah Tower", "Address Downtown", "Rose Tower",
  "Ocean Heights Dubai", "D1 Tower", "Torch Tower",
  "The Address Dubai Mall", "The Address Dubai Marina",
  "Damac Heights", "Sky View Tower", "One Sheikh Zayed Road",
  "Index Tower", "Maze Tower", "Vision Tower",
  "Ahmed Abdul Rahim Al Attar Tower", "Sulafa Tower",
  "The Torch Dubai", "Capital Market Authority Tower",
  "Al Kazim Towers", "Millennium Tower Dubai",
  "Park Place Tower", "The Tower Dubai", "Bay Gate Tower",

  // Additional well-known buildings worldwide
  "International Financial Centre Seoul",
  "Lotte Center Hanoi", "Bitexco Financial Tower",
  "Sapphire Tower Istanbul", "Skyland Istanbul",
  "Neva Towers Moscow", "Capital Towers Moscow",
  "IFC Seoul", "Three IFC Seoul", "Parc 1 Seoul",
  "Northeast Asia Trade Tower", "Haeundae I'Park Marina",
  "Lotte Castle Star Busan",
  "MahaNakhon Tower", "Magnolias Ratchadamri Boulevard",
  "The Residences at Mandarin Oriental Bangkok",
  "Thamrin Nine Tower 1", "Pakubuwono Signature",
  "Menara Astra", "The Pinnacle Sudirman",
  "Gama Tower Jakarta", "World Financial Center Beijing",
  "Greenland Center Wuhan", "Zhongguo Zun",
  "Ping An Tower", "Shanghai Center",
  "Nanning Logan Century", "Kunming Wanda Plaza",
  "Dalian Greenland Center", "Shenyang Greenland Center",
  "Poly International Plaza Guangzhou",
  "R&F Yingkai Square", "Shimao Qianhai Center",
  "GF Securities Tower", "East Pacific Center Tower A",
  "Posco Tower Songdo", "Lotte World Tower Seoul",
  "Abraj Al-Bait", "Abraj Al Bait Clock Tower",
  "Clock Tower Mecca",

  // More international skyscrapers
  "Nanjing World Trade Center", "White Magnolia Plaza",
  "Global City Plaza", "Guangzhou International Cultural Center",
  "Metrobank Center", "International Youth Cultural Center",
  "Aspire Tower Doha", "NBK Tower", "Arraya Tower",
  "OCT Tower", "Shenzhen Bay Innovation Tower",
  "Fortune Center Shanghai", "Changsha IFS Tower 2",
  "Beyond Office Tower", "KAFD World Trade Center",
  "Address Beach Resort", "The Assima Tower",
  "Lusail Plaza Tower", "Greenland Bund Centre",

  // Additional hints - generic building names people might try
  "Skytree", "Sky Tower", "Cloud Tower", "Star Tower",
  "Diamond Tower", "Crystal Tower", "Gold Tower",
  "Silver Tower", "Platinum Tower", "Pearl Tower",
  "Sun Tower", "Moon Tower", "Wind Tower",
  "Bay Tower", "Harbor Tower", "River Tower",
  "Lake Tower", "Ocean Tower", "Mountain Tower",
  "Century Tower", "Millennium Tower", "Grand Tower",
  "Royal Tower", "Imperial Tower", "Crown Tower",
  "Gateway Tower", "Landmark Tower", "Signature Tower",
  "Summit Tower", "Apex Tower", "Zenith Tower",
  "Pinnacle Tower", "Peak Tower", "Heights Tower",
  "Vista Tower", "Horizon Tower", "Panorama Tower Miami",
  "Infinity Tower Brisbane",

  // More Dubai buildings
  "Cayan Tower Dubai", "DAMAC Towers by Paramount",
  "Burj Vista", "Marina Gate Tower", "Dubai Marina Tower",
  "Palm Tower", "Nakheel Tower", "Dubai Creek Tower",
  "One Palm", "Jumeirah Gate Tower",
  "The Address Sky View", "Address Harbour Point",
  "Burj Daman", "Boulevard Point", "Act One Act Two",
  "Residence Inn by Marriott Dubai", "SRG Tower",

  // More Chinese buildings
  "Greenland Puli Center", "Suzhou ICC",
  "Jiangxi Nanchang Greenland Central Plaza",
  "Leatop Plaza", "Diwang International Fortune Center",
  "Wuxi Maoye City", "CCCC Southern Financial Building",
  "Nanshan Science Technology Building",
  "Zhongtian Future Ark Tower", "Shengjing Finance Plaza",
  "Hengyu Jinrong Center", "Huaqiang Golden Corridor",
  "Chongqing IFS Tower 1", "Moi Center",
  "TEDA IFC", "Honglou Times Square",
  "Shenzhen Bay Innovation Centre",
  "Guangxi Wealth Financial Center",
  "R&F Centre", "Greenland Hangzhou Center",

  // More US buildings (200-250m range)
  "110 North Wacker", "CitySpire Center New York",
  "28 Liberty Street", "4 Times Square", "MetLife Building New York",
  "731 Lexington Avenue", "126 Madison Avenue", "The Centrale",
  "181 Fremont", "IDS Center", "BNY Mellon Center",
  "200 Clarendon Street Boston", "Four Seasons Hotel Miami",
  "111 Murray Street", "One Chicago East Tower",
  "220 Central Park South", "One Liberty Place Philadelphia",
  "2 Manhattan West", "Four Seasons Hotel New York Downtown",
  "15 Hudson Yards", "125 Greenwich Street",
  "NEMA Chicago", "Sixth and Guadalupe",
  "Trump World Tower New York", "Aon Center Los Angeles",
  "One Atlantic Center", "Aston Martin Residences",
  "The Orchard New York",

  // More European buildings
  "Skyland Istanbul Tower 1", "Skyland Istanbul Tower 2",
  "Triumph Palace Moscow", "Naberezhnaya Tower",
  "Five Towers Moscow", "City of Capitals Saint Petersburg Tower",
  "iCity Space Tower", "Imperia Tower Moscow",
  "Federation Tower West", "Tour Majunga", "Tour Hekla",
  "Newfoundland London", "Aspen at Consort Place",
  "South Quay Plaza", "One Nine Elms", "8 Canada Square",
  "25 Canada Square London", "Tour Incity",
  "Allianz Tower Milan", "Westend Tower Frankfurt",
  "Hotel Ukraina Moscow", "Roche Tower 2",
  "8 Bishopsgate London", "One Park Drive London",
  "Intempo Benidorm", "Deansgate Square South Tower",
  "Warsaw Unit", "Zlota 44", "Generali Tower Milan",
  "Olszynki Park", "Zalmhaventoren", "Sky Tower Wroclaw",
  "Tower 42 London", "30 St Mary Axe London",
  "BT Tower London", "100 Bishopsgate",
  "Beetham Tower Manchester",

  // More Asia-Pacific buildings
  "SO Sofitel Residences Dubai", "Tianjin World Financial Center Tower",
  "Shenyang International Center", "Qingdao Landmark Tower",
  "Yantai Shimao No.1 The Harbour", "Wenzhou World Trade Center Tower",
  "Guangxi Finance Plaza", "Palais Royale Mumbai",
  "Huijin Center", "One Island East Hong Kong",
  "Forte Towers", "Shimao Cross-Strait Plaza",
  "Khalid Al Attar Tower", "Riverfront Times Square",
  "Hangzhou Centre Tower", "Qianhai Horoy Tower",
  "Haeundae I'Park Marina Tower 2", "C Future City East Tower",
  "Concord International Centre", "Powerlong Center Tower 1",
  "Dongguan TBA Tower", "Lokhandwala Minerva",
  "Address Downtown Dubai", "The Address Beach Resort Dubai",
  "We've the Zenith Tower", "Al Wasl Tower Dubai",
  "Luminary Tower", "Zhongzhou Holdings Financial Center",

  // More South American buildings
  "Epic Tower", "Torres Atrio", "Infinity Coast",
  "Boreal Tower", "Orion Complex",
  "Centro Financiero Confinanzas",
  "Plaza Bocagrande", "Museo Parque Central",
  "Torre Telefonica Chile", "Le Parc Tower Buenos Aires",
  "Torre Norte Sao Paulo", "Mirante do Vale",
  "Rio Sul Center", "World Trade Center Montevideo",

  // More African buildings
  "Commercial Bank of Ethiopia Headquarters",
  "Ponte City Apartments", "UAP Old Mutual Tower",
  "NECOM House Lagos", "Global Trade Center Addis Ababa",

  // More Canadian buildings
  "TD Canada Trust Tower", "One Bloor Toronto",
  "Brookfield Place East Toronto", "CIBC Square",
  "ICE Condominiums", "1250 Rene-Levesque",
  "Telus Sky Calgary", "Ten York Toronto",
  "Shangri-La Toronto", "Bay Adelaide Centre",

  // More Oceania buildings
  "West Side Place Melbourne", "One Sydney Harbour",
  "Premier Tower Melbourne", "One William Street Brisbane",
  "120 Collins Street", "101 Collins Street Melbourne",
  "Prima Pearl Melbourne", "Soul Gold Coast",
  "Soleil Gold Coast", "Citigroup Centre Sydney",
  "Central Park Sydney", "World Tower Sydney",
  "Governor Phillip Tower", "Aurora Place Sydney",
  "Quay Quarter Tower Sydney",

  // Additional well-known buildings by common name
  "Cheung Kong Centre Hong Kong", "Hopewell Centre Hong Kong",
  "Two IFC Hong Kong", "The Center Hong Kong",
  "Convention Plaza Hong Kong", "Langham Place Hong Kong",
  "International Finance Center Hong Kong",
  "Menara Kuala Lumpur", "Menara TM",
  "Republic Plaza Singapore", "UOB Plaza Singapore",
  "One Raffles Place Singapore", "Capital Tower Singapore",
  "Guoco Tower Singapore", "Tanjong Pagar Centre",
  "Marina Bay Sands Tower", "DBS Asia Central",
  "CapitaSpring Singapore", "ION Orchard Singapore",

  // Indian skyscrapers
  "Imperial Towers Mumbai", "World One Mumbai",
  "Orchid Crown Mumbai", "Lodha The Park Mumbai",
  "One Avighna Park Mumbai", "Ahuja Tower Mumbai",
  "Planet Godrej Mumbai", "Kohinoor Square Mumbai",
  "Supernova Spira Delhi", "DLF Tower Delhi",
  "The 42 Kolkata", "Forum Atmosphere Kolkata",

  // Japanese skyscrapers
  "Toranomon Hills Station Tower",
  "Shibuya Scramble Square", "Toranomon Hills Mori JP Tower",
  "Midtown Tower Tokyo", "Mori JP Tower",
  "Tokyo Midtown Yaesu", "Roppongi Hills Mori Tower",
  "NTT Docomo Yoyogi Building", "Shinjuku Park Tower",
  "Sunshine 60", "Mode Gakuen Cocoon Tower",

  // Korean skyscrapers
  "Haeundae Doosan We've the Zenith",
  "Centum Premier Tower", "Dream Tower Jeju",
  "Samsung Tower Palace", "Tower Palace Three",
  "Trade Tower Seoul", "Seoul International Finance Center",
  "FKI Tower Seoul",

  // More misc well-known buildings people might guess
  "Torre Mayor Mexico City", "Torre Reforma Mexico City",
  "Torre BBVA Mexico City", "Torre Ejecutiva Pemex",
  "Sapphire Istanbul", "Folkart Towers Izmir",
  "Cevahir Sky City Istanbul",
  "Doha Tower Qatar", "Al Bidda Tower Qatar",
  "Palm Jumeirah Tower", "Atlantis The Royal Dubai",
  "Museum of the Future Dubai", "Dubai Frame",
  "Princess Tower Dubai", "Torch Tower Dubai",
  "Marina Pinnacle Dubai", "Sulafa Tower Dubai",
  "Almas Tower Dubai",
  "Capital Gate Abu Dhabi", "Etihad Towers Abu Dhabi",
  "The Galleria Abu Dhabi",
  "Al Hamra Tower Kuwait", "NBK Tower Kuwait",
  "Kipco Tower Kuwait",
  "Bahrain World Trade Center", "Bahrain Financial Harbour",
  "The Avenues Tower Kuwait",
];
