export const tennisPlayersHints: string[] = [
  "Jimmy Connors", "Roger Federer", "Novak Djokovic", "Ivan Lendl", "Rafael Nadal",
  "John McEnroe", "Pete Sampras", "Bjorn Borg", "Guillermo Vilas", "Andre Agassi",
  "Ilie Nastase", "Boris Becker", "Rod Laver", "Thomas Muster", "Stefan Edberg",
  "Arthur Ashe", "John Newcombe", "Stan Smith", "Ken Rosewall", "Mats Wilander",
  "Lleyton Hewitt", "Andy Murray", "Marcelo Rios", "Michael Chang", "Andy Roddick",
  "Yevgeny Kafelnikov", "David Ferrer", "Tomas Berdych", "Jo-Wilfried Tsonga", "Richard Gasquet",
  "Gael Monfils", "Juan Martin del Potro", "Carlos Alcaraz", "Jannik Sinner", "Daniil Medvedev",
  "Alexander Zverev", "Stefanos Tsitsipas", "Dominic Thiem", "Grigor Dimitrov", "Nick Kyrgios",
  "Taylor Fritz", "Casper Ruud", "Holger Rune", "Felix Auger-Aliassime", "Frances Tiafoe",
  "Ben Shelton", "Tommy Paul", "Karen Khachanov", "Andrey Rublev", "Hubert Hurkacz",
  "Alex de Minaur", "Lorenzo Musetti", "Jack Draper", "Ugo Humbert", "Alexei Popyrin",
  "Arthur Fils", "Mariano Puerta", "Nicolas Almagro", "Fernando Gonzalez", "Nicolas Kiefer",
  "Tim Henman", "Greg Rusedski", "Goran Ivanisevic", "Marat Safin", "Gustavo Kuerten",
  "Carlos Moya", "Alex Corretja", "Albert Costa", "Juan Carlos Ferrero", "Sebastien Grosjean",
  "Younes El Aynaoui", "Sjeng Schalken", "Nikolay Davydenko", "Mikhail Youzhny", "Dmitry Tursunov",
  "Radek Stepanek", "Jiri Novak", "Paradorn Srichaphan", "Wayne Ferreira", "Mark Philippoussis",
  "Pat Rafter", "Patrick Rafter", "Mark Woodforde", "Todd Woodbridge", "Richard Krajicek",
  "Paul Haarhuis", "Jacco Eltingh", "Magnus Norman", "Magnus Gustafsson", "Jonas Bjorkman",
  "Thomas Johansson", "Thomas Enqvist", "Mikael Pernfors", "Stefan Koubek", "Tommy Haas",
  "Andrei Medvedev", "Marcelo Filippini", "Fabrice Santoro", "Cedric Pioline", "Guy Forget",
  "Henri Leconte", "Yannick Noah", "Thierry Tulasne", "Gilles Simon", "Paul-Henri Mathieu",
  "Arnaud Clement", "Nicolas Escude", "Michael Llodra", "Julien Benneteau", "Adrian Mannarino",
  "Benoit Paire", "Lucas Pouille", "Pierre-Hugues Herbert", "Nicolas Mahut", "Jeremy Chardy",
  "David Goffin", "Steve Darcis", "Olivier Rochus", "Christophe Rochus", "Xavier Malisse",
  "Ruben Bemelmans", "Kimmer Coppejans", "Rik de Voest", "Kevin Anderson", "John Isner",
  "Sam Querrey", "Donald Young", "Steve Johnson", "Ryan Harrison", "Jack Sock",
  "Mardy Fish", "Robby Ginepri", "James Blake", "Vincent Spadea", "Justin Gimelstob",
  "Taylor Dent", "Paul Goldstein", "Brad Gilbert", "Aaron Krickstein", "Jim Courier",
  "Todd Martin", "Jared Palmer", "Jonathan Stark", "Richey Reneberg", "Patrick McEnroe",
  "Alex O'Brien", "Doug Flach", "David Wheaton", "MaliVai Washington", "Brian Teacher",
  "Tim Mayotte", "Paul Annacone", "Ken Flach", "Robert Seguso", "Kelly Jones",
  "Sandy Mayer", "Gene Mayer", "Anders Jarryd", "Joakim Nystrom", "Jan Gunnarsson",
  "Niclas Kroon", "Henrik Holm", "Jonas Svensson", "Ronnie Bathman", "Magnus Larsson",
  "Peter Lundgren", "Nicklas Kulti", "Nicklas Kroon", "Mikael Tillstrom", "Robin Soderling",
  "Joachim Johansson", "Robin Vik", "Martin Damm", "David Rikl", "Cyril Suk",
  "Petr Korda", "Karel Novacek", "Jaroslav Navratil", "Jiri Vanek", "Tomas Zib",
  "Ivo Minar", "Lukas Rosol", "Jan Hajek", "Dusan Lajovic", "Viktor Troicki",
  "Janko Tipsarevic", "Filip Krajinovic", "Laslo Djere", "Miomir Kecmanovic", "Nenad Zimonjic",
  "Nikola Milojevic", "Ivan Dodig", "Mate Pavic", "Marin Cilic", "Borna Coric",
  "Nikola Mektic", "Ante Pavic", "Ivo Karlovic", "Mario Ancic", "Ivan Ljubicic",
  "Marko Cilic", "Antonio Veic", "Franko Skugor", "Borna Gojo", "Duje Ajdukovic",
  "Dino Prizmic", "Dominik Koepfer", "Yannick Hanfmann", "Daniel Altmaier", "Jan-Lennard Struff",
  "Maximilian Marterer", "Oscar Otte", "Andreas Mies", "Kevin Krawietz", "Tim Puetz",
  "Mischa Zverev", "Philipp Kohlschreiber", "Florian Mayer", "Rainer Schuettler", "Benjamin Becker",
  "Alexander Popp", "Daniel Elsner", "Lars Burgsmuller", "Christian Vinck", "Dirk Dier",
  "Marc-Kevin Goellner", "Alexander Waske", "Michael Berrer", "Tobias Kamke", "Peter Gojowczyk",
  "Dustin Brown", "Jurgen Melzer", "Oliver Marach", "Andreas Haider-Maurer", "Gerald Melzer",
  "Brian Gottfried", "Vitas Gerulaitis", "Harold Solomon", "Eddie Dibbs", "Roscoe Tanner",
  "Dick Stockton", "Bob Lutz", "Cliff Richey", "Jeff Borowiak", "Trey Waltke",
  "Raul Ramirez", "Manuel Orantes", "Jose Higueras", "Andres Gimeno", "Juan Gisbert",
  "Marty Riessen",
];
