// ~500 US cities/metro areas people might guess for cost of living
export const usCitiesCostOfLivingHints: string[] = [
  // Top 100 (the actual answers)
  "Manhattan", "San Francisco", "Honolulu", "Brooklyn", "San Jose",
  "Orange County (CA)", "Washington DC", "Los Angeles", "Seattle", "Boston",
  "San Diego", "Stamford (CT)", "Queens (NY)", "Oakland", "Portland (OR)",
  "Denver", "Miami", "Sacramento", "Hartford", "Austin",
  "Chicago", "Minneapolis", "Philadelphia", "Raleigh", "Nashville",
  "Salt Lake City", "Baltimore", "Charlotte", "Tampa", "Dallas",
  "Atlanta", "Houston", "Las Vegas", "Phoenix", "Richmond (VA)",
  "Pittsburgh", "Orlando", "Columbus", "Jacksonville", "San Antonio",
  "Indianapolis", "Kansas City", "Tucson", "Reno", "Cincinnati",
  "St. Louis", "Milwaukee", "Albuquerque", "Des Moines", "Louisville",
  "Omaha", "Cleveland", "Boise", "Colorado Springs", "El Paso",
  "Knoxville", "Tulsa", "Little Rock", "Oklahoma City", "Memphis",
  "Birmingham", "Buffalo", "Wichita", "Fort Wayne", "Lexington",
  "Spokane", "Shreveport", "Lubbock", "Columbia (SC)", "Augusta",
  "McAllen", "Brownsville", "Corpus Christi", "Dayton", "Akron",
  "Toledo", "Youngstown", "Syracuse", "Rochester (NY)", "Provo",
  "Ogden", "Huntsville", "Chattanooga", "Jackson (MS)", "Fayetteville (AR)",
  "Cedar Rapids", "Sioux Falls", "Green Bay", "Peoria", "Springfield (MO)",
  "Topeka", "Amarillo", "Beaumont", "Tyler", "Abilene",
  "Harlingen", "Kalamazoo", "Decatur", "Jonesboro", "Danville",
  // Beyond top 100 — cities from every state, suburbs, smaller cities, college towns
  // Northeast
  "New York City", "The Bronx", "Staten Island", "Jersey City", "Newark",
  "Hoboken", "Trenton", "Princeton", "New Brunswick", "Atlantic City",
  "Camden", "Paterson", "Elizabeth", "Edison", "Woodbridge",
  "White Plains", "Yonkers", "New Rochelle", "Poughkeepsie", "Albany",
  "Schenectady", "Utica", "Binghamton", "Ithaca", "Saratoga Springs",
  "Long Island", "Hempstead", "Montclair", "Morristown", "Red Bank",
  "Providence", "Warwick", "Newport", "Cranston",
  "New Haven", "Bridgeport", "Waterbury", "Danbury", "Greenwich", "Norwalk",
  "Worcester", "Springfield (MA)", "Cambridge", "Somerville", "Lowell",
  "Brockton", "Fall River", "New Bedford", "Cape Cod", "Nantucket",
  "Martha's Vineyard", "Northampton", "Amherst",
  "Portland (ME)", "Bangor", "Lewiston", "Augusta (ME)", "Bar Harbor",
  "Burlington (VT)", "Montpelier", "Rutland", "Brattleboro",
  "Concord (NH)", "Manchester (NH)", "Nashua", "Hanover", "Portsmouth (NH)",
  "Harrisburg", "Scranton", "Allentown", "Bethlehem", "Reading",
  "Lancaster", "York", "Erie", "State College", "Wilkes-Barre",
  // Southeast
  "Virginia Beach", "Norfolk", "Arlington (VA)", "Alexandria (VA)", "Fairfax",
  "Charlottesville", "Roanoke", "Lynchburg", "Hampton", "Williamsburg",
  "Raleigh-Durham", "Durham", "Greensboro", "Winston-Salem", "Wilmington (NC)",
  "Asheville", "Fayetteville (NC)", "High Point", "Chapel Hill",
  "Charleston (SC)", "Greenville (SC)", "Myrtle Beach", "Spartanburg", "Hilton Head",
  "Savannah", "Athens (GA)", "Macon", "Columbus (GA)", "Marietta",
  "Roswell (GA)", "Alpharetta", "Decatur (GA)",
  "Fort Lauderdale", "West Palm Beach", "Boca Raton", "Naples", "Sarasota",
  "Fort Myers", "Cape Coral", "Clearwater", "St. Petersburg", "Daytona Beach",
  "Gainesville (FL)", "Tallahassee", "Pensacola", "Panama City", "Key West",
  "Ocala", "Lakeland", "Port St. Lucie", "Palm Bay", "Kissimmee",
  "Mobile", "Montgomery", "Tuscaloosa", "Auburn (AL)", "Dothan",
  "Gulfport", "Biloxi", "Hattiesburg", "Tupelo", "Oxford (MS)",
  "New Orleans", "Baton Rouge", "Lafayette (LA)", "Lake Charles", "Monroe (LA)",
  "Lexington (KY)", "Bowling Green (KY)", "Owensboro", "Covington (KY)", "Frankfort (KY)",
  "Murfreesboro", "Clarksville", "Franklin (TN)", "Johnson City",
  "Cookeville", "Kingsport",
  // Midwest
  "Detroit", "Grand Rapids", "Ann Arbor", "Lansing", "Flint",
  "Saginaw", "Traverse City", "Muskegon", "Holland (MI)", "Battle Creek",
  "Dearborn", "Warren (MI)", "Sterling Heights", "Troy (MI)", "Livonia",
  "Madison (WI)", "Racine", "Kenosha", "Appleton", "Oshkosh",
  "Eau Claire", "La Crosse", "Janesville", "Wausau", "Fond du Lac",
  "Naperville", "Aurora (IL)", "Rockford", "Joliet", "Springfield (IL)",
  "Champaign", "Peoria (IL)", "Bloomington (IL)", "Decatur (IL)", "Carbondale",
  "Evanston", "Schaumburg", "Elgin", "Waukegan",
  "Evansville", "South Bend", "Gary", "Terre Haute",
  "Muncie", "Lafayette (IN)", "Bloomington (IN)", "Fishers", "Carmel (IN)",
  "Canton", "Springfield (OH)", "Mansfield",
  "Lima (OH)", "Zanesville", "Findlay", "Sandusky",
  "St. Paul", "Duluth", "Rochester (MN)", "Bloomington (MN)", "St. Cloud",
  "Mankato", "Moorhead", "Winona",
  "Iowa City", "Davenport", "Waterloo (IA)", "Dubuque", "Ames",
  "Sioux City", "Council Bluffs", "Burlington (IA)", "Mason City",
  "Fargo", "Bismarck", "Grand Forks", "Minot", "Williston",
  "Rapid City", "Aberdeen (SD)", "Pierre", "Brookings",
  "Lincoln", "Grand Island", "North Platte", "Kearney", "Bellevue (NE)",
  "Overland Park", "Lawrence (KS)", "Manhattan (KS)", "Salina",
  // South Central
  "Fort Worth", "Arlington (TX)", "Plano", "Irving", "Frisco",
  "McKinney", "Denton", "Round Rock", "Midland", "Odessa",
  "Waco", "Killeen", "Temple", "Bryan", "College Station",
  "Laredo", "Edinburg", "Mission (TX)", "Galveston", "Port Arthur",
  "Sugar Land", "Pearland", "The Woodlands", "Conroe",
  "Bentonville", "Fort Smith", "Hot Springs", "Pine Bluff", "Conway (AR)",
  "Norman", "Broken Arrow", "Lawton", "Edmond", "Stillwater (OK)",
  "Enid", "Muskogee", "Bartlesville",
  // Mountain West
  "Park City", "Logan", "St. George", "Orem",
  "Nampa", "Meridian (ID)", "Idaho Falls", "Pocatello",
  "Twin Falls", "Coeur d'Alene", "Moscow (ID)",
  "Billings", "Missoula", "Great Falls", "Helena", "Bozeman", "Kalispell",
  "Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs",
  "Jackson (WY)", "Cody",
  "Boulder", "Fort Collins", "Pueblo", "Grand Junction",
  "Loveland", "Greeley", "Castle Rock", "Durango", "Aspen",
  "Vail", "Telluride", "Steamboat Springs",
  "Santa Fe", "Las Cruces", "Rio Rancho", "Roswell (NM)",
  "Flagstaff", "Tempe", "Scottsdale", "Mesa", "Gilbert", "Chandler",
  "Glendale (AZ)", "Peoria (AZ)", "Surprise", "Yuma", "Prescott",
  "Sedona", "Lake Havasu City", "Sierra Vista",
  "Henderson", "North Las Vegas", "Sparks", "Carson City",
  // Pacific
  "Berkeley", "Palo Alto",
  "Mountain View", "Sunnyvale", "Santa Clara", "Cupertino", "Fremont",
  "Hayward", "Redwood City", "San Mateo", "Santa Cruz", "Monterey",
  "Santa Barbara", "Ventura", "Oxnard", "Pasadena", "Long Beach",
  "Anaheim", "Irvine", "Riverside", "San Bernardino", "Ontario (CA)",
  "Bakersfield", "Fresno", "Stockton", "Modesto", "Visalia",
  "Chico", "Redding", "Eureka (CA)", "Santa Rosa", "Napa",
  "Vallejo", "Concord (CA)", "Walnut Creek", "Pleasanton",
  "Palm Springs", "Palm Desert", "Temecula", "Murrieta", "Escondido",
  "Carlsbad", "Oceanside", "Encinitas", "La Jolla",
  "Eugene", "Salem", "Bend", "Medford",
  "Corvallis", "Ashland", "Grants Pass", "Hillsboro", "Beaverton",
  "Tacoma", "Bellevue (WA)", "Redmond (WA)", "Everett",
  "Olympia", "Bellingham", "Yakima", "Kennewick",
  "Richland", "Walla Walla", "Pullman",
  "Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan",
  "Maui", "Hilo", "Kailua", "Pearl City",
  // DC metro
  "Bethesda", "Silver Spring", "Rockville",
  "College Park", "Annapolis", "Frederick (MD)", "Columbia (MD)",
  "Tysons Corner", "Reston", "McLean", "Falls Church",
];
