// Top 100 US News ranked universities (2026 edition) plus 400+ additional US colleges and universities
export const usnewsCollegeRankingsHints: string[] = [
  // Top 100
  "Princeton", "MIT", "Harvard", "Yale", "Stanford",
  "University of Chicago", "Johns Hopkins", "Northwestern", "Duke", "UPenn",
  "Caltech", "Cornell", "Brown", "Dartmouth", "UC Berkeley",
  "Columbia", "Vanderbilt", "UCLA", "Rice", "Washington University in St. Louis",
  "Carnegie Mellon", "University of Michigan", "Notre Dame", "Emory", "Georgetown",
  "UNC Chapel Hill", "University of Virginia", "USC", "UC San Diego", "University of Texas at Austin",
  "University of Florida", "NYU", "UC Davis", "Georgia Tech", "UC Irvine",
  "Tufts", "University of Illinois Urbana-Champaign", "University of Wisconsin-Madison", "Boston College", "UC Santa Barbara",
  "Ohio State", "Rutgers", "University of Maryland", "Boston University", "University of Washington",
  "Lehigh", "University of Rochester", "University of Georgia", "Purdue", "Northeastern",
  "Florida State", "Virginia Tech", "Texas A&M", "Wake Forest", "William & Mary",
  "Case Western Reserve", "Villanova", "UC Merced", "Penn State", "University of Minnesota",
  "SUNY Stony Brook", "Santa Clara University", "George Washington University", "Michigan State", "University of Massachusetts Amherst",
  "University of Miami", "NC State", "Rensselaer Polytechnic Institute", "University of Connecticut", "Brandeis",
  "University of Pittsburgh", "Tulane", "SUNY Binghamton", "Indiana University", "UC Riverside",
  "Clemson", "SUNY Buffalo", "Syracuse", "Rutgers Newark", "Colorado School of Mines",
  "New Jersey Institute of Technology", "Stevens Institute of Technology", "Drexel", "University of Illinois Chicago", "Yeshiva University",
  "Worcester Polytechnic Institute", "Pepperdine", "Marquette", "American University", "Baylor",
  "University of South Florida", "Rochester Institute of Technology", "SMU", "University of Delaware", "Howard",
  "UC Santa Cruz", "Fordham", "TCU", "Florida International University", "University of Colorado Boulder",
  // Beyond top 100 — Ivy League & top private
  "Williams", "Amherst", "Swarthmore", "Pomona",
  "Bowdoin", "Middlebury", "Wellesley", "Carleton", "Claremont McKenna",
  "Haverford", "Colby", "Hamilton", "Grinnell", "Davidson",
  "Colgate", "Harvey Mudd", "Wesleyan", "Vassar", "Bates",
  "Colorado College", "Oberlin", "Macalester", "Kenyon", "Bucknell",
  "Lafayette", "Whitman", "Reed", "Scripps", "Barnard",
  "Bryn Mawr", "Smith", "Mount Holyoke", "Trinity College", "Sewanee",
  "Connecticut College", "Union College", "Denison", "DePauw", "Furman",
  "Rhodes", "Centre", "Dickinson", "Gettysburg", "Franklin & Marshall",
  "Skidmore", "Sarah Lawrence", "Bennington", "Bard", "Hampshire",
  "St. Olaf", "Beloit", "Knox", "Lawrence University", "Wooster",
  "Wabash", "Earlham", "Kalamazoo", "Allegheny", "Juniata",
  // Other well-known private universities
  "Creighton", "Loyola University Chicago", "Catholic University",
  "Seton Hall", "Fairfield", "Providence College", "DePaul", "Duquesne",
  "University of San Diego", "University of San Francisco", "Regis University",
  "Rockhurst", "Xavier University", "Dayton", "St. Louis University",
  "Hofstra", "Adelphi", "Quinnipiac", "Sacred Heart", "Marist",
  "Elon", "High Point", "Rollins", "Stetson", "Mercer",
  "Samford", "Belmont", "Lipscomb",
  "Chapman", "Whitworth", "University of Puget Sound",
  "Pacific Lutheran", "Seattle University", "University of Portland",
  "Willamette", "Lewis & Clark", "Santa Clara",
  "University of the Pacific",
  // Engineering & tech schools
  "Rose-Hulman", "Olin College",
  "Cooper Union", "Illinois Institute of Technology",
  "Clarkson", "Kettering",
  "Missouri University of Science and Technology", "South Dakota School of Mines",
  "Michigan Technological University", "Montana Tech",
  // Service academies
  "West Point", "United States Military Academy", "Naval Academy",
  "United States Naval Academy", "Air Force Academy",
  "United States Air Force Academy", "Coast Guard Academy", "Merchant Marine Academy",
  // HBCUs
  "Morehouse", "Spelman", "Tuskegee", "Hampton", "Howard University",
  "Fisk", "Clark Atlanta", "Florida A&M", "North Carolina A&T",
  "Prairie View A&M", "Grambling State", "Southern University",
  "Jackson State", "Morgan State", "Delaware State", "Alcorn State",
  "Bethune-Cookman", "Dillard", "Xavier University of Louisiana",
  "Tougaloo", "Claflin", "Benedict", "Voorhees", "Philander Smith",
  "Alabama A&M", "Alabama State", "Tennessee State", "Norfolk State",
  "Virginia State", "South Carolina State", "Savannah State",
  "Coppin State", "Bowie State", "Lincoln University",
  "Langston University", "Texas Southern", "University of Arkansas Pine Bluff",
  "Winston-Salem State", "Elizabeth City State", "Fayetteville State",
  // Major state universities (University of X)
  "University of Alaska", "University of Arizona",
  "University of Arkansas",
  "University of Central Florida", "University of Colorado Denver",
  "University of Hawaii", "University of Idaho",
  "University of Indiana",
  "University of Louisiana Lafayette", "University of Louisiana Monroe",
  "University of Maine", "University of Massachusetts Boston",
  "University of Massachusetts Lowell", "University of Mississippi",
  "University of Missouri", "University of Montana", "University of Nevada Las Vegas",
  "University of Nevada Reno", "University of New Hampshire",
  "University of New Mexico", "University of North Carolina Charlotte",
  "University of North Carolina Greensboro", "University of North Carolina Wilmington",
  "University of North Dakota", "University of Rhode Island",
  "University of South Dakota",
  "University of Texas Arlington", "University of Texas Dallas",
  "University of Texas El Paso", "University of Texas San Antonio",
  "University of Toledo", "University of Tulsa",
  "University of Wisconsin Milwaukee", "University of Wyoming",
  // Other state flagships and major publics
  "Oregon State", "Washington State",
  "Colorado State", "Kansas State", "Mississippi State", "Oklahoma State",
  "Texas Tech", "Louisiana State University", "West Virginia University",
  "University of Houston", "George Mason University",
  "San Diego State", "San Jose State", "Fresno State",
  "Cal Poly San Luis Obispo", "Cal Poly Pomona",
  "California State University Northridge", "California State University Fullerton",
  "California State University Long Beach", "California State University Sacramento",
  "California State University Los Angeles", "California State University Dominguez Hills",
  "California State University San Bernardino", "California State University Bakersfield",
  "California State University Chico", "California State University East Bay",
  "California State University Stanislaus", "California State University Monterey Bay",
  "California State University Channel Islands", "California State University San Marcos",
  "Humboldt State", "Sonoma State",
  "SUNY Albany", "SUNY Geneseo", "SUNY Oswego",
  "SUNY Plattsburgh", "SUNY Potsdam", "SUNY New Paltz", "SUNY Oneonta",
  "SUNY Cortland", "SUNY Fredonia", "SUNY Brockport",
  "CUNY Baruch", "CUNY Hunter", "CUNY Brooklyn College", "CUNY Queens College",
  "CUNY City College", "CUNY John Jay", "CUNY Lehman",
  "Rutgers Camden",
  "University of Tennessee Chattanooga", "University of Tennessee Martin",
  "University of Alabama Birmingham", "University of Alabama Huntsville",
  "Georgia Southern", "Georgia State",
  "Eastern Kentucky", "Western Kentucky",
  "University of Louisville",
  "Ball State", "Indiana State", "Purdue Fort Wayne",
  "Eastern Michigan", "Western Michigan", "Central Michigan",
  "Northern Michigan", "Grand Valley State", "Wayne State",
  "Northern Illinois", "Southern Illinois", "Eastern Illinois", "Western Illinois",
  "Illinois State",
  "University of Northern Iowa", "University of Wisconsin La Crosse",
  "University of Wisconsin Eau Claire", "University of Wisconsin Oshkosh",
  "University of Wisconsin Stevens Point", "University of Wisconsin Whitewater",
  "University of Wisconsin Green Bay", "University of Wisconsin Stout",
  "University of Wisconsin Platteville", "University of Wisconsin River Falls",
  "Minnesota State Mankato", "Minnesota State Moorhead",
  "North Dakota State", "South Dakota State",
  "University of Northern Colorado", "University of Southern Mississippi",
  "Middle Tennessee State", "East Tennessee State",
  "Appalachian State", "University of North Carolina Asheville",
  "James Madison", "Old Dominion", "Radford",
  "George Mason", "College of William & Mary",
  "University of Mary Washington",
  "Towson", "Salisbury",
  "Providence", "Bryant",
  "Stonehill", "Assumption", "Merrimack", "Bentley",
  "Babson", "Olin", "WPI", "Clark University",
  "College of the Holy Cross", "Wheaton College Massachusetts",
  "Emerson", "Simmons", "Lesley", "Suffolk",
  "Roger Williams", "Salve Regina",
  "Ithaca College", "St. Lawrence University", "Hobart and William Smith",
  "Siena", "Le Moyne", "Niagara", "Canisius", "St. Bonaventure",
  "Manhattan College", "Pace University", "New School", "Pratt Institute",
  "Parsons", "FIT", "School of Visual Arts", "Juilliard",
  "Berklee College of Music", "New England Conservatory",
  "Oberlin Conservatory", "Eastman School of Music",
  "Kennesaw State", "University of West Georgia",
  "Jacksonville State", "Troy University",
  "Florida Atlantic", "Florida Gulf Coast", "University of North Florida",
  "University of West Florida",
  "Saginaw Valley State", "Ferris State", "Lake Superior State",
  "Bowling Green State", "Kent State", "Miami University",
  "Ohio University", "University of Akron", "University of Cincinnati",
  "Wright State", "Youngstown State", "Cleveland State",
  "Marshall University", "Shepherd University",
  // Additional well-known schools
  "University of Iowa", "University of Oregon", "University of Nebraska",
  "Iowa State", "University of Oklahoma", "University of Kentucky",
  "Arizona State", "University of Utah", "Auburn",
  "University of South Carolina", "Temple", "University of Alabama",
  "University of Tennessee", "University of Kansas",
  "Gonzaga", "Loyola Marymount", "University of Denver",
  "University of Vermont",
];
